In [ ]:
import pandas as pd
import os

In [ ]:
!ls

drive  sample_data

In [ ]:
NETSCI_WORDNET_PATH = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NetSci Team/wordnet_entries_v3"

In [ ]:
json_files = [NETSCI_WORDNET_PATH + "/" + json_file for json_file in os.listdir(NETSCI_WORDNET_PATH)]
json_files

In [ ]:
%%time
from tqdm import tqdm

files = []
for file in tqdm(json_files[1000:1500]):
  files.append(pd.read_json(file, orient='index').transpose())

wordnet = pd.concat(files)
wordnet

100%|██████████| 500/500 [02:17<00:00,  3.63it/s]

CPU times: user 2.27 s, sys: 146 ms, total: 2.41 s
Wall time: 2min 17s

,sense_id,word,synset_id,community,example_sentences,contextual_info
0,ns_samson_3,samson,118,"[bukid, nasabing, barangay, road, residente, k...","[Jemar Modequillo , nagsagawa ng Oplan Sita an...","{'news_sites': {'abante': {'2020': 3, '2021': ..."
0,ns_samuel_0,samuel,7984,"[city, justice, gabi, barangay, philippine, po...","[Ayon sa ulat ng dzBB radio nitong Biyernes , ...","{'books': {'100year': {'1908': 2, '1976': 30, ..."
0,ns_samuel_1,samuel,7985,"[buhay, hirap, bagay, puso, pilipinas, araw, s...",[10 At isinaysay ni Samuel ang buong salita ng...,"{'books': {'100year': {'1902': 1, '1907': 1, '..."
0,ns_samuel_2,samuel,7986,"[kuwento, star, nina, michael, karakter, holly...","[Mula nang umere noong Marso , tinutukan ng vi...","{'news_sites': {'abante': {'2021': 1}, 'balita..."
0,ns_samuel_3,samuel,170,"[namatay, biktima, driver, lalaki, matapos, it...","[Ang mga namatay ay sila Hannah Castro , 16-an...","{'books': {'100year': {'1976': 7}, 'bible': {'..."
...,...,...,...,...,...,...
0,ns_sombrero_2,sombrero,122,"[lalaki, sakay, dalawang, lalaking, motorsiklo]","[Nakita niyang nasok , ay dalawang lalaki , na...","{'books': {'100year': {'1909': 1, '1912': 1, '..."
0,ns_sopas_0,sopas,8364,"[magluto, masarap, kumain, sinigang, kumakain,...",[Champorado nalang daw sabi ko di ako kumakain...,"{'books': {'100year': {'1902': 4, '1909': 1, '..."
0,ns_sopas_1,sopas,8365,"[lagyan, ung, tapos, kapatid, baka, pala, nana...",[Ung gusto ko kahapon ng sopas or champorado ....,"{'news_sites': {'abante': {'2021': 1}}, 'onlin..."
0,ns_sopas_2,sopas,8366,"[parang, sakit, panahon, kape, sarap, malamig,...",[XX_EMOJI XX_EMOJI Kapag ganito ang panahon pa...,"{'books': {'100year': {'2001': 1, '2006': 1}, ..."
0,ns_sopas_3,sopas,13,"[sana, nalang, salamat, nakapag, today, hotdog...",[Di talaga sopas ang sopas pag walang hotdog ....,{'social_media': {'twitter': {'2021': 32}}}

In [ ]:
ns_wordnet = pd.concat(files).reset_index(drop=True)
to_drop = ns_wordnet.loc[ns_wordnet.example_sentences.apply(type) != list].index.values # drop empty example sentences
ns_wordnet = ns_wordnet.drop(to_drop).reset_index(drop=True)
ns_wordnet

,sense_id,word,synset_id,community,example_sentences,contextual_info
0,ns_samson_3,samson,118,"[bukid, nasabing, barangay, road, residente, k...","[Jemar Modequillo , nagsagawa ng Oplan Sita an...","{'news_sites': {'abante': {'2020': 3, '2021': ..."
1,ns_samuel_0,samuel,7984,"[city, justice, gabi, barangay, philippine, po...","[Ayon sa ulat ng dzBB radio nitong Biyernes , ...","{'books': {'100year': {'1908': 2, '1976': 30, ..."
2,ns_samuel_1,samuel,7985,"[buhay, hirap, bagay, puso, pilipinas, araw, s...",[10 At isinaysay ni Samuel ang buong salita ng...,"{'books': {'100year': {'1902': 1, '1907': 1, '..."
3,ns_samuel_2,samuel,7986,"[kuwento, star, nina, michael, karakter, holly...","[Mula nang umere noong Marso , tinutukan ng vi...","{'news_sites': {'abante': {'2021': 1}, 'balita..."
4,ns_samuel_3,samuel,170,"[namatay, biktima, driver, lalaki, matapos, it...","[Ang mga namatay ay sila Hannah Castro , 16-an...","{'books': {'100year': {'1976': 7}, 'bible': {'..."
...,...,...,...,...,...,...
494,ns_sombrero_2,sombrero,122,"[lalaki, sakay, dalawang, lalaking, motorsiklo]","[Nakita niyang nasok , ay dalawang lalaki , na...","{'books': {'100year': {'1909': 1, '1912': 1, '..."
495,ns_sopas_0,sopas,8364,"[magluto, masarap, kumain, sinigang, kumakain,...",[Champorado nalang daw sabi ko di ako kumakain...,"{'books': {'100year': {'1902': 4, '1909': 1, '..."
496,ns_sopas_1,sopas,8365,"[lagyan, ung, tapos, kapatid, baka, pala, nana...",[Ung gusto ko kahapon ng sopas or champorado ....,"{'news_sites': {'abante': {'2021': 1}}, 'onlin..."
497,ns_sopas_2,sopas,8366,"[parang, sakit, panahon, kape, sarap, malamig,...",[XX_EMOJI XX_EMOJI Kapag ganito ang panahon pa...,"{'books': {'100year': {'2001': 1, '2006': 1}, ..."
498,ns_sopas_3,sopas,13,"[sana, nalang, salamat, nakapag, today, hotdog...",[Di talaga sopas ang sopas pag walang hotdog ....,{'social_media': {'twitter': {'2021': 32}}}

In [ ]:
NLP_WORDNET_PATH = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/filwordnet.pkl"

In [ ]:
nlp_wordnet = pd.read_pickle(NLP_WORDNET_PATH)

In [ ]:
nlp_wordnet

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD

In [ ]:
nlp_wordnet.iloc[0]['sense_embedding']

In [ ]:
!pip install sentence_transformers -q

     |████████████████████████████████| 85 kB 4.6 MB/s
     |████████████████████████████████| 5.5 MB 71.4 MB/s
     |████████████████████████████████| 1.3 MB 57.4 MB/s
     |████████████████████████████████| 163 kB 75.6 MB/s
     |████████████████████████████████| 7.6 MB 57.9 MB/s
  Building wheel for sentence-transformers (setup.py) ... done

In [ ]:
from sentence_transformers import SentenceTransformer

MODEL_DIR = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/models"

model = SentenceTransformer(f'{MODEL_DIR}/sroberta-nli-1epoch')
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: RobertaModel
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)


WSD:
*  for each word
    * if cos(nlp[word].senseembeddings, ns[word].senseembeddings) <= threshold
        * concat(nlp[word], ns[word])

In [ ]:
ns_wordnet.head()

,sense_id,word,synset_id,community,example_sentences,contextual_info
0,ns_tanggalin_2,tanggalin,8771,"[mahirap, buhay, kailangan, kasama, tao, natin...",[Dahil sa Kanyang paghatol at pagkastigo tayo ...,"{'books': {'100year': {'1986': 1, '2003': 1}, ..."
1,ns_tanggalin_3,tanggalin,8772,"[pork, batas, pwesto, plano, sakaling, tax, go...",[Hiniling ni Senator Miriam Defensor-Santiago ...,"{'news_sites': {'abante': {'2020': 11, '2021':..."
2,ns_tanggapan_0,tanggapan,8773,"[kailangan, kasama, pera, tao, natin, bayan, p...",[Inihayag ng Palasyo na suspendido ang pasok s...,"{'books': {'100year': {'1902': 2, '1908': 3, '..."
3,ns_tanggapan_1,tanggapan,144,"[regional, community, bir, sss, office, group,...",[Lumutang na sa tanggapan ng National Bureau o...,"{'news_sites': {'abante': {'2020': 32, '2021':..."
4,ns_tanggapan_2,tanggapan,525,"[kongreso, aquino, senator, bumisita, kasaluku...",[Sinabi ng tanggapan ni Vice President Leni Ro...,"{'books': {'100year': {'1937': 1, '1956': 1, '..."

In [ ]:
nlp_wordnet.head()

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos,synset_id
0,matino,matino_0,[ 3.92004242e-03 3.12551409e-02 4.41497937e-...,"['halatang wala ka ng gagawing matino HAHAHA',...",{'twitter': {'2021': 10}},FW,44
1,matino,matino_1,[ 1.42582236e-02 -7.32653495e-03 4.27205190e-...,['May mga magulang na matino ang isip at kataw...,"{'google_books': {'2018': 2}, 'twitter': {'202...",FW,2393
2,matino,matino_2,[ 5.81043446e-03 -2.38136970e-03 4.27450798e-...,"['ng pelikula. Maganda at matino.', 'kasama sa...","{'bandera': {'2014': 2, '2018': 2, '2021': 1, ...",VB,685
3,matino,matino_3,[-7.02383462e-03 1.44386766e-02 2.91953124e-...,"['akong sinabing matino.', 'Duda ako sa matino...","{'twitter': {'2021': 7}, 'bandera': {'2020': 1...",NN,357
4,maayos,maayos_0,[ 1.02245081e-02 2.21954919e-02 5.89414425e-...,"['buti nalang nakasagot naman ng maayos.', 'sa...",{'twitter': {'2021': 10}},JJ,260

In [ ]:
import torch

def text_to_embs(sentence_list_texts):
    sentence_embeddings = model.encode(sentence_list_texts, show_progress_bar=False, normalize_embeddings=True)

    return torch.tensor(sentence_embeddings)

def mean_embs(sentence_embs):
    sense_embeddings = torch.mean(sentence_embs, dim=0)

    return sense_embeddings

def get_sentence_embs_df(df):
    df['sense_embeddings'] = None

    for idx, row in df.iterrows():
        # get example sentences
        sentence_list_texts = row['example_sentences']

        # encode to sentence embeddings
        sentence_embeddings = text_to_embs(sentence_list_texts)

        # mean sentence embeddings
        sense_embeddings = mean_embs(sentence_embeddings)

        # append sense embeddings to dataframe row
        row['sense_embeddings'] = sense_embeddings

    return df

In [ ]:
ns_wordnet = get_sentence_embs_df(ns_wordnet)
ns_wordnet

,sense_id,word,synset_id,community,example_sentences,contextual_info,sense_embeddings
0,ns_samson_3,samson,118,"[bukid, nasabing, barangay, road, residente, k...","[Jemar Modequillo , nagsagawa ng Oplan Sita an...","{'news_sites': {'abante': {'2020': 3, '2021': ...","[tensor(0.0387), tensor(0.0088), tensor(-0.020..."
1,ns_samuel_0,samuel,7984,"[city, justice, gabi, barangay, philippine, po...","[Ayon sa ulat ng dzBB radio nitong Biyernes , ...","{'books': {'100year': {'1908': 2, '1976': 30, ...","[tensor(0.0214), tensor(-0.0238), tensor(-0.00..."
2,ns_samuel_1,samuel,7985,"[buhay, hirap, bagay, puso, pilipinas, araw, s...",[10 At isinaysay ni Samuel ang buong salita ng...,"{'books': {'100year': {'1902': 1, '1907': 1, '...","[tensor(-0.0153), tensor(0.0519), tensor(0.029..."
3,ns_samuel_2,samuel,7986,"[kuwento, star, nina, michael, karakter, holly...","[Mula nang umere noong Marso , tinutukan ng vi...","{'news_sites': {'abante': {'2021': 1}, 'balita...","[tensor(-0.0080), tensor(0.0159), tensor(0.035..."
4,ns_samuel_3,samuel,170,"[namatay, biktima, driver, lalaki, matapos, it...","[Ang mga namatay ay sila Hannah Castro , 16-an...","{'books': {'100year': {'1976': 7}, 'bible': {'...","[tensor(0.0246), tensor(-0.0210), tensor(-0.00..."
...,...,...,...,...,...,...,...
494,ns_sombrero_2,sombrero,122,"[lalaki, sakay, dalawang, lalaking, motorsiklo]","[Nakita niyang nasok , ay dalawang lalaki , na...","{'books': {'100year': {'1909': 1, '1912': 1, '...","[tensor(0.0121), tensor(0.0184), tensor(-0.013..."
495,ns_sopas_0,sopas,8364,"[magluto, masarap, kumain, sinigang, kumakain,...",[Champorado nalang daw sabi ko di ako kumakain...,"{'books': {'100year': {'1902': 4, '1909': 1, '...","[tensor(0.0043), tensor(0.0405), tensor(0.0296..."
496,ns_sopas_1,sopas,8365,"[lagyan, ung, tapos, kapatid, baka, pala, nana...",[Ung gusto ko kahapon ng sopas or champorado ....,"{'news_sites': {'abante': {'2021': 1}}, 'onlin...","[tensor(-0.0035), tensor(0.0456), tensor(0.023..."
497,ns_sopas_2,sopas,8366,"[parang, sakit, panahon, kape, sarap, malamig,...",[XX_EMOJI XX_EMOJI Kapag ganito ang panahon pa...,"{'books': {'100year': {'2001': 1, '2006': 1}, ...","[tensor(0.0226), tensor(0.0385), tensor(-0.021..."
498,ns_sopas_3,sopas,13,"[sana, nalang, salamat, nakapag, today, hotdog...",[Di talaga sopas ang sopas pag walang hotdog ....,{'social_media': {'twitter': {'2021': 32}}},"[tensor(-0.0004), tensor(0.0332), tensor(0.013..."

In [ ]:
nlp_wordnet = get_sentence_embs_df(nlp_wordnet)
nlp_wordnet

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos,sense_embeddings
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...",NN,"[tensor(0.0114), tensor(0.0058), tensor(-0.008..."
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN,"[tensor(0.0352), tensor(0.0621), tensor(0.0185..."
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN,"[tensor(0.0182), tensor(0.0152), tensor(0.0200..."
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ,"[tensor(0.0139), tensor(0.0176), tensor(0.0183..."
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB,"[tensor(-0.0038), tensor(0.0338), tensor(0.021..."
...,...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN,"[tensor(0.0238), tensor(0.0431), tensor(0.0439..."
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN,"[tensor(-0.0269), tensor(-0.0207), tensor(0.04..."
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN,"[tensor(0.0132), tensor(0.0138), tensor(0.0390..."
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN,"[tensor(0.0087), tensor(0.0009), tensor(0.0586..."
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD,"[tensor(0.0246), tensor(0.0117), tensor(0.0464..."

In [ ]:
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-08)

In [ ]:
import torch
import torch.nn.functional as F

def merge_wn(nlp_wn, ns_wn, thres):
    new_wn = pd.DataFrame()
    new_wn['merge_label'] = None

    # Initialize 
    cos = torch.nn.CosineSimilarity(dim=1, eps=1e-08)

    # Get vocab intersection
    nlp_vocab = set(nlp_wn['word'].tolist())
    ns_vocab = set(ns_wn['word'].tolist())
    vocab_combined = nlp_vocab.intersection(ns_vocab)  

    for w in vocab_combined:
        ns_rows = ns_wn.loc[ns_wn['word'] == w]
        nlp_rows = nlp_wn.loc[nlp_wn['word'] == w]

        try:
            ns_se = torch.stack(ns_rows['sense_embeddings'].tolist())
        except:
            print(w)
            print(len(ns_rows['sense_embeddings'].tolist()))
            print(ns_rows['sense_embeddings'].tolist())
            print([t.shape for t in ns_rows['sense_embeddings'].tolist()])

        nlp_se = torch.stack(nlp_rows['sense_embeddings'].tolist())
        
        # cosine similarity = normalize the vectors & multiply
        similarity_matrix = F.normalize(nlp_se) @ F.normalize(ns_se).t()

        max_values, indices = torch.max(similarity_matrix, dim=1)


        # apply threshold
        for idx, mv in enumerate(max_values):
            if mv < thres: # below threshold, append row
                indices[idx] = -1 # sentinel value, marks the rows that will be ignored later

        for idx_nlp, idx_ns in enumerate(indices):
            idx_ns_scalar = idx_ns.item()
            
            if idx_ns_scalar != -1:
                row_nlp = nlp_rows.iloc[idx_nlp].append(pd.Series({'merge_label': idx_ns_scalar}))
                new_wn = new_wn.append(row_nlp, ignore_index=True)
                row_ns = ns_rows.iloc[idx_ns_scalar].append(pd.Series({'merge_label': idx_ns_scalar}))
                new_wn = new_wn.append(row_ns, ignore_index=True)
            else:
                row_nlp = nlp_rows.iloc[idx_nlp].append(pd.Series({'merge_label': -1})) # -1 means no group
                new_wn = new_wn.append(row_nlp, ignore_index=True)
        
        sense_ids = new_wn['sense_id'].tolist()
        ns_sense_ids = [id for id in sense_ids if "ns" in id]

        for idx, row_ns in ns_rows.iterrows():
            if row_ns['sense_id'] not in ns_sense_ids:
                row_ns = row_ns.append(pd.Series({'merge_label': -1})) # -1 means no group
                new_wn = new_wn.append(row_ns, ignore_index=True)


    # drop duplicates
    #new_wn = new_wn.drop_duplicates()
    new_wn = new_wn.drop_duplicates(subset=['sense_id']).reset_index(drop=True)

    return new_wn

In [ ]:
new_wn = merge_wn(nlp_wordnet, ns_wordnet, 0.4)
new_wn

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word,community,synset_id
0,2,"{'twitter': {'2021': 9}, 'google_books': {'201...",[naglalabasan mga pictures na mukhang sinumpa ...,FW,"[-0.009288171, 0.03410301, 0.048074644, -0.002...","[tensor(-0.0093), tensor(0.0341), tensor(0.048...",sinumpa_0,sinumpa,NaN,NaN
1,2,"{'books': {'100year': {'1974': 1}, 'bible': {'...",[sinumpa ata ako ng last ex ko bat diko pa kay...,NaN,NaN,"[tensor(-0.0021), tensor(0.0230), tensor(0.025...",ns_sinumpa_2,sinumpa,"[parang, ata, kasalanan, bat, yata, sumpa, pin...",128
2,1,"{'bible': {'0': 4}, 'twitter': {'2021': 1}}",[umuunlad : nguni't agad kong sinumpa ang kani...,VB,"[-0.02514634, 0.023591122, 0.056542564, 0.0149...","[tensor(-0.0251), tensor(0.0236), tensor(0.056...",sinumpa_1,sinumpa,NaN,NaN
3,1,"{'books': {'100year': {'1937': 1}, 'bible': {'...","[Noong mga taga-serbisyo sila , maraming tao a...",NaN,NaN,"[tensor(0.0025), tensor(0.0146), tensor(0.0199...",ns_sinumpa_1,sinumpa,"[buhay, tao, puso, taong, diyos, bibig, salita...",192
4,-1,"{'books': {'100year': {'1908': 2, '1909': 1, '...",[XX_USERNAME Sinumpa ako nung ex ko yata di na...,NaN,NaN,"[tensor(-0.0171), tensor(0.0451), tensor(0.023...",ns_sinumpa_0,sinumpa,"[kasama, sana, araw, baka, lalaki, lupang, nak...",8287
...,...,...,...,...,...,...,...,...,...,...
627,1,"{'gma': {'2017': 1, '2012': 4}, 'google_books'...","[Bautista ang naturang mga seksyon ng batas, p...",NN,"[0.038094662, -0.01623686, 0.01190753, -0.0223...","[tensor(0.0381), tensor(-0.0162), tensor(0.011...",seksyon_0,seksyon,NaN,NaN
628,1,"{'news_sites': {'abante': {'2020': 2, '2021': ...","[Nakasaad ito sa Artikulo 14 Seksyon 6 ., Naka...",NaN,NaN,"[tensor(0.0145), tensor(0.0226), tensor(0.0215...",ns_seksyon_1,seksyon,"[batas, nakasaad, artikulo]",8082
629,1,"{'twitter': {'2021': 8}, 'abante': {'2020': 1}...","[na di ako kabilang sa seksyon., ang iyong sag...",NN,"[0.036451794, 0.030192232, 0.033836287, -0.053...","[tensor(0.0365), tensor(0.0302), tensor(0.0338...",seksyon_1,seksyon,NaN,NaN
630,-1,"{'books': {'100year': {'2004': 1}, 'google_boo...",[Ang Diyos ay parehong nagpapatuloy sa gawain ...,NaN,NaN,"[tensor(0.0136), tensor(0.0010), tensor(-0.003...",ns_seksyon_0,seksyon,"[kalsada, dalawang, gawain, bahagi, silangang]",8081
631,-1,"{'news_sites': {'abscbn': {'2021': 1}, 'balita...",[Kasong paglabag sa Seksyon 5 at Seksyon 11 ng...,NaN,NaN,"[tensor(0.0378), tensor(-0.0122), tensor(-0.00...",ns_seksyon_2,seksyon,"[kasong, paglabag, comprehensive]",511

In [ ]:
#
# NOT YET SURE HOW TO HANDLE COMMUNITY AND POS
#
def aggregate_metadata(wn):
    vocab = list(set(new_wn['word'].values))
    cols = ['word', 'sense_id', 'example_sentences', 'contextual_info']
    df_res = pd.DataFrame(columns=cols)

    for w in vocab[2:3]:
        df_w = wn[wn['word'] == w]
        display(df_w)
        group_labels = list(set(df_w['merge_label'].values.tolist()))

        for idx, group in enumerate(group_labels):
            df_group = df_w[df_w['merge_label'] == group]

            if group == -1:
                df_res = df_res.append(df_group[cols])
            else:
                row = {}
                contextual_info = df_group['contextual_info'].values
                example_sentences = df_group['example_sentences'].values
                combined_contextual_info = aggregate_contextual_info(contextual_info)
                combined_example_sentences = aggregate_contextual_info(example_sentences)
                
                row['word'] = w
                row['sense_id'] = f"new_{w}_{idx}"
                row['example_sentences'] = combined_example_sentences
                row['contextual_info'] = combined_contextual_info

                df_res = df_res.append(row, ignore_index=True)
    
    df_res = df_res.reset_index(drop=True)

                
            
            


    return df_res

In [ ]:
aggregate_metadata(new_wn)

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word,community,synset_id
12,0,{'twitter': {'2021': 10}},"[la kam giyapon naundang pamalit sigarilyo, ka...",NN,"[-0.03195212, -0.022939313, 0.02492847, 0.0025...","[tensor(-0.0319), tensor(-0.0229), tensor(0.02...",sigarilyo_0,sigarilyo,NaN,NaN
13,0,"{'books': {'100year': {'1902': 2, '1907': 3, '...",[Ilang mga bata ang pinagsuot ng uniporme at s...,NaN,NaN,"[tensor(0.0089), tensor(0.0132), tensor(0.0122...",ns_sigarilyo_0,sigarilyo,"[buhay, kasama, tapos, pera, tao, pati, sana, ...",8167
14,2,"{'twitter': {'2021': 1}, 'radyoinquirer': {'20...","[maliit na pakete ng sigarilyo., ang kargado n...",NN,"[-0.020460006, 0.005703236, -0.015030688, 0.00...","[tensor(-0.0205), tensor(0.0057), tensor(-0.01...",sigarilyo_1,sigarilyo,NaN,NaN
15,2,"{'news_sites': {'abante': {'2020': 21, '2021':...",[Tinatayang aabot sa P160 milyong halaga ng um...,NaN,NaN,"[tensor(-0.0329), tensor(-0.0029), tensor(-0.0...",ns_sigarilyo_2,sigarilyo,"[nagbebenta, ipinagbabawal, halaga, million, p...",8169
16,-1,"{'news_sites': {'abante': {'2020': 8, '2021': ...",[Winasak ng Bureau of Customs ( BOC ) – Port o...,NaN,NaN,"[tensor(-0.0186), tensor(-0.0037), tensor(-0.0...",ns_sigarilyo_1,sigarilyo,"[mataas, lugar, pilipinas, nasabing, bansa, it...",8168
17,-1,"{'books': {'100year': {'1902': 1, '1922': 1, '...","[Tatlong tao , kabilang ang dalawang menor de ...",NaN,NaN,"[tensor(-0.0082), tensor(-0.0140), tensor(-0.0...",ns_sigarilyo_3,sigarilyo,"[biktima, lalaki, sakay, sasakyan, matapos, it...",183

,word,sense_id,example_sentences,contextual_info
0,sigarilyo,new_sigarilyo_0,"[la kam giyapon naundang pamalit sigarilyo, ka...","[twitter, books, news_sites, online_forums, so..."
1,sigarilyo,new_sigarilyo_1,"[maliit na pakete ng sigarilyo., ang kargado n...","[twitter, radyoinquirer, balita, gma, news_sit..."
2,sigarilyo,ns_sigarilyo_1,[Winasak ng Bureau of Customs ( BOC ) – Port o...,"{'news_sites': {'abante': {'2020': 8, '2021': ..."
3,sigarilyo,ns_sigarilyo_3,"[Tatlong tao , kabilang ang dalawang menor de ...","{'books': {'100year': {'1902': 1, '1922': 1, '..."

In [ ]:
df = pd.DataFrame(columns=['word', 'sense_id', 'example_sentences', 'contextual_info', 'sense_embeddings', 'community'])
df

Empty DataFrame
Columns: [word, sense_id, example_sentences, contextual_info, sense_embeddings, community]
Index: []

In [ ]:
df = df.append(test.iloc[0][['word', 'sense_id', 'example_sentences', 'contextual_info', 'sense_embeddings', 'community']])
df

,word,sense_id,example_sentences,contextual_info,sense_embeddings,community
0,sinumpa,sinumpa_0,[naglalabasan mga pictures na mukhang sinumpa ...,"{'twitter': {'2021': 9}, 'google_books': {'201...","[tensor(-0.0093), tensor(0.0341), tensor(0.048...",NaN

In [ ]:
test = aggregate_metadata(new_wn)
test

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word,community,synset_id
0,2,"{'twitter': {'2021': 9}, 'google_books': {'201...",[naglalabasan mga pictures na mukhang sinumpa ...,FW,"[-0.009288171, 0.03410301, 0.048074644, -0.002...","[tensor(-0.0093), tensor(0.0341), tensor(0.048...",sinumpa_0,sinumpa,NaN,NaN
1,2,"{'books': {'100year': {'1974': 1}, 'bible': {'...",[sinumpa ata ako ng last ex ko bat diko pa kay...,NaN,NaN,"[tensor(-0.0021), tensor(0.0230), tensor(0.025...",ns_sinumpa_2,sinumpa,"[parang, ata, kasalanan, bat, yata, sumpa, pin...",128
2,1,"{'bible': {'0': 4}, 'twitter': {'2021': 1}}",[umuunlad : nguni't agad kong sinumpa ang kani...,VB,"[-0.02514634, 0.023591122, 0.056542564, 0.0149...","[tensor(-0.0251), tensor(0.0236), tensor(0.056...",sinumpa_1,sinumpa,NaN,NaN
3,1,"{'books': {'100year': {'1937': 1}, 'bible': {'...","[Noong mga taga-serbisyo sila , maraming tao a...",NaN,NaN,"[tensor(0.0025), tensor(0.0146), tensor(0.0199...",ns_sinumpa_1,sinumpa,"[buhay, tao, puso, taong, diyos, bibig, salita...",192
4,-1,"{'books': {'100year': {'1908': 2, '1909': 1, '...",[XX_USERNAME Sinumpa ako nung ex ko yata di na...,NaN,NaN,"[tensor(-0.0171), tensor(0.0451), tensor(0.023...",ns_sinumpa_0,sinumpa,"[kasama, sana, araw, baka, lalaki, lupang, nak...",8287

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word,community,synset_id
0,2,"{'twitter': {'2021': 9}, 'google_books': {'201...",[naglalabasan mga pictures na mukhang sinumpa ...,FW,"[-0.009288171, 0.03410301, 0.048074644, -0.002...","[tensor(-0.0093), tensor(0.0341), tensor(0.048...",sinumpa_0,sinumpa,NaN,NaN
1,2,"{'books': {'100year': {'1974': 1}, 'bible': {'...",[sinumpa ata ako ng last ex ko bat diko pa kay...,NaN,NaN,"[tensor(-0.0021), tensor(0.0230), tensor(0.025...",ns_sinumpa_2,sinumpa,"[parang, ata, kasalanan, bat, yata, sumpa, pin...",128
2,1,"{'bible': {'0': 4}, 'twitter': {'2021': 1}}",[umuunlad : nguni't agad kong sinumpa ang kani...,VB,"[-0.02514634, 0.023591122, 0.056542564, 0.0149...","[tensor(-0.0251), tensor(0.0236), tensor(0.056...",sinumpa_1,sinumpa,NaN,NaN
3,1,"{'books': {'100year': {'1937': 1}, 'bible': {'...","[Noong mga taga-serbisyo sila , maraming tao a...",NaN,NaN,"[tensor(0.0025), tensor(0.0146), tensor(0.0199...",ns_sinumpa_1,sinumpa,"[buhay, tao, puso, taong, diyos, bibig, salita...",192
4,-1,"{'books': {'100year': {'1908': 2, '1909': 1, '...",[XX_USERNAME Sinumpa ako nung ex ko yata di na...,NaN,NaN,"[tensor(-0.0171), tensor(0.0451), tensor(0.023...",ns_sinumpa_0,sinumpa,"[kasama, sana, araw, baka, lalaki, lupang, nak...",8287

In [ ]:
# test case for different sources, different years aggergation
contextual_info = test.iloc[3:]['contextual_info'].values
contextual_info

array([{'books': {'100year': {'1937': 1}, 'bible': {'0': 2}, 'google_books': {'2018': 11, '2019': 12}, 'gutenberg': {'1913': 1}}, 'social_media': {'twitter': {'2021': 12}}},
       {'books': {'100year': {'1908': 2, '1909': 1, '1945': 2, '2007': 1}, 'bible': {'0': 5}, 'google_books': {'2019': 2, '2021': 1}, 'gutenberg': {'1906': 1, '1921': 1}}, 'news_sites': {'abante': {'2021': 1}, 'bandera': {'2010': 1, '2017': 1, '2020': 1}, 'gma': {'2008': 1}}, 'social_media': {'twitter': {'2021': 63}}}],
      dtype=object)

In [ ]:
# test case for same year increment
contextual_info = [{'books': {'100year': {'1937': 1}, 'bible': {'0': 2}, 'google_books': {'2018': 11, '2019': 12}, 'gutenberg': {'1913': 1}}, 'social_media': {'twitter': {'2021': 12}}}] * 2
contextual_info

[{'books': {'100year': {'1937': 1},
   'bible': {'0': 2},
   'google_books': {'2018': 11, '2019': 12},
   'gutenberg': {'1913': 1}},
  'social_media': {'twitter': {'2021': 12}}},
 {'books': {'100year': {'1937': 1},
   'bible': {'0': 2},
   'google_books': {'2018': 11, '2019': 12},
   'gutenberg': {'1913': 1}},
  'social_media': {'twitter': {'2021': 12}}}]

In [ ]:
def aggregate_contextual_info(contextual_info_lst):
    res = {}
    for i in contextual_info_lst:
        for k_sourcetype in i:
            v_sourcetype = i[k_sourcetype]
            # print(k_sourcetype)
            # print(f"    {v_sourcetype}")

            if k_sourcetype not in res: # first time
                res[k_sourcetype] = {}

            for k_source in v_sourcetype:
                v_source = v_sourcetype[k_source]
                # print(f"        {k_source}")
                # print(f"        {v_source}")

                if k_source not in res[k_sourcetype]: # first time
                    res[k_sourcetype][k_source] = {}

                for k_year in v_source:
                    v_year = v_source[k_year]
                    # print(f"            {k_year}")
                    # print(f"            {v_year}")

                    if k_year not in res[k_sourcetype][k_source]: # first time
                        res[k_sourcetype][k_source][k_year] = v_year
                    else:
                        res[k_sourcetype][k_source][k_year] += v_year
                        
    return res

In [ ]:
aggregate_contextual_info(contextual_info)

{'books': {'100year': {'1937': 1, '1908': 2, '1909': 1, '1945': 2, '2007': 1},
  'bible': {'0': 7},
  'google_books': {'2018': 11, '2019': 14, '2021': 1},
  'gutenberg': {'1913': 1, '1906': 1, '1921': 1}},
 'social_media': {'twitter': {'2021': 75}},
 'news_sites': {'abante': {'2021': 1},
  'bandera': {'2010': 1, '2017': 1, '2020': 1},
  'gma': {'2008': 1}}}

In [ ]:
# test case for example_sentences aggeragtion
example_sentences = test.iloc[:2]['example_sentences'].values
example_sentences

array([list(['naglalabasan mga pictures na mukhang sinumpa hahahaha.', 'yan emz HAHAHAHA sinumpa na', 'sinumpa yata ako ng mga may', 'ilang tao na yung sinumpa ko tapos nagkatotoo haha sori', 'tabginang yan sinumpa ko sa sarii ko never akong', 'talaga may sala mare sinumpa mo ko HAHAHAHAHAHAHAHA', 'mukhang sinumpa ako ni simp ah bigla', 'sinumpa ko na ang unfair naman binlock', 'Yan tuloy sinumpa ang show nyo.', 'pinarusahan at sinumpa.']),
       list(['sinumpa ata ako ng last ex ko bat diko pa kaya kumilala ng iba', 'sinumpa ata ako sa 41 ?', 'Sinumpa at pinarusahan sila ng Diyos dahil dito .', "Parang sinumpa mo na kasi ang isang tao , kapag 'yun ang sinabi mo , di ba ?", 'Sinumpa ata ako sa spike rush', 'sinumpa yata ako ng mga may galit sakin hahaha', 'kasalanan to ni sai , sinumpa ang joshtin XX_URL', 'sinumpa ba yung acc ko ngayon bat ang malas XX_EMOJI', 'pukingina sinumpa na yata ako ng cod', 'Tangina sinumpa rin ata ako ng gin .'])],
      dtype=object)

In [ ]:
def aggregate_contextual_info(example_sentences_lst):
    res = []
    for lst in example_sentences_lst:
        res += lst
    
    return res

In [ ]:
aggregate_contextual_info(example_sentences)

['naglalabasan mga pictures na mukhang sinumpa hahahaha.',
 'yan emz HAHAHAHA sinumpa na',
 'sinumpa yata ako ng mga may',
 'ilang tao na yung sinumpa ko tapos nagkatotoo haha sori',
 'tabginang yan sinumpa ko sa sarii ko never akong',
 'talaga may sala mare sinumpa mo ko HAHAHAHAHAHAHAHA',
 'mukhang sinumpa ako ni simp ah bigla',
 'sinumpa ko na ang unfair naman binlock',
 'Yan tuloy sinumpa ang show nyo.',
 'pinarusahan at sinumpa.',
 'sinumpa ata ako ng last ex ko bat diko pa kaya kumilala ng iba',
 'sinumpa ata ako sa 41 ?',
 'Sinumpa at pinarusahan sila ng Diyos dahil dito .',
 "Parang sinumpa mo na kasi ang isang tao , kapag 'yun ang sinabi mo , di ba ?",
 'Sinumpa ata ako sa spike rush',
 'sinumpa yata ako ng mga may galit sakin hahaha',
 'kasalanan to ni sai , sinumpa ang joshtin XX_URL',
 'sinumpa ba yung acc ko ngayon bat ang malas XX_EMOJI',
 'pukingina sinumpa na yata ako ng cod',
 'Tangina sinumpa rin ata ako ng gin .']

In [ ]:
vocab = set(new_wn.word.tolist())
vocab

{'tanggalin',
 'tanggapan',
 'tanggapin',
 'tanghalian',
 'tanglaw',
 'tanim',
 'tanso',
 'tanyag',
 'tao',
 'taong-bayan',
 'tapakan',
 'tapat',
 'tapik',
 'tapon',
 'tapos',
 'tapunan',
 'tapusin',
 'tarangkahan',
 'tasa',
 'tatak',
 'tatay',
 'tatsulok',
 'tau',
 'taw',
 'tawa',
 'tawag',
 'tawagan',
 'tawanan',
 'teka',
 'tela',
 'telebisyon',
 'telepono',
 'teller',
 'tema',
 'tenge',
 'teorya',
 'terorista',
 'terror',
 'tesla',
 'test',
 'thompson',
 'tibo',
 'tigil',
 'tigre',
 'tiis',
 'tilaok',
 'tili',
 'timba',
 'timbangan',
 'timbre',
 'timog',
 'timog-kanluran',
 'timog-silangan',
 'tin',
 'tinapay',
 'tinda',
 'tindahan',
 'tindig',
 'tingin',
 'tingnan',
 'tinig',
 'tinola',
 'tinta',
 'tipaklong',
 'tirahan',
 'titanium',
 'titi',
 'titik',
 'tito',
 'titser',
 'tiwala',
 'tiyak',
 'tiyan',
 'tiyanak',
 'tiyo',
 'tobey',
 'tomboy',
 'tonelada',
 'torotot',
 'torpe',
 'trabaho',
 'traction',
 'tracy',
 'trahedya',
 'trak',
 'traydor',
 'tree',
 'tren',
 'trilyon',
 'trooper',
 'tropeo',
 'trumpeta',
 'trunk',
 'tsaa',
 'tsaka',
 'tsokolate',
 'tsuper',
 'tubigan',
 'tugatog',
 'tugisin',
 'tugtog',
 'tuhod',
 'tuklas',
 'tukoy',
 'tulak',
 'tuldok',
 'tulin',
 'tulisan',
 'tulog',
 'tumaas',
 'tumakbo',
 'tumanaw',
 'tumanggap',
 'tumbong',
 'tumpak',
 'tumuntong',
 'tunghayan',
 'tungkod',
 'tungkulin',
 'tungo',
 'tuning',
 'tunog',
 'tuod',
 'turing',
 'turista',
 'turner',
 'tuso',
 'tusok',
 'tusukin',
 'tutok',
 'tuwa',
 'tuwalya',
 'ubas',
 'ubusin',
 'udyok',
 'ugat',
 'ugong',
 'uhaw',
 'ulam',
 'ulan',
 'uli',
 'ulo',
 'ululin',
 'ulupong',
 'ulyanin',
 'umaandar',
 'umahon',
 'umangat',
 'umani',
 'umanib',
 'umisip',
 'umpisa',
 'umpisahan',
 'umurong',
 'umutot',
 'unan',
 'unawa',
 'ungas',
 'unggoy',
 'ungol',
 'uniporme',
 'uno',
 'unos',
 'upuan',
 'uri',
 'urong',
 'usap',
 'utak',
 'utopia',
 'utos',
 'utot',
 'uwak',
 'vega',
 'veteran',
 'wagi',
 'wakas',
 'wakasan',
 'walis',
 'walker',
 'walo',
 'ward',
 'warren',
 'warrior',
 'wasak',
 'wasto',
 'watawat',
 'watson',
 'waw',
 'wayne',
 'wb',
 'weird',
 'wen',
 'west',
 'wheeler',
 'whey',
 'white',
 'wika',
 'windang',
 'wood',
 'xavier',
 'xian',
 'xy',
 'yabang',
 'yakap',
 'yaman',
 'yang',
 'yapos',
 'yaya',
 'yelo',
 'yen',
 'yin',
 'yosi',
 'yuan',
 'yugto',
 'yuta',
 'zen',
 'zion',
 'zombie',
 'zoology'}

In [ ]:
def print_group(df, word):
    df_word = df.loc[df['word'] == word]
    merge_labels = set(df_word['merge_label'].tolist())

    for label in merge_labels:
        print(f"GROUP {label}")
        df_subset = df_word[df_word['merge_label'] == label]

        for idx, row in df_subset.iterrows():
            print(row['sense_id'])
            for sent in row['example_sentences']:
                print(f"    {sent}")

In [ ]:
print_group(new_wn, "tunog")

GROUP 0
tunog_0
    e biglang boom yung tunog HAHAHAHA
    kung sa akin lang yung tunog grounded HAHAHAHAA
    talaga ako dito yung may tunog na talaga
    ko alam saan galing yung tunog!
    kung saan nag mumula yung tunog!
    naman kasi sumigaw ng walang tunog?
    pagsneeze mo ang cute ng tunog?
    dati natutuwa pa ako sa tunog, ngayon, shet.
    ramdam na ramdam ko yung tunog jusq kulang nalang lumitaw sa
    ang ganda ng tunog pero mejo mahina.
ns_tunog_0
    Bigla akong kinabahan sa tunog ng laptop ko habang nanunuod tas ayaw pa mamatay hanep yan parang sasabog na kanina eh hahahaha
    Aga ko nagising kanina tapos bigla ko lang naalala yung tunog ng magic shop kay jimin na part tapos narealize ko na unti unti na akong lumalabas sa magic shop ?
    ang hirap ng feeling dati konting tunog lng sa bike mo dikana makatulog pano pa kaya pag totally sira na yung dimo na magamit
    so umakyat ako sa rooftop para umiyak ng malakas ng walang makakarinig sakin tapos andon pala yung borders namin so need ko umiyak ng walang tunog sa kwarto kasi andito rin tatay ko pucha di ako makahinga putangina naman hahaha
    maya't maya tuloy tulog ako tapos nagigising nalang ako sa tunog ng messenger hmp bigla nalang may tatawag or tadtad ng pm kasi puro typing nalang daw , yun pala 'di ko nasend yung dapat na reply HAHAHAHAHAA warahel XX_EMOJI XX_EMOJI XX_EMOJI
    grabe yung tunog ng codelock na doors sa live ni nancy , naaalala ko ung nagtatago kami sa mockup na unit tas tangina tumunog yon bigla , buti nalang di manager na gagu ang pumasok SKSKSKSKS
    XX_USERNAME isang family na lumipat sa bagong bahay tas may kwarto na bawal nilang pasukin osjxjs then may biglang tunog na nanggaling sa kwarto na un gusto alamin nung bida pero di siya pinayagan tas na kidnap kuya niya den tuloy tuloy na ganda kung ikaw nalang umalam ng plot hehehe XX_EMOJI
    akala ko kagabi baba akyat si mommy kasi parang may naglalakad sa hallway as in tunog talaga ng hakbang ta's pabalik balik , ta's pag silip ko wala naman tulog na din lahat sa bahay pati si mommy hahahaha gagi wala namang takutan napatulog ako agad ng wala sa oras eh , k skl bye .
    pucha nawala sa isip ko na sira nga pala laptop anlutong tuloy ng tunog HAHAHAHAHAHA
    Ang ganda nung panaginip ko kanina tapos bigla akong nagising kasi ang lakas nung tunog ng generator XX_EMOJI XX_EMOJI
tunog_2
    kapaso na dayon tas kadagko tunog fan
    di nakooo ganahan sa tunog sa mga sakyanan
    mahaboy every morning kada mag tunog ang alarm
    Mayo lng di gawa tunog kag wala may naka bati
GROUP 1
tunog_1
    na ang mga tunog.
    pagkakaiba ng tunog nito.
    ng mga tunog na ito.
    ay lumilikha ng maingay na tunog.
    Ang tanging tunog ay ang orasang pumipitik, na
    ibang-iba ang tunog.
    nai-record na mahiwagang tunog na tila pamilyar na nadidinig sa mga
    na kadalasan ay lumilikha ng tunog.
    kanta, nagpapalakasan pa ng tunog.
    at paglatag ng tunog.
ns_tunog_1
    Nguni't sa mundo ng mga tao tila sila ay walang nalalaman sa mga pinagmulan ng mga bagay na ito , nguni't hanggang ngayon ay patuloy na sumasalungat sa Akin , na tila ang Aking mga salita ay may tunog lamang at walang kahulugan .
    Hindi siya nito inino pagkat gaya ng datiy nakatanga ito sa kawalan , tila nakaharap sa isang panooring walang tunog at walang hugis at walang kulay .
    Musikang malapit sa puso ng mga Pinoy na binigyan ng bagong tunog ang handog ni Darryl Shy , ang naging The Voice of the Philippines Season 1 finalist na Star Records exclusive recording artist na ngayon , sa kanyang self-titled debut album .
    Wala kang naririnig na tunog at walang nakikitang liwanag ; hindi mo namamalayan ang pagdating ng isang bagong langit at isang bagong lupa , ng isang bagong kapanahunan , dahil sinasabi ng iyong ama , XX_OTHERS Anak ko , huwag kang bumangon , maaga pa . Malamig ang panahon , kaya huwag kang lumabas , baka matusok ng tabak at espada ang iyong mga mata .
    Mula sa temperatura hanggang sa hangin , mula sa tunog hanggang sa liwanag , gumawa ang Diyos ng mga maingat na plano at pag-aayos , upang ang mga katawan ng mga tao at ang kapaligirang kanilang tinitirahan ay hindi sasailalim sa anumang balakid mula sa mga natural na kundisyon , at sa halip ang sangkatauhan ay magkakaroon ng kakayahang manirahan at magpakarami nang normal at manirahan nang normal kasama ang lahat ng bagay nang magkasundo .
    Sa silyon , ang matandang lalaki ay gayon pa rin , tila nakaharap sa isang panooring walang tunog at walang hugis at walang kulay .
    Iyon ay , lahat ng bagay na may buhay at walang buhay ay patuloy na pasulong sa mga mata ng Diyos , at ang mga ito rin ay lumilikha ng mga tunog nang sabay-sabay .
    Nagmagandang-gabi si Julio sa ama ni Atong , ngunit gayon pa rin ito , tila nakaharap sa isang panooring walang tunog at walang hugis at walang kulay .
    Subalit sa mundo ng tao ay parang wala silang alam sa mga pinagmulan ng mga bagay na ito , ngunit palagi Akong sinasalungat , na para bang may tunog lamang ang Aking mga salita ngunit walang kahulugan .
    Nakaharap siya sa pintuan , walang kagalaw-galaw , ni hindi kumukurap , at gayong dilat ang mga mata ay tila walang nakikita , tila nakaharap sa isang panooring walang tunog at walang hugis at walang kulay .
GROUP 2
tunog_3
    ang mas kakaibang tunog mula sa sari-saring artists na iba-iba ang
    kanyang style at tunog sa mga awiting Regret It, Missing You,
    Kahit na tunog masaya at upbeat ang album,
    Mukhang pang-party at sayawan ang tunog ng kanta kung saan ka-collaborate
    na-record na kanta sa tunog na SKA. Sa Pilipinas, sumikat ito
    kanta rito ang mga kakaibang tunog gaya ng recordings ng mga
    sa kanyang dating tunog. Ang Malibu, unang awitin sa album na
    at may napansin siya sa tunog ng awitin.
    ang orihinal na tunog. Taong 1999 nang mabuo ang pop rock
    Pinoy na binigyan ng bagong tunog ang handog ni Darryl Shy,
ns_tunog_2
    Hatid ni Inigo ang emosyong nararamdaman ng iniwan ng minamahal sa bagong pop version ng kanta na may tunog trap ballad hatid ng music producer na si Moophs gamit ang gitara .
    Isang original song na lang ang kulang na si Sam mismo ang sumulat at naglapat ng tunog .
    Si Marlo mismo ang sumulat ng lyrics at naglapat ng tunog sa nasabing awitin , na inareglo ni Adonis Tabanda .
    Magaan pakinggan ang kanta dahil sa suwabeng boses ni JC , at acoustic pop na tunog nito , lalo na ang mensahe na gusto niyang makasama uli ang isang espesyal na tao na matagal nang hindi nakikita .
    Samantala , nu'ng unang in-upload ni Yeng sa YouTube ang nasabing awitin na siya mismo ang sumulat , naglapat ng tunog at kumanta noong Agosto 23 , 2014 ay naging talk of the town na ito agad kaya naman maraming nagkainteres na panoorin ito .
    Bibida na nga worldwide simula sa June 25 ang inaabangang "Options" album ni Inigo tampok ang 12 orihinal na kanta na layuning maipakilala ang tunog ng Original Pilipino Music ( OPM ) sa buong mundo .
    Layuning maipakilala ang tunog ng Original Pilipino Music ( OPM ) sa buong mundo .
    "Nang ibigay sa akin yung song , napaigtad ako nang bahagya sa kinauupuan ko pero nang mabasa ko ang lyrics at marinig ko ang tunog , nagustuhan ko agad .
    Nakasentro ang pop reimagination ng 1980 classic sa emosyong nararamdaman ng iniwan ng minamahal na may tunog trap ballad gamit ang gitara .
    Maging nang una pa lang ito i-upload ni Yeng Constantino sa YouTube ( siya mismo ang sumulat , naglapat ng tunog at kumanta ) noong Agosto 23 , 2014 ay naging talk of the town agad ito dahil marami ang nagkainteres na panoorin ito .

In [ ]:
torch.max(new_wn.t(), dim=1)

torch.return_types.max(
values=tensor([0.4814, 0.5849, 0.4313]),
indices=tensor([1, 1, 1]))

In [ ]:
torch.max(new_wn, dim=1)

torch.return_types.max(
values=tensor([0.3345, 0.5849, 0.4411, 0.3843]),
indices=tensor([2, 1, 1, 2]))

In [ ]:
new_wn = pd.DataFrame(columns=['merge_label'])
new_wn

Empty DataFrame
Columns: [merge_label]
Index: []

In [ ]:
nlp_wordnet.iloc[1]['merge_label'] = 1

In [ ]:
row  = nlp_wordnet.iloc[1].append(pd.Series({'merge_label': 1}))
row

word                                                             abala
sense_id                                                       abala_1
sense_embedding      [0.035149045, 0.062080346, 0.018494673, -0.062...
example_sentences    [pasensya na sa abala!, sa abala., po, pasensy...
contextual_info      {'twitter': {'2021': 8}, 'radyoinquirer': {'20...
pos                                                                 NN
sense_embeddings     [tensor(0.0352), tensor(0.0621), tensor(0.0185...
merge_label                                                          1
dtype: object

In [ ]:
new_wn.append(row, ignore_index=True)

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word
0,1,"{'twitter': {'2021': 8}, 'radyoinquirer': {'20...","[pasensya na sa abala!, sa abala., po, pasensy...",NN,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[tensor(0.0352), tensor(0.0621), tensor(0.0185...",abala_1,abala

In [ ]:
nlp_wordnet

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos,sense_embeddings
0,1,1,1,1,1,1,1
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN,"[tensor(0.0352), tensor(0.0621), tensor(0.0185..."
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN,"[tensor(0.0182), tensor(0.0152), tensor(0.0200..."
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ,"[tensor(0.0139), tensor(0.0176), tensor(0.0183..."
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB,"[tensor(-0.0038), tensor(0.0338), tensor(0.021..."
...,...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN,"[tensor(0.0238), tensor(0.0431), tensor(0.0439..."
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN,"[tensor(-0.0269), tensor(-0.0207), tensor(0.04..."
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN,"[tensor(0.0132), tensor(0.0138), tensor(0.0390..."
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN,"[tensor(0.0087), tensor(0.0009), tensor(0.0586..."
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD,"[tensor(0.0246), tensor(0.0117), tensor(0.0464..."

In [ ]:
new_wn.append(nlp_wordnet.iloc[0])

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_embeddings,sense_id,word
0,NaN,"{'abante': {'2021': 1}, 'gma': {'2009': 1, '20...","[15 barangays, 415 na tao at 120 pamilya sa Re...",NN,"[0.016414613, 0.016713655, -0.018530315, -0.00...","[tensor(0.0164), tensor(0.0167), tensor(-0.018...",tao_0,tao
1,NaN,"{'gma': {'2021': 1, '2018': 2, '2012': 1, '202...","[Dinagsa ng mga tao ang isang lamay sa likod, ...",NN,"[0.0012409107, 0.01373657, 0.0048804055, 0.007...","[tensor(0.0012), tensor(0.0137), tensor(0.0049...",tao_3,tao
0,NaN,"{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...","[ng gabi, habang abala umano sa pagtitinda ang...",NN,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[tensor(0.0114), tensor(0.0058), tensor(-0.008...",abala_0,abala

In [ ]:
new_wn

Empty DataFrame
Columns: []
Index: []

In [ ]:
import torch.nn.functional as F

# cosine similarity = normalize the vectors & multiply
C = F.normalize(nlp_se) @ F.normalize(ns_se).t()
C

tensor([[0.1441, 0.0934, 0.3345],
        [0.4814, 0.5849, 0.4313],
        [0.2113, 0.4411, 0.1627],
        [0.2203, 0.3649, 0.3843]])

In [ ]:
a, b = torch.max(C, dim=1)
a,b

(tensor([0.3345, 0.5849, 0.4411, 0.3843]), tensor([2, 1, 1, 2]))

In [ ]:
for i in a:
    if i > 0.4:
        print("hew")

hew
hew

In [ ]:
nlp_se[0].unsqueeze(dim=0).shape

torch.Size([1, 768])

In [ ]:
cos(nlp_se[0].unsqueeze(dim=0), ns_se[1].unsqueeze(dim=0))

tensor([0.0934])

In [ ]:
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-08)
cos(nlp_se, ns_se)

IndexError: ignored

In [ ]:
def WSD_EVAL(nlp_wn, ns_wn, thres=0.5):
    print(f'Threshold: {thres}')
    # Initialize 
    cos = torch.nn.CosineSimilarity(dim=1, eps=1e-08)

    # Sentence embeddings
    sentence_embeddings_nlp = torch.tensor(df_text_embs['embs'].values.tolist())

    lst = []

    senses = df_senses.loc[df_senses['word']==target_word]

    senses_dict = {}

    for row in senses.itertuples():
        senses_dict[row.sense_id] = {'sense_embedding': row.sense_embedding}

    for idx, sense in enumerate(senses_dict):
        output = cos(sentence_embeddings, torch.tensor(senses_dict[sense]['sense_embedding']).unsqueeze(0))
        lst.append(output)

    res = torch.stack(lst, dim=1)
    labels = torch.argmax(res, dim=1).tolist()
    scores = torch.max(res, dim=1)[0].tolist()

    sense_ids = list(senses_dict.keys())

    # if less than threshold, label as 'XX'

    mapped_labels = []
    for idx, score in enumerate(scores):
        if score < thres:
            mapped_labels.append('XX')
        else:
            mapped_labels.append(sense_ids[labels[idx]])

    # mapped_labels = []
    # for label in labels:
    #     mapped_labels.append(sense_ids[label])

    # # Append labels to DataFrame
    # df_text_embs.loc[:, 'sense_id'] = mapped_labels
    # df_text_embs.loc[:, 'score'] = scores

    return mapped_labels, scores

Read nlp wordnet pickle . Sense embeddings intact.

Read netsci wordnet. Generate sense embeddings. Add to dataframe.

WSD:
*  for each word
    * if cos(nlp[word].senseembeddings, ns[word].senseembeddings) <= threshold
        * concat(nlp[word], ns[word])