In [1]:
from wordnet import *
from translate import *
import nltk
#nltk.download('wordnet')

# Load translate words

In [15]:
df_valid = pd.read_csv('full_vocab_translated.csv')
df_valid

        fil_text     eng_text backtranslation
0         matino        sober          matino
1         maayos         well          mabuti
2     hanapbuhay   occupation      hanapbuhay
3        trabaho         work         trabaho
4           obra         work         trabaho
...          ...          ...             ...
2593      bilasa       bilasa          bilasa
2594     makipot       narrow         makitid
2595        tuod         tuod            tuod
2596    bumaling  turn around          umikot
2597        anas         anas            anas

[2598 rows x 3 columns]

## Query WordNet

In [3]:
words = df_valid['eng_text'].values.tolist()
df = get_wordnet_entries(words)

No found:  oo
No found:  matiyaga
No found:  makulit
No found:  ganoon
No found:  abala
No found:  mabanas
No found:  bugso
No found:  buhos
No found:  maiksi
No found:  parati
No found:  bihira
No found:  magaaral
No found:  tapon
No found:  usap
No found:  pandak
No found:  mapakla
No found:  pait
No found:  pasyal
No found:  tawa
No found:  halakhak
No found:  ligaya
No found:  tapos
No found:  banat
No found:  sapag
No found:  run away
No found:  when
No found:  ebak
No found:  looks like
No found:  lapat
No found:  laglag
No found:  hulog
No found:  with
No found:  palpak
No found:  tanim
No found:  suot
No found:  kinapal
No found:  takal
No found:  hapdi
No found:  commit suicide
No found:  nitso
No found:  dalamhati
No found:  windang
No found:  nasira
No found:  lupaypay
No found:  putol
No found:  sira
No found:  lagim
No found:  kapkapan
No found:  ibiyahe
No found:  duwelo
No found:  makati
No found:  labi
No found:  mamitas
No found:  umani
No found:  sagarin
No found:  take advantage
No found:  akay
No found:  for example
No found:  ehemplo
No found:  tunghayan
No found:  masdan
No found:  matyagan
No found:  titser
No found:  hepe
No found:  batugan
No found:  petiks
No found:  punda
No found:  a lot
No found:  pino
No found:  mainam
No found:  bimpo
No found:  lampara
No found:  mamon
No found:  sinaing
No found:  palay
No found:  fried rice
No found:  itanim
No found:  wake up
No found:  gatungan
No found:  ere
No found:  alapaap
No found:  agos
No found:  subok
No found:  likha
No found:  buo
No found:  kusa
No found:  atras
No found:  on the road
No found:  the street
No found:  awayin
No found:  kumandidato
No found:  carry out
No found:  pasimuno
No found:  way of thinking
No found:  ideklara
No found:  lahad
No found:  ipot
No found:  lupa
No found:  libag
No found:  basehan
No found:  malagay
No found:  will go
No found:  go up
No found:  get off
No found:  lupit
No found:  dosena
No found:  anim
No found:  balitaktakan
No found:  the bible
No found:  una
No found:  uno
No found:  isa
No found:  baybay
No found:  sumara
No found:  isara
No found:  turned on
No found:  because
No found:  lantad
No found:  kalo
No found:  maton
No found:  sanggano
No found:  far away
No found:  kinurakot
No found:  wagi
No found:  you
No found:  to the north
No found:  onsa
No found:  balibol
No found:  balbal
No found:  elise
No found:  aloy
No found:  balag
No found:  bako
No found:  bahala
No found:  bahag
No found:  young man
No found:  dilis
No found:  cut off
No found:  fill in
No found:  abangan
No found:  kataka-taka
No found:  dambana
No found:  igawad
No found:  sustento
No found:  rason
No found:  taguri
No found:  can be given
No found:  ilathala
No found:  gandahan
No found:  speed up
No found:  yaman
No found:  very much
No found:  sobra
No found:  hingil
No found:  sweep away
No found:  let go
No found:  iwan
No found:  sambitin
No found:  torotot
No found:  kapote
No found:  numerong
No found:  parte
No found:  throw away
No found:  ibasura
No found:  binta
No found:  pasas
No found:  duhat
No found:  dalandan
No found:  suha
No found:  buko
No found:  caldereta
No found:  tinola
No found:  in the meantime
No found:  very deep
No found:  manloloko
No found:  unos
No found:  ungas
No found:  sentri
No found:  guwardiya
No found:  pingpong
No found:  ipin
No found:  noo
No found:  the brain
No found:  kiki
No found:  bilat
No found:  burat
No found:  hita
No found:  sense of smell
No found:  bunganga
No found:  leeg
No found:  puson
No found:  sikmura
No found:  muning
No found:  tilaok
No found:  ipis
No found:  baka
No found:  paniki
No found:  langgam
No found:  the door
No found:  pulutan
No found:  lundag
No found:  halo-halo
No found:  tayo
No found:  for sure
No found:  dumausdos
No found:  kabigin
No found:  hingi
No found:  stay away
No found:  kawala
No found:  kapos
No found:  hataw
No found:  palo
No found:  swerte
No found:  banga
No found:  get over
No found:  sipa
No found:  tadyak
No found:  the beginning
No found:  umpisa
No found:  suyo
No found:  duda
No found:  relos
No found:  unawa
No found:  intindi
No found:  sabit
No found:  inom
No found:  kalkal
No found:  uri
No found:  landas
No found:  gunita
No found:  agad
No found:  apura
No found:  towards
No found:  slim down
No found:  palit
No found:  iba
No found:  salit
No found:  akto
No found:  tsaka
No found:  haplos
No found:  grabe
No found:  paalis
No found:  henyo
No found:  sigla
No found:  the bible
No found:  taimtim
No found:  damot
No found:  hayok
No found:  ama
No found:  saglit
No found:  stand up
No found:  bahing
No found:  mura
No found:  agahan
No found:  kadamay
No found:  kanto
No found:  asikaso
No found:  take care
No found:  yaya
No found:  presko
No found:  the sky
No found:  naliliyo
No found:  a lot
No found:  duwende
No found:  North West
No found:  North East
No found:  South East
No found:  South West
No found:  kutsero
No found:  baraha
No found:  bareta
No found:  antanda
No found:  the market
No found:  lamesa
No found:  dining tables
No found:  kinse
No found:  bulbol
No found:  hintuturo
No found:  giliw
No found:  sinisinta
No found:  irog
No found:  bokya
No found:  have fun
No found:  have fun
No found:  get angry
No found:  get angry
No found:  yabang
No found:  be proud
No found:  very difficult
No found:  tamis
No found:  munti
No found:  very little
No found:  back off
No found:  garapata
No found:  om
No found:  rebelde
No found:  rebyu
No found:  rekado
No found:  reseta
No found:  lito
No found:  diwa
No found:  bear fruit
No found:  huli
No found:  binibini
No found:  sablay
No found:  palya
No found:  cover up
No found:  keep secret
No found:  hanap
No found:  dilim
No found:  butterfly knife
No found:  bigay
No found:  find out
No found:  buklatin
No found:  abu
No found:  take note
No found:  from
No found:  asa
No found:  halakhakan
No found:  sapakin
No found:  lapis
No found:  pondo
No found:  pondohan
No found:  dampi
No found:  tapik
No found:  kulo
No found:  kutsara
No found:  we
No found:  pipi
No found:  tarangkahan
No found:  ngawa
No found:  bayong
No found:  kuya
No found:  basa
No found:  lango
No found:  kuto
No found:  busina
No found:  primera
No found:  hesus
No found:  tinda
No found:  lapa
No found:  ipon
No found:  and
No found:  from
No found:  satsat
No found:  tili
No found:  kokak
No found:  ngawngaw
No found:  iangat
No found:  pukpok
No found:  hold on
No found:  miswa
No found:  kabo
No found:  sintas
No found:  bol
No found:  gyera
No found:  paalaala
No found:  uli
No found:  banwa
No found:  barangay
No found:  take sides
No found:  basbas
No found:  batak
No found:  salitan
No found:  in return
No found:  mukmok
No found:  tampo
No found:  pokpok
No found:  mumo
No found:  mithiin
No found:  ninang
No found:  beke
No found:  moreno
No found:  biik
No found:  puday
No found:  butaw
No found:  gapang
No found:  box office
No found:  ululin
No found:  inam
No found:  dunong
No found:  lupig
No found:  bilasa
No found:  tuod
No found:  turn around

In [4]:
df

,word,synset_id,gloss,eng_text
0,sober,grave.s.01,dignified and somber in manner or character an...,a grave God-fearing man | a quiet sedate natur...
1,sober,drab.s.02,lacking brightness or color; dull,drab faded curtains | sober Puritan grey | chi...
2,well,well.v.01,"come up, as of a liquid",Tears well in her eyes | the currents well up
3,well,well.a.01,in good health especially after having suffere...,appears to be entirely well | the wound is nea...
4,well,good.s.13,resulting favorably,it's a good thing that I wasn't there | it is ...
...,...,...,...,...
5018,narrow,narrow.v.01,make or become more narrow or restricted,The selection was narrowed | The road narrowed
5019,narrow,narrow.a.01,not wide,a narrow bridge | a narrow line across the page
5020,narrow,narrow-minded.a.02,lacking tolerance or flexibility or breadth of...,a brilliant but narrow-minded judge | narrow o...
5021,narrow,narrow.a.04,very limited in degree,won by a narrow margin | a narrow escape
5022,narrow,minute.s.02,characterized by painstaking care and detailed...,a minute inspection of the grounds | a narrow ...

## Translate

In [5]:
res = translate_df(df, mode="en_to_tl", backtranslate=False)
res

Progress: 0.00
translated_text: isang libingan na may takot sa Diyos | isang tahimik na likas na tahimik | bilang matino bilang isang hukom | isang taimtim na pangako | ang hukom ay taimtim habang binibigkas niya ang hatol
Progress: 0.00
translated_text: kupas kupas na mga kurtina | matino Puritan grey | mga bata sa madilim na kayumangging damit
Progress: 0.00
translated_text: Maluha-luha sa kanyang mga mata | lumalakas ang agos
Progress: 0.00
translated_text: mukhang ganap na maayos | ang sugat ay halos magaling na | isang mahusay na tao | Sa tingin ko ako ay mabuti; at least maayos na ang pakiramdam ko
Progress: 0.00
translated_text: buti na lang wala ako | buti naman nanatili ka | buti na lang walang nakakita sa iyo | lahat ay mabuti na nagtatapos
Progress: 0.00
translated_text: maganda ang ugali ng mga bata | isang gawain nang maayos | naging maayos ang party | nakatulog siya ng maayos | isang well-argued thesis | isang masarap na ulam | isang well-planned party | ang sanggol ay maaaring maglakad nang maayos
Progress: 0.00
translated_text: Ang problema ay naiintindihan ng mabuti | siya ay well informed | iling mabuti bago gamitin ang | para maiwasan ang food poisoning siguraduhin na ang karne ay mahusay na luto | magaling na karne ng baka | well-satisfied na mga customer | may pinag-aralan
Progress: 0.00
translated_text: Maaari ko bang gawin ito | isang pagkakamali na madaling mauwi sa kapahamakan | maaaring kailanganin mo ang iyong payong | maaari rin niyang linlangin tayo
Progress: 0.00
translated_text: isang libro na sulit basahin | alam na alam ang mga paghihirap sa hinaharap | pinaghihinalaan lamang ng mabuti kung ano ang maaaring mangyari
Progress: 0.00
translated_text: ang proyekto ay mahusay na isinasagawa | ang fetus ay may mahusay na binuo organs | ang kanyang ama ay lubos na nasiyahan sa kanyang mga marka
Progress: 0.00
translated_text: ang kanilang mga kapitbahay ay nagsalita tungkol sa kanila | pinag-isipan niyang mabuti ang libro
Progress: 0.00
translated_text: Natatakot ako na ang pelikula ay sobra sa badyet | pagpinta sa silid na puti ay ginawa itong tila malaki (o malaki) na mas malaki | ang bahay ay bumagsak nang malaki sa halaga | tumaas nang husto ang presyo
Progress: 0.00
translated_text: Makabubuti kung wala ka nang sasabihin pa | hindi maayos na tumanggi
Progress: 0.00
translated_text: magaling siyang sumayaw | magaling siyang magsulat
Progress: 0.00
translated_text: nagpakasal siya ng maayos | Ang mga bata ay nanirahan nang may pakinabang sa Seattle
Progress: 0.00
translated_text: Maganda ang kanilang pamumuhay | nakayanan na niyang mamuhay ng maginhawa mula nang mamatay ang kanyang asawa
Progress: 0.00
translated_text: kinuha ng mabuti ang biro | kinuha ng mabuti ang trahedya na balita
Progress: 0.00
translated_text: hindi ito itinuturing na isa sa kanyang mga di malilimutang gawa | ang symphony ay pinarangalan bilang isang mapanlikhang gawa | siya ay may utang na loob sa pangunguna sa trabaho ni John Dewey | ang gawain ng isang aktibong imahinasyon | Ang pagguho ay ang gawain ng hangin o tubig sa paglipas ng panahon
Progress: 0.00
translated_text: naghahanap siya ng trabaho | maraming tao ang walang trabaho
Progress: 0.00
translated_text: ang pag-master ng pangalawang wika ay nangangailangan ng maraming trabaho | walang mga paaralan ang nag-aalok ng graduate na pag-aaral sa interior design
Progress: 0.00
translated_text: pinag-aralan niya ang buong Wagnerian oeuvre | Ang gawa ni Picasso ay maaaring hatiin sa mga panahon
Progress: 0.00
translated_text: Ako ay magsisikap na mapabuti ang aking mga marka | nagsumikap siya para sa mas magandang kalagayan ng pamumuhay para sa mahihirap
Progress: 0.00
translated_text: Nagtatrabaho na ba ulit ang asawa mo? | Ang aking asawa ay hindi kailanman nagtrabaho | Gusto mo bang magtrabaho pagkatapos ng edad na 60? | Hindi siya gumawa ng anumang trabaho dahil nagmana siya ng maraming pera | Nagtatrabaho siya bilang isang waitress upang maipagpatuloy ang kanyang sarili sa kolehiyo
Progress: 0.00
translated_text: Ang proseso ng pagboto ay hindi gumagana tulad ng iniisip ng mga tao | Paano gumagana ang iyong ideya sa pagsasanay? | Ang paraang ito ay hindi gumagana | Mabilis na kumilos ang mga break ng bago kong sasakyan | Gumagana lamang ang gamot kung iniinom mo ito ng maraming tubig
Progress: 0.00
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.01
translated_text: gumawa ng bato sa mga kasangkapan | iproseso ang bakal | gawan ng metal
Progress: 0.01
translated_text: Ang ilang mga magulang ay nag-eehersisyo sa kanilang mga sanggol | Pinaghirapan ako ng aking personal na tagapagsanay | magtrabaho ng mga kalamnan | ang puzzle na ito ay magsasanay sa iyong isip
Progress: 0.01
translated_text: gumawa ng paraan sa pamamagitan ng karamihan ng tao | gumawa ng paraan sa kagubatan
Progress: 0.01
translated_text: Nagtatrabaho siya sa mga night club | Ang tindero ay nagtatrabaho sa Midwest | Ang artist na ito ay halos gumagana sa acrylics
Progress: 0.01
translated_text: gawin ang iyong paraan sa bawat problema o gawain | Siya ay nagtatrabaho sa kanyang pangalawang martini nang dumating ang mga bisita | Magsimula mula sa ibaba at magtrabaho patungo sa itaas
Progress: 0.01
translated_text: Hindi ako makagawa ng milagro | gumawa ng kalituhan | magdala ng mga komento | magbiro | Nagdulot ng ginhawa ang ulan sa lugar na naapektuhan ng tagtuyot
Progress: 0.01
translated_text: Trabaho ang lupa | linangin ang lupa
Progress: 0.01
translated_text: Ang masa na ito ay hindi madaling gumana | Ang malambot na metal ay gumagana nang maayos
Progress: 0.01
translated_text: Naimpluwensyahan ng gawa ng pintor ang batang pintor | Nagtrabaho siya sa kanyang mga kaibigan upang suportahan ang kandidato sa pulitika
Progress: 0.01
translated_text: Ginagawa ng pilot na ito ang mga kontrol | Maaari ka bang gumawa ng electric drill?
Progress: 0.01
translated_text: Maingat niyang hinulma ang mga rice ball | Bumuo ng mga silindro mula sa kuwarta | hugis ng pigura | Gawing espada ang metal
Progress: 0.01
translated_text: gawin ang mga pasas sa kuwarta | ang mag-aaral ay gumawa ng ilang biro sa kanyang presentasyon | isakay ang katawan sa flatbed truck
Progress: 0.01
translated_text: masahin ang kuwarta | gawin ang luad hanggang sa ito ay malambot
Progress: 0.01
translated_text: Pinagsasamantalahan niya ang bagong sistema ng pagbubuwis | Alam niya kung paano gawin ang sistema | nagtatrabaho siya sa kanyang mga magulang para sa pakikiramay
Progress: 0.01
translated_text: nalutas mo ba ang problema? | Ayusin ang iyong mga problema sa boss | ang hindi kasiya-siyang sitwasyong ito ay hindi gagana mismo | nakuha mo ba? | Nakuha mo ba ang ibig kong sabihin? | Hindi niya magawa ang problema sa matematika
Progress: 0.01
translated_text: Inaasim namin ang mga ubas sa napakatagal na panahon upang makamit ang mataas na nilalamang alkohol | Ang nagtitinda ay gumawa ng alak sa malalaking oak vats
Progress: 0.01
translated_text: Ang gatas ay umasim | Ang alak ay gumana | Ang cream ay nakabukas--kailangan nating itapon ito
Progress: 0.01
translated_text: hindi ito itinuturing na isa sa kanyang mga di malilimutang gawa | ang symphony ay pinarangalan bilang isang mapanlikhang gawa | siya ay may utang na loob sa pangunguna sa trabaho ni John Dewey | ang gawain ng isang aktibong imahinasyon | Ang pagguho ay ang gawain ng hangin o tubig sa paglipas ng panahon
Progress: 0.01
translated_text: naghahanap siya ng trabaho | maraming tao ang walang trabaho
Progress: 0.01
translated_text: ang pag-master ng pangalawang wika ay nangangailangan ng maraming trabaho | walang mga paaralan ang nag-aalok ng graduate na pag-aaral sa interior design
Progress: 0.01
translated_text: pinag-aralan niya ang buong Wagnerian oeuvre | Maaaring hatiin sa mga panahon ang gawa ni Picasso
Progress: 0.01
translated_text: Ako ay magsisikap na mapabuti ang aking mga marka | nagsumikap siya para sa mas magandang kalagayan ng pamumuhay para sa mahihirap
Progress: 0.01
translated_text: Nagtatrabaho na ba ulit ang asawa mo? | Ang aking asawa ay hindi kailanman nagtrabaho | Gusto mo bang magtrabaho pagkatapos ng edad na 60? | Hindi siya gumawa ng anumang trabaho dahil nagmana siya ng maraming pera | Nagtatrabaho siya bilang isang waitress upang maipagpatuloy ang kanyang sarili sa kolehiyo

Progress: 0.01
translated_text: Ang proseso ng pagboto ay hindi gumagana tulad ng iniisip ng mga tao | Paano gumagana ang iyong ideya sa pagsasanay? | Ang paraang ito ay hindi gumagana | Mabilis kumilos ang mga break ng bago kong sasakyan | Gumagana lamang ang gamot kung iniinom mo ito ng maraming tubig
Progress: 0.01
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.01
translated_text: gumawa ng bato sa mga kasangkapan | iproseso ang bakal | gawan ng metal
Progress: 0.01
translated_text: Ang ilang mga magulang ay nag-eehersisyo sa kanilang mga sanggol | Pinaghirapan ako ng aking personal na tagapagsanay | magtrabaho ng mga kalamnan | ang puzzle na ito ay magsasanay sa iyong isip
Progress: 0.01
translated_text: gumawa ng paraan sa pamamagitan ng karamihan ng tao | gumawa ng paraan sa kagubatan
Progress: 0.01
translated_text: Nagtatrabaho siya sa mga night club | Ang tindero ay nagtatrabaho sa Midwest | Ang artist na ito ay halos gumagana sa acrylics
Progress: 0.01
translated_text: gawin ang iyong paraan sa bawat problema o gawain | Siya ay nagtatrabaho sa kanyang pangalawang martini nang dumating ang mga bisita | Magsimula mula sa ibaba at magtrabaho patungo sa itaas
Progress: 0.01
translated_text: Hindi ako makagawa ng milagro | gumawa ng kalituhan | magdala ng mga komento | magbiro | Nagdulot ng ginhawa ang ulan sa lugar na naapektuhan ng tagtuyot
Progress: 0.01
translated_text: Trabaho ang lupa | linangin ang lupa
Progress: 0.01
translated_text: Ang masa na ito ay hindi madaling gumana | Ang malambot na metal ay gumagana nang maayos
Progress: 0.01
translated_text: Naimpluwensyahan ng gawa ng pintor ang batang pintor | Nagtrabaho siya sa kanyang mga kaibigan upang suportahan ang kandidato sa pulitika
Progress: 0.01
translated_text: Ginagawa ng pilot na ito ang mga kontrol | Maaari ka bang gumawa ng electric drill?
Progress: 0.01
translated_text: Maingat niyang hinulma ang mga rice ball | Bumuo ng mga silindro mula sa kuwarta | hugis ng pigura | Gawing espada ang metal
Progress: 0.01
translated_text: gawin ang mga pasas sa kuwarta | ang mag-aaral ay gumawa ng ilang biro sa kanyang presentasyon | isakay ang katawan sa flatbed truck
Progress: 0.01
translated_text: masahin ang kuwarta | gawin ang luad hanggang sa ito ay malambot
Progress: 0.01
translated_text: Pinagsasamantalahan niya ang bagong sistema ng pagbubuwis | Alam niya kung paano gawin ang sistema | nagtatrabaho siya sa kanyang mga magulang para sa pakikiramay
Progress: 0.01
translated_text: nalutas mo ba ang problema? | Ayusin ang iyong mga problema sa boss | ang hindi kasiya-siyang sitwasyong ito ay hindi gagana mismo | nakuha mo ba? | Nakuha mo ba ang ibig kong sabihin? | Hindi niya magawa ang problema sa matematika
Progress: 0.01
translated_text: Inaasim namin ang mga ubas sa napakatagal na panahon upang makamit ang mataas na nilalamang alkohol | Ang nagtitinda ay gumawa ng alak sa malalaking oak vats
Progress: 0.01
translated_text: Ang gatas ay umasim | Ang alak ay gumana | Ang cream ay nakabukas--kailangan nating itapon ito
Progress: 0.01
translated_text: ang mga pagtatantya ng pagkalugi ng lungsod sa trabahong iyon ay umabot sa isang milyong dolyar | ang trabaho sa pag-aayos ng makina ay tumagal ng ilang oras | ang walang katapusang gawain ng pag-uuri ng mga sample | mga gawain sa umaga ng magsasaka
Progress: 0.01
translated_text: umaasa sa matibay na kapayapaan | pangmatagalang pagkakaibigan
Progress: 0.01
translated_text: ang mga hindi gaanong matibay na bato ay unti-unting napupuna upang bumuo ng mga lambak | ang matibay na granite ng sinaunang Appalachian spine ng kontinente
Progress: 0.01
translated_text: makunat na diin | tensile pull
Progress: 0.01
translated_text: malagkit na tanso | malleable na mga metal tulad ng ginto | ibinabad nila ang katad para maging malambot | malambot na tunaw na salamin | gawa sa mataas na makunat na haluang metal
Progress: 0.01
translated_text: isang matatag na hagdan | isang matatag na kapayapaan | isang matatag na relasyon | matatag na presyo
Progress: 0.01
translated_text: isang all-right na pelikula | kinilig ang mga pasahero pero ayos lang | ayos lang ba ang lahat? | maayos ang lahat | bagay ay okay | hapunan at ang mga pelikula ay naging maayos | isa pang minuto magiging maayos na ako
Progress: 0.01
translated_text: ayos lang siya mag-isa | hinawakan ang lahat ng karapatan sa ilalim ng presyon
Progress: 0.02
translated_text: nagturo siya ng mga wikang banyaga | ang wikang ipinakilala ay pamantayan sa buong teksto | ang bilis kung saan ang isang programa ay maaaring isagawa ay depende sa wika kung saan ito nakasulat
Progress: 0.02
translated_text: magulo ang kanyang pananalita | marahas niyang wika | itinala niya ang sinasalitang wika ng mga lansangan
Progress: 0.02
translated_text: ang kanyang mga komposisyon ay palaging nagsisimula sa lyrics | isinulat niya ang parehong mga salita at musika | ang awit ay gumagamit ng wikang kolokyal
Progress: 0.02
translated_text: legal na terminolohiya | biological nomenclature | ang wika ng sosyolohiya
Progress: 0.02
translated_text: nagturo siya ng mga wikang banyaga | ang wikang ipinakilala ay pamantayan sa buong teksto | ang bilis kung saan ang isang programa ay maaaring isagawa ay depende sa wika kung saan ito nakasulat
Progress: 0.02
translated_text: magulo ang kanyang pananalita | marahas niyang wika | itinala niya ang sinasalitang wika ng mga lansangan
Progress: 0.02
translated_text: ang kanyang mga komposisyon ay laging nagsisimula sa lyrics | isinulat niya ang parehong mga salita at musika | ang awit ay gumagamit ng wikang kolokyal
Progress: 0.02
translated_text: legal na terminolohiya | biological nomenclature | ang wika ng sosyolohiya
Progress: 0.02
translated_text: nakita niya ang mga gantimpala ngunit hindi ang mga panganib ng krimen | may panganib na gumawa siya ng mali
Progress: 0.02
translated_text: Nanganganib kaming mawalan ng maraming pera sa pakikipagsapalaran na ito | Bakit itataya ang iyong buhay? | Inilagay niya ang kanyang trabaho sa linya nang sabihin niya sa amo na siya ay mali
Progress: 0.02
translated_text: isang maselang violin passage | pinong china | isang pinong lasa | ang pinong pakpak ng isang paru-paro
Progress: 0.02
translated_text: isang saranggola na masyadong maselan upang lumipad nang ligtas | marupok na mga plato ng porselana | marupok lumang buto | isang mahinang sasakyan
Progress: 0.02
translated_text: malambot na mga kamay | maselang balat ng isang sanggol
Progress: 0.02
translated_text: maselang negosasyon sa malalaking kapangyarihan | nag-aalangan na maging tahasan sa napakakiliti na bagay | isang madamdaming paksa
Progress: 0.02
translated_text: trabaho ay ang pagpapalaya ng sangkatauhan | ang trabaho ng surgeon ay ang pagliligtas ng mga buhay
Progress: 0.02
translated_text: isang ligtas na paglalakbay | magiging ligtas ka dito | isang ligtas na lugar | isang ligtas na taya
Progress: 0.02
translated_text: isang magandang pamumuhunan | isang ligtas na pamumuhunan
Progress: 0.02
translated_text: ang tibo ng kamatayan | naramdaman niya ang pagtusok ng mga kulitis
Progress: 0.02
translated_text: Inipit nila sa akin ang bill ng hapunan | Nasaktan ako ng malaking singil sa buwis
Progress: 0.02
translated_text: isang masiglang kumusta | isang gay sunny room | isang maaraw na ngiti
Progress: 0.02
translated_text: noong bata pa ang mga puso at bakla | ang isang makata ay hindi maaaring maging bakla, sa ganoong kumpanya ng jocund | ang masayang crowd sa reunion | masayang matandang Saint Nick | isang masayahing matandang ginoo | magkaroon ng isang maligayang Pasko | palakpakan ng masayang pagtawa | isang masayang tawa
Progress: 0.02
translated_text: nanguna sa isang gay Bohemian life | isang gay old rogue na may mata sa mga babae
Progress: 0.02
translated_text: mga batang babae na nakasuot ng matapang na bagong damit | magigiting na mga banner na lumilipad | Ang `braw&#39; ay isang Scottish na salita | isang damit na medyo masyadong bakla para sa kanyang mga taon | mga ibong may gay na balahibo
Progress: 0.02
translated_text: isang maligaya (o festal) na okasyon | bakla at kapana-panabik na night life | isang masayang gabi

Progress: 0.02
translated_text: Ang pinaka-nabigo sa bawat naghamon ay ang kamangha-manghang pag-akyat ni Ruth noong Setyembre | palara ang iyong kalaban
Progress: 0.02
translated_text: isang kakaibang hybrid accent | ang kanyang pananalita ay may nakakatawang twang | mayroon silang ilang mga nakakatawang ideya tungkol sa digmaan | nagkaroon ng kakaibang pangalan | ang kakaibang mabangong amoy ng mga clove | isang bagay na tiyak na kakaiba tungkol sa bayang ito | what a rum fellow | iisang pag-uugali
Progress: 0.02
translated_text: pag-aalaga ay tumanda sa kanya | Pinatahimik nila ito dahil sa takot sa reaksyon ng publiko
Progress: 0.02
translated_text: ang takot sa Diyos | ang paggalang ng mga Tsino sa mga patay | tinatrato ng mga Pranses ang pagkain nang may banayad na paggalang | ang kanyang paggalang sa batas ay may hangganan sa pagsamba
Progress: 0.02
translated_text: Natatakot ako sa mga taglamig sa Moscow | Hindi tayo dapat matakot sa mga Komunista!
Progress: 0.02
translated_text: Matakot sa Diyos bilang iyong ama | Pinupuri namin ang henyo
Progress: 0.02
translated_text: nalulungkot dahil namatay ang kanyang aso | Mas mabuti pang kalimutan mo at ngumiti / Kaysa alalahanin mo at malungkot
Progress: 0.02
translated_text: malungkot na balita | ayaw niya ng malungkot na pelikula | ito ay isang napakalungkot na kuwento | Kapag ako ay namatay, aking pinakamamahal, / Huwag kang kumanta ng malungkot na kanta para sa akin
Progress: 0.02
translated_text: ang aking pananalapi ay nasa isang kaawa-awang kalagayan | isang malungkot na desisyon | ang kanyang damit ay nasa malungkot na anyo | isang malungkot na estado ng mga pangyayari
Progress: 0.02
translated_text: isang masungit na batang lalaki na may mahahabang malikot na mga binti | malamya na mga daliri | kung ano ang isang masungit na nilalang ang isang giraffe ay | hinila ang kanyang mabigat na pigura mula sa kanyang upuan
Progress: 0.02
translated_text: isang awkward na istilo ng tuluyan | isang malamya na paghingi ng tawad | ang kanyang masalimuot na istilo ng pagsulat | kung totoo ang bulung-bulungan, may higit pa bang hindi bagay kaysa ulitin ito ngayon?
Progress: 0.02
translated_text: isang awkward na bundle na dadalhin | isang load ng mga hindi magandang gamit | malamya na sapatos na gawa sa kahoy | ang cello, isang medyo hindi maganda na instrumento para sa isang babae
Progress: 0.02
translated_text: isang makulit na manggagawa | gumawa ng isang malamya na trabaho | ang kanyang naguguluhang pagtatangka na maglagay ng isang istante
Progress: 0.02
translated_text: aso, fox, at iba pa | hindi namin gusto ang mga tulad mo sa paligid
Progress: 0.02
translated_text: Hindi na natin makikita ang katulad niya | Hindi ko kayang tiisin ang mga taong katulad niya
Progress: 0.02
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.02
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.02
translated_text: suit ng katulad na disenyo | isang limitadong bilog ng mga katulad na isip | ang mga miyembro ng pamilya ng pusa ay may katulad na disposisyon | tulad ng dalawang gisantes sa isang pod | mala-dog na debosyon | isang parang panaginip na kalidad
Progress: 0.02
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.02
translated_text: lahat ng politiko ay magkatulad | magkamukha sila | ang mga kaibigan ay karaniwang magkapareho sa background at panlasa
Progress: 0.02
translated_text: mga kahon na may kaukulang sukat | ang katulad na panahon ng naunang taon
Progress: 0.02
translated_text: isang maingay na karinderya | isang maliit na asong maingay
Progress: 0.02
translated_text: isang malakas na signal ng radyo | malakas na gamot | isang malakas na lalaki
Progress: 0.02
translated_text: isang makapangyarihang lason | malakas na alak | isang makapangyarihang tasa ng tsaa | isang matigas na inumin
Progress: 0.02
translated_text: isang hindi magugupi na kuta | mga kuta na ginawang hindi masusugatan ang hangganan | isang secure na koneksyon sa telepono
Progress: 0.02
translated_text: isang matibay na pundasyon | ilang malalaking gusaling kahoy
Progress: 0.03
translated_text: isang mainit na landas | mainit ang bango
Progress: 0.03
translated_text: isang mahigpit na pagkakahawak | nagbigay ng malakas na paghila sa lubid
Progress: 0.03
translated_text: mainit na kalan | mainit na tubig | isang mainit na araw ng Agosto | isang mainit na masikip na silid | siya ay mainit at pagod | isang mainit na noo
Progress: 0.03
translated_text: naging mainit at mabigat ang labanan | isang mainit na pakikipag-ugnayan | isang matinding labanan | naging rumaragasang agos ang ilog
Progress: 0.03
translated_text: mainit ang ulo | isang mainit na paksa | isang mainit na bagong libro | isang mainit na pag-iibigan | isang mainit na argumento
Progress: 0.03
translated_text: ay mainit para sa kanya | mainit na pantalon
Progress: 0.03
translated_text: mainit na paninda | isang mainit na kotse
Progress: 0.03
translated_text: isang mainit na sports car | isang paltos na bilis | nakakuha ng mainit na simula | sa mainit na pagtugis | isang red-hot line drive
Progress: 0.03
translated_text: mainit na salsa | ang jalapeno peppers ay napakainit
Progress: 0.03
translated_text: isang mainit na drummer | ang init niya ngayong gabi
Progress: 0.03
translated_text: isa sa mga hot young talents | Ang mga manika ng repolyo patch ay mainit noong nakaraang panahon
Progress: 0.03
translated_text: painitin mo siya | sa hot seat | sa mainit na tubig
Progress: 0.03
translated_text: mainit na balita sa press | mainit na impormasyon
Progress: 0.03
translated_text: mainit sa craps | mainit ang dice ngayong gabi
Progress: 0.03
translated_text: mainit na fuel rods | isang mainit na laboratoryo
Progress: 0.03
translated_text: isang mainit na kawad | isang live wire
Progress: 0.03
translated_text: isang kamangha-manghang paglalakbay sa Silangan | ang pelikula ay hindi kapani-paniwala! | isang paungol na tagumpay | isang kahanga-hangang koleksyon ng mga bihirang aklat | nagkaroon ng nakakagulong usapan tungkol sa pulitika | isang napakalaking tagumpay
Progress: 0.03
translated_text: kahit na medyo natatakot ako, gayunpaman gusto kong subukan ito | habang ayaw namin sa isa&#39;t isa, magkasundo kami | siya ay isang mahigpit ngunit patas na panginoon | ipinagkaloob na ito ay mapanganib, ang parehong gusto ko pa ring pumunta
Progress: 0.03
translated_text: Ang mga resulta, gayunpaman pangkalahatan, ay mahalaga | sinimulan nila, gayunpaman nag-aatubili, na kilalanin ang pagiging lehitimo ng ilan sa mga alalahanin ng oposisyon
Progress: 0.03
translated_text: Ang tagumpay, gayunpaman ito ay dinala, ay matamis | gayunpaman ginawa niya ito, ito ay napakatalino
Progress: 0.03
translated_text: ang kanyang opinyon ay may malaking timbang | ang pag-unlad ay nagpapahiwatig ng pagtaas ng bigat ng mga item na nakalista
Progress: 0.03
translated_text: isang maikling buhay | isang maikling flight | isang maikling holiday | isang maikling kwento | ilang maikling buwan lamang
Progress: 0.03
translated_text: maikling palda | maikling buhok | ang board ay isang talampakang maikli | isang maikling paghagis
Progress: 0.03
translated_text: siya ay pandak at pandak | pandak sa tangkad | isang maikling smokestack | isang maliit na lalaki
Progress: 0.03
translated_text: isang hindi sapat na kita | mahinang suweldo | maikli ang pera | sa maikling rasyon | kulang ang pagkain | kapos sa karanasan
Progress: 0.03
translated_text: isang maikling sale | maikli sa cotton
Progress: 0.03
translated_text: isang light pound | isang kaunting tasa ng asukal | regular na nagbibigay ng maikling timbang
Progress: 0.03
translated_text: isang maikling pananaw sa problema | mga patakaran sa shortsighted | kinutya ng mga kritiko ng maikling pananaw ang plano | myopic na pag-iisip
Progress: 0.03
translated_text: shortbread ay isang maikling crumbly cookie | isang maikling flaky pie crust
Progress: 0.03
translated_text: subukang linangin ang isang hindi gaanong brusque na paraan | isang maikling tugon | napakaikli ng salesgirl sa kanya

Progress: 0.03
translated_text: mahinang sabi niya sa akin na ipagpatuloy ito | maikli niyang kausap ang lahat | maikling sabi niya na hindi niya nagustuhan
Progress: 0.03
translated_text: isang maliit na silid-kainan | isang maliit na bahay | isang maliit na kotse | isang maliit (o maliit) na grupo
Progress: 0.03
translated_text: isang maliit na negosyo | isang pahayagan na may katamtamang sirkulasyon | maliliit na plano | isang pocket-size na bansa
Progress: 0.03
translated_text: anong laking bata ka | maliliit na bata
Progress: 0.03
translated_text: isang hamak na cottage | isang mababang kura paroko | isang mahinhin na tao ng mga tao | maliliit na simula
Progress: 0.03
translated_text: maliit na | maliit na | Ang tula ni eecummings ay nakasulat lahat sa maliliit na letra
Progress: 0.03
translated_text: isang maliit na boses | isang maliit na boses
Progress: 0.03
translated_text: isang maliit na suweldo | katamtamang inflation | nakatulong sa aking maliit na paraan
Progress: 0.03
translated_text: isang masiglang kumusta | isang gay sunny room | isang maaraw na ngiti
Progress: 0.03
translated_text: sinubukan niyang muli | inensayo nila ulit ang eksena
Progress: 0.03
translated_text: Lagi akong nariyan para tulungan ka | laging dumarating sa oras | palaging may ilang polusyon sa hangin | kailanman umaasa na hampasin itong mayaman | laging abala
Progress: 0.03
translated_text: palaging mabait at mapagbigay | lagi siyang dumadating sa oras
Progress: 0.03
translated_text: you can always resign if you don&#39;t like it | maaari kang palaging magpahinga ng isang araw
Progress: 0.03
translated_text: lagi tayong magkaibigan | Pahahalagahan ko ito palagi | Lagi kitang mamahalin
Progress: 0.03
translated_text: minsan gusto niyang bumalik siya sa England | minsan ang kanyang photography ay makapigil-hininga | minsan dumarating sila sa loob ng isang buwan; sa ibang pagkakataon sa loob ng anim na buwan
Progress: 0.03
translated_text: ihatid ang pakete sa aking tahanan | wala siyang bahay na mapupuntahan | sa inyo o samin?
Progress: 0.03
translated_text: nagtayo siya ng isang maliit na tirahan malapit sa lawa | sila ay nakalikom ng pera upang magbigay ng mga tahanan para sa mga walang tirahan
Progress: 0.03
translated_text: Ang mga taripa ng Canada ay nagbigay-daan sa mga kumpanya ng troso ng Estados Unidos na magtaas ng mga presyo sa bahay | ang kanyang tahanan ay New Jersey
Progress: 0.03
translated_text: tahanan ay kung saan ang puso ay | siya ay lumaki sa isang mabuting Kristiyanong tahanan | walang lugar tulad ng tahanan
Progress: 0.03
translated_text: inilipat niya ang kanyang pamilya sa Virginia | Ito ay isang mabuting Kristiyanong sambahayan | Naghintay ako hanggang sa makatulog ang buong bahay | tinanong ng guro kung ilang tao ang bumubuo sa kanyang tahanan
Progress: 0.04
translated_text: ang British Home Office ay may mas malawak na mga responsibilidad kaysa sa United States Department of the Interior | panloob na pulitika ng bansa
Progress: 0.04
translated_text: Nananatili siya sa bahay tuwing katapusan ng linggo | pagkatapos ng laro ang mga bata ay nagdala ng mga kaibigan sa bahay para sa hapunan | Uuwi ako bukas | dumating nakasakay sa bahay sa estilo | sana uuwi ka sa pasko | Iuuwi ko na siya | huwag kalimutang magsulat sa bahay
Progress: 0.04
translated_text: pinauwi ang pako | pinauwi ang kanyang punto | tumama ang kanyang mga komento
Progress: 0.04
translated_text: may bahay siya sa Cape Cod | naramdaman niyang kailangan na niyang lumabas ng bahay
Progress: 0.04
translated_text: pumalakpak ang bahay | binilang niya ang bahay
Progress: 0.04
translated_text: inilipat niya ang kanyang pamilya sa Virginia | Ito ay isang mabuting Kristiyanong sambahayan | Naghintay ako hanggang sa makatulog ang buong bahay | tinanong ng guro kung ilang tao ang bumubuo sa kanyang tahanan
Progress: 0.04
translated_text: ipinakita nila sa amin ang mga larawan ng kanilang kasal | ang isang pelikula ay isang serye ng mga imahe na pinalabas nang napakabilis na pinagsasama ng mata ang mga ito
Progress: 0.04
translated_text: siya ang prototype ng magandang breeding | binigyan niya ang Amerika ng imahe ng mabuting ama
Progress: 0.04
translated_text: maaaring siya ang kambal ni Gingrich | siya ang mismong imahe ng kanyang ina
Progress: 0.04
translated_text: bagama&#39;t ang kanyang sikat na imahe ay gawa-gawa ito ay nagsilbi upang magbigay ng inspirasyon sa musika at pageantry | sinubukan ng kumpanya na mag-proyekto ng isang altruistic na imahe
Progress: 0.04
translated_text: ang barya ay may effigy ni Lincoln | ang libingan ng emperador ay inukit ang kanyang imahe sa bato
Progress: 0.04
translated_text: Hindi ko siya nakikitang nakasakay sa kabayo! | Nakikita ko kung ano ang mangyayari | Nakikita ko ang panganib sa diskarteng ito
Progress: 0.04
translated_text: ipinakita nila sa amin ang mga larawan ng kanilang kasal | ang isang pelikula ay isang serye ng mga imahe na pinalabas nang napakabilis na pinagsasama ng mata ang mga ito
Progress: 0.04
translated_text: isang maliit na pagpipinta ni Picasso | binili niya ang painting bilang puhunan | ang kanyang mga larawan ay nakasabit sa Louvre
Progress: 0.04
translated_text: inilarawan niya ang kanyang mental na larawan ng kanyang umaatake | wala siyang malinaw na larawan ng kanyang sarili o ng kanyang mundo | nag-iwan ng permanenteng impresyon sa kanyang isipan ang mga pangyayari
Progress: 0.04
translated_text: ang pampulitikang larawan ay paborable | ang relihiyosong tanawin sa England ay nagbago noong nakaraang siglo
Progress: 0.04
translated_text: nanood sila ng sine tuwing Sabado ng gabi | ang pelikula ay kinunan sa lokasyon
Progress: 0.04
translated_text: masyadong madalas ang salaysay ay nagambala ng mahabang mga larawan ng salita | ang may-akda ay nagbibigay ng isang mapagpahirap na larawan ng buhay sa Poland | ang polyeto ay naglalaman ng maikling paglalarawan ng mga sikat na Vermonters
Progress: 0.04
translated_text: ang mismong larawan ng isang modernong heneral | siya ang larawan ng kawalan ng pag-asa
Progress: 0.04
translated_text: Hindi ko siya nakikitang nakasakay sa kabayo! | Nakikita ko kung ano ang mangyayari | Nakikita ko ang panganib sa diskarteng ito
Progress: 0.04
translated_text: Ang eksenang ito ay naglalarawan ng buhay bansa | ang mukha ng bata ay ibinigay na may labis na lambing sa pagpipinta na ito
Progress: 0.04
translated_text: ang paaralan ay itinayo noong 1932 | naglalakad siya sa paaralan tuwing umaga
Progress: 0.04
translated_text: manatili pagkatapos ng paaralan | wala siyang pinalampas kahit isang araw sa paaralan | kapag tapos na ang araw ng pasukan ay sabay kaming naglalakad pauwi
Progress: 0.04
translated_text: ipinapaalam ng paaralan sa mga magulang | ang buong paaralan ay lumabas para sa laro
Progress: 0.04
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.04
translated_text: ang paaralan ay itinayo noong 1932 | naglalakad siya sa paaralan tuwing umaga
Progress: 0.04
translated_text: manatili pagkatapos ng paaralan | wala siyang pinalampas kahit isang araw sa paaralan | kapag tapos na ang araw ng pasukan ay sabay kaming naglalakad pauwi
Progress: 0.04
translated_text: ipinapaalam ng paaralan sa mga magulang | ang buong paaralan ay lumabas para sa laro
Progress: 0.04
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.04
translated_text: may magandang record ang abogado | ang track record ay nagpapakita na siya ay magiging isang mabuting pangulo
Progress: 0.04
translated_text: Sinabi noon ni Al Smith, `Tingnan natin ang rekord&#39; | nasa lahat ng record books ang pangalan niya
Progress: 0.04
translated_text: tinabla niya ang Olympic record | sinira ng produksyon ng kape noong nakaraang taon ang lahat ng naunang rekord | Itinakda ng Chicago ang rekord ng homicide
Progress: 0.04
translated_text: pinasiyahan niya na ang criminal record ng nasasakdal ay hindi maaaring ibunyag sa korte | ang puta ay may rekord na isang milya ang haba
Progress: 0.04
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;

Progress: 0.04
translated_text: Ang iskulturang ito ay ginugunita ang mga biktima ng mga kampong konsentrasyon | Inaalaala namin ang mga Patay
Progress: 0.04
translated_text: ang sahod ay binayaran sa pamamagitan ng tseke | nasayang niya ang kanyang suweldo sa inumin | inipon nila ang isang-kapat ng lahat ng kanilang kinikita
Progress: 0.04
translated_text: ang kabayaran ng kasalanan ay kamatayan | ang kabutihan ay sariling gantimpala
Progress: 0.04
translated_text: ang sahod ay binayaran sa pamamagitan ng tseke | nasayang niya ang kanyang suweldo sa inumin | inipon nila ang isang-kapat ng lahat ng kanilang kinikita
Progress: 0.04
translated_text: ang lamig ay kitang kita ang aming hininga | lumabas sa lamig | ang lamig ay isang vasoconstrictor
Progress: 0.04
translated_text: nanginginig siya sa lamig | ang lamig ay tumulong sa pag-alis ng kanyang ulo
Progress: 0.04
translated_text: isang malamig na klima | isang malamig na silid | lumamig na ang hapunan | malamig na mga daliri | kung nilalamig ka, pataasin ang init | isang malamig na beer
Progress: 0.04
translated_text: isang malamig na unfriendly na tango | isang malamig at hindi mapagmahal na tao | isang malamig na impersonal na paraan | malamig na lohika | ang concert ay iniwan ako ng malamig
Progress: 0.04
translated_text: isang malamig na landas | mga aso na nagtatangkang makatanggap ng malamig na amoy
Progress: 0.04
translated_text: mga teoryang kinakain ng gamugamo tungkol sa lahi | lipas na balita
Progress: 0.04
translated_text: malamig sa kanyang mga pagsulong | isang malamig na babae
Progress: 0.04
translated_text: sa malamig na dugo | malamig ang dugong pagpatay | walang kabuluhang pagkawasak
Progress: 0.04
translated_text: isang malamig na madla | malamig na tugon sa bagong dula
Progress: 0.04
translated_text: malamig ang boksingero | hinimatay ng malamig
Progress: 0.04
translated_text: isang napakatalino na pagganap | isang magaling na artista
Progress: 0.04
translated_text: may mga lalaking ayaw sa mga babaeng utak | isang makinang na isip | isang napakatalino na solusyon sa problema
Progress: 0.04
translated_text: ang makikinang na buhay hukuman sa Versailles | isang maluwalhating gawa ng sining | kahanga-hangang mga katedral | ang kahanga-hangang seremonya ng koronasyon
Progress: 0.05
translated_text: maliwanag na damit | makikinang na tapiserya | isang ibong may matingkad na balahibo
Progress: 0.05
translated_text: isang makinang na bituin | makikinang na mga chandelier
Progress: 0.05
translated_text: ang maliwanag na tunog ng seksyon ng trumpeta | ang makinang na tunog ng mga trumpeta
Progress: 0.05
translated_text: ang bundok na iyon ay matibay na bato | sagana ang bato sa New England at maraming quarry
Progress: 0.05
translated_text: inilagay niya ang hiyas sa isang singsing para sa kanyang asawa | mayroon siyang mga hiyas na gawa sa lahat ng pinakapambihirang bato
Progress: 0.05
translated_text: dapat siyang may pusong bato | ang kanyang mukha ay kasing tigas ng bato
Progress: 0.05
translated_text: ibinuhos niya ang kanyang imahe bilang isang mapilit na amo | tanggalin mo ang iyong damit
Progress: 0.05
translated_text: Binato niya ang kumot sa bata | itapon ang pera sa kamay ng pulubi
Progress: 0.05
translated_text: Sulyap | Binigyan niya ako ng masamang tingin
Progress: 0.05
translated_text: buksan ang ilaw | itapon ang pingga
Progress: 0.05
translated_text: Inihagis niya ang sinag ng flashlight sa sulok | Ang lumulubog na araw ay nagbigay ng mahabang anino | gumawa ng spell | magbigay ng mainit na liwanag
Progress: 0.05
translated_text: Jane sabay hagis ng hapunan | itapon ang kotse sa reverse
Progress: 0.05
translated_text: mang-iinsulto | maghagis ng paratang sa isang tao
Progress: 0.05
translated_text: magdaos ng reception | magkaroon, magtapon, o gumawa ng isang party | magbigay ng kurso
Progress: 0.05
translated_text: Ang mga tanong na ito ay nakalilito maging ang mga eksperto | Ang tanong na ito ay lubos na naghagis sa akin | Ang tanong na ito ay nataranta maging ang guro
Progress: 0.05
translated_text: ang kanyang mga komposisyon ay laging nagsisimula sa lyrics | isinulat niya ang parehong mga salita at musika | ang awit ay gumagamit ng wikang kolokyal
Progress: 0.05
translated_text: mayroon siyang regalo para sa mga salita | inilagay niya ang kanyang mga iniisip sa mga salita
Progress: 0.05
translated_text: nagkaroon sila ng away | mayroon silang mga salita
Progress: 0.05
translated_text: ang mga salita ay ang mga bloke kung saan ginawa ang mga pangungusap | halos hindi siya nagsasalita ng sampung salita sa buong umaga
Progress: 0.05
translated_text: naging maayos ang usapan namin | mayroon kaming isang salita o dalawa tungkol dito
Progress: 0.05
translated_text: isang mahusay na makatas na steak | isang malaking pulutong | ang dakilang auk | isang magandang lumang oak | isang mahusay na barko ng karagatan | isang malaking pagkaantala
Progress: 0.05
translated_text: isang mahusay na gawa ng sining | Si Einstein ay isa sa mga natatanging pigura noong ika-20 siglo
Progress: 0.05
translated_text: isang malaking krisis | nagkaroon ng malaking taya sa kinalabasan
Progress: 0.05
translated_text: ginawa niyang bully job | isang maayos na sports car | nagkaroon ng magandang oras sa party | mukha ka lang bagsak
Progress: 0.05
translated_text: kabisera A | mahusay na A | maraming mga manuskrito sa medieval ang nasa script ng majuscule
Progress: 0.05
translated_text: ay malaki sa anak | ay mahusay na may anak
Progress: 0.05
translated_text: isang mahusay na makatas na steak | isang malaking pulutong | ang dakilang auk | isang magandang lumang oak | isang mahusay na barko ng karagatan | isang malaking pagkaantala
Progress: 0.05
translated_text: isang mahusay na gawa ng sining | Si Einstein ay isa sa mga natatanging pigura noong ika-20 siglo
Progress: 0.05
translated_text: isang malaking krisis | nagkaroon ng malaking taya sa kinalabasan
Progress: 0.05
translated_text: ginawa niyang bully job | isang maayos na sports car | nagkaroon ng magandang oras sa party | mukha ka lang bagsak
Progress: 0.05
translated_text: kabisera A | mahusay na A | maraming mga manuskrito sa medieval ang nasa script ng majuscule
Progress: 0.05
translated_text: ay malaki sa anak | ay mahusay na may anak
Progress: 0.05
translated_text: ang kanyang kasipagan ay nanalo sa kanya ng mabilis na promosyon | ang pagiging matipid at industriya ay itinuturing pa rin bilang mga birtud
Progress: 0.05
translated_text: mga visual na depekto | pinahihintulutan ng aparatong ito ang pagtuklas ng mga depekto sa mga baga
Progress: 0.05
translated_text: isang kapintasan ang naging sanhi ng pagkabasag ng kristal | kung mayroong anumang mga depekto dapat mong ipadala ito pabalik sa tagagawa
Progress: 0.05
translated_text: isang matinding pagtatalo | mapait tungkol sa diborsyo
Progress: 0.05
translated_text: ang mapait na katotohanan | isang mapait na kalungkutan
Progress: 0.05
translated_text: isang acerbic tone piercing kung hindi man ay mabulaklak na prosa | isang barrage ng acid comments | ang kanyang matalas na pananalita ay nagpaparami sa kanya ng mga kaaway | mapait na salita | paltos na pagpuna | mapanlinlang na mga biro tungkol sa pampulitikang pagpatay, mga host ng talk-show at medikal na etika | isang sulfurous denunciation | isang vitriolic critique
Progress: 0.05
translated_text: isang mapait na pakikibaka | mapait na mga kaaway
Progress: 0.05
translated_text: mapait na lamig | isang hanging nanunuot
Progress: 0.05
translated_text: ito ay napakalamig | mapait na lamig
Progress: 0.05
translated_text: Ang pagiging pamilyar sa panganib ay ginagawang mas matapang ngunit hindi gaanong matapang ang isang matapang na tao | isang lantad na matapang na puso...nagtagumpay sa sakit | magpakita ng isang matapang na halimbawa sa pamamagitan ng pag-akay sa kanila nang ligtas papasok at palabas sa teritoryong hawak ng kaaway
Progress: 0.05
translated_text: mapangahas na mga explorer | walang takot na mga reporter at photographer | matapang na mga pioneer
Progress: 0.05
translated_text: mga batang babae na nakasuot ng matapang na bagong damit | magigiting na mga banner na lumilipad | Ang `braw&#39; ay isang Scottish na salita | isang damit na medyo masyadong bakla para sa kanyang mga taon | mga ibong may gay na balahibo

Progress: 0.05
translated_text: ang ikatlong baseman ay gumawa ng ilang kapansin-pansing paghinto | ang kanyang pagtigil sa daloy ay nagresulta sa isang baha
Progress: 0.05
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.05
translated_text: huminto ang sasakyan | Huminto siya sa harap ng bintana ng tindahan
Progress: 0.05
translated_text: Harangan ang kanyang halalan | Itigil ang proseso
Progress: 0.05
translated_text: huminto kami sa bahay ni Tita Mary | huminto sila ng tatlong araw sa Florence
Progress: 0.05
translated_text: huminto ng kotse | pigilan ang magnanakaw
Progress: 0.06
translated_text: itigil ang proyekto | putulin ang negosasyon
Progress: 0.06
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.06
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.06
translated_text: harangan ang daan | barikada ang mga lansangan | itigil ang abalang kalsada
Progress: 0.06
translated_text: ang lamig ay kitang kita ang aming hininga | lumabas sa lamig | ang lamig ay isang vasoconstrictor
Progress: 0.06
translated_text: nanginginig siya sa lamig | ang lamig ay tumulong sa pag-alis ng kanyang ulo
Progress: 0.06
translated_text: isang malamig na klima | isang malamig na silid | lumamig na ang hapunan | malamig na mga daliri | kung nilalamig ka, pataasin mo ang init | isang malamig na beer
Progress: 0.06
translated_text: isang malamig na unfriendly na tango | isang malamig at hindi mapagmahal na tao | isang malamig na impersonal na paraan | malamig na lohika | ang concert ay iniwan ako ng malamig
Progress: 0.06
translated_text: isang malamig na landas | mga aso na nagtatangkang makatanggap ng malamig na amoy
Progress: 0.06
translated_text: mga teoryang kinakain ng gamugamo tungkol sa lahi | lipas na balita
Progress: 0.06
translated_text: malamig sa kanyang mga pagsulong | isang malamig na babae
Progress: 0.06
translated_text: sa malamig na dugo | malamig ang dugong pagpatay | walang kabuluhang pagkawasak
Progress: 0.06
translated_text: isang malamig na madla | malamig na tugon sa bagong dula
Progress: 0.06
translated_text: malamig ang boksingero | hinimatay ng malamig
Progress: 0.06
translated_text: isang kagalakang pagmasdan | ang kasiyahan ng kanyang kumpanya | ang bagong kotse ay isang kasiyahan
Progress: 0.06
translated_text: Ang mga kulay na ito ay nakalulugod sa mga pandama | isang kasiya-siyang sensasyon
Progress: 0.06
translated_text: isang mabangis na pambubugbog | matinding labanan | isang galit na galit na labanan
Progress: 0.06
translated_text: mabangis na katapatan | sa nakakaiyak na galit | matinding ayaw | marahas na hilig
Progress: 0.06
translated_text: cutthroat competition | walang bituka na kahandaang samantalahin
Progress: 0.06
translated_text: malalakas na hangin at alon | ang mabangis na kulog ay umuungal sa akin kanilang musika | masungit na panahon | maalon na dagat
Progress: 0.06
translated_text: matabang pagkain | matabang tissue
Progress: 0.06
translated_text: isang makatas na kontrata | isang magandang matabang trabaho
Progress: 0.06
translated_text: matabang lupang sakahan | isang matabang lupain | isang produktibong ubasan | mayamang lupa
Progress: 0.06
translated_text: sa huli kailangan niyang sumuko | sa wakas ay tapos na ang taglamig
Progress: 0.06
translated_text: maubos ang ipon | Mabilis naming nilaro ang aming lakas
Progress: 0.06
translated_text: pagod na mga ina na may umiiyak na mga sanggol | nakakapagod din kumain
Progress: 0.06
translated_text: bromidic sermons | ang kanyang mga pangungusap ay walang kabuluhan at karaniwan | hackneyed na mga parirala | isang stock na sagot | paulit-ulit na mga walang kwentang biro | parroting ilang timeworn axiom | ang trite metapora `matigas gaya ng mga pako&#39;
Progress: 0.06
translated_text: ang tela sa mga kurtina ay magaan at semitransparent | ang hinabing tela ay nagmula sa Mesopotamia noong mga 5000 BC | nagsukat siya ng sapat na materyal para sa isang damit
Progress: 0.06
translated_text: binigyan niya ng malakas na suntok ang ilong | hinipan niya ang lahat ng kandila sa isang puff
Progress: 0.06
translated_text: Ang mga dahon ay umiihip sa hangin | ang bangka ay naanod sa lawa | Ang bangka ay naaanod sa bukas na dagat | ang bangkang nawasak ay naanod palayo sa pampang
Progress: 0.06
translated_text: Nasira ko ang hapunan at kailangan naming kumain sa labas | ginulo ng piyanista ang mahirap na sipi sa ikalawang paggalaw
Progress: 0.06
translated_text: Sinayang niya ang kanyang mana sa kanyang mga kaibigang hindi tapat | Sinayang mo ang pagkakataong makakuha at advanced na degree
Progress: 0.06
translated_text: itulak mo! | Nagtulakan ang mga bata | Pumutok ngayon!
Progress: 0.06
translated_text: The story blew their cover | Ang dobleng ahente ay hinipan ng kabilang panig
Progress: 0.06
translated_text: Pumutok ang mga bombilya | Pumutok ang fuse
Progress: 0.06
translated_text: Pumutok ang gulong | Nagpabuga kami ng gulong
Progress: 0.06
translated_text: Nagmamadali siyang bumaba ng bulwagan upang tanggapin ang kanyang mga bisita | Ang mga sasakyan ay tumakbo sa kalsada
Progress: 0.06
translated_text: bukas na mundo | lahat ay umaasa para sa isang mas magandang bukas
Progress: 0.06
translated_text: ang kanyang karera ay nasa kanal | lahat ng gawaing iyon ay bumaba sa imburnal | ang mga pensiyon ay nasa palikuran
Progress: 0.06
translated_text: ang Panahon ng Puritan ay kulang sa kulay | ang mga karakter ay inilarawan nang may pambihirang liwanag
Progress: 0.06
translated_text: umaasa siya na ang kanyang mga paghahabol ay magkakaroon ng pagkakahawig ng pagiging tunay | sinubukan niyang bigyan ang kanyang kasinungalingan ng gloss ng moral na sanction | hindi nagtagal ay nagkaroon ng ibang kulay ang sitwasyon
Progress: 0.06
translated_text: Kinulayan ng bata ang mga guhit | Taglagas kulay ang mga puno | kulayan ang itim at puting pelikula
Progress: 0.06
translated_text: Ang aking personal na damdamin ay nagbibigay kulay sa aking paghatol sa kasong ito | Nababalot ng kalungkutan ang kanyang buhay
Progress: 0.06
translated_text: may kulay na pelikula | nagrenta siya ng color television | kahanga-hangang mga ilustrasyon ng kulay
Progress: 0.06
translated_text: Sinabi noon ni Al Smith, `Tingnan natin ang rekord&#39; | nasa lahat ng record books ang pangalan niya
Progress: 0.06
translated_text: magpareserba sa akin ng upuan sa isang flight | Nag-book ang ahente ng mga tiket sa palabas para sa buong pamilya | mangyaring humawak ng mesa sa Maxim&#39;s
Progress: 0.06
translated_text: Sinabi noon ni Al Smith, `Tingnan natin ang rekord&#39; | nasa lahat ng record books ang pangalan niya
Progress: 0.06
translated_text: magpareserba sa akin ng upuan sa isang flight | Nag-book ang ahente ng mga tiket sa palabas para sa buong pamilya | mangyaring humawak ng mesa sa Maxim&#39;s
Progress: 0.06
translated_text: siya ay may matalas na tainga | isang magandang tainga para sa pitch
Progress: 0.06
translated_text: sila ay pinagkalooban ng kanilang Tagapaglikha ng ilang mga Karapatan na hindi maipagkakaila | Ang ilang mga karapatan ay hindi kailanman maaaring ibigay sa pamahalaan ngunit dapat panatilihin sa mga kamay ng mga tao | ang karapatan ay hindi isang bagay na ibinibigay sa iyo ng isang tao; ito ay isang bagay na hindi maaaring alisin ng sinuman
Progress: 0.07
translated_text: nagsusulat siya gamit ang kanyang kanang kamay ngunit nag-pitch gamit ang kanyang kaliwang | tamaan siya ng mabilis na karapatan sa katawan
Progress: 0.07
translated_text: pakiramdam niya nasa kanan siya | ang katuwiran ng kanyang pag-angkin
Progress: 0.07
translated_text: mga karapatan sa mineral | mga karapatan sa pelikula
Progress: 0.07
translated_text: Itama ang mga pagkakamali | iwasto ang kalkulasyon

Progress: 0.07
translated_text: ang kanang kamay ko | kanang gitnang field | isang pagliko sa kanan | ang kanang pampang ng isang ilog ay ang pampang sa iyong kanang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.07
translated_text: ang tamang sagot | ang tamang bersyon | ang tamang sagot | tinahak ang tamang daan | ang tamang desisyon
Progress: 0.07
translated_text: hindi tama na umalis sa party ng walang paalam | tamang pag-uugali
Progress: 0.07
translated_text: lahat sa tamang lugar nito | ang tamang tao para sa trabaho | hindi siya bagay sa posisyon
Progress: 0.07
translated_text: bagay na naman ngayon | ayusin ang mga bagay
Progress: 0.07
translated_text: ano ang tamang salita para dito? | ang tamang paraan ng pagbubukas ng mga talaba
Progress: 0.07
translated_text: ang kanang bahagi ng tela ay nagpakita ng pattern | siguraduhin na ang iyong kamiseta ay nasa kanang bahagi sa labas
Progress: 0.07
translated_text: magandang panahon para magtanim ng kamatis | ang tamang oras para kumilos | ang panahon ay hinog na para sa malalaking pagbabago sa sosyolohikal
Progress: 0.07
translated_text: tumingin siya sa kanan at kaliwa | ang partido ay lumipat sa kanan
Progress: 0.07
translated_text: mangyaring gawin ang iyong trabaho ng maayos! | hindi mo ba ako kayang buhatin ng disente?
Progress: 0.07
translated_text: she felt right at home | nahulog siya sa bitag
Progress: 0.07
translated_text: ang baby ay mighty cute | siya ay matinding pagod | ito ay malakas na mahalumigmig | ang batang iyon ay makapangyarihang malaki na ngayon | mayroon silang tamang magandang lugar | sila&#39;y lubos na nagalak
Progress: 0.07
translated_text: na nagsisilbi sa kanya ng tama | gawin ang tama sa kanya
Progress: 0.07
translated_text: ang bulaklak ay wastong inilarawan ng kanyang anak na lalaki | tama ang hula niya
Progress: 0.07
translated_text: ginagawa niya nang eksakto (o eksakto) kung ano ang sinabi nito sa kanya na gawin | gaya nga ng sinabi niya--wala na ang hiyas | mayroon lamang itong sapat na asin
Progress: 0.07
translated_text: isang wastong hinuha | isang wastong argumento | isang wastong kontrata
Progress: 0.07
translated_text: isang tumpak na pagpaparami | tumpak ang accounting | tumpak na mga sukat | isang tumpak na sukat
Progress: 0.07
translated_text: isang tumpak na larawan | isang tumpak na sukat
Progress: 0.07
translated_text: siya ay lubos na kumbinsido | ganap na nasiyahan sa pagkain | ito ay ganap na naiiba mula sa kung ano ang aming inaasahan | ay ganap na may kasalanan | isang ganap na bagong sitwasyon | mali lahat ng direksyon | ito ay hindi lahat ng kanyang kasalanan | isang ganap na bagong diskarte | isang buong bagong ideya
Progress: 0.07
translated_text: napunan niya nang buo ang form | ang apartment ay ganap na inayos
Progress: 0.07
translated_text: sila ay pinagkalooban ng kanilang Tagapaglikha ng ilang mga Karapatan na hindi maipagkakaila | Ang ilang mga karapatan ay hindi kailanman maaaring ibigay sa pamahalaan ngunit dapat panatilihin sa mga kamay ng mga tao | ang karapatan ay hindi isang bagay na ibinibigay sa iyo ng isang tao; ito ay isang bagay na hindi maaaring alisin ng sinuman
Progress: 0.07
translated_text: nagsusulat siya gamit ang kanyang kanang kamay ngunit nag-pitch gamit ang kanyang kaliwang | tamaan siya ng mabilis na karapatan sa katawan
Progress: 0.07
translated_text: pakiramdam niya nasa kanan siya | ang katuwiran ng kanyang pag-angkin
Progress: 0.07
translated_text: mga karapatan sa mineral | mga karapatan sa pelikula
Progress: 0.07
translated_text: Itama ang mga pagkakamali | iwasto ang kalkulasyon
Progress: 0.07
translated_text: ang kanang kamay ko | kanang gitnang field | isang pagliko sa kanan | ang kanang pampang ng isang ilog ay ang pampang sa iyong kanang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.07
translated_text: ang tamang sagot | ang tamang bersyon | ang tamang sagot | tinahak ang tamang daan | ang tamang desisyon
Progress: 0.07
translated_text: hindi tama na umalis sa party ng walang paalam | tamang pag-uugali
Progress: 0.07
translated_text: lahat sa tamang lugar nito | ang tamang tao para sa trabaho | hindi siya bagay sa posisyon
Progress: 0.07
translated_text: bagay na naman ngayon | ayusin ang mga bagay
Progress: 0.07
translated_text: ano ang tamang salita para dito? | ang tamang paraan ng pagbubukas ng mga talaba
Progress: 0.07
translated_text: ang kanang bahagi ng tela ay nagpakita ng pattern | siguraduhin na ang iyong kamiseta ay nasa kanang bahagi sa labas
Progress: 0.07
translated_text: magandang panahon para magtanim ng kamatis | ang tamang oras para kumilos | ang panahon ay hinog na para sa malalaking pagbabago sa sosyolohikal
Progress: 0.07
translated_text: tumingin siya sa kanan at kaliwa | ang partido ay lumipat sa kanan
Progress: 0.07
translated_text: mangyaring gawin ang iyong trabaho ng maayos! | hindi mo ba ako kayang buhatin ng disente?
Progress: 0.07
translated_text: she felt right at home | nahulog siya sa bitag
Progress: 0.07
translated_text: ang baby ay mighty cute | siya ay matinding pagod | ito ay malakas na mahalumigmig | ang batang iyon ay makapangyarihang malaki na ngayon | mayroon silang tamang magandang lugar | sila&#39;y lubos na nagalak
Progress: 0.07
translated_text: na nagsisilbi sa kanya ng tama | gawin ang tama sa kanya
Progress: 0.07
translated_text: ang bulaklak ay wastong inilarawan ng kanyang anak | tama ang hula niya
Progress: 0.07
translated_text: ang pagsusulit ay puno ng mga tanong sa bitag | lahat ng ito ay isang silo at maling akala
Progress: 0.07
translated_text: Hurl&#39;d headlong...Sa napakalalim na kapahamakan, doon manirahan | isang demonyo mula sa kailaliman ng hukay | Ang impiyerno ay sementadong may mabuting hangarin
Progress: 0.07
translated_text: hayaan silang itugma ang kanilang pinakamahusay na mga atleta laban sa atin | pit isang chess player laban sa Russian champion | Pinaglalaruan niya ang kanyang dalawang anak laban sa isa&#39;t isa
Progress: 0.07
translated_text: sila ay napapanahon | wala pa kaming balita sa kanila hanggang ngayon
Progress: 0.07
translated_text: Alam mo bang may nakikita siyang matandang lalaki? | Nililigawan na naman niya ang dati niyang asawa!
Progress: 0.07
translated_text: isang pinagsamang sesyon ng Kongreso | magkasanib na mga may-ari
Progress: 0.07
translated_text: joint income-tax return | magkasanib na pagmamay-ari
Progress: 0.08
translated_text: isang ugali ng karerahan | isang bum na kabit ng Central Park
Progress: 0.08
translated_text: Maaari mo bang ikonekta ang dalawang loudspeaker? | Pagtaliin ang mga lubid | Mag-link ng mga braso
Progress: 0.08
translated_text: Hindi ko maiugnay ang dalawang piraso ng ebidensya sa aking isipan | isama ang mga katotohanang ito | Hindi ko ma-relate ang mga pangyayaring ito
Progress: 0.08
translated_text: Ang dalawang kalye ay nagkokonekta upang maging isang highway | Nagsanib ang aming mga landas | Muling nag-link ang mga manlalakbay sa airport
Progress: 0.08
translated_text: Ang lokal na tren ay hindi kumonekta sa Amtrak na tren | Ang mga eroplano ay hindi kumonekta at kailangan mong maghintay ng apat na oras
Progress: 0.08
translated_text: Pakisaksak ang toaster! | Ikonekta ang TV para mapanood natin ang football game ngayong gabi
Progress: 0.08
translated_text: ang timog na pader ay may maliit na bintana | ang mga dingding ay natatakpan ng mga larawan
Progress: 0.08
translated_text: isang pader ng tubig | isang pader ng usok | isang pader ng pagtatangi | ang mga negosasyon ay tumakbo sa isang brick wall
Progress: 0.08
translated_text: ang kanyang likod ay sa pader | ang kumpetisyon ay nagtutulak sa kanila sa pader
Progress: 0.08
translated_text: ang mga dingding ng silindro ay butas-butas | ang mga dingding ng lalagyan ay asul
Progress: 0.08
translated_text: sinundan ng pader ang kalsada | dumeretso siya sa likod ng garden wall at naghintay
Progress: 0.08
translated_text: nilusob nila ang kuta ng lungsod | hinipan nila ang trumpeta at ang mga pader ay bumagsak
Progress: 0.08
translated_text: hindi mo ako binigyan ng sapat na paunawa | isang obituary notice
Progress: 0.08
translated_text: nakatanggap kami ng paunawa na lisanin ang lugar | nagbigay siya ng abiso dalawang buwan bago siya lumipat

Progress: 0.08
translated_text: Nakita niya ang mataas na antas ng tingga sa kanyang inuming tubig | May nakita kaming bakas ng tingga sa pintura
Progress: 0.08
translated_text: Napansin niyang may sumusunod sa kanya | markahan ang aking mga salita
Progress: 0.08
translated_text: Hindi niya kinikilala ang kanyang mga kasamahan kapag nakasalubong nila siya sa hallway | She acknowledged his complement with a smile | mahalagang kilalanin ang gawa ng iba sa sariling sulatin
Progress: 0.08
translated_text: Natagpuan namin ang ideyang ito sa Plato | Nangyari ako sa pinakakahanga-hangang panaderya sa hindi kalayuan dito | Nakakita siya ng isang kawili-wiling libro sa bookstore noong isang araw
Progress: 0.08
translated_text: Nakita niya ang mataas na antas ng tingga sa kanyang inuming tubig | Nakakita kami ng mga bakas ng tingga sa pintura
Progress: 0.08
translated_text: Nahanap mo ba ang iyong salamin? | Hindi ko mahanap ang aking guwantes!
Progress: 0.08
translated_text: hanapin ang produkto ng dalawang numero | Ang physicist na nakahanap ng mailap na particle ay nanalo ng Nobel Prize
Progress: 0.08
translated_text: Feeling ko hindi niya ako gusto | I find him to be obnoxious | Nakita kong medyo nakakaaliw ang pelikula
Progress: 0.08
translated_text: Natagpuan namin ang mga Republican na nanalo sa mga opisina | Marami kang makikitang dayaan sa paaralang ito | Noong 1960&#39;s nakita ang paghihimagsik ng nakababatang henerasyon laban sa mga itinatag na tradisyon | Gusto kong makita ang mga resulta
Progress: 0.08
translated_text: Natagpuan ko ang gadget na ito na magsisilbing pambukas ng bote | Nakuha ko ang mga tool na ito upang ayusin ang aming pagtutubero | Hinawakan ng chairman ang isang sekretarya noong Biyernes ng gabi upang i-type ang apurahang liham
Progress: 0.08
translated_text: Natuklasan ni Roentgen ang mga X-ray | Naniniwala ang mga physicist na nakakita sila ng bagong elementary particle
Progress: 0.08
translated_text: Nalaman niyang nagsinungaling ito sa kanya | Mali ang kwento, sa abot ng aking matuklasan
Progress: 0.08
translated_text: Nakahanap siya ng oras at lakas para alagaan ang kanyang tumatanda nang mga magulang | Nakahanap kami ng pera para maipaaral sa kolehiyo ang aming mga anak
Progress: 0.08
translated_text: Ang mga aspetong ito ng sibilisasyon ay hindi nakakahanap ng pagpapahayag o tumatanggap ng interpretasyon | Nakatanggap ng magandang review ang kanyang pelikula | Wala akong nakuha kundi gulo para sa aking mabuting hangarin
Progress: 0.08
translated_text: Natagpuan ko ang aking sarili sa isang mahirap na sitwasyon | Nang magising siya, natagpuan niya ang kanyang sarili sa isang silid ng ospital
Progress: 0.08
translated_text: Nabawi niya ang kontrol sa sarili | Hinanap niya ang boses niya at mabilis na sumagot
Progress: 0.08
translated_text: ang kanyang mga editoryal ay nagbigay ng sasakyan para sa kanyang pampulitikang pananaw | ang isang kongregasyon ay isang sasakyan ng pagkakakilanlan ng grupo | ang dula ay isang sasakyan lamang upang ipakita ang kanyang mga talento
Progress: 0.08
translated_text: sa susunod na araw | susunod sa linya | ang susunod na pangulo | ang susunod na aytem sa listahan
Progress: 0.08
translated_text: nagkaroon ng mga katabing silid | sa susunod na silid | yung taong nakaupo sa tabi ko | magkatabi ang mga kwarto namin
Progress: 0.08
translated_text: nagtrabaho siyang parang demonyo para matapos ang trabaho sa oras | demonyo siya sa math
Progress: 0.08
translated_text: ano ang demonyo | ang deuce kasama nito | ang mga dickens na sinasabi mo
Progress: 0.08
translated_text: Nakakainis talaga ang mga lamok sa tenga ko | Naiirita ako na hindi niya isinasara ang pinto pagkatapos niyang umalis
Progress: 0.08
translated_text: isang maliit na silid-kainan | isang maliit na bahay | isang maliit na kotse | isang maliit (o maliit) na grupo
Progress: 0.08
translated_text: isang maliit na negosyo | isang pahayagan na may katamtamang sirkulasyon | maliliit na plano | isang pocket-size na bansa
Progress: 0.08
translated_text: anong laking bata ka | maliliit na bata
Progress: 0.08
translated_text: isang hamak na cottage | isang mababang kura paroko | isang mahinhin na tao ng mga tao | maliliit na simula
Progress: 0.08
translated_text: maliit na | maliit na | Ang tula ni eecummings ay nakasulat lahat sa maliliit na letra
Progress: 0.08
translated_text: isang maliit na boses | isang maliit na boses
Progress: 0.08
translated_text: isang maliit na suweldo | katamtamang inflation | nakatulong sa aking maliit na paraan
Progress: 0.08
translated_text: ang parehong lalaki na nakita ko kahapon | hindi kailanman nagsuot ng parehong damit nang dalawang beses | ang kalsadang ito ay pareho sa dinaanan namin kahapon | sa parehong gilid ng kalye
Progress: 0.08
translated_text: mga kurtina na kapareho ng kulay ng mga dingding | dalawang batang babae sa parehong edad | ang mag-ina ay may parehong asul na mata | mga hayop ng parehong species | ang parehong mga patakaran tulad ng dati | dalawang kahon na may parehong sukat | sa parehong araw sa susunod na taon
Progress: 0.08
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.08
translated_text: ang nayon ay nanatiling pareho | ang kanyang ugali ay katulad ng dati
Progress: 0.08
translated_text: indibidwal na patak ng ulan | mangyaring markahan ang mga indibidwal na pahina | nagpunta sila sa kani-kanilang paraan
Progress: 0.08
translated_text: markahan ang mga indibidwal na pahina | sa isang case-by-case na batayan
Progress: 0.08
translated_text: isang indibidwal na naglilingkod | single occupancy | isang single bed
Progress: 0.09
translated_text: lahat tayo ay may kanya-kanyang sasakyan | bawat kuwarto ay may pribadong paliguan
Progress: 0.09
translated_text: bawat bayan ay may kanya-kanyang kalidad | ang radikal na katangian ng ating mga hinihingi
Progress: 0.09
translated_text: isang tunay na karakter | kakaibang karakter | isang magiliw sira-sira | ang may kakayahang uri | isang mental case
Progress: 0.09
translated_text: ang kanilang iba&#39;t ibang mga reaksyon ay sumasalamin sa kanilang magkaibang mga personalidad | likas na sa kanya ang tumulong sa kapwa
Progress: 0.09
translated_text: Pleistocene vegetation | ang flora ng southern California | ang botany ng China
Progress: 0.09
translated_text: Trabaho ang lupa | linangin ang lupa
Progress: 0.09
translated_text: walang kasunduan sa pagitan ng teorya at pagsukat | ang mga resulta ng dalawang pagsusulit ay nasa sulat
Progress: 0.09
translated_text: ang magandang negosyo ay nakasalalay sa pagkakaroon ng magandang paninda | nag-aalok ang tindahang iyon ng iba&#39;t ibang produkto
Progress: 0.09
translated_text: pinagbubuti nila ang kanilang produkto bawat taon | iniluluwas nila ang karamihan sa kanilang produksyong pang-agrikultura
Progress: 0.09
translated_text: kasanayan ay ang produkto ng oras ng pagsasanay | ang kanyang reaksyon ay bunga ng gutom at pagod
Progress: 0.09
translated_text: para sa iyong ikabubuti | ano ang mabuting mag-alala?
Progress: 0.09
translated_text: timbangin ang mabuti laban sa masama | kabilang sa pinakamataas na kalakal sa lahat ay ang kaligayahan at pagsasakatuparan sa sarili
Progress: 0.09
translated_text: may tatlong palapag na gusali sa kanto | ito ay isang kahanga-hangang edipisyo
Progress: 0.09
translated_text: sa panahon ng konstruksiyon kailangan naming lumihis | ang kanyang libangan ay ang paggawa ng mga bangka
Progress: 0.09
translated_text: ang kanilang pangunahing negosyo ay paggawa ng bahay | ang mga manggagawa sa gusali ay nangangalakal
Progress: 0.09
translated_text: ginawa ng maliit na baboy na ito ang kanyang bahay sa dayami | Ang ilang sira-sira ay gumawa ng electric brassiere warmer
Progress: 0.09
translated_text: Mabilis na nabuo ang paglaban sa plano ng manager | Lumalakas ang presyon sa hangganan ng India-Pakistani
Progress: 0.09
translated_text: bumuo ng isang modernong bansa | bumuo ng isang milyong dolyar na negosyo
Progress: 0.09
translated_text: Gumawa kami ng lakas ng loob | bumuo ng tiwala | palakasin ang seguridad sa mga paliparan
Progress: 0.09
translated_text: ang tela sa mga kurtina ay magaan at semitransparent | ang hinabing tela ay nagmula sa Mesopotamia noong mga 5000 BC | nagsukat siya ng sapat na materyal para sa isang damit

Progress: 0.09
translated_text: mayroon silang masyadong maraming kasangkapan para sa maliit na apartment | may isang kasangkapan lang sa kwarto
Progress: 0.09
translated_text: Humingi ako ng mainit na inumin | mahilig uminom bago maghapunan
Progress: 0.09
translated_text: isang lunok ng likido ay sapat na | uminom siya ng beer niya at hinaplos ang labi niya
Progress: 0.09
translated_text: Ang pasyente ay dapat uminom ng ilang litro bawat araw | Ang mga bata ay gustong uminom ng soda
Progress: 0.09
translated_text: I-toast natin ang birthday girl! | Inom tayo sa Bagong Taon
Progress: 0.09
translated_text: Ang Canada ay katabi ng US | Nagmartsa ang England kasama ang Scotland
Progress: 0.09
translated_text: may mga limitasyon sa halagang maaari mong taya | mabilis itong lumalago nang walang nakikitang limitasyon
Progress: 0.09
translated_text: kailangan naming magbihis ng mabilis | bihisan ang pasyente | Maaari bang magbihis ang bata nang mag-isa?
Progress: 0.09
translated_text: Nagdamit siya sa pinakabagong fashion ng Paris | nagbihis siya ng suit and tie
Progress: 0.09
translated_text: mag-ayos ng mga aso | bihisan ang mga kabayo
Progress: 0.09
translated_text: ang matikas na kasuotan ginoo | mga manggagawang maayos ang pananamit | mga monghe na nakasuot ng hood na damit | nagpunta tungkol sa kakaiba bihisan | mga propesor na nakasuot ng pulang-pula | mga ginoong nakasuot ng tuxedo | mga propesor sa Harvard na nakasuot ng pulang-pula
Progress: 0.09
translated_text: hilig ng hayop | makalaman na kaalaman | makalamang pagnanasa | isang senswal na kasiyahan sa pagkain | musika ang tanging senswal na kasiyahan na walang bisyo
Progress: 0.09
translated_text: ang laki na ng sitwasyon | she hates me, ang laki naman nun
Progress: 0.09
translated_text: namula siya nang makita ang laki ng bill | ang tanging lungsod ng anumang laki sa lugar na iyon
Progress: 0.09
translated_text: ang economic-size package | katamtamang laki ng bahay
Progress: 0.09
translated_text: Iginagalang ko ang kanyang paghatol | Pinahahalagahan namin ang kanyang pagkamalikhain
Progress: 0.09
translated_text: Ipapasuri ko ang mga alahas ng pamilya ng isang propesyonal | i-access ang lahat ng mga kadahilanan kapag kumukuha ng panganib
Progress: 0.09
translated_text: Paano mo ire-rate ang kanyang mga pagkakataon na maging Presidente? | Ang ginto ay mataas ang rating sa mga Romano
Progress: 0.09
translated_text: ang pabagu-bagong halaga ng pera ng ginto at pilak | naglalagay siya ng mataas na presyo sa kanyang mga serbisyo | hindi niya makalkula ang halaga ng koleksyon
Progress: 0.09
translated_text: ang presyo ng gasolina | nakuha niya ang kanyang bagong kotse sa mahusay na mga tuntunin | magkano ang damage?
Progress: 0.09
translated_text: ang halaga sa buhay ng tao ay napakalaking | ang presyo ng tagumpay ay mahirap na trabaho | anong presyo ng kaluwalhatian?
Progress: 0.09
translated_text: sa hilaw na | sa kabuuan | sa kanyang birthday suit
Progress: 0.09
translated_text: natural na yogurt | natural na ani | hilaw na lana | hilaw na asukal | bales ng bastos na bulak
Progress: 0.09
translated_text: hubad na ambisyon | galit na galit | maaari kang makapatay ng isang tao balang araw gamit ang iyong hilaw na kapangyarihan
Progress: 0.09
translated_text: nakatanggap ng hilaw na paggamot mula sa kanyang mga kaibigan | isang raw deal
Progress: 0.09
translated_text: raw data | ang hilaw na halaga ng produksyon | tanging ang krudo na mahahalagang istatistika
Progress: 0.09
translated_text: hilaw na talento | hilaw na kagandahan
Progress: 0.09
translated_text: ang mga bagong lalaki ay sabik na lumaban | mga hilaw na recruit
Progress: 0.09
translated_text: isang bagong batas | mga bagong sasakyan | isang bagong kometa | isang bagong kaibigan | isang bagong taon | ang bagong daigdig
Progress: 0.09
translated_text: ang mga bagong lalaki ay sabik na lumaban | mga hilaw na recruit
Progress: 0.09
translated_text: mayroon na silang bagong mga pinuno | apat na taong gulang na ang aking bagong sasakyan ngunit may 15,000 milya lamang dito | handang tumahak sa bagong direksyon
Progress: 0.10
translated_text: mga bagong ideya | binibili niya ang lahat ng bagong-fangled na makinang ito at hindi kailanman ginagamit ang mga ito
Progress: 0.10
translated_text: Modernong Ingles | Ang Bagong Hebrew ay Israeli Hebrew
Progress: 0.10
translated_text: bagong patatas | batang mais
Progress: 0.10
translated_text: mga bagong karanasan | mga bagong karanasan sa kanya | mga pagkakamali ng isang bago sa trabaho
Progress: 0.10
translated_text: sila ay bagong kasal | bagong itinaas na pagtutol | isang bagong ayos ng buhok | damo bagong hugasan ng ulan | isang bagong linis na sahig | sariwa pa tayo sa kamatis
Progress: 0.10
translated_text: isang berdeng puno | berdeng mga patlang | berdeng pintura
Progress: 0.10
translated_text: hilaw na prutas | piniritong berdeng kamatis | berdeng kahoy
Progress: 0.10
translated_text: mukha kang berde | berde sa paligid ng hasang
Progress: 0.10
translated_text: isang berdeng puno | berdeng mga patlang | berdeng pintura
Progress: 0.10
translated_text: hilaw na prutas | piniritong berdeng kamatis | berdeng kahoy
Progress: 0.10
translated_text: mukha kang berde | berde sa paligid ng hasang
Progress: 0.10
translated_text: ang pagpupumilit ng kanilang gutom | mahalaga ang press ng negosyo
Progress: 0.10
translated_text: binigyan niya ng isang pindutin ang button | gumamit siya ng pressure para pigilan ang pagdurugo | sa pagpindot ng isang pindutan
Progress: 0.10
translated_text: Pinindot niya ang mga board | pindutin ang iyong hinlalaki sa lugar na ito
Progress: 0.10
translated_text: mabigat sa isip | May gumugulo sa kanyang isipan
Progress: 0.10
translated_text: piniga niya ang kanyang mga labi | ang spasm ay nagkontrata sa kalamnan
Progress: 0.10
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Ang Dean ay nagtutulak para sa kanyang paboritong kandidato
Progress: 0.10
translated_text: pindutin ang iyong mga kamiseta | nakatayo siya doon na namamalantsa
Progress: 0.10
translated_text: isang barbarous na krimen | brutal na pambubugbog | malupit na pagpapahirap | Ang magaspang na pagtrato ni Stalin sa mga kulak | isang mabangis na sampal | masasamang sipa
Progress: 0.10
translated_text: istorbo ang paghuhugas ng pinggan bago kami kumuha ng dish washer | medyo nakakaabala | hindi siya kaibigan, siya ay isang infliction
Progress: 0.10
translated_text: Matapos uminom ng sobra, nagsuka ang mga estudyante | Tuluy-tuloy siyang nagpurga | Ni-regurgitate ng pasyente ang pagkain na binigay namin sa kanya kagabi
Progress: 0.10
translated_text: lalong nandidiri | sawa na sa mga reklamo nila | sakit ng lahat | sakit sa kamatayan ng pagsuyo | tsismis na nakakasakit | pagod sa ingay at usok
Progress: 0.10
translated_text: ang maputlang liwanag ng kalahating buwan | isang maputlang araw | ang liwanag ng hapon na dumarating sa mga el track ay nahulog sa maputlang pahaba sa kalye | isang maputla na langit | ang maputla (o wan) na mga bituin | ang liwanag ng madaling araw
Progress: 0.10
translated_text: nakaupong ganap, may sakit sa inggit | siya ay may sakit sa pananabik
Progress: 0.10
translated_text: malagim na sugat | ang mabangis na resulta ng pambobomba | ang malagim na gawain ng paglibing sa mga biktima | isang malagim na pagpatay | malagim na katibayan ng sakripisyo ng tao | malagim na mga kuwento ng digmaan at salot sa Middle Ages | malagim na pagpapahirap na ipinaglihi ng mga baliw
Progress: 0.10
translated_text: ang buong lungsod ay naapektuhan ng hindi maaalis na kalamidad | ang lindol ay isang kalamidad
Progress: 0.10
translated_text: Namatay siya sa cancer | Ang mga bata ay namatay sa apoy | Ang pasyente ay pumunta nang mapayapa | Sinipa ng matandang lalaki ang balde sa edad na 102
Progress: 0.10
translated_text: Namamatay ako sa kahihiyan nang matuklasan ang aking munting kasinungalingan | Halos mamatay kami sa kakatawa nung palabas
Progress: 0.10
translated_text: Ang makina sa wakas ay umalis | Namatay ang sasakyan sa kalsada | Nasira ang bus na sinakyan namin habang papunta sa bayan | Nasira ang coffee maker | Nabigo ang makina habang papunta sa bayan | ang kanyang paningin ay napunta pagkatapos ng aksidente

Progress: 0.10
translated_text: Siya ay namamatay para sa isang sigarilyo | Nahihiya akong umalis
Progress: 0.10
translated_text: Namatay ang kanilang galit | Mamamatay ang sikreto ko kasama ko!
Progress: 0.10
translated_text: dulo ng pier | binuhol niya ang dulo ng thread | sumakay sila hanggang sa dulo ng linya | ang mga terminal ng anterior arches ng fornix
Progress: 0.10
translated_text: katapusan ng taon | ang pagtatapos ng panahon ng warranty
Progress: 0.10
translated_text: kapana-panabik ang wakas | Kinailangan kong ma-miss ang huling bahagi ng pelikula
Progress: 0.10
translated_text: ibinigay namin ito sa dulo ng seksyon dahil kinasasangkutan nito ang calculus | Magsimula sa simula at magpatuloy hanggang sa makarating ka sa dulo
Progress: 0.10
translated_text: siya ay dumating sa isang masamang wakas | ang tinatawag na maluwalhating eksperimento ay dumating sa isang nakakahiya na wakas
Progress: 0.10
translated_text: tumunog ang telepono sa kabilang dulo | magkasabay na isinulat ang magkabilang dulo
Progress: 0.10
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.10
translated_text: Tinapos niya ang kanilang pagkakaibigan nang malaman niyang minsan na itong nahatulan ng isang krimen | Ang pag-atake sa Poland ay nagwakas sa medyo mapayapang panahon pagkatapos ng WW I
Progress: 0.10
translated_text: Dinanas niya ang parusa | Maraming mga santo ang dumanas ng pagkamartir
Progress: 0.10
translated_text: Nagdusa siya ng bali sa aksidente | Nagkaroon siya ng insulin shock pagkatapos kumain ng tatlong candy bar | Nagkaroon siya ng pasa sa binti | Nabali ang braso niya sa scuffle
Progress: 0.10
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.10
translated_text: matugunan ang isang marahas na kamatayan | magdusa ng isang kakila-kilabot na kapalaran
Progress: 0.10
translated_text: nanlumo at miserable siya | isang mensahe ng pag-asa para sa naghihirap na sangkatauhan | kawawang mga bilanggo na nagsisiksikan sa mabahong mga kulungan
Progress: 0.10
translated_text: hindi sapat na pagsasanay | ang mga tauhan ay hindi sapat | hindi siya pantay sa gawain
Progress: 0.10
translated_text: isang hindi sapat na kita | mahinang suweldo | maikli ang pera | sa maikling rasyon | kulang ang pagkain | kapos sa karanasan
Progress: 0.10
translated_text: saktan ang lahat ng batas ng sangkatauhan | lumalabag sa mga pangunahing batas o sibilisasyon ng tao | lumabag sa batas | sirain ang isang pangako
Progress: 0.10
translated_text: Huwag labagin ang aking hardin | lumalabag sa aking privacy
Progress: 0.10
translated_text: lapastanganin ang isang sementeryo | lumalabag sa kabanalan ng simbahan | lapastanganin ang pangalan ng Diyos
Progress: 0.10
translated_text: Sinira mo ang kotse ko sa pagbuhos ng asukal sa tangke! | Sinira ng luha ang make-up niya
Progress: 0.11
translated_text: Masisira ako ng magarbong kasal ng anak ko! | Ang pagbagsak sa mga pamilihan sa pananalapi ay bumagsak sa kanya
Progress: 0.11
translated_text: pagkatapos ng rebolusyon ang aristokrasya ay natapos | ang hindi matagumpay na pagtakbo sa pwesto ay nagdulot sa kanya ng pagkasira sa pulitika at ekonomiya
Progress: 0.11
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.11
translated_text: Napaiyak siya nang marinig ang balita ng pagkamatay nito | Napaiyak sa pagkadismaya ang batang babae sa wheelchair nang hindi siya makaakyat sa hagdan
Progress: 0.11
translated_text: `Nanalo ako!&#39; bulalas niya | `Tulong!&#39; umiyak siya | `Nandito na ako,&#39; sigaw ng ina nang makitang naliligaw ang kanyang anak
Progress: 0.11
translated_text: bago tayo magkaroon ng mga pahayagan, isang sumisigaw ng bayan ang sumisigaw ng balita | Iniyakan niya ang kanyang mga paninda sa palengke
Progress: 0.11
translated_text: uminom siya para malunod ang kanyang kalungkutan | sumulat siya ng isang tala na nagpapahayag ng kanyang panghihinayang | sa kanyang rue, ang pagkakamali ay nagdulot sa kanya ng laro
Progress: 0.11
translated_text: Buong araw nagrereklamo ang nanay ko | Marami siyang dapat sipain
Progress: 0.11
translated_text: Ikinalulungkot ko ang pagalit na pagkilos na ito | ikinalungkot namin ang pagkawala ng mga benepisyo
Progress: 0.11
translated_text: isang batch ng mga titik | isang deal ng problema | maraming pera | gumawa siya ng mint sa stock market | tingnan ang iba pang mga nanalo sa aming malaking passel ng mga larawan | ito ay dapat magkaroon ng maraming gastos | isang patay na mamamahayag | isang balumbon ng pera
Progress: 0.11
translated_text: ihiwalay ang mga mandirigma sa misa | kapangyarihan sa mga tao
Progress: 0.11
translated_text: mas mura kung bilhin ito nang maramihan | nakatanggap siya ng mass of correspondence | ang dami ng mga export
Progress: 0.11
translated_text: kasama sa pinagsama-samang gastos ang mga gastos ng lahat ng dibisyon na pinagsama para sa buong taon | ang pinagsama-samang halaga ng pagkakautang
Progress: 0.11
translated_text: dalawang taon na ang nakalipas | Ang `agone&#39; ay isang archaic na salita para sa `ago&#39;
Progress: 0.11
translated_text: matagal na ang nakalipas | animnapung taon na ang nakalipas nang dumating ang aking lolo sa US
Progress: 0.11
translated_text: ang mga solusyon kahapon ay hindi sapat na mabuti | marami kaming pinagsaluhan kahapon
Progress: 0.11
translated_text: gulat sa stock market | isang takot sa digmaan | isang bomb scare ang nagbunsod sa kanila upang lumikas sa gusali
Progress: 0.11
translated_text: isang masusing paghahanap sa mga ledger ay nagsiwalat ng walang | ang kinalabasan ay nagbigay-katwiran sa paghahanap
Progress: 0.11
translated_text: Ang pulisya ay naghahanap ng mga pahiwatig | Hinahanap nila ang nawawalang lalaki sa buong county
Progress: 0.11
translated_text: Buong araw kaming naghanap at sa wakas ay natagpuan namin ang bata sa kagubatan | Maghanap sa ibang lugar para sa perpektong regalo!
Progress: 0.11
translated_text: kinailangan ng mga mag-aaral na magsaliksik sa kasaysayan ng Ikalawang Digmaang Pandaigdig para sa kanilang proyekto sa kasaysayan | Naghanap siya ng impormasyon sa kanyang mga kamag-anak sa web | Sinasaliksik ng mga siyentipiko ang kalikasan ng kamalayan
Progress: 0.11
translated_text: Hinalughog ng pulisya ang suspek | Hinalughog namin sa buong bahay ang nawawalang susi
Progress: 0.11
translated_text: Hinabol ng pulis ang magnanakaw sa eskinita | hinabol ng aso ang kuneho
Progress: 0.11
translated_text: Hinabol ng pulis ang magnanakaw sa eskinita | hinabol ng aso ang kuneho
Progress: 0.11
translated_text: gumawa sila ng pagsusuri sa mga nilalaman | isang pagsusuri sa pagiging maaasahan nito sa ilalim ng stress
Progress: 0.11
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.11
translated_text: ginawa nilang tseke ang kanilang kagamitan | tumakbo ang piloto sa pamamaraan ng pag-check-out
Progress: 0.11
translated_text: suriin ang preno | Tingnan ang makina
Progress: 0.11
translated_text: tingnan ang bulung-bulungan | suriin ang oras ng klase
Progress: 0.11
translated_text: Pinatunayan niya na ang mga balbula ay sarado | Tingnan na ang mga kurtina ay sarado | kontrolin ang kalidad ng produkto
Progress: 0.11
translated_text: i-moderate ang iyong pag-inom ng alak | hawakan mo ang iyong dila | pigilin mo ang iyong init ng ulo | kontrolin ang iyong galit
Progress: 0.11
translated_text: Pakisuri ang bawat pangalan sa listahan | lagyan ng tsek ang mga item | markahan ang mga yunit
Progress: 0.11
translated_text: Ang dalawang kuwento ay hindi magkasundo sa maraming detalye | Sinusuri ng sulat-kamay ang pirma sa tseke | Hindi tugma ang fingerprints ng suspek sa nasa baril

Progress: 0.11
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.11
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.11
translated_text: Gusto kong makita kung nagsasalita siya ng French | Tingnan kung gumagana ito | alamin kung nagsasalita siya ng Russian | Suriin kung aalis ang tren sa oras
Progress: 0.11
translated_text: suriin ang baybay ng salitang ito | suriin ang iyong mga katotohanan
Progress: 0.11
translated_text: sinusubaybayan namin ang kalidad ng hangin | binabantayan ng mga pulis ang mga galaw ng suspek
Progress: 0.11
translated_text: Nahihirapan akong maalala ang mga pangalan ng lahat ng aking mga kakilala | kaibigan tayo ng pamilya
Progress: 0.11
translated_text: lahat ng kanilang mga tagasuporta ay lumabas para sa laro | magkakaibigan sila ng library
Progress: 0.11
translated_text: binigyan niya ng malakas na tulak ang pinto | magandang ehersisyo ang pagtulak
Progress: 0.11
translated_text: ang pagtulak ng tubig sa mga dingding ng tangke | ang tulak ng mga jet engine
Progress: 0.11
translated_text: ang elevator ay pinaandar ng mga push button | ang pagtulak sa tabi ng kama ay nagpaandar ng buzzer sa desk
Progress: 0.11
translated_text: Ang tindero ay agresibong itinutulak ang bagong modelo ng computer | Ang kumpanya ay labis na nag-a-advertise ng kanilang mga bagong laptop
Progress: 0.11
translated_text: Nagsabunot siya ng maraming taon para magkaroon ng disenteng pamumuhay | Kailangan nating mag-push ng kaunti para ma-deadline! | Siya ay nagtutulak sa kanyang tesis ng doktor
Progress: 0.11
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Itinutulak ng Dean ang kanyang paboritong kandidato
Progress: 0.11
translated_text: binigyan niya ng malakas na tulak ang pinto | magandang ehersisyo ang pagtulak
Progress: 0.11
translated_text: ang pagtulak ng tubig sa mga dingding ng tangke | ang tulak ng mga jet engine
Progress: 0.11
translated_text: ang elevator ay pinaandar ng mga push button | ang pagtulak sa tabi ng kama ay nagpaandar ng buzzer sa desk
Progress: 0.11
translated_text: Ang tindero ay agresibong itinutulak ang bagong modelo ng computer | Ang kumpanya ay labis na nag-a-advertise ng kanilang mga bagong laptop
Progress: 0.12
translated_text: Nagsabunot siya ng maraming taon para magkaroon ng disenteng pamumuhay | Kailangan nating mag-push ng kaunti para ma-deadline! | Siya ay nagtutulak sa kanyang tesis ng doktor
Progress: 0.12
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Itinutulak ng Dean ang kanyang paboritong kandidato
Progress: 0.12
translated_text: tinamaan niya ng buong lakas na kaya niyang ibigay | nawasak ito sa lakas ng unos | ang isang pamahalaan ay walang sigla at puwersa ng isang buhay na tao
Progress: 0.12
translated_text: ang mahiwagang presensya ng isang masamang kapangyarihan | nawa&#39;y sumaiyo ang puwersa | ang mga puwersa ng kasamaan
Progress: 0.12
translated_text: Pinilit niya siyang kumuha ng trabaho sa lungsod | Pinisil niya ito para sa impormasyon
Progress: 0.12
translated_text: Siya rammed kanyang isip sa focus | Ginagalit niya ako
Progress: 0.12
translated_text: gumuhit ng kariton | hilahin ang isang kareta
Progress: 0.12
translated_text: tinamaan niya ng buong lakas na kaya niyang ibigay | nawasak ito sa lakas ng unos | ang isang pamahalaan ay walang sigla at puwersa ng isang buhay na tao
Progress: 0.12
translated_text: ang misteryosong presensya ng isang masamang kapangyarihan | nawa&#39;y sumaiyo ang puwersa | ang mga puwersa ng kasamaan
Progress: 0.12
translated_text: Pinilit niya siyang kumuha ng trabaho sa lungsod | Pinisil niya ito para sa impormasyon
Progress: 0.12
translated_text: Siya rammed kanyang isip sa focus | Ginagalit niya ako
Progress: 0.12
translated_text: gumuhit ng kariton | hilahin ang isang kareta
Progress: 0.12
translated_text: ang biglaang martilyo ng mga kamao ang nahuli sa kanya | ang paghampas ng mga paa sa pasilyo
Progress: 0.12
translated_text: kinatok ng tindero ang kumakatok sa pinto | isang Southern Baptist na mahilig sa bibliya
Progress: 0.12
translated_text: ram ang gate gamit ang isang sledgehammer | kumatok sa pinto
Progress: 0.12
translated_text: inasam niya ang pagdampi ng kanyang kamay | ang malamig na dampi ng hangin sa gabi
Progress: 0.12
translated_text: may bahid ng panunuya sa tono niya | may nakita siyang multo ng ngiti sa mukha nito
Progress: 0.12
translated_text: nakipag-ugnayan ang piloto sa base | nakipag-ugnayan siya sa kanyang mga kasamahan
Progress: 0.12
translated_text: gusto niya ang dampi ng seda sa kanyang balat | ang ibabaw ay nagkaroon ng mamantika na pakiramdam
Progress: 0.12
translated_text: Pindutin ang bato para sa suwerte | Hindi niya ginalaw ang kanyang asawa
Progress: 0.12
translated_text: Isang nakakapukaw na pelikula | Naantig ako sa iyong magiliw na liham ng pakikiramay
Progress: 0.12
translated_text: Mayroong maraming mga katanungan na tumutukoy sa kanyang talumpati | Ang aking sinabi ay nauukol sa iyong mga naunang komento
Progress: 0.12
translated_text: Ang dalawang gusali ay magkadikit | Nagdampi ang kanilang mga kamay | Ang wire ay hindi dapat makipag-ugnayan sa metal na takip | Ang mga ibabaw ay nakikipag-ugnay sa puntong ito
Progress: 0.12
translated_text: Hindi ko siya hawakan ng sampung talampakang poste | Ang lokal na Mafia ay hindi hawakan ang pagsusugal
Progress: 0.12
translated_text: Ang sikat ng araw ay umabot sa dingding | Maabot kaya niya? | Hindi dapat hawakan ng upuan ang dingding
Progress: 0.12
translated_text: Walang makakaagaw sa cotton para sa tibay | Hindi man lang naaapektuhan ng iyong pagganap ang iyong mga kasamahan | Ang kanyang pagpupursige at ambisyon ay tumutugma lamang sa kanyang mga magulang
Progress: 0.12
translated_text: kulay blond ang kanyang uban na buhok | ang mga dahon ay may kulay pula noong Nobyembre
Progress: 0.12
translated_text: Ang trapiko sa New York ay palaging alalahanin | ito ay isang malaking pag-aalala
Progress: 0.12
translated_text: ang kanyang pag-aalala sa posibilidad na matanggal sa trabaho | ito ay hindi trabaho ngunit pag-aalala na pumatay | gusto niyang mamatay at tapusin ang kanyang mga problema
Progress: 0.12
translated_text: nakatagpo siya ng pangkalahatang pakiramdam ng pagtutol mula sa maraming mamamayan | sa kabila ng pagsalungat ng mga pahayagan ay nagpatuloy siya
Progress: 0.12
translated_text: mababaw na tubig | isang mababaw na ulam | isang mababaw na hiwa | isang mababaw na aparador | nagtatag ng isang mababaw na beachhead | pindutin ang bola sa mababaw na kaliwang field
Progress: 0.12
translated_text: mababaw na paghinga | isang gabi ng mababaw na maligalig na pagtulog | sa isang mababaw na ulirat
Progress: 0.12
translated_text: mababaw na tao | ang kanyang mga argumento ay tila mababaw at nakakapagod
Progress: 0.12
translated_text: siya ay may magaspang na pag-uugali ngunit isang first-rate na isip | pag-uugali na nagtatak sa kanya bilang karaniwan | isang untutored at uncouth na tao | isang bastos na sundalo--isang tunay na matigas na lalaki | sumasamo sa bulgar na lasa para sa karahasan | ang bulgar na pagpapakita ng mga bagong mayaman
Progress: 0.12
translated_text: ang mga karaniwang tao noong mga panahong iyon ay lubhang nagdusa | pag-uugali na nagtatak sa kanya bilang karaniwan | ang kanyang parisukat na plebeian na ilong | isang bulgar at hindi kanais-nais na tao | ang hindi nahugasang masa
Progress: 0.12
translated_text: karaniwang pananalita | isang katutubong termino | katutubong nagsasalita | ang bulgar na dila ng masa | ang teknikal at bulgar na mga pangalan para sa isang uri ng hayop
Progress: 0.12
translated_text: magaspang na wika | isang bastos na biro | magaspang na pag-uugali | isang makalupang sense of humor | isang revoltingly gross expletive | isang bulgar na kilos | punong puno ng lenggwahe na dapat ay na-edit
Progress: 0.12
translated_text: isang maliit na silid-kainan | isang maliit na bahay | isang maliit na kotse | isang maliit (o maliit) na grupo

Progress: 0.12
translated_text: kaunting ulan ang bumagsak noong Mayo | binigyan ito ng kaunting pag-iisip | kaunting oras ang natitira | kaunti pa ang pera namin | kaunting pag-asa ang nanatili | may kaunting pagkakataon na gagana ito | may kaunting pagkakataon na gagana ito
Progress: 0.12
translated_text: anong laking bata ka | maliliit na bata
Progress: 0.12
translated_text: isang kalikot na halaga ng pera | isang footling gesture | ang aming mga alalahanin ay lilliputian kumpara sa mga bansang nasa digmaan | isang maliit (o maliit) bagay | isang hindi pagkakaunawaan sa mga nakakatuwang detalye | limitado sa maliliit na negosyo | nakakatuwang pagsisikap | Ang pagbibigay ng libreng pagkain sa isang pulis ay maaaring labag sa batas, ngunit ito ay tila isang picayune infraction
Progress: 0.12
translated_text: isang maliit na boses | isang maliit na boses
Progress: 0.12
translated_text: siya ay pandak at pandak | pandak sa tangkad | isang maikling smokestack | isang maliit na lalaki
Progress: 0.12
translated_text: maliit na | maliit na | Ang tula ni eecummings ay nakasulat lahat sa maliliit na letra
Progress: 0.12
translated_text: isang magandang maliit na trabaho | pagpalain ang iyong munting puso | aking mahal na munting ina | isang matamis na maliit na pakikitungo | Pagod na ako sa mga maliliit mong pakana | maruruming maliit na trick | kung ano ang isang pangit na maliit na sitwasyon
Progress: 0.12
translated_text: halos hindi nila marinig ang nagsasalita | halos hindi namin sila kilala | namiss lang matamaan | ay bahagya pang tumunog ang kampana nang bumukas ang pinto | bihira na sana siyang dumating bago siya nakahanap ng dahilan para umalis
Progress: 0.12
translated_text: ang mga epekto ng tagtuyot ay kitang-kita sa sinumang makakita sa mga tuyong bukid | maliwanag na poot | ipinahayag na hindi pag-apruba | mga pakinabang ng patent | ginawang malinaw ang kanyang kahulugan | ito ay malinaw na siya ay hindi reaksyonaryo | sa malinaw na pagtingin
Progress: 0.12
translated_text: isang nakikitang pagbabago sa ugali | isang malinaw na maliwanag na pagbura sa manuskrito | isang nakikitang pagbabago sa pag-uugali
Progress: 0.12
translated_text: I-clear ang manuskrito para sa publikasyon | Hindi pinahintulutan ng rock star ang mapanirang-puri na talambuhay na ito
Progress: 0.12
translated_text: linisin ang mga dahon sa damuhan | Maaliwalas na niyebe mula sa kalsada
Progress: 0.13
translated_text: Maaari mo bang linawin ang mga pangungusap na ito? | I-clear ang tanong kung sino ang may kasalanan
Progress: 0.13
translated_text: Magkano ang kinikita mo sa isang buwan sa iyong bagong trabaho? | Malaki ang kinikita niya sa bago niyang trabaho | ang pagsasanib na ito ay nagdala ng maraming pera | Kinukuha niya ang $5,000 bawat buwan
Progress: 0.13
translated_text: magbayad ng utang | lutasin ang isang lumang utang
Progress: 0.13
translated_text: isang malinaw at kasalukuyang panganib | isang malinaw na paliwanag | isang malinaw na kaso ng pagpatay | isang malinaw na indikasyon na siya ay galit | nagbigay sa atin ng malinaw na ideya ng kalikasan ng tao
Progress: 0.13
translated_text: isang kumplikadong problema na nangangailangan ng malinaw na ulo | hindi malinaw kung ano ang inaasahan sa atin
Progress: 0.13
translated_text: isang malinaw na pananaw | isang malinaw na landas tungo sa tagumpay | bukas na tubig | ang bukas na kanayunan
Progress: 0.13
translated_text: malinaw na tubig | malinaw na mga plastic bag | malinaw na salamin | malinaw at malinis ang hangin
Progress: 0.13
translated_text: kami ay malinaw sa panganib | ang barko ay malinaw sa bahura
Progress: 0.13
translated_text: malinis na budhi | tumingin sa kanyang nagtatanong na may malinaw na hindi nababagabag na mga mata
Progress: 0.13
translated_text: pagsisikap na makakuha ng malinis na bass sa mga orkestra na pag-record | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.13
translated_text: kasing linaw ng sipol | malinaw na mga yapak sa niyebe | ang liham ay nagbalik ng malinaw na imahe ng kanyang lolo | isang spire clean-cut laban sa langit | isang malinaw na pattern
Progress: 0.13
translated_text: isang malinis na bill ng kalusugan | isang malinaw na nagwagi
Progress: 0.13
translated_text: isang malinaw na perpektong brilyante | ang maaliwalas na kutis ng isang malusog na dalaga
Progress: 0.13
translated_text: ay absolved sa lahat ng sisihin | ngayon ay malinaw na sa paratang ng kaduwagan | ang kanyang opisyal na karangalan ay napagtibay
Progress: 0.13
translated_text: malinaw na isip | isang percipient na may-akda
Progress: 0.13
translated_text: basahin ang libro ng malinaw hanggang sa dulo | nakatulog nang malinaw sa buong gabi | may mga bukas na patlang na malinaw sa abot-tanaw
Progress: 0.13
translated_text: malinaw na makikita sa ilalim ng mikroskopyo | Umiyak siya ng malakas at malinaw
Progress: 0.13
translated_text: maputlang seagreen | maputlang asul na mata
Progress: 0.13
translated_text: ang maputlang liwanag ng kalahating buwan | isang maputlang araw | ang liwanag ng hapon na dumarating sa mga el track ay nahulog sa maputlang pahaba sa kalye | isang maputla na langit | ang maputla (o wan) na mga bituin | ang liwanag ng madaling araw
Progress: 0.13
translated_text: isang maputlang rendition ng aria | maputlang tuluyan na may mahinang tamis ng lavender | isang mahinang pagganap
Progress: 0.13
translated_text: ang maputlang mukha ng invalid | biglang namula ang maputi niyang mukha
Progress: 0.13
translated_text: nilaro nila basta magaan | basta maganda ang ilaw
Progress: 0.13
translated_text: nakita niya sa wakas ang liwanag | maaari mo bang bigyan ng liwanag ang problemang ito?
Progress: 0.13
translated_text: may kislap siya sa mata | may walang hanggang kislap sa kanyang mga mata
Progress: 0.13
translated_text: nakita nila ang liwanag ng beacon | may ilaw sa bawat sulok
Progress: 0.13
translated_text: Ang matinding init ay maaaring mag-apoy ng halos anumang tuyong bagay | Magsindi ng sigarilyo
Progress: 0.13
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.13
translated_text: isang magaan na pagkarga | ang magnesiyo ay isang magaan na metal--may tiyak na gravity na 1.74 sa 20 degrees C
Progress: 0.13
translated_text: mapusyaw na asul | mapusyaw na kulay tulad ng mga pastel | isang mapusyaw na kulay na pulbos
Progress: 0.13
translated_text: light infantry | magaan na kabalyerya | magaan na industriya | magaan na armas
Progress: 0.13
translated_text: isang magaan na pangungusap | isang magaan na accent | ang mga nasawi ay magaan | mahinang snow ay bumabagsak | mahinang maulap na ulan | magaan na usok mula sa tsimenea
Progress: 0.13
translated_text: isang silid na maliwanag kapag nakabukas ang mga shutter | maaliwalas at magaan ang loob ng bahay
Progress: 0.13
translated_text: ang pantig na nagtatapos sa maikling patinig ay isang magaan na pantig | mahinang diin sa ikalawang pantig
Progress: 0.13
translated_text: pagsisikap na makakuha ng malinis na bass sa mga pag-record ng orkestra | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.13
translated_text: magaan at matikas ang mananayaw | isang lightsome buoyant step | naglakad na may mahinang hakbang
Progress: 0.13
translated_text: magaan na gawaing bahay | magaan na ehersisyo
Progress: 0.13
translated_text: ang magaan na pagdampi ng kanyang mga daliri | banayad na simoy ng hangin
Progress: 0.13
translated_text: biglang nanghina sa sakit | ay may sakit at nanghihina dahil sa gutom | magaan ang pakiramdam sa ulo | isang swooning fit | magaan ang ulo sa alak | magaan ang ulo dahil sa kawalan ng tulog
Progress: 0.13
translated_text: manipis na papel | magaan na damit ng tag-init
Progress: 0.13
translated_text: abstemious sa paggamit ng mga pang-abay | isang magaan na kumakain | isang magaan na naninigarilyo | kumain ng magaan na hapunan
Progress: 0.13
translated_text: isang light pound | isang kaunting tasa ng asukal | regular na nagbibigay ng maikling timbang
Progress: 0.13
translated_text: magaan na taludtod | isang light comedy

Progress: 0.13
translated_text: walang ginagawa na kasiyahan | magaan na banter | magaan na idle chat
Progress: 0.13
translated_text: magaan na sasakyang panghimpapawid | isang magaan na trak
Progress: 0.13
translated_text: diet cola | light (o lite) beer | lite (o magaan) mayonesa | isang low-cal diet
Progress: 0.13
translated_text: sa isang idlip lang | isang light sleeper | isang hindi mapakali na puyat na gabi
Progress: 0.13
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.13
translated_text: naglalaba ng kape | matubig na gatas | mahinang tsaa
Progress: 0.13
translated_text: ang pantig na nagtatapos sa maikling patinig ay isang magaan na pantig | mahinang diin sa ikalawang pantig
Progress: 0.13
translated_text: Isa lang akong maling tao | mahinang sangkatauhan
Progress: 0.13
translated_text: isang mahinang matandang babae | parang walang laman ang katawan niya
Progress: 0.14
translated_text: isang malabong balangkas | ang wan sun cast malabong anino | ang mahinang liwanag ng isang malayong kandila | mahinang kulay | isang mahinang sumisitsit na tunog | isang mahinang aroma | mahinang pulso
Progress: 0.14
translated_text: isang madaling trabaho | isang madaling problema | isang madaling tagumpay | ang bahay ay madaling init | nasiyahan sa madaling sagot | kinuha ang madaling paraan sa kanyang dilemma
Progress: 0.14
translated_text: isang madaling paglalakad sa paligid ng bloke | sa isang dahan-dahan (o maluwag) na bilis
Progress: 0.14
translated_text: alam na ginawa ko ang aking makakaya, ang aking isip ay madali | isang madaling mabait na paraan | sa oras na nahaharap ang bata sa aktwal na problema sa pagbabasa ay pamilyar siya at komportable sa lahat ng mga elemento ng salita
Progress: 0.14
translated_text: isang madaling tapik sa balikat | banayad na ulan | isang banayad na simoy | isang malambot (o magaan) na pagtapik sa bintana
Progress: 0.14
translated_text: isang madaling biktima | isang madaling marka
Progress: 0.14
translated_text: sila ay komportable o kahit na mayaman sa ilang mga pamantayan | madaling pamumuhay | isang maunlad na pamilya | ang kanyang pamilya ay may magandang kalagayan sa pananalapi | mayayamang miyembro ng komunidad
Progress: 0.14
translated_text: isang madaling pag-akyat | isang banayad na dalisdis
Progress: 0.14
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.14
translated_text: madali siyang na-excite | ay madaling malito | madali siyang nanalo | ang china na ito ay napakadaling masira | napakadali ng tagumpay
Progress: 0.14
translated_text: dahan dahan siyang nagsalita | dahan dahan ka dito--madulas ang daan | ang mga glacier ay mabilis na gumagalaw | dahan-dahan lang para makita ko ang mga tanawin
Progress: 0.14
translated_text: natakot siya na ang pagbanggit nito ay maaaring mabuksan muli ang sugat | sa kaibuturan ng kanyang dibdib ay nabubuhay ang tahimik na sugat | Ang tamang mambabasa ng isang mahusay na tula ay maaaring sabihin sa sandaling ito ay tumama sa kanya na siya ay nagkaroon ng isang walang kamatayang sugat--na hindi niya ito malalampasan.
Progress: 0.14
translated_text: Sinaktan niya ako nang hindi niya ako isinama sa kanyang mga bisita | Ang pananalitang ito ay talagang nabugbog ang aking ego
Progress: 0.14
translated_text: ang ilog ay umiikot sa mga burol | ang landas ay lumiliko sa mga ubasan | minsan, gumagala ang gout sa buong katawan
Progress: 0.14
translated_text: Ang daan ay umiikot sa lawa | ang landas na baluktot sa kagubatan
Progress: 0.14
translated_text: igulong ang iyong buhok sa paligid ng iyong daliri | Ikabit ang sinulid sa palibot ng spool | Niyakap niya ang anak
Progress: 0.14
translated_text: walang bakas ng ebidensya para sa claim | isang tincture ng condescension
Progress: 0.14
translated_text: may bahid ng panunuya sa tono niya | may nakita siyang multo ng ngiti sa mukha nito
Progress: 0.14
translated_text: Dapat nating sundin nang mabuti ang pag-unlad ng ekonomiya ay Cuba | subaybayan ang pag-unlad ng mag-aaral
Progress: 0.14
translated_text: gumuhit ng linya | bakas ang balangkas ng isang pigura sa buhangin
Progress: 0.14
translated_text: ni-retrace namin ang rutang tinahak namin noong summer | subaybayan ang iyong landas
Progress: 0.14
translated_text: Tinunton ng mga mangangaso ang usa sa kakahuyan | hinabol ng mga tiktik ang suspek hanggang sa matagpuan nila ito
Progress: 0.14
translated_text: Tinunton ng mga bata ang gilid ng madilim na kagubatan | Tinunton ng mga babae ang pastulan
Progress: 0.14
translated_text: bakas ang isang disenyo | bakas ang isang pattern
Progress: 0.14
translated_text: Maaari mo bang maintindihan ang liham na ito? | Natunton ng arkeologo ang mga hieroglyph
Progress: 0.14
translated_text: nagpakita siya ng mga palatandaan ng strain | tinanggap nila ang mga palatandaan ng tagsibol
Progress: 0.14
translated_text: nabaliktad niya ang polarity ng baterya | mga singil ng kabaligtaran na tanda
Progress: 0.14
translated_text: umaasa siyang isa itong augury | ito ay isang tanda mula sa Diyos
Progress: 0.14
translated_text: Pinirmahan niya ang sulat at ipinadala ito | Mangyaring mag-sign dito
Progress: 0.14
translated_text: Pinagtibay ng lahat ng partido ang kasunduan sa kapayapaan | Napirmahan mo na ba ang iyong kontrata?
Progress: 0.14
translated_text: Pumirma siya para maglaro ng casino noong Disyembre 18 | Pumirma ang soprano para kantahin ang bagong opera
Progress: 0.14
translated_text: Pinirmahan niya ang kanyang hindi pag-apruba gamit ang isang dismissive hand gesture | Sinenyasan ng kainan ang mga waiter na dalhin ang menu
Progress: 0.14
translated_text: lagdaan ang isang intersection | Ang kalsadang ito ay nilagdaan na
Progress: 0.14
translated_text: Tawagan ang pakikipag-ugnayan | kanselahin ang dinner party | kailangan naming i-scrub ang aming mga plano sa bakasyon | scratch that meeting--may sakit ang upuan
Progress: 0.14
translated_text: Mangyaring hampasin ang pangungusap na ito mula sa talaan | scratch that remark
Progress: 0.14
translated_text: Siya ay nagkamot ng sapat na pera para sa kolehiyo | nagkamot sila ng kakarampot na pamumuhay
Progress: 0.14
translated_text: mag-ukit ng panulat | inukit ang trophy cupt ng panalo | nagkamot ang magkasintahan sa balat ng puno
Progress: 0.14
translated_text: nagpakita siya ng mga senyales ng strain | tinanggap nila ang mga palatandaan ng tagsibol
Progress: 0.14
translated_text: nabaliktad niya ang polarity ng baterya | mga singil ng kabaligtaran na tanda
Progress: 0.14
translated_text: umaasa siyang isa itong augury | ito ay isang tanda mula sa Diyos
Progress: 0.14
translated_text: Pinirmahan niya ang sulat at ipinadala ito | Mangyaring mag-sign dito
Progress: 0.14
translated_text: Pinagtibay ng lahat ng partido ang kasunduan sa kapayapaan | Napirmahan mo na ba ang iyong kontrata?
Progress: 0.14
translated_text: Pumirma siya para maglaro ng casino noong Disyembre 18 | Pumirma ang soprano para kantahin ang bagong opera
Progress: 0.14
translated_text: Pinirmahan niya ang kanyang hindi pag-apruba gamit ang isang dismissive hand gesture | Sinenyasan ng kainan ang mga waiter na dalhin ang menu
Progress: 0.14
translated_text: lagdaan ang isang intersection | Ang kalsadang ito ay nilagdaan na
Progress: 0.14
translated_text: Sabihin na nating hindi siya nagsabi ng totoo | Sabihin nating marami kang pera--ano ang gagawin mo?
Progress: 0.14
translated_text: Iniisip ko na kumita siya ng maraming pera sa kanyang bagong nobela | Naisip kong hanapin siya sa masamang kalagayan | hindi niya naisip na hanapin siya sa kusina | Galit yata siya sa akin dahil pinatayo ko siya
Progress: 0.14
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.14
translated_text: Dapat mong isaalang-alang ang kanyang edad | Itinuring ng hukom ang kabataan ng nagkasala at naging maluwag
Progress: 0.14
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.15
translated_text: Kailangan mong umasa sa aming mga kalaban | Asahan mo ang tag-ulan

Progress: 0.15
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.15
translated_text: Dapat mong isaalang-alang ang kanyang edad | Itinuring ng hukom ang kabataan ng nagkasala at naging maluwag
Progress: 0.15
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.15
translated_text: Kailangan mong umasa sa aming mga kalaban | Asahan mo ang tag-ulan
Progress: 0.15
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.15
translated_text: Dapat mong isaalang-alang ang kanyang edad | Itinuring ng hukom ang kabataan ng nagkasala at naging maluwag
Progress: 0.15
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.15
translated_text: Kailangan mong umasa sa aming mga kalaban | Asahan mo ang tag-ulan
Progress: 0.15
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.15
translated_text: Dapat mong isaalang-alang ang kanyang edad | Itinuring ng hukom ang kabataan ng nagkasala at naging maluwag
Progress: 0.15
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.15
translated_text: Kailangan mong umasa sa aming mga kalaban | Asahan mo ang tag-ulan
Progress: 0.15
translated_text: Magkaroon ng isa pang mangkok ng sopas ng manok! | Hindi ako kumukuha ng asukal sa aking kape
Progress: 0.15
translated_text: ang kotseng ito ay kumonsumo ng maraming gas | Naubos namin ang aming ipon | Tumatakbo sila sa 20 bote ng alak sa isang linggo
Progress: 0.15
translated_text: nagbabala siya laban sa paggamit ng narcotic drugs | sanay sa paggamit ng mga kompyuter
Progress: 0.15
translated_text: ang function ng auger ay magbutas ng mga butas | ang ganda ng balete pero anong silbi nito?
Progress: 0.15
translated_text: ginamit niya ang kanyang kaalaman sa mabuti | may kani-kaniyang gamit ang mga parokyano
Progress: 0.15
translated_text: ang mga kuwago ay may mga gawi sa gabi | nakagawian niya ang pag-ikot sa dulo ng kanyang buhok | matagal na paggamit ay pinatigas niya ito
Progress: 0.15
translated_text: gamitin mo ang ulo mo! | Spanish lang ang gamit namin sa bahay | Hindi ko magagamit ang tool na ito | Mag-apply ng magnetic field dito | Ang pag-iisip na ito ay inilapat sa maraming proyekto | Paano mo ginagamit ang tool na ito? | Inilapat ko ang panuntunang ito para makakuha ng magagandang resulta | gamitin ang mga plastic bag para mag-imbak ng pagkain | Hindi siya marunong gumamit ng computer
Progress: 0.15
translated_text: Ginagamit niya ang kanyang mga maimpluwensyang kaibigan para makakuha ng trabaho | Ginamit ng asawa ng presidente ang kanyang magagandang koneksyon
Progress: 0.15
translated_text: maglapat ng prinsipyo | magsagawa ng relihiyon | mag-ingat sa pagbaba ng hagdan | gamitin ang iyong sentido komun | magsagawa ng hindi marahas na paglaban
Progress: 0.15
translated_text: Dati linggo-linggo siyang tumatawag sa kanyang ina ngunit ngayon ay paminsan-minsan na lamang | Nagkasakit ako noon kapag kumakain ako sa dining hall na iyon | Nagbakasyon sila noon sa Bahamas
Progress: 0.15
translated_text: nagbabala siya laban sa paggamit ng narcotic drugs | sanay sa paggamit ng mga kompyuter
Progress: 0.15
translated_text: ang function ng auger ay magbutas ng mga butas | ang ganda ng balete pero anong silbi nito?
Progress: 0.15
translated_text: ginamit niya ang kanyang kaalaman sa mabuti | may kani-kaniyang gamit ang mga parokyano
Progress: 0.15
translated_text: ang mga kuwago ay may mga gawi sa gabi | nakagawian niya ang pag-ikot ng dulo ng kanyang buhok | matagal na paggamit ay pinatigas niya ito
Progress: 0.15
translated_text: gamitin mo ang ulo mo! | Spanish lang ang gamit namin sa bahay | Hindi ko magagamit ang tool na ito | Mag-apply ng magnetic field dito | Ang pag-iisip na ito ay inilapat sa maraming proyekto | Paano mo ginagamit ang tool na ito? | Inilapat ko ang panuntunang ito para makakuha ng magagandang resulta | gamitin ang mga plastic bag para mag-imbak ng pagkain | Hindi siya marunong gumamit ng computer
Progress: 0.15
translated_text: Ginagamit niya ang kanyang mga maimpluwensyang kaibigan para makakuha ng trabaho | Ginamit ng asawa ng presidente ang kanyang magagandang koneksyon
Progress: 0.15
translated_text: maglapat ng prinsipyo | magsagawa ng relihiyon | mag-ingat sa pagbaba ng hagdan | gamitin ang iyong sentido komun | magsanay ng hindi marahas na paglaban
Progress: 0.15
translated_text: Dati linggo-linggo siyang tumatawag sa kanyang ina ngunit ngayon ay paminsan-minsan na lamang | Nagkasakit ako noon kapag kumakain ako sa dining hall na iyon | Nagbakasyon sila noon sa Bahamas
Progress: 0.15
translated_text: binigyan siya ng pangkalahatang pamamahala ng programa | ang direksyon ba ng ekonomiya ay tungkulin ng pamahalaan?
Progress: 0.15
translated_text: Dinala namin siya sa aming punong | pwede mo ba akong ihatid sa main entrance? | Dinala niya kami sa palasyo
Progress: 0.15
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.15
translated_text: Subukan ang mga bagong crackers na ito | Tikman ang mga regional dish
Progress: 0.15
translated_text: ang komposisyon ay nagpapakita ng mga problema para sa mga mag-aaral ng musikal na anyo | ang isang visual na pattern ay dapat isama hindi lamang ang mga bagay ngunit ang mga puwang sa pagitan ng mga ito
Progress: 0.15
translated_text: ugali nila na magbigay ng taunang pagtaas | binago nila ang kanilang dietary pattern
Progress: 0.15
translated_text: ang kumbensyon ng hindi pagpapangalan sa pangunahing tauhan | ang karahasan ay ang panuntunan hindi ang eksepsiyon | ang kanyang formula para mapabilib ang mga bisita
Progress: 0.15
translated_text: isang blueprint para sa isang bahay | isang pattern para sa isang palda
Progress: 0.15
translated_text: ang mga pattern ng trapiko sa paligid ng O&#39;Hare ay napakasikip | nanatili sila sa pattern hanggang sa tumaas ang fog
Progress: 0.15
translated_text: isang halimbawa ng tagumpay | isang modelo ng kalinawan | siya ang mismong modelo ng isang modernong mayor na heneral
Progress: 0.15
translated_text: huwarang pag-uugali | modelong mamamayan
Progress: 0.15
translated_text: Dinala namin siya sa aming punong | pwede mo ba akong ihatid sa main entrance? | Dinala niya kami sa palasyo
Progress: 0.15
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.15
translated_text: ang ikatlong baseman ay gumawa ng ilang kapansin-pansing paghinto | ang kanyang pagtigil sa daloy ay nagresulta sa isang baha
Progress: 0.15
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.15
translated_text: huminto ang sasakyan | Huminto siya sa harap ng bintana ng tindahan
Progress: 0.15
translated_text: Harangan ang kanyang halalan | Itigil ang proseso
Progress: 0.15
translated_text: huminto kami sa bahay ni Tita Mary | huminto sila ng tatlong araw sa Florence
Progress: 0.15
translated_text: huminto ng kotse | pigilan ang magnanakaw
Progress: 0.16
translated_text: itigil ang proyekto | putulin ang negosasyon
Progress: 0.16
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.16
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo

Progress: 0.16
translated_text: harangan ang daan | barikada ang mga lansangan | itigil ang abalang kalsada
Progress: 0.16
translated_text: isang magandang pass | ang mga bagay ay dumating sa ulo kahapon
Progress: 0.16
translated_text: sinapak niya ito | Binigyan ko ito ng umiikot
Progress: 0.16
translated_text: ang kanyang kinabukasan ay nakasalalay sa kanyang pagpasa sa pagsubok na iyon | nakakuha siya ng pass sa introductory chemistry
Progress: 0.16
translated_text: Dumaan kami sa punto kung saan naka-park ang sasakyan ng pulis | Isang kakila-kilabot na kaisipan ang pumasok sa kanyang isipan
Progress: 0.16
translated_text: Isang itim na limousine ang dumaan nang dumungaw siya sa bintana | Dinaanan niya ang kanyang propesor sa bulwagan | Nalampasan ng isang linya ng mga sundalo ang isa pa
Progress: 0.16
translated_text: Ipinasa nila ang susog | Hindi natin maisabatas kung paano ginugugol ng mga tao ang kanilang libreng oras
Progress: 0.16
translated_text: bigyan mo ako ng kutsara, pakiusap | Ibalik ang mga file sa akin, mangyaring | Ibinalik niya ang bilanggo sa kanyang mga abogado
Progress: 0.16
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.16
translated_text: Anong nangyayari? | Ang pagpupulong ay naganap nang walang insidente | Walang nangyari na tila mahalaga
Progress: 0.16
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.16
translated_text: Mangyaring ipaalam ang mensaheng ito sa lahat ng empleyado | ipasa ang mabuting balita
Progress: 0.16
translated_text: Lumagpas siya sa aming inaasahan | Nanguna siya sa kanyang pagganap noong nakaraang taon
Progress: 0.16
translated_text: Ang ari-arian ay nahulog sa aking kapatid na babae | Ibinalik ang lupa sa pamilya | Ang ari-arian ay ipinagkaloob sa isang tagapagmana na ipinapalagay ng lahat na patay na
Progress: 0.16
translated_text: I-clear ang manuskrito para sa publikasyon | Hindi pinahintulutan ng rock star ang mapanirang-puri na talambuhay na ito
Progress: 0.16
translated_text: Namatay siya sa cancer | Ang mga bata ay namatay sa apoy | Ang pasyente ay pumunta nang mapayapa | Sinipa ng matandang lalaki ang balde sa edad na 102
Progress: 0.16
translated_text: isang team na may magandang passing attack | isang pass play
Progress: 0.16
translated_text: Ang lalaking ito ay pumatay ng maraming tao nang subukan niyang magnakaw sa isang bangko | Ang magsasaka ay pumatay ng baboy para sa bakasyon
Progress: 0.16
translated_text: pumatay ng galaw | binatukan niya ang proposal ng estudyante
Progress: 0.16
translated_text: ang sigarilyo ay pumatay | nakamamatay ang pagmamaneho ng lasing
Progress: 0.16
translated_text: Nag-down siya ng tatlong martinis bago kumain | Nakapatay siya ng isang bote ng brandy noong gabing iyon | Uminom sila ng ilang beer pagkatapos ng trabaho
Progress: 0.16
translated_text: Ang lalaking ito ay pumatay ng maraming tao nang subukan niyang magnakaw sa isang bangko | Ang magsasaka ay pumatay ng baboy para sa bakasyon
Progress: 0.16
translated_text: pumatay ng galaw | binatukan niya ang proposal ng estudyante
Progress: 0.16
translated_text: ang sigarilyo ay pumatay | nakamamatay ang pagmamaneho ng lasing
Progress: 0.16
translated_text: Nag-down siya ng tatlong martinis bago kumain | Nakapatay siya ng isang bote ng brandy noong gabing iyon | Uminom sila ng ilang beer pagkatapos ng trabaho
Progress: 0.16
translated_text: ang instant replay ay nagdulot ng masyadong mahabang pagkaantala | siya ay nag-utos ng isang hold sa aksyon
Progress: 0.16
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.16
translated_text: Nakita niya ang mataas na antas ng tingga sa kanyang inuming tubig | Nakakita kami ng mga bakas ng tingga sa pintura
Progress: 0.16
translated_text: Napansin niya na ang kanyang presentasyon ay tumagal ng masyadong maraming oras | Napansin nila na ito ay isang magandang araw upang maglayag
Progress: 0.16
translated_text: Sundin ang mga utos | ipagdiwang ang Pasko | Obserbahan ang Yom Kippur
Progress: 0.16
translated_text: Pagmasdan ang sanggol, mangyaring! | Ang mundo ay nanonood ng Sarajevo | Sinundan niya ang mga lalaking may hawak na binocular
Progress: 0.16
translated_text: Ang pianista ay nagpapanatili ng oras sa metronome | panatilihin ang bilang | Hindi ko masubaybayan ang lahat ng aking mga empleyado
Progress: 0.16
translated_text: panatilihin ang mga appointment | hindi niya tinutupad ang kanyang mga pangako | Nanatili kami sa orihinal na mga kondisyon ng kontrata
Progress: 0.16
translated_text: Nakita niya ang mataas na antas ng tingga sa kanyang inuming tubig | May nakita kaming bakas ng tingga sa pintura
Progress: 0.16
translated_text: Napansin niya na ang kanyang presentasyon ay tumagal ng masyadong maraming oras | Napansin nila na ito ay isang magandang araw upang maglayag
Progress: 0.16
translated_text: Sundin ang mga utos | ipagdiwang ang Pasko | Obserbahan ang Yom Kippur
Progress: 0.16
translated_text: Pagmasdan ang sanggol, mangyaring! | Ang mundo ay nanonood ng Sarajevo | Sinundan niya ang mga lalaking may dalang binocular
Progress: 0.16
translated_text: Ang pianista ay nagpapanatili ng oras sa metronome | panatilihin ang bilang | Hindi ko masubaybayan ang lahat ng aking mga empleyado
Progress: 0.16
translated_text: panatilihin ang mga appointment | hindi niya tinutupad ang kanyang mga pangako | Nanatili kami sa orihinal na mga kondisyon ng kontrata
Progress: 0.16
translated_text: isang malungkot na ekspresyon | isang hitsura ng tagumpay | galit na mukha
Progress: 0.16
translated_text: lumabas siya para tingnan | panay ang tingin niya sa mga mata niya | binigyan niya ito ng magandang pagtingin sa | Hinahanap siya ng camera niya
Progress: 0.16
translated_text: ang pakiramdam ng lungsod ay nasasabik sa kanya | pinagbuti ng isang klerigo ang tono ng pulong | ito ay may amoy ng pagtataksil
Progress: 0.16
translated_text: Tumingin siya sa kalawakan ng lupain | Tingnan mo ang anak mo! | Tingnan mo--isang usa sa likod-bahay!
Progress: 0.16
translated_text: Natutulog daw siya | Ito ay tila isang napakahirap na problema | Mukhang malansa ang proyektong ito | Nagmukha silang mga taong matagal nang hindi kumakain o natutulog
Progress: 0.16
translated_text: Ano ang hitsura niya? | Mukhang malungkot ang bata | Mukha siyang namutla pagkatapos ng operasyon
Progress: 0.16
translated_text: Buong araw kaming naghanap at sa wakas ay natagpuan namin ang bata sa kagubatan | Maghanap sa ibang lugar para sa perpektong regalo!
Progress: 0.16
translated_text: Ang bahay ay mukhang hilaga | Ang aking likod-bahay ay tumingin sa pond | Nakaharap ang gusali sa parke
Progress: 0.17
translated_text: Nakikita mo ba ang tungkol sa tanghalian? | Dapat kong asikasuhin ang bagay na ito | Siya ang nag-asikaso sa negosyong ito
Progress: 0.17
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.17
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.17
translated_text: malihis na pag-uugali | mga lihis na ideya
Progress: 0.17
translated_text: Sinabi ng senador na tututulan niya ang panukalang batas | Huwag mo itong labanan!
Progress: 0.17
translated_text: hayaan silang itugma ang kanilang pinakamahusay na mga atleta laban sa atin | pit isang chess player laban sa Russian champion | Pinaglalaruan niya ang kanyang dalawang anak laban sa isa&#39;t isa
Progress: 0.17
translated_text: isang masipag (o pasyente) na manggagawa | sa matiyaga (o matiyagang) industriya ay binuhay niya ang bagsak na negosyo
Progress: 0.17
translated_text: sinisiyasat ng isang masigasig na tiktik ang lahat ng mga pahiwatig | isang masigasig na paghahanap ng mga file

Progress: 0.17
translated_text: napuno ng masigasig na mga tao ang mga lansangan | isang masigasig na tugon | ay masigasig sa pagkuha ng mga aralin sa ballet
Progress: 0.17
translated_text: isang masiglang talakayan | masigla at kaakit-akit na mga magulang | isang masiglang party
Progress: 0.17
translated_text: isang mabilis na paglalakad sa parke | isang masiglang lakad | isang masayang paghabol | naglalakbay sa mabilis na bilis | isang mabilis na bilis | isang hampas ng hangin
Progress: 0.17
translated_text: malinis na talbog na buhok | isang masiglang bola ng tennis | kasing tibay ng batikang hickory | bukal na karerahan
Progress: 0.17
translated_text: isang dynamic na puno ng buhay na babae | isang mahalagang at karismatikong pinuno | ang buong buhay na mundong ito
Progress: 0.17
translated_text: isang kinakabahan na adik | isang nerbiyos na lahi
Progress: 0.17
translated_text: gumugol ng isang balisang gabi sa paghihintay para sa mga resulta ng pagsusulit | nagsumite ng balisang sulyap sa likod niya | mga kaba na sandali bago mag-takeoff | isang hindi matahimik na isip
Progress: 0.17
translated_text: sakit sa nerbiyos | neural disorder
Progress: 0.17
translated_text: isang kinakabahan na adik | isang nerbiyos na lahi
Progress: 0.17
translated_text: gumugol ng isang balisang gabi sa paghihintay para sa mga resulta ng pagsusulit | nagsumite ng balisang sulyap sa likod niya | mga kaba na sandali bago mag-takeoff | isang hindi matahimik na isip
Progress: 0.17
translated_text: sakit sa nerbiyos | neural disorder
Progress: 0.17
translated_text: Sinampal ng naiinip na guro ang estudyante | isang putok ng baril ang tumama sa kanyang noo
Progress: 0.17
translated_text: bumangga siya sa poste | tumakbo sampal sa kanya
Progress: 0.17
translated_text: isang sikat na tourist attraction | isang sikat na babae | hindi na sikat ang mga manika ng repolyo patch
Progress: 0.17
translated_text: ang popular na boto | sikat na representasyon | mga institusyon ng popular na pamahalaan
Progress: 0.17
translated_text: mga demokratikong anyo ng sining | isang demokratiko o popular na kilusan | tanyag na kaisipan | sikat na agham | popular na fiction
Progress: 0.17
translated_text: isang sikat na artista | isang tanyag na musikero | isang sikat na siyentipiko | isang kilalang hukom | isang kilalang mananalaysay | isang kilalang pintor
Progress: 0.17
translated_text: Mayroon akong isang brush na may panganib sa aking pagpunta sa trabaho | sinubukan niyang iwasan ang anumang pagsipilyo sa mga pulis
Progress: 0.17
translated_text: Ang kanyang mahabang palda ay sumipilyo sa sahig | Isang hingal ang bumalot sa mga manonood
Progress: 0.17
translated_text: magsipilyo ng mga mumo | magsipilyo ng alikabok mula sa jacket | isantabi ang mga pagtutol
Progress: 0.17
translated_text: isang sikat na tourist attraction | isang sikat na babae | hindi na sikat ang mga manika ng repolyo patch
Progress: 0.17
translated_text: ang popular na boto | sikat na representasyon | mga institusyon ng popular na pamahalaan
Progress: 0.17
translated_text: mga demokratikong anyo ng sining | isang demokratiko o popular na kilusan | tanyag na kaisipan | sikat na agham | popular na fiction
Progress: 0.17
translated_text: kung paano ito lumabas ay isang misteryo | nananatili itong isa sa mga lihim ng kalikasan
Progress: 0.17
translated_text: kung paano ito lumabas ay isang misteryo | nananatili itong isa sa mga lihim ng kalikasan
Progress: 0.17
translated_text: mga aklat ang kanyang mga guro | ang karanasan ay isang mapaghingi na guro
Progress: 0.17
translated_text: isang matiyagang ngiti | ay matiyaga sa mga bata | isang tumpak at matiyagang siyentipiko | pasensya na po
Progress: 0.17
translated_text: naantala ng pagpapalamig ang paglambot ng prutas | napagmasdan niya ang paglambot ng bakal sa pamamagitan ng init
Progress: 0.17
translated_text: lumambot ng pagkabigla | masira ang isang pagkahulog
Progress: 0.17
translated_text: ang kanyang pagmamahal sa kanyang trabaho | ang mga bata ay nangangailangan ng maraming pagmamahal
Progress: 0.17
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.17
translated_text: ang kanilang pag-ibig ay nag-iwan sa kanila na walang malasakit sa kanilang paligid | siya ang kanyang unang pag-ibig
Progress: 0.17
translated_text: naiinis sa kanya ang kanyang pakikipagtalik | hindi siya nagkaroon ng anumang pag-ibig sa mga buwan | napakakomplikado ng buhay pag-ibig niya
Progress: 0.17
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.17
translated_text: Ang estudyanteng ito ay natutulog sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.17
translated_text: hanggang sa isang tamad na ilog | tamad na puting ulap | sa isang tamad na bilis
Progress: 0.17
translated_text: nanghihinang mga hari sa ilalim ng pamumuno ng bansa ay nanghina | isang tamad na tambay | tamad maghugas ng pinggan | walang pasubali idle youth | mga tamad na empleyado | ang mga walang trabaho ay hindi kinakailangang mahiya sa trabaho
Progress: 0.17
translated_text: mapurol (o mabagal) ang negosyo | isang matamlay na pamilihan
Progress: 0.17
translated_text: siya ay mataba at hindi gumagalaw | isang matamlay na manggagawa | isang isip lumago torpid sa katandaan
Progress: 0.17
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.17
translated_text: ang ganda ng coordination ng kanyang disiplinadong muscles | isang disiplinadong kaisipan
Progress: 0.17
translated_text: mahigpit na paglalapat ng batas | isang mahigpit na vegetarian
Progress: 0.17
translated_text: isang mahigpit na tagapagturo | isang mahigpit na disciplinarian | mahigpit na pamantayan
Progress: 0.18
translated_text: isang matiyagang ngiti | ay matiyaga sa mga bata | isang eksakto at matiyagang siyentipiko | pasensya na po
Progress: 0.18
translated_text: ang iskultura ay isang anyo ng sining | anong klaseng dessert ang meron?
Progress: 0.18
translated_text: mabait sa mga maysakit na pasyente | isang mabait na master | mabubuting salita na nagpapakita ng pang-unawa at pakikiramay | nagpasalamat sa kanya para sa kanyang mabait na liham
Progress: 0.18
translated_text: isang tuyong klima sa mga asthmatics | ang magiliw na sikat ng araw | Ang mga mainit na pavement sa tag-araw ay hindi gaanong kabaitan sa paa
Progress: 0.18
translated_text: kapansanan sa pagbabasa | kapansanan sa pandinig
Progress: 0.18
translated_text: naglaro sila ng word games | naisip niya ang kanyang pagpipinta bilang isang laro na pumupuno sa kanyang walang laman na oras | masaya at laro ang buhay niya
Progress: 0.18
translated_text: ang laro ay 6 lahat | nagsisilbi siya para sa laro
Progress: 0.18
translated_text: gumawa sila ng pakana para siraan ang gobernador | Nakita ko ang kanyang maliit na laro mula sa simula
Progress: 0.18
translated_text: siya ay nasa laro sa pagtutubero | nasa show biz siya
Progress: 0.18
translated_text: para sa mga artista, hindi laro ang pagsasaulo ng mga linya | para sa kanya, ang buhay ay puro saya at laro
Progress: 0.18
translated_text: Aling kabayo ang iyong sinusuportahan? | Pupusta ako sa bagong kabayo
Progress: 0.18
translated_text: isang baldado na sundalo | isang paa ng laro
Progress: 0.18
translated_text: ang presyo ng gasolina | nakuha niya ang kanyang bagong kotse sa mahusay na mga tuntunin | magkano ang damage?
Progress: 0.18
translated_text: Nasira ng snow ang bubong | Nasira niya ang sasakyan nang mabangga niya ang puno
Progress: 0.18
translated_text: purong hangin at tubig | purong ginto | puro pangunahing kulay | ang dalisay at kaibig-ibig na kanta ng biyolin | puro tono | purong oxygen
Progress: 0.18
translated_text: isang arrant tanga | isang ganap na duwag | isang ganap na tanga | isang kontrabida na may dobleng tinina | matinding kapabayaan | isang perpektong idiot | puro katangahan | anong gulo | stark staring mad | isang masinsinang kontrabida | walang kwentang salita | ang walang halong katotohanan
Progress: 0.18
translated_text: Purong at matamis ang aking nadama bilang isang bagong sanggol | dalisay na parang niyebe

Progress: 0.18
translated_text: dalisay at vestal na kahinhinan | isang spinster o virgin lady | ang mga lalaki ay nag-utos na ang kanilang mga babae ay dapat na dalisay at birhen
Progress: 0.18
translated_text: purong hangin at tubig | purong ginto | puro pangunahing kulay | ang dalisay at kaibig-ibig na kanta ng biyolin | puro tono | purong oxygen
Progress: 0.18
translated_text: isang arrant tanga | isang ganap na duwag | isang ganap na tanga | isang kontrabida na may dobleng tinina | matinding kapabayaan | isang perpektong idiot | puro katangahan | anong gulo | stark staring mad | isang masinsinang kontrabida | walang kwentang salita | ang walang halong katotohanan
Progress: 0.18
translated_text: Purong at matamis ang aking nadama bilang isang bagong sanggol | dalisay na parang niyebe
Progress: 0.18
translated_text: dalisay at vestal na kahinhinan | isang spinster o virgin lady | ang mga lalaki ay nag-utos na ang kanilang mga babae ay dapat na dalisay at birhen
Progress: 0.18
translated_text: shine the silver, please | polish ang sapatos ko
Progress: 0.18
translated_text: makinis na balat | isang makinis na tabletop | makinis na tela | isang makinis na daan | tubig na kasingkinis ng salamin
Progress: 0.18
translated_text: masyado siyang pulitiko para makipag-away sa napakahalagang personahe | pinayapa ng manager ang customer ng maayos na paghingi ng tawad para sa pagkakamali
Progress: 0.18
translated_text: isang mahaba, makinis na hakbang | ang tuluy-tuloy na galaw ng isang pusa | ang likidong biyaya ng isang ballerina
Progress: 0.18
translated_text: isang laso ng buhangin sa pagitan ng galit na dagat at ng tahimik na bay | ang tahimik na tubig ng isang lagoon | isang lawa ng tahimik na asul na tubig na sumasalamin sa isang tahimik na asul na kalangitan | isang makinis na tawiran ng channel | bahagya isang alon sa tahimik na tubig | walang humpay na tubig
Progress: 0.18
translated_text: durugin ang isang lata ng aluminyo | pisilin ang isang limon
Progress: 0.18
translated_text: Tinalo ni Agassi si Becker sa kampeonato ng tennis | Tinalo namin ang kompetisyon | Tinalo ng Harvard si Yale sa huling laro ng football
Progress: 0.18
translated_text: Nadurog siya sa pagtanggi nito sa kanyang imbitasyon | Ang pagkamatay ng kanyang anak ay bumagsak sa kanya
Progress: 0.18
translated_text: pinababa | isang sirang lalaki | ang kanyang nasirang diwa
Progress: 0.18
translated_text: para sa iyong ikabubuti | ano ang mabuting mag-alala?
Progress: 0.18
translated_text: timbangin ang mabuti laban sa masama | kabilang sa pinakamataas na kalakal sa lahat ay ang kaligayahan at pagsasakatuparan sa sarili
Progress: 0.18
translated_text: magandang balita mula sa ospital | isang magandang report card | kapag siya ay mabuti siya ay napakabuti | ang isang mahusay na kutsilyo ay isang mahusay para sa pagputol | ang tuod na ito ay gagawa ng magandang picnic table | isang magandang check | isang magandang biro | isang magandang panlabas na pintura | isang magaling na sekretarya | magandang damit para sa opisina
Progress: 0.18
translated_text: nagbibigay ng buong sukat | nagbibigay ng magandang sukat | isang magandang milya mula dito
Progress: 0.18
translated_text: lahat ng kagalang-galang na kumpanya ay nagbibigay ng mga garantiya | sinira ang magandang pangalan ng pamilya
Progress: 0.18
translated_text: isang kasunduan sa limitasyon ng armas na kapaki-pakinabang sa lahat ng mga bansa | ang mga kapaki-pakinabang na epekto ng isang mapagtimpi na klima | ang karanasan ay mabuti para sa kanya
Progress: 0.18
translated_text: lahat tayo ay nagsaya | magandang asal
Progress: 0.18
translated_text: isang tunay na mabuting tao | isang makatarungang dahilan | isang matuwid at kagalang-galang na tao
Progress: 0.18
translated_text: sanay sa handicrafts | isang mahusay na juggler | isang dalubhasang trabaho | isang magaling na mekaniko | isang sinanay na marksman | isang mahusay na inhinyero | isang hindi gaanong kilala ngunit hindi gaanong mahusay na kompositor | ang epekto ay nakamit sa pamamagitan ng mahusay na retoke
Progress: 0.18
translated_text: nagkaroon ng magandang ehersisyo | nagbigay ng magandang paglilinis sa bahay
Progress: 0.18
translated_text: isang mabuting kaibigan | malapit at mahal ang mga kapatid ko
Progress: 0.18
translated_text: isang magandang pamumuhunan | isang ligtas na pamumuhunan
Progress: 0.18
translated_text: magandang panahon para magtanim ng kamatis | ang tamang oras para kumilos | ang panahon ay hinog na para sa malalaking pagbabago sa sosyolohikal
Progress: 0.18
translated_text: buti na lang wala ako | buti naman nanatili ka | buti na lang walang nakakita sa iyo | lahat ay mabuti na nagtatapos
Progress: 0.18
translated_text: ang batas ay epektibo kaagad | isang warranty na maganda para sa dalawang taon | ang batas ay may bisa na (o may bisa)
Progress: 0.18
translated_text: magandang musika | isang seryosong libro
Progress: 0.18
translated_text: magandang ngipin | Mayroon pa akong isang magandang paa | isang maayos na pag-iisip sa isang maayos na katawan
Progress: 0.18
translated_text: mga kapaki-pakinabang na epekto ng balanseng diyeta | isang magandang pagtulog sa gabi | ang nakapagpapalusog na impluwensya ng purong hangin
Progress: 0.18
translated_text: maganda ang ugali ng mga bata | isang gawain nang maayos | naging maayos ang party | nakatulog siya ng maayos | isang well-argued thesis | isang masarap na ulam | isang well-planned party | ang sanggol ay maaaring maglakad nang maayos
Progress: 0.19
translated_text: natalo siya ng husto | natalo namin siya ng husto
Progress: 0.19
translated_text: isang matalas na photographic na imahe | ang matalim na bitak ng sanga | ang malutong na snap ng mga tuyong dahon sa ilalim ng paa
Progress: 0.19
translated_text: isang matinding tagamasid ng pulitika at mga pulitiko | matulis na komento | nagyeyelong parang kutsilyo na pangangatwiran | kasing matalas at matinis na gaya ng hampas ng pangil | tumatagos na pananaw | madalas na penetrative observation
Progress: 0.19
translated_text: isang matalinong negosyante | palaging binabasa ng isang matalinong nangungupahan ang maliit na letra sa isang lease | siya ay napakatalino upang sumama sa kanila sa isang daan na maaaring humantong lamang sa kanilang pagbagsak
Progress: 0.19
translated_text: matalas na pagpuna | isang matalas na palitan ng salita | isang maasim na pahayag
Progress: 0.19
translated_text: isang matinis na sipol | isang matinis na saya
Progress: 0.19
translated_text: isang biglang kanyon | ang matarik na agos ng itaas na ilog | ang matarik na burol ng mga pinturang Tsino | isang matalim na patak
Progress: 0.19
translated_text: isang matinding sakit | matalas na hangin
Progress: 0.19
translated_text: isang matalim na kutsilyo | isang lapis na may matalas na punto
Progress: 0.19
translated_text: ang daan ay umiikot nang husto pagkatapos ng liwanag | lumiko bigla pakaliwa dito | ang visor ay acutely peak | ang kanyang sapatos ay acutely pointed toes
Progress: 0.19
translated_text: kailangan mong harapin ang musika | inumin mo ang iyong gamot
Progress: 0.19
translated_text: ang paghawak ng mga bilanggo | ang paggamot ng tubig dumi sa alkantarilya | ang karapatan sa pantay na pagtrato sa sistema ng hustisyang kriminal
Progress: 0.19
translated_text: ang libro ay naglalaman ng isang mahusay na talakayan ng modal logic | ang kanyang pagtrato sa tanong ng lahi ay masama
Progress: 0.19
translated_text: narinig niya ang mga ulat na nagdudulot sila ng gulo | kung tutuusin, masaya silang mag-asawa
Progress: 0.19
translated_text: ang ulat ng kanyang talumpati | ang kwento ay nasa 11 o&#39;clock news | ang ulat ng kanyang talumpati na ibinigay sa balita sa gabi ay nagpagalit sa gobernador
Progress: 0.19
translated_text: nakuha niya ang isang reputasyon bilang isang artista bago siya nagsimulang magsulat | siya ay isang tao ng masamang ulat
Progress: 0.19
translated_text: Dose-dosenang mga insidente ng pambubugbog sa asawa ang iniulat araw-araw sa lungsod na ito | Ang koponan ay nag-ulat ng mga makabuluhang pag-unlad sa kanilang pananaliksik
Progress: 0.19
translated_text: Iniulat ni Snow sa China noong 1950&#39;s | Sinakop ng cub reporter ang New York City

Progress: 0.19
translated_text: narinig niya ang mga ulat na nagdudulot sila ng gulo | kung tutuusin, masaya silang mag-asawa
Progress: 0.19
translated_text: ang ulat ng kanyang talumpati | ang kwento ay nasa 11 o&#39;clock news | ang ulat ng kanyang talumpati na ibinigay sa balita sa gabi ay nagpagalit sa gobernador
Progress: 0.19
translated_text: nakuha niya ang isang reputasyon bilang isang artista bago siya nagsimulang magsulat | siya ay isang tao ng masamang ulat
Progress: 0.19
translated_text: Dose-dosenang mga insidente ng pambubugbog sa asawa ang iniulat araw-araw sa lungsod na ito | Ang pangkat ay nag-ulat ng mga makabuluhang pag-unlad sa kanilang pananaliksik
Progress: 0.19
translated_text: Iniulat ni Snow sa China noong 1950&#39;s | Sinakop ng cub reporter ang New York City
Progress: 0.19
translated_text: Gumawa siya ng tula | Nagsulat siya ng apat na nobela
Progress: 0.19
translated_text: Ilang aklat ang isinulat ni Georges Simenon? | Nag-publish siya ng 25 mga libro sa kanyang mahabang karera
Progress: 0.19
translated_text: Ang pintor ay nagsulat ng mga Chinese character sa isang malaking piraso ng puting papel | Ang Ruso ay nakasulat gamit ang alpabetong Cyrillic
Progress: 0.19
translated_text: ang kanyang salaysay ay kawili-wili | Ang mga kuwento ng Disney ay nakakaaliw sa mga matatanda pati na rin sa mga bata
Progress: 0.19
translated_text: Pinatunayan ng kanyang mataas na lagnat ang kanyang karamdaman | Ang mga gusali sa Roma ay nagpapakita ng mataas na antas ng pagiging sopistikado ng arkitektura | Ang desisyong ito ay nagpapakita ng kanyang pagkamakatarungan
Progress: 0.19
translated_text: ang mga epekto ng tagtuyot ay kitang-kita sa sinumang makakita sa mga tuyong bukid | maliwanag na poot | ipinahayag na hindi pag-apruba | mga pakinabang ng patent | ginawang malinaw ang kanyang kahulugan | ito ay malinaw na siya ay hindi reaksyonaryo | sa malinaw na pagtingin
Progress: 0.19
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.19
translated_text: glycerinated gelatin ay ginagamit bilang isang base para sa maraming ointments | sinabi niya sa pintor na gusto niya ng dilaw na base na may pahiwatig lamang ng berde | lahat ng niluto niya ay parang kanin ang basehan
Progress: 0.19
translated_text: baseborn wretches na may maruruming mukha | ng mapagpakumbaba (o mababang) kapanganakan
Progress: 0.19
translated_text: batayang barya ng aluminyo | isang base metal
Progress: 0.19
translated_text: base at di-makabayang motibo | isang base, nakababagot na paraan ng pamumuhay | ang pagdaraya ay hindi marangal | itinuturing nilang imoral ang kolonyalismo | hindi etikal na gawi sa paghawak ng pampublikong pondo
Progress: 0.19
translated_text: na liberal na pagsunod kung wala ang iyong hukbo ay magiging isang base rabble | pagkuha ng isang masamang bentahe | sinakal sa ambisyon ng mas makahulugang uri | isang bagay na mahalagang bulgar at masama sa pulitika
Progress: 0.19
translated_text: Sinibak ng amo ang kanyang sekretarya ngayon | Tinapos ng kumpanya ang 25% ng mga manggagawa nito
Progress: 0.19
translated_text: chemistry is not my cup of tea | ang kanyang bag ngayon ay natututong maglaro ng golf | ang pag-aasawa ay halos hindi niya ulam
Progress: 0.19
translated_text: chemistry is not my cup of tea | ang kanyang bag ngayon ay natututong maglaro ng golf | ang pag-aasawa ay halos hindi niya ulam
Progress: 0.19
translated_text: ang plastic ng isip ng mga bata | isang likas na mapagbigay
Progress: 0.19
translated_text: isang mapaghubog na impluwensya | isang karanasan sa pagbuo
Progress: 0.19
translated_text: ang tunog ng ulan sa bubong | ang ganda ng tunog ng musika
Progress: 0.19
translated_text: Nag `Mmmmm&#39; | Pumutok ang baril
Progress: 0.19
translated_text: tunog ang kampana | tunog ng isang tiyak na tala
Progress: 0.19
translated_text: mahusay na pamumuhunan | isang maayos na ekonomiya
Progress: 0.19
translated_text: malusog na pag-aalinlangan | isang malusog na takot sa rattlesnakes | ang malusog na saloobin ng mga batas ng Pransya | malusog na relasyon sa pagitan ng paggawa at pamamahala | isang matalinong solusyon | isang mahusay na diskarte sa problema | mahusay na payo | walang matinong paliwanag sa kanyang desisyon
Progress: 0.19
translated_text: isang sound timber | ang pader ay tunog | isang maayos na pundasyon
Progress: 0.19
translated_text: magandang ngipin | Mayroon pa akong isang magandang paa | isang maayos na pag-iisip sa isang maayos na katawan
Progress: 0.19
translated_text: isang mabigat na tulog | nakatulog ng mahimbing | isang sound sleeper | malalim na tulog na walang gising
Progress: 0.19
translated_text: isang termino sa bilangguan | umalis siya ng paaralan bago matapos ang termino
Progress: 0.19
translated_text: itinakda ng kontrata ang mga kondisyon ng pag-upa | ang mga tuntunin ng kasunduan ay mapagbigay
Progress: 0.20
translated_text: nag-ulat siya ng ilang hindi kilalang tawag | tumawag siya sa London | narinig niyang nagri-ring ang phone pero ayaw niyang sagutin ang tawag
Progress: 0.20
translated_text: hindi na tumatawag sa hapon ang mga asawa ng senior professors sa mga bagong dating | ang mga tauhan sa mga nobela ni Henry James ay walang hanggang tawag sa isa&#39;t isa, kadalasan sa parlor ng ilang tirahan
Progress: 0.20
translated_text: maraming tawag para sa mga kwentong Pasko | hindi maraming tawag para sa buggywhips
Progress: 0.20
translated_text: ang panawagan ng pastor sa kanyang mga parokyano | tawag ng tindero sa isang customer
Progress: 0.20
translated_text: Pinangalanan nila ang kanilang anak na David | Ang bagong paaralan ay ipinangalan sa sikat na pinuno ng Civil Rights
Progress: 0.20
translated_text: Tinawag niya akong bastard | Tinawag niyang tamad at walang utang na loob ang kanyang mga anak
Progress: 0.20
translated_text: Sinubukan kitang tawagan buong gabi | Kumuha ng dalawang aspirin at tawagan ako sa umaga
Progress: 0.20
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.20
translated_text: Siya ay tinawag sa opisina ng direktor | Tumawag ng pulis!
Progress: 0.20
translated_text: Ang Wannsee Conference ay tinawag upang talakayin ang `Final Solution&#39; | Ang bagong dean ay tumatawag ng mga pagpupulong bawat linggo
Progress: 0.20
translated_text: Tumatawag si Hawaii! | Isang transmiter sa Samoa ang narinig na tumatawag
Progress: 0.20
translated_text: Lagi niya akong tinatawag ng `Sir&#39; | Tawagin mo akong Mister | Tinatawag niya ito sa unang pangalan
Progress: 0.20
translated_text: 4 na beses na siyang tinawag para sa tungkulin ng hurado | Tinawag nila siya sa aktibong tungkuling militar
Progress: 0.20
translated_text: Tinawag niya ang pangalan ko | Tinawag ng auctioneer ang mga bid
Progress: 0.20
translated_text: nilaro nila basta magaan | basta maganda ang ilaw
Progress: 0.20
translated_text: nakita niya sa wakas ang liwanag | maaari mo bang bigyan ng liwanag ang problemang ito?
Progress: 0.20
translated_text: may kislap siya sa mata | may permanenteng kislap sa kanyang mga mata
Progress: 0.20
translated_text: nakita nila ang liwanag ng beacon | may ilaw sa bawat sulok
Progress: 0.20
translated_text: Ang matinding init ay maaaring mag-apoy ng halos anumang tuyong bagay | Magsindi ng sigarilyo
Progress: 0.20
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.20
translated_text: isang magaan na pagkarga | ang magnesiyo ay isang magaan na metal--may tiyak na gravity na 1.74 sa 20 degrees C
Progress: 0.20
translated_text: mapusyaw na asul | mapusyaw na kulay tulad ng mga pastel | isang mapusyaw na kulay na pulbos
Progress: 0.20
translated_text: light infantry | magaan na kabalyerya | magaan na industriya | magaan na armas
Progress: 0.20
translated_text: isang magaan na pangungusap | isang magaan na accent | ang mga nasawi ay magaan | mahinang snow ay bumabagsak | mahinang maulap na ulan | magaan na usok mula sa tsimenea
Progress: 0.20
translated_text: isang silid na maliwanag kapag nakabukas ang mga shutter | maaliwalas at magaan ang loob ng bahay
Progress: 0.20
translated_text: ang pantig na nagtatapos sa maikling patinig ay isang magaan na pantig | mahinang diin sa ikalawang pantig

Progress: 0.20
translated_text: pagsisikap na makakuha ng malinis na bass sa mga pag-record ng orkestra | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.20
translated_text: magaan at matikas ang mananayaw | isang lightsome buoyant step | naglakad na may mahinang hakbang
Progress: 0.20
translated_text: magaan na gawaing bahay | magaan na ehersisyo
Progress: 0.20
translated_text: ang magaan na pagdampi ng kanyang mga daliri | banayad na simoy ng hangin
Progress: 0.20
translated_text: biglang nanghina sa sakit | ay may sakit at nanghihina dahil sa gutom | magaan ang pakiramdam sa ulo | isang swooning fit | magaan ang ulo sa alak | magaan ang ulo dahil sa kawalan ng tulog
Progress: 0.20
translated_text: manipis na papel | magaan na damit ng tag-init
Progress: 0.20
translated_text: abstemious sa paggamit ng mga pang-abay | isang magaan na kumakain | isang magaan na naninigarilyo | kumain ng magaan na hapunan
Progress: 0.20
translated_text: isang light pound | isang kaunting tasa ng asukal | regular na nagbibigay ng maikling timbang
Progress: 0.20
translated_text: magaan na taludtod | isang light comedy
Progress: 0.20
translated_text: walang ginagawa na kasiyahan | magaan na banter | magaan na idle chat
Progress: 0.20
translated_text: magaan na sasakyang panghimpapawid | isang magaan na trak
Progress: 0.20
translated_text: diet cola | light (o lite) beer | lite (o magaan) mayonesa | isang mababang-cal na diyeta
Progress: 0.20
translated_text: sa isang idlip lang | isang light sleeper | isang hindi mapakali na puyat na gabi
Progress: 0.20
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.20
translated_text: nilaro nila basta magaan | basta maganda ang ilaw
Progress: 0.20
translated_text: nakita niya sa wakas ang liwanag | maaari mo bang bigyan ng liwanag ang problemang ito?
Progress: 0.20
translated_text: may kislap siya sa mata | may walang hanggang kislap sa kanyang mga mata
Progress: 0.20
translated_text: nakita nila ang liwanag ng beacon | may ilaw sa bawat sulok
Progress: 0.20
translated_text: Ang matinding init ay maaaring mag-apoy ng halos anumang tuyong bagay | Magsindi ng sigarilyo
Progress: 0.20
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.20
translated_text: isang magaan na pagkarga | Ang magnesiyo ay isang magaan na metal--may tiyak na gravity na 1.74 sa 20 degrees C
Progress: 0.20
translated_text: mapusyaw na asul | mapusyaw na kulay tulad ng mga pastel | isang mapusyaw na kulay na pulbos
Progress: 0.20
translated_text: light infantry | magaan na kabalyerya | magaan na industriya | magaan na armas
Progress: 0.20
translated_text: isang magaan na pangungusap | isang magaan na accent | ang mga nasawi ay magaan | mahinang snow ay bumabagsak | mahinang maulap na ulan | magaan na usok mula sa tsimenea
Progress: 0.21
translated_text: isang silid na maliwanag kapag nakabukas ang mga shutter | maaliwalas at magaan ang loob ng bahay
Progress: 0.21
translated_text: ang pantig na nagtatapos sa maikling patinig ay isang magaan na pantig | mahinang diin sa ikalawang pantig
Progress: 0.21
translated_text: pagsisikap na makakuha ng malinis na bass sa mga pag-record ng orkestra | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.21
translated_text: magaan at matikas ang mananayaw | isang lightsome buoyant step | naglakad na may mahinang hakbang
Progress: 0.21
translated_text: magaan na gawaing bahay | magaan na ehersisyo
Progress: 0.21
translated_text: ang magaan na pagdampi ng kanyang mga daliri | banayad na simoy ng hangin
Progress: 0.21
translated_text: biglang nanghina sa sakit | ay may sakit at nanghihina dahil sa gutom | magaan ang pakiramdam sa ulo | isang swooning fit | magaan ang ulo sa alak | magaan ang ulo dahil sa kawalan ng tulog
Progress: 0.21
translated_text: manipis na papel | magaan na damit ng tag-init
Progress: 0.21
translated_text: abstemious sa paggamit ng mga pang-abay | isang magaan na kumakain | isang magaan na naninigarilyo | kumain ng magaan na hapunan
Progress: 0.21
translated_text: isang light pound | isang kaunting tasa ng asukal | regular na nagbibigay ng maikling timbang
Progress: 0.21
translated_text: magaan na taludtod | isang light comedy
Progress: 0.21
translated_text: walang ginagawa na kasiyahan | magaan na banter | magaan na idle chat
Progress: 0.21
translated_text: magaan na sasakyang panghimpapawid | isang magaan na trak
Progress: 0.21
translated_text: diet cola | light (o lite) beer | lite (o magaan) mayonesa | isang mababang-cal na diyeta
Progress: 0.21
translated_text: sa isang idlip lang | isang light sleeper | isang hindi mapakali na puyat na gabi
Progress: 0.21
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.21
translated_text: I-clear ang manuskrito para sa publikasyon | Hindi pinahintulutan ng rock star ang mapanirang-puri na talambuhay na ito
Progress: 0.21
translated_text: linisin ang mga dahon sa damuhan | Maaliwalas na niyebe mula sa kalsada
Progress: 0.21
translated_text: Maaari mo bang linawin ang mga pangungusap na ito? | I-clear ang tanong kung sino ang may kasalanan
Progress: 0.21
translated_text: Magkano ang kinikita mo sa isang buwan sa iyong bagong trabaho? | Malaki ang kinikita niya sa bago niyang trabaho | ang pagsasanib na ito ay nagdala ng maraming pera | Kinukuha niya ang $5,000 bawat buwan
Progress: 0.21
translated_text: magbayad ng utang | lutasin ang isang lumang utang
Progress: 0.21
translated_text: isang malinaw at kasalukuyang panganib | isang malinaw na paliwanag | isang malinaw na kaso ng pagpatay | isang malinaw na indikasyon na siya ay galit | nagbigay sa atin ng malinaw na ideya ng kalikasan ng tao
Progress: 0.21
translated_text: isang kumplikadong problema na nangangailangan ng malinaw na ulo | hindi malinaw kung ano ang inaasahan sa atin
Progress: 0.21
translated_text: isang malinaw na pananaw | isang malinaw na landas tungo sa tagumpay | bukas na tubig | ang bukas na kanayunan
Progress: 0.21
translated_text: malinaw na tubig | malinaw na mga plastic bag | malinaw na salamin | malinaw at malinis ang hangin
Progress: 0.21
translated_text: kami ay malinaw sa panganib | ang barko ay malinaw sa bahura
Progress: 0.21
translated_text: malinis na budhi | tumingin sa kanyang nagtatanong na may malinaw na hindi nababagabag na mga mata
Progress: 0.21
translated_text: pagsisikap na makakuha ng malinis na bass sa mga orkestra na pag-record | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.21
translated_text: kasing linaw ng sipol | malinaw na mga yapak sa niyebe | ang liham ay nagbalik ng malinaw na imahe ng kanyang lolo | isang spire clean-cut laban sa langit | isang malinaw na pattern
Progress: 0.21
translated_text: isang malinis na bill ng kalusugan | isang malinaw na nagwagi
Progress: 0.21
translated_text: isang malinaw na perpektong brilyante | ang maaliwalas na kutis ng isang malusog na dalaga
Progress: 0.21
translated_text: ay absolved sa lahat ng sisihin | ngayon ay malinaw na sa paratang ng kaduwagan | ang kanyang opisyal na karangalan ay napagtibay
Progress: 0.21
translated_text: malinaw na isip | isang percipient na may-akda
Progress: 0.21
translated_text: basahin ang libro ng malinaw hanggang sa dulo | nakatulog nang malinaw sa buong gabi | may mga bukas na patlang na malinaw sa abot-tanaw
Progress: 0.21
translated_text: malinaw na makikita sa ilalim ng mikroskopyo | Umiyak siya ng malakas at malinaw
Progress: 0.21
translated_text: Linisin ang kalan! | Nilinis ng dentista ang ngipin ko
Progress: 0.21
translated_text: maglinis ka bago mo makita ang iyong mga lolo&#39;t lola | linisin ang iyong mga kuko bago kumain
Progress: 0.21
translated_text: Nilinis ng mga lalaki ang mga pinggan ng sandwich | Ang mga puno ay nalinis ng mga mansanas sa pamamagitan ng bagyo
Progress: 0.21
translated_text: mga batang may malinis na kumikinang na mukha | malinis na puting kamiseta | malinis na pinggan | isang malinis na bahay | ang pusa ay malinis na hayop

Progress: 0.21
translated_text: isang malinis na bill ng kalusugan | isang malinaw na nagwagi
Progress: 0.21
translated_text: pagsisikap na makakuha ng malinis na bass sa mga orkestra na pag-record | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.21
translated_text: malinis na tubig | sariwang hangin
Progress: 0.21
translated_text: isang malinis na rekord ng pagboto | malinis na lisensya sa pagmamaneho
Progress: 0.21
translated_text: isang malinis na gasolina | mas malinis at mas mahusay na mga makina | ang taktikal na bomba ay makatwirang malinis
Progress: 0.21
translated_text: magandang malinis na saya | isang malinis na biro
Progress: 0.21
translated_text: patas na kopya | isang malinis na manuskrito
Progress: 0.21
translated_text: mga blangkong pahina | punan ang mga blangkong puwang | isang malinis na pahina | malawak na puting mga gilid
Progress: 0.21
translated_text: isang malinis na laban | isang pampalakasang solusyon ng hindi pagkakasundo | mahilig sa sportsman
Progress: 0.21
translated_text: isang malinis na bakasyon | isang malinis na pagwawalis | isang malinis na pahinga
Progress: 0.21
translated_text: isang malinis na kaliwa ang napunta niya sa pisngi ng kanyang kalaban | isang malinis na hagis | ang maayos na kawastuhan ng kutsilyo ng surgeon
Progress: 0.22
translated_text: malinis nakalimutan ang appointment | Ako ay plumb (o plum) tuckered out
Progress: 0.22
translated_text: bumiyahe ang bola ng 90 mph sa kanyang serve | inihagis ng alkalde ang unang bola | gumulong ang bola sa sulok na bulsa
Progress: 0.22
translated_text: ang bola sa base ng hinlalaki | tumayo siya sa mga bola ng kanyang mga paa
Progress: 0.22
translated_text: gumagalaw ang Earth sa paligid ng araw | naglayag siya sa buong mundo
Progress: 0.22
translated_text: pinamunuan niya ang isang maliit na brilyante | diamante ay trumps
Progress: 0.22
translated_text: pinamunuan niya ang isang maliit na brilyante | diamante ay trumps
Progress: 0.22
translated_text: ang mga istante ng tindahan ay naglalaman ng maraming iba&#39;t ibang uri ng tsaa | itinapon nila ang tsaa sa daungan ng Boston
Progress: 0.22
translated_text: gumamit ng halaman ang pulis para linlangin ang mga magnanakaw | inangkin niya na ang ebidensya laban sa kanya ay isang halaman
Progress: 0.22
translated_text: Nagtanim siya ng tuhod sa likod ng kanyang kalaban | Ang dentista ay nagtanim ng ngipin sa gilagid
Progress: 0.22
translated_text: Magtanim ng espiya sa Moscow | magtanim ng mga bug sa apartment ng dissident
Progress: 0.22
translated_text: isang tuwid na tangkad | tuwid na mga tangkay ng bulaklak | para sa isang aso, ang isang tuwid na buntot ay nagpapahiwatig ng pagsalakay | isang haligi na patayo pa rin sa gitna ng mga guho | umupo siya ng bolt patayo
Progress: 0.22
translated_text: Ipinakita ng eksperimento ang kawalang-tatag ng tambalang | Ipinakita ng mathematician ang bisa ng haka-haka
Progress: 0.22
translated_text: maaga silang nagsimula | alam niyang simula pa lang ay siya na ang lalaking para sa kanya
Progress: 0.22
translated_text: siya ay nagsimula dahil ang isa sa mga regular na pitcher ay nasa ospital | ang ibig sabihin ng kanyang pagsisimula ay naisip ng coach na isa siya sa kanilang pinakamahusay na linemen
Progress: 0.22
translated_text: ang panimulang signal ay berdeng ilaw | hinintay ng mga mananakbo ang simula
Progress: 0.22
translated_text: Nagsimula kaming magtrabaho sa madaling araw | Sino ang magsisimula? | Magtrabaho kaagad sa pagsikat ng araw! | Nagsimulang dumating ang mga unang turista sa Cambodia | Nagsimula siya sa madaling araw | Bumaba na tayo sa trabaho
Progress: 0.22
translated_text: Nagsimula ang US ng digmaan sa Gitnang Silangan | Nagsimula ang mga Iraqi ng labanan | magsimula ng bagong kabanata sa iyong buhay
Progress: 0.22
translated_text: Nagsisimula ang DMZ sa ibabaw mismo ng burol | Magsisimula ang ikalawang kilusan pagkatapos ng Allegro | Ang mga presyo para sa mga bahay na ito ay nagsisimula sa $250,000
Progress: 0.22
translated_text: Nagsimula siya ng bagong programa | Magsimula ng isang pundasyon
Progress: 0.22
translated_text: Sino ang nagsimula ng kumpanyang ito? | Nagsimula kami sa isang kapana-panabik na negosyo | Sinisimulan ko ang aking araw sa isang masarap na almusal | Sinimulan namin ang bagong semestre | Ang sesyon sa hapon ay magsisimula sa 4 PM | Nagsimula ang pagdanak ng dugo nang maglunsad ng sorpresang pag-atake ang mga partisan
Progress: 0.22
translated_text: Hindi namin ma-start ang makina | simulan ang computer
Progress: 0.22
translated_text: Magsisimula ako ng alas otso ng umaga | Ready, set, go!
Progress: 0.22
translated_text: Kumuha ng posisyon | magsimula ng bagong trabaho
Progress: 0.22
translated_text: Nagsimula ang nobela sa isang pagpatay | Nagsisimula ang aking ari-arian sa tatlong puno ng maple | Ang kanyang araw ay nagsisimula sa isang pag-eehersisyo | Nagsisimula ang semestre sa isang convocation ceremony
Progress: 0.22
translated_text: magsimula ng tabako | Sinimulan niya ang sabaw habang mainit pa | Nagsimula kami sa physics noong ika-10 baitang
Progress: 0.22
translated_text: maaga silang nagsimula | alam niyang simula pa lang ay siya na ang lalaking para sa kanya
Progress: 0.22
translated_text: siya ay nagsimula dahil ang isa sa mga regular na pitcher ay nasa ospital | ang ibig sabihin ng kanyang pagsisimula ay naisip ng coach na isa siya sa kanilang pinakamahusay na linemen
Progress: 0.22
translated_text: ang panimulang signal ay berdeng ilaw | ang mga mananakbo ay naghintay sa pagsisimula
Progress: 0.22
translated_text: Nagsimula kaming magtrabaho sa madaling araw | Sino ang magsisimula? | Magtrabaho kaagad sa pagsikat ng araw! | Nagsimulang dumating ang mga unang turista sa Cambodia | Nagsimula siya sa madaling araw | Bumaba na tayo sa trabaho
Progress: 0.22
translated_text: Nagsimula ang US ng digmaan sa Gitnang Silangan | Nagsimula ang mga Iraqi ng labanan | magsimula ng bagong kabanata sa iyong buhay
Progress: 0.22
translated_text: Nagsisimula ang DMZ sa ibabaw mismo ng burol | Magsisimula ang ikalawang kilusan pagkatapos ng Allegro | Ang mga presyo para sa mga bahay na ito ay nagsisimula sa $250,000
Progress: 0.22
translated_text: Nagsimula siya ng bagong programa | Magsimula ng isang pundasyon
Progress: 0.22
translated_text: Sino ang nagsimula ng kumpanyang ito? | Nagsimula kami sa isang kapana-panabik na negosyo | Sinisimulan ko ang aking araw sa masarap na almusal | Sinimulan namin ang bagong semestre | Ang sesyon sa hapon ay magsisimula sa 4 PM | Nagsimula ang pagdanak ng dugo nang maglunsad ng sorpresang pag-atake ang mga partisan
Progress: 0.22
translated_text: Hindi namin ma-start ang makina | simulan ang computer
Progress: 0.22
translated_text: Magsisimula ako ng alas otso ng umaga | Ready, set, go!
Progress: 0.22
translated_text: Kumuha ng posisyon | magsimula ng bagong trabaho
Progress: 0.22
translated_text: Nagsimula ang nobela sa isang pagpatay | Nagsisimula ang aking ari-arian sa tatlong puno ng maple | Ang kanyang araw ay nagsisimula sa isang pag-eehersisyo | Nagsisimula ang semestre sa isang convocation ceremony
Progress: 0.22
translated_text: magsimula ng tabako | Sinimulan niya ang sabaw habang mainit pa | Nagsimula kami sa physics noong ika-10 baitang
Progress: 0.22
translated_text: gumamit ng halaman ang pulis para linlangin ang mga magnanakaw | inangkin niya na ang ebidensya laban sa kanya ay isang halaman
Progress: 0.22
translated_text: Nagtanim siya ng tuhod sa likod ng kanyang kalaban | Ang dentista ay nagtanim ng ngipin sa gilagid
Progress: 0.22
translated_text: Magtanim ng espiya sa Moscow | magtanim ng mga bug sa apartment ng dissident
Progress: 0.22
translated_text: hindi niya nagustuhan ang mahabang paalam | umalis siya | ang paghihiwalay ay napakatamis na kalungkutan
Progress: 0.22
translated_text: Anong oras aalis ang iyong tren? | Hindi siya umalis hanggang hatinggabi | Aalis ang barko sa hatinggabi
Progress: 0.22
translated_text: Nag-iwan siya ng gulo nang lumipat siya | Sa wakas ay iniwan siya ng kanyang suwerte | iniwan siya ng kanyang asawa pagkatapos ng 20 taong pagsasama | umiiyak siya sa pag-aakalang siya ay naiwan

Progress: 0.22
translated_text: Ang inflation ay nag-iwan sa kanila na walang pera | Hindi kami nakaimik dahil sa sinabi ng pangulo
Progress: 0.22
translated_text: iwanan ito bilang ay | pabayaan ang batang usa | iwanan ang mga bulaklak na nakikita mo sa parke
Progress: 0.22
translated_text: umalis ng kwarto | umalis ng bansa ang takas
Progress: 0.22
translated_text: Hindi ito nag-iiwan ng puwang para sa pagpapabuti | Ang ebidensya ay nagpapahintulot lamang ng isang konklusyon | payagan ang mga pagkakamali | mag-iwan ng maraming oras para sa biyahe | Ang pamamaraang ito ay nagbibigay ng maraming pahinga
Progress: 0.22
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.22
translated_text: Gusto niyang umalis | Umalis ng bahay ang binatilyo | Iniwan niya ang kanyang posisyon sa Red Cross | Umalis siya sa Senado pagkaraan ng dalawang termino | pagkatapos ng 20 taon sa kaparehong kumpanya, nag-pusta siya
Progress: 0.22
translated_text: Ipinaubaya niya ang desisyon sa kanyang kinatawan | iwanan ang iyong anak sa pangangalaga ng nars
Progress: 0.23
translated_text: Ipinamana sa akin ng aking tiyahin ang lahat ng kanyang alahas | Iniwan sa akin ng aking lolo ang kanyang buong ari-arian
Progress: 0.23
translated_text: Naiwan kaming apat | 19 bawas 8 dahon 11
Progress: 0.23
translated_text: Iniwan niya ang anim na anak | Sa kanyang pagkamatay, iniwan niya ang kanyang asawa at 11 pusa
Progress: 0.23
translated_text: magbigay ng lihim sa mga Ruso | iwanan ang iyong pangalan at tirahan dito | magbigay ng bagong kasanayan sa mga mag-aaral
Progress: 0.23
translated_text: Nakalimutan ko yung payong ko sa restaurant | Iniwan ko ang susi ko sa loob ng sasakyan at ni-lock ang pinto
Progress: 0.23
translated_text: ang magnetic effect ay mas malaki kapag ang baras ay pahaba | ang kanyang desisyon ay may nakapanlulumong kahihinatnan para sa negosyo | napaka bait niya pagkatapos ng pangyayari
Progress: 0.23
translated_text: ang mga desisyon na may malaking kahihinatnan ay ginawa mismo ng pangulo | ang kabutihan ay higit na sandali kaysa sa seguridad | ang resulta ay walang kahihinatnan
Progress: 0.23
translated_text: ang magnetic effect ay mas malaki kapag ang baras ay pahaba | ang kanyang desisyon ay may nakapanlulumong kahihinatnan para sa negosyo | masyado siyang matalino pagkatapos ng kaganapan
Progress: 0.23
translated_text: sila ay nagsisikap na makahanap ng mapayapang solusyon | ang mga sagot ay nasa likod ng libro | kinalkula niya ang resulta sa apat na decimal na lugar
Progress: 0.23
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.23
translated_text: pambata tantrums | pag-uugali ng bata
Progress: 0.23
translated_text: muling umiyak ang sanggol | hinawakan niya ang sanggol sa kanyang mga bisig | parang simple lang, pero kapag may sarili kang baby, iba na lahat
Progress: 0.23
translated_text: muling umiyak ang sanggol | hinawakan niya ang sanggol sa kanyang mga bisig | parang simple lang, pero kapag may sarili kang baby, iba na lahat
Progress: 0.23
translated_text: ang sanggol ng pamilya | ang sanggol ng Korte Suprema
Progress: 0.23
translated_text: nanatili siyang bata sa mga praktikal na bagay habang siya ay nabubuhay | tumigil ka sa pagiging baby!
Progress: 0.23
translated_text: Malusog at napakababae ang pakiramdam ko habang dinadala ang sanggol | ang sarap sa pakiramdam na gumagalaw ang baby ko sa loob
Progress: 0.23
translated_text: madalas palayawin ng mga lolo&#39;t lola ang mga bata | Huwag nating mollycoddle ang ating mga estudyante!
Progress: 0.23
translated_text: muling umiyak ang sanggol | hinawakan niya ang sanggol sa kanyang mga bisig | parang simple lang, pero kapag may sarili kang baby, iba na lahat
Progress: 0.23
translated_text: bagong patatas | batang mais
Progress: 0.23
translated_text: isang batang industriya | bata pa ang araw
Progress: 0.23
translated_text: unseasoned artillery volunteers | hindi pa nasusubok sa labanan | isang illustrator na hindi pa nasusubukan sa mural painting | isang batang kamay sa pag-aararo
Progress: 0.23
translated_text: muling umiyak ang sanggol | hinawakan niya ang sanggol sa kanyang mga bisig | parang simple lang, pero kapag may sarili kang baby, iba na lahat
Progress: 0.23
translated_text: ang sanggol ng pamilya | ang sanggol ng Korte Suprema
Progress: 0.23
translated_text: nanatili siyang bata sa mga praktikal na bagay habang siya ay nabubuhay | tumigil ka sa pagiging baby!
Progress: 0.23
translated_text: Malusog at napakababae ang pakiramdam ko habang dinadala ang sanggol | ang sarap sa pakiramdam na gumagalaw ang baby ko sa loob
Progress: 0.23
translated_text: madalas palayawin ng mga lolo&#39;t lola ang mga bata | Huwag nating mollycoddle ang ating mga estudyante!
Progress: 0.23
translated_text: Ang mga uling ay kumikinang sa dilim | Ang mga kandila ay nasusunog
Progress: 0.23
translated_text: Nasunog ang araw sa hamog | Nagsusunog kami ng karbon at iba pang fossil fuel
Progress: 0.23
translated_text: Nag-aapoy siya sa galit | Siya ay nasusunog upang subukan ang kanyang bagong himpapawid
Progress: 0.23
translated_text: magsunog ng basura | Diesel oil lang ang sinusunog ng sasakyan
Progress: 0.23
translated_text: gupitin ang isang disk | magsunog ng CD
Progress: 0.23
translated_text: naubos ang mga produkto ng pagkasunog sa makina | naglalabas ng gas ang halaman
Progress: 0.23
translated_text: naubos ang mga produkto ng pagkasunog sa makina | naglalabas ng gas ang halaman
Progress: 0.23
translated_text: Dinanas niya ang parusa | Maraming mga santo ang dumanas ng pagkamartir
Progress: 0.23
translated_text: Nagdusa siya ng bali sa aksidente | Nagkaroon siya ng insulin shock pagkatapos kumain ng tatlong candy bar | Nagkaroon siya ng pasa sa binti | Nabali ang braso niya sa scuffle
Progress: 0.23
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.23
translated_text: matugunan ang isang marahas na kamatayan | magdusa ng isang kakila-kilabot na kapalaran
Progress: 0.23
translated_text: nakaramdam siya ng panlulumo at kahabag-habag | isang mensahe ng pag-asa para sa naghihirap na sangkatauhan | kawawang mga bilanggo na nagsisiksikan sa mabahong mga kulungan
Progress: 0.23
translated_text: hawakan mo ang iyong apoy hanggang sa makita mo ang puti ng kanilang mga mata | umatras sila sa harap ng nalalanta na apoy ng kaaway
Progress: 0.23
translated_text: magpaputok ng baril | magpaputok ng bala
Progress: 0.23
translated_text: Sinibak ng amo ang kanyang sekretarya ngayon | Tinapos ng kumpanya ang 25% ng mga manggagawa nito
Progress: 0.23
translated_text: Sinibak ang mga sundalo | Ang pagsuko ay nagpaputok ng malamig na pag-aalinlangan
Progress: 0.23
translated_text: pukawin ang awa | taasan ang isang ngiti | pukawin ang pakikiramay
Progress: 0.23
translated_text: hawakan mo ang iyong apoy hanggang sa makita mo ang puti ng kanilang mga mata | umatras sila sa harap ng nalalanta na apoy ng kaaway
Progress: 0.23
translated_text: ilagay ang takure sa apoy | barbecue sa isang bukas na apoy
Progress: 0.23
translated_text: Itinuro ni Clinton ang kanyang apoy sa Republican Party | inatake ang gobyerno | huwag mo akong bigyan ng anumang flak
Progress: 0.23
translated_text: magpaputok ng baril | magpaputok ng bala
Progress: 0.23
translated_text: Sinibak ng amo ang kanyang sekretarya ngayon | Tinapos ng kumpanya ang 25% ng mga manggagawa nito
Progress: 0.23
translated_text: Sinibak ang mga sundalo | Ang pagsuko ay nagpaputok ng malamig na pag-aalinlangan
Progress: 0.23
translated_text: pukawin ang awa | taasan ang isang ngiti | pukawin ang pakikiramay
Progress: 0.24
translated_text: polusyon sa hangin | isang amoy ng mga kemikal sa hangin | magbukas ng bintana at magpapasok ng hangin | Kailangan ko ng sariwang hangin
Progress: 0.24
translated_text: huminto ang kanyang kamay sa kalagitnaan ng hangin | inihagis niya ang bola sa ere
Progress: 0.24
translated_text: isang himpapawid ng misteryo | ang bahay ay may napabayaang hangin | isang kapaligiran ng pagkatalo ang bumalot sa punong tanggapan ng kandidato | may aura ng romansa ang lugar

Progress: 0.24
translated_text: ang simoy ng hangin ay pinalamig ng lawa | habang naghihintay siya ay nararamdaman niya ang hangin sa kanyang leeg
Progress: 0.24
translated_text: nagkaroon ng matinding init habang ang kometa ay pumasok sa kapaligiran | tumambad ito sa hangin
Progress: 0.24
translated_text: ang programa ay nasa ere mula 9 hanggang hatinggabi | ginamit ng pangulo ang airwaves para dalhin ang kanyang mensahe sa mga tao
Progress: 0.24
translated_text: Ang paglalakbay sa himpapawid ay nagsasangkot ng labis na paghihintay sa mga paliparan | kung mayroon kang oras upang maglaan pumunta sa pamamagitan ng hangin
Progress: 0.24
translated_text: ipasahimpapawid ang mga lumang damit ng taglamig | magpahangin sa mga silid na puno ng usok
Progress: 0.24
translated_text: ang simoy ng hangin ay pinalamig ng lawa | habang naghihintay siya ay nararamdaman niya ang hangin sa kanyang leeg
Progress: 0.24
translated_text: mga punong nakayuko sa ilalim ng mabangis na hangin | kapag walang hangin, hilera | ang radyaktibidad ay tinatangay paitaas ng agos ng hangin at palabas sa atmospera
Progress: 0.24
translated_text: iyan ay maraming hangin | wag mo akong bigyan ng jazz na yan
Progress: 0.24
translated_text: nakakuha siya ng tip sa stock market | isang magandang lead para sa isang trabaho
Progress: 0.24
translated_text: ang ilog ay umiikot sa mga burol | ang landas ay lumiliko sa mga ubasan | minsan, gumagala ang gout sa buong katawan
Progress: 0.24
translated_text: Ang daan ay umiikot sa lawa | ang landas na baluktot sa kagubatan
Progress: 0.24
translated_text: igulong ang iyong buhok sa paligid ng iyong daliri | Ikabit ang sinulid sa palibot ng spool | Niyakap niya ang anak
Progress: 0.24
translated_text: nilusob nila ang ating teritoryal na tubig | nakaupo sila sa gilid ng tubig
Progress: 0.24
translated_text: pinagdebatehan ng bayan ang paglilinis ng suplay ng tubig | kailangan mo munang putulin ang tubig
Progress: 0.24
translated_text: may dugo sa kanyang ihi | kailangang gumawa ng tubig ang bata
Progress: 0.24
translated_text: Napaawang ang aking bibig sa inaasahang magandang hapunan | Namilog ang kanyang mga mata
Progress: 0.24
translated_text: sinubukan nila ang kanyang kakayahan upang mahanap ang mga bagay sa kalawakan | ang walang hangganang mga rehiyon ng walang hanggan
Progress: 0.24
translated_text: nag-iwan ng espasyo ang arkitekto sa harap ng gusali | huminto sila sa isang open space sa gubat | ang espasyo sa pagitan ng kanyang mga ngipin
Progress: 0.24
translated_text: ang mga astronaut ay naglakad sa kalawakan nang walang tether | ang unang pangunahing milestone sa paggalugad sa kalawakan ay noong 1957, nang ang Sputnik 1 ng USSR ay umikot sa Earth
Progress: 0.24
translated_text: ang layo mula sa kapanganakan hanggang kamatayan | nangyari ang lahat sa loob ng 10 minuto
Progress: 0.24
translated_text: sinubukan nila ang kanyang kakayahan upang mahanap ang mga bagay sa kalawakan | ang walang hangganang mga rehiyon ng walang hanggan
Progress: 0.24
translated_text: nag-iwan ng espasyo ang arkitekto sa harap ng gusali | huminto sila sa isang open space sa gubat | ang espasyo sa pagitan ng kanyang mga ngipin
Progress: 0.24
translated_text: ang mga astronaut ay naglakad sa kalawakan nang walang tether | ang unang pangunahing milestone sa paggalugad sa kalawakan ay noong 1957, nang ang Sputnik 1 ng USSR ay umikot sa Earth
Progress: 0.24
translated_text: ang layo mula sa kapanganakan hanggang kamatayan | nangyari ang lahat sa loob ng 10 minuto
Progress: 0.24
translated_text: nakuha niya sa isang kahila-hilakbot na ayusin | gumawa siya ng kaguluhan sa kanyang kasal
Progress: 0.24
translated_text: ang kanyang marangal na ugali | ang kanyang mabilis na paraan ng pagsasalita | kanilang nomadic mode of existence | sa katangiang istilo ng New York | isang malungkot na paraan ng pamumuhay | sa isang nakasasakit na paraan
Progress: 0.24
translated_text: ang balat ay ang pinakabagong uso | sinundan niya ang mga kasalukuyang uso | ang 1920s ay may sariling istilo
Progress: 0.24
translated_text: I-istilo ang aking buhok | i-istilo ang damit
Progress: 0.24
translated_text: ang kanyang marangal na ugali | ang kanyang mabilis na paraan ng pagsasalita | kanilang nomadic mode of existence | sa katangiang istilo ng New York | isang malungkot na paraan ng pamumuhay | sa isang nakasasakit na paraan
Progress: 0.24
translated_text: isang paraan ng kontrol | isang halimbawa ay ang pinakamahusay na ahensya ng pagtuturo | ang tunay na daan tungo sa tagumpay
Progress: 0.24
translated_text: tumingin siya sa ibang direksyon | hindi alam ang daan pauwi
Progress: 0.24
translated_text: ganyan talaga | Ganun din ang naramdaman ko
Progress: 0.24
translated_text: ang landas ng kabutihan | magkahiwalay kami ng daan | ang mga landas natin sa buhay ang naghiwalay sa atin | ang henyo ay karaniwang sumusunod sa isang rebolusyonaryong landas
Progress: 0.24
translated_text: silid na dadaanan | gumawa ng paraan para sa | halos walang sapat na silid sa siko upang lumingon
Progress: 0.24
translated_text: ito ay isang mahabang paraan sa Moscow | malayo-layo ang kanyang narating
Progress: 0.24
translated_text: over budget | malayo sa base | ang kabilang bahagi ng burol ay tama matalinong mas matarik kaysa sa gilid na aming kinaroroonan
Progress: 0.24
translated_text: isang malawakang operasyon ng pagsasaka | isang multinasyunal na operasyon | nagbayad sila ng buwis sa bawat yugto ng operasyon | kinailangan nilang pagsamahin ang kanilang mga operasyon
Progress: 0.24
translated_text: nag-organisa sila ng rescue operation | ang pinakamalaking operasyon ng pulisya sa kasaysayan ng Pransya | pagpapatakbo ng isang restaurant ay medyo isang operasyon | pagsamahin ang mga kumpanya sa iba&#39;t ibang operasyon
Progress: 0.24
translated_text: iiskedyul nila ang operasyon sa sandaling magkaroon ng operating room | namatay siya habang sumasailalim sa operasyon
Progress: 0.24
translated_text: ang mga operasyon sa paggawa ng bahay | ilang operasyon ng machine tool
Progress: 0.24
translated_text: ang lakas ng makina nito ay tumutukoy sa operasyon nito | ang pagpapatakbo ng eroplano sa malakas na hangin | inihambing nila ang pagganap ng pagluluto ng bawat oven | ang pagganap ng jet ay umaayon sa matataas na pamantayan
Progress: 0.24
translated_text: ang proseso ng pag-iisip | ang cognitive operation ng pag-alala
Progress: 0.24
translated_text: ang mga problema sa dulo ng kabanata ay nagpakita ng mga prosesong matematikal na kasangkot sa derivation | natututo sila ng mga pangunahing operasyon ng arithmetic
Progress: 0.24
translated_text: ang defensive line braced para ihinto ang pagtakbo | ang coach ay nagbigay ng malaking diin sa pagtakbo
Progress: 0.24
translated_text: sumabog siya sa pagtakbo | ang kanyang pang-araw-araw na pagtakbo ay nagpapanatili sa kanya ng fit
Progress: 0.24
translated_text: Wag kang tatakbo--malagutan ka ng hininga | Nagtakbuhan ang mga bata sa tindahan
Progress: 0.24
translated_text: Kung nakita mo ang lalaking ito, tumakbo ka! | Nakatakas ang mga magnanakaw bago dumating ang mga pulis
Progress: 0.25
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.25
translated_text: ang kuwento o argumento ay tumatakbo bilang mga sumusunod | sabi nga sa kasabihan...
Progress: 0.25
translated_text: Umagos ang tubig sa kweba | ang Missouri ay nagpapakain sa Mississippi
Progress: 0.25
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.25
translated_text: Mga pagtatantya para sa mga pagkalugi sa saklaw ng lindol na kasing taas ng $2 bilyon | Ang mga rate ng interes ay tumatakbo mula 5 hanggang 10 porsyento | Ang mga instrumento ay mula sa tuba hanggang sa mga simbalo | Ang aking mga mag-aaral ay mula sa napakaliwanag hanggang sa mapurol
Progress: 0.25
translated_text: Paulit-ulit nilang pinaandar ang mga tape | Tutugtog kita ng paborito kong record | Hindi siya nagsasawang i-play ang video na iyon

Progress: 0.25
translated_text: sino itong mga taong tumatakbo sa gusali? | Tumatakbo siya sa paligid na nagsasabi sa lahat ng kanyang mga problema | palayain ang mga aso
Progress: 0.25
translated_text: Siya ay madalas na kinakabahan bago ang kanyang mga lektura | Ang mga damit na ito ay tumatakbo nang maliit | Siya ay hilig sa katabaan
Progress: 0.25
translated_text: mag-amok | tumakbong buhong | magpatakbo ng kaguluhan
Progress: 0.25
translated_text: magpatakbo ng isang paksa | magpatakbo ng isang proseso
Progress: 0.25
translated_text: magpatakbo ng temperatura | makipagsapalaran
Progress: 0.25
translated_text: Ang mga kwentong ito ay die hard | Ang alamat ni Elvis ay nagtitiis
Progress: 0.25
translated_text: Patakbuhin ang makinang panghugas | magpatakbo ng bagong program sa Mac | ang computer ay nagsagawa ng pagtuturo
Progress: 0.25
translated_text: Tatlong beses naming pinatakbo ang ad | Ang papel na ito ay nagdadala ng pagsusuri sa restawran | Lahat ng malalaking network ay nagsagawa ng press conference
Progress: 0.25
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.25
translated_text: Tumakbo sa tindahan! | Palagi siyang tumatakbo sa Italy, dahil may manliligaw siya doon
Progress: 0.25
translated_text: Madalas manghuli si Goering ng mga baboy-ramo sa Poland | Ang mga aso ay tumatakbo sa usa | Nangangaso ang Duke sa kagubatan na ito
Progress: 0.25
translated_text: siya ay tumatakbo sa Marathon sa taong ito | karera tayo at tingnan kung sino ang unang makarating doon
Progress: 0.25
translated_text: Ang talumpati ay kailangang dumaan sa ilang higit pang mga draft | patakbuhin ang iyong presentasyon bago ang pulong
Progress: 0.25
translated_text: tunawin ang mantikilya | tunawin ang ginto | Ang wax ay natunaw sa araw
Progress: 0.25
translated_text: bilang batis ng bundok na may malayang umaagos na tubig | mga hovel na walang tumatakbong tubig
Progress: 0.25
translated_text: gumana nang mas mahusay ang mga running play kaysa sa mga pass play | tumalon sa pagtakbo | isang tumatakbong simula
Progress: 0.25
translated_text: sa pagpapatakbo (o gumagana) order | isang functional na hanay ng mga preno
Progress: 0.25
translated_text: tumingin siya sa ibang direksyon | hindi alam ang daan pauwi
Progress: 0.25
translated_text: Hindi ko masundan ang direksyon ng kanyang iniisip | ang kanyang mga mithiin ay nagpasiya ng direksyon ng kanyang karera | nagmungkahi sila ng bagong direksyon para sa kompanya
Progress: 0.25
translated_text: binigyan siya ng pangkalahatang pamamahala ng programa | ang direksyon ba ng ekonomiya ay tungkulin ng pamahalaan?
Progress: 0.25
translated_text: ang pokus ng aktibidad ay lumipat sa molecular biology | wala siyang direksyon sa buhay niya
Progress: 0.25
translated_text: isang stream ng mga tao na walang laman mula sa terminal | ang museo ay nagplano nang mabuti para sa daloy ng mga bisita
Progress: 0.25
translated_text: dalawang daloy ng pag-unlad ang tumatakbo sa kasaysayan ng Amerika | batis ng kamalayan | ang daloy ng pag-iisip | agos ng kasaysayan
Progress: 0.25
translated_text: ang mga babae ay may sakit at napapailalim sa labis na regla | ang isang babae ay hindi umiinom ng gout maliban kung ang kanyang regla ay itinigil | ang semilya ay nagsisimulang lumitaw sa mga lalaki at ilalabas sa parehong oras ng buhay na ang catamenia ay nagsisimulang dumaloy sa mga babae
Progress: 0.25
translated_text: Umagos ang tubig sa kweba | ang Missouri ay nagpapakain sa Mississippi
Progress: 0.25
translated_text: Ang damit na ito ay nakabitin nang maayos | Ang mahaba niyang itim na buhok ay dumaloy sa kanyang likuran
Progress: 0.25
translated_text: isang desisyon na hindi pabor sa oposisyon | isinaalang-alang ng kanyang konklusyon ang ebidensya | nasiyahan sa pagpapasiya ng panel
Progress: 0.25
translated_text: ang stopping point ng bawat round ay sinenyasan ng bell | ang merkado ay hanggang sa matapos | mas mahusay silang naglalaro sa pagtatapos ng season
Progress: 0.25
translated_text: ang kanyang kamatayan ay minarkahan ang pagtatapos ng isang panahon | kapag na-broadcast ang mga huling yugto na ito, ito na ang magiging pagtatapos ng palabas
Progress: 0.25
translated_text: ang pagtatapos ng isang deal sa negosyo | ang pagtatapos ng kasunduan sa kapayapaan
Progress: 0.25
translated_text: ang pasanin ng desisyon ay kanyang | mabilis siyang gumawa ng konklusyon
Progress: 0.25
translated_text: dulo ng pier | binuhol niya ang dulo ng thread | sumakay sila hanggang sa dulo ng linya | ang mga terminal ng anterior arches ng fornix
Progress: 0.25
translated_text: katapusan ng taon | ang pagtatapos ng panahon ng warranty
Progress: 0.25
translated_text: kapana-panabik ang wakas | Kinailangan kong ma-miss ang huling bahagi ng pelikula
Progress: 0.25
translated_text: ibinigay namin ito sa dulo ng seksyon dahil kinasasangkutan nito ang calculus | Magsimula sa simula at magpatuloy hanggang sa makarating ka sa dulo
Progress: 0.25
translated_text: siya ay dumating sa isang masamang wakas | ang tinatawag na maluwalhating eksperimento ay dumating sa isang nakakahiya na wakas
Progress: 0.25
translated_text: tumunog ang telepono sa kabilang dulo | magkasabay na isinulat ang magkabilang dulo
Progress: 0.25
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.25
translated_text: Tinapos niya ang kanilang pagkakaibigan nang malaman niyang minsan na itong nahatulan ng isang krimen | Ang pag-atake sa Poland ay nagwakas sa medyo mapayapang panahon pagkatapos ng WW I
Progress: 0.25
translated_text: magmahalan, hindi digmaan | magsikap | magsaliksik | walang gawin | gumawa ng rebolusyon
Progress: 0.25
translated_text: Ginawa ni John ang pagpipinta, ang pagtanggal ng damo, at nilinis niya ang mga kanal | nagsagawa ng triple pirouette ang skater | gumawa siya ng kaunting sayaw
Progress: 0.25
translated_text: Kumusta na kaya siya sa bago niyang trabaho? | Kumusta ka na sa graduate school? | Malayo na ang narating niya
Progress: 0.25
translated_text: magdulot ng kaguluhan | gumawa ng paghalo | magdulot ng aksidente
Progress: 0.25
translated_text: Ang ilang mga salita ay sasagot | Ang kotseng ito ay angkop sa aking layunin | Magagawa ba ang $100? | Ang gradong &#39;B&#39; ay hindi sapat para makapasok ako sa medikal na paaralan | Wala nang ibang magsisilbi
Progress: 0.26
translated_text: Gawin ang aking silid sa asul | Ginawa ko ang pirasong ito sa kahoy upang ipahayag ang aking pagmamahal sa kagubatan
Progress: 0.26
translated_text: Dapat kang kumilos bilang isang may sapat na gulang | Huwag kumilos na parang tanga | Ano ang dahilan kung bakit niya ginagawa ito? | Mabangis ang kilos ng aso, ngunit talagang takot siya sa mga tao
Progress: 0.26
translated_text: Gumagawa ang sasakyang ito ng 150 milya bawat oras | Nagsagawa kami ng 6 na milya sa aming paglalakad araw-araw
Progress: 0.26
translated_text: Si John ay mayaman | Hindi ito magandang sagot
Progress: 0.26
translated_text: Ang presidente ng kumpanya ay si John Smith | Ito ang aking bahay
Progress: 0.26
translated_text: Nasaan ang payong ko? | Ang toolshed ay nasa likod | Ano ang nasa likod ng pag-uugaling ito?
Progress: 0.26
translated_text: Nawala ko ang aking pitaka; ito ay sa pagbisita sa bahay ng aking mga magulang | Mayroong dalawang daang tao sa kanyang libing | Nagkaroon ng maraming ingay sa kusina
Progress: 0.26
translated_text: Ang pera na ito ang tanging kita ko | Ang pader na bato ay ang backdrop para sa pagtatanghal | Ang mga ito ay bumubuo sa aking buong pag-aari | Binubuo ng mga bata ang koro | Ang kabuuan na ito ay kumakatawan sa aking buong kita para sa isang taon | Ang iilang lalaking ito ay binubuo ng kanyang buong hukbo
Progress: 0.26
translated_text: Siya ay isang herpetologist | Siya ang aming resident philosopher
Progress: 0.26
translated_text: Ang ating dakilang pinuno ay wala na | Ang aking lolo ay nabuhay hanggang sa katapusan ng digmaan

Progress: 0.26
translated_text: nagkaroon ng karagdagan sa mga buwis sa ari-arian ngayong taon | naitala nila ang pagtaas ng timbang ng baka sa loob ng ilang linggo
Progress: 0.26
translated_text: Nakuha ko ang isang dumaan na kaalaman sa Chinese | Magkaroon ng pang-unawa sa internasyonal na pananalapi
Progress: 0.26
translated_text: Narating namin ang Detroit pagsapit ng tanghali | Umabot ang tubig sa pintuan | Halos hindi na kami nakarating sa finish line | Kailangan kong pindutin ang MAC machine bago magsimula ang katapusan ng linggo
Progress: 0.26
translated_text: Ang koponan ng tahanan ay nakakakuha ng lupa | Matapos talunin ang Knicks, naunahan ng Blazers ang Lakers sa laban para sa numero unong playoff berth sa Western Conference
Progress: 0.26
translated_text: ang kilusang pangkapayapaan ay nakakuha ng momentum | ang kotse ay nagtitipon ng bilis
Progress: 0.26
translated_text: Magkano ang kinikita mo sa isang buwan sa iyong bagong trabaho? | Malaki ang kinikita niya sa bago niyang trabaho | ang pagsasanib na ito ay nagdala ng maraming pera | Kinukuha niya ang $5,000 bawat buwan
Progress: 0.26
translated_text: kanyang saklaw ng aktibidad | wala na siyang aksyon
Progress: 0.26
translated_text: ang pagkilos ng mga likas na pwersa | aktibidad ng bulkan
Progress: 0.26
translated_text: pinahina ng kamakailang aksyong pederal ang posisyon ng segregationist | ang United Nations ay dapat magkaroon ng kapangyarihan na magmungkahi at mag-organisa ng aksyon nang hindi naliligalig ng mga walang kaugnayang isyu | ang aksyon ng Unyon ng pagpapalaya sa mga alipin sa Timog
Progress: 0.26
translated_text: ang aksyon ay wala na sa mga stock ng teknolohiya kundi sa mga munisipal na bono | laging sinusubukan ng mga gawker na maging malapit sa aksyon hangga&#39;t maaari
Progress: 0.26
translated_text: Binalaan siya na ipoproseso siya ng district attorney | Inaksyunan niya ang kumpanya para sa diskriminasyon
Progress: 0.26
translated_text: magsagawa ng isang gawain | isagawa ang desisyon ng mga tao | Inaksyunan niya ang operasyon
Progress: 0.26
translated_text: gumawa ng gulo sa opisina ng isang tao | lumikha ng galit
Progress: 0.26
translated_text: Ang kumpanya ay nilikha 25 taon na ang nakakaraan | Gumawa siya ng bagong kilusan sa pagpipinta
Progress: 0.26
translated_text: gumawa ng tula | Gumawa si Schoenberg ng labindalawang tono na musika | Nilikha ni Picasso ang Cubism | Gumawa ng mga talata si Auden
Progress: 0.26
translated_text: Gumagawa kami ng higit pang mga kotse kaysa sa maaari naming ibenta | Ang kumpanya ay gumagawa ng mga laruan sa loob ng dalawang siglo
Progress: 0.26
translated_text: Ipagluto mo ako ng hapunan, pakiusap | pwede mo ba akong gawan ng omelette? | pakiayos ng almusal para sa mga bisita
Progress: 0.26
translated_text: I-fudge ang mga figure | magluto ng mga aklat | huwad ang data
Progress: 0.26
translated_text: Ang kanyang kumpanya ay bumuo ng isang bagong uri ng materyales sa gusali na lumalaban sa lahat ng uri ng panahon | Gumawa sila ng bagong pamamaraan
Progress: 0.26
translated_text: Nakuha ko ang isang malakas na pag-ayaw sa telebisyon | Ang mga bata ay dapat bumuo ng isang pakiramdam ng tama at mali | Nakabuo si Dave ng mga katangian ng pamumuno sa kanyang bagong posisyon | bumuo ng isang hilig para sa pagpipinta
Progress: 0.26
translated_text: Nagpatubo siya ng balbas | Ang pasyente ay nagkaroon ng pananakit ng tiyan | Nagkaroon ako ng mga nakakatawang spot sa buong katawan ko | Mahusay na nabuo na mga suso
Progress: 0.26
translated_text: Isang bagong relihiyosong kilusan ang nagmula sa bansang iyon | isang pag-ibig na umusbong sa pagkakaibigan | ang ideya para sa aklat ay nagmula sa isang maikling kuwento | Isang kawili-wiling kababalaghan ang bumangon
Progress: 0.26
translated_text: bumuo ng lupain | Pinaunlad ng bansa ang likas na yaman | Unti-unting naitayo ang mga malalayong lugar sa bansa
Progress: 0.26
translated_text: Sinasanay ng matandang master ang mga world-class na biyolinista | binuo natin ang mga pinuno para sa hinaharap
Progress: 0.26
translated_text: Isang bulaklak ang nabuo sa sanga | Ang bansa ay naging isang makapangyarihang superpower | Ang embryo ay bubuo sa isang fetus | Ang sitwasyong ito ay umunlad sa mahabang panahon
Progress: 0.26
translated_text: Maraming bansa sa Asya ang umuunlad na ngayon sa napakabilis na bilis | Mabilis na nagmoderno ang Vietnam
Progress: 0.26
translated_text: Ang perpektong klima dito ay nagpapaunlad ng butil | Gumawa siya ng bagong uri ng mansanas
Progress: 0.26
translated_text: Dapat tayong bumuo ng mas maraming potensyal na customer | bumuo ng isang merkado para sa bagong mobile phone
Progress: 0.26
translated_text: Ang bata ay nabuo nang maganda sa kanyang bagong kindergarten | Nang gumugol siya ng tag-araw sa kampo, ang batang lalaki ay kapansin-pansing lumaki at hindi na nagpakita ng ilan sa kanyang lumang pag-uugali ng kabataan
Progress: 0.26
translated_text: Iulat ang balita habang ito ay nabuo | Ang mga kilusang pampulitika na ito ay umuurong paminsan-minsan
Progress: 0.26
translated_text: may bagong tatak ng bayani sa mga pelikula ngayon | anong make of car yan?
Progress: 0.26
translated_text: magmahalan, hindi digmaan | magsikap | magsaliksik | walang gawin | gumawa ng rebolusyon
Progress: 0.26
translated_text: magalit sa isang tao | Ginawa niya kaming tanga | Nagpakatanga siya sa pulong | Huwag itong gawing big deal | Ang imbensyon na ito ay gagawin kang milyonaryo | Linawin mo ang sarili mo
Progress: 0.26
translated_text: gumawa ng gulo sa opisina ng isang tao | lumikha ng galit
Progress: 0.26
translated_text: Ang mga ad ay nag-udyok sa akin na bumili ng VCR | Sa wakas nakuha ako ng aking mga anak na bumili ng computer | Pinabili ako ng asawa ko ng bagong sofa
Progress: 0.26
translated_text: magdulot ng kaguluhan | gumawa ng paghalo | magdulot ng aksidente
Progress: 0.26
translated_text: Gumagawa kami ng higit pang mga kotse kaysa sa maaari naming ibenta | Ang kumpanya ay gumagawa ng mga laruan sa loob ng dalawang siglo
Progress: 0.26
translated_text: Gumuhit ako ng linya dito | gumawa ng konklusyon | gumuhit ng mga parallel | gumawa ng pagtatantya | Ano ang masasabi mo sa kanyang mga pahayag?
Progress: 0.26
translated_text: Hindi maaaring pagsamahin ang mga tao sa pamamagitan lamang ng pagpasa ng batas! | Pinapawisan ka ng init
Progress: 0.26
translated_text: gumawa ng tula | Gumawa si Schoenberg ng labindalawang tono na musika | Nilikha ni Picasso ang Cubism | Gumawa ng mga talata si Auden
Progress: 0.26
translated_text: Magkano ang kinikita mo sa isang buwan sa iyong bagong trabaho? | Malaki ang kinikita niya sa bago niyang trabaho | ang pagsasanib na ito ay nagdala ng maraming pera | Kinukuha niya ang $5,000 bawat buwan
Progress: 0.27
translated_text: Gawin ang aking silid sa asul | Ginawa ko ang pirasong ito sa kahoy upang ipahayag ang aking pagmamahal sa kagubatan
Progress: 0.27
translated_text: Binubuo ng pader na ito ang background ng setting ng entablado | Ang mga sanga ay ginawang bubong | Ito ay gumagawa ng isang magandang pagpapakilala
Progress: 0.27
translated_text: gawin ang unang koponan | Ginawa namin ito! | Baka hindi siya makakuha ng grade
Progress: 0.27
translated_text: Gumagawa siya ng isang mahusay na host | Gagawa siya ng mabuting ama
Progress: 0.27
translated_text: gumawa ng damit | gumawa ng cake | gumawa ng pader ng mga bato
Progress: 0.27
translated_text: gumawa ng desisyon | gumawa ng isang hakbang | gumawa ng mga advance | tumawag sa telepono
Progress: 0.27
translated_text: ginawa ng maliit na baboy na ito ang kanyang bahay sa dayami | Ang ilang sira-sira ay gumawa ng electric brassiere warmer
Progress: 0.27
translated_text: gawing alak ang tubig | gawing ginto ang tingga | gawing ladrilyo ang luwad
Progress: 0.27
translated_text: makipagkaibigan | gumawa ng mga kaaway
Progress: 0.27
translated_text: Siya ay pinangalanang Pinuno ng Komite | Ginawa siyang presidente ng club
Progress: 0.27
translated_text: Si Nicklaus ay nagkaroon ng 70 | Nakakuha ang koponan ng Brazil ng 4 na layunin | Gumawa siya ng 29 puntos sa araw na iyon
Progress: 0.27
translated_text: Narating namin ang Detroit sa tanghali | Umabot ang tubig sa pintuan | Halos hindi na kami nakarating sa finish line | Kailangan kong pindutin ang MAC machine bago magsimula ang katapusan ng linggo

Progress: 0.27
translated_text: magkamali | gumawa ng faux-pas
Progress: 0.27
translated_text: magdaos ng reception | magkaroon, magtapon, o gumawa ng isang party | magbigay ng kurso
Progress: 0.27
translated_text: ayusin ang kama | gumawa ng kwarto
Progress: 0.27
translated_text: Ang nakatakas na bilanggo ay dinala sa mga burol | Ginawa namin para sa mga bundok
Progress: 0.27
translated_text: Nagsalita siya ngunit wala siyang sinabi sa huli | Parang kinakamusta niya kami
Progress: 0.27
translated_text: gumawa ng paraan sa pamamagitan ng karamihan ng tao | gumawa ng paraan sa kagubatan
Progress: 0.27
translated_text: Ipagluto mo ako ng hapunan, pakiusap | pwede mo ba akong gawan ng omelette? | pakiayos ng almusal para sa mga bisita
Progress: 0.27
translated_text: Sa wakas ay naakit ni Harry si Sally | Naka-score ka ba kagabi? | Ginawa ni Harry si Sally
Progress: 0.27
translated_text: nagsikap na masakop ang lahat ng babasahin | wished him luck sa kanyang pagsusumikap | sinubukan niya itong mabuti
Progress: 0.27
translated_text: nakakuha siya ng A para sa pagsisikap | sila ay pinamamahalaan lamang sa matinding pagsusumikap
Progress: 0.27
translated_text: gumawa siya ng isang mahusay na gawa | ang libro ay ang kanyang pinakamahusay na pagsisikap
Progress: 0.27
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.27
translated_text: isang tupi sa napkin | isang tupi sa kanyang pantalon | isang plication sa kanyang blouse | isang pagbaluktot ng colon | isang baluktot ng kanyang siko
Progress: 0.27
translated_text: tiklupin ang pahayagan | itaas mo ang iyong kwelyo
Progress: 0.27
translated_text: Nagpasya ang mga may-ari na lumipat at isara ang pabrika | Nagsasara ang negosyo ko tuwing 8 PM | isara ang tindahan
Progress: 0.27
translated_text: ang reflex motion ng kanyang kilay ay nagpakita ng kanyang pagkagulat | ang paggalaw ay tanda ng buhay | isang naiinip na galaw ng kanyang kamay | gastrointestinal motility
Progress: 0.27
translated_text: gumawa siya ng motion to adjourn | tawag niya para sa tanong
Progress: 0.27
translated_text: kontrolado ng pulis ang galaw ng karamihan | ang paggalaw ng mga tao mula sa mga sakahan patungo sa mga lungsod | dire-diretso siya sa daraanan ko ng galaw niya
Progress: 0.27
translated_text: umaasa ang sinehan sa maliwanag na galaw | ang sunud-sunod na kumikislap na mga ilaw ay nagbigay ng ilusyon ng paggalaw
Progress: 0.27
translated_text: ang sitwasyon ay nanawagan para sa matibay na hakbang | gumawa ng hakbang ang pulisya para mabawasan ang krimen
Progress: 0.27
translated_text: palaging isang hakbang sa likod | banayad na gradations sa kulay | manatiling nakasabay sa mga moda
Progress: 0.27
translated_text: Para sa mga hangal ay sumugod kung saan ang mga anghel ay natatakot na tapakan | tumapak sa preno
Progress: 0.27
translated_text: Inaabuso ng amo na ito ang kanyang mga manggagawa | Lagi siyang natatapakan ng iba para mauna
Progress: 0.27
translated_text: Siya ay tumuntong sa isang buhay na marangyang | hindi siya tutungo sa yapak ng kanyang ama
Progress: 0.27
translated_text: binigyan niya ng malakas na tulak ang pinto | magandang ehersisyo ang pagtulak
Progress: 0.27
translated_text: ang pagtulak ng tubig sa mga dingding ng tangke | ang tulak ng mga jet engine
Progress: 0.27
translated_text: ang elevator ay pinaandar ng mga push button | ang pagtulak sa tabi ng kama ay nagpaandar ng buzzer sa desk
Progress: 0.27
translated_text: Ang tindero ay agresibong itinutulak ang bagong modelo ng computer | Ang kumpanya ay labis na nag-a-advertise ng kanilang mga bagong laptop
Progress: 0.27
translated_text: Nagsabunot siya ng maraming taon para magkaroon ng disenteng pamumuhay | Kailangan nating mag-push ng kaunti para ma-deadline! | Siya ay nagtutulak sa kanyang tesis ng doktor
Progress: 0.27
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Ang Dean ay nagtutulak para sa kanyang paboritong kandidato
Progress: 0.27
translated_text: Maglakad, huwag tumakbo! | Naglakad kami sa halip na magmaneho | Naglalakad siya na medyo nahihilo | Hindi pa makalakad ang pasyente | Pumunta sa cabinet
Progress: 0.27
translated_text: Maglakad sa mahigpit na lubid | Nilakad ni Paul ang mga lansangan ng Damascus | Naglalakad siya ng 3 milya araw-araw
Progress: 0.27
translated_text: Dapat tayong lumakad kasama ang ating mga kapatid na inalisan | Maglakad kasama ng Diyos
Progress: 0.27
translated_text: Inilalakad niya ang kabayo sa bundok | Maglakad sa aso dalawang beses sa isang araw
Progress: 0.27
translated_text: Magkahawak kamay ang magkasintahan habang naglalakad | Gusto naming maglakad tuwing Linggo
Progress: 0.27
translated_text: ang reflex motion ng kanyang kilay ay nagpakita ng kanyang pagkagulat | ang paggalaw ay tanda ng buhay | isang naiinip na galaw ng kanyang kamay | gastrointestinal motility
Progress: 0.27
translated_text: gumawa siya ng motion to adjourn | tawag niya para sa tanong
Progress: 0.27
translated_text: kontrolado ng pulis ang galaw ng karamihan | ang paggalaw ng mga tao mula sa mga sakahan patungo sa mga lungsod | dire-diretso siya sa daraanan ko ng galaw niya
Progress: 0.28
translated_text: umaasa ang sinehan sa maliwanag na galaw | ang sunud-sunod na kumikislap na mga ilaw ay nagbigay ng ilusyon ng paggalaw
Progress: 0.28
translated_text: inihatid ng guwardiya ang kriminal sa pulis | ibigay ang mga bilanggo | ibigay ang bayan sa kaaway | tinidor ang pera
Progress: 0.28
translated_text: magbigay ng hatol | maghatid ng paghatol
Progress: 0.28
translated_text: maghatid ng atake | maghatid ng suntok | Ang boksingero ay nagmaneho pauwi ng isang solidong kaliwa
Progress: 0.28
translated_text: hinarap namin ang isang hukbong may malaking lakas | napabayaan ng mga pulitiko ang ating postura sa militar
Progress: 0.28
translated_text: tinamaan niya ng buong lakas na kaya niyang ibigay | nawasak ito sa lakas ng unos | ang isang pamahalaan ay walang sigla at puwersa ng isang buhay na tao
Progress: 0.28
translated_text: inayos niya ang intensity ng tunog | sinukat nila ang lakas ng signal ng istasyon
Progress: 0.28
translated_text: ang lakas ng lason | ang lakas ng drinks
Progress: 0.28
translated_text: Maglakad, huwag tumakbo! | Naglakad kami sa halip na magmaneho | Naglalakad siya na medyo nahihilo | Hindi pa makalakad ang pasyente | Pumunta sa cabinet
Progress: 0.28
translated_text: Maglakad sa mahigpit na lubid | Nilakad ni Paul ang mga lansangan ng Damascus | Naglalakad siya ng 3 milya araw-araw
Progress: 0.28
translated_text: Dapat tayong lumakad kasama ang ating mga kapatid na inalisan | Maglakad kasama ng Diyos
Progress: 0.28
translated_text: Inilalakad niya ang kabayo sa bundok | Maglakad sa aso dalawang beses sa isang araw
Progress: 0.28
translated_text: Magkahawak kamay ang magkasintahan habang naglalakad | Gusto naming maglakad tuwing Linggo
Progress: 0.28
translated_text: Ang kalaban ay umatras | Umalis ang limo mula sa gilid ng bangketa
Progress: 0.28
translated_text: Kakailanganin nating umalis mula sa pakikipagkita sa kanya | Umatras siya sa dati niyang pangako | Ang agresibong kumpanya ng pamumuhunan ay humila sa mga sungay nito
Progress: 0.28
translated_text: nakapuntos ang Yankees ng 3 run sa ibaba ng 9th | ang kanilang unang tally ay dumating sa 3rd inning
Progress: 0.28
translated_text: sa mga eksperimentong pagsubok ang dami ng carbon ay hiwalay na sinusukat | tinawag niyang bagong pagsubok ang bawat pitik ng barya
Progress: 0.28
translated_text: nagkaroon ng bahid ng malas | Si Nicklaus ay nagkaroon ng run of birdies
Progress: 0.28
translated_text: ang defensive line braced para ihinto ang pagtakbo | ang coach ay nagbigay ng malaking diin sa pagtakbo
Progress: 0.28
translated_text: napatakbo siya | ang kanyang pang-araw-araw na pagtakbo ay nagpapanatili sa kanya ng fit
Progress: 0.28
translated_text: Pinamahalaan ko ang kanyang kampanya para sa gobernador | nakalikom siya ng pera para sa pagtakbo sa Senado

Progress: 0.28
translated_text: matagal nang tumakbo ang dula sa Broadway | ang koponan ay nasiyahan sa isang maikling run ng mga tagumpay
Progress: 0.28
translated_text: Huwag kang tatakbo--malagutan ka ng hininga | Nagtakbuhan ang mga bata sa tindahan
Progress: 0.28
translated_text: Kung nakita mo ang lalaking ito, tumakbo ka! | Nakatakas ang mga magnanakaw bago dumating ang mga pulis
Progress: 0.28
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.28
translated_text: ang kuwento o argumento ay tumatakbo bilang mga sumusunod | sabi nga sa kasabihan...
Progress: 0.28
translated_text: Umagos ang tubig sa kweba | ang Missouri ay nagpapakain sa Mississippi
Progress: 0.28
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.28
translated_text: Mga pagtatantya para sa mga pagkalugi sa saklaw ng lindol na kasing taas ng $2 bilyon | Ang mga rate ng interes ay tumatakbo mula 5 hanggang 10 porsyento | Ang mga instrumento ay mula sa tuba hanggang sa mga simbalo | Ang aking mga mag-aaral ay mula sa napakaliwanag hanggang sa mapurol
Progress: 0.28
translated_text: Paulit-ulit nilang pinaandar ang mga tape | Tutugtog kita ng paborito kong record | Hindi siya nagsasawang i-play ang video na iyon
Progress: 0.28
translated_text: sino itong mga taong tumatakbo sa gusali? | Tumatakbo siya sa paligid na nagsasabi sa lahat ng kanyang mga problema | palayain ang mga aso
Progress: 0.28
translated_text: Siya ay madalas na kinakabahan bago ang kanyang mga lektura | Ang mga damit na ito ay tumatakbo nang maliit | Siya ay hilig sa katabaan
Progress: 0.28
translated_text: mag-amok | tumakbong buhong | magpatakbo ng kaguluhan
Progress: 0.28
translated_text: magpatakbo ng isang paksa | magpatakbo ng isang proseso
Progress: 0.28
translated_text: magpatakbo ng temperatura | makipagsapalaran
Progress: 0.28
translated_text: Ang mga kwentong ito ay die hard | Ang alamat ni Elvis ay nagtitiis
Progress: 0.28
translated_text: Patakbuhin ang makinang panghugas | magpatakbo ng bagong program sa Mac | ang computer ay nagsagawa ng pagtuturo
Progress: 0.28
translated_text: Tatlong beses naming pinatakbo ang ad | Ang papel na ito ay nagdadala ng pagsusuri sa restawran | Lahat ng malalaking network ay nagsagawa ng press conference
Progress: 0.28
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang mga daliri niya
Progress: 0.28
translated_text: Tumakbo sa tindahan! | Palagi siyang tumatakbo sa Italy, dahil may manliligaw siya doon
Progress: 0.28
translated_text: Madalas manghuli si Goering ng mga baboy-ramo sa Poland | Ang mga aso ay tumatakbo sa usa | Nangangaso ang Duke sa kagubatan na ito
Progress: 0.28
translated_text: siya ay tumatakbo sa Marathon sa taong ito | magkarera tayo at tingnan kung sino ang unang makarating doon
Progress: 0.28
translated_text: Ang talumpati ay kailangang dumaan sa ilang higit pang mga draft | patakbuhin ang iyong presentasyon bago ang pulong
Progress: 0.28
translated_text: tunawin ang mantikilya | tunawin ang ginto | Ang wax ay natunaw sa araw
Progress: 0.28
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.28
translated_text: magmaneho ng kotse o bus | Kaya mo bang magmaneho nitong four-wheel truck?
Progress: 0.28
translated_text: Nagmamaneho kami sa unibersidad tuwing umaga | Nagmotor sila papuntang London para sa teatro
Progress: 0.28
translated_text: Hinahatid niya ako sa paaralan araw-araw | Pinaandar namin ang sasakyan papunta sa garahe
Progress: 0.28
translated_text: Siya rammed kanyang isip sa focus | Ginagalit niya ako
Progress: 0.28
translated_text: itaboy ang kaaway | itulak ang pagnanasang manigarilyo | talunin ang mga mananakop
Progress: 0.29
translated_text: Nagsabunot siya ng maraming taon para magkaroon ng disenteng pamumuhay | Kailangan nating mag-push ng kaunti para ma-deadline! | Siya ay nagtutulak sa kanyang tesis ng doktor
Progress: 0.29
translated_text: Ang kotseng ito ay tumatakbo nang maayos | Maayos ang pagmamaneho ng bago kong trak
Progress: 0.29
translated_text: Nagmamaneho siya ng bread truck | Nagmamaneho siya para sa kumpanya ng taxi sa Newark
Progress: 0.29
translated_text: Ang amplifier ang nagtutulak sa tubo | pinapatakbo ng singaw ang mga makina | ang device na ito ay nagtutulak ng mga disk para sa computer
Progress: 0.29
translated_text: nilakad nila ang mga lansangan ng maliit na bayan | nakatira siya sa Nassau Street
Progress: 0.29
translated_text: nagtrabaho siya sa magkabilang panig ng kalye | ang kooperasyon ay isang dalawang-daan na kalye
Progress: 0.29
translated_text: ang kanyang marangal na ugali | ang kanyang mabilis na paraan ng pagsasalita | kanilang nomadic mode of existence | sa katangiang istilo ng New York | isang malungkot na paraan ng pamumuhay | sa isang nakasasakit na paraan
Progress: 0.29
translated_text: isang paraan ng kontrol | isang halimbawa ay ang pinakamahusay na ahensya ng pagtuturo | ang tunay na daan tungo sa tagumpay
Progress: 0.29
translated_text: tumingin siya sa ibang direksyon | hindi alam ang daan pauwi
Progress: 0.29
translated_text: ganyan talaga | Ganun din ang naramdaman ko
Progress: 0.29
translated_text: ang landas ng kabutihan | pumunta kami sa magkahiwalay na daan | ang mga landas natin sa buhay ang naghiwalay sa atin | ang henyo ay karaniwang sumusunod sa isang rebolusyonaryong landas
Progress: 0.29
translated_text: silid na dadaanan | gumawa ng paraan para sa | halos hindi sapat na silid ng siko upang lumiko
Progress: 0.29
translated_text: ito ay isang mahabang paraan sa Moscow | malayo-layo ang kanyang narating
Progress: 0.29
translated_text: over budget | malayo sa base | ang kabilang bahagi ng burol ay tama matalinong mas matarik kaysa sa gilid na aming kinaroroonan
Progress: 0.29
translated_text: magmaneho ng kotse o bus | Kaya mo bang magmaneho nitong four-wheel truck?
Progress: 0.29
translated_text: Nagmamaneho kami sa unibersidad tuwing umaga | Nagmotor sila papuntang London para sa teatro
Progress: 0.29
translated_text: Hinahatid niya ako sa paaralan araw-araw | Pinaandar namin ang sasakyan papunta sa garahe
Progress: 0.29
translated_text: Siya rammed kanyang isip sa focus | Ginagalit niya ako
Progress: 0.29
translated_text: itaboy ang kaaway | itulak ang pagnanasang manigarilyo | talunin ang mga mananakop
Progress: 0.29
translated_text: Nagsabunot siya ng maraming taon para magkaroon ng disenteng pamumuhay | Kailangan nating mag-push ng kaunti para ma-deadline! | Siya ay nagtutulak sa kanyang tesis ng doktor
Progress: 0.29
translated_text: Ang kotseng ito ay tumatakbo nang maayos | Maayos ang pagmamaneho ng bago kong trak
Progress: 0.29
translated_text: Nagmamaneho siya ng trak ng tinapay | Nagmamaneho siya para sa kumpanya ng taxi sa Newark
Progress: 0.29
translated_text: Ang amplifier ang nagtutulak sa tubo | pinapatakbo ng singaw ang mga makina | ang device na ito ay nagtutulak ng mga disk para sa computer
Progress: 0.29
translated_text: isang nagmamaneho ng personal na ambisyon | ang puwersang nagtutulak ay ang kanyang likas na sigasig | isang impulsive force
Progress: 0.29
translated_text: Nanalo si Grant ng isang mapagpasyang tagumpay sa labanan ng Chickamauga | nawala ang kanyang mga romantikong ideya tungkol sa digmaan nang pumasok siya sa isang tunay na pakikipag-ugnayan
Progress: 0.29
translated_text: sumiklab ang away sa hockey game | nagkaroon ng labanan sa mga lansangan | ang malungkot na mag-asawa ay napunta sa isang kakila-kilabot na scrap
Progress: 0.29
translated_text: nag-away ang mga tribo | Palaging nag-aaway ang magkapatid | Ang mga militanteng grupo ay nakikipaglaban para sa kontrol ng bansa

Progress: 0.29
translated_text: Sinabi ng senador na tututulan niya ang panukalang batas | Huwag mo itong labanan!
Progress: 0.29
translated_text: Siya struggled para sa taon upang mabuhay nang walang kapakanan | Napabuntong hininga siya
Progress: 0.29
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Itinutulak ng Dean ang kanyang paboritong kandidato
Progress: 0.29
translated_text: ang reflex motion ng kanyang kilay ay nagpakita ng kanyang pagkagulat | ang paggalaw ay tanda ng buhay | isang naiinip na galaw ng kanyang kamay | gastrointestinal motility
Progress: 0.29
translated_text: kontrolado ng pulis ang galaw ng karamihan | ang paggalaw ng mga tao mula sa mga sakahan patungo sa mga lungsod | dire-diretso siya sa daraanan ko ng galaw niya
Progress: 0.29
translated_text: isa siyang charter member ng kilusan | kailangang igalang ng mga pulitiko ang isang kilusang masa | pinamunuan niya ang pambansang harapan ng pagpapalaya
Progress: 0.29
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.29
translated_text: umaasa ang sinehan sa maliwanag na galaw | ang sunud-sunod na kumikislap na mga ilaw ay nagbigay ng ilusyon ng paggalaw
Progress: 0.29
translated_text: hindi lantarang liberal pero yan ang uso ng libro | isang malawak na paggalaw ng mga manghahalal sa kanan
Progress: 0.29
translated_text: Pinamahalaan ko ang kanyang kampanya para sa gobernador | nakalikom siya ng pera para sa pagtakbo sa Senado
Progress: 0.29
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.29
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Ang Dean ay nagtutulak para sa kanyang paboritong kandidato
Progress: 0.29
translated_text: nakapuntos ang Yankees ng 3 run sa ibaba ng 9th | ang kanilang unang tally ay dumating sa 3rd inning
Progress: 0.29
translated_text: sa mga eksperimentong pagsubok ang dami ng carbon ay hiwalay na sinusukat | tinawag niyang bagong pagsubok ang bawat pitik ng barya
Progress: 0.29
translated_text: nagkaroon ng bahid ng malas | Si Nicklaus ay nagkaroon ng run of birdies
Progress: 0.29
translated_text: ang defensive line braced para ihinto ang pagtakbo | ang coach ay nagbigay ng malaking diin sa pagtakbo
Progress: 0.29
translated_text: sumabog siya sa pagtakbo | ang kanyang pang-araw-araw na pagtakbo ay nagpapanatili sa kanya ng fit
Progress: 0.29
translated_text: Pinamahalaan ko ang kanyang kampanya para sa gobernador | nakalikom siya ng pera para sa pagtakbo sa Senado
Progress: 0.29
translated_text: ang dula ay matagal nang tumakbo sa Broadway | ang koponan ay nasiyahan sa isang maikling run ng mga tagumpay
Progress: 0.29
translated_text: Huwag kang tatakbo--malagutan ka ng hininga | Nagtakbuhan ang mga bata sa tindahan
Progress: 0.29
translated_text: Kung nakita mo ang lalaking ito, tumakbo ka! | Nakatakas ang mga magnanakaw bago dumating ang mga pulis
Progress: 0.29
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.29
translated_text: ang kuwento o argumento ay tumatakbo bilang mga sumusunod | sabi nga sa kasabihan...
Progress: 0.30
translated_text: Umagos ang tubig sa kweba | ang Missouri ay nagpapakain sa Mississippi
Progress: 0.30
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.30
translated_text: Mga pagtatantya para sa mga pagkalugi sa saklaw ng lindol na kasing taas ng $2 bilyon | Ang mga rate ng interes ay tumatakbo mula 5 hanggang 10 porsyento | Ang mga instrumento ay mula sa tuba hanggang sa mga simbalo | Ang aking mga mag-aaral ay mula sa napakaliwanag hanggang sa mapurol
Progress: 0.30
translated_text: Paulit-ulit nilang pinaandar ang mga tape | Tutugtog kita ng paborito kong record | Hindi siya nagsasawang i-play ang video na iyon
Progress: 0.30
translated_text: sino itong mga taong tumatakbo sa gusali? | Tumatakbo siya sa paligid na nagsasabi sa lahat ng kanyang mga problema | palayain ang mga aso
Progress: 0.30
translated_text: Siya ay madalas na kinakabahan bago ang kanyang mga lektura | Ang mga damit na ito ay tumatakbo nang maliit | Siya ay hilig sa katabaan
Progress: 0.30
translated_text: mag-amok | tumakbong buhong | magpatakbo ng kaguluhan
Progress: 0.30
translated_text: magpatakbo ng isang paksa | magpatakbo ng isang proseso
Progress: 0.30
translated_text: magpatakbo ng temperatura | makipagsapalaran
Progress: 0.30
translated_text: Ang mga kwentong ito ay die hard | Ang alamat ni Elvis ay nagtitiis
Progress: 0.30
translated_text: Patakbuhin ang makinang panghugas | magpatakbo ng bagong program sa Mac | ang computer ay nagsagawa ng pagtuturo
Progress: 0.30
translated_text: Tatlong beses naming pinatakbo ang ad | Ang papel na ito ay nagdadala ng pagsusuri sa restawran | Lahat ng malalaking network ay nagsagawa ng press conference
Progress: 0.30
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.30
translated_text: Tumakbo sa tindahan! | Palagi siyang tumatakbo sa Italy, dahil may manliligaw siya doon
Progress: 0.30
translated_text: Madalas manghuli si Goering ng mga baboy-ramo sa Poland | Ang mga aso ay tumatakbo sa usa | Nangangaso ang Duke sa kagubatan na ito
Progress: 0.30
translated_text: siya ay tumatakbo sa Marathon sa taong ito | karera tayo at tingnan kung sino ang unang makarating doon
Progress: 0.30
translated_text: Ang talumpati ay kailangang dumaan sa ilang higit pang mga draft | patakbuhin ang iyong presentasyon bago ang pulong
Progress: 0.30
translated_text: tunawin ang mantikilya | tunawin ang ginto | Ang wax ay natunaw sa araw
Progress: 0.30
translated_text: Pinamahalaan ko ang kanyang kampanya para sa gobernador | nakalikom siya ng pera para sa pagtakbo sa Senado
Progress: 0.30
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.30
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Ang Dean ay nagtutulak para sa kanyang paboritong kandidato
Progress: 0.30
translated_text: Napagdesisyunan ang kaso | Ang hukom ay nagpasya sa kaso pabor sa nagsasakdal | Ang ama ay humatol nang ang mga anak na lalaki ay nag-aaway tungkol sa kanilang mana
Progress: 0.30
translated_text: ang pasanin ng desisyon ay kanyang | mabilis siyang nakagawa ng konklusyon
Progress: 0.30
translated_text: isang desisyon na hindi pabor sa oposisyon | isinaalang-alang ng kanyang konklusyon ang ebidensya | nasiyahan sa pagpapasiya ng panel
Progress: 0.30
translated_text: Isara ang pinto | isara ang bintana
Progress: 0.30
translated_text: Nagpasya ang mga may-ari na lumipat at isara ang pabrika | Nagsasara ang negosyo ko tuwing 8 PM | isara ang tindahan
Progress: 0.30
translated_text: Nagsara kami sa bahay noong Biyernes | Isinara nila ang deal sa gusali
Progress: 0.30
translated_text: Ang stock market ay nagsara ng mataas nitong Biyernes | Ang aking mga bagong stock ay nagsara sa $59 kagabi
Progress: 0.30
translated_text: isara ang circuit | magsara ng sugat | isara ang isang libro | isara ang isang payong
Progress: 0.30
translated_text: ang mga pangwakas na yugto ng halalan | ang mga huling linggo ng taon | ang pangwakas na eksena ng pelikula | pangwakas na pananalita

Progress: 0.30
translated_text: dulo ng pier | binuhol niya ang dulo ng thread | sumakay sila hanggang sa dulo ng linya | ang mga terminal ng anterior arches ng fornix
Progress: 0.30
translated_text: katapusan ng taon | ang pagtatapos ng panahon ng warranty
Progress: 0.30
translated_text: kapana-panabik ang wakas | Kinailangan kong ma-miss ang huling bahagi ng pelikula
Progress: 0.30
translated_text: ibinigay namin ito sa dulo ng seksyon dahil kinasasangkutan nito ang calculus | Magsimula sa simula at magpatuloy hanggang sa makarating ka sa dulo
Progress: 0.30
translated_text: siya ay dumating sa isang masamang wakas | ang tinatawag na maluwalhating eksperimento ay dumating sa isang nakakahiya na wakas
Progress: 0.30
translated_text: tumunog ang telepono sa kabilang dulo | magkasabay na isinulat ang magkabilang dulo
Progress: 0.30
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.30
translated_text: Tinapos niya ang kanilang pagkakaibigan nang malaman niyang minsan na itong nahatulan ng isang krimen | Ang pag-atake sa Poland ay nagwakas sa medyo mapayapang panahon pagkatapos ng WW I
Progress: 0.30
translated_text: ang stopping point ng bawat round ay sinenyasan ng bell | ang merkado ay hanggang sa matapos | mas mahusay silang naglalaro sa pagtatapos ng season
Progress: 0.30
translated_text: Isara ang pinto | isara ang bintana
Progress: 0.30
translated_text: Nagpasya ang mga may-ari na lumipat at isara ang pabrika | Nagsasara ang negosyo ko tuwing 8 PM | isara ang tindahan
Progress: 0.30
translated_text: Nagsara kami sa bahay noong Biyernes | Isinara nila ang deal sa gusali
Progress: 0.30
translated_text: Ang stock market ay nagsara ng mataas nitong Biyernes | Nagsara ang aking mga bagong stock sa $59 kagabi
Progress: 0.30
translated_text: isara ang circuit | magsara ng sugat | isara ang isang libro | isara ang isang payong
Progress: 0.30
translated_text: malapit na magtanghali | gaano tayo kalapit sa bayan? | isang malapit na pagbuo ng mga barko
Progress: 0.30
translated_text: isang malapit na pamilya | tayong lahat...sa malapit na pakikiramay kay... | malapit na kamag-anak | isang malapit na pagkakahawig
Progress: 0.30
translated_text: malapit sa mga kapitbahay | sa malapit na hinaharap | sila ay malapit sa katumbas | ang kanyang pinakamalapit na diskarte sa tagumpay | isang napakalapit na bagay | isang malapit na tamaan ng bomba | siya ay malapit sa luha | siya ay malapit sa luha | nagkaroon ng malapit na tawag
Progress: 0.30
translated_text: malapit na pangangasiwa | binigyang pansin | isang malapit na pag-aaral | nanatiling mahigpit na pagbabantay sa mga paggasta
Progress: 0.30
translated_text: isang malapit na pagsasalin | isang tapat na kopya ng larawan | isang matapat na paglalahad ng mga naobserbahang katotohanan
Progress: 0.30
translated_text: isang malapit na paligsahan | isang malapit na halalan | isang mahigpit na laro
Progress: 0.30
translated_text: isang maalikabok na walang hangin na attic | ang kakila-kilabot na malapit na kapaligiran | mainit at masikip at ang hangin ay asul na may usok
Progress: 0.31
translated_text: isang malapit na habi | makinis na percale na may napakahigpit na paghabi
Progress: 0.31
translated_text: aming cheeseparing administration | napakalapit (o malapit) sa kanyang pera | isang peni-pinching kuripot matanda
Progress: 0.31
translated_text: habang papalapit ang araw ng kasal | nakatayo malapit sa pinto | huwag barilin hangga&#39;t hindi sila lumalapit | papalapit sa totoong paliwanag | laging malapit ang kanyang ina | Malapit na ang wakas | hindi nakalapit ang bala | huwag masyadong lumapit sa apoy
Progress: 0.31
translated_text: ang bangka ay may metal na tapusin | nag-apply siya ng coat of a clear finish | kapag masyadong manipis ang finish mahirap ilapat ng pantay
Progress: 0.31
translated_text: ang stopping point ng bawat round ay sinenyasan ng bell | ang merkado ay hanggang sa matapos | mas mahusay silang naglalaro sa pagtatapos ng season
Progress: 0.31
translated_text: sila ay gumanap na may mahusay na polish | Hinangaan ko ang katangi-tanging pagpipino ng kanyang prosa | halos isang inspirasyon na nagbibigay sa lahat ng gawain ng pagtatapos na halos sining
Progress: 0.31
translated_text: isang pulutong ang nagtipon sa pagtatapos | halos mapagod siya nang makita ang kanilang destinasyon
Progress: 0.31
translated_text: tumindi ang pananabik nang malapit nang matapos | ang aking kabayo ay ilang haba sa likod sa tapusin | ang nagwagi ay ang pangkat na may pinakamaraming puntos sa pagtatapos
Progress: 0.31
translated_text: alak ang magiging katapusan niya | ito ay isang labanan hanggang sa matapos
Progress: 0.31
translated_text: ang kanyang kamatayan ay minarkahan ang pagtatapos ng isang panahon | kapag na-broadcast ang mga huling yugto na ito, ito na ang magiging pagtatapos ng palabas
Progress: 0.31
translated_text: ang kanyang pinakamahusay na pagtatapos sa isang pangunahing paligsahan ay pangatlo | ang pagtatapos ng tagapagsalita ay sinalubong ng palakpakan
Progress: 0.31
translated_text: Tinapos niya ang mga pinggan | Nakumpleto niya ang mga kinakailangan para sa kanyang Master&#39;s Degree | Tinapos ng pinakamabilis na mananakbo ang karera sa loob lamang ng 2 oras; ang iba ay natapos sa loob ng mahigit 4 na oras
Progress: 0.31
translated_text: He ended up marrying his high school sweetheart | nawalan siya ng trabaho at muling naninirahan sa bahay
Progress: 0.31
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.31
translated_text: Ang karpintero ay natapos nang maganda ang mesa | hindi natapos ng maayos ang shirt na ito
Progress: 0.31
translated_text: dulo ng pier | binuhol niya ang dulo ng thread | sumakay sila hanggang sa dulo ng linya | ang mga terminal ng anterior arches ng fornix
Progress: 0.31
translated_text: katapusan ng taon | ang pagtatapos ng panahon ng warranty
Progress: 0.31
translated_text: ang wakas ay kapana-panabik | Kinailangan kong makaligtaan ang huling bahagi ng pelikula
Progress: 0.31
translated_text: ibinigay namin ito sa dulo ng seksyon dahil kinasasangkutan nito ang calculus | Magsimula sa simula at magpatuloy hanggang sa makarating ka sa dulo
Progress: 0.31
translated_text: siya ay dumating sa isang masamang wakas | ang tinatawag na maluwalhating eksperimento ay dumating sa isang nakakahiya na wakas
Progress: 0.31
translated_text: tumunog ang telepono sa kabilang dulo | magkasabay na isinulat ang magkabilang dulo
Progress: 0.31
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.31
translated_text: Tinapos niya ang kanilang pagkakaibigan nang malaman niyang minsan na itong nahatulan ng isang krimen | Ang pag-atake sa Poland ay nagwakas sa medyo mapayapang panahon pagkatapos ng WW I
Progress: 0.31
translated_text: Pinagdebatehan namin ang tanong ng aborsyon | Pinagdebatehan ni John si Maria
Progress: 0.31
translated_text: Isinaalang-alang nila ang posibilidad ng isang welga | Ibalik ang panukala sa iyong isipan
Progress: 0.31
translated_text: ang dahilan kung bakit idineklara ang digmaan | ang mga batayan para sa kanilang deklarasyon
Progress: 0.31
translated_text: ang kanyang katwiran ay maaaring may kapansanan | kailangan niyang umasa nang kaunti sa katwiran kaysa sa pagpukaw sa kanilang mga damdamin
Progress: 0.31
translated_text: wala siyang dahilan para magreklamo | may magandang dahilan sila para magsaya
Progress: 0.31
translated_text: pukawin ang awa | taasan ang isang ngiti | pukawin ang pakikiramay
Progress: 0.31
translated_text: Kilala siyang harry sa kanyang mga tauhan kapag siya ay sobrang trabaho | Ang lalaking ito ay hina-harass ang mga katrabaho niyang babae

Progress: 0.31
translated_text: wala siyang dahilan para magreklamo | may magandang dahilan sila para magsaya
Progress: 0.31
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.31
translated_text: magdulot ng kaguluhan | gumawa ng paghalo | magdulot ng aksidente
Progress: 0.31
translated_text: Ang mga ad ay nag-udyok sa akin na bumili ng VCR | Sa wakas nakuha ako ng aking mga anak na bumili ng computer | Pinabili ako ng asawa ko ng bagong sofa
Progress: 0.31
translated_text: ang dahilan kung bakit idineklara ang digmaan | ang mga batayan para sa kanilang deklarasyon
Progress: 0.31
translated_text: ang kanyang katwiran ay maaaring may kapansanan | kailangan niyang umasa nang kaunti sa katwiran kaysa sa pagpukaw ng kanilang mga damdamin
Progress: 0.31
translated_text: wala siyang dahilan para magreklamo | may magandang dahilan sila para magsaya
Progress: 0.31
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.31
translated_text: Itinulak ng liberal na partido ang mga reporma | Siya ay crusading para sa mga karapatan ng kababaihan | Ang Dean ay nagtutulak para sa kanyang paboritong kandidato
Progress: 0.31
translated_text: Palagi niyang inuunahan ang kanyang mga lektura na may biro | Pinauna niya ang kanyang panayam sa isang kritikal na pahayag tungkol sa institusyon
Progress: 0.31
translated_text: sila ay nasa isang magiliw na katayuan | nagtrabaho siya sa pansamantalang batayan
Progress: 0.31
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.31
translated_text: kulang siya sa pundasyong kailangan para sa advanced na pag-aaral | isang magandang saligan sa matematika
Progress: 0.31
translated_text: Inaasahan niya ang kanyang pagsisimula bilang isang may sapat na gulang | ang pundasyon ng isang bagong siyentipikong lipunan
Progress: 0.31
translated_text: nagbabasa siya upang mapabuti ang kanyang isip | siya ay may matalas na talino
Progress: 0.31
translated_text: nagkaroon sila ng kasunduan na hindi sila makikialam sa negosyo ng isa&#39;t isa | nagkaroon ng pagkakaunawaan sa pagitan ng management at ng mga manggagawa
Progress: 0.31
translated_text: ang kanyang pakikiramay ay palaging kasama ng mga underdog | Alam kong maaasahan ko ang pag-unawa niya
Progress: 0.31
translated_text: Hindi niya maintindihan ang kanyang asawa | Naiintindihan ko ang ibig niyang sabihin
Progress: 0.31
translated_text: Ngayon nakikita ko na! | Hindi ko lang makita ang iyong punto | Napagtanto ba niya kung gaano kahalaga ang desisyong ito? | Hindi ko maintindihan ang ideya
Progress: 0.31
translated_text: Naiintindihan niya ang French | Marunong ka bang magbasa ng Greek?
Progress: 0.32
translated_text: Sinabi niya na gusto niya itong pakasalan | sabihin mo sa akin kung ano ang bumabagabag sa iyo | sabihin ang iyong opinyon | isaad ang iyong pangalan
Progress: 0.32
translated_text: Biktima umano siya ng isang krimen | Sinabi niya na huli na para makialam sa digmaan | Ang sabi ng registrar ay may utang ako sa school money
Progress: 0.32
translated_text: Sabihin na nating hindi siya nagsabi ng totoo | Sabihin nating marami kang pera--ano ang gagawin mo?
Progress: 0.32
translated_text: Ang sipi ay nagbabasa ng mga sumusunod | Ano ang sinasabi ng batas?
Progress: 0.32
translated_text: sabi ko sakanya umuwi na | Inutusan niya siyang mag-shopping | Sinabihan ng ina ang bata na magbihis
Progress: 0.32
translated_text: Binibigkas niya ang mga salitang Pranses sa isang nakakatawang paraan | Hindi ko masasabing `zip wire&#39; | Maaari bang iparinig ng bata ang masalimuot na salitang ito?
Progress: 0.32
translated_text: Ano ang sinasabi ng painting na ito? | May sinabi ba ang mukha niya tungkol sa nararamdaman niya?
Progress: 0.32
translated_text: Sabihin ang grasya | Sinabi niya sa kanya ang &#39;Aba Ginoong Maria&#39;
Progress: 0.32
translated_text: Ang tag-araw ay naglalabas ng matingkad na damit | Inilalabas niya ang pinakamahusay sa kanya
Progress: 0.32
translated_text: Hindi isiwalat ng auction house ang presyo kung saan ibinenta ng van Gogh | Hindi isisiwalat ng aktres kung ilang taon na siya | ilabas ang katotohanan | siya ang nagbalita sa kanya | buksan ang mga ebidensya sa kasong pagpatay
Progress: 0.32
translated_text: Sinabi niya na gusto niya itong pakasalan | sabihin mo sa akin kung ano ang bumabagabag sa iyo | sabihin ang iyong opinyon | isaad ang iyong pangalan
Progress: 0.32
translated_text: Biktima umano siya ng isang krimen | Sinabi niya na huli na para makialam sa digmaan | Ang sabi ng registrar ay may utang ako sa school money
Progress: 0.32
translated_text: Sabihin na nating hindi siya nagsabi ng totoo | Sabihin nating marami kang pera--ano ang gagawin mo?
Progress: 0.32
translated_text: Ang sipi ay nagbabasa ng mga sumusunod | Ano ang sinasabi ng batas?
Progress: 0.32
translated_text: sabi ko sakanya umuwi na | Inutusan niya siyang mag-shopping | Sinabihan ng ina ang bata na magbihis
Progress: 0.32
translated_text: Binibigkas niya ang mga salitang Pranses sa isang nakakatawang paraan | Hindi ko masasabing `zip wire&#39; | Maaari bang iparinig ng bata ang masalimuot na salitang ito?
Progress: 0.32
translated_text: Ano ang sinasabi ng painting na ito? | May sinabi ba ang mukha niya tungkol sa nararamdaman niya?
Progress: 0.32
translated_text: Sabihin ang grasya | Sinabi niya sa kanya ang &#39;Aba Ginoong Maria&#39;
Progress: 0.32
translated_text: gawa ng lahat ng nabanggit na may-akda | ang nasabing partido ay tinanggihan ang mga paratang
Progress: 0.32
translated_text: Ang tag-araw ay naglalabas ng matingkad na damit | Inilalabas niya ang pinakamahusay sa kanya
Progress: 0.32
translated_text: Hindi isiwalat ng auction house ang presyo kung saan ibinenta ng van Gogh | Hindi isisiwalat ng aktres kung ilang taon na siya | ilabas ang katotohanan | siya ang nagbalita sa kanya | buksan ang mga ebidensya sa kasong pagpatay
Progress: 0.32
translated_text: ang iskultura ay isang anyo ng sining | anong klaseng dessert ang meron?
Progress: 0.32
translated_text: ang komposisyon ay nagtatanghal ng mga problema para sa mga mag-aaral ng musikal na anyo | ang isang visual na pattern ay dapat isama hindi lamang ang mga bagay ngunit ang mga puwang sa pagitan ng mga ito
Progress: 0.32
translated_text: Pinag-aralan ni Leonardo ang katawan ng tao | malakas ang pangangatawan niya | kusa ang espiritu ngunit mahina ang laman
Progress: 0.32
translated_text: ang sanaysay ay nasa anyo ng isang diyalogo | una niyang ini-sketch ang plot sa anyong balangkas
Progress: 0.32
translated_text: siya ay nasa tuktok ng kanyang anyo | off form ang team kagabi
Progress: 0.32
translated_text: nabubuo ang mga grupong panlipunan sa lahat ng dako | Nagbuo sila ng isang kumpanya
Progress: 0.32
translated_text: Binubuo ng pader na ito ang background ng setting ng entablado | Ang mga sanga ay ginawang bubong | Ito ay gumagawa ng isang magandang pagpapakilala
Progress: 0.32
translated_text: hubugin ang kuwarta | bumuo ng karakter ng bata
Progress: 0.32
translated_text: Maingat niyang hinulma ang mga rice ball | Bumuo ng mga silindro mula sa kuwarta | hugis ng pigura | Gawing espada ang metal
Progress: 0.32
translated_text: ang rookie ay gumawa ng isang maikling hitsura sa unang yugto | ito ang huling pagpapakita ni Bernhardt sa America
Progress: 0.32
translated_text: sinusubukan nilang panatilihin up appearances | palabas lang ang seremonyang iyon
Progress: 0.32
translated_text: ang kasalukuyang estado ng kaalaman | kanyang estado ng kalusugan | sa mahinang kalagayang pinansyal
Progress: 0.32
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.32
translated_text: bumalik siya sa lupang sinilangan | bumisita siya sa ilang bansa sa Europa

Progress: 0.32
translated_text: Sinabi niya na gusto niya itong pakasalan | sabihin mo sa akin kung ano ang bumabagabag sa iyo | sabihin ang iyong opinyon | isaad ang iyong pangalan
Progress: 0.32
translated_text: isang kondisyon (o estado) ng pagkasira | ang kasalukuyang katayuan ng negosasyon sa armas
Progress: 0.32
translated_text: isang kondisyon sa puso | isang kondisyon ng balat
Progress: 0.32
translated_text: itinakda ng kontrata ang mga kondisyon ng pag-upa | ang mga tuntunin ng kasunduan ay mapagbigay
Progress: 0.32
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.32
translated_text: Nakasaad sa testamento na maaari siyang manirahan sa bahay habang buhay | Ang kontrata ay nagtatakda ng mga petsa ng mga pagbabayad
Progress: 0.32
translated_text: naghilamos siya ng mukha | Sana nakita ko ang pagmumukha niya nang makatanggap siya ng balita
Progress: 0.32
translated_text: isang malungkot na ekspresyon | isang hitsura ng tagumpay | galit na mukha
Progress: 0.32
translated_text: tumingin siya sa isang silid na puno ng mga mukha | pagbalik niya sa trabaho ay marami siyang nakilalang bagong mukha
Progress: 0.32
translated_text: sinuri niya ang lahat ng panig ng kristal | pumatak ang hamog mula sa mukha ng dahon
Progress: 0.32
translated_text: Hindi ako makapaniwala sa kanyang katapangan | nagkaroon siya ng effrontery na tanungin ang aking katapatan
Progress: 0.32
translated_text: Dapat mong harapin ang iyong mga problema | Hinarap niya ang kakila-kilabot na kahihinatnan ng kanyang mga pagkakamali
Progress: 0.32
translated_text: Dapat mong harapin ang iyong kalaban | Hinarap ni Jackson si Smith sa boxing ring | Sa wakas ay nagharap ang dalawang magkaaway
Progress: 0.32
translated_text: Ang bahay ay mukhang hilaga | Ang aking likod-bahay ay tumingin sa pond | Nakaharap ang gusali sa parke
Progress: 0.32
translated_text: ang nakaharap na pahina | magkaharap ang dalawang sofa
Progress: 0.33
translated_text: Hinarap namin siya sa ebidensya | Siya ay nahaharap sa lahat ng ebidensya at hindi na maitatanggi ang kanyang mga aksyon | Isang napakalaking dilemma ang humaharap sa atin
Progress: 0.33
translated_text: Naghintay ako ng ilang araw para sa kanyang sagot | sumulat siya ng mga tugon sa ilan sa kanyang mga kritiko
Progress: 0.33
translated_text: Ayaw niyang sumagot | sagutin ang tanong | Sumagot kami na tatanggapin namin ang imbitasyon
Progress: 0.33
translated_text: siya ay humingi ng paumanhin pagkatapos | pupunta siya sa tindahan pero babalik siya dito mamaya | hindi ito nangyari hanggang pagkatapos | dalawang oras pagkatapos noon
Progress: 0.33
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.33
translated_text: isang pahayag na nagbubuod sa kalagayan ng bansa | ang balita ay inihayag sa bansa | sinamba siya ng buong bansa
Progress: 0.33
translated_text: Ang rehiyon ng Bordeaux ay gumagawa ng magagandang red wine | Gumagawa sila ng magandang ham sa Parma | Nagtatanim kami ng trigo dito | Nag-aalaga kami ng baboy dito
Progress: 0.33
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.33
translated_text: bumalik siya sa lupang sinilangan | bumisita siya sa ilang bansa sa Europa
Progress: 0.33
translated_text: isang pahayag na nagbubuod sa kalagayan ng bansa | ang balita ay inihayag sa bansa | sinamba siya ng buong bansa
Progress: 0.33
translated_text: ito ay isang bulubunduking lugar | Bansa ng Bibliya
Progress: 0.33
translated_text: ito ay isang magandang lugar para sa isang picnic | isang maliwanag na lugar sa isang planeta
Progress: 0.33
translated_text: sino ang may ari ng lugar na ito? | ang pangulo ay nag-aalala tungkol sa ari-arian sa tapat ng White House
Progress: 0.33
translated_text: siya ay may isang espesyal na lugar sa aking mga saloobin | isang lugar sa aking puso | isang sistemang pampulitika na walang lugar para sa hindi gaanong kilalang mga grupo
Progress: 0.33
translated_text: pwede ka bang pumunta sa pwesto ko? | pumalit sa kanyang lugar | kapalit ng
Progress: 0.33
translated_text: ihatid ang pakete sa aking tahanan | wala siyang bahay na mapupuntahan | sa inyo o samin?
Progress: 0.33
translated_text: nalampasan niya ang kanyang pwesto | ang mga responsibilidad ng isang lalaki sa kanyang istasyon | kasal sa itaas ng kanyang istasyon
Progress: 0.33
translated_text: nag-book siya ng kanilang mga upuan nang maaga | umupo siya sa pwesto ng iba
Progress: 0.33
translated_text: nagkita sila sa Elm Plaza | Lugar ng Grosvenor
Progress: 0.33
translated_text: sa pangalawang lugar | lumipat mula sa ikatlo hanggang ikalimang posisyon
Progress: 0.33
translated_text: Ilagay ang iyong mga gamit dito | Ibaba ang tray | Itakda ang mga aso sa pabango ng mga nawawalang bata | Maglagay ng diin sa isang tiyak na punto
Progress: 0.33
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.33
translated_text: tumawag sa telepono | maglagay ng taya
Progress: 0.33
translated_text: Itinutok niya ang kanyang mga kamao sa mukha ng kanyang kalaban | pamumuna nakadirekta sa kanyang superior | idirekta ang iyong galit sa iba, hindi sa iyong sarili
Progress: 0.33
translated_text: ang hanay ng isang supersonic jet | ang isang piano ay may mas malawak na saklaw kaysa sa boses ng tao | ang layunin ng batas sa munisipyo | sa loob ng compass ng artikulong ito | sa loob ng saklaw ng isang pagsisiyasat | hindi maaabot ng batas | sa pampulitikang orbit ng isang kapangyarihang pandaigdig
Progress: 0.33
translated_text: saklaw ng paggalaw | siya ay hindi maabot ng kanilang apoy
Progress: 0.33
translated_text: dinadala nila ang mga baka sa bukas na hanay tuwing tagsibol | pinangarap niya ang isang bahay sa hanay
Progress: 0.33
translated_text: ang lambak ay nasa pagitan ng dalawang hanay ng mga burol | ang mga kapatagan ay nasa kabila lamang ng bulubundukin
Progress: 0.33
translated_text: ang hukbo ay nagpapanatili ng isang hanay ng misayl sa disyerto | anumang magandang golf club ay magkakaroon ng hanay kung saan maaari kang magsanay
Progress: 0.33
translated_text: sinagot niya ang isang hanay ng mga tanong | humanga siya sa hanay at pagkakaiba-iba ng koleksyon
Progress: 0.33
translated_text: Mga pagtatantya para sa mga pagkalugi sa saklaw ng lindol na kasing taas ng $2 bilyon | Ang mga rate ng interes ay tumatakbo mula 5 hanggang 10 porsyento | Ang mga instrumento ay mula sa tuba hanggang sa mga simbalo | Ang aking mga mag-aaral ay mula sa napakaliwanag hanggang sa mapurol
Progress: 0.33
translated_text: Ang mga gypsies ay gumagala sa kakahuyan | roving vagabonds | ang gumagala na Hudyo | Ang mga baka ay gumagala sa buong prairie | ang mga manggagawa ay naaanod mula sa isang bayan patungo sa susunod | Nagpagulong-gulong sila sa bayan
Progress: 0.33
translated_text: ilatag ang mga damit | ilatag ang mga argumento
Progress: 0.33
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.33
translated_text: kinokolekta nila ang basura minsan sa isang linggo | karamihan sa mga basura ay dinadala sa mga imburnal
Progress: 0.33
translated_text: kung ang pagsisikap ay hindi nagdudulot ng kabayarang pakinabang ito ay isang pag-aaksaya | walang isip na pagwawaldas ng mga likas na yaman
Progress: 0.33
translated_text: isang buhay na nailalarawan sa pamamagitan ng walang pag-iimpok at pag-aaksaya | ang pagsasayang ng mga pinalampas na pagkakataon
Progress: 0.33
translated_text: ang mga baog ng gitnang Africa | ang walang track na mga basura ng disyerto
Progress: 0.33
translated_text: Sinayang niya ang kanyang mana sa kanyang mga kaibigang hindi tapat | Sinayang mo ang pagkakataong makakuha at advanced na degree
Progress: 0.33
translated_text: basura init | sayangin ang isang biro sa isang hindi pinapahalagahan na madla
Progress: 0.33
translated_text: Na-liquidate ng mafia ang informer | ang dobleng ahente ay na-neutralize

Progress: 0.33
translated_text: isang disyerto na isla | isang pinabayaan ng diyos na ilang sangang-daan | isang ligaw na kahabaan ng lupain | mga basurang lugar
Progress: 0.33
translated_text: matabang pagkain | matabang tissue
Progress: 0.33
translated_text: isang makatas na kontrata | isang magandang matabang trabaho
Progress: 0.33
translated_text: matabang lupang sakahan | isang matabang lupain | isang produktibong ubasan | mayamang lupa
Progress: 0.33
translated_text: Bahiran ang mesa na ito ng magandang kulay ng walnut | alam ng mga tao kung paano mantsang salamin ang isang magandang asul sa gitnang edad
Progress: 0.33
translated_text: Ang pilak ay nadungisan sa mahabang pagkakalantad sa hangin | Nasira ang kanyang reputasyon matapos ang pakikipagrelasyon sa isang lalaking may asawa
Progress: 0.33
translated_text: gumawa siya ng magandang marka sa algebra | grade A na gatas | ano ang marka mo sa iyong takdang-aralin?
Progress: 0.33
translated_text: tinakpan ng ilang naunang mambabasa ang mga pahina ng dose-dosenang marka | Ang mga paw print ay nasa lahat ng dako
Progress: 0.33
translated_text: ito ay sa London na siya ginawa ang kanyang marka | nag-iwan siya ng hindi maalis na marka sa teatro ng Amerika
Progress: 0.34
translated_text: nagpakita siya ng mga palatandaan ng strain | tinanggap nila ang mga palatandaan ng tagsibol
Progress: 0.34
translated_text: ang bagong kampanya sa advertising ay isang bell ringer | nakapuntos ng bull&#39;s eye | pindutin ang marka | home run ang talumpati ng pangulo
Progress: 0.34
translated_text: minarkahan ng mga tagamanman ang tugaygayan | marka ng abo sa noo ng mga mananampalataya
Progress: 0.34
translated_text: Tinuligsa niya ang aksyon ng gobyerno | Binatikos siya ng lipunan dahil nagkaroon siya ng anak sa labas ng kasal
Progress: 0.34
translated_text: Napansin niyang may sumusunod sa kanya | markahan ang aking mga salita
Progress: 0.34
translated_text: Pakisuri ang bawat pangalan sa listahan | lagyan ng tsek ang mga item | markahan ang mga yunit
Progress: 0.34
translated_text: mga pagsusulit sa grado | puntos ang mga sanaysay sa SAT | markahan ang takdang-aralin
Progress: 0.34
translated_text: nagkaroon ng bahid ng malas | Si Nicklaus ay nagkaroon ng run of birdies
Progress: 0.34
translated_text: may bahid siyang matigas ang ulo | isang bahid ng ligaw
Progress: 0.34
translated_text: isang berdeng palaka na may maliliit na itim na guhit o bar | nawa&#39;y ang mga Bituin at mga Gupit ay magpakailanman
Progress: 0.34
translated_text: ang bawat bata ay inaasahang magbabayad para sa kanilang panatilihin | nag-apply siya sa estado para sa suporta | hindi na niya kayang kumita ng sariling kabuhayan
Progress: 0.34
translated_text: panatilihing malinis | humawak sa puwesto | Palagi niyang pinanghahawakan ang sarili bilang isang ginang | Pinapanatili ako ng mga estudyante sa aking mga paa
Progress: 0.34
translated_text: Magpatuloy sa pagtratrabaho! | Nagpatuloy kami sa trabaho hanggang sa gabi | Patuloy na ngumiti | Nagpatuloy kami sa trabaho hanggang lagpas hatinggabi
Progress: 0.34
translated_text: Maaari ko bang itago ang aking mga lumang stuffed animals? | Itinago niya ang kanyang maiden name pagkatapos niyang ikasal
Progress: 0.34
translated_text: Dapat nating pigilan ang pagkalat ng kanser | Pinigilan ako ng kanyang hilik na makatulog | Iwasang kainin ng bata ang mga marbles
Progress: 0.34
translated_text: panatilihin ang mga appointment | hindi niya tinutupad ang kanyang mga pangako | Nanatili kami sa orihinal na mga kondisyon ng kontrata
Progress: 0.34
translated_text: Ang pianista ay nagpapanatili ng oras sa metronome | panatilihin ang bilang | Hindi ko masubaybayan ang lahat ng aking mga empleyado
Progress: 0.34
translated_text: panatilihin ang isang talaarawan | panatilihin ang isang rekord | panatilihin ang mga tala
Progress: 0.34
translated_text: Pinapanatili niya ang tatlong babae sa guest cottage | panatilihin ang mga boarders
Progress: 0.34
translated_text: Hindi na namin maaaring ipagpatuloy ang ilang mga lingkod | Nananatili siyang abogado | Humina ang yaman ng pamilya at hindi nila mapanatili ang kanilang mga tauhan sa sambahayan | Naubos na ang aming grant at hindi ka namin maipapanatili sa | Ipinagpatuloy namin ang gawain hangga&#39;t kaya namin | Napanatili niya ang kanyang kalmado | napapanatili ng damit na ito ang hugis nito kahit na matapos ang maraming paglalaba
Progress: 0.34
translated_text: Siya lamang ang nagtaguyod ng kanyang pamilya | Ang pera ay magpapapanatili sa ating mabuting layunin | May maliit na kita at marami upang panatilihin
Progress: 0.34
translated_text: Sundin ang mga utos | ipagdiwang ang Pasko | Obserbahan ang Yom Kippur
Progress: 0.34
translated_text: pigil ng ngiti | Panatilihin ang iyong init ng ulo | keep your cool
Progress: 0.34
translated_text: Nag-iingat siya ng ilang manok sa bakuran | nag-iingat siya ng mga bubuyog
Progress: 0.34
translated_text: panatilihin ang aking trabaho para sa akin habang ako ay nanganganak | panatilihin ang aking upuan, mangyaring | panatilihing bukas ang posibilidad ng isang pagsasanib
Progress: 0.34
translated_text: Lagi kong inilalagay ang mga baterya sa freezer | panatilihin ang pagkain sa loob ng isang linggo sa pantry | Nag-iingat siya ng isang sixpack at isang linggong halaga ng mga supply sa refrigerator
Progress: 0.34
translated_text: Nagtatago ako ng kotse sa kanayunan | Nag-iingat siya ng isang apartment sa Paris para sa kanyang mga shopping trip
Progress: 0.34
translated_text: mga inipreserbang karne | panatilihing sariwa ang patatas
Progress: 0.34
translated_text: ang pulis ay sumusunod sa isang promising lead | ang trail ay dumiretso sa may kagagawan
Progress: 0.34
translated_text: nangunguna siya sa alinmang grupo | naghihintay na lang kami ng mangunguna | hindi nila sinunod ang pakay namin
Progress: 0.34
translated_text: nakakuha siya ng tip sa stock market | isang magandang lead para sa isang trabaho
Progress: 0.34
translated_text: Dinala namin siya sa aming punong | pwede mo ba akong ihatid sa main entrance? | Dinala niya kami sa palasyo
Progress: 0.34
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.34
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.34
translated_text: Ang pintong ito ay papunta sa basement | Ang kalsada ay tumatakbo sa Timog
Progress: 0.34
translated_text: Dalhin mo sa akin ang kahon mula sa kabilang kwarto | Dalhin ang mga liham na ito sa amo | Dinadala ako nito sa pangunahing punto
Progress: 0.34
translated_text: Ang mahabang mahirap na taon ng pagsasanay sa trabaho ay nagdala sa kanila sa kanilang kakayahan | magdala ng tubig sa kumukulo
Progress: 0.34
translated_text: Hindi ako makagawa ng milagro | gumawa ng kalituhan | magdala ng mga komento | magbiro | Ang ulan ay nagdulot ng ginhawa sa lugar na tinamaan ng tagtuyot
Progress: 0.34
translated_text: Kunin mo sa akin ang mga aklat na iyon, pakiusap | Maaari mo bang dalhin ang alak? | Kinuha ng aso ang sumbrero
Progress: 0.34
translated_text: magdala ng singil | mga paglilitis sa institusyon
Progress: 0.34
translated_text: Ang kanyang presensya ay nagpapahiram ng isang tiyak na cachet sa kumpanya | Malaki ang naidagdag ng musika sa dulang | Nagdadala siya ng isang espesyal na kapaligiran sa aming mga pagpupulong | Nagdaragdag ito ng isang magaan na tala sa programa
Progress: 0.34
translated_text: Ang pagpipinta ay nagdala ng $10,000 | Ang lumang print ay nakakuha ng mataas na presyo sa auction
Progress: 0.34
translated_text: Dalhin mo sa akin ang kahon mula sa kabilang kwarto | Dalhin ang mga liham na ito sa amo | Dinadala ako nito sa pangunahing punto
Progress: 0.34
translated_text: Ang mahabang mahirap na taon ng pagsasanay sa trabaho ay nagdala sa kanila sa kanilang kakayahan | magdala ng tubig sa kumukulo
Progress: 0.34
translated_text: Hindi ako makagawa ng milagro | gumawa ng kalituhan | magdala ng mga komento | magbiro | Nagdulot ng ginhawa ang ulan sa lugar na naapektuhan ng tagtuyot

Progress: 0.34
translated_text: Kunin mo sa akin ang mga aklat na iyon, pakiusap | Maaari mo bang dalhin ang alak? | Kinuha ng aso ang sumbrero
Progress: 0.34
translated_text: magdala ng singil | mga paglilitis sa institusyon
Progress: 0.34
translated_text: Ang kanyang presensya ay nagpapahiram ng isang tiyak na cachet sa kumpanya | Malaki ang naidagdag ng musika sa dulang | Nagdadala siya ng isang espesyal na kapaligiran sa aming mga pagpupulong | Nagdaragdag ito ng isang magaan na tala sa programa
Progress: 0.34
translated_text: Ang pagpipinta ay nagdala ng $10,000 | Ang lumang print ay nakakuha ng mataas na presyo sa auction
Progress: 0.34
translated_text: takpan ang kanyang mukha ng panyo | takpan ang bata ng kumot | takpan ang libingan ng mga bulaklak
Progress: 0.35
translated_text: Ang digmaan ay pinalawig sa loob ng limang taon | Saklaw ng panahon ang pagliko ng siglo | Ang aking lupain ay umaabot sa ibabaw ng mga burol sa abot-tanaw | Saklaw ng sakahan na ito ang ilang 200 ektarya | Ang Archipelago ay nagpapatuloy ng isa pang 500 milya
Progress: 0.35
translated_text: Ang aklat na ito ay tumatalakay sa incest | Saklaw ng kurso ang lahat ng Western Civilization | Tinatalakay ng bagong aklat ang kasaysayan ng Tsina
Progress: 0.35
translated_text: Ang pangkat na ito ay sumasaklaw sa isang malawak na hanay ng mga tao mula sa iba&#39;t ibang background | ito ay dapat sumaklaw sa lahat ng tao sa grupo
Progress: 0.35
translated_text: Iniulat ni Snow sa China noong 1950&#39;s | Sinakop ng cub reporter ang New York City
Progress: 0.35
translated_text: Mga ibon brood | Tinatakpan ng babae ang mga itlog
Progress: 0.35
translated_text: mga babaeng may takip ang mukha | may takip na mga bagon | isang balcony na may takip
Progress: 0.35
translated_text: ang walang gulo na kaharian ng katwiran | isang lupain ng gawa-gawang | ang pagtaas ng kaharian ng bulak sa timog
Progress: 0.35
translated_text: hindi pa naararo ang lupa | magandang lupang pang-agrikultura
Progress: 0.35
translated_text: pinalawak ang kanyang domain sa Europa | ginawa niya itong batas ng lupain
Progress: 0.35
translated_text: ang eroplano ay tumalikod sa dagat at bumalik sa lupa | yumanig ang lupa ng ilang minuto | ibinagsak niya ang mga troso sa lupa
Progress: 0.35
translated_text: bumalik siya sa lupang sinilangan | bumisita siya sa ilang bansa sa Europa
Progress: 0.35
translated_text: ang walang gulo na kaharian ng katwiran | isang lupain ng gawa-gawang | ang pagtaas ng kaharian ng bulak sa timog
Progress: 0.35
translated_text: isang pahayag na nagbubuod sa kalagayan ng bansa | ang balita ay inihayag sa bansa | sinamba siya ng buong bansa
Progress: 0.35
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.35
translated_text: ang pagsasaka ay isang masipag na buhay | wala nang trabaho sa lupa
Progress: 0.35
translated_text: Lumapag ang ibon sa pinakamataas na sanga | Lumapag ang eroplano sa Istanbul
Progress: 0.35
translated_text: ang sombrerong iyon ay aking pag-aari | siya ay isang tao ng pag-aari
Progress: 0.35
translated_text: sino ang may ari ng lugar na ito? | ang pangulo ay nag-aalala tungkol sa ari-arian sa tapat ng White House
Progress: 0.35
translated_text: Umuwi siya ng 7:00 | Hindi siya nakarating sa Chicago hanggang pagkatapos ng hatinggabi
Progress: 0.35
translated_text: Pagkatapos niyang mailathala ang kanyang libro, dumating na siya | Hindi ko alam kung kakayanin ko ba ito sa science! | Malayo ang mararating mo, anak ko!
Progress: 0.35
translated_text: Siya ay dumating kumanta sa kalsada | Sumama ka sa akin sa Casbah | bumaba ka dito! | lumabas ka sa closet! | pumasok sa kwarto
Progress: 0.35
translated_text: Umuwi siya ng 7:00 | Hindi siya nakarating sa Chicago hanggang pagkatapos ng hatinggabi
Progress: 0.35
translated_text: Dumating ang unang tagumpay makalipas ang tatlong araw | Ito ay dumating bilang isang shock | Ang bukang-liwayway ay dumarating nang maaga sa Hunyo
Progress: 0.35
translated_text: Ang tubig ay dumating sa isang pigsa | Naunawaan natin ang tunay na kahulugan ng buhay | Uminit ang kanilang galit | Napagtanto ko ang tunay na kahulugan ng buhay | Hindi nakatali ang sapatos | makipag-ugnayan sa isang teroristang grupo | namula ang mukha niya | matutupad ang iyong hiling
Progress: 0.35
translated_text: Ang mga melon ay nagmula sa isang baging | Ang pag-unawa ay nagmumula sa karanasan
Progress: 0.35
translated_text: Isang sigaw ang lumabas sa bibig ng babae | Mabigat ang hininga niya
Progress: 0.35
translated_text: Umakyat sa bewang ko ang tubig | Ang manggas ay dumating sa iyong mga buko
Progress: 0.35
translated_text: nabibilang sa isang kategorya | Ito ay nasa ilalim ng isang bagong heading
Progress: 0.35
translated_text: Ang mga bayarin ay umabot sa $2,000 | Umabot sa $2,000 ang bill
Progress: 0.35
translated_text: Ang ideyang ito ay hindi katumbas ng anuman | walang dumating sa kanyang magagarang plano
Progress: 0.35
translated_text: Napag-isipan kong kumuha kami ng isa pang sekretarya | Isang magandang ideya ang dumating sa kanya
Progress: 0.35
translated_text: Siya ay nagmula sa isang matandang Italyanong marangal na pamilya | siya ay nagmula sa mababang pinagmulan
Progress: 0.35
translated_text: Kumusta na kaya siya sa bago niyang trabaho? | Kumusta ka na sa graduate school? | Malayo na ang narating niya
Progress: 0.35
translated_text: Para sa mga hangal ay sumugod kung saan ang mga anghel ay natatakot na tapakan | tumapak sa preno
Progress: 0.35
translated_text: Lumapag ang ibon sa pinakamataas na sanga | Lumapag ang eroplano sa Istanbul
Progress: 0.35
translated_text: ang landed gentry | lupang ari-arian
Progress: 0.35
translated_text: Nahulog ang sanga mula sa puno | Ang kapus-palad na hiker ay nahulog sa isang siwang
Progress: 0.35
translated_text: Bumababa ang temperatura | Ang barometro ay bumabagsak | Nahulog ang kurtina sa diba | Tumaas ang kamay niya saka bumagsak ulit
Progress: 0.35
translated_text: mahulog sa isang bitag | Nagkasakit siya | Nawalan sila ng pabor | Umibig | matulog | mabiktima ng isang impostor | nahulog sa isang kakaibang paraan ng pag-iisip | bumagsak siya pagkatapos niyang mawalan ng trabaho
Progress: 0.35
translated_text: nabibilang sa isang kategorya | Ito ay nasa ilalim ng bagong heading
Progress: 0.35
translated_text: ulan, niyebe at sleet ay bumabagsak | Pinaulanan ni Vesuvius ang nagniningas at mapanirang galit nito sa Herculaneum
Progress: 0.35
translated_text: Dapat tayong tumayo o mahulog | mahulog sa tabi ng daan
Progress: 0.35
translated_text: Maraming sundalo ang nahulog sa Verdun | Ilang usa ang nahulog sa parehong baril | Patay ang biktima ng pamamaril
Progress: 0.35
translated_text: Nahulog ang liwanag sa kanyang mukha | Sumikat ang araw sa mga bukid | Tumama ang liwanag sa gintong kwintas | Isang kakaibang tunog ang tumama sa aking tenga
Progress: 0.35
translated_text: Ang Pasko ay bumagsak sa isang Lunes ngayong taon | Ang impit ay nahuhulog sa unang pantig
Progress: 0.35
translated_text: Bumaba ang dami ng takdang-aralin sa pagtatapos ng semestre | Ang presyon ng cabin ay bumaba nang husto | ang kanyang timbang ay bumaba sa ilalim ng isang daang pounds | bumulong ang boses niya
Progress: 0.35
translated_text: Bumagsak ang gobyerno sa magdamag | Bumagsak ang Dinastiyang Qing kasama si Sun Yat-sen
Progress: 0.35
translated_text: Ang pinakamahirap na gawain ay nahulog sa pinakabatang miyembro ng koponan | Ang responsibilidad ay nahulog sa amin | Ang pressure na magtagumpay ay nahulog sa pinakabatang estudyante
Progress: 0.35
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.35
translated_text: Ang ari-arian ay nahulog sa aking kapatid na babae | Ibinalik ang lupa sa pamilya | Ang ari-arian ay inilipat sa isang tagapagmana na ipinapalagay ng lahat na patay na
Progress: 0.35
translated_text: Nahulog ang plorera at natapon ang tubig sa mesa | Bumagsak ang kanyang buhok sa kanyang noo
Progress: 0.36
translated_text: Nahulog siya sa kanyang upuan | Napaluhod siya
Progress: 0.36
translated_text: Ang damit na ito ay nakabitin nang maayos | Ang mahaba niyang itim na buhok ay dumaloy sa kanyang likuran

Progress: 0.36
translated_text: Bumagsak ang mukha niya nang mabalitaan niyang matatanggal siya sa trabaho | nahulog ang kanyang taluktok
Progress: 0.36
translated_text: Sumapit ang gabi | Bumagsak ang katahimikan
Progress: 0.36
translated_text: natabunan ng mga nahulog na dahon ang sahig ng kagubatan | nakaupo sa isang nahulog na puno ng kahoy
Progress: 0.36
translated_text: pinag-aaralan nila ang ebolusyon ng uniberso | ang pinakamalaking puno na umiiral
Progress: 0.36
translated_text: pinag-aaralan nila ang ebolusyon ng uniberso | ang pinakamalaking puno na umiiral
Progress: 0.36
translated_text: nawasak ang kanyang mundo | nabubuhay tayo sa magkaibang mundo | para sa kanila ang mga demonyo ay bahagi ng realidad gaya ng mga puno
Progress: 0.36
translated_text: ang Earth ay gumagalaw sa paligid ng araw | naglayag siya sa buong mundo
Progress: 0.36
translated_text: ang panlabas na mundo | mundo ng mga insekto
Progress: 0.36
translated_text: ang buong mundo ay nagmamahal sa isang magkasintahan | lagi niyang ginagamit ang `humankind&#39; dahil ang `mankind&#39; ay parang minamaliit ang mga babae
Progress: 0.36
translated_text: pandaigdigang digmaan | pandaigdigang patakaran sa pananalapi | hindi pambansa o kontinental ngunit planetary | isang krisis sa mundo | ng pandaigdigang kahalagahan
Progress: 0.36
translated_text: ang smart set ay napupunta doon | marami silang galit
Progress: 0.36
translated_text: isang pagsabog ng malakas na ulan | isang pagsabog ng kidlat
Progress: 0.36
translated_text: isang barbarous na krimen | brutal na pambubugbog | malupit na pagpapahirap | Ang magaspang na pagtrato ni Stalin sa mga kulak | isang mabangis na sampal | masasamang sipa
Progress: 0.36
translated_text: ang malupit na araw ng tag-init | isang malupit na taglamig
Progress: 0.36
translated_text: makahayop na pagnanasa | isang makahayop na kalikasan | malupit na puwersa | isang mapurol at brutis na lalaki | hayop na pagtrato sa mga bilanggo
Progress: 0.36
translated_text: ang ikatlong baseman ay gumawa ng ilang kapansin-pansing paghinto | ang kanyang paghinto ng agos ay nagresulta sa isang baha
Progress: 0.36
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.36
translated_text: huminto ang sasakyan | Huminto siya sa harap ng bintana ng tindahan
Progress: 0.36
translated_text: Harangan ang kanyang halalan | Itigil ang proseso
Progress: 0.36
translated_text: huminto kami sa bahay ni Tita Mary | huminto sila ng tatlong araw sa Florence
Progress: 0.36
translated_text: huminto ng kotse | pigilan ang magnanakaw
Progress: 0.36
translated_text: itigil ang proyekto | putulin ang negosasyon
Progress: 0.36
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.36
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.36
translated_text: harangan ang daan | barikada ang mga lansangan | itigil ang abalang kalsada
Progress: 0.36
translated_text: isang batch ng mga titik | isang deal ng problema | maraming pera | gumawa siya ng mint sa stock market | tingnan ang iba pang mga nanalo sa aming malaking passel ng mga larawan | ito ay dapat magkaroon ng maraming gastos | isang patay na mamamahayag | isang balumbon ng pera
Progress: 0.36
translated_text: ang libro ay naglalaman ng isang mahusay na talakayan ng modal logic | ang kanyang pagtrato sa tanong ng lahi ay masama
Progress: 0.36
translated_text: naging maayos ang usapan namin | mayroon kaming isang salita o dalawa tungkol dito
Progress: 0.36
translated_text: At ako sa tapat ng pampang ay magiging, handang sumakay at ikalat ang alarma | nakatira kami sa magkabilang gilid ng kalye | sa magkabilang poste
Progress: 0.36
translated_text: nakatingin sa magkasalungat na direksyon | pumunta sila sa magkasalungat na direksyon
Progress: 0.36
translated_text: ang opposite sex | ang dalawang hari ng chess ay naka-set up sa mga parisukat ng magkasalungat na kulay
Progress: 0.36
translated_text: ang epekto ng gamot ay kabaligtaran sa nilalayon | sinasabing ang magkasalungat na karakter ang nagpapasaya sa isang unyon
Progress: 0.36
translated_text: sa diameter na pagkakasalungatan sa kanyang mga claim | diametrical (o kabaligtaran) na mga punto ng view | magkasalungat na kahulugan | matinding at hindi maipagtatanggol na mga polar na posisyon
Progress: 0.36
translated_text: nakaharap sa mesa ang dalawang litrato | buong buhay nila ay nanirahan sa mga bahay nang harapan sa kabila ng kalye | magkatapat sila sa mesa
Progress: 0.36
translated_text: kumikilos na salungat sa ating code of ethics | ang mga katotohanan ay tumuturo sa isang salungat na konklusyon
Progress: 0.36
translated_text: Mary Mary medyo salungat | isang matigas na bata na may marahas na ugali | isang masamang kalooban | naliligaw na pag-uugali
Progress: 0.36
translated_text: masamang agos | isang salungat na hangin
Progress: 0.36
translated_text: ang parehong lalaki na nakita ko kahapon | hindi kailanman nagsuot ng parehong damit nang dalawang beses | ang kalsadang ito ay pareho sa dinaanan namin kahapon | sa parehong gilid ng kalye
Progress: 0.36
translated_text: mga kurtina na kapareho ng kulay ng mga dingding | dalawang batang babae sa parehong edad | ang mag-ina ay may parehong asul na mata | mga hayop ng parehong species | ang parehong mga patakaran tulad ng dati | dalawang kahon na may parehong sukat | sa parehong araw sa susunod na taon
Progress: 0.36
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.36
translated_text: ang nayon ay nanatiling pareho | ang kanyang ugali ay katulad ng dati
Progress: 0.36
translated_text: mga hilera ng magkatulad na bahay | mga sasakyan na magkapareho maliban sa kanilang mga plaka | nagsuot sila ng hindi matukoy na sumbrero
Progress: 0.36
translated_text: ito ang identical room na tinuluyan namin dati | iisa ang tema ng kanyang mga kwento | nakita ang parehong sipi sa dalawang pahayagan | sa mismong lugar na ito | ang mismong sinabi niya kahapon | ang lalaking gusto kong makita
Progress: 0.36
translated_text: hilera ng magkatulad na bahay | mga sasakyan na magkapareho maliban sa kanilang mga plaka | nagsuot sila ng hindi matukoy na sumbrero
Progress: 0.36
translated_text: ito ang identical room na tinuluyan namin dati | iisa ang tema ng kanyang mga kwento | nakita ang parehong sipi sa dalawang pahayagan | sa mismong lugar na ito | ang mismong sinabi niya kahapon | ang lalaking gusto kong makita
Progress: 0.36
translated_text: mayroon siyang isa ngunit kakailanganin ng dalawa at tatlo upang sumama dito | nag-lunch sila sa isa
Progress: 0.36
translated_text: Naglayag siya sa kanyang mga pagsusulit | Dadaan ka with flying colors | Nakuha niya ang kanyang kursong astrophysics
Progress: 0.36
translated_text: isang ace reporter | isang crack shot | isang first-rate na manlalaro ng golp | isang sobrang party | naglaro ng top-notch tennis | isang atleta sa tiptop na kondisyon | siya ay talagang nangunguna
Progress: 0.37
translated_text: lagi silang nakaupo sa kanang bahagi ng simbahan | hindi siya umalis sa tabi ko
Progress: 0.37
translated_text: sinuri niya ang lahat ng panig ng kristal | pumatak ang hamog mula sa mukha ng dahon
Progress: 0.37
translated_text: inikot niya ang kahon upang suriin ang ilalim na bahagi | pininturahan nila ang lahat ng apat na gilid ng bahay
Progress: 0.37
translated_text: siya ay nasa mabigat na bahagi | siya ay nasa panig ng pagbili ng negosyo | inilabas nito ang mas magandang side niya
Progress: 0.37
translated_text: inakyat niya ang matarik na dalisdis | ang bahay ay itinayo sa gilid ng bundok
Progress: 0.37
translated_text: Sinong kasama mo? | ako

Progress: 0.37
translated_text: gilid na bakod | ang side porch
Progress: 0.37
translated_text: kulot ang gilid ng dahon | umupo siya sa gilid ng kama | gilid ng tubig
Progress: 0.37
translated_text: Ang Canada ay katabi ng US | Nagmartsa ang England kasama ang Scotland
Progress: 0.37
translated_text: Salagubang siya sa hagdan | Umuwi sila sa bahay
Progress: 0.37
translated_text: across-the-board na mga pagtaas ng suweldo | isang buong-buong kahulugan | blankong sanction laban sa mga lumalabag sa karapatang pantao | isang imbensyon na may malawak na aplikasyon | isang panoptic na pag-aaral ng nasyonalidad ng Sobyet | binigyan siya ng malawak na kapangyarihan
Progress: 0.37
translated_text: nilinang na pananalita | mga may kulturang Bostonian | kultural na panlasa | isang mabait na matandang babae | magalang na lipunan
Progress: 0.37
translated_text: isang mayabang na opisyal | mayabang na pag-angkin | dibdib na parang paboreal
Progress: 0.37
translated_text: isang mayabang na opisyal | mayabang na pag-angkin | dibdib na parang paboreal
Progress: 0.37
translated_text: isang mayabang na opisyal | mayabang na pag-angkin | dibdib na parang paboreal
Progress: 0.37
translated_text: isang mayabang na opisyal | mayabang na pag-angkin | dibdib na parang paboreal
Progress: 0.37
translated_text: isang lupain ng mga ilog na pilak (o pilak) kung saan lumukso ang salmon | Ang paulit-ulit na pagkayod ay nagbigay sa kahoy ng isang kulay-pilak na kinang
Progress: 0.37
translated_text: nakakasilaw sa kanyang maluwag na dila | pilak na pananalita
Progress: 0.37
translated_text: Namatay sa gutom ang mga bilanggong pulitikal | Maraming nagutom sa kanayunan sa panahon ng tagtuyot
Progress: 0.37
translated_text: siya ay nagugutom sa kanya ng pag-ibig | Nawalan ng gasolina ang makina
Progress: 0.37
translated_text: uhaw sa kaalaman | gutom sa pagkilala | uhaw sa impormasyon
Progress: 0.37
translated_text: Gusto ko nang umuwi | Gusto ko ng sarili kong kwarto
Progress: 0.37
translated_text: Nagtitiwala ako na magiging mas mahusay ka mula ngayon | Sana maintindihan niya na hindi siya makakaasa ng pagtaas
Progress: 0.37
translated_text: isang uhaw sa kaalaman | gutom sa pagmamahal
Progress: 0.37
translated_text: uhaw sa kaalaman | gutom sa pagkilala | uhaw sa impormasyon
Progress: 0.37
translated_text: sabik na matuto | sabik na maglakbay sa ibang bansa | sabik sa tagumpay | sabik na mga katulong | sabik na tingin
Progress: 0.37
translated_text: isang uhaw sa kaalaman | gutom sa pagmamahal
Progress: 0.37
translated_text: isang kagalakang pagmasdan | ang kasiyahan ng kanyang kumpanya | ang bagong kotse ay isang kasiyahan
Progress: 0.37
translated_text: isang kagalakang pagmasdan | ang kasiyahan ng kanyang kumpanya | ang bagong kotse ay isang kasiyahan
Progress: 0.37
translated_text: Siya ay dumating kumanta sa kalsada | Sumama ka sa akin sa Casbah | bumaba ka dito! | lumabas ka sa closet! | pumasok sa kwarto
Progress: 0.37
translated_text: Umuwi siya ng 7:00 | Hindi siya nakarating sa Chicago hanggang pagkatapos ng hatinggabi
Progress: 0.37
translated_text: Dumating ang unang tagumpay makalipas ang tatlong araw | Ito ay dumating bilang isang shock | Ang bukang-liwayway ay dumarating nang maaga sa Hunyo
Progress: 0.37
translated_text: Ang tubig ay dumating sa isang pigsa | Naunawaan natin ang tunay na kahulugan ng buhay | Uminit ang kanilang galit | Napagtanto ko ang tunay na kahulugan ng buhay | Hindi nakatali ang sapatos | makipag-ugnayan sa isang teroristang grupo | namula ang mukha niya | matutupad ang iyong hiling
Progress: 0.37
translated_text: Ang mga melon ay nagmula sa isang baging | Ang pag-unawa ay nagmumula sa karanasan
Progress: 0.37
translated_text: Isang sigaw ang lumabas sa bibig ng babae | Mabigat ang hininga niya
Progress: 0.37
translated_text: Umakyat sa bewang ko ang tubig | Ang manggas ay dumating sa iyong mga buko
Progress: 0.37
translated_text: nabibilang sa isang kategorya | Ito ay nasa ilalim ng isang bagong heading
Progress: 0.37
translated_text: Ang mga bill ay umabot sa $2,000 | Umabot sa $2,000 ang bill
Progress: 0.37
translated_text: Ang ideyang ito ay hindi katumbas ng anuman | walang dumating sa kanyang magagarang plano
Progress: 0.37
translated_text: Napag-isipan kong kumuha kami ng isa pang sekretarya | Isang magandang ideya ang dumating sa kanya
Progress: 0.37
translated_text: Siya ay nagmula sa isang matandang Italyanong marangal na pamilya | siya ay nagmula sa mababang pinagmulan
Progress: 0.37
translated_text: Kumusta na kaya siya sa bago niyang trabaho? | Kumusta ka na sa graduate school? | Malayo na ang narating niya
Progress: 0.37
translated_text: she practices economic without being kuripot | isang hindi mapagbigay na tugon sa apela para sa mga pondo
Progress: 0.37
translated_text: kakaunting mapagkukunan | kakarampot na pamasahe
Progress: 0.37
translated_text: isang maikling buhay | isang maikling flight | isang maikling holiday | isang maikling kwento | ilang maikling buwan lamang
Progress: 0.37
translated_text: maikling palda | maikling buhok | ang board ay isang talampakang maikli | isang maikling paghagis
Progress: 0.37
translated_text: siya ay pandak at pandak | pandak sa tangkad | isang maikling smokestack | isang maliit na lalaki
Progress: 0.37
translated_text: isang hindi sapat na kita | mahinang suweldo | maikli ang pera | sa maikling rasyon | kulang ang pagkain | kapos sa karanasan
Progress: 0.37
translated_text: isang maikling sale | maikli sa cotton
Progress: 0.37
translated_text: isang light pound | isang kaunting tasa ng asukal | regular na nagbibigay ng maikling timbang
Progress: 0.38
translated_text: isang maikling pananaw sa problema | mga patakaran sa shortsighted | kinutya ng mga kritiko ng maikling pananaw ang plano | myopic na pag-iisip
Progress: 0.38
translated_text: shortbread ay isang maikling crumbly cookie | isang maikling flaky pie crust
Progress: 0.38
translated_text: subukang linangin ang isang hindi gaanong brusque na paraan | isang maikling tugon | napakaikli ng salesgirl sa kanya
Progress: 0.38
translated_text: mahinang sabi niya sa akin para ituloy na | maikli niyang kausap ang lahat | maikling sabi niya na hindi niya nagustuhan
Progress: 0.38
translated_text: ang mga batas ay mahigpit na ipinapatupad | mahigpit na kinokontrol
Progress: 0.38
translated_text: Papalapit na kami sa aming destinasyon | Papalapit na sila | Papalapit ng papalapit ang hukbo ng kalaban
Progress: 0.38
translated_text: malapit sa mga kapitbahay | sa malapit na hinaharap | sila ay malapit sa katumbas | ang kanyang pinakamalapit na diskarte sa tagumpay | isang napakalapit na bagay | isang malapit na tamaan ng bomba | siya ay malapit sa luha | siya ay malapit sa luha | nagkaroon ng malapit na tawag
Progress: 0.38
translated_text: ang malapit o malapit na kabayo ay ang nasa kaliwa | ang kaliwang bahagi ng hayop ay ang malapit o malapit na bahagi nito
Progress: 0.38
translated_text: malapit sa beer | isang damit na malapit sa satin
Progress: 0.38
translated_text: aming cheeseparing administration | napakalapit (o malapit) sa kanyang pera | isang peni-pinching kuripot matanda
Progress: 0.38
translated_text: isang mabuting kaibigan | malapit at mahal ang mga kapatid ko
Progress: 0.38
translated_text: naka-sketch sa tinatayang pagkakahawig | isang malapit na pagkakahawig
Progress: 0.38
translated_text: habang papalapit ang araw ng kasal | nakatayo malapit sa pinto | huwag barilin hangga&#39;t hindi sila lumalapit | papalapit sa totoong paliwanag | laging malapit ang kanyang ina | Malapit na ang wakas | hindi nakalapit ang bala | huwag masyadong lumapit sa apoy
Progress: 0.38
translated_text: ang trabaho ay (lamang) tapos na | halos tulog na ang sanggol nang tumunog ang alarm | malapit na tayong matapos | pinatakbo siya pababa ng kotse | muntik na siyang mawalan ng malay | nakipag-usap nang halos 2 oras | ang recording ay halos perpekto | halos lahat ng partido ay pumirma sa kontrata | Malapit na akong mapagod sa pagtakbo | karamihan ay sumasang-ayon
Progress: 0.38
translated_text: gusto niyang lumabas ng kaunti | ginanap sa open air ang concert | camping sa bukas
Progress: 0.38
translated_text: lahat ng mga ulat ay lumabas sa bukas | ang mga katotohanan ay dinala sa ibabaw

Progress: 0.38
translated_text: buksan ang mapa | ibuka ang iyong mga bisig
Progress: 0.38
translated_text: bumukas ang pinto sa patio | Ang mga French door ay nasa terrace
Progress: 0.38
translated_text: isang bukas na pinto | iniwan nilang bukas ang pinto
Progress: 0.38
translated_text: bukas na kanal | ang kalsada ay bukas sa trapiko | bukas na hanay
Progress: 0.38
translated_text: ang nakalantad na hilagang-silangan na hangganan | bukas sa panahon | isang bukas na sugat
Progress: 0.38
translated_text: isang bukas na protesta | isang bukas na liham sa editor
Progress: 0.38
translated_text: panatilihing bukas ang iyong mga mata | bahagyang bumuka ang kanyang bibig
Progress: 0.38
translated_text: bukas na panahon | isang bukas na ekonomiya
Progress: 0.38
translated_text: isang bukas na lungsod | bukas sa pag-atake
Progress: 0.38
translated_text: isang bukas na texture | isang maluwag na habi
Progress: 0.38
translated_text: isang bukas na bangka | isang bukas na apoy | bukas na mga sports car
Progress: 0.38
translated_text: isang bukas na tanong | ang aming posisyon sa panukalang batas na ito ay hindi pa rin mapagpasyahan | ang aming demanda ay hindi pa rin natukoy
Progress: 0.38
translated_text: nakabukas na ang sulat | nakapatong sa mesa ang nakabukas na pakete
Progress: 0.38
translated_text: ang kalinawan at taginting ng isang bukas na tono | ang kanyang natural at bukas na tugon
Progress: 0.38
translated_text: isang lantad na kasinungalingan | hayagang poot | lantarang pagtitipon ng katalinuhan | bukas na mga balota
Progress: 0.38
translated_text: isang sipi na may kakayahang maling interpretasyon | bukas sa interpretasyon | isang isyu na bukas sa tanong | ang oras ay itinakda ng direktor at mga manlalaro at samakatuwid ay napapailalim sa maraming pagkakaiba-iba
Progress: 0.38
translated_text: isang malinaw na pananaw | isang malinaw na landas tungo sa tagumpay | bukas na tubig | ang bukas na kanayunan
Progress: 0.38
translated_text: ang kanyang tapat na mga mata | isang bukas at mapagkakatiwalaang kalikasan | isang heart-to-heart talk
Progress: 0.38
translated_text: sa anong disiplina ang kanyang pagkadoktor? | ang mga guro ay dapat na bihasa sa kanilang paksa | ang antropolohiya ay ang pag-aaral ng tao
Progress: 0.38
translated_text: limitado ang kanyang social sphere | ito ay isang saradong lugar ng trabaho | wala na siya sa orbit ko
Progress: 0.38
translated_text: sila ay lumabas mula sa kakahuyan patungo sa isang malawak na kapatagan | hinangad niya ang mga bukid ng kanyang kabataan
Progress: 0.38
translated_text: ang hukbo ay nasa field na naghihintay ng aksyon | nagsilbi siya sa Vietnam theater sa loob ng tatlong taon
Progress: 0.38
translated_text: bukas na mundo | lahat ay umaasa para sa isang mas magandang bukas
Progress: 0.38
translated_text: huli siyang umindayog sa fastball | wala siyang ipinakita sa mga humampas kundi usok
Progress: 0.38
translated_text: dalawang runner ang nagsimula bago ang baril | isang dalawampung gun salute
Progress: 0.38
translated_text: malalayong lupain | malayong mga bituin
Progress: 0.38
translated_text: isang pagkakataon sa labas | isang malayong posibilidad | isang remote contingency
Progress: 0.38
translated_text: malalayong kaganapan | malayong nakaraan o hinaharap
Progress: 0.38
translated_text: isang malayong pinsan | isang malayong kamag-anak | isang malayong pagkakahawig | mga pagsasaalang-alang na ganap na inalis (o malayo) sa pulitika
Progress: 0.38
translated_text: kaakit-akit na mga incantation | magic sign na nagpoprotekta laban sa masamang impluwensya | isang mahiwagang spell | &#39;ito na ngayon ang napaka witching oras ng gabi | wizard wands | wizardly kapangyarihan
Progress: 0.38
translated_text: Ang Paris ay ang reyna ng mga lungsod | ang reyna ng mga liner ng karagatan
Progress: 0.38
translated_text: makalipas ang dalawang araw ay umalis sila | nagsagawa sila ng dalawang pagtatanghal araw-araw | mayroong 30,000 pasahero kada araw
Progress: 0.38
translated_text: dapat itong dumating anumang araw ngayon | pagkatapos ng araw na iyon ay hindi na siya muling nagtiwala sa kanya | iyon ang mga araw | sa mga araw na ito ay hindi pangkaraniwan
Progress: 0.38
translated_text: ang bukang-liwayway ay ginawang araw ang gabi | mas madaling gawin ang pag-aayos sa araw
Progress: 0.39
translated_text: nagsimula ang araw ko kaninang madaling araw | ito ay isang abalang araw sa stock exchange | tinawag niya itong isang araw at natulog
Progress: 0.39
translated_text: sa araw ng mga dinosaur | noong panahon ng Imperyong Romano | sa mga araw ng paglalayag ng mga barko | siya ay isang matagumpay na pianista sa kanyang panahon
Progress: 0.39
translated_text: karapat-dapat siya sa kanyang araw sa korte | bawat aso ay may kanya-kanyang araw
Progress: 0.39
translated_text: nag-ingat siya sa pagbubukas ng pinto | maingat niyang hinawakan ang vase
Progress: 0.39
translated_text: May nagnakaw ng wallet ko sa tren | Ninakaw ng may-akda na ito ang buong talata mula sa aking disertasyon
Progress: 0.39
translated_text: ang kabayaran ng kasalanan ay kamatayan | ang kabutihan ay sariling gantimpala
Progress: 0.39
translated_text: ito ay naging sa aking kalamangan | umaani ng mga gantimpala ng pagkabukas-palad
Progress: 0.39
translated_text: Ngayon ay pinararangalan natin ang ating mga sundalo | Ang scout ay ginantimpalaan para sa matapang na pagkilos
Progress: 0.39
translated_text: Nanalo siya ng Gold Medal sa skating | Nanalo ang aming home team | Ipanalo ang laro
Progress: 0.39
translated_text: Nakuha ko ang isang dumaan na kaalaman sa Chinese | Magkaroon ng pang-unawa sa internasyonal na pananalapi
Progress: 0.39
translated_text: Ang koponan ng tahanan ay nakakakuha ng lupa | Matapos talunin ang Knicks, naunahan ng Blazers ang Lakers sa laban para sa numero unong playoff berth sa Western Conference
Progress: 0.39
translated_text: Nagtagumpay ang negosyo | Nagtagumpay kami sa pagkuha ng mga tiket sa palabas | nagpumiglas siya upang mapagtagumpayan ang kanyang kapansanan at nanalo
Progress: 0.39
translated_text: Nanalo siya ng Gold Medal sa skating | Nanalo ang aming home team | Ipanalo ang laro
Progress: 0.39
translated_text: Nakuha ko ang isang dumaan na kaalaman sa Chinese | Magkaroon ng pang-unawa sa internasyonal na pananalapi
Progress: 0.39
translated_text: Ang koponan ng tahanan ay nakakakuha ng lupa | Matapos talunin ang Knicks, naunahan ng Blazers ang Lakers sa laban para sa numero unong playoff berth sa Western Conference
Progress: 0.39
translated_text: Nagtagumpay ang negosyo | Nagtagumpay kami sa pagkuha ng mga tiket sa palabas | nagpumilit siyang malampasan ang kanyang kapansanan at nanalo
Progress: 0.39
translated_text: ang kabayaran ng kasalanan ay kamatayan | ang kabutihan ay sariling gantimpala
Progress: 0.39
translated_text: ito ay naging sa aking kalamangan | umaani ng mga gantimpala ng pagkabukas-palad
Progress: 0.39
translated_text: Ngayon ay pinararangalan natin ang ating mga sundalo | Ang scout ay ginantimpalaan para sa matapang na pagkilos
Progress: 0.39
translated_text: Ang magnanakaw jimmied ang lock | Nagawa ng mga raccoon na tanggalin ang takip ng balde ng basura
Progress: 0.39
translated_text: Iginagalang ko ang kanyang paghatol | Pinahahalagahan namin ang kanyang pagkamalikhain
Progress: 0.39
translated_text: piniling mga alak | pangunahing karne ng baka | premyong carnation | de-kalidad na papel | pumili ng mga milokoton
Progress: 0.39
translated_text: tanyag na imahinasyon ay lumikha ng isang mundo ng mga demonyo | Ang imahinasyon ay nagpapakita kung ano ang maaaring maging mundo
Progress: 0.39
translated_text: siya ay may mga delusyon ng kakayahan | ang kanyang mga pangarap ng malawak na kayamanan ay isang guni-guni
Progress: 0.39
translated_text: Siya ached para sa isang sigarilyo | Naiinis ako sa manliligaw ko
Progress: 0.39
translated_text: Nanalo siya ng Gold Medal sa skating | Nanalo ang aming home team | Ipanalo ang laro
Progress: 0.39
translated_text: Nakuha ko ang isang dumaan na kaalaman sa Chinese | Magkaroon ng pang-unawa sa internasyonal na pananalapi
Progress: 0.39
translated_text: Ang koponan ng tahanan ay nakakakuha ng lupa | Matapos talunin ang Knicks, naunahan ng Blazers ang Lakers sa laban para sa numero unong playoff berth sa Western Conference

Progress: 0.39
translated_text: Nagtagumpay ang negosyo | Nagtagumpay kami sa pagkuha ng mga tiket sa palabas | nagpumiglas siya upang mapagtagumpayan ang kanyang kapansanan at nanalo
Progress: 0.39
translated_text: tunay na bagay | totoong tao; hindi multo | isang pelikulang hango sa totoong buhay | isang tunay na sakit | tunay na kababaang-loob | Ang buhay ay totoo! Ang buhay ay taimtim!
Progress: 0.39
translated_text: ang tunay na dahilan | tunay na digmaan | isang tunay na kaibigan | isang tunay na babae | karne at patatas--Tunay na pagkain ang tawag ko diyan | oras na para magkaroon siya ng totoong trabaho | ito ay hindi penny-ante na trabaho--siya ay kumikita ng tunay na pera
Progress: 0.39
translated_text: ipinapakita ng mga istatistika na ang kahirapan at kawalan ng trabaho ay tunay na problema | sa lalaking regular na natutulog sa mga pintuan ay totoo ang kawalan ng tirahan
Progress: 0.39
translated_text: tangible evidence | ang kanyang maikling panahon bilang Punong Ministro ay nagdulot ng ilang tunay na benepisyo sa mahihirap
Progress: 0.39
translated_text: ang kanyang aktwal na motibo | isang literal na pag-iisa na parang disyerto | isang tunay na dilemma
Progress: 0.39
translated_text: tunay na mga presyo | tunay na kita | tunay na sahod
Progress: 0.39
translated_text: ang malaking mundo | isang panaginip lamang, hindi malaki o praktikal | pinakamabigat at makabuluhang bagay
Progress: 0.39
translated_text: napakagaling niya | napakahusay niyang nilalaro | isang napakasayang gabi | Ikinalulungkot ko talaga ito | isang dumadagundong na magandang sinulid
Progress: 0.39
translated_text: lugi ang kumpanya noong nakaraang taon | ang kumpanya ay nagpapatakbo sa pula noong nakaraang taon
Progress: 0.39
translated_text: nagsusulat ng mapupulang mga gawa at barbaric na araw | fann&#39;d sa pamamagitan ng Conquest&#39;s crimson wing | nanginginig sa pulang galit
Progress: 0.39
translated_text: pulang-pula sa galit | naging pula dahil sa pagod | na may mapupulang namumulang mata | mapula ang mukha at marahas | namumula (o pulang-pula) sa kahihiyan
Progress: 0.39
translated_text: ang biglaang martilyo ng mga kamao ay nahuli sa kanya ng hindi nakabantay | ang paghampas ng mga paa sa hallway
Progress: 0.39
translated_text: kinatok ng tindero ang kumakatok sa pinto | isang Southern Baptist na mahilig sa bibliya
Progress: 0.39
translated_text: ram ang gate gamit ang isang sledgehammer | kumatok sa pinto
Progress: 0.39
translated_text: gumawa siya ng magandang marka sa algebra | grade A na gatas | ano ang marka mo sa iyong takdang-aralin?
Progress: 0.39
translated_text: tinakpan ng ilang naunang mambabasa ang mga pahina ng dose-dosenang marka | Ang mga paw print ay nasa lahat ng dako
Progress: 0.39
translated_text: ito ay sa London na ginawa niya ang kanyang marka | nag-iwan siya ng hindi maalis na marka sa teatro ng Amerika
Progress: 0.39
translated_text: nagpakita siya ng mga senyales ng strain | tinanggap nila ang mga palatandaan ng tagsibol
Progress: 0.39
translated_text: ang bagong kampanya sa advertising ay isang bell ringer | nakapuntos ng bull&#39;s eye | pindutin ang marka | home run ang talumpati ng pangulo
Progress: 0.39
translated_text: minarkahan ng mga tagamanman ang tugaygayan | marka ng abo sa noo ng mga mananampalataya
Progress: 0.39
translated_text: Tinuligsa niya ang aksyon ng gobyerno | Binatikos siya ng lipunan dahil nagkaroon siya ng anak sa labas ng kasal
Progress: 0.39
translated_text: Napansin niyang may sumusunod sa kanya | markahan ang aking mga salita
Progress: 0.40
translated_text: Pakisuri ang bawat pangalan sa listahan | lagyan ng tsek ang mga item | markahan ang mga yunit
Progress: 0.40
translated_text: mga pagsusulit sa grado | puntos ang mga sanaysay sa SAT | markahan ang takdang-aralin
Progress: 0.40
translated_text: sinasamba niya ang makapangyarihang dolyar | maliit ang ibig sabihin ng dollar sign sa kanya
Progress: 0.40
translated_text: ang pulis ay sumusunod sa isang promising lead | ang trail ay dumiretso sa may kagagawan
Progress: 0.40
translated_text: nangunguna siya sa alinmang grupo | naghihintay na lang kami ng mangunguna | hindi nila sinunod ang pakay namin
Progress: 0.40
translated_text: nakakuha siya ng tip sa stock market | isang magandang lead para sa isang trabaho
Progress: 0.40
translated_text: Dinala namin siya sa aming punong | pwede mo ba akong ihatid sa main entrance? | Dinala niya kami sa palasyo
Progress: 0.40
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.40
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.40
translated_text: Ang pintong ito ay papunta sa basement | Ang kalsada ay tumatakbo sa Timog
Progress: 0.40
translated_text: isang ilaw na amber ang nagliwanag sa silid | hinangaan niya ang ginto ng buhok nito
Progress: 0.40
translated_text: ang bata ay kasing ganda ng ginto | siya ay may ginintuang puso
Progress: 0.40
translated_text: gintong barya | ang gintong simboryo ng Kapitolyo | ang gintong guya | ginintuan na mga icon
Progress: 0.40
translated_text: mahabang aureate (o ginintuang) buhok | isang gintong karpet
Progress: 0.40
translated_text: isang lupain ng mga ilog na pilak (o pilak) kung saan lumukso ang salmon | Ang paulit-ulit na pagkayod ay nagbigay sa kahoy ng isang kulay-pilak na kinang
Progress: 0.40
translated_text: nakakasilaw sa kanyang maluwag na dila | pilak na pananalita
Progress: 0.40
translated_text: sinasabi niyang corrupt ang kasalukuyang administrasyon | ang pamamahala ng isang asosasyon ay may pananagutan sa mga miyembro nito | mabilis siyang nakilala bilang miyembro ng establisyimento
Progress: 0.40
translated_text: Hindi ako makapaniwala sa kanyang katapangan | nagkaroon siya ng effrontery na tanungin ang aking katapatan
Progress: 0.40
translated_text: isang nickel bag ng droga | isang nickel deck ng heroin
Progress: 0.40
translated_text: pindutin ang iyong mga kamiseta | nakatayo siya doon na namamalantsa
Progress: 0.40
translated_text: ito ang aking pupuntahan | isang spell ng trabaho
Progress: 0.40
translated_text: sinimulan niya ito | Binigyan ko ito ng umiikot
Progress: 0.40
translated_text: Gaano kabilis ang takbo ng iyong bagong sasakyan? | Naglakbay kami mula sa Roma patungong Naples sakay ng bus | Ang mga pulis ay nagbahay-bahay na hinahanap ang suspek | Lumipat ang mga sundalo patungo sa lungsod sa pagtatangkang kunin ito bago sumapit ang gabi | mabilis na naglakbay ang balita
Progress: 0.40
translated_text: Dapat tayong lumayo sa bagay na ito | Marami siyang pinagdaanang problema | lumibot sa mundo sa isang tiyak na paraan | Ang mga mensahe ay dapat dumaan sa mga diplomatikong channel
Progress: 0.40
translated_text: Umalis ka na bago pa ako umiyak | Umaalis ang tren sa tanghali
Progress: 0.40
translated_text: Nainis siya nang marinig ang masamang balita | Dapat itong maging mas seryoso | namula ang mukha niya sa galit | Napunta siya sa ecstasy | Umalis ka na!
Progress: 0.40
translated_text: Ang unang gantimpala ay kay Mary | Napunta sa damit ang pera niya
Progress: 0.40
translated_text: ang kuwento o argumento ay tumatakbo bilang mga sumusunod | sabi nga sa kasabihan...
Progress: 0.40
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.40
translated_text: Naging maayos ang inagurasyon | kamusta ang interview mo?
Progress: 0.40
translated_text: Kailangang umalis ang mga pangit na billboard na ito! | Ang lahat ng mga karangyaan ay kailangang pumunta sa ilalim ng Khmer Rouge
Progress: 0.40
translated_text: Nag `Mmmmm&#39; | Pumutok ang baril
Progress: 0.40
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo

Progress: 0.40
translated_text: Ang pera ay nawala pagkatapos ng ilang araw | Ubos na ang gas sa mga gasolinahan sa Midwest
Progress: 0.40
translated_text: Ang talumpati ay kailangang dumaan sa ilang higit pang mga draft | patakbuhin ang iyong presentasyon bago ang pulong
Progress: 0.40
translated_text: 3 araw kaming walang tubig at pagkain | Ang mga pamahiin na ito ay nabubuhay sa backwaters ng America | Ang driver ng karera ng kotse ay nabuhay sa maraming malubhang aksidente | gaano katagal ang isang tao na walang pagkain at tubig?
Progress: 0.40
translated_text: Paano ito nangyayari? | Naging maayos ang araw hanggang sa natanggap ko ang iyong tawag
Progress: 0.40
translated_text: Namatay siya sa cancer | Ang mga bata ay namatay sa apoy | Ang pasyente ay pumunta nang mapayapa | Sinipa ng matandang lalaki ang balde sa edad na 102
Progress: 0.40
translated_text: Saan nabibilang ang mga aklat na ito? | Ilagay natin ang pangangalagang pangkalusugan kung saan ito nararapat--sa ilalim ng kontrol ng gobyerno | Saan napupunta ang mga aklat na ito?
Progress: 0.40
translated_text: Magsisimula ako ng alas otso ng umaga | Ready, set, go!
Progress: 0.40
translated_text: Maghahalo ang lasa na ito sa iyong ulam | Ang sofa na ito ay hindi sasama sa mga upuan
Progress: 0.40
translated_text: Ang pintong ito ay papunta sa basement | Ang kalsada ay tumatakbo sa Timog
Progress: 0.40
translated_text: Ang makina sa wakas ay umalis | Namatay ang sasakyan sa kalsada | Nasira ang bus na sinakyan namin habang papunta sa bayan | Nasira ang coffee maker | Nabigo ang makina habang papunta sa bayan | ang kanyang paningin ay napunta pagkatapos ng aksidente
Progress: 0.40
translated_text: binisita niya ang bawat estado sa Union | Inaasahan ni Lee na tanggalin ang Maryland mula sa Union | ang nakahihigit na mapagkukunan ng North ay nakabukas ang sukat
Progress: 0.40
translated_text: mga artista tulad ng north light | ang hilagang portiko
Progress: 0.40
translated_text: mas kumikita sila hanggang north | Punta tayo sa norte!
Progress: 0.40
translated_text: isang berdeng puno | berdeng mga patlang | berdeng pintura
Progress: 0.40
translated_text: hilaw na prutas | piniritong berdeng kamatis | berdeng kahoy
Progress: 0.40
translated_text: mukha kang berde | berde sa paligid ng hasang
Progress: 0.40
translated_text: Tubig na umagos | Nagliyab ang apoy palabas ng gusali
Progress: 0.41
translated_text: naglakbay kami sa silangan ng ilang milya | matatagpuan sa silangan ng Roma
Progress: 0.41
translated_text: ang biglaang martilyo ng mga kamao ang nahuli sa kanya | ang paghampas ng mga paa sa hallway
Progress: 0.41
translated_text: kinatok ng tindero ang kumakatok sa pinto | isang Southern Baptist na mahilig sa bibliya
Progress: 0.41
translated_text: ram ang gate gamit ang isang sledgehammer | kumatok sa pinto
Progress: 0.41
translated_text: nagkaroon ng maraming bagong kaibigan | nagtipon siya ng mga salansan ng mga pahayagan
Progress: 0.41
translated_text: siya ay naglalaro ng tennis na may mahusay na enerhiya | puno siya ng zip
Progress: 0.41
translated_text: ang kanyang pagsulat ay naghahatid ng malaking enerhiya | isang kapansin-pansing muscularity ng istilo
Progress: 0.41
translated_text: Bumagsak siya sa kama | Napaupo siya sa upuan
Progress: 0.41
translated_text: Ang araw ay lumubog sa ilalim ng abot-tanaw | Ang lumulubog na araw ay lumubog sa ilalim ng linya ng puno
Progress: 0.41
translated_text: Nasubsob siya sa couch | Bumagsak ang aking diwa
Progress: 0.41
translated_text: Ibinaon niya ang kanyang mga daliri sa malambot na buhangin | Ibinaon niya ang kanyang ulo sa kandungan nito
Progress: 0.41
translated_text: ang kanyang mga tanawin ay itinuring na acme ng kagandahan | ang mga regalo ng artista ay nasa kanilang acme | sa kasagsagan ng kanyang karera | ang rurok ng pagiging perpekto | ang tag-araw ay nasa tuktok nito | ...tinatak si Einstein sa tugatog ng katanyagan | ang summit ng kanyang ambisyon | napakaraming pinakamataas na superlatibo na nakamit ng tao | sa tuktok ng kanyang propesyon
Progress: 0.41
translated_text: ang tanawin mula sa tuktok ay kahanga-hanga | umakyat sila sa dulo ng Monadnock | ang rehiyon ay ilang molekula ang lapad sa tuktok
Progress: 0.41
translated_text: Ang ligaw, mapag-isip na espiritung iyon ay sumikat noong 1929 | Ang mga bid para sa pagpipinta ay nangunguna sa $50 milyon
Progress: 0.41
translated_text: ang kanyang mga tanawin ay itinuring na acme ng kagandahan | ang mga regalo ng artista ay nasa kanilang acme | sa kasagsagan ng kanyang karera | ang rurok ng pagiging perpekto | ang tag-araw ay nasa tuktok nito | ...tinatak si Einstein sa tugatog ng katanyagan | ang summit ng kanyang ambisyon | napakaraming pinakamataas na superlatibo na nakamit ng tao | sa tuktok ng kanyang propesyon
Progress: 0.41
translated_text: ang tanawin mula sa tuktok ay kahanga-hanga | umakyat sila sa dulo ng Monadnock | ang rehiyon ay ilang molekula ang lapad sa tuktok
Progress: 0.41
translated_text: Ang ligaw, mapag-isip na espiritung iyon ay sumikat noong 1929 | Ang mga bid para sa pagpipinta ay nangunguna sa $50 milyon
Progress: 0.41
translated_text: Alisin natin ang kurso sa Akkadian hieroglyphics | Pinawi ng sosyalismo ang mga makalumang kaugalian na ito | tanggalin ang aking mga utang
Progress: 0.41
translated_text: Inalis si John bilang posibleng suspek dahil malakas ang alibi niya | Ang posibilidad na ito ay maaaring alisin sa aming pagsasaalang-alang
Progress: 0.41
translated_text: ang mga bakas ng pampulitikang demokrasya ay agad na binawi | alisin ang katiwalian
Progress: 0.41
translated_text: Ang lalaking ito ay pumatay ng maraming tao nang subukan niyang magnakaw sa isang bangko | Ang magsasaka ay pumatay ng baboy para sa bakasyon
Progress: 0.41
translated_text: pumatay ng galaw | binatukan niya ang proposal ng estudyante
Progress: 0.41
translated_text: ang sigarilyo ay pumatay | nakamamatay ang pagmamaneho ng lasing
Progress: 0.41
translated_text: Nag-down siya ng tatlong martinis bago kumain | Nakapatay siya ng isang bote ng brandy noong gabing iyon | Uminom sila ng ilang beer pagkatapos ng trabaho
Progress: 0.41
translated_text: may pagkatulala ang ekspresyon ng mukha niya | humiga ng kalahating malay, natulala (o natulala) sa suntok | ay bobo dahil sa pagod
Progress: 0.41
translated_text: may pagkatulala ang ekspresyon ng mukha niya | humiga ng kalahating malay, natulala (o natulala) sa suntok | ay bobo dahil sa pagod
Progress: 0.41
translated_text: sobrang siksik hindi niya naiintindihan kahit anong sabihin ko sa kanya | hindi kailanman nakilala ang sinuman na medyo madilim | bagaman mapurol sa klasikal na pag-aaral, sa matematika siya ay hindi karaniwang mabilis | ang mga piping opisyal ay gumagawa ng ilang talagang piping desisyon | siya ay karaniwang hangal o sadyang mapurol | nakipagtulungan sa mga mabagal na mag-aaral
Progress: 0.41
translated_text: struck pipi | hindi nakaimik sa gulat
Progress: 0.41
translated_text: sabik na makita ang bagong palabas sa museo | namamatay na marinig kung sino ang nanalo
Progress: 0.41
translated_text: gumugol ng isang balisang gabi sa paghihintay para sa mga resulta ng pagsusulit | nagsumite ng balisang sulyap sa likod niya | mga kaba na sandali bago mag-takeoff | isang hindi matahimik na isip
Progress: 0.41
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.41
translated_text: Sinibak ng amo ang kanyang sekretarya ngayon | Tinapos ng kumpanya ang 25% ng mga manggagawa nito
Progress: 0.41
translated_text: Pinon ng panukalang ito ang aming mga pagsisikap | Ang kanilang pag-uugali ay natigil sa pagsusumikap ng amo
Progress: 0.41
translated_text: isang pilay na sundalo | isang paa ng laro
Progress: 0.41
translated_text: Pinon ng panukalang ito ang aming mga pagsisikap | Ang kanilang pag-uugali ay natigil sa pagsusumikap ng amo
Progress: 0.41
translated_text: isang baldado na sundalo | isang paa ng laro
Progress: 0.41
translated_text: pagbibigay ng makatotohanang balangkas para sa hinaharap na pananaliksik | ito ay bahagi ng tela ng lipunan
Progress: 0.41
translated_text: ang sukat ng mapa | ang sukat ng modelo
Progress: 0.41
translated_text: walang natitira | itinapon niya ang natitira | kinuha niya ang gusto niya at nakuha ko ang balanse

Progress: 0.41
translated_text: Kailangan niyang balansehin ang trabaho at ang kanyang mga tungkulin sa tahanan | balansehin ang dalawang timbang
Progress: 0.41
translated_text: ang kawalan ng imahinasyon ay isang balakid sa pagsulong ng isang tao | ang kahirapan ng isang distrito ay isang balakid sa magandang edukasyon | ang filibustero ay isang malaking hadlang sa tagumpay ng kanilang plano
Progress: 0.41
translated_text: ang kawalan ng imahinasyon ay isang balakid sa pagsulong ng isang tao | ang kahirapan ng isang distrito ay isang balakid sa magandang edukasyon | ang filibustero ay isang malaking hadlang sa tagumpay ng kanilang plano
Progress: 0.41
translated_text: gusto niyang maramdaman ang isang bahagi ng isang bagay na mas malaki kaysa sa kanyang sarili | Nabasa ko ang isang bahagi ng manuskrito | ang mas maliit na bahagi ay mahirap abutin | ang hayop na bumubuo ng plankton
Progress: 0.41
translated_text: ang likurang bahagi ng bahay | idikit ang dalawang bahagi
Progress: 0.41
translated_text: sinuri nila ang ilog sa tatlong bahagi | kailangan niya ng isang piraso ng granite
Progress: 0.41
translated_text: nangangailangan ito ng pagbabantay sa ating bahagi | nilalabanan nila ang bawat pagsisikap sa kanyang bahagi
Progress: 0.41
translated_text: ang mga rehiyon ng pagsasaka ng France | relihiyon sa lahat ng bahagi ng mundo | mga rehiyon ng kalawakan
Progress: 0.41
translated_text: ang tungkulin ng isang guro | dapat gawin ng gobyerno ang bahagi nito | gampanan ang papel nito
Progress: 0.41
translated_text: ang nakasulat na bahagi ng pagsusulit | ang seksyon ng pananalapi ng kumpanya | engineering division ng BBC
Progress: 0.41
translated_text: Ipinagmamalaki ko ang aking kontribusyon sa pagsulong ng proyekto | ginawa nilang lahat ang kanilang bahagi sa gawain
Progress: 0.42
translated_text: Sinira ng mga kasosyo sa negosyo ang isang tanong sa buwis | Naghiwalay ang mag-asawa pagkatapos ng 25 taong pagsasama | Naghiwalay kami ng kaibigan ko
Progress: 0.42
translated_text: Pinaghiwalay niya ang mga batang nag-aaway | Hinati ni Moises ang Dagat na Pula
Progress: 0.42
translated_text: Nadama kong bahagyang sisihin | Bahagyang naparalisa siya
Progress: 0.42
translated_text: may bagong tatak ng bayani sa mga pelikula ngayon | anong make of car yan?
Progress: 0.42
translated_text: Tinuligsa niya ang aksyon ng gobyerno | Binatikos siya ng lipunan dahil nagkaroon siya ng anak sa labas ng kasal
Progress: 0.42
translated_text: gumawa siya ng magandang marka sa algebra | grade A na gatas | ano ang marka mo sa iyong takdang-aralin?
Progress: 0.42
translated_text: huwag gawin ito sa aking account | ang papel ay tinanggihan dahil sa haba nito | sinubukan niyang sisihin ang biktima ngunit nagdududa ang tagumpay niya sa iskor na iyon
Progress: 0.42
translated_text: may hawak na sama ng loob | pag-aayos ng marka
Progress: 0.42
translated_text: Maraming beses umiskor ang home team | Naka-home run siya | Naabot niya ang .300 noong nakaraang season
Progress: 0.42
translated_text: Sa wakas ay naakit ni Harry si Sally | Naka-score ka ba kagabi? | Ginawa ni Harry si Sally
Progress: 0.42
translated_text: Mataas ang score niya sa SAT | Nakakuha siya ng 200
Progress: 0.42
translated_text: mga pagsusulit sa grado | puntos ang mga sanaysay sa SAT | markahan ang takdang-aralin
Progress: 0.42
translated_text: gumawa siya ng magandang marka sa algebra | grade A na gatas | ano ang marka mo sa iyong takdang-aralin?
Progress: 0.42
translated_text: isang katamtamang grado ng katalinuhan | isang mataas na antas ng pangangalaga ang kailangan | lahat ng ito ay isang bagay ng antas
Progress: 0.42
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.42
translated_text: mga pagsusulit sa grado | puntos ang mga sanaysay sa SAT | markahan ang takdang-aralin
Progress: 0.42
translated_text: namumuhunan lamang siya sa malalaking kumpanyang mahusay na itinatag | sinimulan niya ang kumpanya sa kanyang garahe
Progress: 0.42
translated_text: na-miss niya ang kumpanya nila | nasiyahan siya sa lipunan ng kanyang mga kaibigan
Progress: 0.42
translated_text: nag-organisa sila ng isang party para maghanap ng pagkain | pumasok sa kusina ang kumpanya ng mga kusinero
Progress: 0.42
translated_text: ang inaugural na isyu ng magazine | ang yugto ng inisyatiba sa mga negosasyon | isang panimulang hakbang tungo sa isang kasunduan | ang kanyang unang (o dalaga) na talumpati sa Kongreso | ang unang paglalayag ng liner
Progress: 0.42
translated_text: wag dito mag drill, may gas pipe | mag-drill ng butas sa dingding | drill para sa langis | Ang mga bubuyog ng karpintero ay may mga butas sa dingding
Progress: 0.42
translated_text: bored sa buhay | naglakad-lakad sa museo na may inip na hangin
Progress: 0.42
translated_text: kanyang blase pagwawalang-bahala | isang petulant blase air | ang bored na titig ng matagumpay na bida sa pelikula
Progress: 0.42
translated_text: isang masungit na bansa | isang pagalit na pangungusap | masasamang aksyon
Progress: 0.42
translated_text: isang masamang klima | isang hindi kanais-nais na kapaligiran | isang hindi kanais-nais na lupa | ang hindi magiliw na kapaligiran sa matataas na lugar
Progress: 0.42
translated_text: pagalit na pagkuha sa kapangyarihan | pagalit na malambot na alok | pagalit na bid
Progress: 0.42
translated_text: ang kanyang mga hiwa ay mahusay | ang kanyang pagputol ng cake ay gumawa ng isang kahila-hilakbot na gulo
Progress: 0.42
translated_text: iginiit niya na bigyan namin siya ng huling hiwa bago ang bawat deal | ang pagputol ng mga baraha ay naging isang ritwal
Progress: 0.42
translated_text: ang pagputol ng whisky na may tubig | ang pagnipis ng pintura na may turpentine
Progress: 0.42
translated_text: bawasan ang iyong pang-araw-araw na paggamit ng taba | Gusto ng employer na bawasan ang mga benepisyong pangkalusugan
Progress: 0.42
translated_text: Naputol ang sasakyan sa kaliwa sa intersection | Lumiko sa kanan ang motor
Progress: 0.42
translated_text: maghiwa ng butas | gupitin ang mga kanal | Ang pawis ay tumatama sa kanyang mukha
Progress: 0.42
translated_text: sumulat ng tseke | putulin ang isang tiket | Mangyaring gawin ang check out sa akin
Progress: 0.42
translated_text: i-edit ang pelikula | gupitin ang recording tape
Progress: 0.42
translated_text: Hindi ko na ito ma-hack | hindi niya maaaring putulin ang mahabang araw sa opisina
Progress: 0.42
translated_text: gupitin ang mga kanta | Pinutol niya muli ang lahat ng kanyang pangunahing titulo
Progress: 0.42
translated_text: gupitin ang isang disk | magsunog ng CD
Progress: 0.42
translated_text: Pinutol ni Wayne | Matagal niyang pinutol ang kubyerta
Progress: 0.42
translated_text: I-off ang stereo, mangyaring | putulin ang makina | patayin ang mga ilaw
Progress: 0.42
translated_text: putulin ang ingay | Kinailangan naming putulin ang usapan
Progress: 0.42
translated_text: cutting remarks | talim satire | isang nakatutuwang komento
Progress: 0.42
translated_text: isang malakas na hangin | matalas na hangin | parang kutsilyo malamig | piercing like knife pains | piercing cold | matalim na pamumuna | isang pananakit ng saksak | sakit ng lancinating
Progress: 0.42
translated_text: nagkaroon ng karagdagan sa mga buwis sa ari-arian ngayong taon | naitala nila ang pagtaas ng timbang ng baka sa loob ng ilang linggo
Progress: 0.42
translated_text: ang pagtaas ng kawalan ng trabaho | ang paglaki ng populasyon
Progress: 0.42
translated_text: Sa wakas ay tinaasan ng amo ang kanyang suweldo | Dinagdagan ng unibersidad ang bilang ng mga estudyanteng pinapasok nito
Progress: 0.42
translated_text: isang malaking lungsod | itinakda para sa malaking lungsod | isang malaking halaga | isang malaking (o malaking) kamalig | isang malaking pamilya | malalaking negosyo | isang malaking paggasta | isang malaking bilang ng mga pahayagan | isang malaking grupo ng mga siyentipiko | malalaking lugar sa mundo
Progress: 0.42
translated_text: isang masamang ulo | sa isang malaking galit | nagkaroon ng malaking (o masamang) pagkabigla | isang masamang lindol | isang masamang bagyo
Progress: 0.42
translated_text: isang malaking boses | malaking bold na tunog ng piano

Progress: 0.42
translated_text: isang malaking pigura sa kilusan | malaking tao sa campus | siya ay napakalaki sa mga pampinansyal na bilog | isang kilalang mamamayan
Progress: 0.42
translated_text: malaking gumastos | malaking mangangain | mabigat na mamumuhunan
Progress: 0.43
translated_text: masyadong malaki para sa kanyang britches | nagkaroon ng pamamaga ng ulo | nabusog siya sa pagmamalaki
Progress: 0.43
translated_text: isang matanda na hayop | isang matandang babae
Progress: 0.43
translated_text: isang pusong sapat na malaki upang walang sama ng loob | na napakalaki mo para maging mapagpatawad | isang malaki at mapagbigay na espiritu | isang malaking puso | mapagbigay sa kanyang mga kaaway
Progress: 0.43
translated_text: ay isang malaking tipper | ang masaganang kabutihan ng Diyos | masaganang papuri | isang freehanded host | isang gwapong allowance | Ang anak ng Sabado ay mapagmahal at nagbibigay | isang liberal na tagapagtaguyod ng sining | isang munificent regalo | ang kanyang magiliw at bukas-palad na lolo
Progress: 0.43
translated_text: ay malaki sa anak | ay mahusay na may anak
Progress: 0.43
translated_text: malalawak na kalsada | isang malawak na kurbata | malawak na margin | tatlong talampakan ang lapad | isang ilog na dalawang milya ang lapad | malapad na balikat | isang malawak na ilog
Progress: 0.43
translated_text: across-the-board na mga pagtaas ng suweldo | isang buong-buong kahulugan | blankong sanction laban sa mga lumalabag sa karapatang pantao | isang imbensyon na may malawak na aplikasyon | isang panoptic na pag-aaral ng nasyonalidad ng Sobyet | binigyan siya ng malawak na kapangyarihan
Progress: 0.43
translated_text: isang malawak na tuntunin | ang malawak na mga balangkas ng plano | nakaramdam ng hindi tiyak na pangamba
Progress: 0.43
translated_text: malawak na liwanag ng araw | buong tag-araw
Progress: 0.43
translated_text: isang malawak na damuhan | ang malawak na kapatagan | isang maluwang na tanawin | maluwang na kalangitan
Progress: 0.43
translated_text: isang malawak na pampulitikang paninindigan | mapagbigay at malawak na pakikiramay | isang liberal na pahayagan | mapagparaya sa mga opinyon ng kanyang kalaban
Progress: 0.43
translated_text: pakawalan ang mga mina | Maluwag na kakila-kilabot na mga salot sa sangkatauhan
Progress: 0.43
translated_text: Lumuwag ang silong | lumuwag ang lubid
Progress: 0.43
translated_text: maluwag na damit | maluwag na maluwag ang malalaking sapatos
Progress: 0.43
translated_text: isang impormal na kasunduan | isang maluwag na organisasyon ng mga lokal na magsasaka
Progress: 0.43
translated_text: isang maluwag na interpretasyon ng sinabi sa kanya | isang libreng pagsasalin ng tula
Progress: 0.43
translated_text: maluwag at kulay abo ang balat ng matanda | malubay at kulubot na balat | matumal na layag | isang maluwag na lubid
Progress: 0.43
translated_text: isang bukas na texture | isang maluwag na habi
Progress: 0.43
translated_text: idle talk | isang maluwag na dila
Progress: 0.43
translated_text: isang convict pa rin at large | naghahanap ng dalawang nakatakas na bilanggo | asong nakalugay sa mga lansangan | mga kriminal sa kalye sa kapitbahayan
Progress: 0.43
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.43
translated_text: malalawak na kalsada | isang malawak na kurbata | malawak na margin | tatlong talampakan ang lapad | isang ilog na dalawang milya ang lapad | malapad na balikat | isang malawak na ilog
Progress: 0.43
translated_text: across-the-board na mga pagtaas ng suweldo | isang buong-buong kahulugan | blanket sanction laban sa mga lumalabag sa karapatang pantao | isang imbensyon na may malawak na aplikasyon | isang panoptic na pag-aaral ng nasyonalidad ng Sobyet | binigyan siya ng malawak na kapangyarihan
Progress: 0.43
translated_text: isang malawak na damuhan | ang malawak na kapatagan | isang maluwang na tanawin | maluwang na kalangitan
Progress: 0.43
translated_text: ang kasalukuyang lasa para sa malawak na pantalon | isang buong palda
Progress: 0.43
translated_text: malapad ang sipa | ang palaso ay malapad ng marka | isang pag-aangkin na malawak sa katotohanan
Progress: 0.43
translated_text: tumayo nang magkahiwalay ang mga binti | tumakbo ng malawak sa kaliwang dulo
Progress: 0.43
translated_text: imulat mo ang iyong mga mata | habang nakabukas ang throttle
Progress: 0.43
translated_text: lumawak ang palaso sa marka | isang bala ang naligaw at napatay ang isang nakabantay
Progress: 0.43
translated_text: gumala nang malawak sa maraming lupain | malawak ang kanyang paglalakbay
Progress: 0.43
translated_text: ang kumpanya ay kasiya-siya | natagpuan ang kanyang papuri na kasiya-siya | puno ng kaligayahan at kasiya-siyang kaguluhan | ang mahusay na pag-print ay ginagawang mas kasiya-siyang basahin ang isang libro
Progress: 0.43
translated_text: lunasan ang mga pagkukulang na ito | iwasto ang hindi pagkakapantay-pantay sa mga suweldo | ayusin ang isang oversight
Progress: 0.43
translated_text: matatangkad na tao | matataas na gusali | matataas na puno | matataas na barko
Progress: 0.43
translated_text: wala siya ngayon | hindi mo dapat papasukin ang isang estranghero sa bahay kapag wala ang iyong ina
Progress: 0.43
translated_text: ang pitch ay malayo (o malawak) | isang pitch sa labas
Progress: 0.43
translated_text: tumakas sa leon | gustong lumayo roon | pinaalis ang mga bata sa boarding school | kinawayan ng guro ang mga bata palayo sa patay na hayop | pumunta sa paaralan | umalis sila | humayo kayo at mangaral
Progress: 0.43
translated_text: namigay siya ng pera sa mahihirap | namigay ng ticket
Progress: 0.43
translated_text: isantabi ang mga pagtutol | itinulak ang lahat ng pagdududa
Progress: 0.43
translated_text: nawala ang musika | sinubukang ipaliwanag ang kapakanan ng liham | idle ang mga oras na malayo | ang kanyang mga kuko ay pagod na
Progress: 0.43
translated_text: ang bangka ay 5 milya ang layo (o ang layo) | ang party ay 2 linggo pa rin (o wala pa) | malayo noong ika-18 siglo
Progress: 0.43
translated_text: siya ay nagtrabaho sa malayo sa proyekto para sa higit sa isang taon | walang tigil sa pagmamartilyo ang bata na parang dito nakasalalay ang buhay niya
Progress: 0.43
translated_text: inalis ang gulo | ang bulok na kahoy ay kailangang putulin
Progress: 0.43
translated_text: ilagay ang mga laruan | ang kanyang mga alahas ay nakakulong sa isang ligtas | inihain ang sulat
Progress: 0.43
translated_text: tumabi | italikod ang mukha | umiwas ng tingin
Progress: 0.43
translated_text: nagsimulang magtabi ng pera para makabili ng sasakyan | maglagay ng isang bagay para sa kanyang katandaan | may pugad na itlog na nakatago para sa tag-ulan
Progress: 0.43
translated_text: Nag-donate ako ng dugo sa Red Cross para sa mga biktima ng lindol | mag-abuloy ng pera sa ampunan | Nag-donate siya sa kanyang paboritong kawanggawa bawat buwan
Progress: 0.43
translated_text: mga panuntunang may partikular na aplikasyon | hinihingi na tiyak sa trabaho | isang tiyak at detalyadong account ng aksidente
Progress: 0.43
translated_text: ang quinine ay lubos na tiyak para sa malaria | isang tiyak na lunas | ang isang tiyak na mantsa ay ang pagkakaroon ng isang tiyak na pagkakaugnay para sa mga partikular na elemento ng istruktura
Progress: 0.43
translated_text: pataas at tungkol sa | nabulabog ang buong bayan sa pangyayari
Progress: 0.43
translated_text: tumagal ng humigit-kumulang isang oras | sa loob lamang ng isang minuto | siya ay mga 30 taong gulang | Nakuha ko na ang lahat ng kaya kong panindigan | nagkikita kami halos isang beses sa isang buwan | ilang apatnapung tao ang dumating | tumitimbang ng humigit-kumulang isang daang libra | humigit-kumulang $3,000 | may hawak na 3 galon, higit pa o mas mababa | 20 o higit pang mga tao ang nasa party
Progress: 0.43
translated_text: maruruming damit na nakalatag sa paligid (o tungkol sa) | hanapin natin ang tungkol sa tulong | May mga puno na tumutubo sa paligid | tumingin siya sa paligid niya
Progress: 0.44
translated_text: ilang manonood na nakatayo tungkol sa | tambay sa paligid | naghintay sa susunod na flight
Progress: 0.44
translated_text: gumagala na walang mapupuntahan | ang mga tao ay nagmamadali tungkol sa | balita ay nakukuha sa paligid (o tungkol sa) | naglibot sa Asya | kailangan niya ng payo mula sa isang taong nakapaligid na | natutulog siya sa paligid

Progress: 0.44
translated_text: tungkol sa mukha | bigla siyang lumingon
Progress: 0.44
translated_text: ang trabaho ay (lamang) tapos na | halos tulog na ang sanggol nang tumunog ang alarm | malapit na tayong matapos | pinatakbo siya pababa ng kotse | muntik na siyang mawalan ng malay | nakipag-usap nang halos 2 oras | ang recording ay halos perpekto | halos lahat ng partido ay pumirma sa kontrata | Malapit na akong mapagod sa pagtakbo | karamihan ay sumasang-ayon
Progress: 0.44
translated_text: Binigyan niya siya ng black eye | Nilamig ako ng draft
Progress: 0.44
translated_text: Binigyan niya ako ng maraming problema | Ang aming pagpupulong ay nagbigay ng maraming kawili-wiling impormasyon
Progress: 0.44
translated_text: Ibinigay ko sa kanya ang aking pera | maaari mo ba akong bigyan ng mga aralin? | Binigyan niya ang mga bata ng maraming pagmamahal at magiliw na pag-aalaga
Progress: 0.44
translated_text: Huwag mo siyang pansinin | ibigay ang mga utos | Bigyan mo siya ng aking pinakamahusay na pagbati | bigyang-pansin
Progress: 0.44
translated_text: magdaos ng reception | magkaroon, magtapon, o gumawa ng isang party | magbigay ng kurso
Progress: 0.44
translated_text: Sulyap | Binigyan niya ako ng masamang tingin
Progress: 0.44
translated_text: pag-isipan ang | bigyan ng prayoridad ang | pansinin mo
Progress: 0.44
translated_text: Ang baka ay nagdadala ng 5 litro ng gatas | Ang pananim ngayong taon ay nagbunga ng 1,000 bushel ng mais | Ang ari-arian ay nagbibigay ng ilang kita para sa pamilya
Progress: 0.44
translated_text: magbigay ng lihim sa mga Ruso | iwanan ang iyong pangalan at tirahan dito | magbigay ng bagong kasanayan sa mga mag-aaral
Progress: 0.44
translated_text: Maaari ko bang ibigay sa iyo ang aking mga susi habang nasa pool ako? | Maaari ko bang ibigay sa iyo ang mga bata para sa katapusan ng linggo?
Progress: 0.44
translated_text: Bigyan ng isang lagok | sumigaw
Progress: 0.44
translated_text: Ibinigay niya ang kanyang buhay para sa kanyang mga anak | Binigyan ko ang dalawang anak na lalaki sa digmaan
Progress: 0.44
translated_text: bigyan mo ako ng kutsara, pakiusap | Ibalik ang mga file sa akin, mangyaring | Ibinalik niya ang bilanggo sa kanyang mga abogado
Progress: 0.44
translated_text: Ipinangako niya ang kanyang sarili sa gawain ng Diyos | ibigay ang mga talento sa isang mabuting layunin | ialay ang iyong buhay sa simbahan
Progress: 0.44
translated_text: Binigyan niya siya ng First Aid | Binigyan ko siya ng suntok sa ilong
Progress: 0.44
translated_text: magbigay pugay | magpasalamat
Progress: 0.44
translated_text: bigyan ng degree | magbigay ng diborsiyo | Ang panukalang batas na ito ay nagbibigay sa atin ng mga bagong karapatan
Progress: 0.44
translated_text: Ang parke ay nagbigay daan sa isang supermarket | &#39;Lumapit kayo,&#39; sinabi niya sa karamihan
Progress: 0.44
translated_text: Pakanin ang mga nagugutom na bata sa India | huwag bigyan ang bata ng matigas na karneng ito
Progress: 0.44
translated_text: Gumuho ang pader | Bumagsak ang negosyo | Nabasag ang dam | Gumuho ang bubong | Ang pader ay nagbigay | Ang bubong sa wakas ay nagbigay sa ilalim ng bigat ng yelo
Progress: 0.44
translated_text: Binigyan niya ang pasyente ng tatlong buwan upang mabuhay | Binigyan ko siya ng napakagandang pagkakataon sa tagumpay
Progress: 0.44
translated_text: bumukas ang pinto sa patio | Ang mga French door ay nasa terrace
Progress: 0.44
translated_text: Ang mag-aaral na ito ay nagbibigay ng pangako ng tunay na pagkamalikhain | Ang opisina ay nagbigay ng ebidensya ng pakikialam
Progress: 0.44
translated_text: magbigay ng sariling opinyon | magbigay ng rason
Progress: 0.44
translated_text: Binigyan niya ng magandang palo ang bata | Binigyan ako ng hukom ng 10 taon
Progress: 0.44
translated_text: Ang unibersidad ay naggawad ng degree sa pinakasikat na dating estudyante nito, na hindi nagtapos | magbigay ng karangalan sa isang tao
Progress: 0.44
translated_text: Ang kanyang presensya ay nagpapahiram ng isang tiyak na cachet sa kumpanya | Malaki ang naidagdag ng musika sa dulang | Nagdadala siya ng isang espesyal na kapaligiran sa aming mga pagpupulong | Nagdaragdag ito ng magaan na tala sa programa
Progress: 0.44
translated_text: Hindi gagamitin ng ina ni Joe ang kanyang palayaw at palaging tinatawag siyang Joseph | Ang palayaw ni Henry ay Slim
Progress: 0.44
translated_text: ang pagsasaka ay isang masipag na buhay | wala nang trabaho sa lupa
Progress: 0.44
translated_text: Ang rehiyon ng Bordeaux ay gumagawa ng magagandang red wine | Gumagawa sila ng magandang ham sa Parma | Nagtatanim kami ng trigo dito | Nag-aalaga kami ng baboy dito
Progress: 0.44
translated_text: isang agraryo (o agrikultural) na lipunan | pamayanan ng pagsasaka
Progress: 0.44
translated_text: Sumang-ayon kami sa mga tuntunin ng pag-areglo | Hindi ako makakasang-ayon sa iyo! | hawak ko ang mga nagsasabing sagrado ang buhay | Ang dalawang pilosopo ay nagkakasundo sa puntong ito
Progress: 0.44
translated_text: Pumayag siya sa lahat ng kondisyon ko | Pumayag siyang iwan siya
Progress: 0.44
translated_text: Ang dalawang kuwento ay hindi magkasundo sa maraming detalye | Sinusuri ng sulat-kamay ang pirma sa tseke | Hindi tugma ang fingerprints ng suspek sa nasa baril
Progress: 0.44
translated_text: Ang mga kulay ay hindi nagkakasundo | Ang kanilang mga ideya ay nagkakasundo
Progress: 0.44
translated_text: Ang mga kulay na ito ay nakalulugod sa mga pandama | isang kasiya-siyang sensasyon
Progress: 0.44
translated_text: isang kasiya-siyang balita | kaaya-aya sa ugali at hitsura
Progress: 0.44
translated_text: ang pasyenteng ito ay nagbibigay ng tipikal na halimbawa ng sindrom | may isang halimbawa sa pahina 10
Progress: 0.44
translated_text: kinatawan ng moviegoers | isang kinatawan ng modernong dula
Progress: 0.44
translated_text: ang pasyenteng ito ay nagbibigay ng tipikal na halimbawa ng sindrom | may isang halimbawa sa pahina 10
Progress: 0.44
translated_text: kinatawan ng moviegoers | isang kinatawan ng modernong dula
Progress: 0.44
translated_text: ang Central Intelligence Agency | ang Census Bureau | Opisina ng Pamamahala at Badyet | Tennessee Valley Authority
Progress: 0.44
translated_text: ang ahensya ng Providence | may free agency siya
Progress: 0.44
translated_text: isang paraan ng kontrol | isang halimbawa ay ang pinakamahusay na ahensya ng pagtuturo | ang tunay na daan tungo sa tagumpay
Progress: 0.44
translated_text: isang sangay ng Kongreso | ang botany ay isang sangay ng biology | ang Germanic na sangay ng Indo-European na mga wika
Progress: 0.44
translated_text: ang braso ng record player | isang braso ng dagat | isang sangay ng imburnal
Progress: 0.45
translated_text: ang Central Intelligence Agency | ang Census Bureau | Opisina ng Pamamahala at Badyet | Tennessee Valley Authority
Progress: 0.45
translated_text: ang ahensya ng Providence | may free agency siya
Progress: 0.45
translated_text: isang paraan ng kontrol | isang halimbawa ay ang pinakamahusay na ahensya ng pagtuturo | ang tunay na daan tungo sa tagumpay
Progress: 0.45
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.45
translated_text: Sinibak ng amo ang kanyang sekretarya ngayon | Tinapos ng kumpanya ang 25% ng mga manggagawa nito
Progress: 0.45
translated_text: Napatunayang tama siya | Ang gamot pala ay nagligtas sa kanyang buhay | Siya ay naging HIV positive
Progress: 0.45
translated_text: Ipinakita ng eksperimento ang kawalang-tatag ng tambalang | Ipinakita ng mathematician ang bisa ng haka-haka
Progress: 0.45
translated_text: Ang pagsusuri sa dugo ay nagpakita na siya ang ama | Ang kanyang pag-uugali ay nagpapatunay sa kanyang kawalan ng kakayahan
Progress: 0.45
translated_text: Ang diskarte na ito ay sinubukan na may magagandang resulta | Subukan ang recipe na ito
Progress: 0.45
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.45
translated_text: kulang siya sa pundasyong kailangan para sa advanced na pag-aaral | isang magandang saligan sa matematika
Progress: 0.45
translated_text: inaabangan niya ang kanyang pagsisimula bilang isang may sapat na gulang | ang pundasyon ng isang bagong siyentipikong lipunan

Progress: 0.45
translated_text: magiliw na payo | isang magiliw na kapitbahayan | ang tanging palakaibigang tao dito | isang magiliw na host at hostess
Progress: 0.45
translated_text: isang pamahalaang magiliw sa ating mga interes | isang mapayapang kasunduan
Progress: 0.45
translated_text: user-friendly na mga computer | isang patakarang magiliw sa mamimili | isang nobelang madaling mambabasa
Progress: 0.45
translated_text: sa mapagkaibigang teritoryo | siya ay aksidenteng napatay sa pamamagitan ng friendly fire
Progress: 0.45
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.45
translated_text: Natutulog ang estudyanteng ito sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.45
translated_text: mapagmahal na magulang | mapagmahal na mga tingin
Progress: 0.45
translated_text: Ang tindero ay agresibong itinutulak ang bagong modelo ng computer | Ang kumpanya ay labis na nag-a-advertise ng kanilang mga bagong laptop
Progress: 0.45
translated_text: Ang Rhode Island ay may dalawang karatig na estado; Massachusetts at Conncecticut | ang panig ng Germany na katapat ng France | Utah at ang magkadikit na estado ng Idaho | mga kalapit na lungsod
Progress: 0.45
translated_text: nagkaroon ng mga katabing silid | sa susunod na silid | yung taong nakaupo sa tabi ko | magkatabi ang mga kwarto namin
Progress: 0.45
translated_text: Ang Rhode Island ay may dalawang karatig na estado; Massachusetts at Conncecticut | ang panig ng Germany na katapat ng France | Utah at ang magkadikit na estado ng Idaho | mga kalapit na lungsod
Progress: 0.45
translated_text: lupaing katabi ng mga bundok | New York at mga katabing lungsod
Progress: 0.45
translated_text: ang mga kasosyo ay natuwa sa pagkilala sa kanilang trabaho | tila iniiwasan niya ang paraan ng pagkilala o pagkilala sa gawaing pambabae bago ang kanyang sarili
Progress: 0.45
translated_text: isang politiko na ang paggunita ng mga pangalan ay kapansin-pansin gaya ng kanyang pagkilala sa mga mukha | Sinusukat ng mga eksperimentong sikologo ang lumipas na oras mula sa simula ng stimulus hanggang sa pagkilala nito ng nagmamasid
Progress: 0.45
translated_text: bigyan siya ng pagkilala sa pagsubok | binigyan siya ng kredito para sa kanyang trabaho | bigyan siya ng kredito sa pagsubok
Progress: 0.45
translated_text: isang lumalagong pagsasakatuparan ng panganib na kasangkot | isang biglaang pagkilala sa problemang kanyang kinaharap | pagtaas ng pagkilala na ang diabetes ay madalas na kasama ng iba pang mga malalang sakit
Progress: 0.45
translated_text: Nahihirapan akong maalala ang mga pangalan ng lahat ng aking mga kakilala | kaibigan tayo ng pamilya
Progress: 0.45
translated_text: Nahihirapan akong maalala ang mga pangalan ng lahat ng aking mga kakilala | kaibigan tayo ng pamilya
Progress: 0.45
translated_text: nakuha niya ang isang reputasyon bilang isang artista bago siya nagsimulang magsulat | siya ay isang tao ng masamang ulat
Progress: 0.45
translated_text: payagan mo akong ipakilala sa iyo ang aking anak | ipakilala ang mga bagong kapitbahay sa komunidad
Progress: 0.45
translated_text: Nagdala siya ng bagong judge | Isang masamang tsismis ang ipinakilala ng bagong kalihim
Progress: 0.45
translated_text: magpakilala ng panuntunan | ipakilala ang mga kakaibang prutas
Progress: 0.45
translated_text: Palagi niyang inuunahan ang kanyang mga lektura na may biro | Pinauna niya ang kanyang panayam sa isang kritikal na pahayag tungkol sa institusyon
Progress: 0.45
translated_text: Pinahihintulutan nito ang tubig na dumaloy sa | Ang selyadong pinto na ito ay hindi papayag na pumasok ang tubig sa basement | Papayagan nito ang pag-ulan
Progress: 0.45
translated_text: Pinayagan niya ang kanyang anak na bisitahin ang kanyang nawalay na asawa | Hindi ko hahayaang hanapin ng mga pulis ang kanyang basement | Hindi ako papayag na makita mo ang iyong pagsusulit
Progress: 0.45
translated_text: Nakuha niya ang kanyang squad sa bola | Pinapasok ako nito para sa isang malaking sorpresa | May dinadala siyang babae sa gulo
Progress: 0.45
translated_text: ang tibo ng kamatayan | naramdaman niya ang pagtusok ng mga kulitis
Progress: 0.45
translated_text: Inipit nila sa akin ang bill ng hapunan | Nasaktan ako ng malaking singil sa buwis
Progress: 0.45
translated_text: Sinaktan niya ako nang hindi niya ako isinama sa kanyang mga bisita | Ang pananalitang ito ay talagang nabugbog ang aking ego
Progress: 0.45
translated_text: inaalagaan ang kanyang sugatang braso | ambulansya...para sa mga nasaktang lalaki at babae
Progress: 0.45
translated_text: magtipon ng ilang mga bato | pagsamahin ang iyong mga iniisip
Progress: 0.45
translated_text: Nagtipon kami sa basement ng simbahan | Magtipon tayo sa dining room
Progress: 0.45
translated_text: Ang mga journal ay nag-iipon sa aking opisina | Ang trabaho ay patuloy na tumatambak
Progress: 0.45
translated_text: tipunin ang iyong mga kasamahan | pagsama-samahin ang lahat ng mga interesado sa proyekto | tipunin ang malalapit na miyembro ng pamilya
Progress: 0.45
translated_text: ang kilusang pangkapayapaan ay nakakuha ng momentum | ang kotse ay nagtitipon ng bilis
Progress: 0.45
translated_text: Medyo iba ang tingin niya sa akin | I consider her to be shallow | Hindi ko masyadong nakikita ang sitwasyon na negatibo tulad ng nakikita mo
Progress: 0.45
translated_text: Kunin ang kaso ng China | Isaalang-alang ang sumusunod na kaso
Progress: 0.45
translated_text: Dapat mong isaalang-alang ang kanyang edad | Itinuring ng hukom ang kabataan ng nagkasala at naging maluwag
Progress: 0.46
translated_text: Isinaalang-alang nila ang posibilidad ng isang welga | Ibalik ang panukala sa iyong isipan
Progress: 0.46
translated_text: Sa tingin ko siya ay napakatalino | Naniniwala ako na siya ay napakatalino | Sa tingin ko boyfriend niya | Iniisip ng racist na ang mga taong ito ay mababa
Progress: 0.46
translated_text: Ang iyong pangangailangang matulog ng huli ay hindi dahilan ng iyong late na pagdating sa trabaho | Ang kanyang kamakailang diborsyo ay maaaring ipaliwanag ang kanyang pag-aatubili na makipag-date muli
Progress: 0.46
translated_text: dahil dito, hindi niya ginawa ito | patuloy na nagkaroon ng matinding pananakit ng ulo at naaayon ay bumalik sa doktor
Progress: 0.46
translated_text: ang integridad ng nervous system ay kinakailangan para sa normal na pag-unlad | gumawa siya ng mga hakbang upang masiguro ang pagkakaisa ng teritoryo ng Croatia
Progress: 0.46
translated_text: mayroon siyang isa ngunit kakailanganin ng dalawa at tatlo upang sumama dito | nag-lunch sila sa isa
Progress: 0.46
translated_text: Sundin ang mga utos | ipagdiwang ang Pasko | Obserbahan ang Yom Kippur
Progress: 0.46
translated_text: Ipinagdiriwang nila ang patriarch ng pamilya | Pagkatapos ng pagsusulit, nagdiwang ang mga estudyante
Progress: 0.46
translated_text: Ang direktor ng pelikula ay ipinagdiwang sa buong Hollywood | Ang tenor ay lionized sa Vienna
Progress: 0.46
translated_text: ang pagkapanalo sa lotto ay isang masayang aksidente | ang pagbubuntis ay isang stroke ng malas | ito ay dahil sa isang aksidente o kapalaran
Progress: 0.46
translated_text: kakulangan ng pondo ay nagresulta sa isang sakuna para sa ating sistema ng paaralan | ang kanyang mga patakaran ay isang kalamidad
Progress: 0.46
translated_text: ang buong lungsod ay naapektuhan ng hindi maaalis na kalamidad | ang lindol ay isang kalamidad
Progress: 0.46
translated_text: makarating sa punto | namiss niya yung point ng joke | nawalan na ng saysay ang buhay
Progress: 0.46
translated_text: ilan sa mga detalye ay magkatulad | isang punto ng impormasyon
Progress: 0.46
translated_text: isang kahanga-hangang antas ng pagiging prangka | sa anong yugto ang mga agham panlipunan?
Progress: 0.46
translated_text: isang hilera ng mga puntos | gumuhit ng mga linya sa pagitan ng mga tuldok
Progress: 0.46
translated_text: umiskor siya ng 20 puntos sa unang kalahati | ang touchdown ay nagbibilang ng 6 na puntos
Progress: 0.46
translated_text: napansin niya ang isang item sa New York Times | mayroon siyang ilang mga item sa kanyang listahan ng pamimili | ang pangunahing punto sa agenda ay kinuha muna

Progress: 0.46
translated_text: idinikit niya ang dulo ng kutsilyo sa isang puno | sinira niya ang punto ng kanyang lapis
Progress: 0.46
translated_text: Ipinakita ko sa customer ang glove section | Tinuro niya ang bakanteng parking space | ipinahiwatig niya ang kanyang mga kalaban
Progress: 0.46
translated_text: Ang weather vane ay tumuturo sa North | itinuro palabas ang mga daliri ng mga mananayaw
Progress: 0.46
translated_text: tumutok ng baril | Itinutok niya sa akin ang kanyang armas
Progress: 0.46
translated_text: Ang mga sintomas na ito ay nagpapahiwatig ng isang malubhang sakit | Ang kanyang pag-uugali ay tumuturo sa isang malubhang neurosis | Ang mga tagapagpahiwatig ng ekonomiya ay nagpapahiwatig na ang euro ay undervalued
Progress: 0.46
translated_text: Itinutok niya ang kanyang mga kamao sa mukha ng kanyang kalaban | pamumuna nakadirekta sa kanyang superior | idirekta ang iyong galit sa iba, hindi sa iyong sarili
Progress: 0.46
translated_text: binigyan niya ng tiwala ang tsismis | Ang pagtanggap ng Newtonian mechanics ay hindi pinag-aalinlanganan sa loob ng 200 taon
Progress: 0.46
translated_text: pag-aampon nito ng lipunan | malawak na tinanggap ang panukala
Progress: 0.46
translated_text: ang kanyang pagtanggap sa regalo ay nagpasigla sa kanya | inasahan niya ang kanilang pagtanggap sa kanyang alok
Progress: 0.46
translated_text: Sumang-ayon kami sa mga tuntunin ng pag-areglo | Hindi ako makakasang-ayon sa iyo! | hawak ko ang mga nagsasabing sagrado ang buhay | Ang dalawang pilosopo ay nagkakasundo sa puntong ito
Progress: 0.46
translated_text: Pumayag siya sa lahat ng kondisyon ko | Pumayag siyang iwan siya
Progress: 0.46
translated_text: Ang dalawang kuwento ay hindi magkasundo sa maraming detalye | Sinusuri ng sulat-kamay ang pirma sa tseke | Hindi tugma ang fingerprints ng suspek sa nasa baril
Progress: 0.46
translated_text: Ang mga kulay ay hindi nagkakasundo | Ang kanilang mga ideya ay nagkakasundo
Progress: 0.46
translated_text: Hindi ko matatanggap ang iyong imbitasyon | Pupunta ako para sa resolusyong ito
Progress: 0.46
translated_text: ang kanyang ama ay lubhang mayaman | maraming magiliw na pag-asa ang naka-pin sa mayayamang tiyuhin
Progress: 0.46
translated_text: biniyayaan ng lupaing mayaman sa mineral | mayaman sa ideya | mayaman sa kultural na interes
Progress: 0.46
translated_text: matabang lupang sakahan | isang matabang lupain | isang produktibong ubasan | mayamang lupa
Progress: 0.46
translated_text: malalim na lila | isang mayaman na pula
Progress: 0.46
translated_text: isang mayamang ugat ng tanso | isang masaganang halo ng gas
Progress: 0.46
translated_text: masaganang dessert | patuloy silang nagugutom sa masaganang pagkain
Progress: 0.46
translated_text: isang rich ruby port | full-bodied na alak | isang matatag na claret | ang matibay na lasa ng sariwang brewed na kape
Progress: 0.46
translated_text: nagkaroon ng sapat na pagkain para sa party | napakaraming probisyon | sagana ang pagkain | isang masaganang ani ng ubas | isang mayamang supply
Progress: 0.46
translated_text: she told a funny story | gumawa siya ng isang nakakatawa
Progress: 0.46
translated_text: isang nakakatuwang pelikula na may tuluy-tuloy na mga kalokohan at kalokohan | isang nakakatuwang kapwa | isang comic hat | isang nakakatawang hitsura ng sorpresa | mga nakakatawang kwento na nagpatawa sa lahat | isang napaka nakakatawang manunulat | katawa-tawa sana kung hindi lang masakit | isang masayang karanasan | riible courtroom kalokohan
Progress: 0.46
translated_text: isang kakaibang hybrid accent | ang kanyang pananalita ay may nakakatawang twang | mayroon silang ilang mga nakakatawang ideya tungkol sa digmaan | nagkaroon ng kakaibang pangalan | ang kakaibang mabangong amoy ng mga clove | tiyak na kakaiba sa bayang ito | what a rum fellow | iisang pag-uugali
Progress: 0.46
translated_text: may kakaiba sa aksidente | hanggang sa ilang nakakatawang negosyo | ilang mga tiyak na kakaibang nangyayari | isang makulimlim na deal | ang kanyang motibo ay pinaghihinalaan | kahina-hinalang pag-uugali
Progress: 0.46
translated_text: Iwasan natin ang komprontasyon | humarap sa isang paghaharap | umiwas sa welga
Progress: 0.46
translated_text: Pinipigilan niyang tawagan ang kanyang therapist nang madalas | Dapat niyang iwasang ilathala ang mga alaala ng kanyang asawa
Progress: 0.46
translated_text: Iniiwasan ko ang mga droga | Sa panahon ng Ramadan, iniiwasan ng mga Muslim ang tabako sa araw
Progress: 0.46
translated_text: Ang kontrata ay pinawalang-bisa | magpawalang-bisa sa isang pakiusap
Progress: 0.46
translated_text: Ang espongha ay sumisipsip ng tubig nang maayos | Siya ay nakakuha ng lakas mula sa mga salita ng ministro
Progress: 0.46
translated_text: sipsipin ang lason mula sa lugar na kinagat ng ahas | pagsuso sa isang dayami | sinipsip ng sanggol ang dibdib ng ina
Progress: 0.47
translated_text: Ang espongha ay sumisipsip ng tubig nang maayos | Siya ay nakakuha ng lakas mula sa mga salita ng ministro
Progress: 0.47
translated_text: Pinasuso ng wetnurse ang sanggol | Hindi mo maaaring alagaan ang iyong sanggol sa publiko sa ilang lugar
Progress: 0.47
translated_text: medyo masarap | malapit na | medyo may sakit | lubos na mayaman
Progress: 0.47
translated_text: tama ka | medyo nag-iisa siya | ay medyo nagkakamali | medyo kabaligtaran | hindi pa tapos | hindi ito lubos na nagawa
Progress: 0.47
translated_text: ang kanyang tagumpay ay medyo bagay | medyo babae siya | medyo isang pelikula | medyo lakad | medyo hapon na kami
Progress: 0.47
translated_text: ay medyo biglaang pagbabago | ito ang bagay na dapat gawin | medyo ang galit | Kaya lang!
Progress: 0.47
translated_text: ang kotse ay isang kabuuang pagkawala | ang pagkawala ng mga alagang hayop ay nagdulot ng pagkabangkarote ng rantsero
Progress: 0.47
translated_text: pagbaba ng timbang | isang malubhang pagkawala ng negosyo
Progress: 0.47
translated_text: ang kanyang pagkawala ng kredibilidad ay humantong sa kanyang pagbibitiw | ang pagkawala sa kanya ay hindi malaking kawalan
Progress: 0.47
translated_text: lugi ang kumpanya noong nakaraang taon | ang kumpanya ay nagpapatakbo sa pula noong nakaraang taon
Progress: 0.47
translated_text: siya ay nagpasya na pumunta sa Chicago sa spur of the moment | napaisip siya bigla
Progress: 0.47
translated_text: paikliin ang palda | paikliin ang lubid ng ilang pulgada
Progress: 0.47
translated_text: Nabigo siyang mapansin na wala na ang kanyang anak sa kanyang kuna | Nabigo ang sekretarya na tawagan ang customer at nawala ang account ng kumpanya
Progress: 0.47
translated_text: Saan bagsak ang mga pampublikong paaralan ngayon? | Ang pagtatangkang iligtas ang mga hostage ay nabigo nang husto
Progress: 0.47
translated_text: Nabigo siya sa kanyang pang-amoy sa pagkakataong ito | Ang kanyang lakas sa wakas ay nabigo sa kanya | Nabigo siya ng kanyang mga anak sa krisis
Progress: 0.47
translated_text: Ang makina sa wakas ay umalis | Namatay ang sasakyan sa kalsada | Nasira ang bus na sinakyan namin habang papunta sa bayan | Nasira ang coffee maker | Nabigo ang makina habang papunta sa bayan | ang kanyang paningin ay lumipad pagkatapos ng aksidente
Progress: 0.47
translated_text: Nag-aral siya ng mabuti ngunit nabigo pa rin | Nabigo ba ako sa pagsusulit?
Progress: 0.47
translated_text: Nabigo siya sa kanyang mga obligasyon bilang isang mabuting manugang | Hindi natin dapat pabayaan ang kanyang obligasyon sa mga biktima ng Holocaust
Progress: 0.47
translated_text: Ang kumpanya ng laruan ay nabangkarote matapos ang kumpetisyon ay umupa ng murang Mexican labor | Ilang mga bangko ang nabigo sa taong iyon
Progress: 0.47
translated_text: Binawi niya ang pagbabawal sa paninigarilyo | alisin ang isang embargo | lisanin ang hatol ng kamatayan
Progress: 0.47
translated_text: isa lang alisin sa kabaliwan | ginagaya nito sa marami ang nag-aalis ng isang trahedya ni Shakespeare
Progress: 0.47
translated_text: alisin ang isang banta | alisin ang isang wrapper | Alisin ang maruruming pinggan sa mesa | kunin mo ang baril sa iyong bulsa | Ang makinang ito ay nag-aalis ng init mula sa kapaligiran
Progress: 0.47
translated_text: Tanggalin ang mga lumang sapatos na ito! | Inalis ng kumpanya ang lahat ng patay na kahoy

Progress: 0.47
translated_text: Inalis niya ang kanyang mga anak sa kanayunan | Alisin ang mga tropa sa kagubatan na nakapalibot sa lungsod | alisin ang isang kaso sa ibang hukuman
Progress: 0.47
translated_text: Ang pagkamatay ng kanyang ina ay nagtanggal ng huling hadlang sa kanilang pagsasama | Inaalis ng Diyos ang iyong mga kasalanan
Progress: 0.47
translated_text: ang ideya ay napakalinaw | hindi kailanman naging masaya | Mahal na mahal kita | sobrang sakit ng ulo ko!
Progress: 0.47
translated_text: pinagmasdan niya ang mga ahas upang mailarawan niya ang kanilang pag-uugali | yumuko siya para kunin ang sombrero niya
Progress: 0.47
translated_text: Masaya sila at sana mananatili silang ganyan | kaya mabuhay ang iyong buhay na ang pagtanda ay hindi magdadala ng pagsisisi
Progress: 0.47
translated_text: Hanggang dito na lang ang kaya kong gawin sa estudyanteng ito | marami lang kayang gawin sa isang araw
Progress: 0.47
translated_text: Na-offend ako at ganun din siya | nagtrabaho nang husto at gayon din siya
Progress: 0.47
translated_text: hawakan ang brush kaya | itakda ang mga piraso sa gayon
Progress: 0.47
translated_text: pagod na pagod na halos hindi na siya makatayo | sobrang dumi kaya amoy
Progress: 0.47
translated_text: tapos umalis na siya | pumunta muna sa kaliwa, pagkatapos ay sa kanan | unang dumating ang kidlat, pagkatapos ay kulog | nanood kami ng late movie tapos natulog na | at kaya umuwi at matulog
Progress: 0.47
translated_text: samakatuwid ang X ay dapat na totoo | ang mga itlog ay sariwa at samakatuwid ay kasiya-siya | bata pa kami at mula noon ay optimistic | gabi na kaya dapat tayong pumunta | may kinikilingan ang saksi kaya hindi mapagkakatiwalaan
Progress: 0.47
translated_text: masisira daw ang sasakyan at talagang | napakalamig talaga | ay talagang nagpapasalamat | sa katunayan, ang ulan ay maaaring dumating pa rin | ginawa niya kaya gawin ito!
Progress: 0.47
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.47
translated_text: naghihintay na mga kotse at limousine na nakahanay sa gilid ng bangketa | natagpuan ang kanyang ina na naghihintay sa kanila | isang kahanga-hangang hanay ng mga pagkaing handa at naghihintay para sa mga bisita | handa at naghihintay ang mga pwersang militar
Progress: 0.47
translated_text: siya ay isang modelo ng magalang na pagpigil | hindi siya nawalan ng kontrol sa sarili
Progress: 0.47
translated_text: legal na pagpigil | mga pagpigil na ipinataw sa mga pag-import
Progress: 0.47
translated_text: Nagbakante siya ng posisyon nang siya ay nabuntis | Nagbitiw ang chairman nang mapag-alamang may misappropriated na pondo
Progress: 0.47
translated_text: Ang Kalihim ng Navy ay aalis sa opisina sa susunod na buwan | Nagbitiw ang chairman dahil sa iskandalo sa pananalapi
Progress: 0.47
translated_text: Ibinibigay ko ang aking silid sa pangmatagalang panauhin sa bahay | magbitiw sa pag-angkin sa trono
Progress: 0.47
translated_text: Bumagsak siya sa kama | Napaupo siya sa upuan
Progress: 0.47
translated_text: lihim na nagkita upang talakayin ang mga plano sa pagsalakay | palihim na nanunuod ng sine ang mga bata nang sila ay nasa library | nag-ayos sila ng lihim na pagkikita
Progress: 0.47
translated_text: lihim silang natuwa sa kanyang kahihiyan | umaasang lihim na magbago ang isip niya
Progress: 0.47
translated_text: ayaw niyang pag-usapan ang paksang iyon | ito ay isang napakasensitibong paksa | ang kanyang mga sulat ay laging may temang pag-ibig
Progress: 0.47
translated_text: ang tema ay inihayag sa mga unang hakbang | kinuha ng accompanist ang ideya at inilarawan ito
Progress: 0.47
translated_text: hindi namin naintindihan ang kanyang motibasyon | kumilos siya nang may pinakamahusay na motibo
Progress: 0.47
translated_text: isang motibong puwersa | lakas ng motibo | enerhiya ng motor
Progress: 0.47
translated_text: maaaring ito ay ang etikal na wika ay pangunahing may motivative function | motibo pakiusap | nag-uudyok na mga argumento
Progress: 0.48
translated_text: ang mga runner ay lumabas mula sa mga puno patungo sa kanyang malinaw na paningin | nagkaroon siya ng visual na sensasyon ng matinding liwanag
Progress: 0.48
translated_text: tanyag na imahinasyon ay lumikha ng isang mundo ng mga demonyo | Ang imahinasyon ay nagpapakita kung ano ang maaaring maging mundo
Progress: 0.48
translated_text: ang pampulitikang larawan ay paborable | ang relihiyosong tanawin sa England ay nagbago noong nakaraang siglo
Progress: 0.48
translated_text: nagkaroon siya ng fit | she threw a tantrum | gumawa siya ng eksena
Progress: 0.48
translated_text: nagpinta siya ng mga eksena mula sa pang-araw-araw na buhay | Ang figure 2 ay nagpapakita ng photographic at schematic view ng kagamitan
Progress: 0.48
translated_text: idikit ang karatula sa dingding | gupitin at idikit ang pangungusap sa teksto
Progress: 0.48
translated_text: isang eksibisyon ng sining | isang magandang koleksyon ng sining
Progress: 0.48
translated_text: hindi kailangang maging makabago ang sining para maging mahusay | Hindi ako kailanman magaling sa sining | sinabi niya na ang arkitektura ay ang sining ng pag-aaksaya ng espasyo nang maganda
Progress: 0.48
translated_text: ang sining ng pakikipag-usap | ito ay medyo isang sining
Progress: 0.48
translated_text: ang pagmamataas at kawalan ng panlasa ay nag-ambag sa kanyang mabilis na tagumpay | ang magtanong sa partikular na oras na iyon ay ang panghuli sa masamang lasa
Progress: 0.48
translated_text: ang kanyang salaysay ay kawili-wili | Ang mga kuwento ng Disney ay nakakaaliw sa mga matatanda pati na rin sa mga bata
Progress: 0.48
translated_text: isang kasaysayan ng France | nagbigay siya ng hindi tumpak na salaysay tungkol sa balak na patayin ang pangulo | ang kwento ng exposure sa lead
Progress: 0.48
translated_text: ang ulat ng kanyang talumpati | ang kwento ay nasa 11 o&#39;clock news | ang ulat ng kanyang talumpati na ibinigay sa balita sa gabi ay nagpagalit sa gobernador
Progress: 0.48
translated_text: sinabi niya sa isang fib tungkol sa pagkain ng kanyang kangkong | paano ko mapipigilan ang aking anak na magkwento?
Progress: 0.48
translated_text: Ipinahayag niya ang kanyang galit | Nagsalita siya ng sumpa
Progress: 0.48
translated_text: Isang malaking mabigat na buntong-hininga ang pinakawalan niya | Nagsalita siya ng mga kakaibang tunog na hindi maintindihan ng sinuman
Progress: 0.48
translated_text: Siya ay nagsasalita ng maraming kalokohan | Ang depress na pasyente na ito ay hindi nagsasalita
Progress: 0.48
translated_text: isang arrant tanga | isang ganap na duwag | isang ganap na tanga | isang kontrabida na may dobleng tinina | matinding kapabayaan | isang perpektong idiot | puro katangahan | anong gulo | stark staring mad | isang masinsinang kontrabida | walang kwentang salita | ang walang halong katotohanan
Progress: 0.48
translated_text: dumating sa isang patay na paghinto | lubos na pagkaseryoso
Progress: 0.48
translated_text: Binibigkas niya ang mga salitang Pranses sa isang nakakatawang paraan | Hindi ko masasabing `zip wire&#39; | Maaari bang iparinig ng bata ang masalimuot na salitang ito?
Progress: 0.48
translated_text: nakataas na ang anchor | sumisikat ang araw | humiga siya ng mukha | siya ay nakasangla | ang merkado ay up | ang mais ay up
Progress: 0.48
translated_text: nagkakagulo na ba sila? | gising ng pito tuwing umaga
Progress: 0.48
translated_text: ito ay isang up market | isang pagpapabuti ng ekonomiya
Progress: 0.48
translated_text: ang pataas na hagdanan | isang pangkalahatang pataas na paggalaw ng isda
Progress: 0.48
translated_text: siya ay nasa kanyang takdang-aralin | kailangang maging up para sa laro
Progress: 0.48
translated_text: tumingin sa taas! | lumakas ang musika | ang mga pira-piraso ay lumipad paitaas | tumaas ang presyo | pataas na mobile
Progress: 0.48
translated_text: ay inilipat sa punong-tanggapan | hanggang Canada para magbakasyon
Progress: 0.48
translated_text: inilipat nila ang petsa ng pagpupulong | mula pagkabata pataas
Progress: 0.48
translated_text: Ang tagapagsalita na ito ay nag-uutos ng mataas na bayad | Ang may-akda ay nag-uutos ng isang patas na pagdinig mula sa kanyang mga mambabasa

Progress: 0.48
translated_text: kontrolin ang badyet | Command ang pwersang militar
Progress: 0.48
translated_text: Pinuna ng papel ang bagong pelikula | Huwag itumba ang pagkain--libre ito
Progress: 0.48
translated_text: isang kahanga-hangang tanawin | ang ganoong poise ay singular sa isang napakabata
Progress: 0.48
translated_text: isang kakaibang hybrid accent | ang kanyang pananalita ay may nakakatawang twang | mayroon silang ilang mga nakakatawang ideya tungkol sa digmaan | nagkaroon ng kakaibang pangalan | ang kakaibang mabangong amoy ng mga clove | isang bagay na tiyak na kakaiba tungkol sa bayang ito | what a rum fellow | iisang pag-uugali
Progress: 0.48
translated_text: mauunawaan ba ang iisang tao bukod sa kanyang kultura? | bawat katotohanan sa mundo ay maaaring isahan...hindi katulad ng iba pang katotohanan at nag-iisang uri nito
Progress: 0.48
translated_text: isang natatanging halimbawa | ang natatanging umiiral na halimbawa ng sulat-kamay ni Donne | isang natatanging kopya ng isang sinaunang manuskrito | may mga natatanging solusyon ang ilang uri ng problema
Progress: 0.48
translated_text: may mga limitasyon sa halagang maaari mong taya | ito ay mabilis na lumalaki nang walang limitasyon sa paningin
Progress: 0.48
translated_text: isang hilera ng mga puntos | gumuhit ng mga linya sa pagitan ng mga tuldok
Progress: 0.48
translated_text: na-save ng kampana | narinig niya ang kalayuan ng mga kampana ng simbahan
Progress: 0.48
translated_text: ang timbre ng kanyang soprano ay mayaman at kaibig-ibig | ang mga muffled na tono ng sirang kampana ay nagpatawag sa kanila upang magkita
Progress: 0.48
translated_text: Naglayag siya sa kanyang mga pagsusulit | Dadaan ka with flying colors | Nakuha niya ang kanyang kursong astrophysics
Progress: 0.48
translated_text: matukoy mo ba ang posisyon ng kalaban? | Hindi matukoy ng mga chemist ang pagkakakilanlan ng chromosome
Progress: 0.48
translated_text: Ang lobo ay tumaas sa ibabaw | ginawang takong ng hangin ang sisidlan | Nakalista ang barko sa starboard
Progress: 0.48
translated_text: pinatalas ng pangalawang baseman ang kanyang mga spike bago ang bawat laro | Sinisira ng mga spike ng golfers ang putting greens
Progress: 0.48
translated_text: Naghintay ako ng ilang araw para sa kanyang sagot | sumulat siya ng mga tugon sa ilan sa kanyang mga kritiko
Progress: 0.48
translated_text: sila ay nagsisikap na makahanap ng mapayapang solusyon | ang mga sagot ay nasa likod ng libro | kinalkula niya ang resulta sa apat na decimal na lugar
Progress: 0.48
translated_text: ang sagot niya sa anumang problema ay magpakalasing | ang sagot nila ay idemanda ako
Progress: 0.48
translated_text: Ayaw niyang sumagot | sagutin ang tanong | Sumagot kami na tatanggapin namin ang imbitasyon
Progress: 0.48
translated_text: sagutin ang pinto | sagutin ang telepono
Progress: 0.48
translated_text: sagutin ang isang tanong | sagutin mo ang bugtong
Progress: 0.48
translated_text: Ang ilang mga salita ay sasagot | Ang kotseng ito ay angkop sa aking layunin | Magagawa ba ang $100? | Hindi sapat ang gradong &#39;B&#39; para makapasok ako sa medikal na paaralan | Wala nang ibang magsisilbi
Progress: 0.48
translated_text: Iniisip ko na kumita siya ng maraming pera sa kanyang bagong nobela | Naisip kong hanapin siya sa masamang kalagayan | hindi niya naisip na hanapin siya sa kusina | Galit yata siya sa akin dahil pinatayo ko siya
Progress: 0.49
translated_text: I am guessing na tataas na naman ang presyo ng real estate | Hindi ko masasabing mali ka
Progress: 0.49
translated_text: ang pag-master ng pangalawang wika ay nangangailangan ng maraming trabaho | walang mga paaralan ang nag-aalok ng graduate na pag-aaral sa interior design
Progress: 0.49
translated_text: sa anong disiplina ang kanyang pagkadoktor? | ang mga guro ay dapat na bihasa sa kanilang paksa | ang antropolohiya ay ang pag-aaral ng tao
Progress: 0.49
translated_text: pag-aralan ang isang soneto ni Shakespeare | pag-aralan ang ebidensya sa isang kriminal na paglilitis | pag-aralan ang iyong tunay na motibo
Progress: 0.49
translated_text: Siya ay nag-aaral ng geology sa kanyang silid | May pagsusulit ako sa susunod na linggo; Kailangan kong pindutin ang mga libro ngayon
Progress: 0.49
translated_text: paulit-ulit na pagkopya ay humahantong sa pagpaparami ng mga error | ang pagpaparami ng mga cell na ito ay isang natural na kaugnayan ng paglaki
Progress: 0.49
translated_text: ang pagpaparami ng apat sa tatlo ay nagbibigay ng labindalawang | apat na beses tatlo ay katumbas ng labindalawa
Progress: 0.49
translated_text: maaaring isama ng mga teorya ang mga katotohanan at batas at nasubok na mga hypotheses | totoo sa katotohanan at teorya
Progress: 0.49
translated_text: isang siyentipikong hypothesis na nakaligtas sa eksperimentong pagsubok ay naging isang siyentipikong teorya | iminungkahi niya ang isang sariwang teorya ng alkalis na kalaunan ay tinanggap sa mga kemikal na kasanayan
Progress: 0.49
translated_text: ang arkitekto ay may teorya na mas marami ay mas mababa | pinatay nila siya sa teorya na walang sinasabi ang mga patay na tao
Progress: 0.49
translated_text: binayaran niya ang kanyang bill at umalis | padalhan ako ng account kung ano ang utang ko
Progress: 0.49
translated_text: Sisingilin ba ako para sa serbisyong ito? | Sinisingil kami ng 4 na gabi sa hotel, bagaman nag-stay lang kami ng 3 gabi
Progress: 0.49
translated_text: ito ay kasing ganda ng ginto | isang hiling na katumbas ng isang utos | ang kanyang pahayag ay katumbas ng pag-amin ng pagkakasala
Progress: 0.49
translated_text: ang welga ay suportado ng ranggo at file ng unyon | tumaas siya mula sa hanay upang maging koronel
Progress: 0.49
translated_text: poll nila ang kanilang membership | natagpuan nila ang hindi pagkakaunawaan sa kanilang sariling hanay | sumapi siya sa hanay ng mga walang trabaho
Progress: 0.49
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.49
translated_text: isang umiiyak na kahihiyan | isang matinding kasinungalingan | lantarang paglabag sa karapatang pantao | isang nakasisilaw na error | matinding kawalan ng kakayahan | matinding kawalan ng katarungan | pagtataksil sa ranggo
Progress: 0.49
translated_text: ganap na kalayaan | isang ganap na dimwit | isang ganap na kasinungalingan | out-and-out na labanan | isang out-and-out na kasinungalingan | isang ranggo na tagalabas | maraming right-down na bisyo | nakuha ang trabaho sa pamamagitan ng matinding pagtitiyaga | puro katangahan
Progress: 0.49
translated_text: gusto niyang maramdaman ang isang bahagi ng isang bagay na mas malaki kaysa sa kanyang sarili | Nabasa ko ang isang bahagi ng manuskrito | ang mas maliit na bahagi ay mahirap abutin | ang hayop na bumubuo ng plankton
Progress: 0.49
translated_text: ang likurang bahagi ng bahay | idikit ang dalawang bahagi
Progress: 0.49
translated_text: sinuri nila ang ilog sa tatlong bahagi | kailangan niya ng isang piraso ng granite
Progress: 0.49
translated_text: nangangailangan ito ng pagbabantay sa ating bahagi | nilalabanan nila ang bawat pagsisikap sa kanyang bahagi
Progress: 0.49
translated_text: ang mga rehiyon ng pagsasaka ng France | relihiyon sa lahat ng bahagi ng mundo | mga rehiyon ng kalawakan
Progress: 0.49
translated_text: ang tungkulin ng isang guro | dapat gawin ng gobyerno ang bahagi nito | gampanan ang papel nito
Progress: 0.49
translated_text: ang nakasulat na bahagi ng pagsusulit | ang seksyon ng pananalapi ng kumpanya | engineering division ng BBC
Progress: 0.49
translated_text: Ipinagmamalaki ko ang aking kontribusyon sa pagsulong ng proyekto | ginawa nilang lahat ang kanilang bahagi sa gawain
Progress: 0.49
translated_text: Sinira ng mga kasosyo sa negosyo ang isang tanong sa buwis | Naghiwalay ang mag-asawa pagkatapos ng 25 taong pagsasama | Naghiwalay kami ng kaibigan ko
Progress: 0.49
translated_text: Pinaghiwalay niya ang mga batang nag-aaway | Hinati ni Moises ang Dagat na Pula
Progress: 0.49
translated_text: Nadama kong bahagyang sisihin | Bahagyang naparalisa siya
Progress: 0.49
translated_text: Ang aming mga anak ay nagbabahagi ng pagmamahal sa musika | Ang dalawang bansa ay nagbabahagi ng mahabang hangganan

Progress: 0.49
translated_text: ang nakasulat na bahagi ng pagsusulit | ang seksyon ng pananalapi ng kumpanya | engineering division ng BBC
Progress: 0.49
translated_text: naglaro siya ng baseball sa klase D sa loob ng dalawang taon | Si Princeton ay nasa NCAA Division 1-AA
Progress: 0.49
translated_text: ang nakasulat na bahagi ng pagsusulit | ang seksyon ng pananalapi ng kumpanya | engineering division ng BBC
Progress: 0.49
translated_text: naglaro siya ng baseball sa klase D sa loob ng dalawang taon | Si Princeton ay nasa NCAA Division 1-AA
Progress: 0.49
translated_text: hatiin ang cake sa tatlong pantay na bahagi | Inukit ng British ang Ottoman Empire pagkatapos ng Unang Digmaang Pandaigdig
Progress: 0.49
translated_text: Pinaghiwalay niya ang mga batang nag-aaway | Hinati ni Moises ang Dagat na Pula
Progress: 0.49
translated_text: hindi pa naararo ang lupa | magandang lupang pang-agrikultura
Progress: 0.49
translated_text: pinalawak ang kanyang domain sa Europa | ginawa niya itong batas ng lupain
Progress: 0.49
translated_text: ang eroplano ay tumalikod sa dagat at bumalik sa lupa | yumanig ang lupa ng ilang minuto | ibinagsak niya ang mga troso sa lupa
Progress: 0.49
translated_text: bumalik siya sa lupang sinilangan | bumisita siya sa ilang bansa sa Europa
Progress: 0.49
translated_text: ang walang gulo na kaharian ng katwiran | isang lupain ng gawa-gawang | ang pagtaas ng kaharian ng bulak sa timog
Progress: 0.49
translated_text: isang pahayag na nagbubuod sa kalagayan ng bansa | ang balita ay inihayag sa bansa | sinamba siya ng buong bansa
Progress: 0.49
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.49
translated_text: ang pagsasaka ay isang masipag na buhay | wala nang trabaho sa lupa
Progress: 0.49
translated_text: Lumapag ang ibon sa pinakamataas na sanga | Lumapag ang eroplano sa Istanbul
Progress: 0.49
translated_text: siya ay isang opisyal ng hukuman | ang club ay naghalal ng mga opisyal nito para sa darating na taon
Progress: 0.49
translated_text: i-convert ang lahat ng mga sukat sa metric units | mas madaling magtrabaho sa sukatan
Progress: 0.49
translated_text: ang metric system | mga katumbas na panukat
Progress: 0.49
translated_text: Ang gatas ay umasim | Ang alak ay gumana | Ang cream ay nakabukas--kailangan nating itapon ito
Progress: 0.49
translated_text: isang maling (o maasim) na tala | off key ang kanyang pagkanta
Progress: 0.50
translated_text: isang madilim na pagsimangot | the proverbially dour New England Puritan | isang malungkot, walang pag-asa na kibit balikat | umupo siya sa moody na katahimikan | isang morose at unsociable na paraan | isang saturnine, halos misanthropic na batang henyo | isang maasim na ugali | isang nagtatampo na karamihan
Progress: 0.50
translated_text: isang bihirang salita | mga bihirang libro
Progress: 0.50
translated_text: isang bihirang hitsura | Ang kabuuang eclipses ay bihirang pangyayari
Progress: 0.50
translated_text: bihirang mga halamang gamot | bihirang mga patch ng berde sa disyerto
Progress: 0.50
translated_text: mga bihirang gas | lightheaded mula sa rarefied bundok hangin
Progress: 0.50
translated_text: kung ano ang napakabihirang bilang isang araw sa Hunyo | isang bihirang kasanayan | isang hindi karaniwang pagkamapagpatawa | siya ay mabait sa isang hindi karaniwang antas
Progress: 0.50
translated_text: isang panandaliang sulyap | takas na oras | mabilis na panandaliang pagsasamahan ng mga bagay na nagsasalubong at lumilipas | isang panandaliang sulyap
Progress: 0.50
translated_text: Ang mainit na tubig ay magpapaliit sa sweater | Maaari mo bang paliitin ang larawang ito?
Progress: 0.50
translated_text: Ang tela ay lumiit | Lumiit ang lobo
Progress: 0.50
translated_text: Lumiit ang kanyang kita | Nanghina ang aking tapang nang makita ko ang gawain sa harap ko
Progress: 0.50
translated_text: nagdala sila ng isang malawak na imbentaryo ng hardware | huminto sila sa pagbebenta sa mga eksaktong sukat upang mabawasan ang imbentaryo
Progress: 0.50
translated_text: maaaring kailanganin ang isang imbentaryo upang makita kung may kulang | nagsagawa sila ng imbentaryo bawat buwan
Progress: 0.50
translated_text: ang crime capital ng Italy | ang kabisera ng droga ng Columbia
Progress: 0.50
translated_text: isang kapital na kapwa | isang malaking ideya
Progress: 0.50
translated_text: kabisera A | mahusay na A | maraming mga manuskrito sa medieval ang nasa script ng majuscule
Progress: 0.50
translated_text: ang trabahong ito ay nangangailangan ng pamumuhunan ng ilang mahirap na pag-iisip | gumawa siya ng emosyonal na pamumuhunan sa trabaho
Progress: 0.50
translated_text: fleet ng paa | ang fleet scurrying ng squirrels | isang mabilis na agos | mabilis na paglipad ng isang arrow | isang matulin na mananakbo
Progress: 0.50
translated_text: mabilis na pelikula | sa mabilis na track sa paaralan | magtakda ng mabilis na bilis | isang mabilis na kotse
Progress: 0.50
translated_text: isang mabilis na kalsada | ang mga damong court ay mas mabilis kaysa sa luwad
Progress: 0.50
translated_text: Congreve gumuhit ng isang debauched aristokratikong lipunan | malungkot na nawala at nasiraan ng loob | magulo na pamumuhay | mabilis na mga babae
Progress: 0.50
translated_text: bumisita sa paglipad | lumipad na sulyap sa libro | isang mabilis na inspeksyon | isang mabilis na pagbisita
Progress: 0.50
translated_text: isang matatag na kaalyado | tapat na tagasuporta | ang tunay na pusong sundalo...ng Tippecanoe | mabilis na kaibigan
Progress: 0.50
translated_text: ang bilis niyang makarating dito? | tumakbo nang mabilis hangga&#39;t kaya niya | nangangailangan ng tulong medikal nang mabilis | mabilis na umaagos na mga ilog | mabilis na balita | mabilis na pagbubukas (o mabilis na pagsasara) na mga shutter
Progress: 0.50
translated_text: mahigpit na nakahawak sa lubid | mabilis na naipit ang paa niya | hinawakan ng mahigpit
Progress: 0.50
translated_text: halos hindi nila marinig ang nagsasalita | halos hindi namin sila kilala | namiss lang matamaan | ay bahagya pang tumunog ang kampana nang bumukas ang pinto | bihira na sana siyang dumating bago siya nakahanap ng dahilan para umalis
Progress: 0.50
translated_text: nagsusulat siya ng mga libro para sa mga bata | mga bata pa lang sila | Ang `tiddler&#39; ay isang British na termino para sa youngster
Progress: 0.50
translated_text: isang menor de edad na makata | may maliit na bahagi sa dula | isang menor de edad na opisyal | marami sa matatapang na adventurer na ito ay menor de edad na mga maharlika | menor de edad na mga kalsada sa likod
Progress: 0.50
translated_text: nagkaroon ng maliliit na pagkakaiba | isang maliit na kaguluhan
Progress: 0.50
translated_text: isang maliit na bahagi ng mga kita | Ursa Minor
Progress: 0.50
translated_text: ang mga menor de edad na susi | sa B flat minor
Progress: 0.50
translated_text: minor injuries lang ang natamo | ilang menor de edad na pagbaha | isang maliit na tropikal na kaguluhan
Progress: 0.50
translated_text: isang maliit na negosyo | isang pahayagan na may katamtamang sirkulasyon | maliliit na plano | isang pocket-size na bansa
Progress: 0.50
translated_text: Iniisip ko kung ito ba ang tamang gawin | Iniisip niya kung magi-snow ba ngayong gabi
Progress: 0.50
translated_text: Palagi akong may gusto sa pagbabasa | nagkaroon siya ng pagkagusto sa gin
Progress: 0.50
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.50
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.50
translated_text: ito ay isang maliit na ekonomiya upang maglakad sa trabaho araw-araw | may naipon na 50 cents
Progress: 0.50
translated_text: trabaho ay ang pagpapalaya ng sangkatauhan | ang trabaho ng surgeon ay ang pagliligtas ng mga buhay
Progress: 0.50
translated_text: Makakatipid ito ng pera | Ililigtas kita sa gulo | Makakatipid ito ng maraming oras
Progress: 0.50
translated_text: Ang hakbang na ito ay makatipid ng pera | Ang mga hindi pinalad ay kailangang magtipid ngayon

Progress: 0.50
translated_text: panatilihin ang aking trabaho para sa akin habang ako ay nanganganak | panatilihin ang aking upuan, mangyaring | panatilihing bukas ang posibilidad ng isang pagsasanib
Progress: 0.50
translated_text: pananampalatayang nagliligtas | mapagtubos (o tumutubos) pag-ibig
Progress: 0.50
translated_text: isang nakakahawa ng saya | ang impeksyon ng kanyang sigasig sa tula
Progress: 0.50
translated_text: isang nakamamatay na aksidente | isang nakamamatay na kaaway | mortal na labanan | isang mortal na sakit
Progress: 0.50
translated_text: isang nakamamatay na aksidente | isang nakamamatay na kaaway | mortal na labanan | isang mortal na sakit
Progress: 0.50
translated_text: nakamamatay na mga lason | nakamamatay na sandata | isang lethal injection
Progress: 0.50
translated_text: makamandag na ahas | isang nakapipinsalang kagat ng insekto
Progress: 0.50
translated_text: siya ay baliw na umiibig | nakamamatay na mapurol | nakamamatay na maalab | deucedly matalino | nakakabaliw na nagseselos
Progress: 0.50
translated_text: Pinag-aralan ni Leonardo ang katawan ng tao | malakas ang pangangatawan niya | kusa ang espiritu ngunit mahina ang laman
Progress: 0.50
translated_text: ang frame ay nagpapabuti ngunit hindi mismo ang paksa ng atensyon | ang frame ay mas mahalaga kaysa sa salamin na hawak nito
Progress: 0.51
translated_text: Naka-set up ako! | Ang inosenteng lalaki ay kinulit ng mga pulis
Progress: 0.51
translated_text: Hindi ko ilalagay ito sa paraang iyon | Ibinigay niya ang kanyang kahilingan sa napakagalang na pananalita
Progress: 0.51
translated_text: ang propesyonal na lalaki o babae ay nagtataglay ng mga natatanging kwalipikasyon | nagsimula ang kanyang propesyonal na karera pagkatapos ng Olympics | propesyonal na teatro | propesyonal na football | isang propesyonal na tagapagluto | propesyonal na aktor at atleta
Progress: 0.51
translated_text: mga propesyonal na organisasyon | isang propesyonal na larangan tulad ng batas
Progress: 0.51
translated_text: propesyonal na pag-uugali | propesyonal na etika | isang ganap na propesyonal na pagganap
Progress: 0.51
translated_text: kailangan namin ng propesyonal na payo | propesyonal na pagsasanay | propesyonal na kagamitan para sa kanyang bagong opisina
Progress: 0.51
translated_text: tapos na ang pag-aani | tapos na ang affair, tapos na, tapos na | ang biglang tinapos na panayam
Progress: 0.51
translated_text: halika at magkita tayo sandali | doon
Progress: 0.51
translated_text: ang wallpaper ay natatakpan ng mga bulaklak | sumakit ang buong katawan niya | ang lahat ay nalinis ng isang pinong layer ng soot
Progress: 0.51
translated_text: ang bolt ay dumulas sa lugar | dumulas ang tubig mula sa pinakintab na marmol
Progress: 0.51
translated_text: dislocate joints | ang artificial hip joint ay lumambo at kinailangang ibalik sa pamamagitan ng operasyon
Progress: 0.51
translated_text: isang jumbo jet | jumbo hipon
Progress: 0.51
translated_text: isang nakatutuwang pakana | kalahating lutong ideya | isang panukalang screwball na walang panalangin ng pagtatrabaho
Progress: 0.51
translated_text: ang daming nagwala | ay baliw na subukan ang kanyang bagong bisikleta
Progress: 0.51
translated_text: nagkaroon ng nakakabaliw na panaginip | nagsuot ng nakakalokong sumbrero
Progress: 0.51
translated_text: baliw sa mga kotse at karera | siya ay potty tungkol sa kanya
Progress: 0.51
translated_text: nanatiling huffy nang matagal | nagagalit siya kapag ginising mo siya ng napakaaga | galit sa kanyang kaibigan | masakit sa isang pangungusap
Progress: 0.51
translated_text: isang pulutong ng mga nahihibang mga tagahanga ng baseball | isang bagay na galit na galit sa kanilang kagalakan | isang baliw na ipo-ipo ng kasiyahan
Progress: 0.51
translated_text: harebrained na mga ideya | kinuha ang nakakabaliw na mga panganib sa likod ng gulong | isang ganap na baliw na pamamaraan upang bumuo ng isang tulay sa pagitan ng dalawang bundok
Progress: 0.51
translated_text: bawat henerasyon ay dapat magkaroon ng sariling rebelyon | ang kanyang katawan ay nagrerebelde laban sa pagod
Progress: 0.51
translated_text: ito ang paglangoy na pinakanasiyahan nila | ilang sandali lang silang lumangoy sa pool
Progress: 0.51
translated_text: Kinailangan naming lumangoy ng 20 minuto para makarating sa baybayin | isang malaking isda ang lumalangoy sa tangke
Progress: 0.51
translated_text: iniiwasan ng mga taganayon ang lugar sa paniniwalang ito ay isinumpa | isinumpa kasama ang apat na anak na babae | hindi isang sinumpa na patak | ang kanyang isinumpang katangahan | Masusumpa ako kung makikita ko ang iyong katwiran
Progress: 0.51
translated_text: sa puso mo alam mong totoo | ang kanyang kuwento ay matutunaw ang iyong dibdib
Progress: 0.51
translated_text: siya ay patuloy na lumalaban sa purong spunk | wala kang puso para sa baseball
Progress: 0.51
translated_text: ito ay nasa gitna ng bayan | tumakbo sila pasulong sa puso ng pakikibaka | sila ay nasa mata ng bagyo
Progress: 0.51
translated_text: ang diwa ng argumento ng tagausig | ang puso at kaluluwa ng Republican Party | ang kulit ng kwento
Progress: 0.51
translated_text: nahirapan siyang ipahayag ang pagmamahal na naramdaman | nanalo ang bata sa puso ng lahat | the warmness of his welcome made us feel at home
Progress: 0.51
translated_text: pinamunuan niya ang reyna ng mga puso | puso ay trumps
Progress: 0.51
translated_text: ang kanyang mga hubad na paa ay nakalabas mula sa kanyang pantalon | nakabaluti mula ulo hanggang paa
Progress: 0.51
translated_text: nakapulupot sa paanan ng kama | ang paa ng pahina | ang paa ng listahan | paanan ng bundok
Progress: 0.51
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.51
translated_text: sumunod siya sa paglalakad | ang pinakamabilis na paa
Progress: 0.51
translated_text: mga dila ng apoy na dinilaan sa mga dingding | ang mga riple ay sumabog ng mabilis na mga kutsilyo ng apoy sa dilim
Progress: 0.51
translated_text: nagsalita siya ng makapal na dila | may malikot siyang dila
Progress: 0.51
translated_text: Hindi ako makapaniwala sa kanyang katapangan | nagkaroon siya ng effrontery na tanungin ang aking katapatan
Progress: 0.51
translated_text: ang lalamunan ng plorera | ang lalamunan ng isang tsimenea
Progress: 0.51
translated_text: tumayo siya sa likod ng stage | nakatago ito sa likod ng tindahan
Progress: 0.51
translated_text: Siya plumped para sa Labor Party | Sinuportahan ko si Kennedy noong 1960
Progress: 0.51
translated_text: pabalik sa driveway | Umatras ang sasakyan at tumama sa puno
Progress: 0.51
translated_text: Ipangalawa ko ang galaw na iyon | Hindi ko maibabalik ang planong ito | mag-endorso ng bagong proyekto
Progress: 0.51
translated_text: Aling kabayo ang iyong sinusuportahan? | Pupusta ako sa bagong kabayo
Progress: 0.51
translated_text: ang likod ng bakuran | ang pasukan sa likod
Progress: 0.51
translated_text: likod (o hulihan) binti | ang hadlang bahagi ng isang bangkay
Progress: 0.51
translated_text: lumipat siya pabalik | natapilok nang humakbang paatras | tumingin siya sa likuran ng bintana ng sasakyan
Progress: 0.51
translated_text: ibalik ang mga orasan ng isang oras | huwag nang lumingon sa likod | ang mga mahilig sa nakaraan ay magiliw na nakatingin sa likuran
Progress: 0.51
translated_text: binayaran namin lahat ng hiniram namin | sinaktan niya ako at binatukan ko siya pabalik | Pinananatili ako pagkatapos ng paaralan para makipag-usap pabalik sa guro
Progress: 0.51
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.51
translated_text: Ang Canada ay katabi ng US | Nagmartsa ang England kasama ang Scotland
Progress: 0.51
translated_text: Pinaalis niya ang kanyang kapatid na babae | Hinampas ng kambing ang hiker gamit ang kanyang mga sungay
Progress: 0.52
translated_text: sumakay siya sa bukana ng kanyon | gumawa sila ng apoy sa bukana ng yungib
Progress: 0.52
translated_text: Siya ay nagsasalita ng maraming bagay na walang kapararakan | Ang depress na pasyente na ito ay hindi nagsasalita
Progress: 0.52
translated_text: lumilipad ang kanyang isip | Hindi ko maalis sa isip ko ang mga sinabi niya

Progress: 0.52
translated_text: matapang na sumulong ang ulo ng hanay | sila ang nangunguna sa pag-atake
Progress: 0.52
translated_text: ang ulo ng hagdan | ang ulo ng pahina | ang pinuno ng listahan
Progress: 0.52
translated_text: siya ay dalawang ulo na mas matangkad kaysa sa kanyang nakababatang kapatid na babae | ang kanyang kabayo ay nanalo sa pamamagitan ng isang ulo
Progress: 0.52
translated_text: isang ulo ng cauliflower | isang pinuno ng litsugas
Progress: 0.52
translated_text: siya ang nasa unahan | nasa ulunan siya ng column
Progress: 0.52
translated_text: isang magandang pass | ang mga bagay ay dumating sa ulo kahapon
Progress: 0.52
translated_text: ang tanong ng sakit ay nararapat na seryosong talakayan | sa ilalim ng ulo ng mga menor de edad na makatang Romano
Progress: 0.52
translated_text: ang ulo ng pako | ang pinhead ay ang ulo ng isang pin
Progress: 0.52
translated_text: saan siya patungo | Nagtungo kami sa mga bundok
Progress: 0.52
translated_text: mayroon siyang mga kamay ng isang surgeon | pinahaba niya ang kanyang mitt
Progress: 0.52
translated_text: inayos ng upahang kamay ang rehas | isang ranch hand
Progress: 0.52
translated_text: nakilala niya ang kanyang sulat-kamay | hindi mabasa ang kanyang kamay
Progress: 0.52
translated_text: Hindi ako nakahawak ng magandang kamay buong gabi | pilit niyang tinitingnan ang kamay ko
Progress: 0.52
translated_text: bigyan mo ako ng kutsara, pakiusap | Ibalik ang mga file sa akin, mangyaring | Ibinalik niya ang bilanggo sa kanyang mga abogado
Progress: 0.52
translated_text: nagsuklay siya ng buhok | bawat buhok ay binubuo ng mga layer ng patay na keratinized cells
Progress: 0.52
translated_text: sila ay nakatakas sa pamamagitan ng isang hair&#39;s-breadth | natalo sila sa eleksyon sa pamamagitan ng bigote
Progress: 0.52
translated_text: ang kanyang mga hubad na paa ay nakalabas mula sa kanyang pantalon | nakabaluti mula ulo hanggang paa
Progress: 0.52
translated_text: nakapulupot sa paanan ng kama | ang paa ng pahina | ang paa ng listahan | paanan ng bundok
Progress: 0.52
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.52
translated_text: sumunod siya sa paglalakad | ang pinakamabilis na paa
Progress: 0.52
translated_text: Pakiramdam ang malambot na tela na ito! | Pininger ng customer ang sweater
Progress: 0.52
translated_text: Siya thumbed sa pamamagitan ng ulat | Binilisan niya ang volume
Progress: 0.52
translated_text: Pinasuso nila ang bundok | Maraming mountaineers ang umaakyat sa Mt. Everest pero hindi lahat summit
Progress: 0.52
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.52
translated_text: sa mata ng batas | Nagkamali ako sa paningin niya
Progress: 0.52
translated_text: siya ay may mata para sa sariwang talento | may mata siyang artista
Progress: 0.52
translated_text: ito ay nasa gitna ng bayan | tumakbo sila pasulong sa puso ng pakikibaka | sila ay nasa mata ng bagyo
Progress: 0.52
translated_text: isa siyang tigre sa tennis court | napukaw nito ang tigre sa akin
Progress: 0.52
translated_text: ang braso ng record player | isang braso ng dagat | isang sangay ng imburnal
Progress: 0.52
translated_text: isang sangay ng Kongreso | ang botany ay isang sangay ng biology | ang Germanic na sangay ng Indo-European na mga wika
Progress: 0.52
translated_text: Ang US ay nagbibigkis para sa isang tunggalian sa Gitnang Silangan | ang mga tropa ay nagtatayo sa hangganan ng Iraq
Progress: 0.52
translated_text: ang braso ng record player | isang braso ng dagat | isang sangay ng imburnal
Progress: 0.52
translated_text: isang sangay ng Kongreso | ang botanika ay isang sangay ng biology | ang Germanic na sangay ng Indo-European na mga wika
Progress: 0.52
translated_text: Ang US ay nagbibigkis para sa isang tunggalian sa Gitnang Silangan | ang mga tropa ay nagtatayo sa hangganan ng Iraq
Progress: 0.52
translated_text: ang pating ay isang malaking isda | sa sala ay may isang tangke ng makukulay na isda
Progress: 0.52
translated_text: sa Japan karamihan ng isda ay kinakain hilaw | pagkatapos ng pagkatakot tungkol sa sakit sa paa at bibig ay maraming tao ang nagsimulang kumain ng isda sa halip na karne | mayroon silang chef na dalubhasa sa isda
Progress: 0.52
translated_text: Iniwasan niya ang isyu | nilampasan niya ang problema | Sila ay madalas na umiiwas sa kanilang mga responsibilidad | mahusay niyang iniiwasan ang mga tanong
Progress: 0.52
translated_text: Iniwasan niya ang isyu | nilampasan niya ang problema | Sila ay madalas na umiiwas sa kanilang mga responsibilidad | mahusay niyang iniiwasan ang mga tanong
Progress: 0.52
translated_text: ang yabang niya ay mas malala pa sa laban niya | sa tuwing nanalo siya ay nalantad kami sa kanyang gasconade
Progress: 0.52
translated_text: ang batalyon ay kalansay lamang ng dati nitong sarili | ang hubad na kalansay ng isang nobela
Progress: 0.52
translated_text: Napanganga niya ang kanyang bubble gum | Nguyain ang iyong pagkain at huwag lunukin ito! | Ang mga baka ay nagmamastika ng damo
Progress: 0.52
translated_text: Pinagalitan ng ina ang anak sa pagpasok sa sasakyan ng estranghero | Ang deputy ay ginulo ang Punong Ministro | Binihisan ng kostumer ang waiter para sa pagdadala ng malamig na sopas
Progress: 0.52
translated_text: isang magandang lalaki | ginagawa lang ito ng lalaki para sa ilang manika
Progress: 0.52
translated_text: Matapos uminom ng sobra, nagsuka ang mga estudyante | Tuloy-tuloy siyang nagpurga | Ni-regurgitate ng pasyente ang pagkain na binigay namin sa kanya kagabi
Progress: 0.52
translated_text: magkaroon ng pagkakahawig | maglagay ng pirma
Progress: 0.52
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.52
translated_text: Mga regalo sa oso | pasanin ang mabigat na kargada | pasanin ang balita | nagdadala ng mga utos
Progress: 0.52
translated_text: Ang puno ng mansanas ay nagbunga ng masasarap na mansanas ngayong taon | Ang hindi kilalang halaman ay nagbunga ng napakarilag na mga bulaklak
Progress: 0.53
translated_text: Tatanggapin ko ang mga singil | Pumayag siyang pasanin ang responsibilidad
Progress: 0.53
translated_text: Ang banga ay may dalang alak | Ang canteen ay may hawak na sariwang tubig | Ito ay naglalaman ng tubig
Progress: 0.53
translated_text: mga account na may interes | Magkano ang binabayaran ng savings certificate na ito taun-taon?
Progress: 0.53
translated_text: Nakasuot siya ng pulang laso | magkaroon ng peklat
Progress: 0.53
translated_text: Dinala niya ng maayos ang sarili | dinadala niya ang kanyang sarili nang may dignidad | Maayos silang kumilos sa mga mahihirap na panahong ito
Progress: 0.53
translated_text: Taglay niya ang titulong Duchess | Hinawakan niya ang pagkagobernador ng halos isang dekada
Progress: 0.53
translated_text: Nakataas ang ulo niya | Binuhat niya ang sarili patayo
Progress: 0.53
translated_text: Ipinanganak niya ang kanyang anak | Inaasahan ng isa pang anak sa Enero | karga ko ang anak niya
Progress: 0.53
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.53
translated_text: May pinakialaman ang mga dokumento sa aking mesa | Kinalikot ng reporter ang mga katotohanan
Progress: 0.53
translated_text: aso, fox, at iba pa | hindi namin gusto ang mga tulad mo sa paligid
Progress: 0.53
translated_text: Hindi na natin makikita ang katulad niya | Hindi ko kayang tiisin ang mga taong katulad niya
Progress: 0.53
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.53
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.53
translated_text: suit ng katulad na disenyo | isang limitadong bilog ng mga katulad na isip | ang mga miyembro ng pamilya ng pusa ay may katulad na disposisyon | tulad ng dalawang gisantes sa isang pod | mala-dog na debosyon | isang parang panaginip na kalidad

Progress: 0.53
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.53
translated_text: lahat ng politiko ay magkatulad | magkamukha sila | ang mga kaibigan ay karaniwang magkapareho sa background at panlasa
Progress: 0.53
translated_text: mga kahon na may kaukulang sukat | ang katulad na panahon ng nakaraang taon
Progress: 0.53
translated_text: Ang mga bayarin ay umabot sa $2,000 | Umabot sa $2,000 ang bill
Progress: 0.53
translated_text: Inabot ng anak ko ang aming bagong sasakyan | ang rock star ay kumukuha ng kanyang gitara sa bawat konsiyerto
Progress: 0.53
translated_text: isang buong bayan na nasalanta ng lindol | nagbigay ng buong atensyon | isang kabuuang kabiguan
Progress: 0.53
translated_text: isang buong laro | isang kabuuang eclipse | isang kabuuang sakuna
Progress: 0.53
translated_text: ang pagsulat ay isang paraan ng therapy para sa kanya | ito ay isang bagay ng pinagtatalunang may-akda
Progress: 0.53
translated_text: paghigpitan ang paggamit ng paradahang ito | limitahan ang oras na maaari mong gugulin sa iyong mga kaibigan
Progress: 0.53
translated_text: ayusin ang mga variable | tukuyin ang mga parameter
Progress: 0.53
translated_text: limitadong digmaan | isang limitadong tagumpay | isang limitadong bilog ng mga kaibigan
Progress: 0.53
translated_text: hindi niya pinahahalagahan ang aking katatawanan | hindi ka makakaligtas sa hukbo na walang sense of humor
Progress: 0.53
translated_text: kung purihin o isumpa niya ako ay nakadepende sa ugali niya noon | nasa bad humor siya
Progress: 0.53
translated_text: ang kanyang mga komposisyon ay laging nagsisimula sa lyrics | isinulat niya ang parehong mga salita at musika | ang awit ay gumagamit ng wikang kolokyal
Progress: 0.53
translated_text: ang tore ay may binibigkas na pagtabingi | ang barko ay bumuo ng isang listahan sa starboard | lumakad siya na may mabigat na hilig sa kanan
Progress: 0.53
translated_text: Ang lobo ay tumaas sa ibabaw | ginawang takong ng hangin ang sisidlan | Nakalista ang barko sa starboard
Progress: 0.53
translated_text: ang tore ay may binibigkas na pagtabingi | ang barko ay bumuo ng isang listahan sa starboard | lumakad siya na may mabigat na hilig sa kanan
Progress: 0.53
translated_text: Ang lobo ay tumaas sa ibabaw | ginawang takong ng hangin ang sisidlan | Nakalista ang barko sa starboard
Progress: 0.53
translated_text: pandaigdigang digmaan | pandaigdigang patakaran sa pananalapi | hindi pambansa o kontinental ngunit planetary | isang krisis sa mundo | ng pandaigdigang kahalagahan
Progress: 0.53
translated_text: isang spherical na bagay | halos orbicular ang hugis | maliit na globular na bahay tulad ng pugad-wasp nest
Progress: 0.53
translated_text: hinila nila ang canoe sa pampang | umupo siya sa pampang ng ilog at pinagmamasdan ang agos
Progress: 0.53
translated_text: nag-cash siya ng tseke sa bangko | hawak ng bangkong iyon ang sangla sa aking tahanan
Progress: 0.53
translated_text: Maaari tayong magtiwala sa Diyos | Umasa sa iyong mga kaibigan | bangko sa iyong magandang edukasyon | Sumusumpa ako sa mga recipe ng aking lola
Progress: 0.53
translated_text: ang pinalawak na bintana ay magbibigay sa atin ng panahon upang mahuli ang mga magnanakaw | mayroon silang isang window na wala pang isang oras kung kailan magtagumpay ang isang pag-atake
Progress: 0.53
translated_text: kumatok siya sa pinto | sinara niya ang pinto pagkaalis niya
Progress: 0.53
translated_text: isinara namin ang pinto sa mga imigrante ng Haitian | edukasyon ang pinto sa tagumpay
Progress: 0.53
translated_text: ang opisina sa tabi ng pinto | nakatira sila sa dalawang pinto sa kalye mula sa amin
Progress: 0.53
translated_text: kinain niya ang kanyang laman ng patatas | narinig niya ang kanyang punung-puno ng tsismis
Progress: 0.53
translated_text: punan ang isang lalagyan | punan ang bata ng pagmamalaki
Progress: 0.53
translated_text: Unti-unting napuno ng tubig ang pool | Unti-unting napuno ang teatro
Progress: 0.53
translated_text: Kinuha niya ang trabaho bilang direktor ng pag-unlad | siya ay sumasakop sa posisyon ng manager | malapit nang sakupin ng batang prinsipe ang trono
Progress: 0.53
translated_text: ito ay isang makitid na pagkatalo | ang tanging pagkatalo ng hukbo | sila ay nagdusa ng isang nakakumbinsi na pagdila
Progress: 0.53
translated_text: Dapat mong malampasan ang lahat ng paghihirap | talunin ang iyong mga kaaway | Daig niya ang pagiging mahiyain | Napagtagumpayan niya ang kanyang kahinaan | Lalong lumakas ang galit niya at sumabog siya
Progress: 0.53
translated_text: pumatay ng galaw | binatukan niya ang proposal ng estudyante
Progress: 0.53
translated_text: Linisin ang kalan! | Nilinis ng dentista ang ngipin ko
Progress: 0.54
translated_text: maglinis ka bago mo makita ang iyong lolo&#39;t lola | linisin ang iyong mga kuko bago kumain
Progress: 0.54
translated_text: Nilinis ng mga lalaki ang mga pinggan ng sandwich | Ang mga puno ay nalinis ng mga mansanas sa pamamagitan ng bagyo
Progress: 0.54
translated_text: mga batang may malinis na kumikinang na mukha | malinis na puting kamiseta | malinis na pinggan | isang malinis na bahay | ang pusa ay malinis na hayop
Progress: 0.54
translated_text: isang malinis na bill ng kalusugan | isang malinaw na nagwagi
Progress: 0.54
translated_text: pagsisikap na makakuha ng malinis na bass sa mga pag-record ng orkestra | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.54
translated_text: malinis na tubig | sariwang hangin
Progress: 0.54
translated_text: isang malinis na rekord ng pagboto | malinis na lisensya sa pagmamaneho
Progress: 0.54
translated_text: isang malinis na gasolina | mas malinis at mas mahusay na mga makina | ang taktikal na bomba ay makatwirang malinis
Progress: 0.54
translated_text: magandang malinis na saya | isang malinis na biro
Progress: 0.54
translated_text: patas na kopya | isang malinis na manuskrito
Progress: 0.54
translated_text: mga blangkong pahina | punan ang mga blangkong puwang | isang malinis na pahina | malawak na puting mga gilid
Progress: 0.54
translated_text: isang malinis na laban | isang pampalakasang solusyon ng hindi pagkakasundo | mahilig sa sportsman
Progress: 0.54
translated_text: isang malinis na bakasyon | isang malinis na pagwawalis | isang malinis na pahinga
Progress: 0.54
translated_text: isang malinis na kaliwa ang napunta niya sa pisngi ng kanyang kalaban | isang malinis na hagis | ang maayos na kawastuhan ng kutsilyo ng surgeon
Progress: 0.54
translated_text: malinis nakalimutan ang appointment | Ako ay plumb (o plum) tuckered out
Progress: 0.54
translated_text: isang imposibleng panaginip | isang imposibleng sitwasyon
Progress: 0.54
translated_text: imposibleng pag-uugali | hindi matiis na kabastusan
Progress: 0.54
translated_text: isang sample para sa sampung araw na libreng pagsubok | nabigo ang pagsubok ng progesterone na mapawi ang sakit
Progress: 0.54
translated_text: nakaligtas siya sa malaking pagsubok ng labanan | ang mga kandidato ay dapat makipagkumpetensya sa isang pagsubok ng kasanayan
Progress: 0.54
translated_text: sa mga eksperimentong pagsubok ang dami ng carbon ay hiwalay na sinusukat | tinawag niyang bagong pagsubok ang bawat pitik ng barya
Progress: 0.54
translated_text: Ang diskarte na ito ay sinubukan na may magagandang resulta | Subukan ang recipe na ito
Progress: 0.54
translated_text: Sinusuri tayo ng guro bawat linggo | Nag-quiz kami sa French irregular verbs
Progress: 0.54
translated_text: lagi siyang may dalang posporo para sindihan ang kanyang tubo | basta&#39;t may lucifer ka na magpapagaan sa bading mo
Progress: 0.54
translated_text: Ang dalawang kuwento ay hindi magkasundo sa maraming detalye | Sinusuri ng sulat-kamay ang pirma sa tseke | Hindi tugma ang fingerprints ng suspek sa nasa baril
Progress: 0.54
translated_text: Ang katotohanang ito ay isinama sa isa pa | Matchmaker, maaari mo bang ipares ang aking anak sa isang magandang binata? | Ang mag-aaral ay ipinares sa isang kasosyo para sa pakikipagtulungan sa proyekto
Progress: 0.54
translated_text: Walang makakaagaw sa cotton para sa tibay | Hindi man lang naaapektuhan ng iyong performance ang iyong mga kasamahan | Ang kanyang pagpupursige at ambisyon ay tumutugma lamang sa kanyang mga magulang

Progress: 0.54
translated_text: matugunan ang isang pangangailangan | ang trabahong ito ay hindi tumutugma sa aking mga pangarap
Progress: 0.54
translated_text: hayaan silang itugma ang kanilang pinakamahusay na mga atleta laban sa atin | pit isang chess player laban sa Russian champion | Pinaglalaruan niya ang kanyang dalawang anak laban sa isa&#39;t isa
Progress: 0.54
translated_text: ipantay natin ang mga tungkulin sa lahat ng empleyado sa opisinang ito | Tinugma ng kumpanya ang patakaran sa diskwento ng mga kakumpitensya nito
Progress: 0.54
translated_text: isang pagsasaayos ng sari-saring bulaklak sa tagsibol | sari-saring laki | sari-saring accessories | isang pinaghalong programa ng baroque at kontemporaryong musika | isang motley crew | sari-saring mga agham na karaniwang kilala bilang panlipunan
Progress: 0.54
translated_text: isang maraming panig na paksa | isang multifaceted na gawain | sari-saring interes | ang samu&#39;t saring ingay ng isang dakilang lungsod | isang sari-saring mga tao
Progress: 0.54
translated_text: hinarap namin ang isang hukbong may malaking lakas | napabayaan ng mga pulitiko ang ating postura sa militar
Progress: 0.54
translated_text: Huwag mo na siyang pansinin--palagi siyang nag-pose para mapabilib ang mga ka-edad niya! | Nag-postura siya at ginawang tanga
Progress: 0.54
translated_text: magkaroon ng pagkakahawig | maglagay ng pirma
Progress: 0.54
translated_text: Hindi ko matiis ang patuloy niyang pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.54
translated_text: Mga regalo sa oso | pasanin ang mabigat na kargada | pasanin ang balita | nagdadala ng mga utos
Progress: 0.54
translated_text: Ang puno ng mansanas ay nagbunga ng masasarap na mansanas ngayong taon | Ang hindi kilalang halaman ay nagbunga ng napakarilag na mga bulaklak
Progress: 0.54
translated_text: Tatanggapin ko ang mga singil | Pumayag siyang pasanin ang responsibilidad
Progress: 0.54
translated_text: Ang banga ay may dalang alak | Ang canteen ay may hawak na sariwang tubig | Ito ay naglalaman ng tubig
Progress: 0.54
translated_text: mga account na may interes | Magkano ang binabayaran ng savings certificate na ito taun-taon?
Progress: 0.54
translated_text: Nakasuot siya ng pulang laso | magkaroon ng peklat
Progress: 0.54
translated_text: Dinala niya ng maayos ang sarili | dinadala niya ang kanyang sarili nang may dignidad | Maayos silang kumilos sa mga mahihirap na panahong ito
Progress: 0.54
translated_text: Taglay niya ang titulong Duchess | Hinawakan niya ang pagiging gobernador ng halos isang dekada
Progress: 0.54
translated_text: Nakataas ang ulo niya | Binuhat niya ang sarili patayo
Progress: 0.54
translated_text: Ipinanganak niya ang kanyang anak | Inaasahan ng isa pang anak sa Enero | karga ko ang anak niya
Progress: 0.54
translated_text: nakaramdam ng panghihinayang sa kanyang naglahong kabataan | nanghihinayang sa mga pagkakamaling nagawa niya | masama ang pakiramdam niya sa pagkabasag ng plorera
Progress: 0.54
translated_text: ang aking pananalapi ay nasa isang kaawa-awang kalagayan | isang malungkot na desisyon | ang kanyang damit ay nasa malungkot na anyo | isang malungkot na estado ng mga pangyayari
Progress: 0.54
translated_text: isang sorry kabayo | isang paumanhin na dahilan | isang tamad na walang-bilang, walang kabuluhan na goldbrick | ang kotse ay isang hindi magandang piraso ng basura
Progress: 0.54
translated_text: isang asul na araw | ang madilim na araw ng digmaan | isang linggo ng maulan na nakababahalang panahon | isang malungkot na tanawin ng taglamig | ang unang malungkot na mga araw ng Nobyembre | isang madilim na madilim na araw | malupit na tag-ulan
Progress: 0.54
translated_text: Hindi ako umiinom ng marami | Hindi ako masyadong naglalakbay
Progress: 0.55
translated_text: Hindi ako umiinom ng marami | Hindi ako masyadong naglalakbay
Progress: 0.55
translated_text: Madalas hampasin ng guro ang mga estudyante | Ang mga bata ay lubhang natalo
Progress: 0.55
translated_text: Pinapaltos ng Senador ang administrasyon sa kanyang talumpati noong Biyernes | pinalaki ng propesor ang mga estudyante | pinaso ng iyong mga invectives ang komunidad
Progress: 0.55
translated_text: halatang umbok ang baril sa kanyang bulsa | ang umbok ng kamelyo | tumayo siya sa mabatong katanyagan | ang occipital protuberance ay mahusay na binuo | ang bony excrescence sa pagitan ng mga sungay nito
Progress: 0.55
translated_text: Natagpuan namin ang ideyang ito sa Plato | Nangyari ako sa pinakakahanga-hangang panaderya sa hindi kalayuan dito | Nakakita siya ng isang kawili-wiling libro sa bookstore noong isang araw
Progress: 0.55
translated_text: Nabawasan siya dahil lagi siyang nagsasalita | Nasira siya sa Sarhento
Progress: 0.55
translated_text: ang mga resulta ay tiyak na naghihikayat | siya ay tiyak na isang masipag | ito ay magiging isang magandang araw para sigurado | sila ay darating, tiyak na | akala nila siguradong pinatay na siya | siguradong mananalo siya bilang shooting | siguradong mabango sila | siguradong darating siya
Progress: 0.55
translated_text: nakadama ng tiyak na tagumpay | ay sigurado (o tiyak) na nakita niya ito | ay lubos na sigurado sa kanyang mga paniniwala | sigurado ng kanyang mga kaibigan
Progress: 0.55
translated_text: tiyaking idiskonekta ang plantsa kapag tapos ka na sa | siguraduhing i-lock ang mga pinto
Progress: 0.55
translated_text: tiyak na mabibigo siya | tiyak ang kanyang kapalaran | Sa buhay na ito walang tiyak kundi kamatayan at buwis | nahaharap siya sa tiyak na kamatayan | biglaan ngunit siguradong panghihinayang | siguradong mananalo siya
Progress: 0.55
translated_text: isang tiyak na katayuan | ay nasa siguradong lupa
Progress: 0.55
translated_text: isang mabilis at tiyak na lunas | isang tiyak na paraan upang makilala ang dalawang | Ang alikabok ng kahoy ay isang siguradong tanda ng anay
Progress: 0.55
translated_text: ang mga resulta ay tiyak na nakapagpapatibay | siya ay tiyak na isang masipag | ito ay magiging isang magandang araw para sigurado | sila ay darating, tiyak na | akala nila siguradong napatay na siya | siguradong mananalo siya bilang shooting | siguradong mabango sila | siguradong darating siya
Progress: 0.55
translated_text: minsan minahal niya siya | ang kanyang dating pagsulat | dancer siya minsan
Progress: 0.55
translated_text: Pinahaba namin ang aming pamamalagi | Pinahaba niya ang kanyang pagbisita sa ibang araw | Ang pulong ay inilabas hanggang hatinggabi
Progress: 0.55
translated_text: Sinustento namin ang diplomatikong negosasyon hangga&#39;t maaari | pahabain ang paggamot sa pasyente | ipagpatuloy ang mabuting gawain
Progress: 0.55
translated_text: Ang batas ay pinalawig sa lahat ng mamamayan | palawakin ang hanay ng mga application | palawakin ang iyong abot-tanaw | Palawakin ang iyong likod-bahay
Progress: 0.55
translated_text: Ang serbisyo ay tumatakbo hanggang sa Cranbury | Ang kanyang kaalaman ay hindi masyadong napupunta | Ang aking alaala ay umaabot pabalik sa aking ikaapat na taon ng buhay | Ang mga katotohanan ay higit pa sa pagsasaalang-alang sa kanyang mga personal na ari-arian
Progress: 0.55
translated_text: Ang digmaan ay pinalawig sa loob ng limang taon | Saklaw ng panahon ang pagliko ng siglo | Ang aking lupain ay umaabot sa ibabaw ng mga burol sa abot-tanaw | Saklaw ng sakahan na ito ang ilang 200 ektarya | Ang Archipelago ay nagpapatuloy ng isa pang 500 milya
Progress: 0.55
translated_text: mag-extend ng loan | Nag-aalok ang bangko ng magandang deal sa mga bagong mortgage
Progress: 0.55
translated_text: Inilahad niya ang kanyang kamay | ituro ang isang daliri | mag-abot ng kamay | inilabas ng bubuyog ang tibo nito
Progress: 0.55
translated_text: ipaabot ang aking pagbati | Inialay niya ang kanyang pakikiramay
Progress: 0.55
translated_text: Iunat ang iyong mga binti! | Palawakin ang iyong kanang braso sa itaas ng iyong ulo
Progress: 0.55
translated_text: Pinahaba namin ang aming pamamalagi | Pinahaba niya ang kanyang pagbisita sa ibang araw | Ang pulong ay inilabas hanggang hatinggabi
Progress: 0.55
translated_text: Buksan ang pahayagan | iunat ang kapirasong tela | pahabain ang antenna ng TV

Progress: 0.55
translated_text: Nag-extend talaga siya nang umakyat sa Kilimanjaro | Huwag masyadong pilitin ang iyong isip
Progress: 0.55
translated_text: Ang digmaang sibil ay dinala sa kalapit na lalawigan | Ang sakit ay umabot sa malalayong lalawigan ng bundok
Progress: 0.55
translated_text: iunat ang sopas sa pamamagitan ng pagdaragdag ng higit pang cream | pahabain ang kaserola na may kaunting kanin
Progress: 0.55
translated_text: Ibinenta niya ang kanyang bahay noong Enero | Ibinebenta niya ang kanyang katawan upang mabuhay at masuportahan ang kanyang bisyo sa droga
Progress: 0.55
translated_text: Nakikitungo siya sa ginto | Nagtitinda ng sapatos ang magkapatid
Progress: 0.55
translated_text: Ipinagbili ni Hudas si Hesus | Ang espiya ay nagtaksil sa kanyang bansa
Progress: 0.55
translated_text: Ibinenta niya ang kanyang bahay noong Enero | Ibinebenta niya ang kanyang katawan upang mabuhay at masuportahan ang kanyang bisyo sa droga
Progress: 0.55
translated_text: Nakikitungo siya sa ginto | Nagtitinda ng sapatos ang magkapatid
Progress: 0.55
translated_text: Ipinagbili ni Hudas si Hesus | Ang espiya ay nagtaksil sa kanyang bansa
Progress: 0.55
translated_text: Yakapin mo ako, pakiusap | Niyakap nila | Niyakap niya ito palapit sa kanya
Progress: 0.55
translated_text: Yakapin mo ako, pakiusap | Niyakap nila | Niyakap niya ito palapit sa kanya
Progress: 0.55
translated_text: katulad na pagkain sa magkatulad na presyo | mga problemang katulad ng sa akin | pareho silang nakasuot ng coat
Progress: 0.55
translated_text: lahat ng politiko ay magkatulad | magkamukha sila | ang mga kaibigan ay karaniwang magkapareho sa background at panlasa
Progress: 0.55
translated_text: suit ng katulad na disenyo | isang limitadong bilog ng mga katulad na isip | ang mga miyembro ng pamilya ng pusa ay may katulad na disposisyon | tulad ng dalawang gisantes sa isang pod | mala-dog na debosyon | isang parang panaginip na kalidad
Progress: 0.55
translated_text: mapagpapalit na mga saksakan ng kuryente | mapapalitang bahagi
Progress: 0.55
translated_text: isang kasaysayan ng France | nagbigay siya ng hindi tumpak na salaysay tungkol sa balak na patayin ang pangulo | ang kwento ng exposure sa lead
Progress: 0.55
translated_text: itinuro niya ang kasaysayan ng Medieval | mahabang view ang kasaysayan
Progress: 0.55
translated_text: ang bukang-liwayway ng naitalang kasaysayan | mula sa simula ng kasaysayan
Progress: 0.55
translated_text: ang karbon ay isang matigas na itim na materyal | trigo ang gamit nila sa paggawa ng tinapay
Progress: 0.55
translated_text: ang tela sa mga kurtina ay magaan at semitransparent | ang hinabing tela ay nagmula sa Mesopotamia noong mga 5000 BC | nagsukat siya ng sapat na materyal para sa isang damit
Progress: 0.55
translated_text: mga materyales sa pagsulat | kapaki-pakinabang na materyales sa pagtuturo
Progress: 0.55
translated_text: siya ay materyal sa unibersidad | siya ay vice-presidential material
Progress: 0.55
translated_text: kapitalistang pagsasamantala ng uring manggagawa | ang pagbabayad ng mas mababa sa mga Black at paniningil ng higit sa kanila ay isang paraan ng pambibiktima
Progress: 0.55
translated_text: gamitin mo ang ulo mo! | Spanish lang ang gamit namin sa bahay | Hindi ko magagamit ang tool na ito | Mag-apply ng magnetic field dito | Ang pag-iisip na ito ay inilapat sa maraming proyekto | Paano mo ginagamit ang tool na ito? | Inilapat ko ang panuntunang ito para makakuha ng magagandang resulta | gamitin ang mga plastic bag para mag-imbak ng pagkain | Hindi siya marunong gumamit ng computer
Progress: 0.55
translated_text: Ginagamit niya ang kanyang mga maimpluwensyang kaibigan para makakuha ng trabaho | Ginamit ng asawa ng presidente ang kanyang magagandang koneksyon
Progress: 0.56
translated_text: maglapat ng prinsipyo | magsagawa ng relihiyon | mag-ingat sa pagbaba ng hagdan | gamitin ang iyong sentido komun | magsanay ng hindi marahas na paglaban
Progress: 0.56
translated_text: Dati linggo-linggo siyang tumatawag sa kanyang ina ngunit ngayon ay paminsan-minsan na lamang | Nagkasakit ako noon kapag kumakain ako sa dining hall na iyon | Nagbakasyon sila noon sa Bahamas
Progress: 0.56
translated_text: ang aking kasakiman ang naging instrumento ng aking pagkawasak | Binigyan tayo ng agham ng mga bagong kasangkapan upang labanan ang sakit
Progress: 0.56
translated_text: nadama niya na ang kanyang buong buhay ay isang kabiguan | noong taong iyon ay nagkaroon ng crop failure
Progress: 0.56
translated_text: nagalit siya sa hindi ko pagbabalik ng kanyang tawag | kabiguang suriin ng mekaniko ang preno
Progress: 0.56
translated_text: kinailangang ideklara ng kumpanya ang pagkabangkarote | Ang mga mapanlinlang na pautang ay humantong sa pagkabigo ng maraming mga bangko
Progress: 0.56
translated_text: ang nangungunang tao | prima ballerina | prima donna | isang star figure skater | ang bida na papel | isang stellar role | isang stellar performance
Progress: 0.56
translated_text: ang kanyang salaysay ay kawili-wili | Ang mga kuwento ng Disney ay nakakaaliw sa mga matatanda pati na rin sa mga bata
Progress: 0.56
translated_text: isang kasaysayan ng France | nagbigay siya ng hindi tumpak na salaysay tungkol sa balak na patayin ang pangulo | ang kwento ng exposure sa lead
Progress: 0.56
translated_text: ang ulat ng kanyang talumpati | ang kwento ay nasa 11 o&#39;clock news | ang ulat ng kanyang talumpati na ibinigay sa balita sa gabi ay nagpagalit sa gobernador
Progress: 0.56
translated_text: sinabi niya sa isang fib tungkol sa pagkain ng kanyang kangkong | paano ko mapipigilan ang aking anak na magkwento?
Progress: 0.56
translated_text: mahal niya ang takip-silim | natapos sila bago sumapit ang gabi
Progress: 0.56
translated_text: Ang madilim na gabi ay sumasakay sa langit/At nag-uumpisa sa umaga | ang takipsilim ningning ng langit | isang bangka sa ilog twilit
Progress: 0.56
translated_text: Sinubukan kitang tawagan buong gabi | Kumuha ng dalawang aspirin at tawagan ako sa umaga
Progress: 0.56
translated_text: isang matalas na photographic na imahe | ang matalim na bitak ng sanga | ang malutong na snap ng mga tuyong dahon sa ilalim ng paa
Progress: 0.56
translated_text: isang matinding tagamasid ng pulitika at mga pulitiko | matulis na komento | nagyeyelong parang kutsilyo na pangangatwiran | kasing talas at matinis na gaya ng hampas ng pangil | tumatagos na pananaw | madalas na penetrative observation
Progress: 0.56
translated_text: isang matalinong negosyante | palaging binabasa ng isang matalinong nangungupahan ang maliit na letra sa isang lease | siya ay napakatalino upang sumama sa kanila sa isang daan na maaaring humantong lamang sa kanilang pagbagsak
Progress: 0.56
translated_text: matalas na pagpuna | isang matalas na palitan ng salita | isang maasim na pahayag
Progress: 0.56
translated_text: isang matinis na sipol | isang matinis na saya
Progress: 0.56
translated_text: isang biglang kanyon | ang matarik na alon sa itaas na ilog | ang mga matarik na burol ng mga pinturang Tsino | isang matalim na patak
Progress: 0.56
translated_text: isang matinding sakit | matalas na hangin
Progress: 0.56
translated_text: isang matalim na kutsilyo | isang lapis na may matalas na punto
Progress: 0.56
translated_text: umikot ang daan pagkatapos ng liwanag | lumiko bigla pakaliwa dito | ang visor ay acutely peak | ang kanyang sapatos ay acutely pointed toes
Progress: 0.56
translated_text: isang matalas na photographic na imahe | ang matalim na bitak ng sanga | ang malutong na snap ng mga tuyong dahon sa ilalim ng paa
Progress: 0.56
translated_text: isang matinding tagamasid ng pulitika at mga pulitiko | matulis na komento | nagyeyelong parang kutsilyo na pangangatwiran | kasing matalas at matinis na gaya ng hampas ng pangil | tumatagos na pananaw | madalas na penetrative observation
Progress: 0.56
translated_text: isang matalinong negosyante | palaging binabasa ng isang matalinong nangungupahan ang maliit na letra sa isang lease | siya ay napakatalino upang sumama sa kanila sa isang daan na maaaring humantong lamang sa kanilang pagbagsak
Progress: 0.56
translated_text: matalas na pagpuna | isang matalas na palitan ng salita | isang maasim na pahayag

Progress: 0.56
translated_text: isang matinis na sipol | isang matinis na saya
Progress: 0.56
translated_text: isang biglang kanyon | ang matarik na agos ng itaas na ilog | ang matarik na burol ng mga pinturang Tsino | isang matalim na patak
Progress: 0.56
translated_text: isang matinding sakit | matalas na hangin
Progress: 0.56
translated_text: isang matalim na kutsilyo | isang lapis na may matalas na punto
Progress: 0.56
translated_text: ang daan ay umiikot nang husto pagkatapos ng liwanag | lumiko pakaliwa dito | ang visor ay acutely peak | ang kanyang sapatos ay acutely pointed toes
Progress: 0.56
translated_text: durugin ang isang lata ng aluminyo | pisilin ang isang limon
Progress: 0.56
translated_text: Tinalo ni Agassi si Becker sa kampeonato ng tennis | Tinalo namin ang kompetisyon | Tinalo ng Harvard si Yale sa huling laro ng football
Progress: 0.56
translated_text: Nadurog siya sa pagtanggi nito sa kanyang imbitasyon | Ang pagkamatay ng kanyang anak ay bumagsak sa kanya
Progress: 0.56
translated_text: ang pagsulat ay isang paraan ng therapy para sa kanya | ito ay isang bagay ng pinagtatalunang may-akda
Progress: 0.56
translated_text: ang pagkakasulat sa kanyang mga nobela ay mahusay | ang editoryal na iyon ay isang magandang piraso ng pagsulat
Progress: 0.56
translated_text: binaliktad niya ang papel para hindi makita ng nakasulat | hindi mabasa ang sinulat ng doktor
Progress: 0.56
translated_text: Gumawa siya ng tula | Nagsulat siya ng apat na nobela
Progress: 0.56
translated_text: Ilang aklat ang isinulat ni Georges Simenon? | Nag-publish siya ng 25 mga libro sa kanyang mahabang karera
Progress: 0.56
translated_text: Ang pintor ay nagsulat ng mga Chinese character sa isang malaking piraso ng puting papel | Ang Ruso ay nakasulat gamit ang alpabetong Cyrillic
Progress: 0.56
translated_text: mag-isyu ng bagong uniporme sa mga bata | magbigay ng mga kumot para sa mga kama
Progress: 0.56
translated_text: Ang mga bagong resulta ay nangangako | Ang mga resulta ay nangako ng katanyagan at kaluwalhatian
Progress: 0.56
translated_text: ang natatanging singsing ng kampana ng simbahan | ang tugtog ng telepono | ang tintinnabulasyon na napakalaki ng bukol mula sa tugtog at paglamig ng mga kampana
Progress: 0.56
translated_text: I-ring ang mga kampana | Ang aking tiyuhin ay tumutunog tuwing Linggo sa lokal na simbahan
Progress: 0.56
translated_text: Sinubukan kitang tawagan buong gabi | Kumuha ng dalawang aspirin at tawagan ako sa umaga
Progress: 0.56
translated_text: singsing na ibon | band ang mga gansa upang obserbahan ang kanilang migratory pattern
Progress: 0.56
translated_text: kailangan mong harapin ang musika | inumin mo ang iyong gamot
Progress: 0.56
translated_text: isang masuwerteng pagtakas | isang masuwerteng hula
Progress: 0.56
translated_text: ang aking masuwerteng araw | isang masuwerteng lalaki
Progress: 0.57
translated_text: isang kanais-nais na oras para humingi ng taas | masuwerteng bituin | isang maunlad na sandali upang makagawa ng desisyon
Progress: 0.57
translated_text: isang masuwerteng pagtakas | isang masuwerteng hula
Progress: 0.57
translated_text: ang aking masuwerteng araw | isang masuwerteng lalaki
Progress: 0.57
translated_text: isang kanais-nais na oras para humingi ng taas | masuwerteng bituin | isang maunlad na sandali upang makagawa ng desisyon
Progress: 0.57
translated_text: makarating sa punto | namiss niya yung point ng joke | nawalan na ng saysay ang buhay
Progress: 0.57
translated_text: ilan sa mga detalye ay magkatulad | isang punto ng impormasyon
Progress: 0.57
translated_text: isang kahanga-hangang antas ng pagiging prangka | sa anong yugto ang mga agham panlipunan?
Progress: 0.57
translated_text: isang hilera ng mga puntos | gumuhit ng mga linya sa pagitan ng mga tuldok
Progress: 0.57
translated_text: umiskor siya ng 20 puntos sa unang kalahati | ang touchdown ay nagbibilang ng 6 na puntos
Progress: 0.57
translated_text: napansin niya ang isang item sa New York Times | mayroon siyang ilang mga item sa kanyang listahan ng pamimili | ang pangunahing punto sa agenda ay kinuha muna
Progress: 0.57
translated_text: idinikit niya ang dulo ng kutsilyo sa isang puno | sinira niya ang punto ng kanyang lapis
Progress: 0.57
translated_text: Ipinakita ko sa customer ang glove section | Tinuro niya ang bakanteng parking space | ipinahiwatig niya ang kanyang mga kalaban
Progress: 0.57
translated_text: Ang weather vane ay tumuturo sa North | itinuro palabas ang mga daliri ng mga mananayaw
Progress: 0.57
translated_text: tumutok ng baril | Itinutok niya sa akin ang kanyang armas
Progress: 0.57
translated_text: Ang mga sintomas na ito ay nagpapahiwatig ng isang malubhang sakit | Ang kanyang pag-uugali ay tumuturo sa isang malubhang neurosis | Ang mga tagapagpahiwatig ng ekonomiya ay nagpapahiwatig na ang euro ay undervalued
Progress: 0.57
translated_text: Itinutok niya ang kanyang mga kamao sa mukha ng kanyang kalaban | pamumuna nakadirekta sa kanyang superior | idirekta ang iyong galit sa iba, hindi sa iyong sarili
Progress: 0.57
translated_text: sinunod niya ang mga tagubilin sa sulat | sinunod niya ang liham ng batas
Progress: 0.57
translated_text: ang kabisera ng krimen ng Italya | ang kabisera ng droga ng Columbia
Progress: 0.57
translated_text: isang kapital na kapwa | isang malaking ideya
Progress: 0.57
translated_text: kabisera A | mahusay na A | maraming mga manuskrito sa medieval ang nasa script ng majuscule
Progress: 0.57
translated_text: isang buod na pagpapatupad | buod ng hustisya
Progress: 0.57
translated_text: isang maikli at komprehensibong aklat | ang isang compact na istilo ay maikli at masigla | maikling paghahambing | isang buod na pagbabalangkas ng isang malawak na paksa
Progress: 0.57
translated_text: ang pinto ay sumara sa isang pagkabigla | ang lahat ng mga garapon at jolts ay pinakinis ng mga shock absorbers
Progress: 0.57
translated_text: ang kanyang katiyakan sa kanyang kataasan ay hindi nagpatanyag sa kanya | pagkatapos ng kabiguan na iyon ay nawalan siya ng tiwala | may awtoridad siyang nagsalita
Progress: 0.57
translated_text: May tiwala ako sa team namin | ang pagtitiwala ay laging hinihiram, hindi pag-aari
Progress: 0.57
translated_text: kinuha niya ako sa kanyang pagtitiwala | ipinagkanulo niya ang kanilang tiwala
Progress: 0.57
translated_text: lahat ay nagtiwala sa kanya sa kanilang mga pagtitiwala | hindi maihayag ng pari ang kanyang mga pagtitiwala
Progress: 0.57
translated_text: isinulat niya ang papel na may malaking pag-asa sa gawain ng iba pang mga siyentipiko | mas nagtiwala siya sa sarili niyang dalawang paa kaysa sa baril
Progress: 0.57
translated_text: itinatangi niya ang pananampalataya ng isang mabuting babae | ang relasyon ng doktor-pasyente ay nakabatay sa tiwala
Progress: 0.57
translated_text: kinuha niya ako sa kanyang pagtitiwala | ipinagkanulo niya ang kanilang tiwala
Progress: 0.57
translated_text: Maaari tayong magtiwala sa Diyos | Umasa sa iyong mga kaibigan | bangko sa iyong magandang edukasyon | Sumusumpa ako sa mga recipe ng aking lola
Progress: 0.57
translated_text: Nagtitiwala ako na magiging mas mahusay ka mula ngayon | Sana maintindihan niya na hindi siya makakaasa ng pagtaas
Progress: 0.57
translated_text: Ang sugo ay pinagkatiwalaan ng lihim ng heneral | Iniaalay ko ang aking kaluluwa sa Diyos
Progress: 0.57
translated_text: Matingkad na asul na panahon ng Oktubre | isang asul na apoy | asul na ulap ng usok ng tabako
Progress: 0.57
translated_text: malungkot sa kakaisip kung ano ang dapat niyang harapin | madilim na mga hula | isang madilim na katahimikan | kinuha ang isang mabangis na pagtingin sa ekonomiya | ang nagdidilim na kalooban | malungkot at asul sa isang kakaibang lungsod | nalulumbay sa pagkawala ng kanyang trabaho | isang dispirited at nagbitiw na ekspresyon sa kanyang mukha | nalulumbay pagkatapos ng kanyang pagkatalo | nakakaramdam ng panghihina ng loob at panghihina ng loob
Progress: 0.57
translated_text: marumi ang bibig at lapastangan | asul na wika | mga salitang bastos
Progress: 0.57
translated_text: isang asul na pelikula | asul na biro | nilaktawan niya ang mga asterisk at binibigyan ka ng mga detalye ng gamy | isang makatas na iskandalo | isang makulit na kindat | malikot na salita | racy anekdota | isang mapanganib na kwento | maanghang na tsismis

Progress: 0.57
translated_text: isang maharlikang pamilya | aristokratikong Bostonians | aristokratikong pamahalaan | isang asul na pamilya | dugong bughaw | ang aristokrasya na may dugong bughaw | ng banayad na dugo | patrician landholders ng American South | aristokratikong tindig | aristokratikong katangian | panlasa ni patrician
Progress: 0.57
translated_text: ang puritan work ethic | puritanic distaste para sa alak | siya ay kahit ano ngunit puritanical sa kanyang pag-uugali
Progress: 0.57
translated_text: isang asul na araw | ang madilim na araw ng digmaan | isang linggo ng maulan na nakababahalang panahon | isang malungkot na tanawin ng taglamig | ang unang mapanglaw na araw ng Nobyembre | isang madilim na madilim na araw | malupit na tag-ulan
Progress: 0.57
translated_text: Matingkad na asul na panahon ng Oktubre | isang asul na apoy | asul na ulap ng usok ng tabako
Progress: 0.57
translated_text: malungkot sa kakaisip kung ano ang dapat niyang harapin | madilim na mga hula | isang madilim na katahimikan | kumuha ng mabangis na pagtingin sa ekonomiya | ang nagdidilim na kalooban | malungkot at asul sa isang kakaibang lungsod | nalulumbay sa pagkawala ng kanyang trabaho | isang dispirited at nagbitiw na ekspresyon sa kanyang mukha | nalulumbay pagkatapos ng kanyang pagkatalo | panghihina ng loob at panghihina ng loob
Progress: 0.57
translated_text: marumi ang bibig at lapastangan | asul na wika | mga salitang bastos
Progress: 0.57
translated_text: isang asul na pelikula | asul na biro | nilaktawan niya ang mga asterisk at binibigyan ka ng mga detalye ng gamy | isang makatas na iskandalo | isang makulit na kindat | malikot na salita | racy anekdota | isang mapanganib na kwento | maanghang na tsismis
Progress: 0.57
translated_text: isang maharlikang pamilya | aristokratikong Bostonians | aristokratikong pamahalaan | isang asul na pamilya | dugong bughaw | ang aristokrasya na may dugong bughaw | ng banayad na dugo | patrician landholders ng American South | aristokratikong tindig | aristokratikong katangian | panlasa ni patrician
Progress: 0.57
translated_text: ang puritan work ethic | puritanic distaste para sa alak | siya ay kahit ano ngunit puritanical sa kanyang pag-uugali
Progress: 0.57
translated_text: isang asul na araw | ang madilim na araw ng digmaan | isang linggo ng maulan na nakababahalang panahon | isang malungkot na tanawin ng taglamig | ang unang mapanglaw na araw ng Nobyembre | isang madilim na madilim na araw | malupit na tag-ulan
Progress: 0.57
translated_text: 3 araw kaming walang tubig at pagkain | Ang mga pamahiin na ito ay nabubuhay sa backwaters ng America | Ang driver ng karera ng kotse ay nabuhay sa maraming malubhang aksidente | gaano katagal ang isang tao na walang pagkain at tubig?
Progress: 0.57
translated_text: halos hindi siya maaaring umiral sa gayong mababang sahod | Mabubuhay ka ba sa $2000 sa isang buwan sa New York City? | Maraming tao sa mundo ang kailangang mabuhay ng $1 sa isang araw
Progress: 0.57
translated_text: ang awit ng mga bala ay nasa himpapawid | ang awit ng hangin | ang mga gulong ay kumanta ng kanilang kanta habang ang tren ay umuusad sa unahan
Progress: 0.57
translated_text: kinailangan ng mga mag-aaral na magsaliksik sa kasaysayan ng Ikalawang Digmaang Pandaigdig para sa kanilang proyekto sa kasaysayan | Naghanap siya ng impormasyon sa kanyang mga kamag-anak sa web | Sinasaliksik ng mga siyentipiko ang kalikasan ng kamalayan
Progress: 0.58
translated_text: silid na dadaanan | gumawa ng paraan para sa | halos hindi sapat na silid ng siko upang lumiko
Progress: 0.58
translated_text: silid na dadaanan | gumawa ng paraan para sa | halos hindi sapat na silid ng siko upang lumiko
Progress: 0.58
translated_text: Nagmamadali siyang bumaba ng bulwagan upang tanggapin ang kanyang mga bisita | Ang mga sasakyan ay tumakbo sa kalye
Progress: 0.58
translated_text: Nagalit sa akin ang aklat na ito | Isang nakakabahalang pag-iisip
Progress: 0.58
translated_text: Nagalit sa akin ang aklat na ito | Isang nakakabahalang kaisipan
Progress: 0.58
translated_text: nanood sila ng sine tuwing Sabado ng gabi | ang pelikula ay kinunan sa lokasyon
Progress: 0.58
translated_text: mga piraso ng teatro inilipat sa celluloid | magiging magandang sinehan ang kwentong ito | saklaw ng pelikula ng mga kaganapang pampalakasan
Progress: 0.58
translated_text: kumuha ng eksena | mag-shoot ng pelikula
Progress: 0.58
translated_text: Sinasanay ng matandang master ang mga world-class na biyolinista | binuo natin ang mga pinuno para sa hinaharap
Progress: 0.58
translated_text: Siya ay nagsasanay upang maging isang guro | Nagsanay siya bilang isang legal aid
Progress: 0.58
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.58
translated_text: Inaayos niya ang kanyang anak upang maging kahalili niya | Ang prinsipe ay inihanda na maging Hari balang araw | Sinanay nila siyang maging isang mandirigma
Progress: 0.58
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.58
translated_text: Mangyaring huwag tutok sa iyong nakababatang kapatid! | Sinanay niya ang kanyang baril sa magnanakaw | Huwag sanayin ang iyong camera sa mga babae | Mag-swipe sa kalaban
Progress: 0.58
translated_text: Sinasanay niya ang aming Olympic team | Siya ang nagtuturo sa crew
Progress: 0.58
translated_text: Nag-rail sila mula Roma hanggang Venice | Nagsanay siya sa Hamburg
Progress: 0.58
translated_text: Sinusundan ng paslit ang kanyang pantalon | Sinanay niya ang kanyang mahabang scarf sa likod niya
Progress: 0.58
translated_text: isang sinanay na isip | sinanay na mga kalapati | mahusay na sinanay na mga tagapaglingkod
Progress: 0.58
translated_text: sanay sa handicrafts | isang mahusay na juggler | isang dalubhasang trabaho | isang magaling na mekaniko | isang sinanay na marksman | isang mahusay na inhinyero | isang hindi gaanong kilala ngunit hindi gaanong mahusay na kompositor | ang epekto ay nakamit sa pamamagitan ng mahusay na retoke
Progress: 0.58
translated_text: teknikal na terminolohiya | isang teknikal na ulat | teknikal na wika
Progress: 0.58
translated_text: Ang ebidensya ay nangangatwiran para sa iyong paghahabol | Ang mga resulta ay nagpapahiwatig ng pangangailangan para sa karagdagang trabaho
Progress: 0.58
translated_text: siya ay nanirahan sa ligaw | nangolekta sila ng mga kabute sa ligaw
Progress: 0.58
translated_text: ligaw na usapan | ligaw na partido
Progress: 0.58
translated_text: ligaw na gansa | nakakain ng mga ligaw na halaman
Progress: 0.58
translated_text: ligaw sa galit | ligaw sa kalungkutan
Progress: 0.58
translated_text: isang ligaw na bala | naghagis siya ng ligaw na pitch
Progress: 0.58
translated_text: isang marahas na sagupaan ng mga kulay | ang kanyang damit ay isang marahas na pula | isang marahas na ingay | ligaw na kulay | ligaw na sigaw
Progress: 0.58
translated_text: walang basehang tsismis | napatunayang walang batayan ang mga paratang | walang ginagawa na takot | walang basehang hinala | walang kwentang selos
Progress: 0.58
translated_text: Ang skydiving ay isang mapanganib na isport | lubhang mapanganib na lumabas sa tubig at fog | isang ligaw na plano sa pananalapi
Progress: 0.58
translated_text: isang disyerto na isla | isang pinabayaan ng diyos na ilang sangang-daan | isang ligaw na kahabaan ng lupain | mga basurang lugar
Progress: 0.58
translated_text: baliw sa mga kotse at karera | siya ay potty tungkol sa kanya
Progress: 0.58
translated_text: barbarian invaders | mga barbarong gawi | isang ganid na tao | krudo at hindi sibilisado ang pakikipaglaban lalo na kung mahusay ang mga armas | ligaw na tribo
Progress: 0.58
translated_text: galit na ulap sa abot-tanaw | galit na galit na hangin | ang rumaragasang dagat
Progress: 0.58
translated_text: lumalagong ligaw | gumagala-gala
Progress: 0.58
translated_text: gumaan ang pakiramdam niya pagkatapos ng kaunting tulog | walang oras para umidlip
Progress: 0.58
translated_text: lahat ay tulog nang tumunog ang telepono | nakatulog sa manibela
Progress: 0.58
translated_text: tulog ang paa ko | manhid sa lamig
Progress: 0.58
translated_text: siya ay namatay | ang aming mahal na yumaong kaibigan

Progress: 0.58
translated_text: ang kahina-hinala ng kanyang pag-angkin | walang tanong tungkol sa bisa ng negosyo
Progress: 0.58
translated_text: Duda ako sa mga ulat na ito | Pinaghihinalaan ko ang kanyang tunay na motibo | wala siyang tiwala sa kanyang madrasta
Progress: 0.58
translated_text: Nakatingin lang siya sa papel | Sumilip lang ako--wala akong nakitang interesante
Progress: 0.58
translated_text: Sa tingin ko siya ay napakatalino | Naniniwala ako na siya ay napakatalino | Sa tingin ko boyfriend niya | Iniisip ng racist na ang mga taong ito ay mababa
Progress: 0.58
translated_text: Iniisip ko na kumita siya ng maraming pera sa kanyang bagong nobela | Naisip kong hanapin siya sa masamang kalagayan | hindi niya naisip na hanapin siya sa kusina | Galit yata siya sa akin dahil pinatayo ko siya
Progress: 0.58
translated_text: Hindi ko matandaan na sinabi ko ang anumang bagay na iyon | Hindi ko maisip kung ano ang apelyido niya | naaalala mo ba ang kanyang numero ng telepono? | Naaalala mo ba na minsan ka niyang minahal? | tumawag ng mga alaala
Progress: 0.58
translated_text: Isipin mo na lang--mayaman ka balang araw! | Isipin kung anong eksena iyon!
Progress: 0.58
translated_text: Mag-isip ng malaki | mag-isip ng manipis
Progress: 0.58
translated_text: I mean walang pinsala | Sinadya ko lang tulungan ka | Hindi niya inisip na saktan ako | Naisipan naming bumalik ng maaga ng gabing iyon
Progress: 0.58
translated_text: Pag-isipan ang bagay sa pamamagitan ng | Isipin kung gaano kahirap ang buhay sa Russia sa mga araw na ito
Progress: 0.58
translated_text: sipsipin ang lason mula sa lugar na kinagat ng ahas | pagsuso sa isang dayami | sinipsip ng sanggol ang dibdib ng ina
Progress: 0.58
translated_text: Ang espongha ay sumisipsip ng tubig nang maayos | Siya ay nakakuha ng lakas mula sa mga salita ng ministro
Progress: 0.59
translated_text: Pinasuso ng wetnurse ang sanggol | Hindi mo maaaring alagaan ang iyong sanggol sa publiko sa ilang lugar
Progress: 0.59
translated_text: kirot ng panghihinayang | nakaramdam siya ng saksak ng pananabik | twing of conscience
Progress: 0.59
translated_text: ibinigay niya ang kanyang pinakamahusay na pagbaril | kumuha siya ng saksak sa pagtataya
Progress: 0.59
translated_text: isang kahanga-hangang antas ng pagiging prangka | sa anong yugto ang mga agham panlipunan?
Progress: 0.59
translated_text: Ang buong mundo ay isang entablado | nagtakda ito ng yugto para sa mapayapang negosasyon
Progress: 0.59
translated_text: nagsaya kami sa party | ang pagdiriwang pagkatapos ng laro ay isang sabog
Progress: 0.59
translated_text: Itinuro ni Clinton ang kanyang apoy sa Republican Party | inatake ang gobyerno | huwag mo akong bigyan ng anumang flak
Progress: 0.59
translated_text: Sinalakay ng press ang bagong Presidente | Ipinako ng mga kritiko ang may-akda dahil sa pangongopya ng isang sikat na sipi
Progress: 0.59
translated_text: ang biglaang pagkatok sa kanya | nakipag bash siya sa mukha niya | natamaan siya sa ulo
Progress: 0.59
translated_text: sila ay nakakuha ng isang mahusay na putok mula dito | anong boot! | mabilis siyang nagmamadali mula sa pag-iniksyon ng heroin | ginagawa niya ito para sa mga sipa
Progress: 0.59
translated_text: ang kantang iyon ay ang kanyang unang hit at minarkahan ang simula ng kanyang karera | ang bagong palabas sa Broadway ay isang tunay na smasher | sumabog ang party
Progress: 0.59
translated_text: Sinarado ang bintana | Nagpaikot-ikot ang matanda sa bahay
Progress: 0.59
translated_text: Natutulog ang estudyanteng ito sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.59
translated_text: bumangga siya sa poste | tumakbo sampal sa kanya
Progress: 0.59
translated_text: lagi siyang nauuna sa business section | ang kasaysayan ng gawaing ito ay tinalakay sa susunod na seksyon
Progress: 0.59
translated_text: walang seksyon ng bansa ang mas masigasig kaysa sa Timog | may tatlong sinagoga sa seksyong Hudyo
Progress: 0.59
translated_text: isang seksyon ng isang pamingwit | ginamit ang mga seksyon ng metal sa ilalim ng lupa | natapos ang huling bahagi ng kalsada
Progress: 0.59
translated_text: ang nakasulat na bahagi ng pagsusulit | ang seksyon ng pananalapi ng kumpanya | engineering division ng BBC
Progress: 0.59
translated_text: makikita mo ito sa departamento ng hardware | nakakuha siya ng trabaho sa makasaysayang seksyon ng Treasury
Progress: 0.59
translated_text: i-segment ang isang orange | hatiin ang isang tambalang salita
Progress: 0.59
translated_text: nasa school age na siya | matangkad para sa kanyang gulang
Progress: 0.59
translated_text: matagal na tayong magkakilala | Ilang taon at taon na rin akong hindi nakapunta doon
Progress: 0.59
translated_text: ang katandaan ay hindi para sa mga sissies | siya ay nagpapakita ng kanyang mga taon | hindi siya pinabagal ng edad | isang balbas na puti na may eld | sa bingit ng pagiging geezerhood
Progress: 0.59
translated_text: Maganda siyang tumanda | tumatanda tayo araw-araw--nakapanlulumong pag-iisip! | Ang mga kabataang lalaki ay tumatanda
Progress: 0.59
translated_text: maaga silang nagsimula | alam niyang simula pa lang ay siya na ang lalaking para sa kanya
Progress: 0.59
translated_text: ang unang bahay sa kanan | ang unang araw ng tagsibol | ang kanyang unang lahi sa pulitika | ang kanyang unang sanggol | sa unang pagkakataon | ang mga unang pagpupulong ng bagong partido | ang unang yugto ng kanyang pagsasanay
Progress: 0.59
translated_text: ang inaugural na isyu ng magazine | ang yugto ng inisyatiba sa mga negosasyon | isang panimulang hakbang tungo sa isang kasunduan | ang kanyang unang (o dalaga) na talumpati sa Kongreso | ang unang paglalayag ng liner
Progress: 0.59
translated_text: ang simula ng kanta ng tula | ang unang taludtod
Progress: 0.59
translated_text: ay una sa kanyang klase | ang nangungunang pigura sa mga marine artist | ang nangungunang nagtapos
Progress: 0.59
translated_text: unang soprano | ang unang seksyon ng biyolin | tumugtog ng unang sungay
Progress: 0.59
translated_text: Dito muna ako | gawin muna natin itong trabaho
Progress: 0.59
translated_text: sinunod niya ang mga tagubilin sa sulat | sinunod niya ang liham ng batas
Progress: 0.59
translated_text: sinunod niya ang mga tagubilin sa sulat | sinunod niya ang liham ng batas
Progress: 0.59
translated_text: naupo kami buong gabi | kinain ang lahat ng pagkain | lahat ng lalaki ay mortal | lahat ng mga partido ay malugod na tinatanggap
Progress: 0.59
translated_text: siya ay lubos na kumbinsido | ganap na nasiyahan sa pagkain | ito ay ganap na naiiba mula sa kung ano ang aming inaasahan | ay ganap na may kasalanan | isang ganap na bagong sitwasyon | mali lahat ng direksyon | ito ay hindi lahat ng kanyang kasalanan | isang ganap na bagong diskarte | isang buong bagong ideya
Progress: 0.59
translated_text: kumilos | gumawa ng mga hakbang | maghiganti
Progress: 0.59
translated_text: Tumagal ng tatlong oras bago pumasok sa trabaho ngayong umaga | Ang kaganapang ito ay inookupahan ng napakaikling panahon
Progress: 0.59
translated_text: Dinala namin siya sa aming punong | pwede mo ba akong ihatid sa main entrance? | Dinala niya kami sa palasyo
Progress: 0.59
translated_text: Kumuha ng cookie! | Maaari mo bang kunin ang bag na ito, mangyaring
Progress: 0.59
translated_text: Malungkot ang tono ng boses niya | Nagbago ang kwento | pinagtibay niya ang isang hangin ng higit na kahusayan | Nagkaroon siya ng kakaibang ugali | Ipinalalagay ng mga diyos ang anyo ng tao o hayop sa mga pabula na ito
Progress: 0.59
translated_text: Binasa ko ang address na ito bilang isang satire | Paano ko dadalhin ang mensaheng ito? | Hindi ka maaaring kumuha ng kredito para dito!
Progress: 0.59
translated_text: Dalhin mo sa akin ang kahon mula sa kabilang kwarto | Dalhin ang mga liham na ito sa amo | Dinadala ako nito sa pangunahing punto
Progress: 0.59
translated_text: Kinukuha namin ang isang ulila mula sa Romania | Kukuha ako ng tatlong salmon steak
Progress: 0.59
translated_text: Sumasakay siya ng bus papuntang trabaho | Dumadaan siya sa Ruta 1 patungong Newark
Progress: 0.59
translated_text: Kunin ang alinman sa mga card na ito | Pumili ng mabuting asawa para sa iyong anak na babae | Pumili siya ng isang pares ng sapatos mula sa dosenang ipinakita sa kanya ng salesgirl

Progress: 0.59
translated_text: Ang tanging babae na magkakaroon sa kanya ay ang anak na babae ng miller | Hindi ako magkakaroon ng asong ito sa aking bahay! | Mangyaring tanggapin ang aking regalo
Progress: 0.59
translated_text: Kinuha niya ang trabaho bilang direktor ng pag-unlad | siya ay sumasakop sa posisyon ng manager | malapit nang sakupin ng batang prinsipe ang trono
Progress: 0.59
translated_text: Kunin ang kaso ng China | Isaalang-alang ang sumusunod na kaso
Progress: 0.59
translated_text: Kailangan ng lakas ng loob na gawin ang kanyang ginawa | ang tagumpay ay karaniwang nangangailangan ng pagsusumikap | Ang trabahong ito ay humihingi ng maraming pasensya at kasanayan | Ang posisyon na ito ay nangangailangan ng maraming personal na sakripisyo | Ang hapunan na ito ay nangangailangan ng isang kamangha-manghang dessert | Ang interbensyong ito ay hindi naglalagay ng pahintulot ng isang pasyente
Progress: 0.59
translated_text: Kumuha ng pagsusulit | Sumugod
Progress: 0.60
translated_text: kumuha ng eksena | mag-shoot ng pelikula
Progress: 0.60
translated_text: alisin ang isang banta | alisin ang isang wrapper | Alisin ang maruruming pinggan sa mesa | kunin mo ang baril sa iyong bulsa | Ang makinang ito ay nag-aalis ng init mula sa kapaligiran
Progress: 0.60
translated_text: Magkaroon ng isa pang mangkok ng sopas ng manok! | Hindi ako kumukuha ng asukal sa aking kape
Progress: 0.60
translated_text: makipagsapalaran | kumuha ng pagkakataon
Progress: 0.60
translated_text: Kinuha ni Hitler ang Baltic Republics | Kinuha ng hukbo ang kuta sa burol
Progress: 0.60
translated_text: Ipinapalagay niya ang posisyong lotus | Umupo siya sa entablado | Umupo kami sa aming mga upuan sa orkestra | Umayos siya ng pwesto sa likod ng puno | mag-pose
Progress: 0.60
translated_text: tumanggap ng mga mag-aaral para sa graduate study | Kailangan nating bumoto kung papapasok o hindi ng bagong miyembro
Progress: 0.60
translated_text: kumuha ng pulso | Isang pagbabasa ang kinuha sa pagyanig ng lupa
Progress: 0.60
translated_text: tatlong buhay ang binawian ng aksidente | Ang pagsusumikap ay kinuha nito sa kanya
Progress: 0.60
translated_text: Ang nakatakas na bilanggo ay dinala sa mga burol | Ginawa namin para sa mga bundok
Progress: 0.60
translated_text: Mangyaring huwag tutok sa iyong nakababatang kapatid! | Sinanay niya ang kanyang baril sa magnanakaw | Huwag sanayin ang iyong camera sa mga babae | Mag-swipe sa kalaban
Progress: 0.60
translated_text: magkasakit | madalang lasing
Progress: 0.60
translated_text: Lagi siyang kumukuha ng payong | Lagi akong may dalang pera | Nag-impake siya ng baril kapag siya ay pumunta sa mga bundok
Progress: 0.60
translated_text: Kumuha kami ng apartment sa isang tahimik na kalye | Magrenta tayo ng kotse | Kukuha ba tayo ng gabay sa Roma?
Progress: 0.60
translated_text: Hindi kukunin ng kahong ito ang lahat ng item | Ang prasko ay may hawak na isang galon
Progress: 0.60
translated_text: Kinukuha ng nanalo ang lahat | Kinuha niya ang unang gantimpala
Progress: 0.60
translated_text: Nagkaroon siya ng AIDS | Siya ay nagkaroon ng pneumonia | Nanlamig siya
Progress: 0.60
translated_text: Hindi ko matanggap ang dogma ng simbahang ito | tumanggap ng argumento
Progress: 0.60
translated_text: Ang tanging babae na magkakaroon sa kanya ay ang anak na babae ng miller | Hindi ako magkakaroon ng asong ito sa aking bahay! | Mangyaring tanggapin ang aking regalo
Progress: 0.60
translated_text: Hindi ko matatanggap ang iyong imbitasyon | Pupunta ako para sa resolusyong ito
Progress: 0.60
translated_text: Hindi tinanggap ng mga tao ang atonal na musika noong panahong iyon | Tinatanggap namin ang ideya ng pangkalahatang pangangalaga sa kalusugan
Progress: 0.60
translated_text: tumanggap ng mga mag-aaral para sa graduate study | Kailangan nating bumoto kung papapasok o hindi ng bagong miyembro
Progress: 0.60
translated_text: Tatanggapin ko ang mga singil | Pumayag siyang pasanin ang responsibilidad
Progress: 0.60
translated_text: Kailangan kong tanggapin ang mga hindi kanais-nais na kondisyon sa pagtatrabaho | Nilunok ko ang insulto | Natuto siyang mamuhay kasama ang maliliit na katangi-tangi ng kanyang asawa
Progress: 0.60
translated_text: makipagsapalaran | kumuha ng pagkakataon
Progress: 0.60
translated_text: tumanggap ng bayad | makatanggap ng regalo | tumanggap ng mga liham mula sa harapan
Progress: 0.60
translated_text: Ang mga aspetong ito ng sibilisasyon ay hindi nakakahanap ng pagpapahayag o tumatanggap ng interpretasyon | Nakatanggap ng magandang review ang kanyang pelikula | Wala akong nakuha kundi gulo para sa aking mabuting hangarin
Progress: 0.60
translated_text: makakuha ng ideya | makaranas ng vertigo | nasusuka | tumanggap ng mga pinsala | magkaroon ng pakiramdam
Progress: 0.60
translated_text: ang kumbinasyon sa ligtas ay isang sikreto | sinubukan niyang ilihim ang pag-inom
Progress: 0.60
translated_text: kung paano ito lumabas ay isang misteryo | nananatili itong isa sa mga lihim ng kalikasan
Progress: 0.60
translated_text: isang lihim na formula | lihim na sangkap | mga lihim na pag-uusap
Progress: 0.60
translated_text: lihim na pagpapatakbo ng katalinuhan | cloak-and-dagger na aktibidad sa likod ng mga linya ng kaaway | butas-butas na intriga | mga lihim na misyon | isang lihim na ahente | lihim na pagbebenta ng armas | palihim na pagpapakilos ng mga tropa | isang undercover na imbestigasyon | paglaban sa ilalim ng lupa
Progress: 0.60
translated_text: isang lihim na kasal | isang secret bride
Progress: 0.60
translated_text: ang kanilang lihim na senyales ay isang kindat | mga lihim na mensahe
Progress: 0.60
translated_text: isang tagong silid o lugar ng pagtatago gaya ng butas ng pari | isang lihim na daanan | ang secret compartment sa desk
Progress: 0.60
translated_text: isang pribadong lugar upang magpahinga at mag-isip | isang liblib na romantikong lugar | isang lihim na hardin
Progress: 0.60
translated_text: ang kaayusan na ito ay dapat panatilihing kumpidensyal | ang kanilang mga lihim na komunikasyon
Progress: 0.60
translated_text: mahiwagang simbolo | ang mystical style ni Blake | lihim na kaalaman | ang lihim na pagkatuto ng mga sinaunang tao
Progress: 0.60
translated_text: ang kumbinasyon sa ligtas ay isang sikreto | sinubukan niyang ilihim ang pag-inom
Progress: 0.60
translated_text: kung paano ito lumabas ay isang misteryo | nananatili itong isa sa mga lihim ng kalikasan
Progress: 0.60
translated_text: isang lihim na formula | lihim na sangkap | mga lihim na pag-uusap
Progress: 0.60
translated_text: lihim na pagpapatakbo ng katalinuhan | cloak-and-dagger na aktibidad sa likod ng mga linya ng kaaway | butas-butas na intriga | mga lihim na misyon | isang lihim na ahente | lihim na pagbebenta ng armas | palihim na pagpapakilos ng mga tropa | isang undercover na imbestigasyon | paglaban sa ilalim ng lupa
Progress: 0.60
translated_text: isang lihim na kasal | isang secret bride
Progress: 0.60
translated_text: ang kanilang lihim na senyales ay isang kindat | mga lihim na mensahe
Progress: 0.60
translated_text: isang tagong silid o lugar ng pagtatago gaya ng butas ng pari | isang lihim na daanan | ang secret compartment sa desk
Progress: 0.60
translated_text: isang pribadong lugar upang magpahinga at mag-isip | isang liblib na romantikong lugar | isang lihim na hardin
Progress: 0.60
translated_text: ang kaayusan na ito ay dapat panatilihing kumpidensyal | ang kanilang mga lihim na komunikasyon
Progress: 0.60
translated_text: mahiwagang simbolo | ang mystical style ni Blake | lihim na kaalaman | ang lihim na pagkatuto ng mga sinaunang tao
Progress: 0.60
translated_text: mga guhit ng abstract forms | gumawa siya ng mga kumplikadong guhit na panulat at tinta tulad ng mga miniature sa medieval
Progress: 0.60
translated_text: gumuhit ng kariton | hilahin ang isang kareta
Progress: 0.61
translated_text: gumuhit ng linya | bakas ang balangkas ng isang pigura sa buhangin
Progress: 0.61
translated_text: Gumuhit ako ng linya dito | gumawa ng konklusyon | gumuhit ng mga parallel | gumawa ng pagtatantya | Ano ang masasabi mo sa kanyang mga pahayag?
Progress: 0.61
translated_text: gumuhit ng sandata | bumunot ng baril | Tinutukan ng magnanakaw ang kanyang biktima ng kutsilyo

Progress: 0.61
translated_text: Siya ay gumuhit ng isang elepante | Gumuhit ako ng kabayo
Progress: 0.61
translated_text: Ang mga komento ng Pangulo ay umani ng matalas na batikos mula sa mga Republican | Humugot ng tawa ang komedyante
Progress: 0.61
translated_text: huminga ng malalim | gumuhit sa isang sigarilyo
Progress: 0.61
translated_text: Nakakuha siya ng $2,000 mula sa account na | Ang mga doktor ay kumuha ng mga medikal na suplay mula sa emergency bank ng ospital
Progress: 0.61
translated_text: gumuhit ng card | magparami
Progress: 0.61
translated_text: Nadala siya sa kawalan ng pag-asa | Tumanggi ang Pangulo na madala sa pagbibigay ng ultimatum | Natapos na ang session
Progress: 0.61
translated_text: iguhit ang shades | iguhit ang mga kurtina
Progress: 0.61
translated_text: Ang espongha ay sumisipsip ng tubig nang maayos | Siya ay nakakuha ng lakas mula sa mga salita ng ministro
Progress: 0.61
translated_text: Ang kanyang kagwapuhan ay umaakit sa mga titig ng maraming lalaki | Ang ad ay nakakuha ng maraming potensyal na customer | Ang piyanistang ito ay humihila ng napakaraming tao | Natuwa ang may-ari ng tindahan na nakakuha ang ad ng maraming bagong customer
Progress: 0.61
translated_text: string na perlas sa isang string | ang bata ay gumuhit ng mga kuwintas na salamin sa isang string | sinulid na pinatuyong cranberry
Progress: 0.61
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.61
translated_text: ang linya ng mga sundalo ay sumulong sa kanilang mga bayoneta na naayos | sila ay nakaayos sa linya ng labanan | pumila ang cast para sa curtain call
Progress: 0.61
translated_text: malinaw na nakaunat ang linya sa kanto | kailangan mong maghintay sa mahabang pila sa checkout counter
Progress: 0.61
translated_text: ang liham ay binubuo ng tatlong maikling linya | may anim na linya sa bawat saknong
Progress: 0.61
translated_text: ang gobyerno ay kumuha ng matatag na kurso | ang mga istoryador ay maaari lamang ituro ang mga linyang iyon kung saan magagamit ang ebidensya
Progress: 0.61
translated_text: maraming linya ang mukha niya | ang pamamalantsa ay nakakaalis ng karamihan sa mga wrinkles
Progress: 0.61
translated_text: alinsunod sa | lumabas siya sa linya | daliri sa linya
Progress: 0.61
translated_text: dapat itong dumaan sa mga opisyal na channel | Ang mga linya ng komunikasyon ay nai-set up sa pagitan ng dalawang kumpanya
Progress: 0.61
translated_text: `hayaan kong ipakita sa iyo ang aking mga ukit&#39; ay medyo pagod na linya | makinis ang linya niya pero hindi ako nahulog dito | ang tinderong iyon ay dapat na nagpraktis ng kanyang mabilis na linya ng pagsasalita
Progress: 0.61
translated_text: linya ang mga guwantes | linya ng tsimenea
Progress: 0.61
translated_text: gumuhit ng linya | bakas ang balangkas ng isang pigura sa buhangin
Progress: 0.61
translated_text: Ipinangako niya ang kanyang sarili sa gawain ng Diyos | ibigay ang mga talento sa isang mabuting layunin | italaga ang iyong buhay sa simbahan
Progress: 0.61
translated_text: sinimulan niya ito | Binigyan ko ito ng umiikot
Progress: 0.61
translated_text: Nag-aalok ang conference center ng health spa | Nag-aalok ang hotel ng mga pribadong meeting room
Progress: 0.61
translated_text: Nagboluntaryo siyang ihatid ang matandang babae sa bahay | Nag-alok akong tumulong sa mga pinggan ngunit hindi ito narinig ng babaing punong-abala
Progress: 0.61
translated_text: ipaabot ang aking pagbati | Inialay niya ang kanyang pakikiramay
Progress: 0.61
translated_text: maglagay ng magandang laban | nag-aalok ng pagtutol
Progress: 0.61
translated_text: mag-extend ng loan | Nag-aalok ang bangko ng magandang deal sa mga bagong mortgage
Progress: 0.61
translated_text: nag-pop siya ng tanong noong Linggo ng gabi | nag-propose siya ng kasal sa lalaking kilala niya sa loob lang ng dalawang buwan | Sa wakas ay nagpahayag ang matandang bachelor sa dalaga
Progress: 0.61
translated_text: binawasan ng gobyerno ang buwis | ang usapin ay isinangguni sa mas mataas na awtoridad
Progress: 0.61
translated_text: mga regulasyon para sa pamamahala ng mga bilangguan ng estado | siya ay may malaking karanasan sa pamahalaan
Progress: 0.61
translated_text: binawasan ng gobyerno ang buwis | ang usapin ay isinangguni sa mas mataas na awtoridad
Progress: 0.61
translated_text: mga regulasyon para sa pamamahala ng mga bilangguan ng estado | siya ay may malaking karanasan sa pamahalaan
Progress: 0.61
translated_text: may awtoridad siyang mag-isyu ng mga warrant | binibigyan ng awtorisasyon ang mga kinatawan na magsagawa ng mga pag-aresto | isang lugar ng potency sa estado
Progress: 0.61
translated_text: ang kanyang katiyakan sa kanyang kataasan ay hindi nagpatanyag sa kanya | pagkatapos ng kabiguan na iyon ay nawalan siya ng tiwala | may awtoridad siyang nagsalita
Progress: 0.61
translated_text: ang Central Intelligence Agency | ang Census Bureau | Opisina ng Pamamahala at Badyet | Tennessee Valley Authority
Progress: 0.61
translated_text: nagpasya silang muling iposisyon ang kanilang mga kasangkapan sa isang inirerekomendang imbakan sa Brooklyn | ang aking sasakyan ay nasa imbakan | binawasan ng mga publisher ang pag-print upang mabawasan ang halaga ng warehousing
Progress: 0.61
translated_text: ang uring manggagawa | isang umuusbong na propesyonal na klase
Progress: 0.61
translated_text: kumuha siya ng kursong basket weaving | Ang paglalandi ay hindi kilala sa mga klase sa kolehiyo
Progress: 0.61
translated_text: naglaro siya ng baseball sa klase D sa loob ng dalawang taon | Si Princeton ay nasa NCAA Division 1-AA
Progress: 0.61
translated_text: ang klase ng &#39;97 | siya ay nasa aking taon sa Hoehandle High
Progress: 0.61
translated_text: ang kalidad ng mga mag-aaral ay tumaas | isang executive ng mababang kalibre
Progress: 0.61
translated_text: bawat bayan ay may sariling kalidad | ang radikal na katangian ng ating mga hinihingi
Progress: 0.61
translated_text: ang timbre ng kanyang soprano ay mayaman at kaibig-ibig | ang mga muffled na tono ng sirang kampana ay nagpatawag sa kanila upang magkita
Progress: 0.61
translated_text: piniling mga alak | pangunahing karne ng baka | premyong carnation | de-kalidad na papel | pumili ng mga milokoton
Progress: 0.61
translated_text: mga taong may kalidad | isang dekalidad na pamilya
Progress: 0.61
translated_text: magagawa niya ito mula sa memorya | natutuwa siyang maalala ang kanyang ama
Progress: 0.61
translated_text: Ang tagapagsalita na ito ay nag-uutos ng mataas na bayad | Ang may-akda ay nag-uutos ng isang patas na pagdinig mula sa kanyang mga mambabasa
Progress: 0.62
translated_text: kontrolin ang badyet | Command ang pwersang militar
Progress: 0.62
translated_text: chemistry is not my cup of tea | ang kanyang bag ngayon ay natututong maglaro ng golf | ang pag-aasawa ay halos hindi niya ulam
Progress: 0.62
translated_text: Naghahain kami ng mga pagkain para sa mga walang tirahan | Inihain niya ang sopas noong 8 PM | Ang mga entertainer ay naghain ng isang masiglang palabas
Progress: 0.62
translated_text: chemistry is not my cup of tea | ang kanyang bag ngayon ay natututong maglaro ng golf | ang pag-aasawa ay halos hindi niya ulam
Progress: 0.62
translated_text: Naghahain kami ng mga pagkain para sa mga walang tirahan | Inihain niya ang sopas noong 8 PM | Ang mga entertainer ay naghain ng isang masiglang palabas
Progress: 0.62
translated_text: Bumagsak siya sa kama | Napaupo siya sa upuan
Progress: 0.62
translated_text: Ang araw ay lumubog sa ilalim ng abot-tanaw | Ang lumulubog na araw ay lumubog sa ilalim ng linya ng puno
Progress: 0.62
translated_text: Nasubsob siya sa couch | Lumubog ang aking diwa
Progress: 0.62
translated_text: Ibinaon niya ang kanyang mga daliri sa malambot na buhangin | Ibinaon niya ang kanyang ulo sa kandungan niya
Progress: 0.62
translated_text: ang laki na ng sitwasyon | she hates me, ang laki naman nun
Progress: 0.62
translated_text: namula siya nang makita ang laki ng bill | ang tanging lungsod ng anumang laki sa lugar na iyon
Progress: 0.62
translated_text: ang economic-size package | katamtamang laki ng bahay

Progress: 0.62
translated_text: sinusubukang mawalan ng labis na timbang | natagpuan ang ilang dagdag na pagbabago na nakalagay sa tokador | isa pang libro sa heraldry ay maaaring isipin na kalabisan | mga kasanayang ginawang kalabisan ng pagsulong ng teknolohiya | natutulog sa ekstrang silid | supernumerary ornamentation | ito ay supererogatory ng kanyang upang matuwa | tanggalin ang mga kalabisan (o hindi kailangan) na mga salita | dagdag na tadyang pati na rin ang iba pang supernumerary na panloob na mga bahagi | labis na keso na ipinamahagi sa mga nangangailangan
Progress: 0.62
translated_text: isang espesyal na flight holiday | ilagay sa mga espesyal na bus para sa malaking laro
Progress: 0.62
translated_text: nanawagan para sa karagdagang tropa | kailangan ng karagdagang tulong | isang dagdag na pares ng sapatos
Progress: 0.62
translated_text: iba ang opinyon ko sa opinyon mo | Hindi ako sa iyong panghihikayat | ano ang iyong mga saloobin sa Haiti?
Progress: 0.62
translated_text: ang kanyang impression sa kanya ay kanais-nais | ano ang iyong damdamin tungkol sa krisis? | pinatibay nito ang aking paniniwala sa kanyang katapatan | Naramdaman kong nagsisinungaling siya
Progress: 0.62
translated_text: ang kanyang panunungkulan ay kasabay ng kaguluhan sa Cuba | ang Nazi assumption of power noong 1934 | nakuha niya ang lahat ng ari-arian ng kumpanya sa halagang sampung milyong dolyar at ang pagpapalagay ng mga utang ng kumpanya
Progress: 0.62
translated_text: mga imahe ng kaisipan ng masasayang panahon | mga kalkulasyon ng kaisipan | sa isang kahila-hilakbot na estado ng pag-iisip | pagdurusa sa isip | malaya sa mga depekto sa pag-iisip
Progress: 0.62
translated_text: kapangyarihang pangkaisipan | pag-unlad ng kaisipan | kalinisan ng isip
Progress: 0.62
translated_text: isang mental na pasyente | sakit sa pag-iisip
Progress: 0.62
translated_text: iba ang opinyon ko sa opinyon mo | Hindi ako sa iyong panghihikayat | ano ang iyong mga saloobin sa Haiti?
Progress: 0.62
translated_text: ang kanyang impression sa kanya ay kanais-nais | ano ang iyong damdamin tungkol sa krisis? | pinatibay nito ang aking paniniwala sa kanyang katapatan | Naramdaman kong nagsisinungaling siya
Progress: 0.62
translated_text: ang kanyang impression sa kanya ay kanais-nais | ano ang iyong damdamin tungkol sa krisis? | pinatibay nito ang aking paniniwala sa kanyang katapatan | Naramdaman kong nagsisinungaling siya
Progress: 0.62
translated_text: ang theatrical notion of disguise ay nauugnay sa kalamidad sa kanyang mga kwento | nagkaroon siya ng kapritso tungkol sa paglipad sa buwan | Ang kapritso ay maaaring maging nakakatawa sa isang taong may oras upang tamasahin ito
Progress: 0.62
translated_text: nagkaroon siya ng pakiramdam ng euphoria | siya ay nagkaroon ng kahila-hilakbot na damdamin ng pagkakasala | Hindi ko siya nagustuhan at mutual ang pakiramdam
Progress: 0.62
translated_text: ang kanyang impression sa kanya ay kanais-nais | ano ang iyong damdamin tungkol sa krisis? | pinatibay nito ang aking paniniwala sa kanyang katapatan | Naramdaman kong nagsisinungaling siya
Progress: 0.62
translated_text: ang pakiramdam ng lungsod ay nasasabik sa kanya | pinagbuti ng isang klerigo ang tono ng pulong | ito ay may amoy ng pagtataksil
Progress: 0.62
translated_text: nagkaroon siya ng malabong pakiramdam | May kakaiba akong naramdaman sa binti ko | nawala lahat ng nararamdaman niya sa braso niya
Progress: 0.62
translated_text: gusto niya ang dampi ng seda sa kanyang balat | ang ibabaw ay nagkaroon ng mamantika na pakiramdam
Progress: 0.62
translated_text: Nakaramdam siya ng sama ng loob | Nakaramdam siya ng panghihinayang
Progress: 0.62
translated_text: Feeling ko hindi niya ako gusto | I find him to be obnoxious | Nakita kong medyo nakakaaliw ang pelikula
Progress: 0.62
translated_text: Naramdaman niya ang hangin | Naramdaman niya ang isang bagay na humahaplos sa kanyang braso | Naramdaman niyang gumapang ang kanyang laman | Naramdaman niya ang init nang bumaba siya ng sasakyan
Progress: 0.62
translated_text: Nawala na ang sipon ko--ayos na ang pakiramdam ko ngayon | Nakaramdam siya ng pagod pagkatapos ng mahabang paglalakad | Nalungkot siya pagkatapos ng pagkawala niya
Progress: 0.62
translated_text: Pakiramdam niya ay maliit at hindi gaanong mahalaga | Pinaparamdam mo sa akin na nakahubad | Naiiba ko ang pakiramdam ng mga estudyante sa kanilang sarili
Progress: 0.62
translated_text: Naramdaman namin ang epekto ng inflation | dinama ng kanyang mga daliri ang string quartet | naramdaman niya ang paghamak nito sa kanya
Progress: 0.62
translated_text: Nanginginig ang lupa | Ang mga kumot ay malambot
Progress: 0.62
translated_text: Pakiramdam ang malambot na tela na ito! | Pininger ng customer ang sweater
Progress: 0.62
translated_text: Dinampot ng nurse ang tiyan ng pasyente | Naramdaman ng runner ang kanyang pulso
Progress: 0.62
translated_text: ang isang Cadillac ay gumagawa ng isang pahayag tungkol sa kung sino ka | ang kanyang mga tantrums ay isang pahayag ng kanyang pangangailangan para sa atensyon
Progress: 0.62
translated_text: inamin ng hukom ang pagiging newsworthiness ng paglilitis | hindi na siya balita sa fashion world
Progress: 0.62
translated_text: Pinag-aralan ni Leonardo ang katawan ng tao | malakas ang pangangatawan niya | kusa ang espiritu ngunit mahina ang laman
Progress: 0.62
translated_text: ang komposisyon ay nagpapakita ng mga problema para sa mga mag-aaral ng musikal na anyo | ang isang visual na pattern ay dapat isama hindi lamang ang mga bagay ngunit ang mga puwang sa pagitan ng mga ito
Progress: 0.62
translated_text: karanasan madalas na tumutukoy sa kakayahan | hubugin ang opinyon ng publiko
Progress: 0.62
translated_text: Maingat niyang hinulma ang mga rice ball | Bumuo ng mga silindro mula sa kuwarta | hugis ng pigura | Gawing espada ang metal
Progress: 0.62
translated_text: hubugin ang kuwarta | bumuo ng karakter ng bata
Progress: 0.62
translated_text: Naputol ang sasakyan sa kaliwa sa intersection | Lumiko sa kanan ang motor
Progress: 0.62
translated_text: Ang daan ay umiikot sa lawa | ang landas na baluktot sa kagubatan
Progress: 0.62
translated_text: kanyang likod arko | maganda ang hubog ng kanyang balakang
Progress: 0.62
translated_text: Pinihit niya ang kanyang hintuturo | kurbadong matindi ang daan
Progress: 0.63
translated_text: ang mga hubog na pangil ng isang walrus | ang kanyang mga hubog na labi ay nagmumungkahi ng isang ngiti ngunit ang kanyang mga mata ay matigas
Progress: 0.63
translated_text: isang taong may karanasan | karanasan ay ang pinakamahusay na guro
Progress: 0.63
translated_text: nagkaroon siya ng karanasan sa relihiyon | matingkad niyang naalala ang karanasan
Progress: 0.63
translated_text: isang nakakagulat na karanasan | tiyak na nakuha ng aming pansin ang masakit na karanasang iyon
Progress: 0.63
translated_text: Marami kaming pagsubok na pinagdaanan | nakakita siya ng aksyon sa Viet Nam
Progress: 0.63
translated_text: Alam ko ang pakiramdam! | nalaman mo na ba ang gutom? | Nabuhay ako sa isang uri ng impiyerno noong ako ay isang adik sa droga | Ang mga nakaligtas sa holocaust ay nabuhay ng isang bangungot | Nabuhay ako sa dalawang diborsyo
Progress: 0.63
translated_text: makakuha ng ideya | makaranas ng vertigo | nasusuka | tumanggap ng mga pinsala | magkaroon ng pakiramdam
Progress: 0.63
translated_text: Nakaramdam siya ng sama ng loob | Nakaramdam siya ng panghihinayang
Progress: 0.63
translated_text: ang mundo ngayon | ngayon mayroon kaming mga computer
Progress: 0.63
translated_text: Ngayon ay maganda | nakita mo ba ang pahayagan ngayon?
Progress: 0.63
translated_text: sa pamamagitan lamang ng kanilang wika ang mga nakatataas na uri sa kasalukuyan ay nakikilala | bihira na tayong makakita ng mga sasakyang hinihila ng kabayo sa mga lansangan ng lungsod | ngayon halos lahat ng tahanan ay may telebisyon
Progress: 0.63
translated_text: may respeto siya sa kanyang mga karibal | gusto niyang malaman kung ano ang ginagawa ng kompetisyon
Progress: 0.63
translated_text: isang magandang isport | isang mahinang isport
Progress: 0.63
translated_text: naging figure of fun siya | sinabi niya ito sa isport
Progress: 0.63
translated_text: Ang mga bata ay nagsasaya sa hardin | ang gamboling tupa sa parang | Ang mga paslit ay gumagala sa playroom

Progress: 0.63
translated_text: Trabaho ang lupa | linangin ang lupa
Progress: 0.63
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.63
translated_text: domesticate oats | paamuin ang lupa
Progress: 0.63
translated_text: binati niya sila sa kanilang pagbuo ng isang plano para matugunan ang emergency | pinondohan nila ang pananaliksik at pagpapaunlad
Progress: 0.63
translated_text: ang pagbuo ng kanyang mga ideya ay tumagal ng maraming taon | ang ebolusyon ng sibilisasyong Griyego | ang mabagal na pag-unlad ng kanyang kakayahan bilang isang manunulat
Progress: 0.63
translated_text: kamakailang mga pag-unlad sa Iraq | nakakapanghinayang pag-unlad!
Progress: 0.63
translated_text: ang pag-unlad ng mga mapagkukunan ng Alaska | ang pagsasamantala sa mga deposito ng tanso
Progress: 0.63
translated_text: pagkatapos niyang makita ang pinakahuling pag-unlad ay nagbago ang kanyang isip at naging tagasuporta | sa chess dapat mong alagaan ang iyong pag-unlad bago ilipat ang iyong reyna
Progress: 0.63
translated_text: bawasan ang iyong pang-araw-araw na paggamit ng taba | Gusto ng employer na bawasan ang mga benepisyong pangkalusugan
Progress: 0.63
translated_text: Ang mainit na tubig ay magpapaliit sa sweater | Maaari mo bang paliitin ang larawang ito?
Progress: 0.63
translated_text: Ipinagbabawal ng gobyerno ang anumang pagtatangka ng isang pag-aalsa | Pinipigilan ng China ang kanyang mga dissidents nang napakahusay | Sinakop ng mga mayamang may-ari ng lupa ang mga magsasaka na nagtatrabaho sa lupa
Progress: 0.63
translated_text: isang kondisyon (o estado) ng pagkasira | ang kasalukuyang katayuan ng negosasyon sa armas
Progress: 0.63
translated_text: isang kondisyon sa puso | isang kondisyon ng balat
Progress: 0.63
translated_text: itinakda ng kontrata ang mga kondisyon ng pag-upa | ang mga tuntunin ng kasunduan ay mapagbigay
Progress: 0.63
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.63
translated_text: Nakasaad sa testamento na maaari siyang manirahan sa bahay habang buhay | Ang kontrata ay nagtatakda ng mga petsa ng mga pagbabayad
Progress: 0.63
translated_text: masamang reaksyon sa gamot | ang kanyang mga tugon ay bumagal sa edad
Progress: 0.63
translated_text: Naghintay ako ng ilang araw para sa kanyang sagot | sumulat siya ng mga tugon sa ilan sa kanyang mga kritiko
Progress: 0.63
translated_text: ang Central Intelligence Agency | ang Census Bureau | Opisina ng Pamamahala at Badyet | Tennessee Valley Authority
Progress: 0.63
translated_text: ang tungkulin ng isang guro | dapat gawin ng gobyerno ang bahagi nito | gampanan ang papel nito
Progress: 0.63
translated_text: ang pagiging nasa katungkulan ay nagbibigay na ng malaking kalamangan sa isang kandidato | noong unang taon niya sa panunungkulan | noong unang taon niya sa kapangyarihan | kapangyarihan ng pangulo
Progress: 0.63
translated_text: Ipinamana sa akin ng aking tiyahin ang lahat ng kanyang alahas | Iniwan sa akin ng aking lolo ang kanyang buong ari-arian
Progress: 0.63
translated_text: isang kusang kalahok | mga kusang katulong
Progress: 0.63
translated_text: Pinahihintulutan nito ang tubig na dumaloy sa | Ang selyadong pinto na ito ay hindi papayag na pumasok ang tubig sa basement | Papayagan nito ang pag-ulan
Progress: 0.63
translated_text: Pinayagan niya ang kanyang anak na bisitahin ang kanyang nawalay na asawa | Hindi ko hahayaang hanapin ng mga pulis ang kanyang basement | Hindi ako papayag na makita mo ang iyong pagsusulit
Progress: 0.63
translated_text: Nakuha niya ang kanyang squad sa bola | Pinapasok ako nito para sa isang malaking sorpresa | May dinadala siyang babae sa gulo
Progress: 0.63
translated_text: ang kanyang layunin ay magbigay ng bagong pagsasalin | hindi sapat ang mabuting hangarin | ito ay nilikha na may mulat na layunin ng pagsagot sa mga kagyat na pangangailangan | hindi niya inilihim ang kanyang mga disenyo
Progress: 0.63
translated_text: ang function ng auger ay magbutas ng mga butas | ang ganda ng balete pero anong silbi nito?
Progress: 0.63
translated_text: ang kanyang determinasyon ay makikita sa kanyang bawat galaw | siya ay isang taong may layunin
Progress: 0.63
translated_text: ang kanyang layunin ay magbigay ng bagong pagsasalin | hindi sapat ang mabuting hangarin | ito ay nilikha na may mulat na layunin ng pagsagot sa mga kagyat na pangangailangan | hindi niya inilihim ang kanyang mga disenyo
Progress: 0.63
translated_text: ang function ng auger ay magbutas ng mga butas | ang ganda ng balete pero anong silbi nito?
Progress: 0.63
translated_text: ang kanyang determinasyon ay makikita sa kanyang bawat galaw | siya ay isang taong may layunin
Progress: 0.63
translated_text: ang pokus ng aktibidad ay lumipat sa molecular biology | wala siyang direksyon sa buhay niya
Progress: 0.63
translated_text: nakatutok | wala sa focus
Progress: 0.63
translated_text: ipinapalagay ng kabihasnan ang paggalang sa batas | ang malaking problema para sa jurisprudence na payagan ang kalayaan habang nagpapatupad ng kaayusan
Progress: 0.64
translated_text: chemistry is not my cup of tea | ang kanyang bag ngayon ay natututong maglaro ng golf | ang pag-aasawa ay halos hindi niya ulam
Progress: 0.64
translated_text: Naghahain kami ng mga pagkain para sa mga walang tirahan | Inihain niya ang sopas noong 8 PM | Ang mga entertainer ay naghain ng isang masiglang palabas
Progress: 0.64
translated_text: bumagsak sa isang puno | Tinamaan ng kidlat ang mga hiker
Progress: 0.64
translated_text: Ang oras ay lumilipad na parang arrow | Ang oras ay tumatakbo sa ilalim niya
Progress: 0.64
translated_text: Nahulog ang sanga mula sa puno | Ang kapus-palad na hiker ay nahulog sa isang siwang
Progress: 0.64
translated_text: Bumababa ang temperatura | Ang barometro ay bumabagsak | Nahulog ang kurtina sa diba | Tumaas ang kamay niya saka bumagsak ulit
Progress: 0.64
translated_text: mahulog sa isang bitag | Nagkasakit siya | Nawalan sila ng pabor | Umibig | matulog | mabiktima ng isang impostor | nahulog sa kakaibang paraan ng pag-iisip | nahulog siya sa mga piraso pagkatapos niyang mawalan ng trabaho
Progress: 0.64
translated_text: nabibilang sa isang kategorya | Ito ay nasa ilalim ng isang bagong heading
Progress: 0.64
translated_text: ulan, niyebe at sleet ay bumabagsak | Pinaulanan ni Vesuvius ang nagniningas at mapanirang galit nito sa Herculaneum
Progress: 0.64
translated_text: Dapat tayong tumayo o mahulog | mahulog sa tabi ng daan
Progress: 0.64
translated_text: Maraming sundalo ang nahulog sa Verdun | Ilang usa ang nahulog sa parehong baril | Patay ang biktima ng pamamaril
Progress: 0.64
translated_text: Nahulog ang liwanag sa kanyang mukha | Sumikat ang araw sa mga bukid | Tumama ang liwanag sa gintong kwintas | Isang kakaibang tunog ang tumama sa aking tenga
Progress: 0.64
translated_text: Ang Pasko ay bumagsak sa isang Lunes ngayong taon | Ang impit ay nahuhulog sa unang pantig
Progress: 0.64
translated_text: Bumaba ang dami ng takdang-aralin sa pagtatapos ng semestre | Ang presyon ng cabin ay bumaba nang husto | ang kanyang timbang ay bumaba sa ilalim ng isang daang pounds | bumulong ang boses niya
Progress: 0.64
translated_text: Bumagsak ang gobyerno sa magdamag | Bumagsak ang Dinastiyang Qing kasama si Sun Yat-sen
Progress: 0.64
translated_text: Ang pinakamahirap na gawain ay nahulog sa pinakabatang miyembro ng koponan | Ang responsibilidad ay nahulog sa amin | Ang pressure na magtagumpay ay nahulog sa pinakabatang estudyante
Progress: 0.64
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.64
translated_text: Ang ari-arian ay nahulog sa aking kapatid na babae | Ibinalik ang lupa sa pamilya | Ang ari-arian ay ipinagkaloob sa isang tagapagmana na ipinapalagay ng lahat na patay na
Progress: 0.64
translated_text: Nahulog ang plorera at natapon ang tubig sa mesa | Bumagsak ang kanyang buhok sa kanyang noo
Progress: 0.64
translated_text: Nahulog siya sa kanyang upuan | Napaluhod siya
Progress: 0.64
translated_text: Ang damit na ito ay nakabitin nang maayos | Ang mahaba niyang itim na buhok ay dumaloy sa kanyang likuran

Progress: 0.64
translated_text: Bumagsak ang mukha niya nang mabalitaan niyang matatanggal siya sa trabaho | nahulog ang kanyang taluktok
Progress: 0.64
translated_text: Sumapit ang gabi | Bumagsak ang katahimikan
Progress: 0.64
translated_text: isang barbarous na krimen | brutal na pambubugbog | malupit na pagpapahirap | Ang magaspang na pagtrato ni Stalin sa mga kulak | isang mabangis na sampal | masasamang sipa
Progress: 0.64
translated_text: bumagsak sa isang puno | Tinamaan ng kidlat ang mga hiker
Progress: 0.64
translated_text: Ang oras ay lumilipad na parang arrow | Ang oras ay tumatakbo sa ilalim niya
Progress: 0.64
translated_text: Nahulog ang sanga mula sa puno | Ang kapus-palad na hiker ay nahulog sa isang siwang
Progress: 0.64
translated_text: Bumababa ang temperatura | Ang barometro ay bumabagsak | Nahulog ang kurtina sa diba | Tumaas ang kamay niya saka bumagsak ulit
Progress: 0.64
translated_text: mahulog sa isang bitag | Nagkasakit siya | Nawalan sila ng pabor | Umibig | matulog | mabiktima ng isang impostor | nahulog sa kakaibang paraan ng pag-iisip | bumagsak siya pagkatapos niyang mawalan ng trabaho
Progress: 0.64
translated_text: nabibilang sa isang kategorya | Ito ay nasa ilalim ng isang bagong heading
Progress: 0.64
translated_text: ulan, niyebe at sleet ay bumabagsak | Pinaulanan ni Vesuvius ang nagniningas at mapanirang galit nito sa Herculaneum
Progress: 0.64
translated_text: Dapat tayong tumayo o mahulog | mahulog sa tabi ng daan
Progress: 0.64
translated_text: Maraming sundalo ang nahulog sa Verdun | Ilang usa ang nahulog sa parehong baril | Patay ang biktima ng pamamaril
Progress: 0.64
translated_text: Nahulog ang liwanag sa kanyang mukha | Sumikat ang araw sa mga bukid | Tumama ang liwanag sa gintong kwintas | Isang kakaibang tunog ang tumama sa aking tenga
Progress: 0.64
translated_text: Ang Pasko ay bumagsak sa isang Lunes ngayong taon | Ang impit ay nahuhulog sa unang pantig
Progress: 0.64
translated_text: Bumaba ang dami ng takdang-aralin sa pagtatapos ng semestre | Ang presyon ng cabin ay bumaba nang husto | ang kanyang timbang ay bumaba sa ilalim ng isang daang pounds | bumulong ang boses niya
Progress: 0.64
translated_text: Bumagsak ang gobyerno sa magdamag | Bumagsak ang Dinastiyang Qing kasama si Sun Yat-sen
Progress: 0.64
translated_text: Ang pinakamahirap na gawain ay nahulog sa pinakabatang miyembro ng koponan | Ang responsibilidad ay nahulog sa amin | Ang pressure na magtagumpay ay nahulog sa pinakabatang estudyante
Progress: 0.64
translated_text: Ang gawain ay nahulog sa akin | Napunta sa akin na ipaalam sa mga magulang ang mga biktima
Progress: 0.64
translated_text: Ang ari-arian ay nahulog sa aking kapatid na babae | Ibinalik ang lupa sa pamilya | Ang ari-arian ay ipinagkaloob sa isang tagapagmana na ipinapalagay ng lahat na patay na
Progress: 0.64
translated_text: Nahulog ang plorera at natapon ang tubig sa mesa | Bumagsak ang kanyang buhok sa kanyang noo
Progress: 0.64
translated_text: Nahulog siya sa kanyang upuan | Napaluhod siya
Progress: 0.64
translated_text: Ang damit na ito ay nakabitin nang maayos | Ang mahaba niyang itim na buhok ay dumaloy sa kanyang likuran
Progress: 0.64
translated_text: Bumagsak ang mukha niya nang mabalitaan niyang matatanggal siya sa trabaho | nahulog ang kanyang taluktok
Progress: 0.64
translated_text: Sumapit ang gabi | Bumagsak ang katahimikan
Progress: 0.64
translated_text: isang barbarous na krimen | brutal na pambubugbog | malupit na pagpapahirap | Ang magaspang na pagtrato ni Stalin sa mga kulak | isang mabangis na sampal | masasamang sipa
Progress: 0.64
translated_text: inaalagaan ng isang mang-aawit ang kanyang boses | ang giraffe ay hindi maaaring gumawa ng anumang vocalizations
Progress: 0.64
translated_text: ang maingay na boses ng talon | ang walang humpay na boses ng artilerya
Progress: 0.64
translated_text: ang pagpapahayag ng aking damdamin | Binigay ko ang aking nararamdaman
Progress: 0.64
translated_text: ang tinig ng batas | ang Times ay hindi boses ng New York | maraming boses ang konserbatismo
Progress: 0.65
translated_text: ang munting tinig ng konsensya | ang tinig ng karanasan | sinabi niya sa kanyang mga boses na gawin ito
Progress: 0.65
translated_text: inaalagaan ng isang mang-aawit ang kanyang boses | ang giraffe ay hindi maaaring gumawa ng anumang vocalizations
Progress: 0.65
translated_text: ang maingay na boses ng talon | ang walang tigil na boses ng artilerya
Progress: 0.65
translated_text: ang pagpapahayag ng aking damdamin | Binigay ko ang aking nararamdaman
Progress: 0.65
translated_text: ang tinig ng batas | ang Times ay hindi boses ng New York | maraming boses ang konserbatismo
Progress: 0.65
translated_text: ang munting tinig ng konsensya | ang tinig ng karanasan | sinabi niya sa kanyang mga boses na gawin ito
Progress: 0.65
translated_text: matinding init | matinding pagkabalisa | matinding pagnanasa | matinding damdamin | ang matinding amoy ng skunk | matinding sakit | matindi ang apoy ng kaaway
Progress: 0.65
translated_text: matinding sakit | nakaramdam ng matinding inis | matinding pangangati at pagkasunog
Progress: 0.65
translated_text: matingkad na berde | matinding asul
Progress: 0.65
translated_text: isang commodious na daungan | isang commodious na gusali na angkop para sa mga kombensiyon
Progress: 0.65
translated_text: isang mahirap na gawain | ang mga pugad na lugar sa mga bangin ay mahirap ma-access | mahirap na panahon | bakit ang hirap mong magtago ng sikreto?
Progress: 0.65
translated_text: isang mahirap na bata | isang hindi mapangasiwaan na sitwasyon
Progress: 0.65
translated_text: nilagyan niya ng kisame ang dami ng babaeng nagtrabaho sa kanya | nagkaroon ng bubong sa suweldo | nagtatag sila ng cap para sa mga presyo
Progress: 0.65
translated_text: dinukot niya ang kanyang bulsa sa loob ng jacket | loob sa labas | nasa loob ng pitch ang nasa pagitan ng home plate at ang batter
Progress: 0.65
translated_text: privy sa panloob na kaalaman | panloob na impormasyon | may pribilehiyong impormasyon
Progress: 0.65
translated_text: isang panloob na lahne | ang panloob na lane
Progress: 0.65
translated_text: wala siya ngayon | hindi mo dapat papasukin ang isang estranghero sa bahay kapag wala ang iyong ina
Progress: 0.65
translated_text: ang pitch ay malayo (o malawak) | isang pitch sa labas
Progress: 0.65
translated_text: tumakas sa leon | gustong lumayo roon | pinaalis ang mga bata sa boarding school | kinawayan ng guro ang mga bata palayo sa patay na hayop | pumunta sa paaralan | umalis sila | humayo kayo at mangaral
Progress: 0.65
translated_text: namigay siya ng pera sa mahihirap | namigay ng ticket
Progress: 0.65
translated_text: isantabi ang mga pagtutol | itinulak ang lahat ng pagdududa
Progress: 0.65
translated_text: nawala ang musika | sinubukang ipaliwanag ang kapakanan ng liham | idle ang mga oras na malayo | ang kanyang mga kuko ay pagod na
Progress: 0.65
translated_text: ang bangka ay 5 milya ang layo (o ang layo) | 2 linggo pa ang pahinga (o wala pa) ang party | malayo noong ika-18 siglo
Progress: 0.65
translated_text: nagtrabaho siya sa malayo sa proyekto nang higit sa isang taon | walang tigil sa pagmamartilyo ang bata na parang dito nakasalalay ang buhay niya
Progress: 0.65
translated_text: inalis ang gulo | ang bulok na kahoy ay kailangang putulin
Progress: 0.65
translated_text: ilagay ang mga laruan | ang kanyang mga hiyas ay nakakulong sa isang ligtas | inihain ang sulat
Progress: 0.65
translated_text: tumabi | italikod ang mukha | umiwas ng tingin
Progress: 0.65
translated_text: nagsimulang magtabi ng pera para makabili ng sasakyan | maglagay ng isang bagay para sa kanyang katandaan | may pugad na itlog na nakatago para sa tag-ulan
Progress: 0.65
translated_text: patay ang oven | patay ang mga ilaw
Progress: 0.65
translated_text: isang off year para sa tennis | off ang performance niya
Progress: 0.65
translated_text: tumakas sa leon | gustong lumayo roon | pinaalis ang mga bata sa boarding school | kinawayan ng guro ang mga bata palayo sa patay na hayop | pumunta sa paaralan | umalis sila | humayo kayo at mangaral
Progress: 0.65
translated_text: ang bangka ay 5 milya ang layo (o ang layo) | ang party ay 2 linggo pa rin (o wala pa) | malayo noong ika-18 siglo

Progress: 0.65
translated_text: linisin ang dumi | inahit niya ang kanyang bigote
Progress: 0.65
translated_text: maaaring siya ang kambal ni Gingrich | siya ang mismong imahe ng kanyang ina
Progress: 0.65
translated_text: isang dobleng (o dalawahan) na tungkulin para sa isang aktor | ang katungkulan ng isang klerigo ay dalawa; pampublikong pangangaral at pribadong impluwensya | bawat episode ay may doble at tatlong kahulugan
Progress: 0.65
translated_text: isang itlog na may double yolk | isang dobleng (binary) na bituin | dobleng pinto | dalawahang kontrol para sa pilot at copilot | Ang duple (o doble) na oras ay binubuo ng dalawa (o maramihang dalawa) na beats sa isang sukat
Progress: 0.65
translated_text: kumain ng dobleng bahagi | ang dosis ay nadoble | dalawang beses na pagtaas
Progress: 0.65
translated_text: isang double bed | isang double room
Progress: 0.65
translated_text: isang tusong dobleng kahulugan | nagsalita na may sawang dila
Progress: 0.65
translated_text: siya ay doble ang gantimpala | dobleng ningning ang kanyang mga mata
Progress: 0.65
translated_text: isang masusing paghahanap sa mga ledger ay nagsiwalat ng walang | ang kinalabasan ay nagbigay-katwiran sa paghahanap
Progress: 0.65
translated_text: Ang pulisya ay naghahanap ng mga pahiwatig | Hinahanap nila ang nawawalang lalaki sa buong county
Progress: 0.65
translated_text: Buong araw kaming naghanap at sa wakas ay natagpuan namin ang bata sa kagubatan | Maghanap sa ibang lugar para sa perpektong regalo!
Progress: 0.65
translated_text: kinailangan ng mga mag-aaral na magsaliksik sa kasaysayan ng Ikalawang Digmaang Pandaigdig para sa kanilang proyekto sa kasaysayan | Naghanap siya ng impormasyon sa kanyang mga kamag-anak sa web | Sinasaliksik ng mga siyentipiko ang kalikasan ng kamalayan
Progress: 0.65
translated_text: Hinalughog ng pulisya ang suspek | Hinalughog namin sa buong bahay ang nawawalang susi
Progress: 0.65
translated_text: nakakuha siya ng bargain sa auction | ang stock ay isang tunay na pagbili sa presyong iyon
Progress: 0.65
translated_text: Bumili ng bagong kotse ang pamilya | Ang conglomerate ay nakakuha ng bagong kumpanya | Bumili siya para sa malaking department store
Progress: 0.65
translated_text: nakakuha siya ng bargain sa auction | ang stock ay isang tunay na pagbili sa presyong iyon
Progress: 0.65
translated_text: Bumili ng bagong kotse ang pamilya | Ang conglomerate ay nakakuha ng bagong kumpanya | Bumili siya para sa malaking department store
Progress: 0.65
translated_text: makisig na kakisigan | isang matalinong bagong damit | isang suit ng voguish cut
Progress: 0.65
translated_text: ilang mga bata ay mas maliwanag sa isang paksa kaysa sa isa pa | mas maagang nagsasalita ang matatalinong bata kaysa karaniwan
Progress: 0.66
translated_text: huwag kang maging sariwa sa akin | impertinent ng isang bata na mag-lecture sa isang matanda | isang bastos na batang lalaki na binigay sa mapang-insulto sa mga estranghero | Huwag kang magpakamarunong sa akin!
Progress: 0.66
translated_text: Binigyan ko siya ng matalinong saludo | naglakad kami sa matalinong bilis
Progress: 0.66
translated_text: isang baha ng mga kahilingan | agos ng pang-aabuso
Progress: 0.66
translated_text: binaha ang basement pagkatapos ng bagyo | Bumaha sa kanyang isipan ang mga imahe
Progress: 0.66
translated_text: Binaha ng bumubong ilog ang nayon | Bumaha ng dugo sa kanyang mga mata ang sirang ugat
Progress: 0.66
translated_text: bahain ang merkado ng mga sapatos na pang-tennis | Gawin ang bansa sa murang import mula sa Silangan
Progress: 0.66
translated_text: Nagbulabula ang mga bata sa tuwa | Ang aking amo ay namumulaklak sa galit
Progress: 0.66
translated_text: wala siyang respeto sa mga inspirasyon ng ibang mga artista | pagkatapos ng mga taon ng trabaho ang kanyang brainchild ay isang tangible reality
Progress: 0.66
translated_text: umupo siya sa gilid ng kama | ang kwarto ay may lamang isang kama at upuan
Progress: 0.66
translated_text: Ang estudyanteng ito ay natutulog sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.66
translated_text: Karaniwan akong pumapasok sa hatinggabi | Natutulog siya sa madaling araw
Progress: 0.66
translated_text: Nakakainis talaga ang mga lamok sa tenga ko | Naiirita ako na hindi niya isinasara ang pinto pagkatapos niyang umalis
Progress: 0.66
translated_text: gumawa ng iritadong kilos | feeling nettled sa patuloy na panunukso | naiinis tungkol sa pag-iiwan | nakaramdam talaga ng asar sa kanyang kakulitan | nagalit walang katapusan sa kanyang mga kasinungalingan | nagulo sa pagkaantala
Progress: 0.66
translated_text: hinarass ang mga nagtatrabahong ina | isang nagmamadaling ekspresyon | ang kanyang kaawa-awang ama ay kailangang tiisin ang kanyang patuloy na pagkagambala | ang galit na galit na mga magulang ng isang masungit na binatilyo
Progress: 0.66
translated_text: siya ay nasa dilim hinggil sa kanilang mga intensyon | ang kanyang mga lektura ay nagtanggal ng kadiliman
Progress: 0.66
translated_text: nakaupo sa isang madilim na sulok | isang madilim na araw | madilim na anino | maitim na parang loob ng itim na pusa
Progress: 0.66
translated_text: madilim na berde | maitim na salamin | madilim na kulay tulad ng wine red o navy blue
Progress: 0.66
translated_text: itim na gawa | isang itim na kasinungalingan | ang kanyang itim na puso ay gumawa ng isa pang itim na gawa | Darth Vader ng madilim na bahagi | isang madilim na layunin | dark undercurrents ng etnikong poot | ang pakana ng ilang masasamang katalinuhan na nakatungo na parusahan siya
Progress: 0.66
translated_text: isang madilim na pagsimangot | the proverbially dour New England Puritan | isang malungkot, walang pag-asa na kibit balikat | umupo siya sa moody na katahimikan | isang morose at unsociable na paraan | isang saturnine, halos misanthropic na batang henyo | isang maasim na ugali | isang nagtatampo na karamihan
Progress: 0.66
translated_text: itong malungkot na bansa | malungkot na panahon ng barbarismo at pamahiin | ang madilim na edad | isang madilim na panahon sa kasaysayan ng edukasyon
Progress: 0.66
translated_text: marami na ang madilim ay malinaw na ngayon sa akin | sabi ng mga hindi nakaka-appreciate ng gawa ni Kafka, malabo ang istilo niya
Progress: 0.66
translated_text: isang asul na araw | ang madilim na araw ng digmaan | isang linggo ng maulan na nakababahalang panahon | isang malungkot na tanawin ng taglamig | ang unang mapanglaw na araw ng Nobyembre | isang madilim na madilim na araw | malupit na tag-ulan
Progress: 0.66
translated_text: National Association for the Advancement of Colored People | mga taong maitim ang balat
Progress: 0.66
translated_text: nakakalimot sa kanyang mga responsibilidad | nakakalimutang katandaan
Progress: 0.66
translated_text: Gumuguhit ako ng blangko | Hinaharang mo ang pangalan ng una mong asawa!
Progress: 0.66
translated_text: Nakalimutan ko yung payong ko sa restaurant | Iniwan ko ang susi ko sa loob ng sasakyan at ni-lock ang pinto
Progress: 0.66
translated_text: kailangan niya ng katahimikan para makatulog | tahimik ang kalye
Progress: 0.66
translated_text: isang tahimik na buhay | isang tahimik na pulutong ng mga nanonood | tahimik na mga taong mapagmahal sa kapayapaan | nanatiling tahimik ang mga paksyon sa loob ng halos 10 taon
Progress: 0.66
translated_text: isang tahimik na madla sa konsiyerto | madilim at tahimik ang silid
Progress: 0.66
translated_text: mga tumahimik na boses | naka-mute na mga trumpeta | isang mahinang bulong | isang tahimik na saway
Progress: 0.66
translated_text: isang laso ng buhangin sa pagitan ng galit na dagat at ng tahimik na bay | ang tahimik na tubig ng isang lagoon | isang lawa ng tahimik na asul na tubig na sumasalamin sa isang tahimik na asul na kalangitan | isang makinis na tawiran ng channel | bahagya isang alon sa tahimik na tubig | walang humpay na tubig
Progress: 0.66
translated_text: ang kanyang mga kamay ay tahimik na nakapatong sa kanyang kandungan | ang rock star ay tahimik na inilabas sa likod na pinto | umupo ka dito nang tahimik hangga&#39;t maaari
Progress: 0.66
translated_text: basurahan itong mga lumang upuan | basura ang isang lumang kotse | i-scrap ang iyong lumang computer

Progress: 0.66
translated_text: ang deterrent power ng nuclear weapons | ang kapangyarihan ng kanyang pag-ibig ay nagligtas sa kanya | ang kanyang kapangyarihan ay natakpan ng banayad na harapan
Progress: 0.66
translated_text: ang pagiging nasa katungkulan ay nagbibigay na ng malaking kalamangan sa isang kandidato | sa kanyang unang taon sa panunungkulan | noong unang taon niya sa kapangyarihan | kapangyarihan ng pangulo
Progress: 0.66
translated_text: ang mahiwagang presensya ng isang masamang kapangyarihan | nawa&#39;y sumaiyo ang puwersa | ang mga puwersa ng kasamaan
Progress: 0.66
translated_text: ang kumplikadong makinarya ng negosasyon | ang makinarya ng utos ay nagtrabaho at naglabas ng isang utos
Progress: 0.66
translated_text: sila ay sakim at gagawin ang lahat para sa pera | paghahagis ng mapag-imbot na mga mata sa bukid ng kanyang kapitbahay | isang nakahawak na matandang kuripot | paghawak sa komersyalismo | sakim sa pera at kapangyarihan | yumaman at sakim | matibay na mga employer na maramot sa mga umento para sa kanilang mga empleyado
Progress: 0.66
translated_text: masugid sa pakikipagsapalaran | isang masugid na ambisyon na magtagumpay | mabangis na lumalamon sa pagmamahal | ang esurient na mga mata ng isang masugid na pag-usisa | sakim sa kasikatan
Progress: 0.66
translated_text: anuman ang aking kapalaran | nararapat sa isang mas mabuting kapalaran | ay may maraming masaya | ang swerte ng Irish | isang biktima ng mga pangyayari | tagumpay na naging bahagi niya
Progress: 0.66
translated_text: sa kaganapang iyon, ang unang posibilidad ay hindi kasama | maaaring umulan kung saan ang piknik ay kanselahin
Progress: 0.66
translated_text: ang magnetic effect ay mas malaki kapag ang baras ay pahaba | ang kanyang desisyon ay may nakapanlulumong kahihinatnan para sa negosyo | napaka bait niya pagkatapos ng pangyayari
Progress: 0.66
translated_text: nagkaroon sila ng away | mayroon silang mga salita
Progress: 0.66
translated_text: Nag-away kami sa tanong kung sino ang nakatuklas ng America | Ang dalawang taong ito ay palaging nag-aalis ng isang bagay
Progress: 0.66
translated_text: mura sana ito sa dobleng presyo | murang pampamilyang restaurant
Progress: 0.66
translated_text: isang flash car | isang marangyang singsing | makulay na kulay | isang matingkad na kasuutan | maingay na mga kamiseta ng isport | isang meretricious ngunit naka-istilong libro | tawdry na palamuti
Progress: 0.66
translated_text: maagap na pagsugpo | aktibong panghihimasok
Progress: 0.66
translated_text: madaling araw | isang maagang babala | maagang pagsusuri | isang maagang pagkamatay | kumuha ng maagang pagreretiro | isang maagang tagsibol | maagang varieties ng mga gisantes at kamatis mature bago ang karamihan sa karaniwang mga varieties
Progress: 0.66
translated_text: sa isang maagang yugto | maagang anyo ng buhay | maagang tao | isang maagang computer
Progress: 0.66
translated_text: ang mga unang naninirahan sa Europa | mga dating henerasyon | sa ibang panahon
Progress: 0.67
translated_text: ang Maagang Hebreong alpabetikong script ay ang pangunahing ginagamit mula ika-11 hanggang ika-6 na siglo BC | Ang Early Modern English ay kinakatawan sa mga dokumentong nakalimbag mula 1476 hanggang 1700
Progress: 0.67
translated_text: siya ay nagtapos ng maaga | maagang natapos ang bahay
Progress: 0.67
translated_text: siya ay partikular na maselan tungkol sa pagbaybay | isang partikular na kakila-kilabot na pag-atake | sa ilalim ng kakaibang trahedya na mga pangyayari | isang partikular na (o espesyal na) maingat na diskarte sa panganib
Progress: 0.67
translated_text: isang magandang babae | isang magandang lalaki | mas maganda pa sa kapatid niya | napakaganda pero hindi sobrang gwapo | ang aming mga kababaihan sa timog ay mahusay na pinapaboran
Progress: 0.67
translated_text: ay isang malaking tipper | ang masaganang kabutihan ng Diyos | masaganang papuri | isang freehanded host | isang gwapong allowance | Ang anak ng Sabado ay mapagmahal at nagbibigay | isang liberal na tagapagtaguyod ng sining | isang munificent regalo | ang kanyang magiliw at bukas-palad na lolo
Progress: 0.67
translated_text: isang magandang babae | isang magandang lalaki | mas maganda pa sa kapatid niya | napakaganda pero hindi sobrang gwapo | ang aming mga kababaihan sa timog ay mahusay na pinapaboran
Progress: 0.67
translated_text: ay isang malaking tipper | ang masaganang kabutihan ng Diyos | masaganang papuri | isang freehanded host | isang gwapong allowance | Ang anak ng Sabado ay mapagmahal at nagbibigay | isang liberal na tagapagtaguyod ng sining | isang munificent regalo | ang kanyang magiliw at bukas-palad na lolo
Progress: 0.67
translated_text: Mayroon siyang $1,000 sa bangko | Mayroon siyang dalawang magagandang anak na babae | Siya ay may hawak na Master&#39;s degree mula sa Harvard
Progress: 0.67
translated_text: makakuha ng ideya | makaranas ng vertigo | nasusuka | tumanggap ng mga pinsala | magkaroon ng pakiramdam
Progress: 0.67
translated_text: Siya ay nagmamay-ari ng tatlong bahay sa Florida | Ilang sasakyan ang mayroon siya?
Progress: 0.67
translated_text: Nakuha niya ang kanyang squad sa bola | Pinapasok ako nito para sa isang malaking sorpresa | May dinadala siyang babae sa gulo
Progress: 0.67
translated_text: Magkaroon ng isa pang mangkok ng sopas ng manok! | Hindi ako kumukuha ng asukal sa aking kape
Progress: 0.67
translated_text: magkaroon ng postdoc | may katulong | may manliligaw
Progress: 0.67
translated_text: magdaos ng reception | magkaroon, magtapon, o gumawa ng isang party | magbigay ng kurso
Progress: 0.67
translated_text: Mayroon akong dalawang taon na natitira | Wala na akong pera | May dalawang taon pa sila bago sila magretiro
Progress: 0.67
translated_text: Anong meron tayo dito? | Ngayon ay mayroon kaming magandang gulo
Progress: 0.67
translated_text: Ang mga ad ay nag-udyok sa akin na bumili ng VCR | Sa wakas nakuha ako ng aking mga anak na bumili ng computer | Pinabili ako ng asawa ko ng bagong sofa
Progress: 0.67
translated_text: Ang tanging babae na magkakaroon sa kanya ay ang anak na babae ng miller | Hindi ako magkakaroon ng asong ito sa aking bahay! | Mangyaring tanggapin ang aking regalo
Progress: 0.67
translated_text: tumanggap ng bayad | makatanggap ng regalo | tumanggap ng mga liham mula sa harapan
Progress: 0.67
translated_text: Nagdusa siya ng bali sa aksidente | Nagkaroon siya ng insulin shock pagkatapos kumain ng tatlong candy bar | Nagkaroon siya ng pasa sa binti | Nabali ang braso niya sa scuffle
Progress: 0.67
translated_text: Si Nicklaus ay nagkaroon ng 70 | Nakakuha ang koponan ng Brazil ng 4 na layunin | Gumawa siya ng 29 puntos sa araw na iyon
Progress: 0.67
translated_text: Ipinanganak ni Abraham si Isaac | Ang mga lalaki ay madalas na ama ng mga anak ngunit hindi sila nakikilala
Progress: 0.67
translated_text: ang instant replay ay nagdulot ng masyadong mahabang pagkaantala | siya ay nag-utos ng isang hold sa aksyon
Progress: 0.67
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.67
translated_text: nakakuha siya ng 3% na pagtaas | nakakuha siya ng dagdag sahod
Progress: 0.67
translated_text: ang emanation ng Banal na Espiritu | ang pagbangon ng Espiritu Santo | ang doktrina ng prusisyon ng Banal na Espiritu mula sa Ama at sa Anak
Progress: 0.67
translated_text: Umangat ang ulap | Ang usok ay bumangon mula sa sunog sa kagubatan | Ang ambon ay bumangon mula sa parang
Progress: 0.67
translated_text: tumaas nang husto ang mga presyo | tumaas nang husto ang halaga ng aming bahay noong nakaraang taon
Progress: 0.67
translated_text: Isang bagong relihiyosong kilusan ang nagmula sa bansang iyon | isang pag-ibig na umusbong sa pagkakaibigan | ang ideya para sa aklat ay nagmula sa isang maikling kuwento | Isang kawili-wiling kababalaghan ang bumangon
Progress: 0.67
translated_text: Gumising ako ng 7 AM araw-araw | Maaga silang bumangon | Siya ay bumangon sa gabi
Progress: 0.67
translated_text: tumaas sa isang hamon | tumaas sa okasyon
Progress: 0.67
translated_text: Sumisikat din ang araw | Ang pagsikat ng araw ay nakita ang takipsilim gabi tumakas... | Umakyat si Jupiter

Progress: 0.67
translated_text: Si Kristo ay nabuhay! | Ang mga patay ay mag-aalsa
Progress: 0.67
translated_text: sila ay napapanahon | wala pa kaming balita sa kanila hanggang ngayon
Progress: 0.67
translated_text: Alam mo bang may nakikita siyang matandang lalaki? | Nililigawan na naman niya ang dati niyang asawa!
Progress: 0.67
translated_text: makalipas ang dalawang araw ay umalis sila | nagsagawa sila ng dalawang pagtatanghal araw-araw | mayroong 30,000 pasahero kada araw
Progress: 0.67
translated_text: dapat itong dumating anumang araw ngayon | pagkatapos ng araw na iyon ay hindi na siya muling nagtiwala sa kanya | iyon ang mga araw | sa mga araw na ito ay hindi pangkaraniwan
Progress: 0.67
translated_text: ang bukang-liwayway ay ginawang araw ang gabi | mas madaling gawin ang pag-aayos sa araw
Progress: 0.67
translated_text: nagsimula ang araw ko kaninang madaling araw | ito ay isang abalang araw sa stock exchange | tinawag niya itong isang araw at natulog
Progress: 0.67
translated_text: sa araw ng mga dinosaur | noong panahon ng Imperyong Romano | sa mga araw ng paglalayag ng mga barko | siya ay isang matagumpay na pianista sa kanyang panahon
Progress: 0.67
translated_text: karapat-dapat siya sa kanyang araw sa korte | bawat aso ay may kanya-kanyang araw
Progress: 0.67
translated_text: mahahalagang tao | ang mahahalagang tanong sa araw na ito
Progress: 0.67
translated_text: isang makabuluhang pagbabago sa mga batas sa buwis | isang makabuluhang pagbabago sa Konstitusyon | isang makabuluhang kontribusyon | mahahalagang detalye | makabuluhang istatistika
Progress: 0.67
translated_text: isang mahalagang sandali sa kanyang karera | isang mahalagang halalan | isang mahalagang isyu para sa mga kababaihan
Progress: 0.67
translated_text: isang mahalagang opisyal | maawtoridad na paraan ng kapitan
Progress: 0.67
translated_text: binibigkas ang kautusan na may mahalagang hangin | gumawa ng mahabang mahahalagang hakbang sa direksyon ng kanyang opisina
Progress: 0.67
translated_text: mahahalagang tao | ang mahahalagang tanong sa araw na ito
Progress: 0.67
translated_text: isang makabuluhang pagbabago sa mga batas sa buwis | isang makabuluhang pagbabago sa Konstitusyon | isang makabuluhang kontribusyon | mahahalagang detalye | makabuluhang istatistika
Progress: 0.67
translated_text: isang mahalagang sandali sa kanyang karera | isang mahalagang halalan | isang mahalagang isyu para sa mga kababaihan
Progress: 0.67
translated_text: isang mahalagang opisyal | maawtoridad na paraan ng kapitan
Progress: 0.68
translated_text: binigkas ang kautusan na may mahalagang hangin | gumawa ng mahabang mahahalagang hakbang sa direksyon ng kanyang opisina
Progress: 0.68
translated_text: aminin ang isang tao sa propesyon | Siya ay ipinasok sa New Jersey Bar
Progress: 0.68
translated_text: ang ikatlong baseman ay gumawa ng ilang kapansin-pansing paghinto | ang kanyang pagtigil sa daloy ay nagresulta sa isang baha
Progress: 0.68
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.68
translated_text: huminto ang sasakyan | Huminto siya sa harap ng bintana ng tindahan
Progress: 0.68
translated_text: Harangan ang kanyang halalan | Itigil ang proseso
Progress: 0.68
translated_text: huminto kami sa bahay ni Tita Mary | huminto sila ng tatlong araw sa Florence
Progress: 0.68
translated_text: huminto ng kotse | pigilan ang magnanakaw
Progress: 0.68
translated_text: itigil ang proyekto | putulin ang negosasyon
Progress: 0.68
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.68
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.68
translated_text: harangan ang daan | barikada ang mga lansangan | itigil ang abalang kalsada
Progress: 0.68
translated_text: ang ikatlong baseman ay gumawa ng ilang kapansin-pansing paghinto | ang kanyang paghinto ng agos ay nagresulta sa isang baha
Progress: 0.68
translated_text: ang mga negosasyon ay nasa pag-aresto | hinawakan sila sa tseke | habang huminto ay nakakuha siya ng tanghalian | ang panandaliang pananatili ay nagawa niyang makatakas sa suntok | ginugol niya ang buong paghinto sa kanyang upuan
Progress: 0.68
translated_text: huminto ang sasakyan | Huminto siya sa harap ng bintana ng tindahan
Progress: 0.68
translated_text: Harangan ang kanyang halalan | Itigil ang proseso
Progress: 0.68
translated_text: huminto kami sa bahay ni Tita Mary | huminto sila ng tatlong araw sa Florence
Progress: 0.68
translated_text: huminto ng kotse | pigilan ang magnanakaw
Progress: 0.68
translated_text: itigil ang proyekto | putulin ang negosasyon
Progress: 0.68
translated_text: Arrest ang pababang trend | Suriin ang paglago ng komunismo sa Timog Silangang Asya | Naglalaman ng kilusang rebelde | Ibalik ang agos ng komunismo
Progress: 0.68
translated_text: ang bronchioles ay nagtatapos sa isang capillary bed | Ang iyong mga karapatan ay huminto kung saan mo nilalabag ang mga karapatan ng ibang | Ang aking ari-arian ay nagtatapos sa mga palumpong | Nagtatapos ang symphony sa isang pianissimo
Progress: 0.68
translated_text: harangan ang daan | barikada ang mga lansangan | itigil ang abalang kalsada
Progress: 0.68
translated_text: triple niya sa rightfield corner | ang timog-silangang sulok ng Mediterranean
Progress: 0.68
translated_text: siya ay isang bituin ng screen at video | Ang telebisyon ay isang daluyan dahil hindi ito bihira o mahusay na ginawa
Progress: 0.68
translated_text: Inalis ng dentista ang kapirasong pagkain na nakaipit sa ilalim ng aking gilagid | Sa wakas ay napalaya niya ang mga binti ng biktima ng lindol na nabaon sa mga guho
Progress: 0.68
translated_text: Ibinibigay ko ang aking silid sa pangmatagalang panauhin sa bahay | magbitiw sa pag-angkin sa trono
Progress: 0.68
translated_text: libreng negosyo | isang libreng port | isang malayang bansa | Mayroon akong isang oras na libre | malayang kalooban | walang kapootang panlahi | huwag mag-atubiling manatili hangga&#39;t gusto mo | isang malayang pagpili
Progress: 0.68
translated_text: libreng pagpapalawak | libreng oxygen | isang libreng elektron
Progress: 0.68
translated_text: komplimentaryong tiket | libreng pagpasok
Progress: 0.68
translated_text: isang libreng locker | isang libreng lane
Progress: 0.68
translated_text: nahulog sa kanya ang nakahiwalay na shutter | hinila niya ang braso niya at tumakbo
Progress: 0.68
translated_text: isang libreng oras sa pagitan ng mga klase | bakanteng oras sa aking mga kamay
Progress: 0.68
translated_text: pagsusulat baog ng pananaw | mga batang recruit na walang karanasan | inosente ng literary merit | ang pangungusap ay walang kahulugan
Progress: 0.68
translated_text: isang maluwag na interpretasyon ng sinabi sa kanya | isang libreng pagsasalin ng tula
Progress: 0.68
translated_text: Inalis ng dentista ang kapirasong pagkain na nakaipit sa ilalim ng aking gilagid | Sa wakas ay napalaya niya ang mga binti ng biktima ng lindol na nabaon sa mga guho
Progress: 0.68
translated_text: Ibinibigay ko ang aking silid sa pangmatagalang panauhin sa bahay | magbitiw ng pag-angkin sa trono
Progress: 0.68
translated_text: libreng negosyo | isang libreng port | isang malayang bansa | Mayroon akong isang oras na libre | malayang kalooban | walang kapootang panlahi | huwag mag-atubiling manatili hangga&#39;t gusto mo | isang malayang pagpili
Progress: 0.68
translated_text: libreng pagpapalawak | libreng oxygen | isang libreng elektron
Progress: 0.68
translated_text: komplimentaryong tiket | libreng pagpasok
Progress: 0.68
translated_text: isang libreng locker | isang libreng lane
Progress: 0.68
translated_text: nahulog sa kanya ang nakahiwalay na shutter | hinila niya ang braso niya at tumakbo
Progress: 0.68
translated_text: isang libreng oras sa pagitan ng mga klase | bakanteng oras sa aking mga kamay

Progress: 0.68
translated_text: pagsusulat baog ng pananaw | mga batang recruit na walang karanasan | inosente ng literary merit | ang pangungusap ay walang kahulugan
Progress: 0.68
translated_text: isang maluwag na interpretasyon ng sinabi sa kanya | isang libreng pagsasalin ng tula
Progress: 0.68
translated_text: ang malaking disyerto ay walang laman | ang kawalan ng laman ng outer space | kung wala ang kanilang suporta siya ay mamumuno sa isang vacuum
Progress: 0.68
translated_text: sinimulan niya ito | Binigyan ko ito ng umiikot
Progress: 0.68
translated_text: Nag-aalok ang conference center ng health spa | Nag-aalok ang hotel ng mga pribadong meeting room
Progress: 0.68
translated_text: Nagboluntaryo siyang ihatid ang matandang babae sa bahay | Nag-alok akong tumulong sa mga pinggan ngunit hindi ito narinig ng babaing punong-abala
Progress: 0.68
translated_text: ipaabot ang aking pagbati | Inialay niya ang kanyang pakikiramay
Progress: 0.68
translated_text: maglagay ng magandang laban | nag-aalok ng pagtutol
Progress: 0.69
translated_text: mag-extend ng loan | Nag-aalok ang bangko ng magandang deal sa mga bagong mortgage
Progress: 0.69
translated_text: nag-pop siya ng tanong noong Linggo ng gabi | nag-propose siya ng kasal sa lalaking kilala niya sa loob lang ng dalawang buwan | Sa wakas ay nagpahayag ang matandang bachelor sa dalaga
Progress: 0.69
translated_text: ang aking napakahalagang katulong | kumuha sila ng karagdagang tulong para matapos ang trabaho
Progress: 0.69
translated_text: inilipat niya ang kanyang pamilya sa Virginia | Ito ay isang mabuting Kristiyanong sambahayan | Naghintay ako hanggang sa makatulog ang buong bahay | tinanong ng guro kung ilang tao ang bumubuo sa kanyang tahanan
Progress: 0.69
translated_text: kamag-anak niya | pamilya niya
Progress: 0.69
translated_text: ang mensahe ay natugunan hindi lamang sa mga empleyado kundi sa bawat miyembro ng pamilya ng kumpanya | tinanggap ng simbahan ang mga bagong miyembro sa pakikisama nito
Progress: 0.69
translated_text: marami siyang gawaing dapat gawin | ang bilang ng mga parameter ay maliit | ang bilang ay halos isang libo
Progress: 0.69
translated_text: ginawa niya ang kanyang kilos ng tatlong beses tuwing gabi | nagkaroon siya ng kaakit-akit na maliit na gawain | isa ito sa pinakamagandang numerong nagawa niya
Progress: 0.69
translated_text: mas gusto niya ang black nylon number | ang sweater na ito ay isang all-wool na numero
Progress: 0.69
translated_text: Ang mga bayarin ay umabot sa $2,000 | Umabot sa $2,000 ang bill
Progress: 0.69
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.69
translated_text: siya at ang kanyang asawa ay nagkakaproblema | laging trabaho ang makipag-ugnayan sa kanya | mga problema sa lunsod tulad ng pagsisikip ng trapiko at ulap
Progress: 0.69
translated_text: sunod-sunod na problema ang naantala ang trabaho | ano ang problema?
Progress: 0.69
translated_text: siya at ang kanyang asawa ay nagkakaproblema | laging trabaho ang makipag-ugnayan sa kanya | mga problema sa lunsod tulad ng pagsisikip ng trapiko at ulap-usok
Progress: 0.69
translated_text: sunod-sunod na problema ang naantala ang trabaho | ano ang problema?
Progress: 0.69
translated_text: ang presyo ng gasolina | nakuha niya ang kanyang bagong kotse sa mahusay na mga tuntunin | magkano ang damage?
Progress: 0.69
translated_text: Nasira ng snow ang bubong | Nasira niya ang sasakyan nang mabangga niya ang puno
Progress: 0.69
translated_text: ang instant replay ay nagdulot ng masyadong mahabang pagkaantala | siya ay nag-utos ng isang hold sa aksyon
Progress: 0.69
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.69
translated_text: ang instant replay ay nagdulot ng masyadong mahabang pagkaantala | siya ay nag-utos ng isang hold sa aksyon
Progress: 0.69
translated_text: Inaasahan namin ang pagbisita ng aming mga kamag-anak | Naghahanap siya ng promosyon | naghihintay siyang ma-draft
Progress: 0.69
translated_text: ito ay pinahahalagahan | isang tao na nakakuha ng mataas na paggalang
Progress: 0.69
translated_text: ang kanyang paggalang sa kanyang mga kagustuhan ay lubhang nakakabigay-puri | siguraduhin mong ibigay ang aking paggalang sa dean
Progress: 0.69
translated_text: ang kanilang mga anak ay hindi kailanman napakalakas sa pagsunod | nag-aral siya sa law school bilang paggalang sa kagustuhan ng kanyang ama
Progress: 0.69
translated_text: napagkamalan niya ang kanyang pagiging lalaki para sa pag-ibig | nagbibigay siya ng respeto
Progress: 0.69
translated_text: bilang paggalang sa iyong kagustuhan | bilang paggalang sa kanyang privacy
Progress: 0.69
translated_text: Iginagalang ko ang kanyang paghatol | Pinahahalagahan namin ang kanyang pagkamalikhain
Progress: 0.69
translated_text: Pinulbos niya ang kanyang ilong | Nagsusuot ng powdered wig ang Hari
Progress: 0.69
translated_text: sariwang tinapay | isang sariwang bango | sariwang litsugas
Progress: 0.69
translated_text: bagong simula | sariwang ideya
Progress: 0.69
translated_text: malinis na tubig | sariwang hangin
Progress: 0.69
translated_text: isang sariwang kamiseta | isang sariwang papel | isang hindi nagamit na sobre
Progress: 0.69
translated_text: huwag kang maging sariwa sa akin | impertinent ng isang bata na mag-lecture sa isang matanda | isang bastos na batang lalaki na binigay sa mapang-insulto sa mga estranghero | Huwag kang magpakamarunong sa akin!
Progress: 0.69
translated_text: sila ay bagong kasal | bagong itinaas na pagtutol | isang bagong ayos ng buhok | damo bagong hugasan ng ulan | isang bagong linis na sahig | sariwa pa tayo sa kamatis
Progress: 0.69
translated_text: Kailangan ng lakas ng loob na gawin ang kanyang ginawa | ang tagumpay ay karaniwang nangangailangan ng pagsusumikap | Ang trabahong ito ay humihingi ng maraming pasensya at kasanayan | Ang posisyon na ito ay nangangailangan ng maraming personal na sakripisyo | Ang hapunan na ito ay nangangailangan ng isang kamangha-manghang dessert | Ang interbensyong ito ay hindi naglalagay ng pahintulot ng isang pasyente
Progress: 0.69
translated_text: Hinihiling namin na nasa oras ang aming sekretarya | Hindi ba masyado tayong nagtatanong sa mga batang ito? | Inaasahan kong darating ang aking mga mag-aaral sa oras para sa kanilang mga aralin
Progress: 0.69
translated_text: sa karamihan ng mga paaralan ang pisikal na edukasyon ay sapilitan | sapilitan ang pagdalo | kinakailangang pagbabasa
Progress: 0.69
translated_text: Anong oras aalis ang iyong tren? | Hindi siya umalis hanggang hatinggabi | Ang barko ay umalis sa hatinggabi
Progress: 0.69
translated_text: Nag-iwan siya ng gulo nang lumipat siya | Sa wakas ay iniwan siya ng kanyang suwerte | iniwan siya ng kanyang asawa pagkatapos ng 20 taong pagsasama | umiiyak siya sa pag-aakalang siya ay naiwan
Progress: 0.69
translated_text: Ang inflation ay nag-iwan sa kanila na walang pera | Hindi kami nakaimik dahil sa sinabi ng pangulo
Progress: 0.69
translated_text: iwanan ito bilang ay | pabayaan ang batang usa | iwanan ang mga bulaklak na nakikita mo sa parke
Progress: 0.69
translated_text: umalis ng kwarto | umalis ng bansa ang takas
Progress: 0.69
translated_text: Hindi ito nag-iiwan ng puwang para sa pagpapabuti | Ang ebidensya ay nagpapahintulot lamang ng isang konklusyon | payagan ang mga pagkakamali | mag-iwan ng maraming oras para sa biyahe | Ang pamamaraang ito ay nagbibigay ng maraming pahinga
Progress: 0.69
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.69
translated_text: Gusto niyang umalis | Umalis ng bahay ang binatilyo | Iniwan niya ang kanyang posisyon sa Red Cross | Umalis siya sa Senado pagkaraan ng dalawang termino | pagkatapos ng 20 taon sa parehong kumpanya, siya ay nakakuha ng mga pusta
Progress: 0.69
translated_text: Ipinaubaya niya ang desisyon sa kanyang kinatawan | iwanan ang iyong anak sa pangangalaga ng nars
Progress: 0.69
translated_text: Ipinamana sa akin ng aking tiyahin ang lahat ng kanyang alahas | Iniwan sa akin ng aking lolo ang kanyang buong ari-arian
Progress: 0.69
translated_text: Naiwan kaming apat | 19 bawas 8 dahon 11

Progress: 0.69
translated_text: Iniwan niya ang anim na anak | Sa kanyang pagkamatay, iniwan niya ang kanyang asawa at 11 pusa
Progress: 0.69
translated_text: magbigay ng lihim sa mga Ruso | iwanan ang iyong pangalan at tirahan dito | magbigay ng bagong kasanayan sa mga mag-aaral
Progress: 0.70
translated_text: Nakalimutan ko yung payong ko sa restaurant | Iniwan ko ang susi ko sa loob ng sasakyan at ni-lock ang pinto
Progress: 0.70
translated_text: ang kaliwang kamay ko | kaliwang gitnang field | ang kaliwang pampang ng isang ilog ay nasa iyong kaliwang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.70
translated_text: natirang meatloaf | may natira siyang kaunting pera kaya nanood siya ng sine | ilang kakaibang dolyar ang natitira | na-save ang natitirang mga sandwich para sa hapunan | hindi nagastos na mga probisyon
Progress: 0.70
translated_text: tumingin siya sa kanan at kaliwa | ang partidong pampulitika ay lumipat sa kaliwa
Progress: 0.70
translated_text: sila ay pinagkalooban ng kanilang Tagapaglikha ng ilang mga Karapatan na hindi maipagkakaila | Ang ilang mga karapatan ay hindi kailanman maaaring ibigay sa pamahalaan ngunit dapat panatilihin sa mga kamay ng mga tao | ang karapatan ay hindi isang bagay na ibinibigay sa iyo ng isang tao; ito ay isang bagay na hindi maaaring alisin ng sinuman
Progress: 0.70
translated_text: nagsusulat siya gamit ang kanyang kanang kamay ngunit nag-pitch gamit ang kanyang kaliwang | tamaan siya ng mabilis na karapatan sa katawan
Progress: 0.70
translated_text: pakiramdam niya nasa kanan siya | ang katuwiran ng kanyang pag-angkin
Progress: 0.70
translated_text: mga karapatan sa mineral | mga karapatan sa pelikula
Progress: 0.70
translated_text: Itama ang mga pagkakamali | iwasto ang kalkulasyon
Progress: 0.70
translated_text: ang kanang kamay ko | kanang gitnang field | isang pagliko sa kanan | ang kanang pampang ng isang ilog ay ang pampang sa iyong kanang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.70
translated_text: ang tamang sagot | ang tamang bersyon | ang tamang sagot | tinahak ang tamang daan | ang tamang desisyon
Progress: 0.70
translated_text: hindi tama na umalis sa party ng walang paalam | tamang pag-uugali
Progress: 0.70
translated_text: lahat sa tamang lugar nito | ang tamang tao para sa trabaho | hindi siya bagay sa posisyon
Progress: 0.70
translated_text: bagay na naman ngayon | ayusin ang mga bagay
Progress: 0.70
translated_text: ano ang tamang salita para dito? | ang tamang paraan ng pagbubukas ng mga talaba
Progress: 0.70
translated_text: ang kanang bahagi ng tela ay nagpakita ng pattern | siguraduhin na ang iyong kamiseta ay nasa kanang bahagi sa labas
Progress: 0.70
translated_text: magandang panahon para magtanim ng kamatis | ang tamang oras para kumilos | ang panahon ay hinog na para sa malalaking pagbabago sa sosyolohikal
Progress: 0.70
translated_text: tumingin siya sa kanan at kaliwa | ang partido ay lumipat sa kanan
Progress: 0.70
translated_text: mangyaring gawin ang iyong trabaho ng maayos! | hindi mo ba ako kayang buhatin ng disente?
Progress: 0.70
translated_text: she felt right at home | nahulog siya sa bitag
Progress: 0.70
translated_text: ang baby ay mighty cute | siya ay matinding pagod | ito ay malakas na mahalumigmig | ang batang iyon ay makapangyarihang malaki na ngayon | mayroon silang tamang magandang lugar | sila&#39;y lubos na nagalak
Progress: 0.70
translated_text: na nagsisilbi sa kanya ng tama | gawin ang tama sa kanya
Progress: 0.70
translated_text: ang bulaklak ay wastong inilarawan ng kanyang anak | tama ang hula niya
Progress: 0.70
translated_text: sila ay pinagkalooban ng kanilang Tagapaglikha ng ilang mga Karapatan na hindi maipagkakaila | Ang ilang mga karapatan ay hindi kailanman maaaring ibigay sa pamahalaan ngunit dapat panatilihin sa mga kamay ng mga tao | ang karapatan ay hindi isang bagay na ibinibigay sa iyo ng isang tao; ito ay isang bagay na hindi maaaring alisin ng sinuman
Progress: 0.70
translated_text: nagsusulat siya gamit ang kanyang kanang kamay ngunit nag-pitch gamit ang kanyang kaliwang | tamaan siya ng mabilis na karapatan sa katawan
Progress: 0.70
translated_text: pakiramdam niya nasa kanan siya | ang katuwiran ng kanyang pag-angkin
Progress: 0.70
translated_text: mga karapatan sa mineral | mga karapatan sa pelikula
Progress: 0.70
translated_text: Itama ang mga pagkakamali | iwasto ang kalkulasyon
Progress: 0.70
translated_text: ang kanang kamay ko | kanang gitnang field | isang pagliko sa kanan | ang kanang pampang ng isang ilog ay ang pampang sa iyong kanang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.70
translated_text: ang tamang sagot | ang tamang bersyon | ang tamang sagot | tinahak ang tamang daan | ang tamang desisyon
Progress: 0.70
translated_text: hindi tama na umalis sa party ng walang paalam | tamang pag-uugali
Progress: 0.70
translated_text: lahat sa tamang lugar nito | ang tamang tao para sa trabaho | hindi siya bagay sa posisyon
Progress: 0.70
translated_text: bagay na naman ngayon | ayusin ang mga bagay
Progress: 0.70
translated_text: ano ang tamang salita para dito? | ang tamang paraan ng pagbubukas ng mga talaba
Progress: 0.70
translated_text: ang kanang bahagi ng tela ay nagpakita ng pattern | siguraduhin na ang iyong kamiseta ay nasa kanang bahagi sa labas
Progress: 0.70
translated_text: magandang panahon para magtanim ng kamatis | ang tamang oras para kumilos | ang panahon ay hinog na para sa malalaking pagbabago sa sosyolohikal
Progress: 0.70
translated_text: tumingin siya sa kanan at kaliwa | ang partido ay lumipat sa kanan
Progress: 0.70
translated_text: mangyaring gawin ang iyong trabaho ng maayos! | hindi mo ba ako kayang buhatin ng disente?
Progress: 0.70
translated_text: she felt right at home | nahulog siya sa bitag
Progress: 0.70
translated_text: ang baby ay mighty cute | siya ay matinding pagod | ito ay malakas na mahalumigmig | ang batang iyon ay makapangyarihang malaki na ngayon | mayroon silang tamang magandang lugar | sila&#39;y lubos na nagalak
Progress: 0.70
translated_text: na nagsisilbi sa kanya ng tama | gawin ang tama sa kanya
Progress: 0.70
translated_text: ang bulaklak ay wastong inilarawan ng kanyang anak | tama ang hula niya
Progress: 0.70
translated_text: gising na iniisip ang kanyang bagong trabaho | hindi pa rin ganap na gising
Progress: 0.70
translated_text: isang alertong isip | alerto sa mga problema | buhay sa kung ano ang nangyayari | gising sa panganib ng kanyang sitwasyon | gising na ngayon sa realidad ng kanyang kalagayan
Progress: 0.70
translated_text: sinira niya ang password ko | basagin ang isang ligtas
Progress: 0.70
translated_text: nagdisenyo siya ng bagong kagamitan | bumili siya ng isang magandang piraso ng china
Progress: 0.70
translated_text: sinuri nila ang ilog sa tatlong bahagi | kailangan niya ng isang piraso ng granite
Progress: 0.70
translated_text: ito ay isang magandang piraso ng trabaho | medyo sinuwerte siya
Progress: 0.70
translated_text: sumulat siya ng isang kawili-wiling piraso sa Iran | ang mga bata ay nagsadula ng isang komiks para pasayahin ang mga bisita
Progress: 0.70
translated_text: isang piraso ng pie | isang hiwa ng tinapay
Progress: 0.70
translated_text: ang tindahang ito ay nagbebenta lamang ng mga object d&#39;art | hindi alam kung sino ang gumawa ng piyesang ito
Progress: 0.71
translated_text: dito siya saglit | Kailangan kong magpahinga para sa isang piraso | isang spell ng magandang panahon | isang patch ng masamang panahon
Progress: 0.71
translated_text: tinuruan niya akong i-set up ang mga lalaki sa chess board | nagsakripisyo siya ng isang piraso para makakuha ng estratehikong kalamangan
Progress: 0.71
translated_text: Naglagay siya ng kubrekama | Pinagsama-sama niya ang ilang mga taludtod | Nagtayo sila ng komite
Progress: 0.71
translated_text: Siya pieced sa sandwich buong umaga | Hindi siya kumakain ng buong pagkain--kumakagat lang siya
Progress: 0.71
translated_text: kailangan nila ng mga alpombra upang takpan ang mga hubad na sahig | ikinakalat namin ang aming mga pantulog sa tuyong sahig ng tent
Progress: 0.71
translated_text: ang sahig ng pelvis | ang sahig ng kweba
Progress: 0.71
translated_text: ang magandang negosyo ay nakasalalay sa pagkakaroon ng magandang paninda | nag-aalok ang tindahang iyon ng iba&#39;t ibang produkto

Progress: 0.71
translated_text: Ginawa ni Mays ang paghuli habang nakatalikod sa plato | ginawa niyang grab para sa bola bago ito lumapag | Nabigo ang pag-agaw ni Martin sa paningkaw at tumakbo ang kabayo palayo | ang snap at throw ng infielder ay isang solong galaw
Progress: 0.71
translated_text: Saluhin ang bola! | Hawak ang pinto ng elevator!
Progress: 0.71
translated_text: Aagawin ka ng kwentong ito | Kinuha ng pelikula ang aking imahinasyon
Progress: 0.71
translated_text: Palaging sinusubukan ng mga lalaki na makipag-chat sa mga bagong sekretarya | Ang aking asawa ay hindi kailanman nanliligaw sa ibang babae
Progress: 0.71
translated_text: nagkaroon ng dizzy spell | isang nahihilo na tuktok | sumakit ang ulo at nakaramdam ng pagkahilo | isang magulong bangin | nahihilo dahil sa suntok sa kanyang ulo | isang nakakabinging pag-akyat sa mukha ng bangin
Progress: 0.71
translated_text: isang nahihilo na blonde | magaan ang ulo na mga binatilyo | nakakalokong hagikgik
Progress: 0.71
translated_text: Tinalo ako ng con-man ng $50 | Niloko kami ng salesman na ito! | dinaya tayo ng kanilang matalinong pakana | Pinait nila ako sa pera ko
Progress: 0.71
translated_text: Niloloko niya ang kanyang asawa | Baka naliligaw ang asawa niya?
Progress: 0.71
translated_text: Tinalo ako ng con-man ng $50 | Niloko kami ng salesman na ito! | dinaya tayo ng kanilang matalinong pakana | Pinait nila ako sa pera ko
Progress: 0.71
translated_text: Niloloko niya ang kanyang asawa | Baka naliligaw ang asawa niya?
Progress: 0.71
translated_text: I-clear ang manuskrito para sa publikasyon | Hindi pinahintulutan ng rock star ang mapanirang-puri na talambuhay na ito
Progress: 0.71
translated_text: linisin ang mga dahon sa damuhan | Maaliwalas na niyebe mula sa kalsada
Progress: 0.71
translated_text: Maaari mo bang linawin ang mga pangungusap na ito? | I-clear ang tanong kung sino ang may kasalanan
Progress: 0.71
translated_text: Magkano ang kinikita mo sa isang buwan sa iyong bagong trabaho? | Malaki ang kinikita niya sa bago niyang trabaho | ang pagsasanib na ito ay nagdala ng maraming pera | Kinukuha niya ang $5,000 bawat buwan
Progress: 0.71
translated_text: magbayad ng utang | lutasin ang isang lumang utang
Progress: 0.71
translated_text: isang malinaw at kasalukuyang panganib | isang malinaw na paliwanag | isang malinaw na kaso ng pagpatay | isang malinaw na indikasyon na siya ay galit | nagbigay sa atin ng malinaw na ideya ng kalikasan ng tao
Progress: 0.71
translated_text: isang kumplikadong problema na nangangailangan ng malinaw na ulo | hindi malinaw kung ano ang inaasahan sa atin
Progress: 0.71
translated_text: isang malinaw na pananaw | isang malinaw na landas tungo sa tagumpay | bukas na tubig | ang bukas na kanayunan
Progress: 0.71
translated_text: malinaw na tubig | malinaw na mga plastic bag | malinaw na salamin | malinaw at malinis ang hangin
Progress: 0.71
translated_text: kami ay malinaw sa panganib | ang barko ay malinaw sa bahura
Progress: 0.71
translated_text: malinis na budhi | tumingin sa kanyang nagtatanong na may malinaw na hindi nababagabag na mga mata
Progress: 0.71
translated_text: pagsisikap na makakuha ng malinis na bass sa mga pag-record ng orkestra | malinaw na halakhak na parang talon | malinaw na pula at asul | isang magaan na tinig na parang pilak na kampana
Progress: 0.71
translated_text: kasing linaw ng sipol | malinaw na mga yapak sa niyebe | ang liham ay nagbalik ng malinaw na imahe ng kanyang lolo | isang spire clean-cut laban sa langit | isang malinaw na pattern
Progress: 0.71
translated_text: isang malinis na bill ng kalusugan | isang malinaw na nagwagi
Progress: 0.71
translated_text: isang malinaw na perpektong brilyante | ang maaliwalas na kutis ng isang malusog na dalaga
Progress: 0.71
translated_text: ay absolved sa lahat ng sisihin | ay ngayon malinaw na sa paratang ng duwag | ang kanyang opisyal na karangalan ay napagtibay
Progress: 0.71
translated_text: malinaw na isip | isang percipient na may-akda
Progress: 0.71
translated_text: basahin ang libro ng malinaw hanggang sa dulo | nakatulog nang malinaw sa buong gabi | may mga bukas na patlang na malinaw sa abot-tanaw
Progress: 0.71
translated_text: malinaw na makikita sa ilalim ng mikroskopyo | Umiyak siya ng malakas at malinaw
Progress: 0.71
translated_text: isang digmaan sa presyo | isang digmaan ng talino | diplomatikong digmaan
Progress: 0.71
translated_text: ang digmaan sa kahirapan | ang digmaan laban sa krimen
Progress: 0.71
translated_text: isang digmaan sa presyo | isang digmaan ng talino | diplomatikong digmaan
Progress: 0.71
translated_text: ang digmaan sa kahirapan | ang digmaan laban sa krimen
Progress: 0.71
translated_text: Nilabanan siya ng mga puno | tumayo sa pagsubok ng oras | Ang mga umaakyat sa bundok ay kailangang lumaban sa yelo at niyebe
Progress: 0.71
translated_text: ang biglaang pagkatok sa kanya | nakipag bash siya sa mukha niya | natamaan siya sa ulo
Progress: 0.71
translated_text: ang biglaang martilyo ng mga kamao ay nahuli sa kanya ng hindi nakabantay | ang paghampas ng mga paa sa pasilyo
Progress: 0.71
translated_text: martilyo ang pilak sa isang mangkok | gumawa ng isang pares ng mga dila
Progress: 0.71
translated_text: ang ospital ay may mahusay na nursing staff | ang heneral ay umasa sa kanyang mga tauhan upang gumawa ng mga karaniwang desisyon
Progress: 0.71
translated_text: inilagay niya ang hiyas sa isang singsing para sa kanyang asawa | mayroon siyang mga hiyas na gawa sa lahat ng pinakapambihirang bato
Progress: 0.71
translated_text: nilagyan niya ng ice pack ang pinsala bilang pag-iingat | isang magandang pananggalang ang isang patakaran sa seguro | ibinaba namin ang aming bantay
Progress: 0.71
translated_text: Hawakan ang posisyon na iyon sa likod ng mga puno! | Hawakan ang tulay laban sa mga pag-atake ng kalaban
Progress: 0.71
translated_text: bantayan laban sa pagiging masyadong palakaibigan sa mga tauhan | bantayan laban sa impeksyon
Progress: 0.71
translated_text: ang sanggol ay isang babae | nag-aaral palang sumakay ng tricycle ang mga babae
Progress: 0.72
translated_text: dalisay at vestal na kahinhinan | isang spinster o virgin lady | ang mga lalaki ay nag-utos na ang kanilang mga babae ay dapat na dalisay at birhen
Progress: 0.72
translated_text: ang average na distansya sa Buwan ay 384,400 kilometro | unang tumuntong ang mga lalaki sa buwan noong 1969
Progress: 0.72
translated_text: gumawa siya ng moon lamp na ginamit niya bilang night light | ang orasan ay may buwan na nagpapakita ng iba&#39;t ibang yugto
Progress: 0.72
translated_text: ang liwanag ng buwan ay ang kaaway ng smuggler | ang Buwan ay sapat na maliwanag upang mabasa ni
Progress: 0.72
translated_text: walang bakas ng ebidensya para sa claim | isang tincture ng condescension
Progress: 0.72
translated_text: lason ang isip ng isang tao | lason ang kapaligiran sa opisina
Progress: 0.72
translated_text: mahilig siyang mag-solve ng mga chessmate puzzle | iyan ay isang tunay na palaisipan
Progress: 0.72
translated_text: Tinalo ako nito! | Nakuha ko--hindi ko alam ang sagot! | isang nakakainis na problema | Ang tanong na ito ay talagang natigil sa akin
Progress: 0.72
translated_text: indibidwal na patak ng ulan | mangyaring markahan ang mga indibidwal na pahina | nagpunta sila sa kani-kanilang paraan
Progress: 0.72
translated_text: markahan ang mga indibidwal na pahina | sa isang case-by-case na batayan
Progress: 0.72
translated_text: isang indibidwal na naglilingkod | single occupancy | isang single bed
Progress: 0.72
translated_text: lahat tayo ay may kanya-kanyang sasakyan | bawat kuwarto ay may pribadong paliguan
Progress: 0.72
translated_text: maaaring mag-isa sa isang masikip na silid | nag-iisa sa kanyang mga iniisip | gusto kong mapag-isa
Progress: 0.72
translated_text: mag-isa lang siya nung nakilala namin siya | madalas siyang nag-iisa | ang nag-iisang skier sa bundok | isang malungkot na mangingisda ang nakatayo sa isang bungkos ng graba | isang malungkot na kaluluwa | isang nag-iisang manlalakbay
Progress: 0.72
translated_text: siya lang ang naniwala sa kanya | hindi mabubuhay sa tinapay lamang | Makukuha ko ang kotse na ito at ang kotse na ito lamang
Progress: 0.72
translated_text: nag-iisa siya sa larangan ng microbiology | ang teoryang ito ay lubos na nag-iisa sa pagtagos nito sa problema | Si Bach ay natatangi sa kanyang paghawak ng counterpoint | craftsmen na ang husay ay walang kapantay | walang kapantay na kakayahan sa palakasan | isang pagkasira ng batas na walang kapantay sa ating kasaysayan

Progress: 0.72
translated_text: ay ganap na sisihin | isang paaralan na ganap na nakatuon sa mga pangangailangan ng mga batang may problema | siya ay nagtatrabaho para kay Mr. Smith eksklusibo | ginawa ito para lamang sa pera | ang pasanin ng patunay ay nakasalalay sa prosekusyon lamang | isang pribilehiyong ipinagkaloob lamang sa kanya
Progress: 0.72
translated_text: nag-iisa ang bata sa bahay | ang haligi ay nakatayong mag-isa, walang sinusuportahan | solo siyang lumipad
Progress: 0.72
translated_text: Iginagalang ko ang kanyang paghatol | Pinahahalagahan namin ang kanyang pagkamalikhain
Progress: 0.72
translated_text: Iginagalang ko ang kanyang paghatol | Pinahahalagahan namin ang kanyang pagkamalikhain
Progress: 0.72
translated_text: Kailangan mong maging isang mahusay na tagamasid upang makita ang lahat ng mga detalye | Nakikita mo ba ang ibon sa punong iyon? | Siya ay bulag--hindi siya nakakakita
Progress: 0.72
translated_text: Ngayon nakikita ko na! | Hindi ko lang makita ang iyong punto | Napagtanto ba niya kung gaano kahalaga ang desisyong ito? | Hindi ko maintindihan ang ideya
Progress: 0.72
translated_text: Natagpuan namin ang mga Republican na nanalo sa mga opisina | Marami kang makikitang dayaan sa paaralang ito | Noong 1960&#39;s nakita ang paghihimagsik ng nakababatang henerasyon laban sa mga itinatag na tradisyon | Gusto kong makita ang mga resulta
Progress: 0.72
translated_text: Hindi ko siya nakikitang nakasakay sa kabayo! | Nakikita ko kung ano ang mangyayari | Nakikita ko ang panganib sa diskarteng ito
Progress: 0.72
translated_text: Medyo iba ang tingin niya sa akin | I consider her to be shallow | Hindi ko masyadong nakikita ang sitwasyon na negatibo tulad ng nakikita mo
Progress: 0.72
translated_text: Nalaman ko na mayroon siyang dalawang anak na nasa hustong gulang na | Nakikita ko na na-promote ka
Progress: 0.72
translated_text: manood ng palabas sa telebisyon | Ang programang ito ay makikita sa buong mundo | tingnan ang isang eksibisyon | Manood ng palabas sa Broadway | Manood ng sine
Progress: 0.72
translated_text: Malamang magkita tayo sa meeting | Napakasaya na makita kang muli!
Progress: 0.72
translated_text: Gusto kong makita kung nagsasalita siya ng French | Tingnan kung gumagana ito | alamin kung nagsasalita siya ng Russian | Suriin kung ang tren ay aalis sa oras
Progress: 0.72
translated_text: Pinatunayan niya na ang mga balbula ay sarado | Tingnan na ang mga kurtina ay sarado | kontrolin ang kalidad ng produkto
Progress: 0.72
translated_text: Dapat kang magpatingin sa isang abogado | Kailangan naming magpatingin sa isang psychiatrist
Progress: 0.72
translated_text: Nakikita mo ba ang tungkol sa tanghalian? | Dapat kong asikasuhin ang bagay na ito | Siya ang nag-asikaso sa negosyong ito
Progress: 0.72
translated_text: makikita ka na ng doktor | Walang nakikita ang ministro bago magtanghali
Progress: 0.72
translated_text: Alam mo bang may nakikita siyang matandang lalaki? | Nililigawan na naman niya ang dati niyang asawa!
Progress: 0.72
translated_text: Tingnan kung makakapunta ka bukas | tingnan natin--anong pelikula ang dapat nating panoorin ngayong gabi?
Progress: 0.72
translated_text: Sinuri ng customs agent ang bagahe | Kailangan kong makita ang iyong pasaporte bago ka makapasok sa bansa
Progress: 0.72
translated_text: Marami kaming pagsubok na pinagdaanan | nakakita siya ng aksyon sa Viet Nam
Progress: 0.72
translated_text: Anong mensahe ang nakikita mo sa liham na ito? | Paano mo binibigyang kahulugan ang kanyang pag-uugali?
Progress: 0.72
translated_text: sensational journalistic reportage ng iskandalo | dilaw na pindutin
Progress: 0.72
translated_text: ang maliit na dilaw na mantsa ng pagtataksil | masyadong dilaw para tumayo at lumaban
Progress: 0.72
translated_text: isang pananaw na unti-unting nabubuo | mga batas na umiiral sa loob ng maraming siglo
Progress: 0.72
translated_text: pinag-aaralan nila ang ebolusyon ng uniberso | ang pinakamalaking puno na umiiral
Progress: 0.72
translated_text: nangolekta siya ng mga tuyong patpat para sa apoy sa kampo | ang bata ay may isang minatamis na mansanas sa isang stick
Progress: 0.72
translated_text: cinnamon sticks | isang stick ng dinamita
Progress: 0.72
translated_text: maglagay ng bala sa mesa | idikit ang iyong hinlalaki sa bitak
Progress: 0.72
translated_text: Kami ay nananatili sa Detroit; hindi kami lilipat sa Cincinnati | Manatili dito sa sulok! | Manatili at may matututunan ka!
Progress: 0.72
translated_text: Ang mga residente ng nayong ito ay sumunod sa Katolisismo | Nananatili siya sa kanyang mga prinsipyo
Progress: 0.72
translated_text: Siya ay tumayo sa tabi ng kanyang asawa sa oras ng problema | Ang magkakaibigan ay magkasama sa digmaan
Progress: 0.72
translated_text: Ang damit ay dumikit sa kanyang katawan | Ang label ay nakadikit sa kahon | Ang mga butil ng bigas ng sushi ay magkakaugnay
Progress: 0.72
translated_text: Inipit nila sa akin ang bill ng hapunan | Nasaktan ako ng malaking singil sa buwis
Progress: 0.73
translated_text: Tinalo ako nito! | Nakuha ko--hindi ko alam ang sagot! | isang nakakainis na problema | Ang tanong na ito ay talagang natigil sa akin
Progress: 0.73
translated_text: Ilagay ang iyong mga gamit dito | Ibaba ang tray | Itakda ang mga aso sa pabango ng mga nawawalang bata | Maglagay ng diin sa isang tiyak na punto
Progress: 0.73
translated_text: Ang kantang iyon ay naglagay sa akin sa kakila-kilabot na magandang katatawanan | ilagay ang iyong mga ideya sa pagsulat
Progress: 0.73
translated_text: Hindi ko ilalagay ito sa paraang iyon | Ibinigay niya ang kanyang kahilingan sa napakagalang na pananalita
Progress: 0.73
translated_text: Masyado niyang binibigyang diin sa kanya ang huling pahayag | Inilagay niya ang lahat ng kanyang pagsisikap sa trabahong ito | Ang guro ay naglagay ng isang kawili-wiling twist sa interpretasyon ng kuwento
Progress: 0.73
translated_text: ayusin ang aking iskedyul | itakda ang buhay ng isang tao | Inilagay ko ang mga alaalang ito sa mga nakaraan
Progress: 0.73
translated_text: Maaari mo bang ikonekta ang dalawang loudspeaker? | Pagtaliin ang mga lubid | Mag-link ng mga braso
Progress: 0.73
translated_text: Hindi ko maiugnay ang dalawang piraso ng ebidensya sa aking isipan | isama ang mga katotohanang ito | Hindi ko talaga ma-relate ang mga pangyayaring ito
Progress: 0.73
translated_text: Ang dalawang kalye ay nagkokonekta upang maging isang highway | Nagsanib ang aming mga landas | Muling nag-link ang mga manlalakbay sa airport
Progress: 0.73
translated_text: Ang lokal na tren ay hindi kumonekta sa Amtrak na tren | Ang mga eroplano ay hindi kumonekta at kailangan mong maghintay ng apat na oras
Progress: 0.73
translated_text: Pakisaksak ang toaster! | Ikonekta ang TV para mapanood natin ang football game ngayong gabi
Progress: 0.73
translated_text: aminin ang isang tao sa propesyon | Siya ay ipinasok sa New Jersey Bar
Progress: 0.73
translated_text: siya ay isang modelo ng magalang na pagpigil | hindi siya nawalan ng kontrol sa sarili
Progress: 0.73
translated_text: legal na pagpigil | mga pagpigil na ipinataw sa mga pag-import
Progress: 0.73
translated_text: ang kanyang panukala ay walang iba kundi isang bahay ng mga baraha | isang bubble ng real estate
Progress: 0.73
translated_text: iyon ang krus niyang pasanin | dinadala niya ang kanyang mga paghihirap na parang koronang tinik
Progress: 0.73
translated_text: Ang pinaka-nabigo sa bawat naghamon ay ang kamangha-manghang pag-akyat ni Ruth noong Setyembre | palara ang iyong kalaban
Progress: 0.73
translated_text: Ang mga ilog ay tumatawid sa lambak na sahig | Ang paradahan ay sumasaklaw ng 3 ektarya | Ang nobela ay sumasaklaw ng tatlong siglo
Progress: 0.73
translated_text: tumawid sa kabayo at asno | Sinubukan ni Mendel ang pag-crossbreed | ang mga species na ito ay hindi nag-interbreed
Progress: 0.73
translated_text: ang mga miyembro ng krus ay dapat na lahat ng bakal | mula sa nakahalang bulwagan ang hagdanan ay umaakyat nang maganda | transversal vibrations | nakahalang colon
Progress: 0.73
translated_text: walang kompetisyon walang market | pinalayas sila sa palengke
Progress: 0.73
translated_text: walang kompetisyon walang market | sila ay itinaboy mula sa pamilihan

Progress: 0.73
translated_text: walang kompetisyon walang market | pinalayas sila sa palengke
Progress: 0.73
translated_text: mag-imbak ng butil para sa taglamig | Ang oso ay nag-iimbak ng taba para sa panahon ng hibernation kapag hindi siya kumakain
Progress: 0.73
translated_text: saan natin iimbak ang mga gulay? | Hindi ko maiimbak lahat ng libro sa attic kaya nagbenta ako ng ilan
Progress: 0.73
translated_text: inirerekomenda ng doktor ang regular na ehersisyo | nag-ehersisyo siya | ang pisikal na pagsusumikap na kinakailangan ng kanyang trabaho ay nagpapanatili sa kanya na magkasya
Progress: 0.73
translated_text: nagbabala siya laban sa paggamit ng narcotic drugs | sanay sa paggamit ng mga kompyuter
Progress: 0.73
translated_text: Ang ilang mga magulang ay nag-eehersisyo sa kanilang mga sanggol | Pinaghirapan ako ng aking personal na tagapagsanay | magtrabaho ng mga kalamnan | ang puzzle na ito ay magsasanay sa iyong isip
Progress: 0.73
translated_text: Nag-drill kami ng mga pandiwang Pranses araw-araw | Ang mga pianista ay nagsasanay ng mga kaliskis
Progress: 0.73
translated_text: Sinasanay ng matandang master ang mga world-class na biyolinista | binuo natin ang mga pinuno para sa hinaharap
Progress: 0.73
translated_text: Siya ay nagsasanay upang maging isang guro | Nagsanay siya bilang isang legal aid
Progress: 0.73
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.73
translated_text: Inaayos niya ang kanyang anak para maging kahalili niya | Ang prinsipe ay inihanda na maging Hari balang araw | Sinanay nila siyang maging isang mandirigma
Progress: 0.73
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.73
translated_text: Mangyaring huwag tutok sa iyong nakababatang kapatid! | Sinanay niya ang kanyang baril sa magnanakaw | Huwag sanayin ang iyong camera sa mga babae | Mag-swipe sa kalaban
Progress: 0.73
translated_text: Sinasanay niya ang aming Olympic team | Siya ang nagtuturo sa crew
Progress: 0.73
translated_text: Nag-rail sila mula Roma hanggang Venice | Nagsanay siya sa Hamburg
Progress: 0.73
translated_text: Sinusundan ng paslit ang kanyang pantalon | Sinanay niya ang kanyang mahabang scarf sa likod niya
Progress: 0.73
translated_text: siya ay nagtatakda ng magandang mesa | silid at board
Progress: 0.73
translated_text: hindi mo dapat ipakita ang iyong pusod sa telebisyon | pinagtatalunan nila kung may pusod o wala si Adam | may tattoo siya sa itaas lang ng pusod niya
Progress: 0.73
translated_text: Tumaya ako ng $100 sa bagong kabayong iyon | Nilaro niya ang lahat ng kanyang pera sa dark horse
Progress: 0.73
translated_text: maaari kang umasa na tutulungan kita anumang oras | Tumingin sa iyong mga kaibigan para sa suporta | Pwede mong taya yan! | Depende sa iyong pamilya sa oras ng krisis
Progress: 0.73
translated_text: Ang pasyente ay dapat uminom ng ilang litro bawat araw | Ang mga bata ay gustong uminom ng soda
Progress: 0.73
translated_text: I-toast natin ang birthday girl! | Inom tayo sa Bagong Taon
Progress: 0.73
translated_text: isang maingay na pulutong ng mga lasing na mandaragat | walang magawang lasing
Progress: 0.73
translated_text: nakaramdam ng pagkalasing sa kanyang tagumpay | lasing sa excitement
Progress: 0.73
translated_text: may mga makapangyarihang makina sa ilalim ng mga hood ng mga bagong kotse | inalis ng mekaniko ang cowling para maayos ang makina ng eroplano
Progress: 0.73
translated_text: Ang ganitong uri ng trabaho ay nakakapagod sa akin | Ako ay matalo | Naligo na siyang lahat pagkatapos ng pagsusulit
Progress: 0.73
translated_text: ang kotseng ito ay kumonsumo ng maraming gas | Naubos namin ang aming ipon | Tumatakbo sila sa 20 bote ng alak sa isang linggo
Progress: 0.73
translated_text: maubos ang ipon | Mabilis naming nilaro ang aming lakas
Progress: 0.74
translated_text: naubos ang mga produkto ng pagkasunog sa makina | naglalabas ng gas ang halaman
Progress: 0.74
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.74
translated_text: ang kanyang pagmamahal sa kanyang trabaho | ang mga bata ay nangangailangan ng maraming pagmamahal
Progress: 0.74
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.74
translated_text: ang kanilang pag-ibig ay nag-iwan sa kanila na walang malasakit sa kanilang paligid | siya ang kanyang unang pag-ibig
Progress: 0.74
translated_text: naiinis sa kanya ang kanyang pakikipagtalik | wala siyang pag-ibig sa loob ng ilang buwan | napakakomplikado ng buhay pag-ibig niya
Progress: 0.74
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.74
translated_text: Natutulog ang estudyanteng ito sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.74
translated_text: ang kanyang pagmamahal sa kanyang trabaho | ang mga bata ay nangangailangan ng maraming pagmamahal
Progress: 0.74
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.74
translated_text: ang kanilang pag-ibig ay nag-iwan sa kanila na walang malasakit sa kanilang paligid | siya ang kanyang unang pag-ibig
Progress: 0.74
translated_text: naiinis sa kanya ang kanyang pakikipagtalik | hindi siya nagkaroon ng anumang pag-ibig sa mga buwan | napakakomplikado ng buhay pag-ibig niya
Progress: 0.74
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.74
translated_text: Ang estudyanteng ito ay natutulog sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.74
translated_text: sinubukan niyang makakuha ng mas magandang view dito | ang kanyang pagsisiyasat sa larangan ng digmaan ay limitado
Progress: 0.74
translated_text: iba ang opinyon ko sa opinyon mo | Hindi ako sa iyong panghihikayat | ano ang iyong mga saloobin sa Haiti?
Progress: 0.74
translated_text: nagpinta siya ng mga eksena mula sa pang-araw-araw na buhay | Ang figure 2 ay nagpapakita ng photographic at schematic view ng kagamitan
Progress: 0.74
translated_text: Medyo iba ang tingin niya sa akin | I consider her to be shallow | Hindi ko masyadong nakikita ang sitwasyon na negatibo tulad ng nakikita mo
Progress: 0.74
translated_text: manood ng palabas sa telebisyon | Ang programang ito ay makikita sa buong mundo | tingnan ang isang eksibisyon | Manood ng palabas sa Broadway | Manood ng sine
Progress: 0.74
translated_text: parang wala akong nakita dati | nabawasan sa wala ang lahat ng gawaing nagawa namin | nag-racked up kami ng isang nakakalungkot na itlog ng gansa | lahat ng ito ay walang kabuluhan | Hindi ko narinig si zilch tungkol dito
Progress: 0.74
translated_text: ang kanyang pagmamahal sa kanyang trabaho | ang mga bata ay nangangailangan ng maraming pagmamahal
Progress: 0.74
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.74
translated_text: ang kanilang pag-ibig ay nag-iwan sa kanila na walang malasakit sa kanilang paligid | siya ang kanyang unang pag-ibig
Progress: 0.74
translated_text: naiinis sa kanya ang kanyang pakikipagtalik | hindi siya nagkaroon ng anumang pag-ibig sa mga buwan | napakakomplikado ng buhay pag-ibig niya
Progress: 0.74
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.74
translated_text: Ang estudyanteng ito ay natutulog sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.74
translated_text: ang kanyang pagmamahal sa kanyang trabaho | ang mga bata ay nangangailangan ng maraming pagmamahal
Progress: 0.74
translated_text: ang teatro ay ang kanyang unang pag-ibig | may hilig siya sa cock fighting
Progress: 0.74
translated_text: ang kanilang pag-ibig ay nag-iwan sa kanila na walang malasakit sa kanilang paligid | siya ang kanyang unang pag-ibig
Progress: 0.74
translated_text: naiinis sa kanya ang kanyang pakikipagtalik | hindi siya nagkaroon ng anumang pag-ibig sa mga buwan | napakakomplikado ng buhay pag-ibig niya

Progress: 0.74
translated_text: Gustung-gusto ko ang pagkaing Pranses | Mahal niya ang kanyang amo at nagsusumikap siya para dito
Progress: 0.74
translated_text: Ang estudyanteng ito ay natutulog sa lahat ng tao sa kanyang dorm | Kilala ni Adam si Eba | Naranasan mo na bang maging intimate sa lalaking ito?
Progress: 0.74
translated_text: Pinasigla ng libro ang kanyang imahinasyon | Ang dulang ito ay nagpapasigla
Progress: 0.74
translated_text: pasiglahin ang aking gana | excite ang audience | pukawin ang mga damdamin
Progress: 0.74
translated_text: Ang mga kwentong ito ay yumanig sa komunidad | niyanig ng digmaang sibil ang bansa
Progress: 0.74
translated_text: siya ay magiging emosyonal sa wala sa lahat | siya ay nagtrabaho up tungkol sa lahat ng ingay
Progress: 0.74
translated_text: isang pulutong ng mga nahihibang mga tagahanga ng baseball | isang bagay na galit na galit sa kanilang kagalakan | isang baliw na ipo-ipo ng kasiyahan
Progress: 0.74
translated_text: aso, fox, at iba pa | hindi namin gusto ang mga tulad mo sa paligid
Progress: 0.74
translated_text: Hindi na natin makikita ang katulad niya | Hindi ko kayang tiisin ang mga taong katulad niya
Progress: 0.74
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.74
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.74
translated_text: suit ng katulad na disenyo | isang limitadong bilog ng mga katulad na isip | ang mga miyembro ng pamilya ng pusa ay may katulad na disposisyon | tulad ng dalawang gisantes sa isang pod | mala-dog na debosyon | isang parang panaginip na kalidad
Progress: 0.74
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.74
translated_text: lahat ng politiko ay magkatulad | magkamukha sila | ang mga kaibigan ay karaniwang magkapareho sa background at panlasa
Progress: 0.74
translated_text: mga kahon na may kaukulang sukat | ang katulad na panahon ng naunang taon
Progress: 0.74
translated_text: aso, fox, at iba pa | hindi namin gusto ang mga tulad mo sa paligid
Progress: 0.74
translated_text: Hindi na natin makikita ang katulad niya | Hindi ko kayang tiisin ang mga taong katulad niya
Progress: 0.74
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.74
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.74
translated_text: galit sa panahon | galit na mga customer | isang galit na katahimikan | pagpapadala ng galit na mga sulat sa mga papel
Progress: 0.74
translated_text: galit na ulap sa abot-tanaw | galit na galit na hangin | ang rumaragasang dagat
Progress: 0.75
translated_text: Ayaw ko sa pagkaing Mexican | Kinasusuklaman niya ang mga pulitiko
Progress: 0.75
translated_text: hindi gumagana ang heating system | mayroon silang radiant heating
Progress: 0.75
translated_text: pinapainit ng araw ang mga karagatan | init ang tubig sa kalan
Progress: 0.75
translated_text: Ang magarbong paraan ng pamumuhay ng mayayaman ay nag-aapoy sa poot ng mahihirap | Ang kapalaran ng mga refugee ay pumukaw ng habag sa buong mundo | Gumising ng lumang damdamin ng poot
Progress: 0.75
translated_text: Pinagalitan ng ina ang anak sa pagpasok sa sasakyan ng estranghero | Ang kinatawan ay ginulo ang Punong Ministro | Binihisan ng kostumer ang waiter para sa pagdadala ng malamig na sopas
Progress: 0.75
translated_text: purong hangin at tubig | purong ginto | puro pangunahing kulay | ang dalisay at kaibig-ibig na kanta ng biyolin | puro tono | purong oxygen
Progress: 0.75
translated_text: isang arrant tanga | isang ganap na duwag | isang ganap na tanga | isang kontrabida na may dobleng tinina | matinding kapabayaan | isang perpektong idiot | puro katangahan | anong gulo | stark staring mad | isang masinsinang kontrabida | walang kwentang salita | ang walang halong katotohanan
Progress: 0.75
translated_text: Purong at matamis ang aking nadama bilang isang bagong sanggol | dalisay na parang niyebe
Progress: 0.75
translated_text: dalisay at vestal na kahinhinan | isang spinster o virgin lady | ang mga lalaki ay nag-utos na ang kanilang mga babae ay dapat na dalisay at birhen
Progress: 0.75
translated_text: mababa sa kanyang dignidad ang mandaya | ipinakita ang kanyang tunay na dignidad kapag nasa ilalim ng presyon
Progress: 0.75
translated_text: ang yabang niya ay mas malala pa sa laban niya | sa tuwing nanalo siya ay nalantad kami sa kanyang gasconade
Progress: 0.75
translated_text: isang amo kamay sa karpintero | kanyang pinagyayabang maisan
Progress: 0.75
translated_text: ang yabang niya ay mas malala pa sa laban niya | sa tuwing nanalo siya ay nalantad kami sa kanyang gasconade
Progress: 0.75
translated_text: isang amo kamay sa karpintero | kanyang pinagyayabang maisan
Progress: 0.75
translated_text: isang tampok na artista | isang itinatampok na item sa pagbebenta
Progress: 0.75
translated_text: malambot na boses | malambot na musika
Progress: 0.75
translated_text: malambot na mga kamay | maselang balat ng isang sanggol
Progress: 0.75
translated_text: isang madalas na binibigkas na opinyon | mga tinig na katinig gaya ng `b&#39; at `g&#39; at `z&#39;
Progress: 0.75
translated_text: malambot na data | ang malambot na agham
Progress: 0.75
translated_text: Ang mapagpalayaw na mga magulang ay nanganganib na masira ang kanilang mga anak | masyadong malambot sa mga bata | malambot sila sa krimen
Progress: 0.75
translated_text: isang malumanay na saway | isang ugat ng banayad na kabalintunaan | sundot magiliw na saya sa kanya
Progress: 0.75
translated_text: isang madaling tapik sa balikat | banayad na ulan | isang banayad na simoy | isang malambot (o magaan) na pagtapik sa bintana
Progress: 0.75
translated_text: siya ay masyadong malambot para sa hukbo | malabo sa gitna | malalambot na pisngi
Progress: 0.75
translated_text: anong ayos ng trabaho! | ang maginhawang buhay ng isang parttime consultant | isang malambot na trabaho
Progress: 0.75
translated_text: maaliwalas na araw at gabi | ang klima ay banayad at nakakatulong sa buhay o paglago | isang malambot na simoy ng hangin
Progress: 0.75
translated_text: ang buwan ay nagbigay ng malambot na mga anino | malambot na kulay ng pastel | mahinang pag-iilaw
Progress: 0.75
translated_text: sapat ay kasing ganda ng isang piging | mayroong higit pa sa sapat na mga abogado sa bansang ito
Progress: 0.75
translated_text: isang sapat na kita | ang pagkain ay sapat | isang disenteng sahod | sapat na pagkain | sapat na pagkain
Progress: 0.75
translated_text: Kumain na ba ako? | Marami na ako, salamat
Progress: 0.75
translated_text: isang madaling trabaho | isang madaling problema | isang madaling tagumpay | ang bahay ay madaling init | nasiyahan sa madaling sagot | kinuha ang madaling paraan sa kanyang dilemma
Progress: 0.75
translated_text: isang madaling paglalakad sa paligid ng bloke | sa isang dahan-dahan (o maluwag) na bilis
Progress: 0.75
translated_text: alam na ginawa ko ang aking makakaya, ang aking isip ay madali | isang madaling mabait na paraan | sa oras na nahaharap ang bata sa aktwal na problema sa pagbabasa ay pamilyar siya at komportable sa lahat ng mga elemento ng salita
Progress: 0.75
translated_text: isang madaling tapik sa balikat | banayad na ulan | isang banayad na simoy | isang malambot (o magaan) na pagtapik sa bintana
Progress: 0.75
translated_text: isang madaling biktima | isang madaling marka
Progress: 0.75
translated_text: sila ay komportable o kahit na mayaman sa ilang mga pamantayan | madaling pamumuhay | isang maunlad na pamilya | maayos ang kalagayan ng kanyang pamilya sa pananalapi | mayayamang miyembro ng komunidad
Progress: 0.75
translated_text: isang madaling pag-akyat | isang banayad na dalisdis
Progress: 0.75
translated_text: ang kanyang madaling birtud | sinabihan siyang iwasan ang maluwag (o magaan) na mga babae | bastos na pag-uugali
Progress: 0.75
translated_text: madali siyang na-excite | ay madaling malito | madali siyang nanalo | ang china na ito ay napakadaling masira | napakadali ng tagumpay

Progress: 0.75
translated_text: dahan dahan siyang nagsalita | dahan dahan ka dito--madulas ang daan | mabilis na gumagalaw ang mga glacier | dahan-dahan lang para makita ko ang mga tanawin
Progress: 0.75
translated_text: maubos ang ipon | Mabilis naming nilaro ang aming lakas
Progress: 0.75
translated_text: isang nakakapagod na martsa | ang pagbisita ay lalo na suot
Progress: 0.75
translated_text: Ang ganitong uri ng trabaho ay nakakapagod sa akin | Ako ay matalo | Naligo na siyang lahat pagkatapos ng pagsusulit
Progress: 0.75
translated_text: ang kotseng ito ay kumonsumo ng maraming gas | Naubos namin ang aming ipon | Tumatakbo sila sa 20 bote ng alak sa isang linggo
Progress: 0.75
translated_text: maubos ang ipon | Mabilis naming nilaro ang aming lakas
Progress: 0.75
translated_text: naubos ang mga produkto ng pagkasunog sa makina | naglalabas ng gas ang halaman
Progress: 0.75
translated_text: isang nakakapagod na martsa | ang pagbisita ay lalo na suot
Progress: 0.75
translated_text: isang mabigat na kargada | ang tingga ay isang mabigat na metal | mabigat na kasangkapan sa mahogany
Progress: 0.75
translated_text: mabigat na buwis | isang mabigat na multa | mabigat na nasawi | mabigat na pagkalugi | malakas na ulan | matinding trapiko
Progress: 0.75
translated_text: mabigat na artilerya | mabigat na impanterya | isang mabigat na cruiser | mabibigat na baril | ang mabigat na industriya ay nagsasangkot ng malakihang produksyon ng mga pangunahing produkto (tulad ng bakal) na ginagamit ng ibang mga industriya
Progress: 0.75
translated_text: isang mabigat na puso | isang mabigat na iskedyul | mabigat na balita | isang matinding katahimikan | mabigat na talukap ng mata
Progress: 0.76
translated_text: isang malakas na suntok | mabigat ang labanan | mabigat na dagat
Progress: 0.76
translated_text: mabigat na hydrogen | mabigat na tubig
Progress: 0.76
translated_text: makapal na usok | mabigat na ulap | hindi maarok na dilim
Progress: 0.76
translated_text: malaking gumastos | malaking mangangain | mabigat na mamumuhunan
Progress: 0.76
translated_text: mabibigat na tunog | isang herald na pinili para sa kanyang tinig
Progress: 0.76
translated_text: mabigat na responsibilidad | humarap sa isang mabigat na desisyon sa panahon ng krisis | isang mabigat na kasalanan | mabibigat na usapin ng estado | ang mabibigat na bagay na tatalakayin sa peace conference
Progress: 0.76
translated_text: ang mabigat na pagtapak ng mga pagod na tropa | inilipat sa isang lumbering sag-bellied trot | napakabigat na sinaunang mga hayop | isang matinding hikab
Progress: 0.76
translated_text: isang mabigat na trak | mabibigat na makinarya
Progress: 0.76
translated_text: puno na mabigat sa prutas | mga baging na binibigatan ng mga ubas
Progress: 0.76
translated_text: mabigat na paghinga | ang paksang ginawa para sa pinaghirapang pagbabasa
Progress: 0.76
translated_text: nagtrabaho sa kanilang mahirap na paraan sa pagmimina | isang nakakapagod na kampanya | mahirap na paggawa | mabigat na trabaho | mabigat na pagpunta | gumugol ng maraming matrabahong oras sa proyekto | magtakda ng parusang bilis
Progress: 0.76
translated_text: mabigat na katatawanan | isang mangungunang pag-uusap
Progress: 0.76
translated_text: isang mabigat na tulog | nakatulog ng mahimbing | isang sound sleeper | malalim na tulog na walang gising
Progress: 0.76
translated_text: ay malaki sa anak | ay mahusay na may anak
Progress: 0.76
translated_text: nagtrabaho sa kanilang mahirap na paraan sa pagmimina | isang nakakapagod na kampanya | mahirap na paggawa | mabigat na trabaho | mabigat na pagpunta | gumugol ng maraming matrabahong oras sa proyekto | magtakda ng parusang bilis
Progress: 0.76
translated_text: iniwan siya ng kendi na may masamang lasa | ang melon ay may masarap na lasa
Progress: 0.76
translated_text: ang aking sariling kagustuhan ay para sa magandang panitikan | ang Irish ay may pagkahilig sa blarney
Progress: 0.76
translated_text: ang pagmamataas at kawalan ng panlasa ay nag-ambag sa kanyang mabilis na tagumpay | ang magtanong sa partikular na oras na iyon ay ang panghuli sa masamang lasa
Progress: 0.76
translated_text: nakatikim siya ng buhay sa wild side | nasiyahan siya sa kanyang maikling lasa ng kalayaan
Progress: 0.76
translated_text: Subukan ang mga bagong crackers na ito | Tikman ang mga regional dish
Progress: 0.76
translated_text: Kailangan mong maging isang mahusay na tagamasid upang makita ang lahat ng mga detalye | Nakikita mo ba ang ibon sa punong iyon? | Siya ay bulag--hindi siya nakakakita
Progress: 0.76
translated_text: Ngayon nakikita ko na! | Hindi ko lang makita ang iyong punto | Napagtanto ba niya kung gaano kahalaga ang desisyong ito? | Hindi ko maintindihan ang ideya
Progress: 0.76
translated_text: Natagpuan namin ang mga Republican na nanalo sa mga opisina | Marami kang makikitang dayaan sa paaralang ito | Noong 1960&#39;s nakita ang paghihimagsik ng nakababatang henerasyon laban sa mga itinatag na tradisyon | Gusto kong makita ang mga resulta
Progress: 0.76
translated_text: Hindi ko siya nakikitang nakasakay sa kabayo! | Nakikita ko kung ano ang mangyayari | Nakikita ko ang panganib sa diskarteng ito
Progress: 0.76
translated_text: Medyo iba ang tingin niya sa akin | I consider her to be shallow | Hindi ko masyadong nakikita ang sitwasyon na negatibo tulad ng nakikita mo
Progress: 0.76
translated_text: Nalaman ko na mayroon siyang dalawang anak na nasa hustong gulang na | Nakikita ko na na-promote ka
Progress: 0.76
translated_text: manood ng palabas sa telebisyon | Ang programang ito ay makikita sa buong mundo | tingnan ang isang eksibisyon | Manood ng palabas sa Broadway | Manood ng sine
Progress: 0.76
translated_text: Malamang magkita tayo sa meeting | Napakasaya na makita kang muli!
Progress: 0.76
translated_text: Gusto kong makita kung nagsasalita siya ng French | Tingnan kung gumagana ito | alamin kung nagsasalita siya ng Russian | Suriin kung aalis ang tren sa oras
Progress: 0.76
translated_text: Pinatunayan niya na ang mga balbula ay sarado | Tingnan na ang mga kurtina ay sarado | kontrolin ang kalidad ng produkto
Progress: 0.76
translated_text: Dapat kang magpatingin sa isang abogado | Kailangan naming magpatingin sa isang psychiatrist
Progress: 0.76
translated_text: Nakikita mo ba ang tungkol sa tanghalian? | Dapat kong asikasuhin ang bagay na ito | Siya ang nag-asikaso sa negosyong ito
Progress: 0.76
translated_text: makikita ka na ng doktor | Walang nakikita ang ministro bago magtanghali
Progress: 0.76
translated_text: Alam mo bang may nakikita siyang matandang lalaki? | Nililigawan na naman niya ang dati niyang asawa!
Progress: 0.76
translated_text: Tingnan kung makakapunta ka bukas | tingnan natin--anong pelikula ang dapat nating panoorin ngayong gabi?
Progress: 0.76
translated_text: Sinuri ng customs agent ang bagahe | Kailangan kong makita ang iyong pasaporte bago ka makapasok sa bansa
Progress: 0.76
translated_text: Marami kaming pagsubok na pinagdaanan | nakakita siya ng aksyon sa Viet Nam
Progress: 0.76
translated_text: Anong mensahe ang nakikita mo sa liham na ito? | Paano mo binibigyang kahulugan ang kanyang pag-uugali?
Progress: 0.76
translated_text: marami siyang gawaing dapat gawin | ang bilang ng mga parameter ay maliit | ang bilang ay halos isang libo
Progress: 0.76
translated_text: ginawa niya ang kanyang kilos ng tatlong beses tuwing gabi | nagkaroon siya ng kaakit-akit na maliit na gawain | isa ito sa pinakamagandang numerong nagawa niya
Progress: 0.76
translated_text: mas gusto niya ang black nylon number | ang sweater na ito ay isang all-wool na numero
Progress: 0.76
translated_text: Ang mga bayarin ay umabot sa $2,000 | Umabot sa $2,000 ang bill
Progress: 0.76
translated_text: Mabibilang mo ba ang mga libro sa iyong istante? | Bilangin ang iyong sukli
Progress: 0.76
translated_text: nag-ulat siya ng ilang hindi kilalang tawag | tumawag siya sa London | narinig niyang nagri-ring ang phone pero ayaw niyang sagutin ang tawag
Progress: 0.76
translated_text: hindi na tumatawag sa hapon ang mga asawa ng senior professors sa mga bagong dating | ang mga tauhan sa mga nobela ni Henry James ay walang hanggang tawag sa isa&#39;t isa, kadalasan sa parlor ng ilang tirahan

Progress: 0.76
translated_text: maraming tawag para sa mga kwentong Pasko | hindi maraming tawag para sa buggywhips
Progress: 0.76
translated_text: ang panawagan ng pastor sa kanyang mga parokyano | tawag ng tindero sa isang customer
Progress: 0.76
translated_text: Pinangalanan nila ang kanilang anak na David | Ang bagong paaralan ay ipinangalan sa sikat na pinuno ng Civil Rights
Progress: 0.76
translated_text: Tinawag niya akong bastard | Tinawag niyang tamad at walang utang na loob ang kanyang mga anak
Progress: 0.76
translated_text: Sinubukan kitang tawagan buong gabi | Kumuha ng dalawang aspirin at tawagan ako sa umaga
Progress: 0.77
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.77
translated_text: Siya ay tinawag sa opisina ng direktor | Tumawag ng pulis!
Progress: 0.77
translated_text: Ang Wannsee Conference ay tinawag upang talakayin ang `Final Solution&#39; | Ang bagong dean ay tumatawag ng mga pagpupulong bawat linggo
Progress: 0.77
translated_text: Tumatawag si Hawaii! | Isang transmiter sa Samoa ang narinig na tumatawag
Progress: 0.77
translated_text: Lagi niya akong tinatawag ng `Sir&#39; | Tawagin mo akong Mister | Tinatawag niya ito sa unang pangalan
Progress: 0.77
translated_text: 4 na beses na siyang tinawag para sa tungkulin ng hurado | Tinawag nila siya sa aktibong tungkuling militar
Progress: 0.77
translated_text: Tinawag niya ang pangalan ko | Tinawag ng auctioneer ang mga bid
Progress: 0.77
translated_text: ang bawat bata ay inaasahang magbabayad para sa kanilang panatilihin | nag-apply siya sa estado para sa suporta | hindi na niya kayang kumita ng sariling kabuhayan
Progress: 0.77
translated_text: gulat sa stock market | isang takot sa digmaan | isang bomb scare ang nagbunsod sa kanila upang lumikas sa gusali
Progress: 0.77
translated_text: Ang estranghero na tumatambay sa paligid ng gusali ay natatakot sa akin | Hinding-hindi siya matatakot ng mga multo
Progress: 0.77
translated_text: Ang oras ay lumilipad na parang arrow | Ang oras ay tumatakbo sa ilalim niya
Progress: 0.77
translated_text: siya ay lumilipad patungong Cincinnati ngayong gabi | Nagmamaneho ba tayo o lumilipad?
Progress: 0.77
translated_text: magpalipad ng saranggola | Lahat ng mga bansa ay nagpapalipad ng kanilang mga watawat sa harap ng UN
Progress: 0.77
translated_text: nawala ang pera sa las Vegas | nag vaporize lahat ng stock assets ko
Progress: 0.77
translated_text: nanatiling huffy nang matagal | nagagalit siya kapag ginising mo siya ng napakaaga | galit sa kanyang kaibigan | masakit sa isang pangungusap
Progress: 0.77
translated_text: isang pulutong ng mga nahihibang mga tagahanga ng baseball | isang bagay na galit na galit sa kanilang kagalakan | isang baliw na ipo-ipo ng kasiyahan
Progress: 0.77
translated_text: harebrained na mga ideya | kinuha ang nakakabaliw na mga panganib sa likod ng gulong | isang ganap na baliw na pamamaraan upang bumuo ng isang tulay sa pagitan ng dalawang bundok
Progress: 0.77
translated_text: may pagkatulala ang ekspresyon ng mukha niya | humiga ng kalahating malay, natulala (o natulala) sa suntok | ay bobo dahil sa pagod
Progress: 0.77
translated_text: sandali lang | sa isang mo | ito ay tumatagal lamang ng isang minuto | sa kaunti lang
Progress: 0.77
translated_text: nakatira kami ng isang oras mula sa airport | 10 minuto lang ang layo nito
Progress: 0.77
translated_text: sa pagkakataong ito ay nagtagumpay siya | apat na beses siyang tumawag | kaya niyang gawin ang sampu sa isang clip
Progress: 0.77
translated_text: maglaan ng oras upang amoy ang mga rosas | Wala akong oras para tapusin | ito ay tumagal ng higit sa kalahati ng aking oras
Progress: 0.77
translated_text: naghintay siya ng matagal | ang oras ng taon para sa pagtatanim | isa siyang magaling na artista noong panahon niya
Progress: 0.77
translated_text: may time siyang nagpipigil ng luha | masaya silang magkasama
Progress: 0.77
translated_text: alam mo ba kung anong oras na? | ang oras ay 10 o&#39;clock
Progress: 0.77
translated_text: nagsilbi siya ng 15 buwang pagkakulong | ang kanyang sentensiya ay 5 hanggang 10 taon | siya ay gumagawa ng oras sa bilangguan ng county
Progress: 0.77
translated_text: sandali lang | sa isang mo | ito ay tumatagal lamang ng isang minuto | sa kaunti lang
Progress: 0.77
translated_text: Ipangalawa ko ang galaw na iyon | Hindi ko maibabalik ang planong ito | mag-endorso ng bagong proyekto
Progress: 0.77
translated_text: pangalawang plauta | ang pangalawang violin
Progress: 0.77
translated_text: sa ganoong mga sandali ay lagi siyang may udyok na umalis | ito ay kailangan lamang sa mga espesyal na okasyon
Progress: 0.77
translated_text: ang party ay medyo isang affair | isang okasyon na isinaayos upang parangalan ang pangulo | isang tila walang katapusang pag-ikot ng mga gawaing panlipunan
Progress: 0.77
translated_text: isang mabigat na atleta | isang maskuladong boksingero | malalakas na armas
Progress: 0.77
translated_text: Nawalan siya ng asawa sa digmaan | Ang mag-asawang gustong ampunin ang bata ay nawala sa kanya nang angkinin siya ng mga biyolohikal na magulang
Progress: 0.77
translated_text: Nawalan ako ng libu-libong dolyar sa masamang pamumuhunan na iyon! | Ang kumpanya ay naging isang pagkalugi pagkatapos ng unang taon
Progress: 0.77
translated_text: Na-miss ko ang pangungusap na iyon | She missed his point | Nawala ang bahagi ng sinabi niya
Progress: 0.77
translated_text: isang nawawalang bata | nawalan ng mga kaibigan | ang kanyang nawawalang libro | nawalan ng mga pagkakataon
Progress: 0.77
translated_text: Madalas kong makita ang aking sarili na disoriented kapag umahon ako sa subway | ang pampamanhid ay nag-iwan sa kanya ng ganap na disoriented
Progress: 0.77
translated_text: mga nawawalang kaluluwa | isang nawawalang henerasyon | isang nawawalang barko | ang nawalang platun
Progress: 0.77
translated_text: isang natalo na labanan | isang nawalang premyo
Progress: 0.77
translated_text: kasing layo at naguguluhan na gaya ng isang propesor na nakikinig sa usapan ng kanyang freshman class | nawala sa isip | isang abalang nakakunot ang noo
Progress: 0.77
translated_text: halatang naguguluhan sa mga tanong niya | nalilito at nalilito | isang maulap at nalilitong pilosopo | halong-halong bata lang | Pakiramdam niya ay nawala siya sa unang araw ng paaralan
Progress: 0.77
translated_text: isang alipin sa fashion | isang alipin ng cocaine | ang kanyang ina ay kanyang hamak na alipin
Progress: 0.77
translated_text: walang katuturang pantig | isang walang katuturang paghalu-halo ng mga salita
Progress: 0.77
translated_text: Si Mozart ay isang child genius | matalino siya pero hindi siya Einstein
Progress: 0.77
translated_text: magkaroon ng pagkakahawig | maglagay ng pirma
Progress: 0.77
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.77
translated_text: Mga regalo sa oso | pasanin ang mabigat na kargada | pasanin ang balita | nagdadala ng mga utos
Progress: 0.77
translated_text: Ang puno ng mansanas ay nagbunga ng masasarap na mansanas ngayong taon | Ang hindi kilalang halaman ay nagbunga ng napakarilag na mga bulaklak
Progress: 0.77
translated_text: Tatanggapin ko ang mga singil | Pumayag siyang pasanin ang responsibilidad
Progress: 0.77
translated_text: Ang banga ay may dalang alak | Ang canteen ay may hawak na sariwang tubig | Ito ay naglalaman ng tubig
Progress: 0.78
translated_text: mga account na may interes | Magkano ang binabayaran ng savings certificate na ito taun-taon?
Progress: 0.78
translated_text: Nakasuot siya ng pulang laso | magkaroon ng peklat
Progress: 0.78
translated_text: Dinala niya ng maayos ang sarili | dinadala niya ang kanyang sarili nang may dignidad | Maayos silang kumilos sa mga mahihirap na panahong ito
Progress: 0.78
translated_text: Taglay niya ang titulong Duchess | Hinawakan niya ang pagkagobernador ng halos isang dekada
Progress: 0.78
translated_text: Nakataas ang ulo niya | Binuhat niya ang sarili patayo

Progress: 0.78
translated_text: Ipinanganak niya ang kanyang anak | Inaasahan ng isa pang anak sa Enero | karga ko ang anak niya
Progress: 0.78
translated_text: isang likas na pinuno | isang ipinanganak na musikero | isang likas na talento
Progress: 0.78
translated_text: sila fumbled sa paligid sa ganap na kadiliman | sa dilim ng gabi
Progress: 0.78
translated_text: Pinaitim ng usok ang kisame | Umitim ang kisame
Progress: 0.78
translated_text: itim na katad na mga jacket | kasing itim ng karbon | mayamang itim na lupa
Progress: 0.78
translated_text: itim na hitsura | itim na salita
Progress: 0.78
translated_text: ang kinabukasan ay nagmukhang itim | ang mga prospect ay malungkot | Ang buhay sa Aran Islands ay palaging madilim at mahirap | kumuha ng malabong pagtingin sa mga bagay-bagay
Progress: 0.78
translated_text: itim na gawa | isang itim na kasinungalingan | ang kanyang itim na puso ay gumawa ng isa pang itim na gawa | Darth Vader ng madilim na bahagi | isang madilim na layunin | dark undercurrents ng etnikong poot | ang pakana ng ilang masasamang katalinuhan na nakabaluktot na parusahan siya
Progress: 0.78
translated_text: bumagsak ang stock market noong Black Friday | isang mapaminsalang pagkatalo | ang labanan ay isang mapaminsalang pagtatapos sa isang mapaminsalang kampanya | ang gayong mga doktrina, kung totoo, ay ganap na nakamamatay sa aking teorya | nakamamatay ang pumasok sa anumang digmaan nang walang pagnanais na manalo dito | isang nakamamatay na pagkakamali
Progress: 0.78
translated_text: isang itim na gabing walang buwan | sa pamamagitan ng napakaitim na kagubatan | ito ay napakadilim sa cellar
Progress: 0.78
translated_text: itim na katatawanan | isang mabangis na biro | mabangis na tawa | masaya mula sa slapstick clowning ... sa savage mordant wit
Progress: 0.78
translated_text: Ang tao...ay nagsulat ng isa sa kanyang pinakamaitim na mga tala bilang isang maninira sa mga isla ng karagatan | isang kahiya-hiyang pag-urong | kasuklam-suklam na pagkatalo | isang opprobrobyong monumento sa kasakiman ng tao | isang nakakahiyang pagpapakita ng kaduwagan
Progress: 0.78
translated_text: may itim na paa mula sa paglalaro sa labas | ang kanyang kamiseta ay itim sa loob ng isang oras
Progress: 0.78
translated_text: Ano ang isusuot ko ngayon? | Isinuot niya ang kanyang pinakamagandang suit para sa kasal | Ang prinsesa ay nagsuot ng mahabang asul na damit | Ipinagpalagay ng reyna ang marangal na damit | Nakasuot siya ng jeans
Progress: 0.78
translated_text: Nag-down siya ng tatlong martinis bago kumain | Nakapatay siya ng isang bote ng brandy noong gabing iyon | Uminom sila ng ilang beer pagkatapos ng trabaho
Progress: 0.78
translated_text: Pinabagsak ng pulis ang armadong suspek | Itinumba ng magnanakaw ang matandang babae matapos itong tumanggi na ibigay ang kanyang pitaka
Progress: 0.78
translated_text: humiga ang mukha | ang buwan ay pababa | ang aming koponan ay nahulog sa pamamagitan ng isang run | pababa ng isang nakasangla | bumaba ang stock market ngayon
Progress: 0.78
translated_text: ang pababang hagdanan | ang pababang daloy ng batis
Progress: 0.78
translated_text: ang merkado ay nalulumbay | bumaba ang mga presyo
Progress: 0.78
translated_text: malungkot sa kakaisip kung ano ang dapat niyang harapin | madilim na mga hula | isang madilim na katahimikan | kumuha ng mabangis na pagtingin sa ekonomiya | ang nagdidilim na kalooban | malungkot at asul sa isang kakaibang lungsod | nalulumbay sa pagkawala ng kanyang trabaho | isang dispirited at nagbitiw na ekspresyon sa kanyang mukha | nalulumbay pagkatapos ng kanyang pagkatalo | nakakaramdam ng panghihina ng loob at panghihina ng loob
Progress: 0.78
translated_text: huwag mahulog | sumakay sa elevator at nag-ski pababa | ang mga presyo ay bumagsak pababa
Progress: 0.78
translated_text: ay ipinadala upang magtrabaho sa opisina ng rehiyon | nagtrabaho sa bukid | bumaba para sa kasal | lumipad pababa sa Florida
Progress: 0.78
translated_text: bumagsak ang pabrika sa panahon ng welga | bumaba na naman ang computer
Progress: 0.78
translated_text: tumakas sa leon | gustong lumayo roon | pinaalis ang mga bata sa boarding school | kinawayan ng guro ang mga bata palayo sa patay na hayop | pumunta sa paaralan | umalis sila | humayo kayo at mangaral
Progress: 0.78
translated_text: mula sa panahong iyon | mula sa ikaanim na siglo pasulong
Progress: 0.78
translated_text: lumabas mula sa karamihan ng tao | ilagay ang aking mga ideya
Progress: 0.78
translated_text: isang nakatutuwang pakana | kalahating lutong ideya | isang panukalang screwball na walang panalangin ng pagtatrabaho
Progress: 0.78
translated_text: ang daming nagwala | ay baliw na subukan ang kanyang bagong bisikleta
Progress: 0.78
translated_text: nagkaroon ng nakakabaliw na panaginip | nagsuot ng nakakalokong sumbrero
Progress: 0.78
translated_text: baliw sa mga kotse at karera | siya ay potty tungkol sa kanya
Progress: 0.78
translated_text: Jam the Voice of America | harangan ang mga signal na inilalabas ng istasyong ito
Progress: 0.78
translated_text: isang hindi mapakali na mobile society | ang mga nomadic na gawi ng mga Bedouins | naniniwala na ang propesyon ng isang peregrine typist ay magkakaroon ng masayang kinabukasan | mga tribung gumagala
Progress: 0.78
translated_text: isang mobile missile system | ang dila ay...ang pinaka-mobile na articulator
Progress: 0.78
translated_text: Ang Britain ay hindi isang tunay na tuluy-tuloy na lipunan | pataas na mobile
Progress: 0.78
translated_text: May-ari siya ng tatlong bahay sa Florida | Ilang sasakyan ang mayroon siya?
Progress: 0.78
translated_text: para sa sarili mong gamit | gawin ang iyong sariling bagay | gumagawa siya ng sarili niyang damit | Ang `ain&#39; ay Scottish
Progress: 0.78
translated_text: ang pagkakapantay-pantay ng ina ay dapat isaalang-alang | ang bipara ay isang babaeng nagsilang ng dalawang anak
Progress: 0.78
translated_text: dapat nating itanim ang pakiramdam ng tungkulin sa ating mga anak | bawat karapatan ay nagpapahiwatig ng responsibilidad; bawat pagkakataon, isang obligasyon; bawat pag-aari, isang tungkulin
Progress: 0.78
translated_text: Naghintay ako ng ilang araw para sa kanyang sagot | sumulat siya ng mga tugon sa ilan sa kanyang mga kritiko
Progress: 0.78
translated_text: sila ay nagsisikap na makahanap ng mapayapang solusyon | ang mga sagot ay nasa likod ng libro | kinalkula niya ang resulta sa apat na decimal na lugar
Progress: 0.78
translated_text: ang sagot niya sa anumang problema ay magpakalasing | ang sagot nila ay idemanda ako
Progress: 0.78
translated_text: Ayaw niyang sumagot | sagutin ang tanong | Sumagot kami na tatanggapin namin ang imbitasyon
Progress: 0.78
translated_text: sagutin ang pinto | sagutin ang telepono
Progress: 0.78
translated_text: sagutin ang isang tanong | sagutin mo ang bugtong
Progress: 0.78
translated_text: Ang ilang mga salita ay sasagot | Ang kotseng ito ay angkop sa aking layunin | Magagawa ba ang $100? | Hindi sapat ang gradong &#39;B&#39; para makapasok ako sa medikal na paaralan | Wala nang ibang magsisilbi
Progress: 0.78
translated_text: dapat nating itanim ang pakiramdam ng tungkulin sa ating mga anak | bawat karapatan ay nagpapahiwatig ng responsibilidad; bawat pagkakataon, isang obligasyon; bawat pag-aari, isang tungkulin
Progress: 0.79
translated_text: isang bihirang salita | mga bihirang libro
Progress: 0.79
translated_text: isang bihirang hitsura | Ang kabuuang eclipses ay bihirang pangyayari
Progress: 0.79
translated_text: bihirang mga halamang gamot | bihirang mga patch ng berde sa disyerto
Progress: 0.79
translated_text: mga bihirang gas | lightheaded mula sa rarefied bundok hangin
Progress: 0.79
translated_text: kung ano ang napakabihirang bilang isang araw sa Hunyo | isang bihirang kasanayan | isang hindi karaniwang pagkamapagpatawa | siya ay mabait sa isang hindi karaniwang antas
Progress: 0.79
translated_text: Siya ay naninirahan sa Princeton | dalawang kwarto ang inokupa niya sa pinakataas na palapag
Progress: 0.79
translated_text: Tumagal ng tatlong oras bago pumasok sa trabaho ngayong umaga | Ang kaganapang ito ay inookupahan ng napakaikling panahon
Progress: 0.79
translated_text: Kinuha niya ang trabaho bilang direktor ng pag-unlad | siya ay sumasakop sa posisyon ng manager | malapit nang sakupin ng batang prinsipe ang trono

Progress: 0.79
translated_text: pinapanatili niyang abala ang kanyang oras | occupied ang wc
Progress: 0.79
translated_text: pinapanatili niya ang kanyang sarili na ganap na abala sa mga aktibidad ng boluntaryo | malalim na nakikibahagi sa pag-uusap
Progress: 0.79
translated_text: lumalabag sa mga prinsipyo ng kalayaan | itinuring na ang ganitong kasamaan ay nakakasakit laban sa lahat ng batas ng sangkatauhan
Progress: 0.79
translated_text: isang hindi magandang reputasyon | isang hindi magandang iskandalo
Progress: 0.79
translated_text: nakakasuka na amoy | nasusuka na offal | isang nakasusuklam na baho
Progress: 0.79
translated_text: Nag-aalok ang conference center ng health spa | Nag-aalok ang hotel ng mga pribadong meeting room
Progress: 0.79
translated_text: Nagboluntaryo siyang ihatid ang matandang babae sa bahay | Nag-alok akong tumulong sa mga pinggan ngunit hindi ito narinig ng babaing punong-abala
Progress: 0.79
translated_text: ipaabot ang aking pagbati | Inialay niya ang kanyang pakikiramay
Progress: 0.79
translated_text: maglagay ng magandang laban | nag-aalok ng pagtutol
Progress: 0.79
translated_text: mag-extend ng loan | Nag-aalok ang bangko ng magandang deal sa mga bagong mortgage
Progress: 0.79
translated_text: nag-pop siya ng tanong noong Linggo ng gabi | nag-propose siya ng kasal sa lalaking kilala niya sa loob lang ng dalawang buwan | Sa wakas ay nagpahayag ang matandang bachelor sa dalaga
Progress: 0.79
translated_text: ang holiday ay nagbigay sa amin ng pagkakataong bisitahin ang Washington | ngayon na ang iyong pagkakataon
Progress: 0.79
translated_text: ang holiday ay nagbigay sa amin ng pagkakataong bisitahin ang Washington | ngayon na ang iyong pagkakataon
Progress: 0.79
translated_text: nakatagpo siya ng pangkalahatang pakiramdam ng pagtutol mula sa maraming mamamayan | sa kabila ng pagsalungat ng mga pahayagan ay nagpatuloy siya
Progress: 0.79
translated_text: hindi handa ang gobyerno para sa isang paghaharap sa mga unyon | ang mga mananakop ay nakatagpo ng matinding pagsalungat
Progress: 0.79
translated_text: nakatagpo siya ng pangkalahatang pakiramdam ng pagtutol mula sa maraming mamamayan | sa kabila ng pagsalungat ng mga pahayagan ay nagpatuloy siya
Progress: 0.79
translated_text: Na-out ang gay actor last week | May naglabas ng isang ahente ng CIA
Progress: 0.79
translated_text: nakatagpo siya ng pangkalahatang pakiramdam ng pagtutol mula sa maraming mamamayan | sa kabila ng pagsalungat ng mga pahayagan ay nagpatuloy siya
Progress: 0.79
translated_text: nakatagpo siya ng pangkalahatang pakiramdam ng pagtutol mula sa maraming mamamayan | sa kabila ng pagsalungat ng mga pahayagan ay nagpatuloy siya
Progress: 0.79
translated_text: may respeto siya sa mga karibal niya | gusto niyang malaman kung ano ang ginagawa ng kompetisyon
Progress: 0.79
translated_text: isang oral na tradisyon | isang oral na kasunduan
Progress: 0.79
translated_text: kalinisan sa bibig | isang oral thermometer | isang oral na bakuna
Progress: 0.79
translated_text: ang oral cavity | ang oral mucous membrane | ang oral surface ng isang starfish
Progress: 0.79
translated_text: limitado ang kanyang social sphere | ito ay isang saradong lugar ng trabaho | wala na siya sa orbit ko
Progress: 0.79
translated_text: ang hanay ng isang supersonic jet | ang isang piano ay may mas malawak na saklaw kaysa sa boses ng tao | ang layunin ng batas sa munisipyo | sa loob ng compass ng artikulong ito | sa loob ng saklaw ng isang pagsisiyasat | hindi maaabot ng batas | sa pampulitikang orbit ng isang kapangyarihang pandaigdig
Progress: 0.79
translated_text: Umiikot ang buwan sa paligid ng Earth | Ang mga planeta ay umiikot sa araw | Ang mga electron ay umiikot sa nucleus
Progress: 0.79
translated_text: ito ay nasa order ng isang milya | isang pagsabog ng mababang pagkakasunud-sunod ng magnitude
Progress: 0.79
translated_text: order pinasiyahan sa mga lansangan | batas at kaayusan
Progress: 0.79
translated_text: inayos niya ang kanyang desk | gumagana na ngayon ang makina
Progress: 0.79
translated_text: sumali siya sa isang golf club | bumuo sila ng isang maliit na lunch society | ang mga lalaking mula sa fraternal order ay magtatrabaho sa soup kitchen ngayon
Progress: 0.79
translated_text: Binigay ko sa waiter ang order ko | In demand ang mga produkto ng kumpanya kaya mas marami silang order kaysa kaya ng kanilang call center
Progress: 0.79
translated_text: sabi ko sakanya umuwi na | Inutusan niya siyang mag-shopping | Sinabihan ng ina ang bata na magbihis
Progress: 0.79
translated_text: Order ako ng ilang bulaklak | mag-utos ng pagtigil sa trabaho
Progress: 0.79
translated_text: Hindi namin makokontrol ang paraan ng pananamit ng mga tao | Mahilig mag-regulate ang bayang ito
Progress: 0.79
translated_text: ayusin ang aking iskedyul | itakda ang buhay ng isang tao | Inilagay ko ang mga alaalang ito sa mga nakaraan
Progress: 0.79
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.79
translated_text: ordinaryong pang-araw-araw na bagay | ordinaryong kagandahang-asal | isang ordinaryong araw | isang ordinaryong alak
Progress: 0.79
translated_text: karaniwang tao | ang ordinaryong (o karaniwang) tao sa lansangan
Progress: 0.79
translated_text: nabubuo ang mga grupong panlipunan sa lahat ng dako | Nagbuo sila ng isang kumpanya
Progress: 0.79
translated_text: gumawa ng isang balangkas | ayusin ang isang strike | gumawa ng isang plano upang kunin ang opisina ng direktor
Progress: 0.79
translated_text: kung gaano siya kaorganisado | halos masyadong organisado ang kanyang buhay
Progress: 0.79
translated_text: organisadong paggawa | mga manggagawang unyon | isang unionized shop
Progress: 0.80
translated_text: binago niya ang pagkakaayos ng mga paksa | ang mga katotohanan ay pamilyar ngunit ito ay sa organisasyon ng mga ito na siya ay orihinal | sinubukan niyang unawain ang kanilang sistema ng pag-uuri
Progress: 0.80
translated_text: sinasabi niyang corrupt ang kasalukuyang administrasyon | ang pamamahala ng isang asosasyon ay may pananagutan sa mga miyembro nito | mabilis siyang nakilala bilang miyembro ng establisyimento
Progress: 0.80
translated_text: ang kanyang mapilit na organisasyon ay hindi isang kaibig-ibig na kalidad | hindi natin ito magagawa maliban kung magtatag tayo ng ilang sistema dito
Progress: 0.80
translated_text: ang konstitusyon ng isang PTA group noong nakaraang taon | ito ay ang pagtatatag ng kanyang reputasyon | naaalala pa niya ang organisasyon ng club
Progress: 0.80
translated_text: binago niya ang pagkakaayos ng mga paksa | ang mga katotohanan ay pamilyar ngunit ito ay sa organisasyon ng mga ito na siya ay orihinal | sinubukan niyang unawain ang kanilang sistema ng pag-uuri
Progress: 0.80
translated_text: sinasabi niyang corrupt ang kasalukuyang administrasyon | ang pamamahala ng isang asosasyon ay may pananagutan sa mga miyembro nito | mabilis siyang nakilala bilang miyembro ng establisyimento
Progress: 0.80
translated_text: ang kanyang mapilit na organisasyon ay hindi isang kaibig-ibig na kalidad | hindi natin ito magagawa maliban kung magtatag tayo ng ilang sistema dito
Progress: 0.80
translated_text: ang konstitusyon ng isang PTA group noong nakaraang taon | ito ay ang pagtatatag ng kanyang reputasyon | naaalala pa niya ang organisasyon ng club
Progress: 0.80
translated_text: ang orihinal na mga naninirahan sa Americas | ang aklat ay mayroon pa ring orihinal na pagkakatali | naibalik ang bahay sa orihinal nitong kondisyon | ang orihinal na pagganap ng opera | ang orihinal na cast | binawi ang kanyang orihinal na pahayag
Progress: 0.80
translated_text: isang tunay na orihinal na diskarte | na may orihinal na musika | isang orihinal na kaisipan
Progress: 0.80
translated_text: orihinal ang dula; hindi isang adaptasyon | iningatan niya ang orihinal na kopya at binigyan lamang siya ng isang xerox | ang pagsasalin ay nakaligtaan ang karamihan sa kapitaganan ng orihinal na Pranses
Progress: 0.80
translated_text: ang impiyerno ay walang poot na gaya ng babaeng hinamak | namula ang mukha niya sa galit
Progress: 0.80
translated_text: sinusubukang magmaneho sa isang blizzard ay ang taas ng kahangalan | Ang pag-aayos sa isang nakakabaliw na lipunan ay ganap na kahangalan

Progress: 0.80
translated_text: ekstremistang pananaw sa pulitika | mga radikal na opinyon sa edukasyon | isang ultra konserbatibo
Progress: 0.80
translated_text: isang rebolusyonaryong pagtuklas | radikal na pananaw sa pulitika
Progress: 0.80
translated_text: basal placentation | mga radikal na dahon
Progress: 0.80
translated_text: bulong niya ng isang spell habang ginagalaw niya ang kanyang mga kamay | na nakasulat sa paligid ng base nito ay isang alindog sa Balinese
Progress: 0.80
translated_text: Buong gabing nagsaya ang mga miyembro ng wedding party | Let&#39;s whoop it up--wala na ang amo!
Progress: 0.80
translated_text: Buong gabing nagsaya ang mga miyembro ng wedding party | Let&#39;s whoop it up--wala na ang amo!
Progress: 0.80
translated_text: ang welga ay suportado ng ranggo at file ng unyon | tumaas siya mula sa hanay upang maging koronel
Progress: 0.80
translated_text: poll nila ang kanilang membership | natagpuan nila ang hindi pagkakaunawaan sa kanilang sariling hanay | sumapi siya sa hanay ng mga walang trabaho
Progress: 0.80
translated_text: paano mo iraranggo ang mga estudyanteng ito? | Mataas ang rating ng restaurant sa food guide
Progress: 0.80
translated_text: isang umiiyak na kahihiyan | isang matinding kasinungalingan | lantarang paglabag sa karapatang pantao | isang nakasisilaw na error | matinding kawalan ng kakayahan | matinding kawalan ng katarungan | pagtataksil sa ranggo
Progress: 0.80
translated_text: ganap na kalayaan | isang ganap na dimwit | isang ganap na kasinungalingan | out-and-out na labanan | isang out-and-out na kasinungalingan | isang ranggo na tagalabas | maraming right-down na bisyo | nakuha ang trabaho sa pamamagitan ng matinding pagtitiyaga | puro katangahan
Progress: 0.80
translated_text: siya ay nagkaroon ng katayuan ng isang menor de edad | ang nobela ay nakamit ang katayuan ng isang klasikong | Ang mga ateista ay hindi nagtatamasa ng isang paborableng posisyon sa buhay ng mga Amerikano
Progress: 0.80
translated_text: isang kondisyon (o estado) ng pagkasira | ang kasalukuyang katayuan ng negosasyon sa armas
Progress: 0.80
translated_text: masamang reaksyon sa gamot | ang kanyang mga tugon ay bumagal sa edad
Progress: 0.80
translated_text: natuwa siya sa naging reaksyon ng audience sa kanyang performance | Natakot si John sa reaksyon ng kanyang ina nang makita ang sirang lampara
Progress: 0.80
translated_text: nawasak ang kanyang mundo | nabubuhay tayo sa magkaibang mundo | para sa kanila ang mga demonyo ay bahagi ng realidad gaya ng mga puno
Progress: 0.80
translated_text: bawat henerasyon ay dapat magkaroon ng sariling rebelyon | ang kanyang katawan ay nagrerebelde laban sa pagod
Progress: 0.80
translated_text: tatlong pag-ikot ang ginawa ng eroplano bago ito bumagsak | ang rebolusyon ng mundo tungkol sa araw ay tumatagal ng isang taon
Progress: 0.80
translated_text: bawat henerasyon ay dapat magkaroon ng sariling rebelyon | ang kanyang katawan ay nagrerebelde laban sa pagod
Progress: 0.80
translated_text: isang rebolusyonaryong pagtuklas | radikal na pananaw sa pulitika
Progress: 0.80
translated_text: mga rebolusyonaryong digmaan | ang panahon ng Rebolusyonaryo
Progress: 0.80
translated_text: rebolusyonaryong polyeto | isang rebolusyonaryong junta
Progress: 0.80
translated_text: ang pagbabago ay nilayon upang mapataas ang mga benta | ang bagyong ito ay tiyak na isang pagbabago para sa mas masahol pa | ang kapitbahayan ay sumailalim sa ilang mga pagbabago mula noong huling pagbisita niya mga taon na ang nakakaraan
Progress: 0.80
translated_text: ang pagbabago ng pamahalaan ay walang epekto sa ekonomiya | ang kanyang pagbabago sa aborsyon ay nagdulot sa kanya ng halalan
Progress: 0.80
translated_text: may mga markadong pagbabago sa lining ng baga | walang pagbabago sa mga bundok
Progress: 0.80
translated_text: pumunta siya sa France para sa variety | ito ay isang nakakapreskong pagbabago upang makilala ang isang babaeng mekaniko
Progress: 0.80
translated_text: Maaaring binago ng pagdating ng sasakyan ang pattern ng paglago ng lungsod | Binago ng talakayan ang aking pag-iisip tungkol sa isyu
Progress: 0.80
translated_text: Siya ay ganap na nagbago habang siya ay tumanda | Nagbago ang panahon kagabi
Progress: 0.80
translated_text: nagbabago ang kanyang kalooban alinsunod sa panahon | Ang pagpili ng mga gulay sa supermarket ay nag-iiba ayon sa panahon
Progress: 0.80
translated_text: lumipat sa ibang brand ng beer | Nagpalit siya ng mga psychiatrist | Nagpalit ng lane ang sasakyan
Progress: 0.80
translated_text: Maaari mo bang i-convert ang aking mga dolyar sa pounds? | Binago niya ang kanyang pangalan | i-convert ang sentimetro sa pulgada | i-convert ang mga hawak sa pagbabahagi
Progress: 0.80
translated_text: Papalitan mo ba ako ng pwesto? | Isang taon na kaming nagpapalitan ng sulat
Progress: 0.80
translated_text: Nagsimulang magbago ang kanyang boses noong siya ay 12 taong gulang | Lumalim ang boses niya nang ibulong niya ang password
Progress: 0.80
translated_text: Kailangang matutunan ni Itay kung paano baguhin ang sanggol | Pagkatapos ng bawat bisita ay pinalitan namin ang mga bed linen
Progress: 0.80
translated_text: naging panuntunan niya na mamasyal bago mag-almusal | maikling gupit ang naging regulasyon
Progress: 0.80
translated_text: file para sa diborsiyo | magsampa ng reklamo
Progress: 0.80
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;
Progress: 0.81
translated_text: Ang talaan ay ginawa ng `nakarehistrong mail&#39; sa bawat punto sa ruta nito upang matiyak ang ligtas na paghahatid | mga rehistradong bono
Progress: 0.81
translated_text: file para sa diborsiyo | magsampa ng reklamo
Progress: 0.81
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;
Progress: 0.81
translated_text: file para sa diborsiyo | magsampa ng reklamo
Progress: 0.81
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;
Progress: 0.81
translated_text: ang mga rehiyon ng pagsasaka ng France | relihiyon sa lahat ng bahagi ng mundo | mga rehiyon ng kalawakan
Progress: 0.81
translated_text: ito ay aabutin sa rehiyon ng dalawa o tatlong buwan upang matapos ang trabaho | ang presyo ay nasa paligid ng $100
Progress: 0.81
translated_text: ito ay isang limitadong larangan ng diskurso | dito tayo pumasok sa rehiyon ng opinyon | ang kaharian ng okultismo
Progress: 0.81
translated_text: selos ay isang bahagi ng kanyang karakter | dalawang bumubuo ng isang komposisyong musikal ay melody at harmony | ang mga elemento ng gramatika ng isang pangungusap | isang pangunahing salik sa kanyang tagumpay | katatawanan: isang mabisang sangkap ng isang talumpati
Progress: 0.81
translated_text: ang kanyang kaaya-ayang personalidad ay isang rekomendasyon na | ang kanyang kayamanan ay hindi isang pasaporte sa mga eksklusibong bilog ng lipunan
Progress: 0.81
translated_text: hindi siya nakatanggap ng pormal na edukasyon | ang aming pagtuturo ay maingat na na-program | ang mahusay na pagtuturo sa silid-aralan ay bihirang gantimpalaan
Progress: 0.81
translated_text: naghanda siya sa pagtuturo habang nasa kolehiyo pa | ang pedagogy ay kinikilala bilang isang mahalagang propesyon
Progress: 0.81
translated_text: may magandang record ang abogado | ang track record ay nagpapakita na siya ay magiging isang mabuting pangulo
Progress: 0.81
translated_text: Sinabi ni Al Smith dati, `Tingnan natin ang rekord&#39; | nasa lahat ng record books ang pangalan niya
Progress: 0.81
translated_text: tinabla niya ang Olympic record | sinira ng produksyon ng kape noong nakaraang taon ang lahat ng naunang rekord | Itinakda ng Chicago ang rekord ng homicide
Progress: 0.81
translated_text: pinasiyahan niya na ang criminal record ng nasasakdal ay hindi maaaring ibunyag sa korte | ang puta ay may rekord na isang milya ang haba
Progress: 0.81
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;
Progress: 0.81
translated_text: Ang iskulturang ito ay ginugunita ang mga biktima ng mga kampong konsentrasyon | Inaalaala namin ang mga Patay

Progress: 0.81
translated_text: naghinang siya ng koneksyon | wala siyang tamang connector sa pagitan ng amplifier at ng mga speaker
Progress: 0.81
translated_text: ang pagsasanib ng mga kamay sa palibot ng mesa | nagkaroon ng koneksyon sa pamamagitan ng internet
Progress: 0.81
translated_text: pinalaki siya sa relihiyong Baptist | isang miyembro ng kanyang sariling pananampalataya ang sumalungat sa kanya
Progress: 0.81
translated_text: lunasan ang mga pagkukulang na ito | iwasto ang hindi pagkakapantay-pantay sa mga suweldo | ayusin ang isang oversight
Progress: 0.81
translated_text: Binago ako ng Simbahan | baguhin ang iyong pag-uugali
Progress: 0.81
translated_text: Nangako ang tamad na estudyante na magreporma | ang nakagawiang manloloko sa wakas ay nakakita ng liwanag
Progress: 0.81
translated_text: Itatalaga ko ang perang ito para sa iyong pananaliksik | Naglalaan siya ng oras para sa pagmumuni-muni araw-araw
Progress: 0.81
translated_text: magpareserba sa akin ng upuan sa isang flight | Nag-book ang ahente ng mga tiket sa palabas para sa buong pamilya | mangyaring humawak ng mesa sa Maxim&#39;s
Progress: 0.81
translated_text: dinala siya ng kanyang katatagan sa labanan | ito ang kanyang hindi matitinag na resolusyon na tapusin ang gawain
Progress: 0.81
translated_text: sa wakas ay nakarating sila sa isang kasunduan sa unyon | hindi nila kailanman nakamit ang isang pangwakas na resolusyon ng kanilang mga pagkakaiba | kailangan niyang magdalamhati bago niya makamit ang pakiramdam ng pagsasara
Progress: 0.81
translated_text: sila ay nagsisikap na makahanap ng mapayapang solusyon | ang mga sagot ay nasa likod ng libro | kinalkula niya ang resulta sa apat na decimal na lugar
Progress: 0.81
translated_text: Na-miss ko ang pangungusap na iyon | She missed his point | Nawala ang bahagi ng sinabi niya
Progress: 0.81
translated_text: Na-miss ko ang concert | Isang linggo siyang hindi pumapasok sa paaralan
Progress: 0.81
translated_text: Paano ko makaligtaan ang typo na iyon? | Ang mga manggagawa sa conveyor belt ay nakakaligtaan ng isa sa sampu
Progress: 0.81
translated_text: Kulang sa asin ang sopas na ito | May kulang sa jewelry box ko!
Progress: 0.81
translated_text: missing in action | isang nawawalang tao
Progress: 0.81
translated_text: wala ang hinlalaki | kulang ang gana niya
Progress: 0.81
translated_text: ang kanilang mga pagsisikap ay kaawa-awa | kaawa-awang kawalan ng karakter | nakakaawa na pagpapakita ng kaduwagan
Progress: 0.81
translated_text: ang aking pananalapi ay nasa isang kaawa-awang kalagayan | isang malungkot na desisyon | ang kanyang damit ay nasa malungkot na anyo | isang malungkot na estado ng mga pangyayari
Progress: 0.81
translated_text: isang kaawa-awang biktima | miserableng biktima ng digmaan | ang sira-sira na silid ay tumama sa kanya bilang extraordinarily pathetic | kaawa-awang apela para sa tulong | kaawa-awang mga batang palaboy | isang kaawa-awang kapalaran | Oh, kawawa ka | ang kanyang kaawa-awang baluktot na mga paa | isang kahabag-habag na buhay
Progress: 0.81
translated_text: nagkaroon siya ng pakiramdam ng euphoria | siya ay nagkaroon ng kahila-hilakbot na damdamin ng pagkakasala | Hindi ko siya nagustuhan at mutual ang pakiramdam
Progress: 0.81
translated_text: ang kanyang impression sa kanya ay kanais-nais | ano ang iyong damdamin tungkol sa krisis? | pinatibay nito ang aking paniniwala sa kanyang katapatan | Naramdaman kong nagsisinungaling siya
Progress: 0.81
translated_text: ang pakiramdam ng lungsod ay nasasabik sa kanya | pinagbuti ng isang klerigo ang tono ng pulong | ito ay may amoy ng pagtataksil
Progress: 0.81
translated_text: nagkaroon siya ng malabong pakiramdam | May kakaiba akong naramdaman sa binti ko | nawala lahat ng nararamdaman niya sa braso niya
Progress: 0.81
translated_text: gusto niya ang dampi ng seda sa kanyang balat | ang ibabaw ay nagkaroon ng mamantika na pakiramdam
Progress: 0.81
translated_text: Nakaramdam siya ng sama ng loob | Nakaramdam siya ng panghihinayang
Progress: 0.81
translated_text: Feeling ko hindi niya ako gusto | I find him to be obnoxious | Nakita kong medyo nakakaaliw ang pelikula
Progress: 0.81
translated_text: Naramdaman niya ang hangin | Naramdaman niya ang isang bagay na humahaplos sa kanyang braso | Naramdaman niyang gumapang ang kanyang laman | Naramdaman niya ang init nang bumaba siya ng sasakyan
Progress: 0.81
translated_text: Nawala na ang sipon ko--ayos na ang pakiramdam ko ngayon | Nakaramdam siya ng pagod pagkatapos ng mahabang paglalakad | Nalungkot siya pagkatapos ng pagkawala niya
Progress: 0.81
translated_text: Pakiramdam niya ay maliit at hindi gaanong mahalaga | Pinaparamdam mo sa akin na nakahubad | Naiiba ko ang pakiramdam ng mga estudyante sa kanilang sarili
Progress: 0.81
translated_text: Naramdaman namin ang epekto ng inflation | dinama ng kanyang mga daliri ang string quartet | naramdaman niya ang paghamak nito sa kanya
Progress: 0.81
translated_text: Nanginginig ang lupa | Ang mga kumot ay malambot
Progress: 0.82
translated_text: Pakiramdam ang malambot na tela na ito! | Pininger ng customer ang sweater
Progress: 0.82
translated_text: Dinampot ng nurse ang tiyan ng pasyente | Naramdaman ng runner ang kanyang pulso
Progress: 0.82
translated_text: ang pakiramdam ng lungsod ay nasasabik sa kanya | pinagbuti ng isang klerigo ang tono ng pulong | ito ay may amoy ng pagtataksil
Progress: 0.82
translated_text: ang kanyang emosyonal na estado ay nakasalalay sa kanyang opinyon | siya ay nasa mabuting kalooban | bumangon ang kanyang diwa
Progress: 0.82
translated_text: wala siyang dahilan para magreklamo | may magandang dahilan sila para magsaya
Progress: 0.82
translated_text: sinuportahan niya ang mga populistang kampanya | nagtrabaho sila sa layunin ng kapayapaan sa mundo | ang koponan ay handa na para sa isang biyahe patungo sa pennant | ang kilusan upang wakasan ang pang-aalipin | nag-ambag sa pagsisikap sa digmaan
Progress: 0.82
translated_text: magdulot ng kaguluhan | gumawa ng paghalo | magdulot ng aksidente
Progress: 0.82
translated_text: Ang mga ad ay nag-udyok sa akin na bumili ng VCR | Sa wakas nakuha ako ng aking mga anak na bumili ng computer | Pinabili ako ng asawa ko ng bagong sofa
Progress: 0.82
translated_text: manipis na alambre | isang manipis na chiffon blouse | isang manipis na libro | isang manipis na layer ng pintura
Progress: 0.82
translated_text: hindi ka maaaring maging masyadong mayaman o masyadong payat | Si Yon Cassius ay may payat at gutom na hitsura
Progress: 0.82
translated_text: isang manipis na balbas | kalat-kalat ang mga puno
Progress: 0.82
translated_text: manipis ang hangin sa matataas na lugar | isang manipis na sabaw | ang skimmed milk ay mas payat kaysa buong gatas | manipis na mantika
Progress: 0.82
translated_text: kaunting ebidensya | isang mahinang argumento | isang manipis na balangkas
Progress: 0.82
translated_text: matabang pagkain | matabang tissue
Progress: 0.82
translated_text: isang makatas na kontrata | isang magandang matabang trabaho
Progress: 0.82
translated_text: matabang lupang sakahan | isang matabang lupain | isang produktibong ubasan | mayamang lupa
Progress: 0.82
translated_text: isang buong baso | isang langit na puno ng mga bituin | isang buong buhay | punong-puno hanggang umaapaw ang auditorium
Progress: 0.82
translated_text: isang buong bayan na nasalanta ng lindol | nagbigay ng buong atensyon | isang kabuuang kabiguan
Progress: 0.82
translated_text: isang buong laro | isang kabuuang eclipse | isang kabuuang sakuna
Progress: 0.82
translated_text: buong tono | isang buong boses
Progress: 0.82
translated_text: nagbibigay ng buong sukat | nagbibigay ng magandang sukat | isang magandang milya mula dito
Progress: 0.82
translated_text: malawak na liwanag ng araw | buong tag-araw
Progress: 0.82
translated_text: ang kasalukuyang lasa para sa malawak na pantalon | isang buong palda
Progress: 0.82
translated_text: ganap na lumaki | hindi niya lubos na naintindihan | alam ng husto | nasa hustong gulang na | ganap na
Progress: 0.82
translated_text: sa puso mo alam mong totoo | ang kanyang kuwento ay matutunaw ang iyong dibdib
Progress: 0.82
translated_text: siya ay patuloy na lumalaban sa purong spunk | wala kang puso para sa baseball

Progress: 0.82
translated_text: ito ay nasa gitna ng bayan | tumakbo sila pasulong sa puso ng pakikibaka | sila ay nasa mata ng bagyo
Progress: 0.82
translated_text: ang diwa ng argumento ng tagausig | ang puso at kaluluwa ng Republican Party | ang kulit ng kwento
Progress: 0.82
translated_text: nahirapan siyang ipahayag ang pagmamahal na naramdaman | nanalo ang bata sa puso ng lahat | the warmness of his welcome made us feel at home
Progress: 0.82
translated_text: pinamunuan niya ang reyna ng mga puso | puso ay trumps
Progress: 0.82
translated_text: isang ulan ng bala | isang pagbabato ng mga insulto
Progress: 0.82
translated_text: huwag kang gagawa para sa iyo ng anumang larawang inanyuan | pera ang kanyang diyos
Progress: 0.82
translated_text: ang goalie ay gumawa ng napakatalino na save | ang relief pitcher ay nakakuha ng kredito para sa isang save
Progress: 0.82
translated_text: Makakatipid ito ng pera | Ililigtas kita sa gulo | Makakatipid ito ng maraming oras
Progress: 0.82
translated_text: Makakatipid ng pera ang hakbang na ito | Ang mga hindi pinalad ay kailangang magtipid ngayon
Progress: 0.82
translated_text: panatilihin ang aking trabaho para sa akin habang ako ay nanganganak | panatilihin ang aking upuan, mangyaring | panatilihing bukas ang posibilidad ng isang pagsasanib
Progress: 0.82
translated_text: magtipon ng ilang mga bato | pagsamahin ang iyong mga iniisip
Progress: 0.82
translated_text: Nagtipon kami sa basement ng simbahan | Magtipon tayo sa dining room
Progress: 0.82
translated_text: Ang mga journal ay nag-iipon sa aking opisina | Ang trabaho ay patuloy na tumatambak
Progress: 0.82
translated_text: tipunin ang iyong mga kasamahan | pagsama-samahin ang lahat ng mga interesado sa proyekto | tipunin ang malalapit na miyembro ng pamilya
Progress: 0.82
translated_text: ang kilusang pangkapayapaan ay nakakuha ng momentum | ang kotse ay nagtitipon ng bilis
Progress: 0.82
translated_text: Gumawa siya ng tula | Nagsulat siya ng apat na nobela
Progress: 0.82
translated_text: Ilang aklat ang isinulat ni Georges Simenon? | Nag-publish siya ng 25 mga libro sa kanyang mahabang karera
Progress: 0.82
translated_text: Ang pintor ay nagsulat ng mga Chinese character sa isang malaking piraso ng puting papel | Ang Ruso ay nakasulat gamit ang alpabetong Cyrillic
Progress: 0.82
translated_text: Itinago ng mga babaeng Muslim ang kanilang mga mukha | itago ang pera
Progress: 0.82
translated_text: Malamang malapit ang kanyang kabayo sa kanyang pinagtataguan | Siya ay nagtatago sa isang cabin sa Montana
Progress: 0.82
translated_text: isang nakatagong mensahe | isang nakatalukbong pagbabanta
Progress: 0.82
translated_text: ito ay isang mahabang martsa | narinig namin ang tunog ng martsa
Progress: 0.82
translated_text: ang martsa ng agham | ang martsa ng oras
Progress: 0.82
translated_text: Nagmartsa siya papunta sa silid-aralan at ibinalita ang pagsusulit | Nagmartsa ang mga sundalo sa hangganan
Progress: 0.83
translated_text: Ang Canada ay katabi ng US | Nagmartsa ang England kasama ang Scotland
Progress: 0.83
translated_text: iguhit ang balangkas ng aklat | balangkasin ang kanyang mga ideya
Progress: 0.83
translated_text: pinaghahanap ng pulisya ang mga kamag-anak ng namatay | siya ay may malayong relasyon pabalik sa New Jersey
Progress: 0.83
translated_text: ang parusa ay dapat na proporsyonal sa krimen | kita na may kaugnayan sa produksyon
Progress: 0.83
translated_text: dila ng apoy na dinilaan ang mga dingding | ang mga riple ay sumabog ng mabilis na mga kutsilyo ng apoy sa dilim
Progress: 0.83
translated_text: kirot ng panghihinayang | nakaramdam siya ng saksak ng pananabik | twing of conscience
Progress: 0.83
translated_text: ibinigay niya ang kanyang pinakamahusay na pagbaril | kumuha siya ng saksak sa pagtataya
Progress: 0.83
translated_text: isang piraso ng pie | isang hiwa ng tinapay
Progress: 0.83
translated_text: nagsusulat siya ng mga libro para sa mga bata | mga bata pa lang sila | Ang `tiddler&#39; ay isang British na termino para sa youngster
Progress: 0.83
translated_text: nagkaroon sila ng tatlong anak | naipag-aral nila ang kanilang mga anak sa kolehiyo
Progress: 0.83
translated_text: nanatili siyang bata sa mga praktikal na bagay habang siya ay nabubuhay | tumigil ka sa pagiging baby!
Progress: 0.83
translated_text: buhay panlipunan | buhay lungsod | totoong buhay
Progress: 0.83
translated_text: umasa siya ng bagong buhay sa Australia | gusto niyang mamuhay ng sarili niyang buhay nang walang panghihimasok ng iba
Progress: 0.83
translated_text: habang may buhay may pag-asa | ang buhay ay nakasalalay sa maraming kemikal at pisikal na proseso
Progress: 0.83
translated_text: ang baterya ay nagkaroon ng maikling buhay | nabuhay siya ng mahaba at masayang buhay
Progress: 0.83
translated_text: Kailangan kong magsalin kapag bumisita sa US ang aking mga in-law mula sa Austria | Maaari mo bang bigyang kahulugan ang talumpati ng mga dumadalaw na dignitaryo? | Isinalin niya sa Ingles ang tula ng Pranses | Nagsasalin siya para sa UN
Progress: 0.83
translated_text: Naiintindihan niya ang French | Marunong ka bang magbasa ng Greek?
Progress: 0.83
translated_text: madalas na hindi isinasalin ng tula | Ang mga nobela ni Tolstoy ay mahusay na isinalin sa Ingles
Progress: 0.83
translated_text: Maaari mo bang isalin ang mga tagubilin sa manwal na ito para sa isang karaniwang tao? | Kailangan bang isalin ang mga pahayag ng psychiatrist?
Progress: 0.83
translated_text: isang pinagsamang sesyon ng Kongreso | magkasanib na mga may-ari
Progress: 0.83
translated_text: joint income-tax return | magkasanib na pagmamay-ari
Progress: 0.83
translated_text: ang stopping point ng bawat round ay sinenyasan ng bell | ang merkado ay hanggang sa matapos | mas mahusay silang naglalaro sa pagtatapos ng season
Progress: 0.83
translated_text: Isara ang pinto | isara ang bintana
Progress: 0.83
translated_text: Nagpasya ang mga may-ari na lumipat at isara ang pabrika | Nagsasara ang negosyo ko tuwing 8 PM | isara ang tindahan
Progress: 0.83
translated_text: Nagsara kami sa bahay noong Biyernes | Isinara nila ang deal sa gusali
Progress: 0.83
translated_text: Ang stock market ay nagsara ng mataas nitong Biyernes | Ang aking mga bagong stock ay nagsara sa $59 kagabi
Progress: 0.83
translated_text: isara ang circuit | magsara ng sugat | isara ang isang libro | isara ang isang payong
Progress: 0.83
translated_text: malapit na magtanghali | gaano tayo kalapit sa bayan? | isang malapit na pagbuo ng mga barko
Progress: 0.83
translated_text: isang malapit na pamilya | tayong lahat...sa malapit na pakikiramay kay... | malapit na kamag-anak | isang malapit na pagkakahawig
Progress: 0.83
translated_text: malapit sa mga kapitbahay | sa malapit na hinaharap | sila ay malapit sa katumbas | ang kanyang pinakamalapit na diskarte sa tagumpay | isang napakalapit na bagay | isang malapit na tamaan ng bomba | siya ay malapit sa luha | siya ay malapit sa luha | nagkaroon ng malapit na tawag
Progress: 0.83
translated_text: malapit na pangangasiwa | binigyang pansin | isang malapit na pag-aaral | nanatiling mahigpit na pagbabantay sa mga paggasta
Progress: 0.83
translated_text: isang malapit na pagsasalin | isang tapat na kopya ng larawan | isang matapat na paglalahad ng mga naobserbahang katotohanan
Progress: 0.83
translated_text: isang malapit na paligsahan | isang malapit na halalan | isang mahigpit na laro
Progress: 0.83
translated_text: isang maalikabok na walang hangin na attic | ang kakila-kilabot na malapit na kapaligiran | mainit at masikip at ang hangin ay asul na may usok
Progress: 0.83
translated_text: isang malapit na habi | makinis na percale na may napakahigpit na paghabi
Progress: 0.83
translated_text: aming cheeseparing administration | napakalapit (o malapit) sa kanyang pera | isang peni-pinching kuripot matanda
Progress: 0.83
translated_text: habang papalapit ang araw ng kasal | nakatayo malapit sa pinto | huwag barilin hangga&#39;t hindi sila lumalapit | papalapit sa totoong paliwanag | laging malapit ang kanyang ina | Malapit na ang wakas | hindi nakalapit ang bala | huwag masyadong lumapit sa apoy
Progress: 0.83
translated_text: Siya ay nangangati upang simulan ang proyekto | Siya ay spoiling para sa isang away

Progress: 0.83
translated_text: Tawagan ang pakikipag-ugnayan | kanselahin ang dinner party | kailangan naming i-scrub ang aming mga plano sa bakasyon | scratch that meeting--may sakit ang upuan
Progress: 0.83
translated_text: Mangyaring hampasin ang pangungusap na ito mula sa talaan | scratch that remark
Progress: 0.83
translated_text: Siya ay nagkamot ng sapat na pera para sa kolehiyo | nagkamot sila ng kakarampot na pamumuhay
Progress: 0.83
translated_text: mag-ukit ng panulat | inukit ang trophy cupt ng panalo | nagkamot ang magkasintahan sa balat ng puno
Progress: 0.83
translated_text: Nakakuha siya ng maraming painting mula sa kanyang tiyuhin | Nakakuha sila ng bagong alagang hayop | Kunin ang iyong mga resulta sa susunod na araw | Kumuha ng pahintulot na magpahinga ng ilang araw sa trabaho
Progress: 0.83
translated_text: Nainis siya nang marinig ang masamang balita | Dapat itong maging mas seryoso | namula ang mukha niya sa galit | Napunta siya sa ecstasy | Umalis ka na!
Progress: 0.83
translated_text: Nakuha niya ang kanyang squad sa bola | Pinapasok ako nito para sa isang malaking sorpresa | May dinadala siyang babae sa gulo
Progress: 0.83
translated_text: Ang mga aspetong ito ng sibilisasyon ay hindi nakakahanap ng pagpapahayag o tumatanggap ng interpretasyon | Nakatanggap ng magandang review ang kanyang pelikula | Wala akong nakuha kundi gulo para sa aking mabuting hangarin
Progress: 0.83
translated_text: Umuwi siya ng 7:00 | Hindi siya nakarating sa Chicago hanggang pagkatapos ng hatinggabi
Progress: 0.83
translated_text: Kunin mo sa akin ang mga aklat na iyon, pakiusap | Maaari mo bang dalhin ang alak? | Kinuha ng aso ang sumbrero
Progress: 0.83
translated_text: makakuha ng ideya | makaranas ng vertigo | nasusuka | tumanggap ng mga pinsala | magkaroon ng pakiramdam
Progress: 0.83
translated_text: Makukuha natin sila! | Maaayos siya niyan! | This time nakuha ko na siya
Progress: 0.83
translated_text: Si Nicklaus ay nagkaroon ng 70 | Nakakuha ang koponan ng Brazil ng 4 na layunin | Gumawa siya ng 29 puntos sa araw na iyon
Progress: 0.84
translated_text: Ang mga ad ay nag-udyok sa akin na bumili ng VCR | Sa wakas nakuha ako ng aking mga anak na bumili ng computer | Pinabili ako ng asawa ko ng bagong sofa
Progress: 0.84
translated_text: Sa wakas nakuha na namin ang suspek | Nahuli mo ba ang magnanakaw?
Progress: 0.84
translated_text: Nagpatubo siya ng balbas | Ang pasyente ay nagkaroon ng pananakit ng tiyan | Nagkaroon ako ng mga nakakatawang spot sa buong katawan ko | Mahusay na nabuo na mga suso
Progress: 0.84
translated_text: Nagkaroon siya ng AIDS | Siya ay nagkaroon ng pneumonia | Nanlamig siya
Progress: 0.84
translated_text: Tinawagan ni Bill ang numerong ito at nakuha niya si Mary | Hindi nakuha ng operator si Kobe dahil sa lindol
Progress: 0.84
translated_text: magalit sa isang tao | Ginawa niya kaming tanga | Nagpakatanga siya sa pulong | Huwag itong gawing big deal | Ang imbensyon na ito ay gagawin kang milyonaryo | Linawin mo ang sarili mo
Progress: 0.84
translated_text: nahuli mo ba ang parunggit na iyon? | Nahuli namin ang isang bagay ng kanyang teorya sa panayam | hindi mahuli ang iyong kahulugan | nakuha mo ba? | Hindi niya nakuha ang biro | Hindi ko lang siya gets
Progress: 0.84
translated_text: Nahuli siya ng kanyang tingin | Nahuli niya ang kanyang mata | Nakuha ang atensyon ng waiter
Progress: 0.84
translated_text: sinalo siya ng bato sa likod ng ulo | Ang suntok ay nakuha siya sa likod | Sinalo siya ng suntok sa tiyan
Progress: 0.84
translated_text: Hindi ka makakakuha ng tubig mula sa isang bato | Saan niya nakuha ang mga balitang ito?
Progress: 0.84
translated_text: Hindi ko nahuli ang iyong pangalan | Hindi niya nakuha ang pangalan nito noong una silang magkita
Progress: 0.84
translated_text: Nakakaakit talaga sa akin ang ugali niyang bata | Ang pagsisinungaling niya ay talagang nakukuha ko
Progress: 0.84
translated_text: Talagang nahuli niya ang diwa ng lugar sa kanyang mga guhit | Tamang-tama ang mood niya sa mga litrato niya
Progress: 0.84
translated_text: Nakuha ng bagyong yelo ang aking hibiscus | nakuha ng pusa ang goldpis
Progress: 0.84
translated_text: Tinalo ako nito! | Nakuha ko--hindi ko alam ang sagot! | isang nakakainis na problema | Ang tanong na ito ay talagang natigil sa akin
Progress: 0.84
translated_text: Nagsimula kaming magtrabaho sa madaling araw | Sino ang magsisimula? | Magtrabaho kaagad sa pagsikat ng araw! | Nagsimulang dumating ang mga unang turista sa Cambodia | Nagsimula siya sa madaling araw | Bumaba na tayo sa trabaho
Progress: 0.84
translated_text: Nagdusa siya ng bali sa aksidente | Nagkaroon siya ng insulin shock pagkatapos kumain ng tatlong candy bar | Nagkaroon siya ng pasa sa binti | Nabali ang braso niya sa scuffle
Progress: 0.84
translated_text: Ipinanganak ni Abraham si Isaac | Ang mga lalaki ay madalas na ama ng mga anak ngunit hindi sila nakikilala
Progress: 0.84
translated_text: Natuto siyang sumayaw mula sa kanyang kapatid na babae | Natutunan ko ang Sanskrit | Nakakakuha ang mga bata ng wika sa napakabilis na bilis
Progress: 0.84
translated_text: Nalaman ko na mayroon siyang dalawang anak na nasa hustong gulang na | Nakikita ko na na-promote ka
Progress: 0.84
translated_text: Tinuruan ko sila ng French | Inutusan niya ako sa paggawa ng bangka
Progress: 0.84
translated_text: Gusto kong makita kung nagsasalita siya ng French | Tingnan kung gumagana ito | alamin kung nagsasalita siya ng Russian | Suriin kung ang tren ay aalis sa oras
Progress: 0.84
translated_text: Ginagawa ko ito para sa kasiyahan nito | masaya siyang kasama
Progress: 0.84
translated_text: naging figure of fun siya | sinabi niya ito sa isport
Progress: 0.84
translated_text: humingi siya ng pera at pagkatapos ay nagsimula ang saya | nagsimula silang mag-away na parang masaya
Progress: 0.84
translated_text: nagulat ako sa pagiging mapaglaro niya | masaya siyang kasama
Progress: 0.84
translated_text: nagkaroon sila ng kasunduan na hindi sila makikialam sa negosyo ng isa&#39;t isa | nagkaroon ng pagkakaunawaan sa pagitan ng management at ng mga manggagawa
Progress: 0.84
translated_text: walang kasunduan sa pagitan ng teorya at pagsukat | ang mga resulta ng dalawang pagsusulit ay nasa sulat
Progress: 0.84
translated_text: isang string ng mga isla | tren ng mga nagdadalamhati | isang tren ng pag-iisip
Progress: 0.84
translated_text: kami ay bahagi ng isang caravan ng halos isang libong kamelyo | sumama sila sa bagon train para sa kaligtasan
Progress: 0.84
translated_text: Sinasanay ng matandang master ang mga world-class na biyolinista | binuo natin ang mga pinuno para sa hinaharap
Progress: 0.84
translated_text: Siya ay nagsasanay upang maging isang guro | Nagsanay siya bilang isang legal aid
Progress: 0.84
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.84
translated_text: Inaayos niya ang kanyang anak para maging kahalili niya | Ang prinsipe ay inihanda na maging Hari balang araw | Sinanay nila siyang maging isang mandirigma
Progress: 0.84
translated_text: Linangin ang iyong panlasa sa musika | Sanayin ang iyong tastebuds | Siya ay mahusay na nag-aral sa tula
Progress: 0.84
translated_text: Mangyaring huwag tutok sa iyong nakababatang kapatid! | Sinanay niya ang kanyang baril sa magnanakaw | Huwag sanayin ang iyong camera sa mga babae | Mag-swipe sa kalaban
Progress: 0.84
translated_text: Sinasanay niya ang aming Olympic team | Siya ang nagtuturo sa crew
Progress: 0.84
translated_text: Nag-rail sila mula Roma hanggang Venice | Nagsanay siya sa Hamburg
Progress: 0.84
translated_text: Sinusundan ng paslit ang kanyang pantalon | Sinanay niya ang kanyang mahabang scarf sa likod niya
Progress: 0.84
translated_text: ugali nila na magbigay ng taunang pagtaas | binago nila ang kanilang dietary pattern
Progress: 0.84
translated_text: isang mahirap na teorya na isabuhay | pagkakaiba sa pagitan ng teorya at praktika ng komunismo
Progress: 0.84
translated_text: ang pagsasagawa ng batas | Ako ang pumalit sa kanyang pagsasanay noong siya ay nagretiro
Progress: 0.84
translated_text: Nag-drill kami ng mga pandiwang Pranses araw-araw | Ang mga pianista ay nagsasanay ng mga kaliskis

Progress: 0.84
translated_text: maglapat ng prinsipyo | magsagawa ng relihiyon | mag-ingat sa pagbaba ng hagdan | gamitin ang iyong sentido komun | magsagawa ng hindi marahas na paglaban
Progress: 0.84
translated_text: magsanay ng ligtas na pakikipagtalik | gumawa ng random na gawa ng kabaitan
Progress: 0.84
translated_text: Itinago ng mga babaeng Muslim ang kanilang mga mukha | itago ang pera
Progress: 0.84
translated_text: Malamang malapit ang kanyang kabayo sa kanyang pinagtataguan | Siya ay nagtatago sa isang cabin sa Montana
Progress: 0.84
translated_text: isang nakatagong mensahe | isang nakatalukbong pagbabanta
Progress: 0.84
translated_text: ang isyu ay maaaring malutas sa pamamagitan ng pag-aatas ng pampublikong edukasyon para sa lahat | hindi kailanman tinatalakay ng mga pulitiko ang mga tunay na isyu
Progress: 0.84
translated_text: siya ay patuloy na inaanod sa paksa | ilang taon na niyang pinag-isipan ang paksa | ito ay isang bagay para sa mga pulis
Progress: 0.85
translated_text: isang bagong isyu ng mga selyo | ang huling isyu ng penicillin ay mahigit isang buwan na ang nakalipas
Progress: 0.85
translated_text: ang magnetic effect ay mas malaki kapag ang baras ay pahaba | ang kanyang desisyon ay may nakapanlulumong kahihinatnan para sa negosyo | napaka bait niya pagkatapos ng pangyayari
Progress: 0.85
translated_text: siya ang ina ng maraming supling | namatay siya ng walang isyu
Progress: 0.85
translated_text: hinarangan niya ang daan palabas | iisa lang ang isyu ng canyon
Progress: 0.85
translated_text: mag-isyu ng bagong uniporme sa mga bata | magbigay ng mga kumot para sa mga kama
Progress: 0.85
translated_text: Tubig na inilabas mula sa butas sa dingding | Parang kusang lumabas ang mga salita
Progress: 0.85
translated_text: sumulat ng tseke | putulin ang isang tiket | Mangyaring gawin ang check out sa akin
Progress: 0.85
translated_text: pareho silang maganda | ang mga ibon ay umaawit at ang bata ay umawit bilang matamis | kumanta na kasing tamis ng nightingale | siya ay bawat bit bilang masama bilang siya ay
Progress: 0.85
translated_text: may punit sa kanyang pantalon | may mga snags siya sa kanyang medyas
Progress: 0.85
translated_text: Kumuha kami ng apartment sa isang tahimik na kalye | Magrenta tayo ng sasakyan | Kukuha ba tayo ng gabay sa Roma?
Progress: 0.85
translated_text: Napunit ang kurtina mula sa itaas hanggang sa ibaba | hilahin ang nilutong manok sa mga piraso
Progress: 0.85
translated_text: nagsilbi siya ng 15 buwang pagkakulong | ang kanyang sentensiya ay 5 hanggang 10 taon | siya ay gumagawa ng oras sa bilangguan ng county
Progress: 0.85
translated_text: ipinakita nila ang lahat ng abala ng isang pakete ng mga beaver | mayroong patuloy na ugong ng paghahanda sa militar
Progress: 0.85
translated_text: ang unang eksperimento ay isang tunay na pabo | ang pagpupulong ay isang dud sa abot ng bagong negosyo ay nababahala
Progress: 0.85
translated_text: Nag-aral siya ng mabuti ngunit nabigo pa rin | Nabigo ba ako sa pagsusulit?
Progress: 0.85
translated_text: ang Italian simula ng Renaissance | Jupiter ang pinagmulan ng radiation | Pittsburgh ay ang pinagmulan ng Ohio River | ugat ng Ruso ng komunismo
Progress: 0.85
translated_text: Ang mga uling ay kumikinang sa dilim | Ang mga kandila ay nasusunog
Progress: 0.85
translated_text: Nasunog ang araw sa hamog | Nagsusunog kami ng karbon at iba pang fossil fuel
Progress: 0.85
translated_text: Nag-aapoy siya sa galit | Siya ay nasusunog upang subukan ang kanyang bagong himpapawid
Progress: 0.85
translated_text: magsunog ng basura | Diesel oil lang ang sinusunog ng sasakyan
Progress: 0.85
translated_text: gupitin ang isang disk | magsunog ng CD
Progress: 0.85
translated_text: nagsusulat siya ng mga libro para sa mga bata | mga bata pa lang sila | Ang `tiddler&#39; ay isang British na termino para sa youngster
Progress: 0.85
translated_text: nag-ping ang sasakyan nang maglagay ako ng low-octane na gasolina | Nag-pink ang kotse nang masyadong malayo ang ignition
Progress: 0.85
translated_text: lugi ang kumpanya noong nakaraang taon | ang kumpanya ay nagpatakbo sa pula noong nakaraang taon
Progress: 0.85
translated_text: nagsusulat ng mapupulang mga gawa at barbaric na araw | fann&#39;d sa pamamagitan ng Conquest&#39;s crimson wing | nanginginig sa pulang galit
Progress: 0.85
translated_text: pulang-pula sa galit | naging pula dahil sa pagod | na may mapupulang namumulang mata | mapula ang mukha at marahas | namumula (o pulang-pula) sa kahihiyan
Progress: 0.85
translated_text: kasing puti ng sariwang niyebe | puting damit ng nobya
Progress: 0.85
translated_text: isang puting Pasko | ang mga puting burol ng hilagang taglamig
Progress: 0.85
translated_text: sa ilalim ng segregation mayroong kahit puting banyo at puting inuming fountain | isang kilusang lily-white na magpapaalis sa mga Negro mula sa organisasyon
Progress: 0.85
translated_text: puting apoy | isang puting-mainit na sentro ng apoy
Progress: 0.85
translated_text: mga blangkong pahina | punan ang mga blangkong puwang | isang malinis na pahina | malawak na puting mga gilid
Progress: 0.85
translated_text: isang mukha ang namumula | ang namumulang pisngi ng invalid | sinubukang magsalita ng walang dugong labi | isang mukha na puno ng galit sa pagkabigla | labi...namumula sa kulay ng kamatayan | mapuputing labi sa takot | puting mukha sa galit
Progress: 0.85
translated_text: ang impiyerno ng labanan | ang impyerno ng silid ng makina | kapag nag-iisa ka Pasko ang hukay
Progress: 0.85
translated_text: digmaan ay impiyerno | pumunta sa blazes
Progress: 0.85
translated_text: Hurl&#39;d headlong...Sa napakalalim na kapahamakan, doon manirahan | isang demonyo mula sa kailaliman ng hukay | Ang impiyerno ay sementadong may mabuting hangarin
Progress: 0.85
translated_text: ang bahay ay isang gulo | hinimas niya ang mussiness ng kama
Progress: 0.85
translated_text: nakuha niya sa isang kahila-hilakbot na ayusin | gumawa siya ng kaguluhan sa kanyang kasal
Progress: 0.85
translated_text: isang batch ng mga titik | isang deal ng problema | maraming pera | gumawa siya ng mint sa stock market | tingnan ang iba pang mga nanalo sa aming malaking passel ng mga larawan | ito ay dapat magkaroon ng maraming gastos | isang patay na mamamahayag | isang balumbon ng pera
Progress: 0.85
translated_text: natapos nila ang laro sa ilalim ng protesta sa pangulo ng liga | bumangon ang senador para irehistro ang kanyang protesta | ang maraming protesta ay hindi nanatili sa pagpapatupad
Progress: 0.85
translated_text: sinigaw niya ang kanyang mga protesta sa umpire | isang ulan ng protesta ang narinig mula sa likuran ng bulwagan
Progress: 0.85
translated_text: ang tore ay may binibigkas na pagtabingi | ang barko ay bumuo ng isang listahan sa starboard | lumakad siya na may mabigat na hilig sa kanan
Progress: 0.85
translated_text: Ang lobo ay tumaas sa ibabaw | ginawang takong ng hangin ang sisidlan | Nakalista ang barko sa starboard
Progress: 0.85
translated_text: Gumawa siya ng tula | Nagsulat siya ng apat na nobela
Progress: 0.85
translated_text: Ilang aklat ang isinulat ni Georges Simenon? | Nag-publish siya ng 25 na libro sa kanyang mahabang karera
Progress: 0.85
translated_text: Ang pintor ay nagsulat ng mga Chinese character sa isang malaking piraso ng puting papel | Ang Ruso ay nakasulat gamit ang alpabetong Cyrillic
Progress: 0.85
translated_text: Gumawa siya ng tula | Nagsulat siya ng apat na nobela
Progress: 0.85
translated_text: Ilang aklat ang isinulat ni Georges Simenon? | Nag-publish siya ng 25 mga libro sa kanyang mahabang karera
Progress: 0.85
translated_text: Ang pintor ay nagsulat ng mga Chinese character sa isang malaking piraso ng puting papel | Ang Ruso ay nakasulat gamit ang alpabetong Cyrillic
Progress: 0.85
translated_text: nagkaroon sila ng away | nagkaroon sila ng mga salita
Progress: 0.85
translated_text: isang mackerel sky na puno ng mga hanay ng mga ulap | pinoprotektahan ng mga hilera ng barbed wire ang mga trenches
Progress: 0.86
translated_text: ang Democratic Party ay isang payong para sa maraming liberal na grupo | sa ilalim ng payong ng kapitalismo
Progress: 0.86
translated_text: isang payong organisasyon | payong insurance coverage

Progress: 0.86
translated_text: pinagkakaguluhan mo ako sa ibang kandidato | Napagkamalan kong sekretarya siya
Progress: 0.86
translated_text: Ang mga tanong na ito ay nakalilito maging ang mga eksperto | Ang tanong na ito ay lubos na naghagis sa akin | Ang tanong na ito ay nataranta maging ang guro
Progress: 0.86
translated_text: Ang kanyang mga pangungusap ay nakalilito sa debate | Ang kanilang mga salita ay nagpapawalang-bisa sa kanilang mga intensyon
Progress: 0.86
translated_text: halatang naguguluhan sa mga tanong niya | nalilito at nalilito | isang maulap at nalilitong pilosopo | halong-halong bata lang | Pakiramdam niya ay nawala siya sa unang araw ng paaralan
Progress: 0.86
translated_text: isang nalilitong hanay ng mga tagubilin | isang nalilitong panaginip tungkol sa katapusan ng mundo | naputol na mga fragment ng isang kuwento | kalat-kalat na kaisipan
Progress: 0.86
translated_text: Madalas kong makita ang aking sarili na disoriented kapag umahon ako sa subway | ang pampamanhid ay nag-iwan sa kanya ng ganap na disoriented
Progress: 0.86
translated_text: mga tropang tumatakas sa sirang hanay | isang nalilitong masa ng mga papel sa desk | ang maliit na hindi maayos na silid | sa sobrang sama ng loob
Progress: 0.86
translated_text: Nakakainis talaga ang mga lamok sa tenga ko | Naiirita ako na hindi niya isinasara ang pinto pagkatapos niyang umalis
Progress: 0.86
translated_text: ang fag na katapusan nitong siglong puno ng krisis | ang buntot ng bagyo
Progress: 0.86
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.86
translated_text: Hinabol ng pulis ang magnanakaw sa eskinita | hinabol ng aso ang kuneho
Progress: 0.86
translated_text: nakita namin ang buong shebang | isang hotdog na may gawa | kinuha namin ang buong caboodle | para sa $10 makukuha mo ang buong paggamot
Progress: 0.86
translated_text: kaligtasan sa pamamagitan ng mga gawa | ang gantimpala para sa mabubuting gawa
Progress: 0.86
translated_text: hindi ito itinuturing na isa sa kanyang mga di malilimutang gawa | ang symphony ay pinarangalan bilang isang mapanlikhang gawa | siya ay may utang na loob sa pangunguna sa trabaho ni John Dewey | ang gawain ng isang aktibong imahinasyon | Ang pagguho ay ang gawain ng hangin o tubig sa paglipas ng panahon
Progress: 0.86
translated_text: naghahanap siya ng trabaho | maraming tao ang walang trabaho
Progress: 0.86
translated_text: ang pag-master ng pangalawang wika ay nangangailangan ng maraming trabaho | walang mga paaralan ang nag-aalok ng graduate na pag-aaral sa interior design
Progress: 0.86
translated_text: pinag-aralan niya ang buong Wagnerian oeuvre | Maaaring hatiin sa mga panahon ang gawa ni Picasso
Progress: 0.86
translated_text: Ako ay magsisikap na mapabuti ang aking mga marka | nagsumikap siya para sa mas magandang kalagayan ng pamumuhay para sa mahihirap
Progress: 0.86
translated_text: Nagtatrabaho na ba ulit ang asawa mo? | Ang aking asawa ay hindi kailanman nagtrabaho | Gusto mo bang magtrabaho pagkatapos ng edad na 60? | Hindi siya gumawa ng anumang trabaho dahil nagmana siya ng maraming pera | Nagtatrabaho siya bilang isang waitress upang maipagpatuloy ang kanyang sarili sa kolehiyo
Progress: 0.86
translated_text: Ang proseso ng pagboto ay hindi gumagana tulad ng iniisip ng mga tao | Paano gumagana ang iyong ideya sa pagsasanay? | Ang pamamaraang ito ay hindi gumagana | Mabilis na kumilos ang mga break ng bago kong sasakyan | Gumagana lamang ang gamot kung iniinom mo ito ng maraming tubig
Progress: 0.86
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.86
translated_text: gumawa ng bato sa mga kasangkapan | iproseso ang bakal | gawan ng metal
Progress: 0.86
translated_text: Ang ilang mga magulang ay nag-eehersisyo sa kanilang mga sanggol | Pinaghirapan ako ng aking personal na tagapagsanay | magtrabaho ng mga kalamnan | ang puzzle na ito ay magsasanay sa iyong isip
Progress: 0.86
translated_text: gumawa ng paraan sa pamamagitan ng karamihan ng tao | gumawa ng paraan sa kagubatan
Progress: 0.86
translated_text: Nagtatrabaho siya sa mga night club | Ang tindero ay nagtatrabaho sa Midwest | Ang artist na ito ay halos gumagana sa acrylics
Progress: 0.86
translated_text: gawin ang iyong paraan sa bawat problema o gawain | Siya ay nagtatrabaho sa kanyang pangalawang martini nang dumating ang mga bisita | Magsimula mula sa ibaba at magtrabaho patungo sa itaas
Progress: 0.86
translated_text: Hindi ako makagawa ng milagro | gumawa ng kalituhan | magdala ng mga komento | magbiro | Nagdulot ng ginhawa ang ulan sa lugar na naapektuhan ng tagtuyot
Progress: 0.86
translated_text: Trabaho ang lupa | linangin ang lupa
Progress: 0.86
translated_text: Ang masa na ito ay hindi madaling gumana | Ang malambot na metal ay gumagana nang maayos
Progress: 0.86
translated_text: Naimpluwensyahan ng gawa ng pintor ang batang pintor | Nagtrabaho siya sa kanyang mga kaibigan upang suportahan ang kandidato sa pulitika
Progress: 0.86
translated_text: Ginagawa ng pilot na ito ang mga kontrol | Maaari ka bang gumawa ng electric drill?
Progress: 0.86
translated_text: Maingat niyang hinulma ang mga rice ball | Bumuo ng mga silindro mula sa kuwarta | hugis ng pigura | Gawing espada ang metal
Progress: 0.86
translated_text: gawin ang mga pasas sa kuwarta | ang mag-aaral ay gumawa ng ilang biro sa kanyang presentasyon | isakay ang katawan sa flatbed truck
Progress: 0.86
translated_text: masahin ang kuwarta | gawin ang luad hanggang sa ito ay malambot
Progress: 0.86
translated_text: Pinagsasamantalahan niya ang bagong sistema ng pagbubuwis | Alam niya kung paano gawin ang sistema | nagtatrabaho siya sa kanyang mga magulang para sa pakikiramay
Progress: 0.86
translated_text: nalutas mo ba ang problema? | Ayusin ang iyong mga problema sa boss | ang hindi kasiya-siyang sitwasyong ito ay hindi gagana mismo | nakuha mo ba? | Nakuha mo ba ang ibig kong sabihin? | Hindi niya magawa ang problema sa matematika
Progress: 0.86
translated_text: Inaasim namin ang mga ubas sa napakatagal na panahon upang makamit ang mataas na nilalamang alkohol | Ang nagtitinda ay gumawa ng alak sa malalaking oak vats
Progress: 0.86
translated_text: Ang gatas ay umasim | Ang alak ay gumana | Ang cream ay nakabukas--kailangan nating itapon ito
Progress: 0.86
translated_text: ang lakas ng makina nito ay tumutukoy sa operasyon nito | ang pagpapatakbo ng eroplano sa malakas na hangin | inihambing nila ang pagganap ng pagluluto ng bawat oven | ang pagganap ng jet ay umaayon sa matataas na pamantayan
Progress: 0.86
translated_text: Ang washing machine ay hindi pupunta maliban kung ito ay nakasaksak sa | Maayos pa ba ang takbo ng lumang kotseng ito? | Hindi na gumagana itong lumang radyo
Progress: 0.86
translated_text: Ang tuod ng puno ay nagsisilbing mesa | Ang mga babaeng estudyante ay nagsilbing control group | Ang talahanayang ito ay magsisilbi nang napakahusay | Ang kanyang kalayaan ay nagsilbi sa kanya ng mabuti | Ang talahanayan ay gumagana bilang isang mesa
Progress: 0.86
translated_text: ang Panahon ng Puritan ay kulang sa kulay | ang mga karakter ay inilarawan nang may pambihirang liwanag
Progress: 0.86
translated_text: umaasa siya na ang kanyang mga paghahabol ay magkakaroon ng pagkakahawig ng pagiging tunay | sinubukan niyang bigyan ang kanyang kasinungalingan ng gloss ng moral na sanction | hindi nagtagal ay nagkaroon ng ibang kulay ang sitwasyon
Progress: 0.86
translated_text: Kinulayan ng bata ang mga guhit | Taglagas kulay ang mga puno | kulayan ang itim at puting pelikula
Progress: 0.86
translated_text: Ang aking personal na damdamin ay nagbibigay kulay sa aking paghatol sa kasong ito | Nababalot ng kalungkutan ang kanyang buhay
Progress: 0.86
translated_text: may kulay na pelikula | nagrenta siya ng color television | kahanga-hangang mga ilustrasyon ng kulay
Progress: 0.86
translated_text: isang piquant wit | maalat na wika
Progress: 0.86
translated_text: ang aking kasakiman ay naging instrumento ng aking pagkawasak | Binigyan tayo ng agham ng mga bagong kasangkapan upang labanan ang sakit

Progress: 0.87
translated_text: aso, fox, at iba pa | hindi namin gusto ang mga tulad mo sa paligid
Progress: 0.87
translated_text: Hindi na natin makikita ang katulad niya | Hindi ko kayang tiisin ang mga taong katulad niya
Progress: 0.87
translated_text: Gusto mo bang subukan ang dish na ito? | Gusto mo bang sumama sa mga pelikula?
Progress: 0.87
translated_text: Gusto kong mag-jogging | Mahilig siyang magbasa ng mga nobelang Ruso
Progress: 0.87
translated_text: suit ng katulad na disenyo | isang limitadong bilog ng mga katulad na isip | ang mga miyembro ng pamilya ng pusa ay may katulad na disposisyon | tulad ng dalawang gisantes sa isang pod | mala-dog na debosyon | isang parang panaginip na kalidad
Progress: 0.87
translated_text: tulad ng mga halaga | katumbas na halaga | ang parehong halaga | nagbigay ng isang anim na suntok at ang isa ay katulad ng numero | parehong numero
Progress: 0.87
translated_text: lahat ng politiko ay magkatulad | magkamukha sila | ang mga kaibigan ay karaniwang magkapareho sa background at panlasa
Progress: 0.87
translated_text: mga kahon na may kaukulang sukat | ang katulad na panahon ng naunang taon
Progress: 0.87
translated_text: isang parada ng mga stroller sa mall | isang parada ng mga saksi
Progress: 0.87
translated_text: ang Central Intelligence Agency | ang Census Bureau | Opisina ng Pamamahala at Badyet | Tennessee Valley Authority
Progress: 0.87
translated_text: na engrossed hitsura o rapt delight | tapos binalot sa panaginip | so intent on this fantastic...narrative that she hardly stirred | rapt with wonder | nababalot sa isip
Progress: 0.87
translated_text: Ayaw kong marinig ang iyak ng isang bata | naluluha siya
Progress: 0.87
translated_text: may punit sa kanyang pantalon | may mga snags siya sa kanyang medyas
Progress: 0.87
translated_text: Naputol ang lubid | punitin ang papel
Progress: 0.87
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.87
translated_text: hilahin ang manok | bunutin ang capon
Progress: 0.87
translated_text: punasan ang pisara | Ipinatong niya ang kanyang mga kamay sa malambot na tela
Progress: 0.87
translated_text: Sinaktan niya ako nang hindi niya ako isinama sa kanyang mga bisita | Ang pananalitang ito ay talagang nabugbog ang aking ego
Progress: 0.87
translated_text: inaalagaan ang kanyang sugatang braso | ambulansya...para sa mga nasaktang lalaki at babae
Progress: 0.87
translated_text: Madalas hampasin ng guro ang mga estudyante | Ang mga bata ay lubhang natalo
Progress: 0.87
translated_text: Pinapaltos ng Senador ang administrasyon sa kanyang talumpati noong Biyernes | pinalaki ng propesor ang mga estudyante | pinaso ng iyong mga invectives ang komunidad
Progress: 0.87
translated_text: isang lalaking sanggol | isang lalaking holly tree
Progress: 0.87
translated_text: isang malalim na boses ng lalaki | panlalaking isports
Progress: 0.87
translated_text: ang lalaking lead | populasyon ng lalaki
Progress: 0.87
translated_text: isang lalaking sanggol | isang lalaking holly tree
Progress: 0.87
translated_text: isang malalim na boses ng lalaki | panlalaking isports
Progress: 0.87
translated_text: ang lalaking lead | populasyon ng lalaki
Progress: 0.87
translated_text: Mga bata ay nakikipagkita sa parke | Nakipagkita sila sa modelo ng Red Dragon
Progress: 0.87
translated_text: ibinalik niya ang tasa sa platito | nawawala ang hawakan ng tasa
Progress: 0.87
translated_text: uminom siya ng isang tasa ng kape | humiram siya ng isang tasa ng asukal
Progress: 0.87
translated_text: pinunan ng mga bubuyog ang mga tasa ng waxen ng pulot | nakasuot siya ng jock strap na may metal cup | ang tasa ng kanyang bra
Progress: 0.87
translated_text: siya ay nanumpa habang ang bola ay naka-rim sa tasa at gumulong palayo | ibalik ang watawat sa tasa
Progress: 0.87
translated_text: Kinakabahan niyang nilalaro ang kanyang singsing sa kasal | Huwag kalilikot sa mga turnilyo | Pinaglaruan niya ang ideyang tumakbo sa Senado
Progress: 0.87
translated_text: Naglaro sila sa kanilang mga kalaban | maglaro ng stock market | paglaruan ang kanyang damdamin | laruan na may ideya
Progress: 0.87
translated_text: ang lamig ay kitang kita ang aming hininga | lumabas sa lamig | ang lamig ay isang vasoconstrictor
Progress: 0.87
translated_text: nanginginig siya sa lamig | ang lamig ay tumulong sa pag-alis ng kanyang ulo
Progress: 0.87
translated_text: isang malamig na klima | isang malamig na silid | lumamig na ang hapunan | malamig na mga daliri | kung nilalamig ka, pataasin ang init | isang malamig na beer
Progress: 0.87
translated_text: isang malamig na unfriendly na tango | isang malamig at hindi mapagmahal na tao | isang malamig na impersonal na paraan | malamig na lohika | ang concert ay iniwan ako ng malamig
Progress: 0.87
translated_text: isang malamig na landas | mga aso na nagtatangkang makatanggap ng malamig na amoy
Progress: 0.87
translated_text: mga teoryang kinakain ng gamugamo tungkol sa lahi | lipas na balita
Progress: 0.87
translated_text: malamig sa kanyang mga pagsulong | isang malamig na babae
Progress: 0.87
translated_text: sa malamig na dugo | malamig ang dugong pagpatay | walang kabuluhang pagkawasak
Progress: 0.87
translated_text: isang malamig na madla | malamig na tugon sa bagong dula
Progress: 0.87
translated_text: malamig ang boksingero | hinimatay ng malamig
Progress: 0.87
translated_text: sila ay sakim at gagawin ang lahat para sa pera | paghahagis ng mapag-imbot na mga mata sa bukid ng kanyang kapitbahay | isang nakahawak na matandang kuripot | paghawak sa komersyalismo | sakim sa pera at kapangyarihan | yumaman at sakim | matibay na mga employer na maramot sa mga umento para sa kanilang mga empleyado
Progress: 0.87
translated_text: masugid sa pakikipagsapalaran | isang masugid na ambisyon na magtagumpay | mabangis na lumalamon sa pagmamahal | ang maaliwalas na mga mata ng isang masugid na kuryusidad | sakim sa kasikatan
Progress: 0.87
translated_text: nakakuha siya ng bargain sa auction | ang stock ay isang tunay na pagbili sa presyong iyon
Progress: 0.87
translated_text: May nagnakaw ng wallet ko sa tren | Ninakaw ng may-akda na ito ang buong talata mula sa aking disertasyon
Progress: 0.87
translated_text: ang pamamaraan ng pagkuha ng lisensya sa pagmamaneho | ito ay isang proseso ng pagsubok at pagkakamali
Progress: 0.87
translated_text: ang proseso ng pag-iisip | ang cognitive operation ng pag-alala
Progress: 0.87
translated_text: mga kaganapan na kasalukuyang nasa proseso | ang proseso ng calcification ay nagsisimula mamaya para sa mga lalaki kaysa sa mga batang babae
Progress: 0.88
translated_text: proseso ng keso | proseso ng buhok | gamutin ang tubig para ito ay maiinom | gamutin ang damuhan ng mga kemikal | gamutin ang isang oil spill
Progress: 0.88
translated_text: Ako na ang bahala sa isang yan | magproseso ng loan | iproseso ang mga aplikante
Progress: 0.88
translated_text: Binalaan siya na ipoproseso siya ng district attorney | Inaksyunan niya ang kumpanya para sa diskriminasyon
Progress: 0.88
translated_text: gumawa ng bato sa mga kasangkapan | iproseso ang bakal | gawan ng metal
Progress: 0.88
translated_text: hindi mo ako binigyan ng sapat na paunawa | isang obituary notice
Progress: 0.88
translated_text: nakatanggap kami ng paunawa na lisanin ang lugar | nagbigay siya ng abiso dalawang buwan bago siya lumipat
Progress: 0.88
translated_text: Nakita niya ang mataas na antas ng tingga sa kanyang inuming tubig | May nakita kaming bakas ng tingga sa pintura
Progress: 0.88
translated_text: Napansin niyang may sumusunod sa kanya | markahan ang aking mga salita
Progress: 0.88
translated_text: Hindi niya kinikilala ang kanyang mga kasamahan kapag nakasalubong nila siya sa hallway | She acknowledged his complement with a smile | mahalagang kilalanin ang gawa ng iba sa sariling sulatin
Progress: 0.88
translated_text: sinaunang kasaysayan | sinaunang kabihasnan tulad ng mga Etruscan at Sumerian | sinaunang Greece
Progress: 0.88
translated_text: gumawa siya ng kopya ng designer dress | ang clone ay kopya ng ninuno nito
Progress: 0.88
translated_text: Ginaya ng mime ang mga dumaraan | Madalas na kinokopya ng mga bata ang kanilang mga magulang o nakatatandang kapatid

Progress: 0.88
translated_text: kopyahin ang cell | kopyahin ang genetic na impormasyon
Progress: 0.88
translated_text: kopyahin ang guhit na iyon | muling lumikha ng larawan ni Rembrandt
Progress: 0.88
translated_text: gumawa siya ng kopya ng designer dress | ang clone ay kopya ng ninuno nito
Progress: 0.88
translated_text: Ginaya ng mime ang mga dumadaan | Madalas na kinokopya ng mga bata ang kanilang mga magulang o nakatatandang kapatid
Progress: 0.88
translated_text: kopyahin ang cell | kopyahin ang genetic na impormasyon
Progress: 0.88
translated_text: kopyahin ang guhit na iyon | muling lumikha ng larawan ni Rembrandt
Progress: 0.88
translated_text: dapat nating isaalang-alang ang problemang ito mula sa pananaw ng mga Ruso | Ang pagtuturo ng kasaysayan ay nagbigay sa kanya ng isang espesyal na pananaw sa mga kasalukuyang kaganapan
Progress: 0.88
translated_text: Hindi ko matiis ang kanyang patuloy na pagpuna | Ang bagong kalihim ay kinailangang magtiis ng maraming hindi propesyonal na mga pahayag | natutunan niyang tiisin ang init | Nagtagal siya ng dalawang taon sa isang miserableng kasal
Progress: 0.88
translated_text: Nilabanan siya ng mga puno | tumayo sa pagsubok ng oras | Ang mga umaakyat sa bundok ay kailangang lumaban sa yelo at niyebe
Progress: 0.88
translated_text: nag-book siya ng kanilang mga upuan nang maaga | umupo siya sa pwesto ng iba
Progress: 0.88
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.88
translated_text: Inayos niya ang kanyang TV set | Pakiayos ang sapatos ko
Progress: 0.88
translated_text: pakuluan ang patatas | pakuluan ang lana
Progress: 0.88
translated_text: lumabas ang buong katawan sa auditorium | ang katawan ng mag-aaral | administratibong katawan
Progress: 0.88
translated_text: isang katawan ng batas | isang katawan ng doktrina | isang katawan ng mga nauna
Progress: 0.88
translated_text: ang lana ay may higit na katawan kaysa sa rayon | kapag ang kuwarta ay may sapat na pagkakapare-pareho, handa na itong i-bake
Progress: 0.88
translated_text: Siya ay kumakain ng saging | Ano ang nakain mo sa hapunan kagabi?
Progress: 0.88
translated_text: Hindi kami kumain hanggang 10 PM dahil ang daming tawag sa telepono | Hindi pa ako kumakain, kaya malugod kong tinatanggap ang iyong paanyaya
Progress: 0.88
translated_text: Ang asong ito ay hindi kumakain ng ilang uri ng karne | Ano ang kinakain ng mga balyena?
Progress: 0.88
translated_text: ang kotseng ito ay kumonsumo ng maraming gas | Naubos namin ang aming ipon | Tumatakbo sila sa 20 bote ng alak sa isang linggo
Progress: 0.88
translated_text: Sinira ng acid ang metal | Ang tuluy-tuloy na pagpatak ng tubig ay kinakalawang ang takip na bakal sa lababo
Progress: 0.88
translated_text: Walisan ang mga mumo sa mesa | Magwalis sa ilalim ng kama
Progress: 0.88
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.88
translated_text: ang bundok na iyon ay matibay na bato | sagana ang bato sa New England at maraming quarry
Progress: 0.88
translated_text: inilagay niya ang hiyas sa isang singsing para sa kanyang asawa | mayroon siyang mga hiyas na gawa sa lahat ng pinakapambihirang bato
Progress: 0.88
translated_text: dapat siyang may pusong bato | ang kanyang mukha ay kasing tigas ng bato
Progress: 0.88
translated_text: bumangon kami bago madaling araw | nag-usap sila hanggang umaga
Progress: 0.88
translated_text: isang eldritch screech | ang tatlong kakaibang kapatid na babae | mga tuod...may mga kakaibang hugis gaya ng mga halimaw na nilalang | isang hindi makalupa na liwanag | naririnig niya ang hindi makalupa na sigaw ng ilang kulot na tumutusok sa ingay
Progress: 0.88
translated_text: French na pagluluto | isang Gallic na kibit-balikat
Progress: 0.88
translated_text: gumuhit ng kariton | hilahin ang isang kareta
Progress: 0.88
translated_text: gumuhit ng linya | bakas ang balangkas ng isang pigura sa buhangin
Progress: 0.88
translated_text: Gumuhit ako ng linya dito | gumawa ng konklusyon | gumuhit ng mga parallel | gumawa ng pagtatantya | Ano ang masasabi mo sa kanyang mga pahayag?
Progress: 0.88
translated_text: gumuhit ng sandata | bumunot ng baril | Tinutukan ng magnanakaw ang kanyang biktima ng kutsilyo
Progress: 0.88
translated_text: Siya ay gumuhit ng isang elepante | Gumuhit ako ng kabayo
Progress: 0.88
translated_text: Ang mga komento ng Pangulo ay umani ng matalas na batikos mula sa mga Republican | Humugot ng tawa ang komedyante
Progress: 0.88
translated_text: huminga ng malalim | gumuhit sa isang sigarilyo
Progress: 0.88
translated_text: Nakakuha siya ng $2,000 mula sa account na | Ang mga doktor ay kumuha ng mga medikal na suplay mula sa emergency bank ng ospital
Progress: 0.88
translated_text: gumuhit ng card | magparami
Progress: 0.89
translated_text: Nadala siya sa kawalan ng pag-asa | Tumanggi ang Pangulo na madala sa pagbibigay ng ultimatum | Natapos ang session
Progress: 0.89
translated_text: iguhit ang shades | iguhit ang mga kurtina
Progress: 0.89
translated_text: Ang espongha ay sumisipsip ng tubig nang maayos | Siya ay nakakuha ng lakas mula sa mga salita ng ministro
Progress: 0.89
translated_text: Ang kanyang kagwapuhan ay umaakit sa mga titig ng maraming lalaki | Ang ad ay nakakuha ng maraming potensyal na customer | Ang piyanistang ito ay humihila ng napakaraming tao | Natuwa ang may-ari ng tindahan na nakakuha ang ad ng maraming bagong customer
Progress: 0.89
translated_text: string na perlas sa isang string | ang bata ay gumuhit ng mga kuwintas na salamin sa isang string | sinulid na pinatuyong cranberry
Progress: 0.89
translated_text: Pinasadahan niya ng mata ang katawan nito | Pinasadahan niya ng mga daliri ang inukit na pigurin | Hinawi niya ang buhok nito gamit ang kanyang mga daliri
Progress: 0.89
translated_text: bigyan ng pahintulot | Si Mandela ay pinahintulutan ng ilang bisita sa bilangguan
Progress: 0.89
translated_text: ang referee ay nagbigay ng libreng sipa sa koponan | iginawad ng hurado ang isang milyong dolyar sa nagsasakdal | Ang mga pondo ay ibinibigay sa mga kwalipikadong mananaliksik
Progress: 0.89
translated_text: bigyan ng degree | magbigay ng diborsiyo | Ang panukalang batas na ito ay nagbibigay sa atin ng mga bagong karapatan
Progress: 0.89
translated_text: libu-libong ektarya ng marshland | ang mga fens ng silangang England
Progress: 0.89
translated_text: Madalas manghuli si Goering ng mga baboy-ramo sa Poland | Ang mga aso ay tumatakbo sa usa | Nangangaso ang Duke sa kagubatan na ito
Progress: 0.89
translated_text: Tinunton ng mga mangangaso ang usa sa kakahuyan | hinabol ng mga tiktik ang suspek hanggang sa matagpuan nila ito
Progress: 0.89
translated_text: lecture hall | pool hall
Progress: 0.89
translated_text: Pinilit niya siyang kumuha ng trabaho sa lungsod | Pinisil niya ito para sa impormasyon
Progress: 0.89
translated_text: maghakot ng mga bato | maghakot ng mga lambat
Progress: 0.89
translated_text: hale at puso | buong isip at katawan | isang buong tao muli
Progress: 0.89
translated_text: mukhang alaga habang nakayuko sa kanyang pag-aayos | ang kanyang mukha ay iginuhit at haggard dahil sa kawalan ng tulog | na raddled ngunit marangal pa rin mukha | gulat na gulat nang makita ang pagod na hitsura ng kanyang gwapong mukha
Progress: 0.89
translated_text: payat na payat na mga kamay | isang bangungot na populasyon ng mga payat na lalaki at skeletal boys | mata ay haggard at lungga | maliliit na naipit na mukha | pinanatili ang buhay sa kanyang nasayang na frame sa pamamagitan lamang ng mabangis na konsentrasyon
Progress: 0.89
translated_text: ang maliit na kulay abong mga selula | kulay abong pranela suit | isang lalaking may kulay abo na buhok
Progress: 0.89
translated_text: na ang balbas sa edad ay paos na | tumango-tango ang ulo niya
Progress: 0.89
translated_text: makalipas ang dalawang araw ay umalis sila | nagsagawa sila ng dalawang pagtatanghal araw-araw | mayroong 30,000 pasahero kada araw
Progress: 0.89
translated_text: dapat itong dumating anumang araw ngayon | pagkatapos ng araw na iyon ay hindi na siya muling nagtiwala sa kanya | iyon ang mga araw | sa mga araw na ito ay hindi pangkaraniwan

Progress: 0.89
translated_text: ang bukang-liwayway ay ginawang araw ang gabi | mas madaling gawin ang pag-aayos sa araw
Progress: 0.89
translated_text: nagsimula ang araw ko kaninang madaling araw | ito ay isang abalang araw sa stock exchange | tinawag niya itong isang araw at natulog
Progress: 0.89
translated_text: sa araw ng mga dinosaur | noong panahon ng Imperyong Romano | sa mga araw ng paglalayag ng mga barko | siya ay isang matagumpay na pianista sa kanyang panahon
Progress: 0.89
translated_text: karapat-dapat siya sa kanyang araw sa korte | bawat aso ay may kanya-kanyang araw
Progress: 0.89
translated_text: ang char ang maglilinis ng carpet | Mayroon akong isang babae na pumapasok sa loob ng apat na oras sa isang araw habang nagsusulat ako
Progress: 0.89
translated_text: ito ay isang insulto sa American womanhood | babae ay ang kaluwalhatian ng paglikha | nagtipon ang patas na kasarian sa veranda
Progress: 0.89
translated_text: lumipat kami sa kanluran sa Arizona | matatagpuan sa kanluran ng Boston
Progress: 0.89
translated_text: ang sagisag ng pag-asa | ang pagkakatawang-tao ng kasamaan | ang mismong avatar ng tuso
Progress: 0.89
translated_text: ang sagisag ng pag-asa | ang pagkakatawang-tao ng kasamaan | ang mismong avatar ng tuso
Progress: 0.89
translated_text: Binalaan siya na ipoproseso siya ng district attorney | Inaksyunan niya ang kumpanya para sa diskriminasyon
Progress: 0.89
translated_text: may kislap siya sa mata | may walang hanggang kislap sa kanyang mga mata
Progress: 0.89
translated_text: isang spark ng interes | isang kislap ng pagiging disente
Progress: 0.89
translated_text: mag-trigger ng reaksyon | paandarin ang mga circuit
Progress: 0.89
translated_text: ng walang pakinabang | walang tulong para dito
Progress: 0.89
translated_text: Ang planta ng dumi sa alkantarilya ay nagsilbi sa mga kalapit na komunidad | Ang garahe ay nagsilbi upang kanlungan ang kanyang mga kabayo
Progress: 0.89
translated_text: serbisyo sa aking trak | ang washing machine ay kailangang serbisiyo
Progress: 0.89
translated_text: isang sundalo ang namamahala sa entrance post | isang istasyon ng bantay
Progress: 0.89
translated_text: ang military post na ito ay nagbibigay ng mahalagang pinagkukunan ng kita para sa kalapit na bayan | may officer&#39;s club sa poste
Progress: 0.89
translated_text: ang iyong mail ay nasa mesa | may post ba para sa akin? | binubuksan niya ang kanyang post
Progress: 0.89
translated_text: isang pares ng mga post ang minarkahan ang layunin | ang sulok ng lote ay ipinahiwatig ng isang taya
Progress: 0.89
translated_text: ang mail ay humahawak ng bilyun-bilyong item araw-araw | nagtatrabaho siya para sa serbisyo sa koreo ng Estados Unidos | sa England tinatawag nila ang mail na &#39;ang post&#39;
Progress: 0.89
translated_text: dumating ito sa unang post | kung nagmamadali ka mahuhuli mo ang post
Progress: 0.89
translated_text: mag-post ng sign | mag-post ng babala sa tambakan
Progress: 0.89
translated_text: ipadala sa akin ang iyong mga pinakabagong resulta | Ipapadala ko sa iyo ang papel kapag nakasulat na
Progress: 0.89
translated_text: ang mga mangangaso ay pinatungan ng mga aso ang oso at pinatay ito | mahilig mag tree squirrel ang aso niya
Progress: 0.89
translated_text: bumiyahe ang bola ng 90 mph sa kanyang serve | inihagis ng alkalde ang unang bola | gumulong ang bola sa sulok na bulsa
Progress: 0.89
translated_text: ang bola sa base ng hinlalaki | tumayo siya sa mga bola ng kanyang mga paa
Progress: 0.89
translated_text: Naputol ang lubid | punitin ang papel
Progress: 0.90
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.90
translated_text: hilahin ang manok | bunutin ang capon
Progress: 0.90
translated_text: napunit sa pagitan ng pag-ibig at poot | napunit ng magkasalungat na katapatan | napunit ng mga hindi pagkakaunawaan sa relihiyon
Progress: 0.90
translated_text: Naputol ang lubid | punitin ang papel
Progress: 0.90
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.90
translated_text: hilahin ang manok | bunutin ang capon
Progress: 0.90
translated_text: napunit sa pagitan ng pag-ibig at poot | napunit ng magkasalungat na katapatan | napunit ng mga hindi pagkakaunawaan sa relihiyon
Progress: 0.90
translated_text: may punit sa kanyang pantalon | mayroon siyang mga snags sa kanyang medyas
Progress: 0.90
translated_text: Naputol ang lubid | punitin ang papel
Progress: 0.90
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.90
translated_text: humila ng manok | bunutin ang capon
Progress: 0.90
translated_text: nagawang gumawa ng crude splint | isang magaspang na cabin ng mga troso na may balat pa rin sa mga ito | magaspang na karpintero
Progress: 0.90
translated_text: magaspang na wika | isang bastos na biro | magaspang na pag-uugali | isang makalupang sense of humor | isang revoltingly gross expletive | isang bulgar na kilos | punong puno ng lenggwahe na dapat ay na-edit
Progress: 0.90
translated_text: hindi nilinis na mineral | langis na krudo
Progress: 0.90
translated_text: ang mga krudo na armas at bastos na mga kagamitang pang-agrikultura ng sinaunang tao | mga primitive na pelikula noong 1890s | primitive na kondisyon ng pamumuhay sa mga bundok ng Appalachian
Progress: 0.90
translated_text: ang mapurol na katotohanan | ang magaspang na katotohanan | pagharap sa matingkad na katotohanan ng deadline
Progress: 0.90
translated_text: raw data | ang hilaw na halaga ng produksyon | tanging ang krudo na mahahalagang istatistika
Progress: 0.90
translated_text: sa panahon ng konstruksiyon kailangan naming lumihis | ang kanyang libangan ay ang paggawa ng mga bangka
Progress: 0.90
translated_text: ang istraktura ay binubuo ng isang serye ng mga arko | sinuot niya ang kanyang buhok sa isang kamangha-manghang pagkakagawa ng mga whirls at ribbons
Progress: 0.90
translated_text: ang kanilang pangunahing negosyo ay ang pagtatayo ng bahay | ang mga manggagawa sa gusali ay nangangalakal
Progress: 0.90
translated_text: Ipinanganak ni Abraham si Isaac | Ang mga lalaki ay madalas na ama ng mga anak ngunit hindi sila nakikilala
Progress: 0.90
translated_text: Binalaan siya na ipoproseso siya ng district attorney | Inaksyunan niya ang kumpanya para sa diskriminasyon
Progress: 0.90
translated_text: mas maraming lupain | higit pang suporta | mas maraming ulan ang bumagsak | higit sa isang galon
Progress: 0.90
translated_text: isang bulwagan na may mas maraming upuan | wala na tayong saging | higit sa isa
Progress: 0.90
translated_text: mas kawili-wili | mas maganda | Mas mabilis
Progress: 0.90
translated_text: mas nagtatrabaho siya ngayon | kumakain sila ng higit sa nararapat
Progress: 0.90
translated_text: gumawa sila ng walang kwentang laro para sa kapangyarihan | gumawa siya ng isang bid upang makakuha ng atensyon
Progress: 0.90
translated_text: batiin ka ng magandang gabi | magpaalam
Progress: 0.90
translated_text: isang digmaan sa presyo | isang digmaan ng talino | diplomatikong digmaan
Progress: 0.90
translated_text: ang digmaan sa kahirapan | ang digmaan laban sa krimen
Progress: 0.90
translated_text: hinahanap nila ang may-ari ng sasakyan | sino ang may-ari ng magiliw na ngiti na iyon?
Progress: 0.90
translated_text: tawagin nating tagumpay ang ulo at kabiguan ang buntot | ang halalan ay isang kahanga-hangang tagumpay para sa Whigs
Progress: 0.90
translated_text: ang kanyang tagumpay sa marathon ay hindi inaasahan | ang kanyang bagong dula ay isang mahusay na tagumpay
Progress: 0.90
translated_text: tinatamasa niya ang malaking tagumpay | hindi niya itinuturing ang kayamanan na kasingkahulugan ng tagumpay
Progress: 0.90
translated_text: ang kanyang anak ay hindi kailanman magiging tagumpay na ang kanyang ama ay | ang mga nanalo lang ang kailangang mag-apply | kung nais mong maging isang tagumpay kailangan mong manamit tulad ng isang tagumpay
Progress: 0.90
translated_text: May nagboluntaryo bang mag-navigate habang nasa biyahe? | Sino ang nag-navigate sa barko noong aksidente?
Progress: 0.90
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig

Progress: 0.90
translated_text: `Nanalo ako!&#39; bulalas niya | `Tulong!&#39; umiyak siya | `Nandito na ako,&#39; sigaw ng ina nang makitang naliligaw ang kanyang anak
Progress: 0.90
translated_text: Inabuso ng aktres ang pulis na nagbigay sa kanya ng parking ticket | Sigaw ng galit na ina sa guro
Progress: 0.90
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.90
translated_text: `Nanalo ako!&#39; bulalas niya | `Tulong!&#39; umiyak siya | `Nandito na ako,&#39; sigaw ng ina nang makitang naliligaw ang kanyang anak
Progress: 0.90
translated_text: Inabuso ng aktres ang pulis na nagbigay sa kanya ng parking ticket | Sigaw ng galit na ina sa guro
Progress: 0.90
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.90
translated_text: `Nanalo ako!&#39; bulalas niya | `Tulong!&#39; umiyak siya | `Nandito na ako,&#39; sigaw ng ina nang makitang naliligaw ang kanyang anak
Progress: 0.90
translated_text: Inabuso ng aktres ang pulis na nagbigay sa kanya ng parking ticket | Sigaw ng galit na ina sa guro
Progress: 0.90
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.90
translated_text: `Nanalo ako!&#39; bulalas niya | `Tulong!&#39; umiyak siya | `Nandito ako,&#39; sigaw ng ina nang makitang naliligaw ang kanyang anak
Progress: 0.90
translated_text: Inabuso ng aktres ang pulis na nagbigay sa kanya ng parking ticket | Sigaw ng galit na ina sa guro
Progress: 0.90
translated_text: Dumagundong ang ilog sa ibaba | Umugong ang makina habang tinutulak ng driver ang kotse sa full throttle
Progress: 0.90
translated_text: masungit niyang tugon | Bumulong ang mga bato sa bangin
Progress: 0.91
translated_text: Siya ay kumakain ng saging | Anong kinain mo kagabi?
Progress: 0.91
translated_text: Hindi kami kumain hanggang 10 PM dahil ang daming tawag sa telepono | Hindi pa ako kumakain, kaya malugod kong tinatanggap ang iyong paanyaya
Progress: 0.91
translated_text: Ang asong ito ay hindi kumakain ng ilang uri ng karne | Ano ang kinakain ng mga balyena?
Progress: 0.91
translated_text: ang kotseng ito ay kumonsumo ng maraming gas | Naubos namin ang aming ipon | Tumatakbo sila sa 20 bote ng alak sa isang linggo
Progress: 0.91
translated_text: Sinira ng acid ang metal | Ang tuluy-tuloy na pagpatak ng tubig ay kinakalawang ang takip na bakal sa lababo
Progress: 0.91
translated_text: naglatag sila ng barrage sa harap ng mga sumusulong na tropa | ang paghihimay ay nagpatuloy ng ilang oras nang hindi humihinto
Progress: 0.91
translated_text: ng walang pakinabang | walang tulong para dito
Progress: 0.91
translated_text: Ang planta ng dumi sa alkantarilya ay nagsilbi sa mga kalapit na komunidad | Ang garahe ay nagsilbi upang kanlungan ang kanyang mga kabayo
Progress: 0.91
translated_text: serbisyo sa aking trak | kailangang serbisyuhan ang washing machine
Progress: 0.91
translated_text: basahin ang patalastas | Nabasa mo na ba ang Salman Rushdie?
Progress: 0.91
translated_text: Ang sipi ay nagbabasa ng mga sumusunod | Ano ang sinasabi ng batas?
Progress: 0.91
translated_text: Binasa niya ang langit at hinulaan ang ulan | Hindi ko mabasa ang kakaiba niyang ugali | Binasa ng manghuhula ang kanyang kapalaran sa bolang kristal
Progress: 0.91
translated_text: Binasa ko ang address na ito bilang isang satire | Paano ko dadalhin ang mensaheng ito? | Hindi ka maaaring kumuha ng kredito para dito!
Progress: 0.91
translated_text: Ang thermometer ay nagpakita ng labintatlong digri sa ibaba ng zero | Ang gauge ay may nakasulat na &#39;bakante&#39;
Progress: 0.91
translated_text: Naiintindihan niya ang French | Marunong ka bang magbasa ng Greek?
Progress: 0.91
translated_text: Nakakainis talaga ang mga lamok sa tenga ko | Naiirita ako na hindi niya isinasara ang pinto pagkatapos niyang umalis
Progress: 0.91
translated_text: Biniro ng mga bata ang bagong guro | Huwag mo akong sakyan nang husto sa aking kabiguan | Sinira siya ng mga katrabaho niya nang magsuot siya ng jacket at kurbata
Progress: 0.91
translated_text: Pinagalitan ng ina ang anak sa pagpasok sa sasakyan ng estranghero | Ang kinatawan ay ginulo ang Punong Ministro | Binihisan ng kostumer ang waiter para sa pagdadala ng malamig na sopas
Progress: 0.91
translated_text: isang kurtina ng lihim | isang kurtina ng mga puno
Progress: 0.91
translated_text: isang kurtina ng lihim | isang kurtina ng mga puno
Progress: 0.91
translated_text: isang kumpidensyal na misyon sa London | ang kanyang singil ay maghatid ng mensahe
Progress: 0.91
translated_text: Pinalitan niya ang lumang razor blade | Kailangan nating palitan ang secretary na umalis noong isang buwan | papalitan ng insurance ang nawalang kita | Ang antigong plorera na ito ay hinding-hindi mapapalitan
Progress: 0.91
translated_text: Pinalitan ni Smith si Miller bilang CEO pagkatapos umalis si Miller | pinalitan ng computer ang slide rule | Pinalitan ni Mary si Susan bilang kapitan ng koponan at ang pinakamataas na ranggo na manlalaro sa paaralan
Progress: 0.91
translated_text: palitan ang aklat sa istante pagkatapos mong basahin ito | pakilagay muli sa kabinet ang malinis na pinggan kapag nahugasan mo na
Progress: 0.91
translated_text: pinalitan ng con artist ang orihinal ng isang pekeng Rembrandt | palitan ang regular na gatas ng walang taba na gatas | maaaring palitan ang mga kasingkahulugan nang hindi binabago ang kahulugan ng konteksto
Progress: 0.91
translated_text: hapunan ay sa 8 | tuwing Linggo sila ay may malaking hapunan pagkabalik nila mula sa simbahan
Progress: 0.91
translated_text: ang aklat ay sinalubong ng katamtamang pagbubunyi | kinilala niya ang papuri ng karamihan | binigyan nila siya ng higit na eclat kaysa sa nararapat sa kanya
Progress: 0.91
translated_text: kumuha siya ng kursong basket weaving | Ang paglalandi ay hindi kilala sa mga klase sa kolehiyo
Progress: 0.91
translated_text: ang gobyerno ay kumuha ng matatag na kurso | ang mga istoryador ay maaari lamang ituro ang mga linyang iyon kung saan magagamit ang ebidensya
Progress: 0.91
translated_text: ang ilog ay dumadaan sa timog na kurso | ang hilagang-silangang takbo ng baybayin
Progress: 0.91
translated_text: kung magpupursige ka sa kursong iyon ay tiyak na mabibigo ka | sa sandaling ang isang bansa ay nagsimula sa isang kurso ng aksyon ito ay nagiging lubhang mahirap para sa anumang pagbawi na maganap
Progress: 0.91
translated_text: giniba ng bagyo ang mga bahay sa dinadaanan nito | ang track ng isang hayop | ang agos ng ilog
Progress: 0.91
translated_text: ang kurso ay mayroon lamang siyam na butas | ang kurso ay wala pang isang milya
Progress: 0.91
translated_text: Umagos ang tubig sa kweba | ang Missouri ay nagpapakain sa Mississippi
Progress: 0.91
translated_text: ang kanilang militar ang pinakamalaki sa rehiyon | ang makinang pangmilitar ay kapareho ng ating hinarap noong 1991 ngunit ngayon ay mas mahina na
Progress: 0.91
translated_text: isang screen ng mga puno na nagbibigay ng privacy | sa ilalim ng takip ng kadiliman | ang brush ay nagbigay ng isang tago para sa laro | ang pinakasimpleng pagtatago ay ang perpektong tumugma sa kulay ng background
Progress: 0.91
translated_text: sa ilalim ng takip ng alikabok | namula ang fox mula sa takip nito
Progress: 0.91
translated_text: tinanggal niya ang tuktok ng karton | hindi niya makuha ang tuktok mula sa bote | ibalik ang takip sa takure
Progress: 0.91
translated_text: takpan ang kanyang mukha ng panyo | takpan ang bata ng kumot | takpan ang libingan ng mga bulaklak
Progress: 0.91
translated_text: Ang digmaan ay pinalawig sa loob ng limang taon | Saklaw ng panahon ang pagliko ng siglo | Ang aking lupain ay umaabot sa ibabaw ng mga burol sa abot-tanaw | Saklaw ng sakahan na ito ang ilang 200 ektarya | Ang Archipelago ay nagpapatuloy ng isa pang 500 milya
Progress: 0.91
translated_text: Ang aklat na ito ay tumatalakay sa incest | Saklaw ng kurso ang lahat ng Western Civilization | Tinatalakay ng bagong aklat ang kasaysayan ng Tsina
Progress: 0.91
translated_text: Ang pangkat na ito ay sumasaklaw sa isang malawak na hanay ng mga tao mula sa iba&#39;t ibang background | ito ay dapat sumaklaw sa lahat ng tao sa grupo

Progress: 0.91
translated_text: Iniulat ni Snow sa China noong 1950&#39;s | Sinakop ng cub reporter ang New York City
Progress: 0.91
translated_text: Mga ibon brood | Tinatakpan ng babae ang mga itlog
Progress: 0.91
translated_text: darating kami bago pagkatapos | magkaibigan na kami simula noon
Progress: 0.91
translated_text: tapos umalis na siya | pumunta muna sa kaliwa, pagkatapos ay sa kanan | unang dumating ang kidlat, pagkatapos ay kulog | nanood kami ng late movie tapos natulog na | at kaya umuwi at matulog
Progress: 0.91
translated_text: kung hindi niya kinuha, sino ang kumuha? | itago mo kung gusto mong | ang kaso, kung gayon, ay sarado | nakapagdesisyon ka na ba noon? | tapos yumaman ka
Progress: 0.91
translated_text: Bata pa ako noon | mas mababa ang mga presyo noon | agham na itinuro noon
Progress: 0.91
translated_text: siya ay humingi ng paumanhin pagkatapos | pupunta siya sa tindahan pero babalik siya dito mamaya | hindi ito nangyari hanggang pagkatapos | dalawang oras pagkatapos noon
Progress: 0.91
translated_text: siya ay humingi ng paumanhin pagkatapos | pupunta siya sa tindahan pero babalik siya dito mamaya | hindi ito nangyari hanggang pagkatapos | dalawang oras pagkatapos noon
Progress: 0.91
translated_text: nang walang lihim na argumento | ang mood posterior sa
Progress: 0.92
translated_text: ang huling yugto ng pyudalismo | isang mas huling sintomas ng sakit | sa kalaunan ay maaaring mailigtas ng agham medikal ang bata
Progress: 0.92
translated_text: hating gabi | huling bahagi ng ika-18 siglo | isang huli na pelikula | kumuha ng late flight | nagkaroon ng late breakfast
Progress: 0.92
translated_text: isang late na birthday card | Huli na ako sa eroplano | huli na ang tren | ang mga nahuling bata ay ipinadala sa punong-guro | laging nahuhuli sa paggawa ng mga appointment sa ngipin
Progress: 0.92
translated_text: isang huli na pag-unlad | ang huli nilang pag-aaway | ang kanyang kamakailang paglalakbay sa Africa | sa mga nakaraang buwan | isang kamakailang isyu ng journal
Progress: 0.92
translated_text: ang huling yugto ng pyudalismo | isang mas huling sintomas ng sakit | sa kalaunan ay maaaring mailigtas ng agham medikal ang bata
Progress: 0.92
translated_text: ang dating pangulo | aktibo pa rin ang ating yumaong Presidente | ang dating nakatira sa White House
Progress: 0.92
translated_text: siya ay humingi ng paumanhin pagkatapos | pupunta siya sa tindahan pero babalik siya dito mamaya | hindi ito nangyari hanggang pagkatapos | dalawang oras pagkatapos noon
Progress: 0.92
translated_text: By and by he&#39;ll understand | magkita na lang tayo mamaya
Progress: 0.92
translated_text: nagdadala ang dugo ng oxygen at nutrients sa mga tissue at nagdadala ng mga dumi na produkto | naniniwala ang mga sinaunang tao na ang dugo ang upuan ng mga damdamin
Progress: 0.92
translated_text: duguan ang mga radiator | dinuguan ng mekaniko ang makina
Progress: 0.92
translated_text: siya ay nararapat sa isang magandang sipa sa puwit | uupo ka ba sa fanny mo at walang gagawin?
Progress: 0.92
translated_text: bromidic sermons | ang kanyang mga pananalita ay walang kabuluhan at karaniwan | hackneyed na mga parirala | isang stock na sagot | paulit-ulit na mga nakakatuwang biro | parroting ilang timeworn axiom | ang trite metapora `matigas gaya ng mga pako&#39;
Progress: 0.92
translated_text: ito ay isang kaso ng masamang paghatol | isa pang pagkakataon ang naganap kahapon | ngunit palaging mayroong sikat na halimbawa ng mga Smith
Progress: 0.92
translated_text: sa kaganapang iyon, ang unang posibilidad ay hindi kasama | maaaring umulan kung saan ang piknik ay kanselahin
Progress: 0.92
translated_text: ang mga paksa para sa pagsisiyasat na ito ay pinili nang sapalaran | ang mga kaso na aming pinag-aralan ay nakuha mula sa dalawang magkaibang komunidad
Progress: 0.92
translated_text: isang tunay na karakter | kakaibang karakter | isang magiliw sira-sira | ang may kakayahang uri | isang mental case
Progress: 0.92
translated_text: isang magandang bata | magandang bansa | isang magandang pagpipinta | isang magandang teorya | isang magandang party
Progress: 0.92
translated_text: Sa tingin ko siya ay napakatalino | Naniniwala ako na siya ay napakatalino | Sa tingin ko boyfriend niya | Iniisip ng racist na ang mga taong ito ay mababa
Progress: 0.92
translated_text: Iniisip ko na kumita siya ng maraming pera sa kanyang bagong nobela | Naisip kong hanapin siya sa masamang kalagayan | hindi niya naisip na hanapin siya sa kusina | Galit yata siya sa akin dahil pinatayo ko siya
Progress: 0.92
translated_text: Hindi ko matandaan na sinabi ko ang anumang bagay na iyon | Hindi ko maisip kung ano ang apelyido niya | naaalala mo ba ang kanyang numero ng telepono? | Naaalala mo ba na minsan ka niyang minahal? | tumawag ng mga alaala
Progress: 0.92
translated_text: Isipin mo na lang--mayaman ka balang araw! | Isipin kung anong eksena iyon!
Progress: 0.92
translated_text: Mag-isip ng malaki | mag-isip ng manipis
Progress: 0.92
translated_text: I mean walang pinsala | Sinadya ko lang tulungan ka | Hindi niya inisip na saktan ako | Naisipan naming bumalik ng maaga ng gabing iyon
Progress: 0.92
translated_text: Pag-isipan ang bagay sa pamamagitan ng | Isipin kung gaano kahirap ang buhay sa Russia sa mga araw na ito
Progress: 0.92
translated_text: gumawa sila ng pakana para siraan ang gobernador | Nakita ko ang kanyang maliit na laro mula sa simula
Progress: 0.92
translated_text: isang bean plot | isang patch ng repolyo | isang briar patch
Progress: 0.92
translated_text: gumawa sila ng anim na hakbang na plano | tinalakay nila ang mga plano para sa isang bagong isyu ng bono
Progress: 0.92
translated_text: ang awkward na disenyo ng keyboard ay nagpahirap sa operasyon | ito ay isang mahusay na disenyo para sa pamumuhay | isang plano para sa pag-upo ng mga bisita
Progress: 0.92
translated_text: Plano niyang magtapos sa paaralan sa susunod na taon | Ang mga rebelde ay nagplano ng kaguluhan at kalituhan
Progress: 0.92
translated_text: Nagkunwari silang patayin ang kanilang amo | magdisenyo ng bagong diskarte sa pagbebenta | magplano ng pag-atake
Progress: 0.92
translated_text: magdisenyo ng mas magandang bitag ng daga | planuhin ang bagong pakpak ng museo
Progress: 0.92
translated_text: masamang epekto | ito ay isang masamang hangin na hindi maganda ang ihip
Progress: 0.92
translated_text: masamang ugali | ng masamang reputasyon
Progress: 0.92
translated_text: ikaw ay tiyak na ginawa sa akin ng isang masamang turn | masamang damdamin | masamang kalooban
Progress: 0.92
translated_text: masamang palatandaan | masamang hula | ang aking mga salita na may mga hindi magandang kulog ay yumanig sa langit | isang patay at nagbabantang katahimikan ang namayani | isang by-election sa isang panahon na lubhang hindi karapat-dapat para sa Gobyerno
Progress: 0.92
translated_text: siya ay hindi handa | hindi nararapat sa isang tao na ipagkanulo ang mga dating kaibigan | hindi maganda ang takbo ng sasakyan | hindi maganda ang performance niya sa exam | hindi maganda ang laro ng koponan | hindi angkop na damit | isang masamang plano
Progress: 0.92
translated_text: sinubukang huwag magsalita ng masama tungkol sa mga patay | pinag-isipan siya ng masama dahil sa kawalan niya ng pag-aalala
Progress: 0.92
translated_text: nadama niya na ang kanyang buong buhay ay isang kabiguan | noong taong iyon ay nagkaroon ng crop failure
Progress: 0.92
translated_text: nagalit siya sa hindi ko pagbabalik ng kanyang tawag | kabiguang suriin ng mekaniko ang preno
Progress: 0.92
translated_text: kinailangang ideklara ng kumpanya ang pagkabangkarote | Ang mga mapanlinlang na pautang ay humantong sa pagkabigo ng maraming mga bangko
Progress: 0.92
translated_text: ang terminong `kabalisahan&#39; ay nagpapahiwatig ng ilang antas ng kaguluhan at emosyonal na pagkabalisa | nilingon niya ang pinanggalingan ng kaguluhan | nagkaroon ng kaguluhan ng neural function
Progress: 0.92
translated_text: nagkaroon ng labis na galit at kaguluhan | hindi niya namalayan ang sama ng loob na naidulot niya sa akin
Progress: 0.92
translated_text: ang kanyang mga aparador ay walang laman kundi mga nobela | sinunog niya lahat ng nobela

Progress: 0.92
translated_text: isang taas ng temperatura sa hapon | isang pagtataas ng lupain na bunga ng aktibidad ng bulkan
Progress: 0.92
translated_text: sagot niya sabay taas ng kilay | natututo ang bumbero ng maraming iba&#39;t ibang pagtaas para sa pag-akyat ng hagdan
Progress: 0.92
translated_text: Itaas ang iyong mga kamay | Magbuhat ng kargada
Progress: 0.92
translated_text: Umangat ang ulap | Ang usok ay bumangon mula sa sunog sa kagubatan | Ang ambon ay bumangon mula sa parang
Progress: 0.92
translated_text: Binawi niya ang pagbabawal sa paninigarilyo | alisin ang isang embargo | lisanin ang hatol ng kamatayan
Progress: 0.92
translated_text: itaas ang aking espiritu | itaas ang kanyang ego
Progress: 0.92
translated_text: alisin ang pagbabawal | itaas ang isang pagkubkob
Progress: 0.93
translated_text: Ang pulbos na ito ay madaling madikit | Ang ganitong mga kakaibang hugis ay hindi nakaimpake nang maayos
Progress: 0.93
translated_text: piniga niya ang kanyang mga labi | ang spasm ay nagkontrata sa kalamnan
Progress: 0.93
translated_text: siksik na lupa | siksik na kumpol ng mga bulaklak
Progress: 0.93
translated_text: isang wrestler ng compact build | siya ay matangkad at mabigat | matipuno ang mga binti | isang makakapal na binata
Progress: 0.93
translated_text: isang maikli at komprehensibong aklat | ang isang compact na istilo ay maikli at masigla | maikling paghahambing | isang buod na pagbabalangkas ng isang malawak na paksa
Progress: 0.93
translated_text: isang convertible sofa | isang convertible coupe
Progress: 0.93
translated_text: ang lead ba ay talagang nababago sa ginto? | mga ideyang naisasalin sa katotohanan
Progress: 0.93
translated_text: Binaligtad ang kalakaran | ang tubig ay bumaling laban sa kanya | Bumaling ang opinyon ng publiko nang mabunyag na ang presidente ay may relasyon sa isang White House intern
Progress: 0.93
translated_text: Binawi niya ang pagbabawal sa paninigarilyo | alisin ang isang embargo | lisanin ang hatol ng kamatayan
Progress: 0.93
translated_text: isang sulyap sa likuran | isang paatras na paggalaw
Progress: 0.93
translated_text: ang bubong ng yungib ay napakataas | Nakita ko ang bubong ng bibig ng oso
Progress: 0.93
translated_text: nilagyan niya ng kisame ang dami ng babaeng nagtrabaho sa kanya | nagkaroon ng bubong sa suweldo | nagtatag sila ng cap para sa mga presyo
Progress: 0.93
translated_text: isang kahel na may katamtamang laki | intermediate na kapasidad | katamtamang mga bombero
Progress: 0.93
translated_text: isang secondhand na ulat | isang secondhand account ng isang alaala ng isang bagay na minsang nabasa | karamihan sa ating kaalaman ay secondhand
Progress: 0.93
translated_text: Secondhand or thirdhand lang ang narinig ko | mas gusto niyang bumili ng secondhand
Progress: 0.93
translated_text: isang bruha ang naglagay ng sumpa sa kanyang buong pamilya | nilagay niya ang whammy sa akin
Progress: 0.93
translated_text: Pinulbos niya ang kanyang ilong | Nagsusuot ng powdered wig ang Hari
Progress: 0.93
translated_text: hindi pa naararo ang lupa | magandang lupang pang-agrikultura
Progress: 0.93
translated_text: pinalawak ang kanyang domain sa Europa | ginawa niya itong batas ng lupain
Progress: 0.93
translated_text: ang eroplano ay tumalikod sa dagat at bumalik sa lupa | yumanig ang lupa ng ilang minuto | ibinagsak niya ang mga troso sa lupa
Progress: 0.93
translated_text: bumalik siya sa lupang sinilangan | bumisita siya sa ilang bansa sa Europa
Progress: 0.93
translated_text: ang walang gulo na kaharian ng katwiran | isang lupain ng gawa-gawang | ang pagtaas ng kaharian ng bulak sa timog
Progress: 0.93
translated_text: isang pahayag na nagbubuod sa kalagayan ng bansa | ang balita ay inihayag sa bansa | sinamba siya ng buong bansa
Progress: 0.93
translated_text: ang estado ay naghalal ng bagong pangulo | Mga bansang Aprikano | mga mag-aaral na dumating sa kapitolyo ng bansa | pinakamalaking tagagawa ng bansa | isang industriyalisadong lupain
Progress: 0.93
translated_text: ang pagsasaka ay isang masipag na buhay | wala nang trabaho sa lupa
Progress: 0.93
translated_text: Lumapag ang ibon sa pinakamataas na sanga | Lumapag ang eroplano sa Istanbul
Progress: 0.93
translated_text: nag-iingat sila ng log ng lahat ng transmission ng istasyon ng radyo | isang email log
Progress: 0.93
translated_text: hindi lantarang liberal pero yan ang uso ng libro | isang malawak na paggalaw ng mga manghahalal sa kanan
Progress: 0.93
translated_text: Ang mga dahon ay umiihip sa hangin | ang bangka ay naanod sa lawa | Ang bangka ay naaanod sa bukas na dagat | ang bangkang nawasak ay naanod palayo sa pampang
Progress: 0.93
translated_text: Naligaw ng landas ang bata at nawala sa paningin ng kanyang mga magulang | huwag lumihis sa itinakdang kurso
Progress: 0.93
translated_text: Ang mga gypsies ay gumagala sa kakahuyan | roving vagabonds | ang gumagala na Hudyo | Ang mga baka ay gumagala sa buong prairie | ang mga manggagawa ay naaanod mula sa isang bayan patungo sa susunod na | Nagpagulong-gulong sila sa bayan
Progress: 0.93
translated_text: snow drifting ilang talampakan ang taas | buhangin na umaanod na parang niyebe
Progress: 0.93
translated_text: ginawa niya ang kanyang unang pagbebenta | kailangan nilang kumpletuhin ang pagbebenta bago magsara ang mga bangko
Progress: 0.93
translated_text: sinubukan nilang palakasin ang benta | nililimitahan ng mga batas ang pagbebenta ng mga baril
Progress: 0.93
translated_text: nagsagawa sila ng sale upang mabawasan ang kanilang imbentaryo | Nakakuha ako ng ilang magagandang bargains sa kanilang taunang sale
Progress: 0.93
translated_text: makakahanap ka ng bitamina C na ibinebenta sa karamihan ng mga parmasya | malapit nang ibenta ang bagong linya ng mga sasakyan
Progress: 0.93
translated_text: sumali siya sa isang golf club | bumuo sila ng isang maliit na lunch society | ang mga lalaking mula sa fraternal order ay magtatrabaho sa soup kitchen ngayon
Progress: 0.93
translated_text: maglagay ng bala sa mesa | idikit ang iyong hinlalaki sa bitak
Progress: 0.93
translated_text: isang malamig na araw ng taglagas | isang cool na silid | cool na mga damit ng tag-init | astig na inumin | malamig na simoy ng hangin
Progress: 0.93
translated_text: i-play ito cool | manatiling cool | nanatiling coolheaded sa krisis | ang pinakawalang kaba na nagwagi sa kasaysayan ng paligsahan
Progress: 0.93
translated_text: ang mga relasyon ay cool at magalang | isang cool na pagtanggap | cool sa ideya ng mas mataas na buwis
Progress: 0.93
translated_text: siya ay isang cool dude | astig yan | Ang ganda talaga ng damit ni Mary | hindi cool na dumating sa isang party ng masyadong maaga
Progress: 0.93
translated_text: mahal niya ang mare at lahat ng kanyang mga kasama | ayaw ng mga kamelyo na iwan ang kanilang mga kapareha
Progress: 0.93
translated_text: nawalan siya ng kapareha sa kanyang sapatos | asul ang isang mata ngunit kayumanggi ang kasama nito
Progress: 0.93
translated_text: Ang katotohanang ito ay isinama sa isa pa | Matchmaker, maaari mo bang ipares ang aking anak sa isang magandang binata? | Ang mag-aaral ay ipinares sa isang kasosyo para sa pakikipagtulungan sa proyekto
Progress: 0.93
translated_text: Ipagluto mo ako ng hapunan, pakiusap | pwede mo ba akong gawan ng omelette? | pakiayos ng almusal para sa mga bisita
Progress: 0.93
translated_text: I-fudge ang mga figure | magluto ng mga aklat | huwad ang data
Progress: 0.93
translated_text: Ang `smog&#39; ay pinaghalong `smoke&#39; at `fog&#39; | Ang `motel&#39; ay isang salitang portmanteau na ginawa sa pamamagitan ng pagsasama-sama ng `motor&#39; at `hotel&#39; | Ang `brunch&#39; ay isang kilalang portmanteau
Progress: 0.93
translated_text: ihalo ang mga mani at pasas | nakikisama siya sa madla | Hindi kami masyadong naghahalo
Progress: 0.93
translated_text: Maghahalo ang lasa na ito sa iyong ulam | Ang sofa na ito ay hindi sasama sa mga upuan
Progress: 0.94
translated_text: kumikilos na salungat sa ating code of ethics | ang mga katotohanan ay tumuturo sa isang salungat na konklusyon
Progress: 0.94
translated_text: Mary Mary medyo salungat | isang matigas na bata na may marahas na ugali | isang masamang kalooban | naliligaw na pag-uugali

Progress: 0.94
translated_text: masamang agos | isang salungat na hangin
Progress: 0.94
translated_text: nagsimula siyang magduda sa katumpakan ng kanyang kumpas | kinuwestiyon ng abogado ang katotohanan ng aking account
Progress: 0.94
translated_text: magiliw na payo | isang magiliw na kapitbahayan | ang tanging palakaibigang tao dito | isang magiliw na host at hostess
Progress: 0.94
translated_text: isang pamahalaang magiliw sa ating mga interes | isang mapayapang kasunduan
Progress: 0.94
translated_text: user-friendly na mga computer | isang patakarang magiliw sa mamimili | isang nobelang madaling mambabasa
Progress: 0.94
translated_text: sa mapagkaibigang teritoryo | siya ay aksidenteng napatay sa pamamagitan ng friendly fire
Progress: 0.94
translated_text: isang masungit na bansa | isang pagalit na pangungusap | masasamang aksyon
Progress: 0.94
translated_text: isang masamang klima | isang hindi kanais-nais na kapaligiran | isang hindi kanais-nais na lupa | ang hindi magiliw na kapaligiran sa matataas na lugar
Progress: 0.94
translated_text: pagalit na pagkuha sa kapangyarihan | pagalit na malambot na alok | pagalit na bid
Progress: 0.94
translated_text: isang batikang manlalakbay | katatagan ng beterano | isang beteranong opisyal
Progress: 0.94
translated_text: Matingkad na asul na panahon ng Oktubre | isang asul na apoy | asul na ulap ng usok ng tabako
Progress: 0.94
translated_text: malungkot sa kakaisip kung ano ang dapat niyang harapin | madilim na mga hula | isang madilim na katahimikan | kinuha ang isang mabangis na pagtingin sa ekonomiya | ang nagdidilim na kalooban | malungkot at asul sa isang kakaibang lungsod | nalulumbay sa pagkawala ng kanyang trabaho | isang dispirited at nagbitiw na ekspresyon sa kanyang mukha | nalulumbay pagkatapos ng kanyang pagkatalo | nakakaramdam ng panghihina ng loob at panghihina ng loob
Progress: 0.94
translated_text: marumi ang bibig at lapastangan | asul na wika | mga salitang bastos
Progress: 0.94
translated_text: isang asul na pelikula | asul na biro | nilaktawan niya ang mga asterisk at binibigyan ka ng mga detalye ng gamy | isang makatas na iskandalo | isang makulit na kindat | malikot na salita | racy anekdota | isang mapanganib na kwento | maanghang na tsismis
Progress: 0.94
translated_text: isang maharlikang pamilya | aristokratikong Bostonians | aristokratikong pamahalaan | isang asul na pamilya | dugong bughaw | ang aristokrasya na may dugong bughaw | ng banayad na dugo | patrician landholders ng American South | aristokratikong tindig | aristokratikong katangian | panlasa ni patrician
Progress: 0.94
translated_text: ang puritan work ethic | puritanic distaste para sa alak | siya ay kahit ano ngunit puritanical sa kanyang pag-uugali
Progress: 0.94
translated_text: isang asul na araw | ang madilim na araw ng digmaan | isang linggo ng maulan na nakababahalang panahon | isang malungkot na tanawin ng taglamig | ang unang malungkot na mga araw ng Nobyembre | isang madilim na madilim na araw | malupit na tag-ulan
Progress: 0.94
translated_text: nag-ping ang sasakyan nang maglagay ako ng low-octane na gasolina | Nag-pink ang kotse nang masyadong malayo ang ignition
Progress: 0.94
translated_text: ang fauna ng China | ang zoology ng Pliocene epoch
Progress: 0.94
translated_text: ito ay isang maliit na ekonomiya upang maglakad sa trabaho araw-araw | may naipon na 50 cents
Progress: 0.94
translated_text: ito ay isang maliit na ekonomiya upang maglakad sa trabaho araw-araw | may naipon na 50 cents
Progress: 0.94
translated_text: trabaho ay ang pagpapalaya ng sangkatauhan | Ang trabaho ng isang surgeon ay ang pagliligtas ng mga buhay
Progress: 0.94
translated_text: Makakatipid ito ng pera | Ililigtas kita sa gulo | Makakatipid ito ng maraming oras
Progress: 0.94
translated_text: Makakatipid ng pera ang hakbang na ito | Ang mga hindi pinalad ay kailangang magtipid ngayon
Progress: 0.94
translated_text: panatilihin ang aking trabaho para sa akin habang ako ay nanganganak | panatilihin ang aking upuan, mangyaring | panatilihing bukas ang posibilidad ng isang pagsasanib
Progress: 0.94
translated_text: ang alpha male sa grupo ng mga chimpanzee | ang alpha star sa isang constellation ay ang pinakamaliwanag o pangunahing bituin
Progress: 0.94
translated_text: isang beta na bersyon | beta software
Progress: 0.94
translated_text: ang Mississippi River delta | ang Nile delta
Progress: 0.94
translated_text: ang kanyang mga hubad na paa ay nakalabas mula sa kanyang pantalon | nakabaluti mula ulo hanggang paa
Progress: 0.94
translated_text: nakapulupot sa paanan ng kama | ang paa ng pahina | ang paa ng listahan | paanan ng bundok
Progress: 0.94
translated_text: ito ay itinayo sa isang base ng solidong bato | tumayo siya sa paanan ng tore
Progress: 0.94
translated_text: sumunod siya sa paglalakad | ang pinakamabilis na paa
Progress: 0.94
translated_text: kunin ang tab | kunin ang pasanin ng mga mortgage na may mataas na interes | ipasa ang kuwenta
Progress: 0.94
translated_text: ang alae ng ilong | ang alae ng buto ng maple | ang mga flat petals ng pea blossom ay alae
Progress: 0.94
translated_text: sa kasamaang palad umulan buong araw | sayang, hindi ako maaaring manatili
Progress: 0.94
translated_text: pinamunuan niya ang isang maliit na brilyante | diamante ay trumps
Progress: 0.94
translated_text: pinamunuan niya ang isang mababang pala | pala ay trumps
Progress: 0.94
translated_text: sa puso mo alam mong totoo | ang kanyang kuwento ay matutunaw ang iyong dibdib
Progress: 0.94
translated_text: siya ay patuloy na lumalaban sa purong spunk | wala kang puso para sa baseball
Progress: 0.94
translated_text: ito ay nasa gitna ng bayan | tumakbo sila pasulong sa puso ng pakikibaka | sila ay nasa mata ng bagyo
Progress: 0.94
translated_text: ang diwa ng argumento ng tagausig | ang puso at kaluluwa ng Republican Party | ang kulit ng kwento
Progress: 0.94
translated_text: nahirapan siyang ipahayag ang pagmamahal na naramdaman | nanalo ang bata sa puso ng lahat | the warmness of his welcome made us feel at home
Progress: 0.94
translated_text: pinamunuan niya ang reyna ng mga puso | puso ay trumps
Progress: 0.94
translated_text: siya ang sisihin dito | ito ay isang bum rap
Progress: 0.94
translated_text: Bumungad sa paningin ang bukid nang lumiko kami sa kanto | Bigla siyang sumulpot out of nowhere
Progress: 0.94
translated_text: i-pop ang pizza sa microwave oven | Isinubo niya ang petit-four sa kanyang bibig
Progress: 0.94
translated_text: Nag-down siya ng tatlong martinis bago kumain | Nakapatay siya ng isang bote ng brandy nang gabing iyon | Uminom sila ng ilang beer pagkatapos ng trabaho
Progress: 0.94
translated_text: Ang lobo ay pumutok | Mabilis na lumalabas ang popcorn na ito sa microwave oven
Progress: 0.95
translated_text: Ang populasyon ng usa sa bayang ito ay umuunlad | umuusbong ang negosyo
Progress: 0.95
translated_text: ang yabang niya ay mas malala pa sa laban niya | sa tuwing nanalo siya ay nalantad kami sa kanyang gasconade
Progress: 0.95
translated_text: pinindot niya ang ilaw | naka-snap paharap ang braso niya
Progress: 0.95
translated_text: Napagtanto niya na pinagtaksilan siya nito | siya ay natagos sa kalungkutan
Progress: 0.95
translated_text: Umaalulong ang hangin sa mga puno | Dumagundong ang tubig sa chute
Progress: 0.95
translated_text: managhoy sa awa sa sarili | humagulgol sa kalungkutan
Progress: 0.95
translated_text: mga instrumental na komposisyon | isang instrumental ensemble
Progress: 0.95
translated_text: magsuklay ng buhok bago maghapunan | suklayin ang lana
Progress: 0.95
translated_text: magsuklay ng buhok bago maghapunan | suklayin ang lana
Progress: 0.95
translated_text: sa mata ng batas | Nagkamali ako sa paningin niya
Progress: 0.95
translated_text: siya ay may mata para sa sariwang talento | may mata siyang artista
Progress: 0.95
translated_text: ito ay nasa gitna ng bayan | tumakbo sila pasulong sa puso ng pakikibaka | sila ay nasa mata ng bagyo
Progress: 0.95
translated_text: Malakas na inalog ng botika ang prasko | Nanginginig ang mga kamay ko
Progress: 0.95
translated_text: ang barko ay tumba | umindayog ang mataas na gusali | Pabalik-balik siya sa kanyang mga paa
Progress: 0.95
translated_text: ang aking pananampalataya ay nayanig | Ang masamang balita ay yumanig sa kanyang pag-asa

Progress: 0.95
translated_text: Ang mga kwentong ito ay yumanig sa komunidad | niyanig ng digmaang sibil ang bansa
Progress: 0.95
translated_text: Napailing siya sa kanyang panaginip | iling ang asin mula sa salt shaker
Progress: 0.95
translated_text: iling ang ulo | Napailing siya sa mga makulit na estudyante | Nakipagkamay ang mga matandang kalaban | Wag mo nga akong i-shake your fist!
Progress: 0.95
translated_text: naglaro sila ng word games | naisip niya ang kanyang pagpipinta bilang isang laro na pumupuno sa kanyang walang laman na oras | masaya at laro ang buhay niya
Progress: 0.95
translated_text: ang laro ay 6 lahat | nagsisilbi siya para sa laro
Progress: 0.95
translated_text: gumawa sila ng pakana para siraan ang gobernador | Nakita ko ang kanyang maliit na laro mula sa simula
Progress: 0.95
translated_text: siya ay nasa laro sa pagtutubero | nasa show biz siya
Progress: 0.95
translated_text: para sa mga artista, hindi laro ang pagsasaulo ng mga linya | para sa kanya, ang buhay ay puro saya at laro
Progress: 0.95
translated_text: Aling kabayo ang iyong sinusuportahan? | Pupusta ako sa bagong kabayo
Progress: 0.95
translated_text: isang baldado na sundalo | isang paa ng laro
Progress: 0.95
translated_text: pinatugtog niya ang unang hiwa sa cd | ang title track ng album
Progress: 0.95
translated_text: ang mga pagtanggal ng editor ay madalas na nakakainis sa mga batang may-akda | magkasundo ang magkabilang panig sa pagtanggal ng iminungkahing sugnay
Progress: 0.95
translated_text: iginiit niya na bigyan namin siya ng huling hiwa bago ang bawat deal | ang pagputol ng mga baraha ay naging isang ritwal
Progress: 0.95
translated_text: ang kanyang mga hiwa ay mahusay | ang kanyang pagputol ng cake ay gumawa ng isang kahila-hilakbot na gulo
Progress: 0.95
translated_text: bawasan ang iyong pang-araw-araw na paggamit ng taba | Gusto ng employer na bawasan ang mga benepisyong pangkalusugan
Progress: 0.95
translated_text: Naputol ang sasakyan sa kaliwa sa intersection | Lumiko sa kanan ang motor
Progress: 0.95
translated_text: maghiwa ng butas | gupitin ang mga kanal | Pinutol ng pawis ang maliliit na agos sa kanyang mukha
Progress: 0.95
translated_text: sumulat ng tseke | putulin ang isang tiket | Mangyaring gawin ang check out sa akin
Progress: 0.95
translated_text: i-edit ang pelikula | gupitin ang recording tape
Progress: 0.95
translated_text: Hindi ko na ito ma-hack | hindi niya maaaring putulin ang mahabang araw sa opisina
Progress: 0.95
translated_text: gupitin ang mga kanta | Pinutol niya muli ang lahat ng kanyang pangunahing titulo
Progress: 0.95
translated_text: gupitin ang isang disk | magsunog ng CD
Progress: 0.95
translated_text: Pinutol ni Wayne | Matagal niyang pinutol ang kubyerta
Progress: 0.95
translated_text: I-off ang stereo, mangyaring | putulin ang makina | patayin ang mga ilaw
Progress: 0.95
translated_text: putulin ang ingay | Kinailangan naming putulin ang usapan
Progress: 0.95
translated_text: halal na karne | isang halal na kusina
Progress: 0.95
translated_text: nagdala sila ng isang malawak na imbentaryo ng hardware | huminto sila sa pagbebenta sa mga eksaktong sukat upang mabawasan ang imbentaryo
Progress: 0.95
translated_text: nag-eksperimento siya sa isang partikular na lahi ng mga puting daga | lumikha siya ng bagong uri ng tupa
Progress: 0.95
translated_text: bromidic sermons | ang kanyang mga pananalita ay walang kabuluhan at karaniwan | hackneyed na mga parirala | isang stock na sagot | paulit-ulit na mga walang kwentang biro | parroting ilang timeworn axiom | ang trite metapora `matigas gaya ng mga pako&#39;
Progress: 0.95
translated_text: isang karaniwang sukat | isang stock item
Progress: 0.95
translated_text: ito ay naging sa aking kalamangan | umaani ng mga gantimpala ng pagkabukas-palad
Progress: 0.95
translated_text: ito ay naging sa aking kalamangan | umaani ng mga gantimpala ng pagkabukas-palad
Progress: 0.95
translated_text: kakulangan ng pondo ay nagresulta sa isang sakuna para sa ating sistema ng paaralan | ang kanyang mga patakaran ay isang kalamidad
Progress: 0.95
translated_text: ang buong lungsod ay naapektuhan ng hindi maaalis na kalamidad | ang lindol ay isang kalamidad
Progress: 0.95
translated_text: Pinagtibay ng lahat ng partido ang kasunduan sa kapayapaan | Napirmahan mo na ba ang iyong kontrata?
Progress: 0.96
translated_text: nagpakita siya ng mga senyales ng strain | tinanggap nila ang mga palatandaan ng tagsibol
Progress: 0.96
translated_text: nabaliktad niya ang polarity ng baterya | mga singil ng kabaligtaran na tanda
Progress: 0.96
translated_text: umaasa siyang isa itong augury | ito ay isang tanda mula sa Diyos
Progress: 0.96
translated_text: Pinirmahan niya ang sulat at ipinadala ito | Mangyaring mag-sign dito
Progress: 0.96
translated_text: Pinagtibay ng lahat ng partido ang kasunduan sa kapayapaan | Napirmahan mo na ba ang iyong kontrata?
Progress: 0.96
translated_text: Pumirma siya para maglaro ng casino noong Disyembre 18 | Pumirma ang soprano para kantahin ang bagong opera
Progress: 0.96
translated_text: Pinirmahan niya ang kanyang hindi pag-apruba gamit ang isang dismissive hand gesture | Sinenyasan ng kainan ang mga waiter na dalhin ang menu
Progress: 0.96
translated_text: lagdaan ang isang intersection | Ang kalsadang ito ay nilagdaan na
Progress: 0.96
translated_text: sinubukan niyang muli | inensayo nila ulit ang eksena
Progress: 0.96
translated_text: Naalarma siya ng bakanteng bahay | Inalerto namin ang mga bagong kapitbahay sa mataas na rate ng pagnanakaw
Progress: 0.96
translated_text: nahuli ng dalawang alertong pulis | sapat na alerto upang makita ang pagkakataon kapag ito ay dumating | palaging alerto at mapagbantay, tulad ng isang sentinel na naka-duty
Progress: 0.96
translated_text: isang mabilis na paglalakad sa parke | isang masiglang lakad | isang masayang paghabol | naglalakbay sa mabilis na bilis | isang mabilis na bilis | isang hampas ng hangin
Progress: 0.96
translated_text: isang alertong isip | alerto sa mga problema | buhay sa kung ano ang nangyayari | gising sa panganib ng kanyang sitwasyon | gising na ngayon sa realidad ng kanyang kalagayan
Progress: 0.96
translated_text: Ipagluto mo ako ng hapunan, pakiusap | pwede mo ba akong gawan ng omelette? | pakiayos ng almusal para sa mga bisita
Progress: 0.96
translated_text: Ihanda ang mga bata para sa paaralan! | maghanda para sa digmaan | Nag-aayos na akong umalis ng bayan pagkatapos kong bayaran ang bill ng hotel
Progress: 0.96
translated_text: humanda | handa na siyang magbitiw | handa nang gumuho ang tulay | Handa na akong magtrabaho | handa na para sa aksyon | handa nang gamitin | ang sopas ay magiging handa sa isang minuto | handang matutong magbasa
Progress: 0.96
translated_text: mukhang may sapat na pera siya | isang handa na mapagkukunan ng pera
Progress: 0.96
translated_text: isang mabilis na pag-iisip | isang handang talino
Progress: 0.96
translated_text: adik siya sa chocolate | nalulong sa cocaine
Progress: 0.96
translated_text: habang may buhay may pag-asa | ang buhay ay nakasalalay sa maraming kemikal at pisikal na proseso
Progress: 0.96
translated_text: ang bawat bata ay inaasahang magbabayad para sa kanilang panatilihin | nag-apply siya sa estado para sa suporta | hindi na niya kayang kumita ng sariling kabuhayan
Progress: 0.96
translated_text: Ang mga tao ay nanirahan sa Africa milyun-milyong taon na ang nakalilipas | Ang mga tao ay naninirahan sa mga isla na ngayon ay desyerto | ang ganitong uri ng isda ay naninirahan malapit sa ilalim ng karagatan | ang mga usa ay naninirahan sa kakahuyan
Progress: 0.96
translated_text: 3 araw kaming walang tubig at pagkain | Ang mga pamahiin na ito ay nabubuhay sa backwaters ng America | Ang driver ng karera ng kotse ay nabuhay sa maraming malubhang aksidente | gaano katagal ang isang tao na walang pagkain at tubig?
Progress: 0.96
translated_text: halos hindi siya maaaring umiral sa gayong mababang sahod | Mabubuhay ka ba sa $2000 sa isang buwan sa New York City? | Maraming tao sa mundo ang kailangang mabuhay ng $1 sa isang araw
Progress: 0.96
translated_text: Ang ating dakilang pinuno ay wala na | Ang aking lolo ay nabuhay hanggang sa katapusan ng digmaan

Progress: 0.96
translated_text: Alam ko ang pakiramdam! | nalaman mo na ba ang gutom? | Nabuhay ako sa isang uri ng impiyerno noong ako ay isang adik sa droga | Ang mga nakaligtas sa holocaust ay nabuhay ng isang bangungot | Nabuhay ako sa dalawang diborsyo
Progress: 0.96
translated_text: siya ay isang buhay na manika | natakot ang buhay na liwanag ng araw sa kanila | talunin ang buhay na impiyerno sa kanya
Progress: 0.96
translated_text: ang Wollemi pine na natagpuan sa Australia ay isang nabubuhay na ispesimen ng isang conifer na inaakalang matagal nang patay at samakatuwid ay kilala bilang isang buhay na fossil | ang tanging nabubuhay na hangganan ng blockhouse sa Pennsylvania
Progress: 0.96
translated_text: ang paglilipat ng mga alyansa sa loob ng isang malaking pamilya | ang kanilang pagkakaibigan ay bumubuo ng isang malakas na ugnayan sa pagitan nila
Progress: 0.96
translated_text: magbigay ng mga kritikal na komento sa lahat ng naroroon | magbigay ng pera | maglabas ng baon para sa mga bata | humarap ng suntok sa isang tao | ang makina ay nagbibigay ng mga soft drink
Progress: 0.96
translated_text: kumalat ng impormasyon | magpakalat ng alingawngaw | i-broadcast ang balita
Progress: 0.96
translated_text: Pinahihintulutan nito ang tubig na dumaloy sa | Ang selyadong pinto na ito ay hindi papayag na pumasok ang tubig sa basement | Papayagan nito ang pag-ulan
Progress: 0.96
translated_text: Pinayagan niya ang kanyang anak na bisitahin ang kanyang nawalay na asawa | Hindi ko hahayaang hanapin ng mga pulis ang kanyang basement | Hindi ako papayag na makita mo ang iyong pagsusulit
Progress: 0.96
translated_text: bigyan ng pahintulot | Si Mandela ay pinahintulutan ng ilang bisita sa bilangguan
Progress: 0.96
translated_text: Itatalaga ko ang perang ito para sa iyong pananaliksik | Naglalaan siya ng oras para sa pagmumuni-muni araw-araw
Progress: 0.96
translated_text: Hindi ito nag-iiwan ng puwang para sa pagpapabuti | Ang ebidensya ay nagpapahintulot lamang ng isang konklusyon | payagan ang mga pagkakamali | mag-iwan ng maraming oras para sa biyahe | Ang pamamaraang ito ay nagbibigay ng maraming pahinga
Progress: 0.96
translated_text: Pinapayagan ko ang posibilidad na ito | Ang mananahi ay nagplano para sa 5% pag-urong pagkatapos ng unang hugasan
Progress: 0.96
translated_text: Ang problemang ito ay umamin ng walang solusyon | Ang maikling kwentong ito ay nagbibigay-daan sa iba&#39;t ibang interpretasyon
Progress: 0.96
translated_text: Hindi namin pinapayagan ang mga aso dito | Ang mga bata ay hindi pinahihintulutan na lampas sa puntong ito | Hindi natin matitiis ang paninigarilyo sa ospital
Progress: 0.96
translated_text: Pinahihintulutan nito ang tubig na dumaloy sa | Ang selyadong pinto na ito ay hindi papayag na pumasok ang tubig sa basement | Papayagan nito ang pag-ulan
Progress: 0.96
translated_text: Pinayagan niya ang kanyang anak na bisitahin ang kanyang nawalay na asawa | Hindi ko hahayaang hanapin ng mga pulis ang kanyang basement | Hindi ako papayag na makita mo ang iyong pagsusulit
Progress: 0.96
translated_text: bigyan ng pahintulot | Si Mandela ay pinahintulutan ng ilang bisita sa bilangguan
Progress: 0.96
translated_text: Itatalaga ko ang perang ito para sa iyong pananaliksik | Naglalaan siya ng oras para sa pagmumuni-muni araw-araw
Progress: 0.96
translated_text: Hindi ito nag-iiwan ng puwang para sa pagpapabuti | Ang ebidensya ay nagpapahintulot lamang ng isang konklusyon | payagan ang mga pagkakamali | mag-iwan ng maraming oras para sa biyahe | Ang pamamaraang ito ay nagbibigay ng maraming pahinga
Progress: 0.96
translated_text: Pinapayagan ko ang posibilidad na ito | Ang mananahi ay nagplano para sa 5% pag-urong pagkatapos ng unang hugasan
Progress: 0.96
translated_text: Ang problemang ito ay umamin ng walang solusyon | Ang maikling kwentong ito ay nagbibigay-daan sa iba&#39;t ibang interpretasyon
Progress: 0.96
translated_text: Hindi namin pinapayagan ang mga aso dito | Ang mga bata ay hindi pinahihintulutan na lampas sa puntong ito | Hindi natin matitiis ang paninigarilyo sa ospital
Progress: 0.96
translated_text: Ang dalawang kalye ay nagkokonekta upang maging isang highway | Nagsanib ang aming mga landas | Muling nag-link ang mga manlalakbay sa airport
Progress: 0.96
translated_text: ang trabaho ay (lamang) tapos na | halos tulog na ang sanggol nang tumunog ang alarm | malapit na tayong matapos | pinatakbo siya pababa ng kotse | muntik na siyang mawalan ng malay | nakipag-usap nang halos 2 oras | ang recording ay halos perpekto | halos lahat ng partido ay pumirma sa kontrata | Malapit na akong mapagod sa pagtakbo | karamihan ay sumasang-ayon
Progress: 0.96
translated_text: iparada ang sasakyan sa bakuran | iparada ang mga bata sa mga in-laws | iparada ang iyong bag sa locker na ito
Progress: 0.96
translated_text: Iparada ang sasakyan sa harap ng aklatan | Pwede ka bang mag park dito?
Progress: 0.97
translated_text: nagsimula siyang maghanap ng gasolinahan | huminto ang tren sa istasyon
Progress: 0.97
translated_text: lumampas siya sa kanyang pwesto | ang mga responsibilidad ng isang lalaki sa kanyang istasyon | kasal sa itaas ng kanyang istasyon
Progress: 0.97
translated_text: isang sundalo ang namamahala sa entrance post | isang istasyon ng bantay
Progress: 0.97
translated_text: nagsimula siyang maghanap ng gasolinahan | huminto ang tren sa istasyon
Progress: 0.97
translated_text: lumampas siya sa kanyang pwesto | ang mga responsibilidad ng isang lalaki sa kanyang istasyon | kasal sa itaas ng kanyang istasyon
Progress: 0.97
translated_text: isang sundalo ang namamahala sa entrance post | isang istasyon ng bantay
Progress: 0.97
translated_text: nag-iisa siya sa larangan ng microbiology | ang teoryang ito ay lubos na nag-iisa sa pagtagos nito sa problema | Kakaiba si Bach sa kanyang paghawak ng counterpoint | craftsmen na ang husay ay walang kapantay | walang kapantay na kakayahan sa palakasan | isang pagkasira ng batas na walang kapantay sa ating kasaysayan
Progress: 0.97
translated_text: isang natatanging halimbawa | ang natatanging umiiral na halimbawa ng sulat-kamay ni Donne | isang natatanging kopya ng isang sinaunang manuskrito | may mga natatanging solusyon ang ilang uri ng problema
Progress: 0.97
translated_text: nagsalita nang may kakaibang accent | nagkaroon ng kakaibang kakayahan sa paglikom ng pondo | isang prangka na natatangi sa panitikan | kakaibang karanasan sa kainan
Progress: 0.97
translated_text: nag-ulat siya ng ilang hindi kilalang tawag | tumawag siya sa London | narinig niyang nagri-ring ang phone pero ayaw niyang sagutin ang tawag
Progress: 0.97
translated_text: hindi na tumatawag sa hapon ang mga asawa ng senior professors sa mga bagong dating | ang mga tauhan sa mga nobela ni Henry James ay walang hanggang tawag sa isa&#39;t isa, kadalasan sa parlor ng ilang tirahan
Progress: 0.97
translated_text: maraming tawag para sa mga kwentong Pasko | hindi maraming tawag para sa buggywhips
Progress: 0.97
translated_text: ang panawagan ng pastor sa kanyang mga parokyano | tawag ng tindero sa isang customer
Progress: 0.97
translated_text: Pinangalanan nila ang kanilang anak na David | Ang bagong paaralan ay ipinangalan sa sikat na pinuno ng Civil Rights
Progress: 0.97
translated_text: Tinawag niya akong bastard | Tinawag niyang tamad at walang utang na loob ang kanyang mga anak
Progress: 0.97
translated_text: Sinubukan kitang tawagan buong gabi | Kumuha ng dalawang aspirin at tawagan ako sa umaga
Progress: 0.97
translated_text: napaiyak siya sa sakit nang ipasok ng doktor ang karayom | Sigaw ko sa kanya mula sa bintana pero hindi niya ako narinig
Progress: 0.97
translated_text: Siya ay tinawag sa opisina ng direktor | Tumawag ng pulis!
Progress: 0.97
translated_text: Ang Wannsee Conference ay tinawag upang talakayin ang `Final Solution&#39; | Ang bagong dean ay tumatawag ng mga pagpupulong bawat linggo
Progress: 0.97
translated_text: Tumatawag si Hawaii! | Isang transmiter sa Samoa ang narinig na tumatawag
Progress: 0.97
translated_text: Lagi niya akong tinatawag ng `Sir&#39; | Tawagin mo akong Mister | Tinatawag niya ito sa unang pangalan
Progress: 0.97
translated_text: 4 na beses na siyang tinawag para sa tungkulin ng hurado | Tinawag nila siya sa aktibong tungkuling militar

Progress: 0.97
translated_text: Tinawag niya ang pangalan ko | Tinawag ng auctioneer ang mga bid
Progress: 0.97
translated_text: ang pagbabago ay nilayon upang mapataas ang mga benta | ang bagyong ito ay tiyak na isang pagbabago para sa mas masahol pa | ang kapitbahayan ay sumailalim sa ilang mga pagbabago mula noong huling pagbisita niya mga taon na ang nakakaraan
Progress: 0.97
translated_text: ang pagbabago ng pamahalaan ay walang epekto sa ekonomiya | ang kanyang pagbabago sa aborsyon ay nagdulot sa kanya ng halalan
Progress: 0.97
translated_text: may mga markadong pagbabago sa lining ng baga | walang pagbabago sa mga bundok
Progress: 0.97
translated_text: pumunta siya sa France para sa variety | ito ay isang nakakapreskong pagbabago upang makilala ang isang babaeng mekaniko
Progress: 0.97
translated_text: Maaaring binago ng pagdating ng sasakyan ang pattern ng paglago ng lungsod | Binago ng talakayan ang aking pag-iisip tungkol sa isyu
Progress: 0.97
translated_text: Siya ay ganap na nagbago habang siya ay tumanda | Nagbago ang panahon kagabi
Progress: 0.97
translated_text: nagbabago ang kanyang kalooban alinsunod sa panahon | Ang pagpili ng mga gulay sa supermarket ay nag-iiba ayon sa panahon
Progress: 0.97
translated_text: lumipat sa ibang brand ng beer | Nagpalit siya ng mga psychiatrist | Nagpalit ng lane ang sasakyan
Progress: 0.97
translated_text: Maaari mo bang i-convert ang aking mga dolyar sa pounds? | Binago niya ang kanyang pangalan | i-convert ang sentimetro sa pulgada | i-convert ang mga hawak sa pagbabahagi
Progress: 0.97
translated_text: Papalitan mo ba ako ng pwesto? | Isang taon na kaming nagpapalitan ng sulat
Progress: 0.97
translated_text: Nagsimulang magbago ang kanyang boses noong siya ay 12 taong gulang | Lumalim ang boses niya nang ibulong niya ang password
Progress: 0.97
translated_text: Kailangang matutunan ni Itay kung paano baguhin ang sanggol | Pagkatapos ng bawat bisita ay pinalitan namin ang mga bed linen
Progress: 0.97
translated_text: ang pagbabago ay nilayon upang mapataas ang mga benta | ang bagyong ito ay tiyak na isang pagbabago para sa mas masahol pa | ang kapitbahayan ay sumailalim sa ilang mga pagbabago mula noong huling pagbisita niya mga taon na ang nakakaraan
Progress: 0.97
translated_text: ang pagbabago ng pamahalaan ay walang epekto sa ekonomiya | ang kanyang pagbabago sa aborsyon ay nagdulot sa kanya ng halalan
Progress: 0.97
translated_text: may mga markadong pagbabago sa lining ng baga | walang pagbabago sa mga bundok
Progress: 0.97
translated_text: pumunta siya sa France para sa variety | ito ay isang nakakapreskong pagbabago upang makilala ang isang babaeng mekaniko
Progress: 0.97
translated_text: Maaaring binago ng pagdating ng sasakyan ang pattern ng paglago ng lungsod | Binago ng talakayan ang aking pag-iisip tungkol sa isyu
Progress: 0.97
translated_text: Siya ay ganap na nagbago habang siya ay tumanda | Nagbago ang panahon kagabi
Progress: 0.97
translated_text: nagbabago ang kanyang kalooban alinsunod sa panahon | Ang pagpili ng mga gulay sa supermarket ay nag-iiba ayon sa panahon
Progress: 0.97
translated_text: lumipat sa ibang brand ng beer | Nagpalit siya ng mga psychiatrist | Nagpalit ng lane ang sasakyan
Progress: 0.97
translated_text: Maaari mo bang i-convert ang aking mga dolyar sa pounds? | Binago niya ang kanyang pangalan | i-convert ang sentimetro sa pulgada | i-convert ang mga hawak sa pagbabahagi
Progress: 0.97
translated_text: Papalitan mo ba ako ng pwesto? | Isang taon na kaming nagpapalitan ng sulat
Progress: 0.97
translated_text: Nagsimulang magbago ang kanyang boses noong siya ay 12 taong gulang | Lumalim ang boses niya nang ibulong niya ang password
Progress: 0.97
translated_text: Kailangang matutunan ni Itay kung paano baguhin ang sanggol | Pagkatapos ng bawat bisita ay pinalitan namin ang mga bed linen
Progress: 0.97
translated_text: ang naglilinis na babae ay darating sa kahaliling Miyerkules | jam tuwing ibang araw
Progress: 0.97
translated_text: i-calibrate ang isang instrumento | nagtapos ng isang silindro
Progress: 0.97
translated_text: Iniisip ko kung ito ba ang tamang gawin | Iniisip niya kung magi-snow ba ngayong gabi
Progress: 0.98
translated_text: gulat sa stock market | isang takot sa digmaan | isang bomb scare ang nagbunsod sa kanila upang lumikas sa gusali
Progress: 0.98
translated_text: Ang estranghero na tumatambay sa paligid ng gusali ay natatakot sa akin | Hindi siya kailanman matatakot ng mga multo
Progress: 0.98
translated_text: Gusto ko nang umuwi | Gusto ko ng sarili kong kwarto
Progress: 0.98
translated_text: Nagtitiwala ako na magiging mas mahusay ka mula ngayon | Sana maintindihan niya na hindi siya makakaasa ng pagtaas
Progress: 0.98
translated_text: Siya ay inaangkin na hindi kailanman nanaginip | Nanaginip siya ng kakaibang eksena
Progress: 0.98
translated_text: isang marahas na pag-atake | isang marahas na tao | marahas na damdamin | isang marahas na galit | nakaramdam ng marahas na ayaw
Progress: 0.98
translated_text: isang marahas na sagupaan ng mga kulay | ang kanyang damit ay isang marahas na pula | isang marahas na ingay | ligaw na kulay | ligaw na sigaw
Progress: 0.98
translated_text: mabangis na katapatan | sa nakakaiyak na galit | matinding ayaw | marahas na hilig
Progress: 0.98
translated_text: nagsusulat ng mapupulang mga gawa at barbaric na araw | fann&#39;d sa pamamagitan ng Conquest&#39;s crimson wing | nanginginig sa pulang galit
Progress: 0.98
translated_text: isang interesadong madla | interesado sa sports | ay interesadong marinig ang tungkol sa kanyang pamilya | interesadong malaman kung sino ang nasa telepono | interesadong mga manonood
Progress: 0.98
translated_text: isang memorandum sa mga kinauukulan | isang negosyo kung saan tatlong lalaki ang nababahala | mga kadahilanan na nababahala sa pagtaas at pagbaba ng mga epidemya | nagpulong ang mga interesadong partido upang pag-usapan ang negosyo
Progress: 0.98
translated_text: Naghalikan ang bagong kasal | Hinalikan niya sa noo ang lolo pagkapasok niya sa kwarto
Progress: 0.98
translated_text: matapat na abogado | matapat na pag-uulat
Progress: 0.98
translated_text: isang maaasahang manggagawa | isang matapat na nagtatrabaho matigas | isang maaasahang sourceSFLe ng impormasyon | siya ay tapat sa kanyang salita | Magiging totoo ako dahil may mga nagtitiwala sa akin
Progress: 0.98
translated_text: nagtrabaho sa isang matapat na kalakalan | magandang tapat na pagkain
Progress: 0.98
translated_text: nagbigay ng matapat na mga sagot | matapat na pag-uulat
Progress: 0.98
translated_text: isang tapat na sahod | isang makatarungang sentimos
Progress: 0.98
translated_text: matanda na ang kanyang ina | isang hinog na katandaan | Ilang taon ka na?
Progress: 0.98
translated_text: lumang tradisyon | lumang bahay | lumang alak | lumang bansa | lumang pagkakaibigan | lumang pera
Progress: 0.98
translated_text: magandang matandang lalaki | parehong lumang kwento
Progress: 0.98
translated_text: isang matandang nagkasala | ang matatandang sundalo
Progress: 0.98
translated_text: dating kaibigan | ating dating kaluwalhatian | ang dating kabisera ng estado | kanyang quondam lover
Progress: 0.98
translated_text: isang tunay na honest-to-god live cowboy | nagkaroon kami ng isang mataas na lumang panahon | umakyat sa ilog upang tumingin sa isang siguradong gulong ng isda
Progress: 0.98
translated_text: Ang Old English ay tinatawag ding Anglo Saxon | Ang Old High German ay High German mula sa kalagitnaan ng ika-9 hanggang sa katapusan ng ika-11 siglo
Progress: 0.98
translated_text: ang dating may-ari | mas malaki ang dati kong bahay
Progress: 0.98
translated_text: isang liham ng paalala tungkol sa mga panganib ng imoralidad | ang babala ay mag-ingat sa mga sorpresa | ang kanyang huling salita ng payo ay huwag makipaglaro sa mga posporo
Progress: 0.98
translated_text: nagbigay sila ng kaunting babala sa kanilang pagdating | mayroon lamang siyang apat na araw na babala bago umalis sa Berlin
Progress: 0.98
translated_text: Binalaan siya ng direktor na maaaring matanggal sa trabaho | Binalaan ako ng doktor tungkol sa mga panganib ng paninigarilyo
Progress: 0.98
translated_text: Binalaan ko siya na huwag masyadong lumayo | Binabalaan kita laban sa mga maling pagpapalagay | Binalaan siya nito na tumahimik

Progress: 0.98
translated_text: umiling sa kanya ang isang monitory finger | isang huwarang sentensiya ng kulungan
Progress: 0.98
translated_text: Anong oras aalis ang iyong tren? | Hindi siya umalis hanggang hatinggabi | Aalis ang barko sa hatinggabi
Progress: 0.98
translated_text: Nag-iwan siya ng gulo nang lumipat siya | Sa wakas ay iniwan siya ng kanyang suwerte | iniwan siya ng kanyang asawa pagkatapos ng 20 taong pagsasama | umiiyak siya sa pag-aakalang siya ay naiwan
Progress: 0.98
translated_text: Ang inflation ay nag-iwan sa kanila na walang pera | Hindi kami nakaimik dahil sa sinabi ng pangulo
Progress: 0.98
translated_text: iwanan ito bilang ay | pabayaan ang batang usa | iwanan ang mga bulaklak na nakikita mo sa parke
Progress: 0.98
translated_text: umalis ng kwarto | umalis ng bansa ang takas
Progress: 0.98
translated_text: Hindi ito nag-iiwan ng puwang para sa pagpapabuti | Ang ebidensya ay nagpapahintulot lamang ng isang konklusyon | payagan ang mga pagkakamali | mag-iwan ng maraming oras para sa biyahe | Ang pamamaraang ito ay nagbibigay ng maraming pahinga
Progress: 0.98
translated_text: Nag-iwan ng marka ang tubig sa damit na sutla | Nag-iwan ng mantsa ang dugo niya sa napkin
Progress: 0.98
translated_text: Gusto niyang umalis | Umalis ng bahay ang binatilyo | Iniwan niya ang kanyang posisyon sa Red Cross | Umalis siya sa Senado pagkaraan ng dalawang termino | pagkatapos ng 20 taon sa parehong kumpanya, siya ay nakakuha ng mga pusta
Progress: 0.98
translated_text: Ipinaubaya niya ang desisyon sa kanyang kinatawan | iwanan ang iyong anak sa pangangalaga ng nars
Progress: 0.98
translated_text: Ipinamana sa akin ng aking tiyahin ang lahat ng kanyang alahas | Iniwan sa akin ng aking lolo ang kanyang buong ari-arian
Progress: 0.98
translated_text: Naiwan kaming apat | 19 bawas 8 dahon 11
Progress: 0.98
translated_text: Iniwan niya ang anim na anak | Sa kanyang pagkamatay, iniwan niya ang kanyang asawa at 11 pusa
Progress: 0.98
translated_text: magbigay ng lihim sa mga Ruso | iwanan ang iyong pangalan at tirahan dito | magbigay ng bagong kasanayan sa mga mag-aaral
Progress: 0.98
translated_text: Nakalimutan ko yung payong ko sa restaurant | Iniwan ko ang susi ko sa loob ng sasakyan at ni-lock ang pinto
Progress: 0.98
translated_text: kaliwang kamay ko | kaliwang gitnang field | ang kaliwang pampang ng isang ilog ay nasa iyong kaliwang bahagi kapag nakaharap ka sa ibaba ng agos
Progress: 0.98
translated_text: natirang meatloaf | may natira siyang kaunting pera kaya nanood siya ng sine | ilang kakaibang dolyar ang natitira | na-save ang natitirang mga sandwich para sa hapunan | hindi nagastos na mga probisyon
Progress: 0.98
translated_text: tumingin siya sa kanan at kaliwa | ang partidong pampulitika ay lumipat sa kaliwa
Progress: 0.98
translated_text: ang nag-iisang doktor sa buong county | isang malungkot na pine | nag-iisang anak | ang nag-iisang tagapagmana | ang tanging halimbawa | isang nag-iisang halimbawa ng duwag | isang nag-iisang batik sa langit
Progress: 0.98
translated_text: siya lang ang naniwala sa kanya | hindi mabubuhay sa tinapay lamang | Makukuha ko ang kotse na ito at ang kotse na ito lamang
Progress: 0.98
translated_text: Nagtatanong lang ako | ito ay isang bagay lamang ng oras | isang scratch lang | siya ay isang bata lamang | sana tumagal iyon ngunit sandali
Progress: 0.99
translated_text: ay ganap na sisihin | isang paaralan na ganap na nakatuon sa mga pangangailangan ng mga batang may problema | siya ay nagtatrabaho para kay Mr. Smith eksklusibo | ginawa ito para lamang sa pera | ang pasanin ng patunay ay nakasalalay sa prosekusyon lamang | isang pribilehiyong ipinagkaloob lamang sa kanya
Progress: 0.99
translated_text: Siya ay dumating lamang upang mahanap ang kanyang asawa patay | Nanalo kami para matalo ulit sa susunod na round
Progress: 0.99
translated_text: Nagsimula kaming magtrabaho sa madaling araw | Sino ang magsisimula? | Magtrabaho kaagad sa pagsikat ng araw! | Nagsimulang dumating ang mga unang turista sa Cambodia | Nagsimula siya sa madaling araw | Bumaba na tayo sa trabaho
Progress: 0.99
translated_text: Nagsimula ang US ng digmaan sa Gitnang Silangan | Nagsimula ang mga Iraqi ng labanan | magsimula ng bagong kabanata sa iyong buhay
Progress: 0.99
translated_text: Nagsisimula ang DMZ sa ibabaw mismo ng burol | Magsisimula ang ikalawang kilusan pagkatapos ng Allegro | Ang mga presyo para sa mga bahay na ito ay nagsisimula sa $250,000
Progress: 0.99
translated_text: Nagsimula siya ng bagong programa | Magsimula ng isang pundasyon
Progress: 0.99
translated_text: Sino ang nagsimula ng kumpanyang ito? | Nagsimula kami sa isang kapana-panabik na negosyo | Sinisimulan ko ang aking araw sa masarap na almusal | Sinimulan namin ang bagong semestre | Ang sesyon sa hapon ay magsisimula sa 4 PM | Nagsimula ang pagdanak ng dugo nang maglunsad ng sorpresang pag-atake ang mga partisan
Progress: 0.99
translated_text: Hindi namin ma-start ang makina | simulan ang computer
Progress: 0.99
translated_text: Magsisimula ako ng alas otso ng umaga | Ready, set, go!
Progress: 0.99
translated_text: Kumuha ng posisyon | magsimula ng bagong trabaho
Progress: 0.99
translated_text: Nagsimula ang nobela sa isang pagpatay | Nagsisimula ang aking ari-arian sa tatlong puno ng maple | Ang kanyang araw ay nagsisimula sa isang pag-eehersisyo | Nagsisimula ang semestre sa isang convocation ceremony
Progress: 0.99
translated_text: magsimula ng tabako | Sinimulan niya ang sabaw habang mainit pa | Nagsimula kami sa physics noong ika-10 baitang
Progress: 0.99
translated_text: isang kondisyon (o estado) ng pagkasira | ang kasalukuyang katayuan ng negosasyon sa armas
Progress: 0.99
translated_text: isang kondisyon sa puso | isang kondisyon ng balat
Progress: 0.99
translated_text: itinakda ng kontrata ang mga kondisyon ng pag-upa | ang mga tuntunin ng kasunduan ay mapagbigay
Progress: 0.99
translated_text: Dapat disiplinahin ng mga magulang ang kanilang mga anak | Sinanay ba ang asong ito?
Progress: 0.99
translated_text: Nakasaad sa testamento na maaari siyang manirahan sa bahay habang buhay | Ang kontrata ay nagtatakda ng mga petsa ng mga pagbabayad
Progress: 0.99
translated_text: nakuha niya sa isang kahila-hilakbot na ayusin | gumawa siya ng kaguluhan sa kanyang kasal
Progress: 0.99
translated_text: Inayos niya ang kanyang TV set | Pakiayos ang sapatos ko
Progress: 0.99
translated_text: ikabit ang lock sa pinto | napako ang tingin niya sa lalaki
Progress: 0.99
translated_text: ayusin ang mga variable | tukuyin ang mga parameter
Progress: 0.99
translated_text: Ipagluto mo ako ng hapunan, pakiusap | pwede mo ba akong gawan ng omelette? | pakiayos ng almusal para sa mga bisita
Progress: 0.99
translated_text: Makukuha natin sila! | Maaayos siya niyan! | This time nakuha ko na siya
Progress: 0.99
translated_text: Ipinatong niya ang kanyang kamay sa kanyang balikat | ilagay ang maleta sa bangko | ituon ang iyong mga mata sa lugar na ito
Progress: 0.99
translated_text: Ihanda ang mga bata para sa paaralan! | maghanda para sa digmaan | Nag-aayos na akong umalis ng bayan pagkatapos kong bayaran ang bill ng hotel
Progress: 0.99
translated_text: tumagal ng dalawang stroke para makalabas sa bunker | ang isang magandang shot ay nangangailangan ng magandang balanse at tempo | iniwan niya ako ng halos imposibleng shot
Progress: 0.99
translated_text: siya ay isang crack shot | isang mahinang tagabaril
Progress: 0.99
translated_text: ang kanyang parting shot ay `drop dead&#39; | she threw shafts of sarcasm | sinusubuan niya ako tuwing may pagkakataon
Progress: 0.99
translated_text: ang aking mga snapshot ay hindi pa nabubuo | sinubukan niyang kumuha ng unposed shots ng mga kaibigan niya
Progress: 0.99
translated_text: siya ay nagpapagaling pa mula sa isang pagbaril sa kanyang binti | Sinalo ko siya ng solid shot sa baba
Progress: 0.99
translated_text: ibinigay niya ang kanyang pinakamahusay na pagbaril | kumuha siya ng saksak sa pagtataya
Progress: 0.99
translated_text: kumuha ng eksena | mag-shoot ng pelikula
Progress: 0.99
translated_text: Nasira ang sasakyan sa kalye | Pumasok siya sa opisina ko
Progress: 0.99
translated_text: shoot craps | shoot ng golf ball

Progress: 0.99
translated_text: Kinuhanan ko ng litrato ang pinangyarihan ng aksidente | Kumuha siya ng larawan ng Pangulo
Progress: 0.99
translated_text: shoot ng basket | shoot ng goal
Progress: 0.99
translated_text: nababagong taffeta | chatoyant (o shot) silk | isang tutubi ang lumipad, nanginginig at nagliliyab
Progress: 0.99
translated_text: nakatakas siya sa mental hospital | nakatakas ang kanaryo sa hawla nito | ang kanyang paglipad ay isang indikasyon ng kanyang pagkakasala
Progress: 0.99
translated_text: isang flight ng magarbong | paglipad ng retorika | paglipad ng imahinasyon
Progress: 0.99
translated_text: sila fumbled sa paligid sa ganap na kadiliman | sa dilim ng gabi
Progress: 0.99
translated_text: Pinaitim ng usok ang kisame | Umitim ang kisame
Progress: 0.99
translated_text: itim na katad na mga jacket | kasing itim ng karbon | mayamang itim na lupa
Progress: 0.99
translated_text: itim na hitsura | itim na salita
Progress: 0.99
translated_text: ang kinabukasan ay nagmukhang itim | ang mga prospect ay malungkot | Ang buhay sa Aran Islands ay palaging madilim at mahirap | kumuha ng malabong pagtingin sa mga bagay-bagay
Progress: 0.99
translated_text: itim na gawa | isang itim na kasinungalingan | ang kanyang itim na puso ay gumawa ng isa pang itim na gawa | Darth Vader ng madilim na bahagi | isang madilim na layunin | dark undercurrents ng etnikong poot | ang pakana ng ilang masasamang katalinuhan na nakabaluktot na parusahan siya
Progress: 0.99
translated_text: bumagsak ang stock market noong Black Friday | isang mapaminsalang pagkatalo | ang labanan ay isang mapaminsalang pagtatapos sa isang mapaminsalang kampanya | ang gayong mga doktrina, kung totoo, ay ganap na nakamamatay sa aking teorya | nakamamatay ang pumasok sa anumang digmaan nang walang pagnanais na manalo dito | isang nakamamatay na pagkakamali
Progress: 0.99
translated_text: isang itim na gabing walang buwan | sa pamamagitan ng napakaitim na kagubatan | ito ay napakadilim sa cellar
Progress: 0.99
translated_text: itim na katatawanan | isang mabangis na biro | mabangis na tawa | masaya mula sa slapstick clowning ... sa savage mordant wit
Progress: 0.99
translated_text: Ang tao...ay nagsulat ng isa sa kanyang pinakamaitim na mga tala bilang isang maninira sa mga isla ng karagatan | isang kahiya-hiyang pag-urong | kasuklam-suklam na pagkatalo | isang opprobrobyong monumento sa kasakiman ng tao | isang nakakahiyang pagpapakita ng kaduwagan
Progress: 0.99
translated_text: may itim na paa mula sa paglalaro sa labas | ang kanyang kamiseta ay itim sa loob ng isang oras
Progress: 1.00
translated_text: isang napaka natural na pag-unlad | ating likas na kapaligiran | likas na agham | likas na yaman | natural na bangin | natural na phenomena
Progress: 1.00
translated_text: isang natural na perlas | natural na gas | natural na seda | natural na blonde na buhok | isang natural na pampatamis | mga likas na pataba
Progress: 1.00
translated_text: ito ay natural na mangyari | natural na kaligtasan sa sakit | likas na pagmamahal ng isang lolo&#39;t lola sa isang apo
Progress: 1.00
translated_text: isang natural na sukat | B natural
Progress: 1.00
translated_text: natural na pag-ayaw ng pusa sa tubig | Ang pag-aalay ng tulong ay likas na gaya ng paghinga
Progress: 1.00
translated_text: natural na yogurt | natural na ani | hilaw na lana | hilaw na asukal | bales ng bastos na bulak
Progress: 1.00
translated_text: isang likas na pinuno | isang ipinanganak na musikero | isang likas na talento
Progress: 1.00
translated_text: isang parang buhay na pose | isang natural na reaksyon
Progress: 1.00
translated_text: sa wakas nalaman niya ang katotohanan | ang totoo ay ayaw niyang gawin iyon
Progress: 1.00
translated_text: pinagtatalunan nila ang katotohanan ng panukala | ang sitwasyon ay nag-uwi sa atin ng tahasang katotohanan ng pagbabanta ng militar | sikat siya sa katotohanan ng kanyang mga larawan | bumaling siya sa relihiyon sa kanyang paghahanap ng walang hanggang katotohanan
Progress: 1.00
translated_text: sinabi niya ang totoo | naisipan niyang sumagot ng totoo pero alam niyang hindi sila maniniwala
Progress: 1.00
translated_text: nagsimula siyang magduda sa katumpakan ng kanyang kumpas | kinuwestiyon ng abogado ang katotohanan ng aking account
Progress: 1.00
translated_text: ang kanyang pagiging masayahin | isang masayang bati | isang masayang silid | kasing saya ng sinumang nakakulong sa kama sa ospital
Progress: 1.00
translated_text: Dapat mong malampasan ang lahat ng paghihirap | talunin ang iyong mga kaaway | Daig niya ang pagiging mahiyain | Napagtagumpayan niya ang kanyang kahinaan | Lalong lumakas ang galit niya at sumabog siya
Progress: 1.00
translated_text: pumatay ng galaw | binatukan niya ang proposal ng estudyante
Progress: 1.00
translated_text: nabigo ang mga inaasahan at nabigo ang mga ambisyon | ang kanilang naudlot na pagtatangka upang makuha ang Calai | maraming bigong makata ang nagtatapos bilang mga gurong naninigarilyo sa tubo | ang kanyang pinakamahusay na pagsisikap ay nabigo
Progress: 1.00
translated_text: isang cute na bata na may pigtails | isang cute na maliit na apartment | tusong kuting | isang tusong sanggol
Progress: 1.00
translated_text: ang mga tusong lalaki ay madalas pumasa para sa matalino | malalim na mga pakana sa pulitika | isang foxy scheme | isang makinis na iwas na sagot | tuso bilang isang soro | nakakalito Dick | isang tusong matandang abogado
Progress: 1.00
translated_text: isang matalinong gadget | ang mga tusong maniobra na humahantong sa kanyang tagumpay | isang mapanlikhang solusyon sa problema
Progress: 1.00
translated_text: ang kahina-hinala ng kanyang pag-angkin | walang tanong tungkol sa bisa ng negosyo
Progress: 1.00
translated_text: Duda ako sa mga ulat na ito | Pinaghihinalaan ko ang kanyang tunay na motibo | wala siyang tiwala sa kanyang madrasta
Progress: 1.00
translated_text: Ang pagpili ay pinaliit | Ang daan ay makitid
Progress: 1.00
translated_text: isang makipot na tulay | isang makitid na linya sa buong pahina
Progress: 1.00
translated_text: isang makinang ngunit makitid ang isip na hukom | makitid na opinyon
Progress: 1.00
translated_text: napanalunan ng makitid na margin | isang makitid na pagtakas
Progress: 1.00
translated_text: isang minutong inspeksyon sa mga bakuran | isang makitid na pagsusuri | isang eksaktong at minutong ulat

,word,synset_id,gloss,eng_text,fil_text
0,sober,grave.s.01,dignified and somber in manner or character an...,a grave God-fearing man | a quiet sedate natur...,isang libingan na may takot sa Diyos | isang t...
1,sober,drab.s.02,lacking brightness or color; dull,drab faded curtains | sober Puritan grey | chi...,kupas kupas na mga kurtina | matino Puritan gr...
2,well,well.v.01,"come up, as of a liquid",Tears well in her eyes | the currents well up,Maluha-luha sa kanyang mga mata | lumalakas an...
3,well,well.a.01,in good health especially after having suffere...,appears to be entirely well | the wound is nea...,mukhang ganap na maayos | ang sugat ay halos m...
4,well,good.s.13,resulting favorably,it's a good thing that I wasn't there | it is ...,buti na lang wala ako | buti naman nanatili ka...
...,...,...,...,...,...
5018,narrow,narrow.v.01,make or become more narrow or restricted,The selection was narrowed | The road narrowed,Ang pagpili ay pinaliit | Ang daan ay makitid
5019,narrow,narrow.a.01,not wide,a narrow bridge | a narrow line across the page,isang makipot na tulay | isang makitid na liny...
5020,narrow,narrow-minded.a.02,lacking tolerance or flexibility or breadth of...,a brilliant but narrow-minded judge | narrow o...,isang makinang ngunit makitid ang isip na huko...
5021,narrow,narrow.a.04,very limited in degree,won by a narrow margin | a narrow escape,napanalunan ng makitid na margin | isang makit...
5022,narrow,minute.s.02,characterized by painstaking care and detailed...,a minute inspection of the grounds | a narrow ...,isang minutong inspeksyon sa mga bakuran | isa...

In [9]:
res.head()

,synset_id,gloss,eng_text,fil_text
eng_word,,,,
sober,grave.s.01,dignified and somber in manner or character an...,a grave God-fearing man | a quiet sedate natur...,isang libingan na may takot sa Diyos | isang t...
sober,drab.s.02,lacking brightness or color; dull,drab faded curtains | sober Puritan grey | chi...,kupas kupas na mga kurtina | matino Puritan gr...
well,well.v.01,"come up, as of a liquid",Tears well in her eyes | the currents well up,Maluha-luha sa kanyang mga mata | lumalakas an...
well,well.a.01,in good health especially after having suffere...,appears to be entirely well | the wound is nea...,mukhang ganap na maayos | ang sugat ay halos m...
well,good.s.13,resulting favorably,it's a good thing that I wasn't there | it is ...,buti na lang wala ako | buti naman nanatili ka...

## Save

In [6]:
res.to_csv('full_vocab_evaluation.csv', index=False)

In [7]:
res = res.rename(columns={'word': 'eng_word'}).set_index('eng_word')
res

,synset_id,gloss,eng_text,fil_text
eng_word,,,,
sober,grave.s.01,dignified and somber in manner or character an...,a grave God-fearing man | a quiet sedate natur...,isang libingan na may takot sa Diyos | isang t...
sober,drab.s.02,lacking brightness or color; dull,drab faded curtains | sober Puritan grey | chi...,kupas kupas na mga kurtina | matino Puritan gr...
well,well.v.01,"come up, as of a liquid",Tears well in her eyes | the currents well up,Maluha-luha sa kanyang mga mata | lumalakas an...
well,well.a.01,in good health especially after having suffere...,appears to be entirely well | the wound is nea...,mukhang ganap na maayos | ang sugat ay halos m...
well,good.s.13,resulting favorably,it's a good thing that I wasn't there | it is ...,buti na lang wala ako | buti naman nanatili ka...
...,...,...,...,...
narrow,narrow.v.01,make or become more narrow or restricted,The selection was narrowed | The road narrowed,Ang pagpili ay pinaliit | Ang daan ay makitid
narrow,narrow.a.01,not wide,a narrow bridge | a narrow line across the page,isang makipot na tulay | isang makitid na liny...
narrow,narrow-minded.a.02,lacking tolerance or flexibility or breadth of...,a brilliant but narrow-minded judge | narrow o...,isang makinang ngunit makitid ang isip na huko...
narrow,narrow.a.04,very limited in degree,won by a narrow margin | a narrow escape,napanalunan ng makitid na margin | isang makit...
narrow,minute.s.02,characterized by painstaking care and detailed...,a minute inspection of the grounds | a narrow ...,isang minutong inspeksyon sa mga bakuran | isa...

In [18]:
# join with df_valid
df_final = df_valid.join(res, on=["eng_word"], how="left").fillna('XX')
df_final

,fil_word,eng_word,backtranslation,synset_id,gloss,eng_text,fil_text
0,matino,sober,matino,grave.s.01,dignified and somber in manner or character an...,a grave God-fearing man | a quiet sedate natur...,isang libingan na may takot sa Diyos | isang t...
0,matino,sober,matino,drab.s.02,lacking brightness or color; dull,drab faded curtains | sober Puritan grey | chi...,kupas kupas na mga kurtina | matino Puritan gr...
1,maayos,well,mabuti,well.v.01,"come up, as of a liquid",Tears well in her eyes | the currents well up,Maluha-luha sa kanyang mga mata | lumalakas an...
1,maayos,well,mabuti,well.a.01,in good health especially after having suffere...,appears to be entirely well | the wound is nea...,mukhang ganap na maayos | ang sugat ay halos m...
1,maayos,well,mabuti,good.s.13,resulting favorably,it's a good thing that I wasn't there | it is ...,buti na lang wala ako | buti naman nanatili ka...
...,...,...,...,...,...,...,...
2594,makipot,narrow,makitid,narrow.a.04,very limited in degree,won by a narrow margin | a narrow escape,napanalunan ng makitid na margin | isang makit...
2594,makipot,narrow,makitid,minute.s.02,characterized by painstaking care and detailed...,a minute inspection of the grounds | a narrow ...,isang minutong inspeksyon sa mga bakuran | isa...
2595,tuod,tuod,tuod,XX,XX,XX,XX
2596,bumaling,turn around,umikot,XX,XX,XX,XX
2597,anas,anas,anas,XX,XX,XX,XX

In [19]:
df_final.to_csv('full_vocab_evaluation_final.csv', index=False)

## Archive

In [27]:
# If icoconvert na to word embeddings do this:
res.iloc[0]['translated_text'].split('|')

['Ang mga madla ay nagkalat ',
 ' Nagkalat ang mga bata sa lahat ng direksyon nang lumapit ang guro']

In [2]:
en_to_tl("world")

'mundo'

In [12]:
pd.read_csv("hot.csv")

,word,synset_id,gloss,example,translated_text
0,hot,hot.a.01,used of physical heat; having a high or higher...,hot stove | hot water | a hot August day | a h...,mainit na kalan | mainit na tubig | isang main...
1,hot,hot.s.02,characterized by violent and forceful activity...,the fighting became hot and heavy | a hot enga...,ang labanan ay naging mainit at mabigat | isan...
2,hot,hot.a.03,extended meanings; especially of psychological...,a hot temper | a hot topic | a hot new book | ...,isang mainit na init ng ulo | isang mainit na ...
3,hot,hot.s.05,sexually excited or exciting,was hot for her | hot pants,ay mainit para sa kanya | mainit na pantalon
4,hot,hot.s.06,recently stolen or smuggled,hot merchandise | a hot car,mainit na paninda | isang mainit na kotse
5,hot,blistering.s.03,very fast; capable of quick response and great...,a hot sports car | a blistering pace | got off...,isang mainit na sports car | isang mabilis na ...
6,hot,hot.s.09,producing a burning sensation on the taste nerves,hot salsa | jalapeno peppers are very hot,mainit na salsa | ang mga jalapeno peppers ay ...
7,hot,hot.s.10,performed or performing with unusually great s...,a hot drummer | he's hot tonight,isang mainit na drummer | ang hot niya ngayong...
8,hot,hot.s.11,very popular or successful,one of the hot young talents | cabbage patch d...,isa sa maiinit na batang talento | ang mga man...
9,hot,hot.s.12,very unpleasant or even dangerous,make it hot for him | in the hot seat | in hot...,gawin itong mainit para sa kanya | sa mainit n...
10,hot,hot.s.13,newest or most recent,news hot off the press | red-hot information,mainit na balita sa press | pulang impormasyon
11,hot,hot.s.14,having or bringing unusually good luck,hot at craps | the dice are hot tonight,mainit sa craps | mainit ang dice ngayong gabi
12,hot,hot.s.19,having or dealing with dangerously high levels...,hot fuel rods | a hot laboratory,mainit na fuel rods | isang mainit na laboratoryo
13,hot,hot.s.20,charged or energized with electricity,a hot wire | a live wire,isang mainit na kawad | isang live na kawad