# Generate Synsets
This notebook contains the code for Synset Induction Module

This takes the sense inventory as an input and outputs the wordnet i.e. sense inventory + synset id

In [3]:
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

In [4]:
def generate_synsets(sense_inventory):
    '''
        df_sense_embeddings: columns=['word', 'sense_id', 'example_sentences', 'pos', 'contextual_info', 'sense_embedding']
    '''
    df_synsets = sense_inventory.copy()
    sense_embeddings = list(sense_inventory['sense_embedding'])
    
    distance_threshold = 0.12
    af = AgglomerativeClustering(n_clusters=None, 
                                     affinity="cosine", 
                                     linkage="average", 
                                     distance_threshold=distance_threshold).fit(sense_embeddings)

    df_synsets['synset_id'] = af.labels_

    return df_synsets

In [5]:
sense_inventory = pd.read_pickle(f"sense_inventory.pkl")
sense_inventory

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,matino,matino_0,"[-0.010973115, 0.011298004, 0.035818312, -0.02...","[lang yung maayos at matino no?, ko yung matin...","{'twitter': {'2021': 8}, 'bandera': {'2013': 1...",NN
1,matino,matino_1,"[0.0036590695, 0.039770428, 0.04998947, -0.013...","[Mukha lang ako matino HAHAHAA, halatang wala ...",{'twitter': {'2021': 10}},FW
2,matino,matino_2,"[0.009747508, -0.00621662, 0.042053748, -0.033...","[ng pelikula. Maganda at matino., kasama sa pe...","{'bandera': {'2014': 2, '2018': 2, '2015': 1, ...",VB
3,maayos,maayos_0,"[0.03358061, 0.021531925, 0.03476327, -0.06221...","[maayos naman., sana, maayos pong lahat., nang...","{'bandera': {'2016': 1}, 'abante': {'2020': 1}...",JJ
4,maayos,maayos_1,"[0.014303654, -0.04044015, -0.016788391, 0.008...",[Tatasahan pa sa ensayo kung maayos na ang rec...,"{'abante': {'2021': 2}, 'balita': {'2016': 1, ...",JJ
5,maayos,maayos_2,"[0.032500096, 0.010635486, 0.011949124, 0.0240...",[sumulong nang maayos at walang hadlang ang ka...,"{'google_books': {'2019': 3, '2020': 3, '2018'...",JJ

In [6]:
wordnet = generate_synsets(sense_inventory)
wordnet

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos,synset_id
0,matino,matino_0,"[-0.010973115, 0.011298004, 0.035818312, -0.02...","[lang yung maayos at matino no?, ko yung matin...","{'twitter': {'2021': 8}, 'bandera': {'2013': 1...",NN,5
1,matino,matino_1,"[0.0036590695, 0.039770428, 0.04998947, -0.013...","[Mukha lang ako matino HAHAHAA, halatang wala ...",{'twitter': {'2021': 10}},FW,4
2,matino,matino_2,"[0.009747508, -0.00621662, 0.042053748, -0.033...","[ng pelikula. Maganda at matino., kasama sa pe...","{'bandera': {'2014': 2, '2018': 2, '2015': 1, ...",VB,2
3,maayos,maayos_0,"[0.03358061, 0.021531925, 0.03476327, -0.06221...","[maayos naman., sana, maayos pong lahat., nang...","{'bandera': {'2016': 1}, 'abante': {'2020': 1}...",JJ,3
4,maayos,maayos_1,"[0.014303654, -0.04044015, -0.016788391, 0.008...",[Tatasahan pa sa ensayo kung maayos na ang rec...,"{'abante': {'2021': 2}, 'balita': {'2016': 1, ...",JJ,1
5,maayos,maayos_2,"[0.032500096, 0.010635486, 0.011949124, 0.0240...",[sumulong nang maayos at walang hadlang ang ka...,"{'google_books': {'2019': 3, '2020': 3, '2018'...",JJ,0

## Save wordnet to file

In [ ]:
wordnet.to_csv(r"./filwordnet.csv", index=False) # To CSV
wordnet.to_pickle(r"./filwordnet.pkl", protocol=3) # To pickle