# Adding New Data (Append w/ Threshold)
Threshold = 0.4

In [1]:
import pandas as pd
from numpy import dot
from numpy.linalg import norm

In [2]:
def get_cosine(embedding_1, embedding_2):
    cos_sim = dot(embedding_1, embedding_2)/(norm(embedding_1)*norm(embedding_2))
    return cos_sim

def append_to_sense_inventory(new_inventory, old_inventory, threshold):
    counter = 0
    combined = old_inventory

    # add new senses
    for new_index, new_row in new_inventory.iterrows():
        high_sim = 0
        temp = 0

        #print(f"\nnew inventory {new_row['sense_id']}...")

        # time efficient slice
        temp_df = old_inventory.loc[old_inventory['word'] == new_row['word']]

        for old_index, old_row in temp_df.iterrows():
            if new_row['word'] == old_row['word']:
                temp = get_cosine(new_row['sense_embedding'], old_row['sense_embedding'])
                #print(f"old inventory {old_row['sense_id']} & new inventory {new_row['sense_id']} sim: {temp}")

            if temp >= high_sim:
                high_sim = temp
        # add sense if it has 'threshold' or lower as its highest similarity among the senses for that word
        #print(f"highest cosine similarity for {new_row['sense_id']} is {str(high_sim)}!")
        if high_sim <= threshold:
            print(f"ADDED: {new_row}")
            combined = combined.append(new_row, ignore_index=True)
            counter += 1

    # sort senses
    combined = combined.sort_values('word')

    # rename all sense id
    word = new_inventory.iloc[0]['word']
    id = 0

    for index, row in combined.iterrows():
        if word == row['word']:
            combined.loc[index, 'sense_id'] = word+'_'+str(id)
            id += 1
        else:
            word = row['word']
            id = 0
            combined.loc[index, 'sense_id'] = word+'_'+str(id)
            id += 1

    # reset index
    combined = combined.reset_index(drop=True)

    print(f"\n# of new senses is {str(counter)}!")
    return combined

## Load old and new sense inventories

In [3]:
old_inventory = pd.read_pickle("old_sense_inventory.pkl")
old_inventory

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,matino,matino_0,"[0.0039200424, 0.03125514, 0.044149794, -0.006...","[halatang wala ka ng gagawing matino HAHAHA, t...",{'twitter': {'2021': 10}},FW
1,matino,matino_1,"[0.014258224, -0.007326535, 0.04272052, -0.020...",[May mga magulang na matino ang isip at katawa...,"{'google_books': {'2018': 2}, 'twitter': {'202...",FW
2,matino,matino_2,"[0.0058104345, -0.0023813697, 0.04274508, -0.0...","[ng pelikula. Maganda at matino., kasama sa pe...","{'bandera': {'2014': 2, '2018': 2, '2021': 1, ...",VB
3,matino,matino_3,"[-0.0070238346, 0.014438677, 0.029195312, -0.0...","[akong sinabing matino., Duda ako sa matino!, ...","{'twitter': {'2021': 7}, 'bandera': {'2020': 1...",NN
4,maayos,maayos_0,"[0.010224508, 0.022195492, 0.058941443, -0.019...","[buti nalang nakasagot naman ng maayos., sana ...",{'twitter': {'2021': 10}},JJ
...,...,...,...,...,...,...
7078,tuod,tuod_1,"[-0.0010470327, 0.024433836, 0.05405687, -0.00...","[sabihin ay parang tuod., Ano ko tuod walang p...","{'balita': {'2017': 2}, 'twitter': {'2021': 6}...",FW
7079,bumaling,bumaling_0,"[-0.002633381, 0.05177117, 0.050690066, 0.0117...",[tingin sakin tas nung bumaling kay joms ay ng...,"{'twitter': {'2021': 7}, 'google_books': {'202...",VB
7080,bumaling,bumaling_1,"[0.029594356, 0.004925939, 0.008006528, 0.0289...","[puso ay ganap nang bumaling sa Diyos, ipinaki...","{'google_books': {'2019': 6, '2021': 4}}",NN
7081,anas,anas_0,"[-0.033860113, 0.0042065405, 0.05422906, 0.003...","[Ni graduate nadaw kog laag anas mama HAHAAHA,...",{'twitter': {'2021': 10}},NN
7082,anas,anas_1,"[0.0004388683, 0.017983321, 0.024509717, -0.00...","[Ka anas ga sarapan, ko, garu ko gurumuson ana...",{'twitter': {'2021': 4}},NN

In [4]:
new_inventory = pd.read_pickle("new_sense_inventory.pkl")
new_inventory

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,matino,matino_0,"[0.008358148, 0.034379065, 0.049863774, -0.010...","[pa nga kong nagagawang matino chudey huhu, ak...",{'twitter': {'2021': 10}},FW
1,matino,matino_1,"[-0.0004953388, 0.030745406, 0.01920554, -0.04...","[ng matino., kung hindi maayos at matino., Iil...","{'gma': {'2014': 1}, 'twitter': {'2021': 7}, '...",NN
2,matino,matino_2,"[-0.0037480977, 0.005228241, 0.04773019, -0.02...","[kala mo naman talaga matino, paligaw at ako y...",{'twitter': {'2021': 10}},FW
3,matino,matino_3,"[0.0103537, -0.014296556, 0.04497205, -0.02459...","[asawa ko, at lubhang matino at palaging magal...","{'google_books': {'2021': 1, '2018': 1}, 'bali...",NN
4,maayos,maayos_0,"[-0.0037643071, 0.019667514, 0.046444785, -0.0...","[nakahinga ako ng maayos, ket konti, ngyon edi...",{'twitter': {'2021': 10}},JJ
...,...,...,...,...,...,...
5721,tuod,tuod_1,"[-0.01778888, -0.038977534, 0.044225916, 0.019...","[ko lang gid no sa tuod lang, nang magbalik gu...",{'twitter': {'2021': 10}},NN
5722,bumaling,bumaling_0,"[0.0004811151, 0.033824384, 0.038164582, 0.000...",[naman sila sa pagbabangayan tsaka bumaling sa...,"{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB
5723,bumaling,bumaling_1,"[0.034572523, 0.014924703, 0.0027387284, 0.030...","[puso na ganap na bumaling sa Kanya, ito ang u...","{'google_books': {'2019': 2, '2021': 3}}",NN
5724,anas,anas_0,"[-0.016895104, 0.0038351163, 0.059679933, 0.00...",[bag ong victim daw niya anas chingching hahah...,{'twitter': {'2021': 5}},FW
5725,anas,anas_1,"[-0.047057528, 0.0045636757, 0.051740468, 0.00...",[maboang nako palangga tika daw anas chan huhu...,{'twitter': {'2021': 5}},FW

In [5]:
combined = append_to_sense_inventory(new_inventory=new_inventory,
                                           old_inventory=old_inventory,threshold=0.4) # 40% and below threshold
combined

ADDED: word                                                           trabaho
sense_id                                                     trabaho_2
sense_embedding      [0.0015942536, -0.045249186, -0.013914352, -0....
example_sentences    [kinalaman ang isyu sa trabaho o desisyon ng S...
contextual_info      {'gma': {'2012': 2}, 'balita': {'2017': 1, '20...
pos                                                                 NN
Name: 12, dtype: object
ADDED: word                                                           matatag
sense_id                                                     matatag_0
sense_embedding      [0.015831824, 0.024847796, -0.022892734, -0.01...
example_sentences    [sapat, maaasahan at matatag na power supply a...
contextual_info      {'balita': {'2016': 2, '2015': 1}, 'radyoinqui...
pos                                                                 JJ
Name: 23, dtype: object
ADDED: word                                                           matanda
sense_id                                                     matanda_2
sense_embedding      [0.031478412, -0.03225393, 0.015033635, 0.0024...
example_sentences    [Sa isang insidente, dalawang matanda ang nalu...
contextual_info      {'gma': {'2018': 1, '2013': 2}, 'balita': {'20...
pos                                                                 JJ
Name: 28, dtype: object
ADDED: word                                                             abala
sense_id                                                       abala_1
sense_embedding      [0.011410227, 0.005817835, -0.008558039, 0.030...
example_sentences    [ng gabi, habang abala umano sa pagtitinda ang...
contextual_info      {'balita': {'2016': 2, '2020': 1, '2018': 1}, ...
pos                                                                 NN
Name: 96, dtype: object
ADDED: word                                                            mainit
sense_id                                                      mainit_1
sense_embedding      [0.0138687985, -0.02657519, -0.026159227, -0.0...
example_sentences    [mainit ang tambalan nila sa backcourt ng Bata...
contextual_info      {'balita': {'2018': 1, '2017': 1, '2015': 1, '...
pos                                                                 JJ
Name: 99, dtype: object
ADDED: word                                                            mainit
sense_id                                                      mainit_3
sense_embedding      [-0.003422911, 0.012066663, -0.025187239, 0.04...
example_sentences    [Dahil dito, nagkaroon ng mainit na pagtatalo ...
contextual_info      {'gma': {'2018': 6, '2012': 1, '2021': 1, '201...
pos                                                                 JJ
Name: 101, dtype: object
ADDED: word                                                            maliit
sense_id                                                      maliit_1
sense_embedding      [0.00087596104, 0.013732761, -0.047468904, -0....
example_sentences    [sa labas ng PAR subalit maliit umano ang tyan...
contextual_info      {'bandera': {'2016': 2, '2019': 2}, 'gma': {'2...
pos                                                                 JJ
Name: 116, dtype: object
ADDED: word                                                            maliit
sense_id                                                      maliit_5
sense_embedding      [0.010744174, 0.015105253, -0.035435624, 0.038...
example_sentences    [hinihinalang shabu sa maliit na plastic sache...
contextual_info      {'balita': {'2017': 3, '2019': 1}, 'bandera': ...
pos                                                                 JJ
Name: 120, dtype: object
ADDED: word                                                            minsan
sense_id                                                      minsan_1
sense_embedding      [-0.031012684, -0.023140734, -0.04852222, -0.0...
example_sentences    [belt sa lightweight division, minsan na rin n...
contextual_info      {'gma': {'2008': 1}, 'balita': {'2016': 3, '20...
pos                                                                 RB
Name: 140, dtype: object
ADDED: word                                                            minsan
sense_id                                                      minsan_3
sense_embedding      [0.027762074, -0.034583144, -0.03403945, 0.034...
example_sentences    [mahina hanggang katamtaman na kung minsan ay ...
contextual_info                         {'radyoinquirer': {'2020': 5}}
pos                                                                 RB
Name: 142, dtype: object
ADDED: word                                                           tirahan
sense_id                                                     tirahan_2
sense_embedding      [-0.015823334, 0.010956938, -0.029329568, 0.02...
example_sentences    [Sumugod ang mga awtoidad sa tirahan ng suspek...
contextual_info      {'gma': {'2019': 2, '2020': 1, '2017': 1, '201...
pos                                                                 NN
Name: 146, dtype: object
ADDED: word                                                             bilis
sense_id                                                       bilis_4
sense_embedding      [0.05798749, -0.011951301, 0.073206894, -0.007...
example_sentences    [na sa 60 kph ang bilis ng MRT3 pagkatapos pal...
contextual_info      {'abante': {'2021': 1, '2020': 2}, 'radyoinqui...
pos                                                                 NN
Name: 296, dtype: object
ADDED: word                                                         hinaharap
sense_id                                                   hinaharap_1
sense_embedding      [-0.0024943433, -0.010737327, -0.007607913, -0...
example_sentences    [hinaharap na murder at subversion., hinaharap...
contextual_info      {'gma': {'2011': 1, '2018': 1, '2008': 1, '201...
pos                                                                 NN
Name: 298, dtype: object
ADDED: word                                                              tama
sense_id                                                        tama_2
sense_embedding      [0.084219076, 0.009974174, 0.0049414653, 0.011...
example_sentences    [ang hindi nagsuot o hindi tama ang pagkakasuo...
contextual_info      {'radyoinquirer': {'2020': 3}, 'abante': {'202...
pos                                                                 JJ
Name: 337, dtype: object
ADDED: word                                                              dami
sense_id                                                        dami_2
sense_embedding      [0.0017380919, -0.00056686846, -0.02043588, 0....
example_sentences    [hindi mabatid na dami ng hinihinalang shabu a...
contextual_info      {'balita': {'2017': 2, '2016': 2, '2018': 3}, ...
pos                                                                 NN
Name: 522, dtype: object
ADDED: word                                                             ibaba
sense_id                                                       ibaba_1
sense_embedding      [0.018385066, 0.028957922, 0.014856746, -0.050...
example_sentences    [ang industry ng baboy at ibaba ang presyo nit...
contextual_info      {'abante': {'2021': 2}, 'radyoinquirer': {'202...
pos                                                                 JJ
Name: 542, dtype: object
ADDED: word                                                             putol
sense_id                                                       putol_1
sense_embedding      [0.022260806, -0.006130127, -0.005138039, 0.03...
example_sentences    [taga ang katawan at putol pa ang dalawang paa...
contextual_info      {'gma': {'2019': 2, '2016': 2, '2017': 2, '201...
pos                                                                 NN
Name: 592, dtype: object
ADDED: word                                                           kahapon
sense_id                                                     kahapon_1
sense_embedding      [0.01844046, -0.04585949, -0.014785218, 0.0172...
example_sentences    [Davis Cup tie simula kahapon, sa Valle Verde ...
contextual_info      {'balita': {'2016': 2, '2018': 4, '2020': 1, '...
pos                                                                 FW
Name: 614, dtype: object
ADDED: word                                                           habulin
sense_id                                                     habulin_2
sense_embedding      [-0.012562494, 0.009140408, -0.01104717, 0.037...
example_sentences    [Tinangka ring habulin ng biktima ang mga susp...
contextual_info      {'gma': {'2021': 2, '2018': 3, '2014': 1, '201...
pos                                                                 VB
Name: 630, dtype: object
ADDED: word                                                            itulak
sense_id                                                      itulak_1
sense_embedding      [0.03247514, -0.03035942, 0.023089979, 0.00823...
example_sentences    [natitira sa ikatlong yugto upang itulak ang C...
contextual_info      {'balita': {'2016': 2, '2015': 4, '2014': 2}, ...
pos                                                                 VB
Name: 647, dtype: object

ADDED: word                                                      samantalahin
sense_id                                                samantalahin_1
sense_embedding      [0.009562215, -0.02592529, -0.023388721, -0.01...
example_sentences    [Reyes na dapat samantalahin ng mga koponan an...
contextual_info      {'balita': {'2018': 2, '2016': 1, '2017': 1}, ...
pos                                                                 VB
Name: 731, dtype: object
ADDED: word                                                           gumamit
sense_id                                                     gumamit_2
sense_embedding      [0.084563605, 0.007306882, -0.008592385, -0.01...
example_sentences    [) ang mga motorista na gumamit ng mga alterna...
contextual_info      {'balita': {'2018': 1, '2015': 2, '2016': 2, '...
pos                                                                 VB
Name: 735, dtype: object
ADDED: word                                                       pangasiwaan
sense_id                                                 pangasiwaan_1
sense_embedding      [-0.013828057, 0.026782375, -0.0011269782, -0....
example_sentences    [Aquino III para personal na pangasiwaan ang o...
contextual_info      {'gma': {'2013': 1, '2012': 1}, 'balita': {'20...
pos                                                                 VB
Name: 744, dtype: object
ADDED: word                                                          matamlay
sense_id                                                    matamlay_1
sense_embedding      [0.031798173, -0.05177498, 0.014028832, 0.0144...
example_sentences    [Nagsimula sila sa laro na matamlay, scoreless...
contextual_info      {'balita': {'2014': 1, '2016': 2, '2019': 1}, ...
pos                                                                 NN
Name: 830, dtype: object
ADDED: word                                                              hepe
sense_id                                                        hepe_1
sense_embedding      [0.0048301225, 0.026625985, -0.019446012, 0.02...
example_sentences    [Ayon kay Grfton Medina, hepe ng BI port opera...
contextual_info              {'radyoinquirer': {'2019': 4, '2021': 1}}
pos                                                                 NN
Name: 837, dtype: object
ADDED: word                                                           malinaw
sense_id                                                     malinaw_0
sense_embedding      [0.011936447, 0.018807476, -0.03490808, 0.0106...
example_sentences    [Hindi pa malinaw kung ano ang motibo sa, Hind...
contextual_info      {'gma': {'2020': 1, '2018': 2, '2017': 2, '201...
pos                                                                 JJ
Name: 962, dtype: object
ADDED: word                                                         operasyon
sense_id                                                   operasyon_2
sense_embedding      [0.015218745, 0.019381637, 0.017739575, -0.016...
example_sentences    [pamilya na maaapektuhan ng mga operasyon ng m...
contextual_info      {'balita': {'2019': 1, '2018': 1, '2015': 1}, ...
pos                                                                 NN
Name: 1096, dtype: object
ADDED: word                                                            maging
sense_id                                                      maging_0
sense_embedding      [0.028257683, 0.049410157, 0.0060002347, -0.05...
example_sentences    [Ambag bago maging busy ulit, | 383, Ambag bag...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 VB
Name: 1118, dtype: object
ADDED: word                                                             lakas
sense_id                                                       lakas_2
sense_embedding      [0.03617269, -0.031627767, 0.020475084, 0.0116...
example_sentences    [Nuggets, ngunit sapat ang lakas ng Golden Sta...
contextual_info      {'balita': {'2017': 2, '2016': 1, '2018': 1}, ...
pos                                                                 NN
Name: 1183, dtype: object
ADDED: word                                                        pagtatapos
sense_id                                                  pagtatapos_1
sense_embedding      [0.026694527, -0.025863608, 0.013285248, 0.010...
example_sentences    [18-15 sa pagtatapos ng unang quarter, subalit...
contextual_info      {'balita': {'2014': 3, '2017': 1, '2019': 2, '...
pos                                                                 NN
Name: 1241, dtype: object
ADDED: word                                                           magsara
sense_id                                                     magsara_0
sense_embedding      [0.01721034, -0.03106897, 0.062746525, 0.00608...
example_sentences    [bago magsara ang 16th Congress, naaprubahan n...
contextual_info      {'bandera': {'2016': 1, '2019': 1}, 'radyoinqu...
pos                                                                 VB
Name: 1243, dtype: object
ADDED: word                                                           dahilan
sense_id                                                     dahilan_3
sense_embedding      [-0.0018747577, -0.016644804, -0.017624099, 0....
example_sentences    [pinalo ng martilyo na dahilan ng pagkamatay n...
contextual_info      {'gma': {'2019': 1, '2015': 2, '2013': 2, '201...
pos                                                                 NN
Name: 1265, dtype: object
ADDED: word                                                             bayan
sense_id                                                       bayan_1
sense_embedding      [0.02015094, -0.045125797, 0.020351682, 0.0213...
example_sentences    [8 kilometers southeast ng bayan ng Sarangani,...
contextual_info                        {'radyoinquirer': {'2020': 10}}
pos                                                                 NN
Name: 1324, dtype: object
ADDED: word                                                             marka
sense_id                                                       marka_1
sense_embedding      [0.034445412, 0.020230353, 0.07163824, -0.0151...
example_sentences    [waxa ku jiro cafimaad marka qof walbo inta ay...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 FW
Name: 1367, dtype: object
ADDED: word                                                             bahid
sense_id                                                       bahid_1
sense_embedding      [-0.02136558, -0.025572803, -0.042581014, -0.0...
example_sentences    [Nananatiling walang bahid ng talo ang tubong ...
contextual_info      {'balita': {'2016': 1, '2015': 1, '2017': 1, '...
pos                                                                 NN
Name: 1370, dtype: object
ADDED: word                                                           basehan
sense_id                                                     basehan_3
sense_embedding      [0.019707035, -0.029166382, -0.042659983, 0.00...
example_sentences    [gagamiting basehan para sa National tryouts s...
contextual_info          {'balita': {'2019': 2, '2018': 1, '2014': 2}}
pos                                                                 NN
Name: 1380, dtype: object
ADDED: word                                                         humantong
sense_id                                                   humantong_1
sense_embedding      [0.023697848, 0.025958974, -0.0018228572, -0.0...
example_sentences    [presyon at baka ito ay humantong sa stroke o ...
contextual_info      {'bandera': {'2019': 1}, 'balita': {'2021': 1,...
pos                                                                 VB
Name: 1387, dtype: object
ADDED: word                                                             stops
sense_id                                                       stops_1
sense_embedding      [0.006894802, -0.039658487, 0.008384391, -0.02...
example_sentences    [and the buck stops there,  pagdidiin ng korte...
contextual_info      {'balita': {'2021': 1, '2015': 1, '2017': 1, '...
pos                                                                 NN
Name: 1457, dtype: object

ADDED: word                                                             siyam
sense_id                                                       siyam_2
sense_embedding      [-0.038666308, -0.047888495, 0.031757634, 0.03...
example_sentences    [ng lindol ay siyam na kilometro sa kanluran n...
contextual_info      {'bandera': {'2019': 1, '2020': 1}, 'radyoinqu...
pos                                                                 JJ
Name: 1467, dtype: object
ADDED: word                                                             siyam
sense_id                                                       siyam_3
sense_embedding      [0.017925331, 0.0019772165, -0.01171122, 0.036...
example_sentences    [Nakuha sa kanila ang siyam na sachet ng hinih...
contextual_info      {'gma': {'2018': 2, '2021': 1}, 'bandera': {'2...
pos                                                                 JJ
Name: 1468, dtype: object
ADDED: word                                                              anim
sense_id                                                        anim_2
sense_embedding      [-0.0008810415, 0.010071407, -0.0021695779, 0....
example_sentences    [makuha ang lima sa anim na winning numbers., ...
contextual_info      {'abante': {'2021': 2, '2020': 2}, 'bandera': ...
pos                                                                 JJ
Name: 1485, dtype: object
ADDED: word                                                          mahigpit
sense_id                                                    mahigpit_2
sense_embedding      [0.0063478174, -0.05634446, -0.027967531, 0.00...
example_sentences    [kabuuang siyam na round sa mahigpit na depens...
contextual_info      {'balita': {'2015': 2, '2016': 2, '2017': 2, '...
pos                                                                 JJ
Name: 1628, dtype: object
ADDED: word                                                            malayo
sense_id                                                      malayo_4
sense_embedding      [0.011517996, 0.010394678, -0.029004227, -0.00...
example_sentences    [Bagamat malayo pa sa kalupaan ng bansa,, Sama...
contextual_info      {'radyoinquirer': {'2021': 1, '2020': 1}, 'bal...
pos                                                                 JJ
Name: 1667, dtype: object
ADDED: word                                                            malayo
sense_id                                                      malayo_5
sense_embedding      [0.023178222, -0.01146186, -0.042546336, -0.03...
example_sentences    [sa 9. 7 porsyento na naitala sa survey noong ...
contextual_info      {'bandera': {'2018': 1, '2016': 1}, 'gma': {'2...
pos                                                                 JJ
Name: 1668, dtype: object
ADDED: word                                                              lead
sense_id                                                        lead_1
sense_embedding      [0.030192804, -0.028964493, 0.03149678, 0.0080...
example_sentences    [Maagang namuhunan ng 26-12 lead pagkatapos ng...
contextual_info      {'abante': {'2020': 2, '2021': 5}, 'balita': {...
pos                                                                 FW
Name: 1762, dtype: object
ADDED: word                                                             litro
sense_id                                                       litro_0
sense_embedding      [0.0026997551, 0.031315506, 0.0030489303, 0.00...
example_sentences    [ko dahil sa milktea isang litro ba naman bawa...
contextual_info                              {'twitter': {'2021': 10}}
pos                                                                 NN
Name: 1806, dtype: object
ADDED: word                                                           bagaman
sense_id                                                     bagaman_0
sense_embedding      [0.0022848235, -0.03499606, -0.026561012, 0.00...
example_sentences    [nakatapat na Legendari Japan Warriors bagaman...
contextual_info      {'balita': {'2015': 1, '2016': 1}, 'abante': {...
pos                                                                 CC
Name: 1939, dtype: object
ADDED: word                                                              taas
sense_id                                                        taas_1
sense_embedding      [0.055990182, -0.016890448, -0.028906116, 0.03...
example_sentences    [nasa edad 30-35, may taas na 5'3, at nakasuot...
contextual_info      {'balita': {'2014': 1, '2016': 3, '2017': 2}, ...
pos                                                                 NN
Name: 1987, dtype: object
ADDED: word                                                             punto
sense_id                                                       punto_1
sense_embedding      [0.012364621, -0.019505465, 0.03214187, 0.0024...
example_sentences    ['Yan ang punto ni House Deputy Speaker Lito, ...
contextual_info      {'abante': {'2021': 1}, 'balita': {'2017': 1},...
pos                                                                 NN
Name: 2125, dtype: object
ADDED: word                                                         pagkawala
sense_id                                                   pagkawala_1
sense_embedding      [0.00876689, -0.05488486, -0.006897903, 0.0150...
example_sentences    [Subalit, ang pagkawala ng dalawang star playe...
contextual_info      {'balita': {'2016': 4, '2018': 2, '2017': 1, '...
pos                                                                 NN
Name: 2173, dtype: object
ADDED: word                                                         pagkawala
sense_id                                                   pagkawala_3
sense_embedding      [0.028420892, 0.014611912, -0.03157745, -0.026...
example_sentences    [ng pagkawala ng kuryente., mahina hanggang sa...
contextual_info      {'bandera': {'2015': 1, '2019': 2}, 'radyoinqu...
pos                                                                 NN
Name: 2175, dtype: object
ADDED: word                                                            hingil
sense_id                                                      hingil_1
sense_embedding      [-0.012593998, -0.0031299652, -0.026064536, 0....
example_sentences    [ng biktima hingil sa nasabing pangyayari, Nag...
contextual_info      {'radyoinquirer': {'2018': 1}, 'abante': {'202...
pos                                                                 NN
Name: 2180, dtype: object
ADDED: word                                                            bahagi
sense_id                                                      bahagi_1
sense_embedding      [0.01823965, -0.019106712, 0.017066214, 0.0147...
example_sentences    [Rose ang paghahabol sa huling bahagi ng fourt...
contextual_info      {'balita': {'2014': 1, '2018': 1, '2015': 1}, ...
pos                                                                 NN
Name: 2292, dtype: object
ADDED: word                                                          dibisyon
sense_id                                                    dibisyon_0
sense_embedding      [0.0045453184, -0.012968051, -0.030721042, -0....
example_sentences    [reorganisasyon sa tatlong dibisyon ng korte.,...
contextual_info      {'balita': {'2018': 2, '2014': 2, '2015': 1, '...
pos                                                                 NN
Name: 2299, dtype: object
ADDED: word                                                            bilyon
sense_id                                                      bilyon_0
sense_embedding      [0.009660244, 0.007211998, -0.014294756, 0.000...
example_sentences    [Meralco na umabot sa P7 bilyon mula sa singil...
contextual_info      {'gma': {'2010': 2}, 'abante': {'2020': 2}, 'b...
pos                                                                 NN
Name: 2306, dtype: object
ADDED: word                                                           mabilis
sense_id                                                     mabilis_4
sense_embedding      [-0.002048655, -0.022356402, 0.01749066, -0.02...
example_sentences    [kanilang kliyente para sa mabilis na paglilit...
contextual_info      {'gma': {'2013': 1, '2012': 2}, 'balita': {'20...
pos                                                                 JJ
Name: 2413, dtype: object
ADDED: word                                                           bahagya
sense_id                                                     bahagya_0
sense_embedding      [0.021470474, -0.012912969, -0.038174555, 0.00...
example_sentences    [Bagamat bahagya nang humina ang Nina sa, baha...
contextual_info      {'balita': {'2016': 1, '2017': 1}, 'gma': {'20...
pos                                                                 RB
Name: 2416, dtype: object

ADDED: word                                                              hita
sense_id                                                        hita_1
sense_embedding      [0.038610198, -0.026035508, 0.010592712, 0.008...
example_sentences    [iniindang pamamaga sa kanang hita, sa naisala...
contextual_info          {'balita': {'2019': 2, '2017': 2, '2016': 1}}
pos                                                                 NN
Name: 2576, dtype: object
ADDED: word                                                             bibig
sense_id                                                       bibig_2
sense_embedding      [-0.02053077, -0.037800785, 0.03784222, 0.0106...
example_sentences    [Tani gihipos ko na lang bibig ko, budlay na g...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 NN
Name: 2588, dtype: object
ADDED: word                                                              test
sense_id                                                        test_3
sense_embedding      [0.023258906, 0.018675854, -0.0068407194, -0.0...
example_sentences    [na ballistic missile test ng ermitanyong bans...
contextual_info          {'balita': {'2016': 2, '2017': 2, '2018': 1}}
pos                                                                 FW
Name: 2828, dtype: object
ADDED: word                                                             tiyak
sense_id                                                       tiyak_1
sense_embedding      [0.01943089, 0.012194642, -0.025195116, -0.017...
example_sentences    [Hindi pa rin tiyak kung ano ang sanhi ng, mat...
contextual_info      {'radyoinquirer': {'2020': 1, '2019': 1}, 'gma...
pos                                                                 RB
Name: 2874, dtype: object
ADDED: word                                                            ibenta
sense_id                                                      ibenta_1
sense_embedding      [0.019937111, 0.031992935, -0.012711799, 0.001...
example_sentences    [COVID-19 vaccine para iligal na ibenta sa mur...
contextual_info      {'twitter': {'2021': 2}, 'abante': {'2021': 1}...
pos                                                                 VB
Name: 2894, dtype: object
ADDED: word                                                            kawala
sense_id                                                      kawala_2
sense_embedding      [-0.006947526, 0.0057384586, -0.012816968, 0.0...
example_sentences    [Wala nang kawala ang lalaking inaresto dahil ...
contextual_info      {'abante': {'2021': 1, '2020': 1}, 'gma': {'20...
pos                                                                 VB
Name: 2912, dtype: object
ADDED: word                                                         kapitolyo
sense_id                                                   kapitolyo_1
sense_embedding      [-0.015291083, 0.036037404, -0.012988697, -0.0...
example_sentences    [sa kamay ng ang kapitolyo ng Afghanistan, Kab...
contextual_info      {'twitter': {'2021': 1}, 'radyoinquirer': {'20...
pos                                                                 NN
Name: 2998, dtype: object
ADDED: word                                                             tulin
sense_id                                                       tulin_1
sense_embedding      [-0.004910155, -0.021724813, -0.018295314, 0.0...
example_sentences    [ni Best Regards ang tulin nito sa largahan up...
contextual_info         {'abante': {'2021': 4}, 'balita': {'2016': 1}}
pos                                                                 NN
Name: 3063, dtype: object
ADDED: word                                                            tingin
sense_id                                                      tingin_2
sense_embedding      [0.009126258, -0.008128941, -0.009837096, 0.02...
example_sentences    [Dahil umano sa masamang tingin, kulang sampun...
contextual_info      {'balita': {'2017': 1, '2021': 1, '2014': 1}, ...
pos                                                                 NN
Name: 3114, dtype: object
ADDED: word                                                          kaalaman
sense_id                                                    kaalaman_2
sense_embedding      [0.0015862158, 0.003608051, 0.007014948, 0.028...
example_sentences    [Lingid sa kanyang kaalaman, nagpatulong pala ...
contextual_info      {'gma': {'2019': 1, '2008': 1, '2015': 1}, 'ba...
pos                                                                 NN
Name: 3234, dtype: object
ADDED: word                                                              agad
sense_id                                                        agad_1
sense_embedding      [-0.0014260777, 0.010654891, -0.00933747, 0.06...
example_sentences    [Dahil dito agad na rumesponde ang mga pulis, ...
contextual_info      {'radyoinquirer': {'2019': 3, '2018': 2}, 'aba...
pos                                                                 RB
Name: 3240, dtype: object
ADDED: word                                                              agad
sense_id                                                        agad_4
sense_embedding      [-0.015837502, -0.035243828, 0.01112304, 0.044...
example_sentences    [na lumaki ang apoy at agad ding naapula alas ...
contextual_info      {'radyoinquirer': {'2019': 3}, 'gma': {'2018':...
pos                                                                 RB
Name: 3243, dtype: object
ADDED: word                                                               iba
sense_id                                                         iba_0
sense_embedding      [0.023499222, 0.0021376128, -0.019745667, 0.03...
example_sentences    [ang naaresto kasama ang walong iba pa sa magk...
contextual_info      {'bandera': {'2020': 1}, 'radyoinquirer': {'20...
pos                                                                 PR
Name: 3325, dtype: object
ADDED: word                                                               iba
sense_id                                                         iba_1
sense_embedding      [0.047395386, -0.019636583, 0.023700058, -0.00...
example_sentences    [ng bruised ribs. Sa iba pang laro, natuldukan...
contextual_info      {'balita': {'2018': 1, '2016': 1, '2021': 1, '...
pos                                                                 PR
Name: 3326, dtype: object
ADDED: word                                                                at
sense_id                                                          at_0
sense_embedding      [0.084930584, 0.07343273, -0.0015760798, -0.00...
example_sentences    [- Suyash Hospital 1, Ahilyabai Holkar Road Ma...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 CC
Name: 3360, dtype: object
ADDED: word                                                                at
sense_id                                                          at_3
sense_embedding      [0.03525982, -0.014211508, -0.029615084, 0.003...
example_sentences    [ang yellow warning sa Albay at Camarines Sur....
contextual_info      {'radyoinquirer': {'2020': 4}, 'balita': {'201...
pos                                                                 CC
Name: 3363, dtype: object
ADDED: word                                                                at
sense_id                                                          at_5
sense_embedding      [-0.002865851, 0.009466458, -0.012852175, 0.03...
example_sentences    [ang dalawang sakay ng kotse at nakipagpalitan...
contextual_info      {'gma': {'2020': 1, '2016': 2, '2014': 1, '201...
pos                                                                 CC
Name: 3365, dtype: object
ADDED: word                                                               cap
sense_id                                                         cap_1
sense_embedding      [0.02700894, 0.023484455, -0.031796485, 0.0661...
example_sentences    [bull cap, itim na jacket at puting T-shirt. H...
contextual_info      {'balita': {'2016': 1, '2017': 1}, 'radyoinqui...
pos                                                                 FW
Name: 3403, dtype: object
ADDED: word                                                              lalo
sense_id                                                        lalo_3
sense_embedding      [0.015718933, -0.011927663, -0.044827394, -0.0...
example_sentences    [ang pagbuhos ng ulan lalo na sa Luzon dulot n...
contextual_info      {'gma': {'2009': 1}, 'bandera': {'2018': 1}, '...
pos                                                                 JJ
Name: 3518, dtype: object
ADDED: word                                                              araw
sense_id                                                        araw_0
sense_embedding      [-0.013693008, -0.052891124, 0.035715573, 0.03...
example_sentences    [Alas 3:07 naman ng madaling araw ng tumama ag...
contextual_info      {'radyoinquirer': {'2020': 1, '2019': 2}, 'ban...
pos                                                                 NN
Name: 3564, dtype: object
ADDED: word                                                              araw
sense_id                                                        araw_1
sense_embedding      [-0.0037262668, -0.052678585, -0.02416498, 0.0...
example_sentences    [Pagkaraan ng tatlong araw na kompetisyon, nag...
contextual_info      {'balita': {'2014': 2, '2019': 2, '2016': 3}, ...
pos                                                                 NN
Name: 3565, dtype: object

ADDED: word                                                             buwan
sense_id                                                       buwan_3
sense_embedding      [0.015549396, -0.03750023, -0.031096313, 0.011...
example_sentences    [sa finals ng kompetisyon sa buwan ng Abril, s...
contextual_info      {'radyoinquirer': {'2018': 2}, 'balita': {'201...
pos                                                                 NN
Name: 3816, dtype: object
ADDED: word                                                              bula
sense_id                                                        bula_3
sense_embedding      [0.01297381, 0.057879508, 0.012686171, -0.0693...
example_sentences    [210909 bula bath ni Para mawala yung kaba, 21...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 NN
Name: 3895, dtype: object
ADDED: word                                                          ika-anim
sense_id                                                    ika-anim_0
sense_embedding      [-0.009260535, 0.004184938, 0.020075971, 0.038...
example_sentences    [na umano'y tumalon mula sa ika-anim na palapa...
contextual_info      {'abante': {'2020': 1}, 'balita': {'2021': 2},...
pos                                                                 NN
Name: 3953, dtype: object
ADDED: word                                                       pagkakataon
sense_id                                                 pagkakataon_1
sense_embedding      [-0.022956975, 0.025392089, 0.001567749, 0.059...
example_sentences    [Nang makakuha ng pagkakataon, tumakas na siya...
contextual_info      {'gma': {'2017': 1, '2018': 1, '2019': 1, '201...
pos                                                                 NN
Name: 4247, dtype: object
ADDED: word                                                              huli
sense_id                                                        huli_3
sense_embedding      [0.0053016557, -0.018342298, -0.019399485, 0.0...
example_sentences    [Samantala, huli namang namataan ang Typhoon Q...
contextual_info      {'radyoinquirer': {'2020': 1, '2018': 1}, 'aba...
pos                                                                 RB
Name: 4416, dtype: object
ADDED: word                                                           manipis
sense_id                                                     manipis_1
sense_embedding      [0.016453274, 0.020183995, -0.03152276, -0.030...
example_sentences    [ng Department of Energy na manipis ang reserb...
contextual_info      {'abscbn': {'2021': 1}, 'balita': {'2017': 2},...
pos                                                                 JJ
Name: 4419, dtype: object
ADDED: word                                                              puno
sense_id                                                        puno_3
sense_embedding      [0.0035556622, -0.052871216, -0.031490527, 0.0...
example_sentences    [puno at tuktok ng team standings sa larong in...
contextual_info      {'balita': {'2018': 1, '2014': 1, '2017': 1, '...
pos                                                                 NN
Name: 4425, dtype: object
ADDED: word                                                        kamag-anak
sense_id                                                  kamag-anak_1
sense_embedding      [0.0076707574, -0.0010217011, 0.037314467, 0.0...
example_sentences    [ayon sa mga kamag-anak ng mga pasaherong nasa...
contextual_info      {'gma': {'2008': 2, '2014': 1}, 'balita': {'20...
pos                                                                 NN
Name: 4480, dtype: object
ADDED: word                                                              gabi
sense_id                                                        gabi_0
sense_embedding      [0.010805586, -0.0067409663, -0.0020734083, 0....
example_sentences    [match ganap na 6:00 ng gabi pagkatapos ng men...
contextual_info      {'balita': {'2017': 2, '2018': 1, '2019': 3, '...
pos                                                                 RB
Name: 4484, dtype: object
ADDED: word                                                             buhay
sense_id                                                       buhay_2
sense_embedding      [0.0002809957, -0.016698923, -0.008919543, 0.0...
example_sentences    [bata pero binawian na ng buhay., tuluyan din ...
contextual_info      {'gma': {'2019': 4, '2017': 1, '2018': 1, '201...
pos                                                                 NN
Name: 4506, dtype: object
ADDED: word                                                             bomba
sense_id                                                       bomba_0
sense_embedding      [0.014046165, -0.013742939, 0.02990396, 0.0029...
example_sentences    [game sa pagbuhos ng 7-0 bomba tampok ang lay-...
contextual_info                     {'abante': {'2021': 4, '2020': 1}}
pos                                                                 NN
Name: 4563, dtype: object
ADDED: word                                                             babae
sense_id                                                       babae_2
sense_embedding      [0.0020644898, -0.023668405, -0.039254226, 0.0...
example_sentences    [babae ) atletang Pinoy ang sasabak sa 530 eve...
contextual_info      {'balita': {'2019': 1, '2016': 2, '2018': 1, '...
pos                                                                 NN
Name: 4868, dtype: object
ADDED: word                                                         kagubatan
sense_id                                                   kagubatan_0
sense_embedding      [0.0060229045, 0.06102525, -0.026525795, -0.02...
example_sentences    [Join nakayo dm nyo lang kagubatan ofc | One H...
contextual_info                               {'twitter': {'2021': 5}}
pos                                                                 NN
Name: 4972, dtype: object
ADDED: word                                                           reverse
sense_id                                                     reverse_1
sense_embedding      [0.0607507, 0.031569324, -0.007647769, 0.01119...
example_sentences    [mass testing by RT-PCR ( reverse transcriptio...
contextual_info      {'bandera': {'2020': 1}, 'balita': {'2021': 2}...
pos                                                                 FW
Name: 5167, dtype: object
ADDED: word                                                          gasolina
sense_id                                                    gasolina_0
sense_embedding      [0.0039718403, -0.006266872, 0.02932989, 0.006...
example_sentences    [nang ginawang pagbuhos umano ng gasolina sa k...
contextual_info      {'gma': {'2017': 2, '2020': 1, '2018': 1}, 'ba...
pos                                                                 NN
Name: 5461, dtype: object
ADDED: word                                                            babala
sense_id                                                      babala_1
sense_embedding      [0.022223428, 0.015825603, 0.012922945, 0.0130...
example_sentences    [Secretary Rosalinda Baldoz kaugnay sa babala ...
contextual_info      {'balita': {'2016': 2, '2014': 2}, 'radyoinqui...
pos                                                                 NN
Name: 5647, dtype: object

# of new senses is 94!

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD

In [6]:
combined

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD

In [8]:
combined.to_csv("updated_sense_inventory.csv", index=False)
combined.to_pickle("updated_sense_inventory.pkl", protocol=3)