# Converts contextual info format of NLP to NetSci

Note: This is a band-aid solution. Future work should change the contextual_info format in the NLP code para hindi na to kailangan i-run.

In [ ]:
import pandas as pd
import json

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
NLP_WORDNET_PATH = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/filwordnet.pkl"

In [71]:
data = pd.read_pickle(NLP_WORDNET_PATH)
data

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'balita': {'2016': 2, '2020': 1, '2018': 1}, ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'twitter': {'2021': 8}, 'radyoinquirer': {'20...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'gma': {'2014': 1, '2017': 1}, 'radyoinquirer...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'balita': {'2016': 1, '2014': 1, '2019': 2, '...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'twitter': {'2021': 3}, 'balita': {'2015': 1,...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'twitter': {'2021': 6}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'twitter': {'2021': 10}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'twitter': {'2021': 10}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'twitter': {'2021': 10}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'twitter': {'2021': 4}},CD

In [52]:
def get_source_type(source):
    if source in ['twitter', 'youtube']:
        return 'social_media'
    elif source in ['abante', 'abscbn', 'balita', 'bandera', 'gma', 'mb', 'philstar','radyoinquirer']:
        return 'news_sites'
    elif source in ['bible', 'google_books', '100year', 'gutenberg']:
        return 'books'
    elif source in ['reddit']:
        return 'online_forums'
    elif source in ['wikipedia']:
        return 'online_encyclopedia'

In [82]:
# Initialize list
contextual_info = []

# Convert to NetSci format
for context in data['contextual_info']:
    json_context = context
    contextual_info_entry = {}
    
    for source in json_context:
        source_type = get_source_type(source)

        if source_type not in contextual_info_entry:
            contextual_info_entry[source_type] = {}
            
        for year_str in json_context[source]:

            if source not in contextual_info_entry[source_type]:
                contextual_info_entry[source_type][source] = {}
                
            counts = json_context[source][year_str]
            contextual_info_entry[source_type][source][year_str] = counts
    
    contextual_info.append(contextual_info_entry)

# Update dataframe
data['contextual_info'] = contextual_info

In [84]:
data

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'news_sites': {'balita': {'2016': 2, '2020': ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'social_media': {'twitter': {'2021': 8}}, 'ne...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'news_sites': {'gma': {'2014': 1, '2017': 1},...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'news_sites': {'balita': {'2016': 1, '2014': ...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'social_media': {'twitter': {'2021': 3}}, 'ne...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'social_media': {'twitter': {'2021': 6}}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'social_media': {'twitter': {'2021': 10}}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'social_media': {'twitter': {'2021': 10}}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'social_media': {'twitter': {'2021': 10}}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'social_media': {'twitter': {'2021': 4}}},CD

In [85]:
data.to_pickle("/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/modified_wordnet.pkl", protocol=3)